### ISSUE TITLE
[prometheus-kube-stack] etcdHighNumberOfLeaderChanges inconsistent

### ISSUE THREAD

**Issue by jensbaitingerbosch** [prometheus-community/helm-charts#1000]
**Describe the bug**

The definition of the alert `etcdHighNumberOfLeaderChanges` in the default rules seams to be wrong. 

The [expression](
https://github.com/prometheus-community/helm-charts/blob/18de98e1638da09ee30dfaf8b486a71f207fc116/charts/kube-prometheus-stack/templates/prometheus/rules/etcd.yaml#L50) uses the function `rate()` which returns the events per second, I guess that 3 leader changes per second is not the indended threshold. The function `increate()` would fit better here.

Additionally the message is inconsistent with the expression. The message says `... {{ $value }} leader changes within the last hour.`, better would be `{{ $value }} leader changes within the last 15 min.` (similar to the expression)

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml#L2-L4
