### ISSUE TITLE
[prometheus-pushgateway] Blindly settings clusterIP will cause chart upgrades to fail

### ISSUE THREAD

**Issue by vbergbauer** [prometheus-community/helm-charts#1004]
Commit  [f183c48](https://github.com/prometheus-community/helm-charts/commit/f183c48e91bc99e025e11f5a708d64615b4799ae) causes a serious problem because explicitly setting the clusterIP will effectively prevent any upgrade:

```
# Success
$ helm install pg prometheus-pushgateway

# Failure
$ helm upgrade pg prometheus-pushgateway --set replicaCount=2
Error: UPGRADE FAILED: cannot patch "pg-prometheus-pushgateway" with kind Service: Service "pg-prometheus-pushgateway" is invalid: spec.clusterIPs[0]: Invalid value: []string(nil): primary clusterIP can not be unset
```

You need to test for the value of clusterIP in the service.yaml template to handle the common case where clusterIP is not explicitly set:
```
{{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
{{- end }}
```

**Comment by elsbrock** [comment]
https://github.com/prometheus-community/helm-charts/pull/954
