### ISSUE TITLE
[kube-prometheus-stack] upgrade ghostunnel to ARM64 compliant image?

### ISSUE THREAD

**Issue by bradwood** [prometheus-community/helm-charts#102]
Hi, at
https://github.com/prometheus-community/helm-charts/blob/78c75ee0c438e9321370ef023e31cf25f998e89b/charts/kube-prometheus-stack/values.yaml#L1141

It would be good to use the newer container image from https://hub.docker.com/r/ghostunnel/ghostunnel/tags as this supports ARM64.

Note that this would require a version bump from `v1.5.2` to `v1.5.3` of this image. Happy to submit a PR, but just wanted to check first...

**Comment by gkarthiks** [comment]
Thanks @bradwood , happy to review a PR for you. Please also make sure this is not breaking anything else.
