### ISSUE TITLE
[prometheus-kube-stack-16.1.1] Wrong selector in prometheus service

### ISSUE THREAD

**Issue by nickytd** [prometheus-community/helm-charts#1021]
Hi

the prometheus service selector is broken in the 16.1.1 release. The ingress points to a service which selector doesn't refer the prometheus pods. 

If you deploy a release with name "monitoring" end enabled prometheus ingress then:
The ingress refers service:
                        /   monitoring-kube-prometheus-prometheus:9090 (<none>)
And the above service has a selector:
                      Selector:          app=prometheus,prometheus=monitoring-kube-prometheus-prometheus
But the pod has  a deferent label set in which "app=prometheus" is missing. Instead there is "app.kubernetes.io/name=prometheus"

Best regards
Niki Dokovski

**Comment by theangryangel** [comment]
I believe this is the ultimate issue https://github.com/prometheus-operator/prometheus-operator/issues/4050 

fwiw I had to go back to 16.0.1

**Comment by testfile2** [comment]
+1. Having the same issue. Pod is missing the app=prometheus label

**Comment by ryanlelek** [comment]
Confirmed in v16.1.1 last night.
New release v16.1.2 deployed into a fresh cluster has resolved the issue for me.

Commit 2411d15
https://github.com/prometheus-community/helm-charts/commit/2411d15017d5b673fc8c211ea20616534eb8e6e4

**Comment by Xtigyro** [comment]
@nickytd Could you please test with `v16.1.2` (https://github.com/prometheus-community/helm-charts/pull/1010)?

**Comment by nickytd** [comment]
👍 v16.1.2 Works as expected.
Thanks
