### ISSUE TITLE
[kube-prometheus-stack] Grafana Nodes Dashboards no data

### ISSUE THREAD

**Issue by iboobel** [prometheus-community/helm-charts#1022]
**Describe the bug**
Some panels on Nodes dashboards are blank. 
![image](https://user-images.githubusercontent.com/3677154/120076283-7e8d5980-c0ad-11eb-98f0-9f7580723ea8.png)

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
Version:"v3.4.1"
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack-16.1.1
 APP VERSION 0.48.0

**What you expected to happen**:
I expect to see CPU load  

**How to reproduce it** (as minimally and precisely as possible):
Install this version of chart 

**Changed values of values.yaml** (only put values which differ from the defaults):
```
grafana:
  enabled: true
  namespaceOverride: ""
  ## Deploy default dashboards.
  defaultDashboardsEnabled: true
```

**Anything else we need to know**:

Looks like problem with $__rate_interval. If I change Min step values $__rate_interval -> 1m, everything works fine. 
https://github.com/prometheus-community/helm-charts/commit/cddb167f271812fa7c010019411e59eaa9c1413f#diff-5f2b97c4e53de9ee2be908cbc511915f2d9757ac600058370a3e88ab829fe3c4L97

Also, there is error in browser console
![image](https://user-images.githubusercontent.com/3677154/120076552-c6f94700-c0ae-11eb-9d0e-eeb0059ae350.png)

**Comment by tux-00** [comment]
This is not the only one with this problem, I can see that the "USE Method / Cluster" is missing some values too.

Into "CPU Utilisation" of the "USE Method / Cluster" dashboard it seems the metric `instance:node_cpu_utilisation:rate5m` doesn't exist anymore but `instance:node_cpu_utilisation:rate1m` exists. I don't know much about how the dashboards are generated.

**Comment by arianvp** [comment]
The dashboards are retrieved with:

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack

**Comment by arianvp** [comment]
The same problem is present upstream: https://github.com/prometheus-operator/kube-prometheus/issues/1104
