### ISSUE TITLE
unable to build kubernetes objects from release manifest

### ISSUE THREAD

**Issue by Azhdar1990** [prometheus-community/helm-charts#1026]
Hello
When i try to deploy i get an error:

helm install --namespace monitoring prometheus prometheus-community/kube-prometheus-stack

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]

kubernetes version - v1.21.1

Could you help me with this issue?

**Comment by zquaisar** [comment]
is there any fix available for this one yet ?

**Comment by mrueg** [comment]
Do old CRDs exist, and if so did you update them?

**Comment by zquaisar** [comment]
yes they do, how to i update these? i see in some other places it says delete the old CRD's

**Comment by mrueg** [comment]
Please see the README.md, it explains what to do on version upgrades as helm doesn't manage CRDs. https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
