### ISSUE TITLE
[kube-prometheus-stack] Disable Grafana test framework by default from grafana sub-chart?

### ISSUE THREAD

**Issue by bradwood** [prometheus-community/helm-charts#103]
Hi,

It appears as if the default `values.yaml` installs the grafana chart with it's "test framework" enabled.

I think this should be disabled by default, for a standard production deployment. Is it worth updating this chart's `values.yaml` to default that to off?

Details:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L64

Happy to add a PR if we agree.

**Comment by gkarthiks** [comment]
Hi @bradwood, thanks for reporting the issue. The `kube-prometheus-stack` pulls the upstream grafana chart and does not modify anything apart form the values related to datasource, monitoring and dashboard.

Though we don't have control over the upstream chart, but you could always pass the `grafana.testFramework.enabled=false` in your helm command with Prometheus Stack.

**Comment by bradwood** [comment]
i just added a stanza in the top-level `values.yaml` in _this_ repo and that did the job. My point was more whether this repo should force the default to false -- it seems like a better default. 

FWIW, I am templating this out first via `helm template` and then `kustomize`ing the resulting manifests so that I can apply them via GitOps...
