### ISSUE TITLE
Alertmanger alerts not printing any Summary Description or Labels

### ISSUE THREAD

**Issue by mitunmbj** [prometheus-community/helm-charts#1034]
Configured Alertmanger to send the alerts via slack but in the slack i can see only the blunt messages, I cannot see any summary or description not even what are alerts for, I used same chart a month ago and it was working fine with slack alerts printing what alert it is, Now it printing alerts blunt. please find the image below 
![image](https://user-images.githubusercontent.com/43162712/120430881-4cbe1080-c395-11eb-8b72-b650e815325d.png)

**Comment by aantn** [comment]
@mitunmbj did you ever figure out what caused this? Ran into something similar lately
