### ISSUE TITLE
kube-prometheus-stack job-patch uses static securityContext

### ISSUE THREAD

**Issue by ErmakovDmitriy** [prometheus-community/helm-charts#1038]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4", GitCommit:"", GitTreeState:"", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-1058+7d0a2b269a2741-dirty", GitCommit:"7d0a2b269a27413f5f125d30c9d726684886c69a", GitTreeState:"dirty", BuildDate:"2021-04-16T13:16:02Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

OKD 4.7.0
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 16.1.2

**What happened**:  manifests rendered by
templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml and templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml can not start the Jobs because the Jobs use static securityContext with `runAsUser: 2000` and `runAsGroup: 2000`, so the installation/upgrade fails.

**What you expected to happen**: Successful chart installation/upgrade.

**How to reproduce it** (as minimally and precisely as possible): Reproduces always if the chart is installed on Openshift. Openshift defines UID and GID ranges for every Namespace and they are in "high" numbers (over 1000000). Default Openshift Policy does not allow to deploy Pods which have securityContext user and group IDs not in a Namespace range.

In all sections in `values.yaml` I configured a custom securityContext to correspond to the user and group IDs for the Openshift Namespace where I was going to install the Chart:

```yaml
securityContext:
  runAsGroup: 1001070000
  runAsNonRoot: true
  runAsUser: 1001070000
  fsGroup: 1001070000
```

**The helm command that you execute and failing/misfunctioning**: helm upgrade --install prometheus-community/kube-prometheus-stack --values=custom-values.yaml

**Anything else we need to know**:
I think that the problem is that UID and GID are defined static in these manifests because the `job-patch-Webhook` and `job-createSecret` can not start their Pods (forbidden by Openshift - UID and GID ranges are incorrect).

https://github.com/prometheus-community/helm-charts/blob/babe08b51bd69896bd37ef2e05336f34740b7c11/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml#L61
https://github.com/prometheus-community/helm-charts/blob/babe08b51bd69896bd37ef2e05336f34740b7c11/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml#L62

**Possible fix**:
When I helm fetch --unpack the chart and just deleted `securityContext` from the Job Templates, the chart (from my local copy) installed without issues.
I wonder if it is possible to make the Job Template also use `securityContext` from `values.yaml` so to make the contexts tunable.

**Comment by samyak335** [comment]
i am facing same issue , kube-prometheus-stack is not being installed in different namespace in openshift cluster. Any solution for this , would be appreciated. I have set the runasuser and runasgroup fsgroup values according to namespace describe details.

C:\Users\i_ist\.crc\bin\oc>helm install -f prometheusvalues.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: C:\Users\~1.KAL\AppData\Local\Temp\helm\repository\kube-prometheus-stack-55.7.1.tgz

coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.fsGroup is a table. Ignoring non-table value (2000)
coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.runAsGroup is a table. Ignoring non-table value (2000)
coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.runAsUser is a table. Ignoring non-table value (1000)
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagerconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD probes.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusagents.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD scrapeconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.runAsUser is a table. Ignoring non-table value (1000)
coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.fsGroup is a table. Ignoring non-table value (2000)
coalesce.go:289: warning: destination for kube-prometheus-stack.alertmanager.alertmanagerSpec.securityContext.runAsGroup is a table. Ignoring non-table value (2000)
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ServiceAccount
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRole
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" Role
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" RoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission-create" Job
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job prometheus-kube-prometheus-admission-create with timeout of 5m0s
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: ADDED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: MODIFIED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Release prometheus has been cancelled.
Error: INSTALLATION FAILED: context canceled
helm.go:84: [debug] context canceled
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650

C:\Users\samyak.kalisetti_ist\.crc\bin\oc>helm delete prometheus -n monitoring
release "prometheus" uninstalled

C:\Users\samyak.kalisetti_ist\.crc\bin\oc>helm install -f prometheusvalues.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug global.rbac.create=true
install.go:214: [debug] Original chart version: ""
Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: global.rbac.create=true
helm.go:84: [debug] expected at most two arguments, unexpected arguments: global.rbac.create=true
helm.sh/helm/v3/pkg/action.(*Install).NameAndChart
        helm.sh/helm/v3/pkg/action/install.go:644
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:220
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:152
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650
