### ISSUE TITLE
[kube-prometheus-stack] Helm-upgrade fails due to admission-webhooks being unable to reach service

### ISSUE THREAD

**Issue by Jaskaranbir** [prometheus-community/helm-charts#1041]
**Describe the bug**
It seems like admission-webhooks arent patched to ignore failures during Helm-upgrades. This causes admission-webhooks to fail while the pod is being patched in single-replica deployments.

**Version of Helm and Kubernetes**:
Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

Kubernetes Version:

```console
$ kubectl version
v1.19.9-gke.1900
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 16.1.2

**What happened**:

> `Error: UPGRADE FAILED: cannot patch "kube-prometheus-kube-prome-general.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-k8s.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-apiserver-availability.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-apiserver-slos" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-apiserver.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-prometheus-general.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-prometheus-node-recording.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-scheduler.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kube-state-metrics" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubelet.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-apps" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-resources" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-storage" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-system-apiserver" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-system-controller-manager" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-system-kubelet" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-system-scheduler" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-kubernetes-system" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-node-exporter.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-node-exporter" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-node-network" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-node.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-prometheus-operator" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator" && cannot patch "kube-prometheus-kube-prome-prometheus" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://kube-prometheus-kube-prome-operator.test-monitoring.svc:443/admission-prometheusrules/validate?timeout=10s": no service port 443 found for service "kube-prometheus-kube-prome-operator"`

**What you expected to happen**:

Helm-upgrade to be completed successfully. 

**How to reproduce it** (as minimally and precisely as possible):

Upgrade Helm-chart, seems to occur randomly. Sometimes the upgrade works.

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
defaultRules:
  rules:
    alertmanager: false
    etcd: false

alertmanager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

prometheusOperator:
  tls:
    enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm upgrade --install my-release prometheus-community/kube-prometheus-stack --version 16.1.2 --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
alertmanager:
  enabled: false
coreDns:
  enabled: false
defaultRules:
  rules:
    alertmanager: false
    etcd: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
prometheusOperator:
  tls:
    enabled: false
```

**Anything else we need to know**:

Something to keep in mind is that the Prometheus cluster is single-replica, so there's no highly available upgrades.

We currently use this patch-job to setup certs/failure-policy post install: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml  
This same job can be used to setup just failure-policy (to `Ignore`) pre-install.

Currently using a temporary workaround for disabling admission-webhook failures before install which resolved the issue:

```console
kubectl get ValidatingWebhookConfiguration -o yaml \
  | sed "s/failurePolicy: Fail/failurePolicy: Ignore/" \
  | kubectl apply -f -
kubectl get MutatingWebhookConfiguration -o yaml \
  | sed "s/failurePolicy: Fail/failurePolicy: Ignore/" \
  | kubectl apply -f -
```

But a more permanent solution within chart would be great. I dont mind creating a PR for this if the community agrees this to be a viable solution.

**Comment by tlperini** [comment]
We are facing the same problem.
K8s v1.17
Chart: 16.10.0

**Comment by rafaribe** [comment]
having the same problem here.

k8s v.1.21.2
Chart: 18.0.0

**Comment by ruckc** [comment]
same problem
k8s v1.22.1
Chart: 18.0.3 - seems like this started sometime in v17

**Comment by timbrd** [comment]
Same problem here.

k8s v1.21.4
Chart: 18.0.3

**Comment by stefano-daitan** [comment]
+1

helm: 3.7.1
k8s server: 1.20.7
kubectl: 1.22.3

**Comment by linxcat** [comment]
I regularly see this as well

Chart/app: kube-prometheus-stack-18.1.0/0.50.0
Helm: v3.5.4
K8S: 1.18
kubectl: v1.20.2

**Comment by yum-dev** [comment]
+1

helm: v3.5.4
k8s: v1.21.2
kubectl: v1.21.0

**Comment by infa-mlagad** [comment]
Any update here. I am also getting same error.

**Comment by infa-mlagad** [comment]
Please check, if this helps. https://github.com/prometheus-community/helm-charts/issues/108

**Comment by SelimBF** [comment]
same issue here 👍 

**k8S version :** Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by vadlungu** [comment]
some on our side 
```
eksctl: v1.22.4
k8s: v1.21.2
helm: v3.7.2"
```

**Comment by SelimBF** [comment]
@vadlungu  if you are trying to install promotheus visit my github repo you find the solution

**Comment by yozhsh** [comment]
same issue
k8s: 1.23
helm: 3.8.0

**Comment by bgaillard** [comment]
Hi, thanks @Jaskaranbir for the provided workaround 👍. 

For those who want to execute the associated commands please be aware that they act on all `validatingwebhookconfiguration` and `mutatingwebhookconfiguration` resources which is probably not what you want in most cases (especially if you have a huge Kubernetes cluster). 

Pick only the resources associated to the `kube-prometheus-stack` instead as explained in comment https://github.com/prometheus-community/helm-charts/issues/108#issuecomment-825689328

In my case I executed the following commands.

```bash
# Check existing objects
kubectl get validatingwebhookconfiguration -A
kubectl get mutatingwebhookconfiguration -A

# Ignore failures
kubectl get validatingwebhookconfiguration NAME_RETURNED_IN_PREVIOUS_COMMAND -o yaml | sed "s/failurePolicy: Fail/failurePolicy: Ignore/" | kubectl apply -f -
kubectl get mutatingwebhookwonfiguration NAME_RETURNED_IN_PREVIOUS_COMMAND  -o yaml | sed "s/failurePolicy: Fail/failurePolicy: Ignore/" | kubectl apply -f -

# Perform Helm changes ...

# Revert policy changes
kubectl get validatingwebhookconfiguration NAME_RETURNED_IN_PREVIOUS_COMMAND -o yaml | sed "s/failurePolicy: Ignore/failurePolicy: Fail/" | kubectl apply -f -
kubectl get mutatingwebhookwonfiguration NAME_RETURNED_IN_PREVIOUS_COMMAND  -o yaml | sed "s/failurePolicy: Ignore/failurePolicy: Fail/" | kubectl apply -f -
```

**Comment by kristianjaeger** [comment]
Same issue.
Helm version: 3.7.2

**Comment by MisterTimn** [comment]
We are facing the same issuel, frequently having to ignore the webhooks to proceed with small upgrades

- kube-prometheus-stack 34.5.1
- helm 3.8.0
- kubernetes v1.22.5

**Comment by ap-vishal** [comment]
Facing same issue.

**Comment by sbkg0002** [comment]
This also fixed it for me: https://github.com/prometheus-operator/prometheus-operator/issues/4399#issuecomment-1004217450

**Comment by stazdx** [comment]
I have the same problem. We need to set `timeoutSecond` in helm template for admission MutatingWebhookConfiguration.
I have added this PR https://github.com/prometheus-community/helm-charts/pull/2233 for solving it.

**Comment by xoxbet** [comment]
Experienced the same issue when upgrading from 40.1.1 to the latest 40.1.2
Setting `prometheusOperator.admissionWebhooks.timeoutSeconds` to 30 helped to solve this.
Thank you @stazdx for making this possible.

**Comment by Hukha** [comment]
We're deploying using ansible and we're having this issue even changing the prometheusOperator.admissionWebhooks.timeoutSeconds to 30 in the values file with no extra logs.
K8s ver: 1.23.7
Helm ver: 3.10.1

**Comment by almereyda** [comment]
We add this in our ArgoCD application definition:

```yaml
ignoreDifferences:
  - group: '*'
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.failurePolicy'
  - group: '*'
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.failurePolicy'
```

**Comment by AndrewSav** [comment]
I wonder what it takes for the bot to remove the stale label. I tried to add some more recent activity in another thread but it was closed anyway

**Comment by lucasmellos** [comment]
@cra1gg I had the same problem, turns out that I had an old MutatingWebhookConfiguration and ValidatingWebhookConfiguration in my cluster, deleting them and installing solved it

**Comment by danports** [comment]
Setting `prometheusOperator.admissionWebhooks.timeoutSeconds` to 30 hasn't helped in my case - I still get intermittent upgrade failures, which can be a little annoying considering how frequently new versions of this chart are released. Using `--no-hooks` on the Helm command seems a bit heavy-handed, so I haven't tried that yet.

**Comment by maxweisspoker** [comment]
I would just like to note that I ran into OP's specific problem. As the error text states, it was failing to reach the webhook service on port 443. After investigating, I saw that indeed the service did not provide 443. Looking into the webhook yaml, I attempted to edit the webhook and define the webhook clientConfig with an [HTTP url](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#url) for the service on the correct port, but got an error saying that only HTTPS is accepted.

So the root cause seems to be that webhooks require TLS on things they call, and like OP, I had my helm values set to disable TLS since everything is internal.  So my workaround was to just delete the webhooks manually and then disable them in the helm values. That's fine for me, since they are merely validating rules that get applied. But this was a very annoying problem that isn't documented.

**Comment by AndrewSav** [comment]
recent activity

**Comment by AndrewSav** [comment]
It looks like may be the "recent activity" has to have some minimum number of characters? Adding short messages does not seem to trigger the bot.

**Comment by neiser** [comment]
@almereyda @cra1gg Just FYI, but for the particular problem of this chart, it's sufficient to add the following `ignoreDifferences`:

```
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: kube-prometheus-stack-admission
    jsonPointers:
      - /webhooks/0/failurePolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: kube-prometheus-stack-admission
    jsonPointers:
      - /webhooks/0/failurePolicy
```

See also #3051

**Comment by larsskj** [comment]
I'm hit by this as well.

**Comment by salimadr** [comment]
Also have that issue 
chart version: 45.24.0

**Comment by AndrewSav** [comment]
This is a message to indicate that people are still interested in this issue and generate "recent activity"

**Comment by maxweisspoker** [comment]
Moar recent activity!

**Comment by sushantkumar-amagi** [comment]
More recent activity. Facing the same issue.

**Comment by NickJ1984** [comment]
Join the waiting

**Comment by HawxChen** [comment]
I am also facing this issue now. Is there anyone debugging it, please count me in. I'd like not to wait until fix dropped from somewhere. Thanks.

**Comment by Chrisys93** [comment]
Also having the problem. Would just using a previous git release solve the problem?
Not even MicroK8s can launch the observability stack, when previously it could.

**Comment by jkroepke** [comment]
If everyone here has the same issue as the author, then you may found the answer here: https://github.com/prometheus-community/helm-charts/issues/1041#issuecomment-1397987346

Webhooks in Kubernetes require TLS, but if you declare

```yaml
prometheusOperator:
  tls:
    enabled: false
```

in your YAML file, then the error is expected.

If you have a different config, but the same error, please create a new issue.
