### ISSUE TITLE
[kube-prometheus-stack] Reference of invalid Prometheus rules in Grafana 1.14 rsrc USE dashboard

### ISSUE THREAD

**Issue by jaanhio** [prometheus-community/helm-charts#1054]
**Describe the bug**
Noticed 2 of the default Grafana USE Method Node/Cluster dashboards are referencing Prometheus rules that does not exist, which resulted in "No data" displayed on the affected panels.

<img width="1595" alt="Screenshot 2021-06-09 at 5 08 43 PM" src="https://user-images.githubusercontent.com/6738954/121328286-c7af9a00-c946-11eb-976f-51100d1031c5.png">
<img width="1604" alt="Screenshot 2021-06-09 at 5 19 33 PM" src="https://user-images.githubusercontent.com/6738954/121328604-0b0a0880-c947-11eb-884d-95978c1d1e4f.png">

**Managed to trace the changes back to a particular release and PR.**

Release v15.4.6: https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-15.4.6...main
PR: https://github.com/prometheus-community/helm-charts/pull/951/files

Prometheus rules file: https://github.com/prometheus-community/helm-charts/blob/217a72df8d80e430e7465656a[…]-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml

i am not entirely clear what is the purpose for the change but if its unintended, i can make a PR to revert this.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
16.5.0 (it should affect all versions >= v15.4.6)

**What happened**:
Grafana 1.14-dashboards USE Node/Cluster are showing "No data" for some of the panels. Root cause is due to the affected panels referencing Prometheus rules that do not exist.

**What you expected to happen**:
The affected panels should pull data from Prometheus rules specified here (https://github.com/prometheus-community/helm-charts/blob/217a72df8d80e430e7465656a[…]-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml) and display accordingly.

**How to reproduce it** (as minimally and precisely as possible):
Use kube-prometheus-stack >= v15.4.6

**Changed values of values.yaml** (only put values which differ from the defaults):
No custom `values.yaml` used.

**The helm command that you execute and failing/misfunctioning**:
```console
helm install my-release prometheus-community/kube-prometheus-stack
```

**Anything else we need to know**:

**Comment by tux-00** [comment]
Same for me, maybe linked with https://github.com/prometheus-community/helm-charts/issues/1022

**Comment by jaanhio** [comment]
in case anyone missed some of what was written above, the breaking change was introduced here:
Release v15.4.6: kube-prometheus-stack-15.4.6...main
PR: https://github.com/prometheus-community/helm-charts/pull/951/files

anyone can provide input on why the changes were made?

**Comment by mrueg** [comment]
It seems like I missed to sync the rulesets as well. Can you give this a try? https://github.com/prometheus-community/helm-charts/pull/1066

**Comment by jaanhio** [comment]
@bismarck @mrueg this is not fixed in #1066. 
could you reopen this issue please? (or at least wait for us to verify this is fixed first before closing it)

these are the affected lines from release v15.4.6 (from which the breaking changes were introduced):
https://github.com/prometheus-community/helm-charts/pull/951/files#diff-c0580b349d3bbf98bb4692b5ca684a7c45a7860f940496f693c6c71e1c34f2a2L80
https://github.com/prometheus-community/helm-charts/pull/951/files#diff-46db88df5994e5a4d24db2af9c39bb2a2ed0679e744927f2ee8dc21c5b12404aL350

i wont list all the lines but its basically the changes made in this file https://github.com/mrueg/prometheus-community-helm-charts/blob/1f5adb611148cb4f6b0cd9298ef70aa432deeeaf/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/node-rsrc-use.yaml.

Questions i have are: 
- whats the reason for the change?
- is it ok for us to change it back (from `5m` to `1m`)?

**Comment by mrueg** [comment]
The dashboards and rules are synced from the upstream project: https://github.com/prometheus-operator/kube-prometheus

Change was made in:
prometheus-operator/kube-prometheus@28d58a9#diff-ad9b0e030d012e83adcdb45dc042bd9364922e140e0c93f247796732a5676e69

**Comment by jaanhio** [comment]
> The dashboards and rules are synced from the upstream project: https://github.com/prometheus-operator/kube-prometheus
> 
> Change was made in:
> [prometheus-operator/kube-prometheus@28d58a9](https://github.com/prometheus-operator/kube-prometheus/commit/28d58a9)#diff-ad9b0e030d012e83adcdb45dc042bd9364922e140e0c93f247796732a5676e69

in this case, seems like the updates for prometheus rules are missing 🤔  https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node-exporter.rules.yaml

**Comment by tux-00** [comment]
This PR doesn't seems to change anything on my side. At least for the "USE Method / Cluster" dashboard.

**Comment by brnck** [comment]
Just updated to

```
"chart":"kube-prometheus-stack-16.10.0"
"app_version":"0.48.1"
```

It seems that the problem still exists

**Comment by jaanhio** [comment]
it is fixed for me. now the USE Method Cluster/Node dashboards are all referencing the "new" `5m` metric rules
