### ISSUE TITLE
[kube-prometheus-stack] Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com"

### ISSUE THREAD

**Issue by nikosece** [prometheus-community/helm-charts#108]
**Describe the bug**
Error installing prometheus. command -> `helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring`. I got the error

`Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://prometheus-prometheus-oper-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s": service "prometheus-prometheus-oper-operator" not found`

Althoutgh `helm install prometheus stable/prometheus-operator --namespace monitoring` was perfectly.
I am using a local kubernetes, at 3 nodes running ubuntu 20.04
**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
"v3.3.1"
```

Kubernetes Version:

```console
$ kubectl version
GitVersion:"v1.19.0"
```

**Which chart**:
**Which version of the chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
key: value
```

```
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**:

**Comment by bzolivereckle** [comment]
same issue here

**Comment by robertb724** [comment]
Yes, this happens to me as well

**Comment by robertb724** [comment]
@bzolivereckle @nikosece Are you all installing these charts on the same cluster? I was able to resolve it by deleting the helm release and then deleting the CRDs. After deleting both a fresh install on the new chart is working.

**Comment by scottrigby** [comment]
Is this issue and fix similar? https://github.com/helm/charts/issues/21080

**Comment by smlx** [comment]
> Is this issue and fix similar? [helm/charts#21080](https://github.com/helm/charts/issues/21080)

Yes, that is the fix.

I saw this issue when I uninstalled the old `prometheus-operator` chart from the `prometheus-operator` namespace and tried to install the new `kube-prometheus-stack` chart into the `kube-prometheus-stack` namespace.

Deleting the `validatingwebhookconfiguration` and `mutatingwebhookconfiguration` associated with the old `prometheus-operator` installation fixed this issue for me.

**Comment by sd2020bs** [comment]
same issue, i deleted all old resources(including roles, rolebindins etc) and tried to install :

helm install testmon prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring
and got error:
Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://testmon-prometheus-operato-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: service "testmon-prometheus-operato-operator" not found

**Comment by darkn3rd** [comment]
@smlx How do you delete `validatingwebhookconfiguration` and `mutatingwebhookconfiguration`.  I didn't want to create a new namespace if I can avoid it, because I have an existing name space I would like to use.

**Comment by Sefiris** [comment]
> @smlx How do you delete `validatingwebhookconfiguration` and `mutatingwebhookconfiguration`. I didn't want to create a new namespace if I can avoid it, because I have an existing name space I would like to use.

my sincere apologies if I'm reviving an old post however to answer your question and what worked for me to change the release name but still keep using the same namespace is the following. Since I found this on a random google for this problem I hope this will help some others too.
```
kubectl get validatingwebhookconfiguration -A
NAME                              WEBHOOKS   AGE
kube-prometheus-stack-admission   1          52d

kubectl delete validatingwebhookconfiguration/kube-prometheus-stack-admission -A
validatingwebhookconfiguration.admissionregistration.k8s.io "kube-prometheus-stack-admission" deleted

kubectl get mutatingwebhookconfiguration -A
NAME                              WEBHOOKS   AGE
kube-prometheus-stack-admission   1          52d

kubectl delete mutatingwebhookconfiguration/kube-prometheus-stack-admission -A
mutatingwebhookconfiguration.admissionregistration.k8s.io "kube-prometheus-stack-admission" deleted

helm install kps prometheus-community/kube-prometheus-stack --version=15.1.1 -n monitoring \
> --set nameOverride=alpha01 \
> --set alertmanager.enabled=false \
> --set grafana.enabled=true \
> --set prometheus.service.type=LoadBalancer,prometheus.service.loadBalancerIP=172.25.3.38 \
> --set prometheusOperator.serviceMonitorSelector={} \
> --set prometheusOperator.serviceMonitorNamespaceSelector={}
NAME: kps
LAST DEPLOYED: Fri Apr 23 16:07:21 2021
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
```

**Comment by billimek** [comment]
I find that I sometimes need to manually delete this webhook for a helm upgrade to succeed sometimes with this chart.

Has anyone figured out a solution that does _not_ require manual intervention?  It's not awesome needing to do this when running the chart in a gitops scenario.

**Comment by quangthe** [comment]
> > @smlx How do you delete `validatingwebhookconfiguration` and `mutatingwebhookconfiguration`. I didn't want to create a new namespace if I can avoid it, because I have an existing name space I would like to use.
> 
> my sincere apologies if I'm reviving an old post however to answer your question and what worked for me to change the release name but still keep using the same namespace is the following. Since I found this on a random google for this problem I hope this will help some others too.
> 
> ```
> kubectl get validatingwebhookconfiguration -A
> NAME                              WEBHOOKS   AGE
> kube-prometheus-stack-admission   1          52d
> 
> kubectl delete validatingwebhookconfiguration/kube-prometheus-stack-admission -A
> validatingwebhookconfiguration.admissionregistration.k8s.io "kube-prometheus-stack-admission" deleted
> 
> kubectl get mutatingwebhookconfiguration -A
> NAME                              WEBHOOKS   AGE
> kube-prometheus-stack-admission   1          52d
> 
> kubectl delete mutatingwebhookconfiguration/kube-prometheus-stack-admission -A
> mutatingwebhookconfiguration.admissionregistration.k8s.io "kube-prometheus-stack-admission" deleted
> 
> helm install kps prometheus-community/kube-prometheus-stack --version=15.1.1 -n monitoring \
> > --set nameOverride=alpha01 \
> > --set alertmanager.enabled=false \
> > --set grafana.enabled=true \
> > --set prometheus.service.type=LoadBalancer,prometheus.service.loadBalancerIP=172.25.3.38 \
> > --set prometheusOperator.serviceMonitorSelector={} \
> > --set prometheusOperator.serviceMonitorNamespaceSelector={}
> NAME: kps
> LAST DEPLOYED: Fri Apr 23 16:07:21 2021
> NAMESPACE: monitoring
> STATUS: deployed
> REVISION: 1
> NOTES:
> kube-prometheus-stack has been installed. Check its status by running:
> ```

Thanks it saves me a day 💯
