### ISSUE TITLE
[prometheus] is not using the recommended resource labels

### ISSUE THREAD

**Issue by rifqifatih** [prometheus-community/helm-charts#1085]
**Is your feature request related to a problem? Please describe.**
Currently most of the Charts are using `app`, `release`, `chart`, `heritage` as the resource labels. For example [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/_helpers.tpl#L20) and [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/templates/deployment.yaml#L6). In contrast, there are also Charts that is using the [recommended label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) (for e.g. [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/deployment.yaml#L11)).

**Describe the solution you'd like**
My suggestion is to make it consistent across Charts using the recommended label if there are no reason not to do it. This would make resource management simpler not looking up into multiple keys of the "same" semantic. I'd be happy to make a PR if this is the desirable state.

**Comment by monotek** [comment]
We could change this but it would introduce a breaking change.

Updates would be hard and need manual steps with kubectl to relabel running statefulsets, if you don't want to have service interruption.

**Comment by nlamirault** [comment]
@rifqifatih i created some PR to solve that : 
* https://github.com/prometheus-community/helm-charts/pull/1028
* https://github.com/prometheus-community/helm-charts/pull/927

**Comment by nlamirault** [comment]
Ping
