### ISSUE TITLE
[kube-prometheus-stack] Dashboard drill down link broken

### ISSUE THREAD

**Issue by daniel-tron** [prometheus-community/helm-charts#1086]
Package: kube-prometheus-stack-16.9.0

Issue:  The drill down link in dashboard Kubernetes/Computer Resources/Namespace (Workloads) point to k8s-resource-**, but the work link should be kubernetes-compute-resource-*, same issue can be reproduced in pod dashboard.

**Comment by brnck** [comment]
I am having the same problem with

```
CHART    APP VERSION
16.10.0	 0.48.1
```

**Comment by muffl0n** [comment]
Weird thing I'm seeing with chart version 16.10.0: If I do a reload after getting the 404 page, I get a redirect to the correct page. Can somebody confirm?

**Comment by brnck** [comment]
@muffl0n Yep, same for me. It seems that additional refresh redirects to the correct page.

**Comment by muffl0n** [comment]
This is still an issue.

**Comment by muffl0n** [comment]
Cannot reproduce in 17.0.3

**Comment by fhera** [comment]
This is still an issue in 18.0.5

**Comment by eirisdg** [comment]
> This is still an issue in 18.0.5

Same here.
It's seems that the redirect doesn't work in first click, only when the web is refresh.

**Comment by tao-zhang** [comment]
Yes, same issue happens to me (18.0.5)

**Comment by skarj** [comment]
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/659

**Comment by skarj** [comment]
https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/659
