### ISSUE TITLE
[prometheus] Inconsistency about annotation based scrape jobs between different charts

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1098]
**Describe the bug**
As of 2021-06-20, the prometheus helm chart README says about [Scraping Pod Metrics via Annotations](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations)

> This chart uses a default configuration that causes prometheus to scrape a variety of kubernetes resource types, provided they have the correct annotations. 

However, on this same github repo, the kube-prometheus-stack README says [prometheus.io/scrape](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#prometheusioscrape)

> The prometheus operator does not support annotation-based discovery of services, using the `PodMonitor` or `ServiceMonitor` CRD in its place as they provide far more configuration options

There was some discussions explaining why annotations support is inferior to `PodMonitor` or `ServiceMonitor` CRD https://github.com/prometheus-operator/prometheus-operator/issues/1547 

Nevertheless, there should be a consistency among all helm charts in https://github.com/prometheus-community/helm-charts regarding the support of Prometheus scraping job via annotation. Basically what is the rationale for the [prometheus-community, prometheus helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) to continue the support for Prometheus scrape job via pod annotation ?

**Version of Helm and Kubernetes**:

Versions

```console
$ helm version

version.BuildInfo{Version:"v3.6.1", GitCommit:"61d8e8c4a6f95540c15c6a65f36a6dd0a45e7a2f", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

```console
helm search repo prometheus-community

NAME                                               CHART VERSION   APP VERSION     DESCRIPTION                                       
prometheus-community/kube-prometheus-stack         16.10.0         0.48.1          kube-prometheus-stack collects Kubernetes 
prometheus-community/prometheus                    14.2.1          2.26.0          Prometheus is a monitoring system and time 
```

**Comment by monotek** [comment]
Because you need the promehteus operator to use the crds and its not part of the prometheus chart so it can use pod and servicemonitors at all.
