### ISSUE TITLE
Transfer ownership and rename scottrigby/prometheus-helm-charts to prometheus-community/helm-charts

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#11]
## Background

Fixes: https://github.com/prometheus-community/community/issues/28#issuecomment-677920051

## Status

- [x] Maintainers poll about whether #1 is a blocker for transferring the repo. From feedback so far appears it is not. See "Is renaming `prometheus-operator` to `kube-prometheus` a blocker?" below
- [x] @brancz final approval as sponsoring prometheus developer

## 📊  Maintainers poll
Are we good to transfer ownership now?

**Note:** Final decision is for @brancz, as he's sponsoring the repo transfer for the `prometheus-community`.

This temporary repo location is working. You can test it now:

```console
$ helm repo add temp-prometheus-community https://scottrigby.github.io/prometheus-helm-charts
"temp-prometheus-community" has been added to your repositories
$ helm repo update
$ helm search repo prometheus | grep temp
temp-prometheus-community/prometheus              	11.12.1      	2.20.1     	Prometheus is a monitoring system and time seri...
temp-prometheus-community/prometheus-adapter      	2.5.1        	v0.7.0     	A Helm chart for k8s prometheus adapter           
temp-prometheus-community/prometheus-blackbox-e...	4.3.1        	0.16.0     	Prometheus Blackbox Exporter                      
temp-prometheus-community/prometheus-cloudwatch...	0.8.4        	0.8.0      	A Helm chart for prometheus cloudwatch-exporter   
temp-prometheus-community/prometheus-consul-exp...	0.1.6        	0.4.0      	A Helm chart for the Prometheus Consul Exporter   
temp-prometheus-community/prometheus-couchdb-ex...	0.1.2        	1.0        	A Helm chart to export the metrics from couchdb...
temp-prometheus-community/prometheus-mongodb-ex...	2.8.1        	v0.10.0    	A Prometheus exporter for MongoDB metrics         
temp-prometheus-community/prometheus-mysql-expo...	0.7.1        	v0.11.0    	A Helm chart for prometheus mysql exporter with...
temp-prometheus-community/prometheus-nats-exporter	2.5.1        	0.6.2      	A Helm chart for prometheus-nats-exporter         
temp-prometheus-community/prometheus-node-exporter	1.11.2       	1.0.1      	A Helm chart for prometheus node-exporter         
temp-prometheus-community/prometheus-operator     	9.3.2        	0.38.1     	DEPRECATED - This chart will be renamed. See ht...
temp-prometheus-community/prometheus-postgres-e...	1.3.1        	0.8.0      	A Helm chart for prometheus postgres-exporter     
temp-prometheus-community/prometheus-pushgateway  	1.4.2        	1.2.0      	A Helm chart for prometheus pushgateway           
temp-prometheus-community/prometheus-rabbitmq-e...	0.5.6        	v0.29.0    	Rabbitmq metrics exporter for prometheus          
temp-prometheus-community/prometheus-redis-expo...	3.5.1        	1.3.4      	Prometheus exporter for Redis metrics             
temp-prometheus-community/prometheus-snmp-exporter	0.0.6        	0.14.0     	Prometheus SNMP Exporter                          
temp-prometheus-community/prometheus-to-sd        	0.3.1        	0.5.2      	Scrape metrics stored in prometheus format and ...
```

After the transfer – as documented in this repo README and all the charts READMEs – you should be able to do the same with:

```console
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
```

### Is renaming `prometheus-operator` to `kube-prometheus` a blocker?

@brancz see how the `temp-prometheus-community/prometheus-operator` is marked `DEPRECATED` in the output? Because it's also flagged in `Chart.yaml` it will be hidden in the hubs like Helm Hub (and Artifact Hub, it's successor). I also made sure to VERY CLEARLY mark the chart README with a [huge deprecation and warning sign](https://github.com/scottrigby/prometheus-helm-charts/tree/main/charts/prometheus-operator) (as well as CLI output if someone tries to install it after missing all that) so no one should mistake it as an active chart.

Regarding the order of this repo transfer and finishing fixing the renamed chart (ongoing in PR #1), I see two options:
1. Wait to complete that until after transferring this repo to [prometheus-community](https://github.com/prometheus-community/)
    - Pro: it will allow us to deprecate the prometheus charts in the `stable` repo immediately, and allowing users to begin contributing directly to them
    - Con: users of `stable/prometheus-operator` will have to wait until the newly named `prometheus-community/kube-prometheus` chart is finished to use it. Then again, they will have to wait until it's ready either way
2. Complete PR #1 before transferring repo ownership to prometheus-community
    - Pro: when we announce the move, we can also announce the upgrade path from `stable/prometheus-operator` chart to `prometheus-community/kube-prometheus`
    - Con: it will delay moving the other charts. Since there are far fewer active maintainers of the `stable/prometheus-operator` chart it's difficult to predict a completion timeline. Also if we transferred first we could still announce the planned change (and link to the PR), which may encourage more participating in review/testing to get it done sooner than it would have otherwise?

I'm clearly in favor of option 1. Does anyone disagree?

### Any other issues need to be resolved first?

All identified issues so far in this gh project [prepare repo for transfer to prometheus-community/helm-charts](https://github.com/scottrigby/prometheus-helm-charts/projects/1) are complete. The other [open issues](https://github.com/scottrigby/prometheus-helm-charts/issues) (apart from https://github.com/scottrigby/prometheus-helm-charts/issues/13, which I'm keeping open to remind us to continue holding PRs in `stable` until this is done so we can close them) either _must_ or _can_ wait until after the transfer.

**Comment by monotek** [comment]
I think using "prometheus-helm-charts" as repo name makes forking easier, because there are already a lot of "Helm-Charts" repos out there.. 

I had a fuckup with one of these Helm-Charts repos once and had to delete & fork with other name to get it fixed.

**Comment by scottrigby** [comment]
@monotek I hear you, but it's easy to [rename a GitHub repo](https://docs.github.com/en/github/administering-a-repository/renaming-a-repository).

**Comment by monotek** [comment]
In my case github mixed repos up, leading to a situation where I could not create prs (or was created for another repo).
Not sure if my fault while forking or github bug (likely the first).

**Comment by scottrigby** [comment]
@monotek Yes this is due to user error, and easy to fix either during forking or afterwards on your fork (https://docs.github.com/en/github/administering-a-repository/renaming-a-repository). I'll follow up with you separately.

**Comment by scottrigby** [comment]
OK this is done ✅  https://github.com/prometheus-community/helm-charts

**Comment by scottrigby** [comment]
See https://prometheus-community.github.io/helm-charts/index.yaml

Existing charts should now be installable per the README instructions

**Comment by monotek** [comment]
Sweet 😎

Maybe we should put a readme.md there to, so you get the links to the chart source if you open: https://prometheus-community.github.io

**Comment by monotek** [comment]
Done in: https://github.com/prometheus-community/helm-charts/pull/39
