### ISSUE TITLE
[kube-prometheus-stack] Remove `templates/grafana/servicemonitor.yaml`

### ISSUE THREAD

**Issue by guidoffm** [prometheus-community/helm-charts#1101]
A ServiceMonitor for the Grafana service is created by this file if a value `grafana.serviceMonitor.selfMonitor` is set to `true` (default value).

The file `templates/grafana/servicemonitor.yaml` does not allow to set `scheme` to `https` for the ServiceMonitor created.

Why not use the Grafana Helm chart builtin ServiceMonitor for this?

It can be enabled by setting the value `grafana.serviceMonitor.enabled` to `true`.

This reduces configuration complexity.

Is there any reason to have a separate file `templates/grafana/servicemonitor.yaml`?

**Comment by monotek** [comment]
I guess yoou should ask in the grafana helm chart repo: https://github.com/grafana/helm-charts

**Comment by guidoffm** [comment]
> I guess yoou should ask in the grafana helm chart repo: https://github.com/grafana/helm-charts

No. The proposal is to use the ServiceMonitor from in the Grafana chart and to drop the ServiceMonitor for Grafana in the `kube-prometheus-stack` chart.

**Comment by guidoffm** [comment]
Still no Resolution

**Comment by mweibel** [comment]
can this be reopened please? I'm also wondering why there's a selfMonitor and a separate serviceMonitor from the subchart in place.

**Comment by monotek** [comment]
Pull request welcome ;-)
