### ISSUE TITLE
[prometheus], [kube-prometheus-stack] Move kube-state-metrics off of Helm stable

### ISSUE THREAD

**Issue by davidnortonjr-sps** [prometheus-community/helm-charts#111]
The `kube-state-metrics` subchart is hosted on the stable chart repository, which will be turned off in November: https://github.com/helm/charts/#deprecation-timeline

[It doesn't look like there's a new home yet](https://github.com/kubernetes/kube-state-metrics/issues/1153), but I wanted to open the issue

**Comment by scottrigby** [comment]
I have started work on this in https://github.com/kubernetes/kube-state-metrics/pull/1237

**Comment by scottrigby** [comment]
Once this is complete, we'll need to update the dependencies in `prometheus` and `kube-prometheus-stack` charts, and their READMEs.

**Comment by gkarthiks** [comment]
@scottrigby I can take care of the prom and kps charts once we have the kube-state-metrics into prom-community.

**Comment by monotek** [comment]
For the prometheus chart i use the bitnami chart now as dependency as long as the official build pipeline is broken.
https://github.com/prometheus-community/helm-charts/pull/556

**Comment by cablespaghetti** [comment]
This can be closed as https://github.com/prometheus-community/helm-charts/pull/307 and https://github.com/prometheus-community/helm-charts/pull/497 have been merged. @monotek
