### ISSUE TITLE
[prometheus-node-exporter] add support for imagePullSecrets

### ISSUE THREAD

**Issue by horihel** [prometheus-community/helm-charts#1114]
**Is your feature request related to a problem? Please describe.**
If you try to pull prometheus-node-exporter from a private in-house mirror with authentication, the unmodified chart will fail because it doesn't allow to specify an imagePullSecret

**Describe the solution you'd like**
same as in (for example) kube-state-metrics chart:
```yaml
imagePullSecrets: []
# - name: "image-pull-secret"
```

**Describe alternatives you've considered**
only alternative is not mirroring or mirroring with an unauthenticated proxy.

**Additional context**
There's pretty much just this snippet missing (indent might be wrong, i just copied this from kube-state-metrics:
```yaml
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
```

Note that i found the same problem with the admission-webhooks in the prometheus-operator charts - there might be more, but i stumbled only over those two (yet).

**Comment by monotek** [comment]
Would you mind to create an pr for this please?

**Comment by horihel** [comment]
i don't mind - just need a little time to set it up.

**Comment by horihel** [comment]
nevermind and sorry - just found out the imagepullsecret gets added to the serviceaccount which should work just as well.
