### ISSUE TITLE
[prometheus-kube-stack] Operator ValidatingWebhookConfiguration and MutatingWebhookConfiguration should not be created if Prometheus Operator is disabled

### ISSUE THREAD

**Issue by francoisminaud** [prometheus-community/helm-charts#1118]
**Describe the bug**
If there is more than one Prometheus installation on a cluster, one may not want to have more than one Operator.
By disabling the Operator in values.yaml that should do the trick but no. 

ValidatingWebhookConfiguration and MutatingWebhookConfiguration are still enabled by default and it caused issues when deploying various relases:

**cannot patch "counteroffer-postgresql" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com"**

To fix this, I had to delete those created objects. They should not be created by default if Operator is disabled.

I will submit a PR for this as the template file seems to be miscontructed.

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

kube-prometheus-chart

**Which version of the chart**:

16.12.0

**What happened**:

ValidatingWebhookConfiguration and MutatingWebhookConfiguration were created

**What you expected to happen**:

ValidatingWebhookConfiguration and MutatingWebhookConfiguration  should not be created

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
rometheusOperator:
  enabled: false
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:

**Comment by francoisminaud** [comment]
It seems like all files in [prometheus-operator](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks) are dependent on .Values.prometheusOperator.admissionWebhooks.enabled and not .Values.prometheusOperator.enabled

Bug or feature?

**Comment by saphoooo** [comment]
Same here, I find confusing having to disable admissionWebhooks when prometheusOperator is already disabled
