### ISSUE TITLE
[kube-prometheus-stack] Values file lacks the ability to set a service type for Grafana

### ISSUE THREAD

**Issue by joereyna** [prometheus-community/helm-charts#113]
**Describe the bug**
I cannot set a service type for the Grafana service.  I can only enable ingress and set it to a hostname.

**Version of Helm and Kubernetes**:

Helm Version:

```
version.BuildInfo{Version:"v3.2.2", GitCommit:"a6ea66349ae3015618da4f547677a14b9ecc09b3", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T21:54:15Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**:  kube-prometheus-stack-9.4.3

**What happened**:
I need to create a service for Grafana and set the service type to LoadBalancer, but this chart won't allow me to do that.  It sets a ClusterIP service type by default and doesn't allow me to change it via the helm chart.

**What you expected to happen**:
I expect to be able to set a service type for any service installed by the helm chart.  Grafana is a service that gets installed, and I expect to be able to set its service type.

**How to reproduce it** (as minimally and precisely as possible):
Deploy chart with default values.yaml and optionally enable ingress for Grafana.  You can only set service type manually after install.

**Anything else we need to know**:
This creates a problem when you want to perform GitOps with your K8s services because my running app (kube-prometheus-stack) will no longer be in sync with the helm chart checked in to my repo.

**Comment by scottrigby** [comment]
You should be able to override any of the dependent charts values, below the [grafana](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/requirements.yaml#L13) dependency name key.

Example: `--set grafana.service.type="LoadBalancer"`.

See￼ https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L119

**Comment by joereyna** [comment]
@scottrigby maybe I'm confused.  The link you pasted is from a different helm chart, right?  I'm talking about the kube-prometheus-stack helm chart and that option doesn't seem to exist.  But I will try the `--set grafana.service.type="LoadBalancer"` option.

The grafana section begins here: 
https://github.com/prometheus-community/helm-charts/blob/4d780c4496a7df089dfde11c8731f26dc51c4a1f/charts/kube-prometheus-stack/values.yaml#L486

and the service section only has one option:
https://github.com/prometheus-community/helm-charts/blob/4d780c4496a7df089dfde11c8731f26dc51c4a1f/charts/kube-prometheus-stack/values.yaml#L576

**Comment by joereyna** [comment]
Ok, so adding this to the service: section (#L576 in values.yaml referenced above), sets the service type to LoadBalancer:
`type: LoadBalancer`

Sorry.  It was just confusing since all the other services in this values.yaml file had the `type: ClusterIP` option already present and I just had to override it.  I'm ok now.

**Comment by scottrigby** [comment]
The grafana chart is a dependency of Kube-prometheus-stack. See the Dependencies section of the chart README: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#dependencies

You can see a charts dependencies with https://helm.sh/docs/helm/helm_dependency_list/

For docs on how this works, see "overriding values from a parent chart": https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart
