### ISSUE TITLE
[kube-prometheus-stack] Modifying grafana datasource (additionalDataSources) won't trigger a grafana restart

### ISSUE THREAD

**Issue by francoisminaud** [prometheus-community/helm-charts#1134]
**Describe the bug**
One may want to add various datasources (Prometheus, Thanos etc) to the list of the Grafana datasources.
When applying the changes, upgrading the helm release, one would think the new datasource is configured in Grafana but it's not, so a manual Grafana pod restart is needed.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

kube-prometheus-stack

**Which version of the chart**:

16.12.1

**What happened**:

New datasource is not listed

**What you expected to happen**:

Datasource should be listed

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

Add or modify a datasource https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L702
 

```console
key: value
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:

**Comment by monotek** [comment]
I guess this question would be fitting better in the grafan chart repo: https://github.com/grafana/helm-charts

**Comment by francoisminaud** [comment]
True, thanks for your comment, I'll close the issue and open it there.
