### ISSUE TITLE
[all] Unit tests

### ISSUE THREAD

**Issue by krichter722** [prometheus-community/helm-charts#1148]
**Is your feature request related to a problem? Please describe.**
I got started with unit tests for charts only recently and would like to suggest them for the project. The scope is simple: test the templates - one file or multiple - as few as possible, as many as necessary, but of course not the entire chart and don't do anything on a k8s cluster.

**Describe the solution you'd like**
I'll provide you with a little preview in #1149 to get you hooked on the stuff, I can't promise any further contribution or that it's not just something you'll close or revert after a few weeks if you don't like the concept.

You need the [helm plugin unittest](https://github.com/quintush/helm-unittest) which is not overboarding with maintainer personal, but it's progressing and working well. And you need to tell your CI to use it. Installation is a one liner.

**Describe alternatives you've considered**
There're value schemes, integration tests, the `helm test` command, but they're not performing tasks that one might see as unit tests. You can't reach any sane test coverage with integration tests - they have their purpose, of course, but it's a different one. Unit tests simply are a different concept that has seen few attention for helm charts. They're part of quality software engineering where everything needs a test - in theory - and in theory there's no difference between theory and practice - you know the drill.

**Additional context**
./.

**Comment by torstenwalter** [comment]
@krichter722 I like those kind of tests. Actually I implemented these kind of test for the Jenkins helm chart 
https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins/tests


It can be configured easily in GitHub Actions:
https://github.com/jenkinsci/helm-charts/blob/main/.github/workflows/lint-test.yaml#L49-L53 https://github.com/jenkinsci/helm-charts/blob/main/ct.yaml#L8

The main effort is in initially writing these kind of tests.
With a project such as this one it might be hard to implement it for all charts at the same time. So when adopting it we should ensure that CI still works also for charts which do not have any tests. Once that is done we could add tests step by step. That's mainly up to the maintainers to decide if they want it or not.

The easiest way would be if people are just creating PRs with unit tests.

If you want you can take https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-cloudwatch-exporter/ for a test drive it's rather small and I could review PRs there.
Just ping me in PRs.

**Comment by krichter722** [comment]
@torstenwalter Thanks for you feedback and sharing your work. Your exactly right with the pain of starting unit tests for an advanced project. I think it's easy to keep the CI build green and add tests step by step. I personally like test-driven bug fixing a lot. And Prometheus chart devs might encourage and enforce unit tests for bug fixes once they embrace the concept.

One leading question about the use of `helm unittest` in https://github.com/jenkinsci/helm-charts: Are the test actually executed? If I check the output of the latest green PR build https://github.com/jenkinsci/helm-charts/pull/381/checks?check_run_id=2713096918 I don't find `unittest` or `Test Suites:` with the browser search nor do I find the section while skimming the output. And I'm having the same problem with `additional-commands` in a demo project that it's not executed. Maybe you can shed some light on this.

**Comment by torstenwalter** [comment]
Search for PASS

```
Old chart version: 3.3.18
New chart version: 3.3.19
Chart version ok.
Validating /home/runner/work/helm-charts/helm-charts/charts/jenkins/Chart.yaml...
Validation success! 👍
Validating maintainers...

### Chart [ jenkins ] charts/jenkins

 PASS  Controller Prometheus ServiceMonitor	charts/jenkins/tests/jenkins-controller-servicemonitor_test.yaml
 PASS  Jenkins Controller	charts/jenkins/tests/jenkins-controller-svc-test.yaml
```

**Comment by torstenwalter** [comment]
If it's not working then I made something wrong when implementing it https://github.com/helm/chart-testing/pull/283 ;-)

**Comment by krichter722** [comment]
@torstenwalter Now, I get it, it's there - both in jenkinsci and my PR, thank you!
