### ISSUE TITLE
[kube-prometheus-stack] etcd rules for newer versions of etcd can no longer be updated using python script

### ISSUE THREAD

**Issue by allenporter** [prometheus-community/helm-charts#1155]
**Describe the bug**
Filed as a separate issue of #225 since the symptoms are a little different. the method for updating etcd rules works for older versions of etcd. That is, the documentation referenced is for the etcd 3.4 docs, and those docs don't exist for etcd 3.5. The etcd docs now just reference https://github.com/etcd-io/etcd/tree/release-3.5/contrib/mixin which refers to using jsonnet mixins rather than a yaml copy of the rules, following a pattern similar to https://github.com/kubernetes-monitoring/kubernetes-mixin

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: v16.12.1

**What happened**:

The method in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack does not update improvements in the base etcd rules because the 3.4 docs are not necessarily updated anymore as part of updating the etcd monitoring rules.

**What you expected to happen**:

Astraight forward way for the latest etcd rules to flow into kube-prometheus-stack (e.g.  there was a fix for https://github.com/etcd-io/etcd/issues/13147 ) 

As a practical example of a problem or looking at an alternative, etcd 3.5 changes an improvement to the error codes so that an `Unknown` error is revamped as `Canceled` and the monitoring rule was improved as part of https://github.com/etcd-io/etcd/issues/13147 -- an alternative can be to keep updating the 3.4 docs, but that doesn't necessarily seem like the forward looking approach.

Really, this approach of supplying mixins rules does not specific to etcd, its just that for the other rules, this is handled by `prometheus-operator/kube-prometheus`.   Maybe the etcd rules could be handled there too?

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
key: value
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
helm get values my-release
```

**Anything else we need to know**:

**Comment by allenporter** [comment]
This is still an issue

**Comment by allenporter** [comment]
The problem description I wrote above is pretty incomprehensible.  Maybe simpler said as:
- kube prometheus stack needs updated etcd rules from upstream (constrains alert spam fixes)
- kube prometheus stack needs a new way to integrate upstream etcd rules because the old way doesn't work anymore

**Comment by allenporter** [comment]
Still relevant

**Comment by gjkim42** [comment]
Any ongoing work for this?
I would say that this one should be addressed.

**Comment by onedr0p** [comment]
This is probably still an issue.

**Comment by onedr0p** [comment]
This is still an issue.

**Comment by allenporter** [comment]
Still relevant

**Comment by monotek** [comment]
PR with a fix would be weclome :)

**Comment by allenporter** [comment]
Totally, I appreciate that.

I personally did spend about two hours learning jsonnet is bit wild.

**Comment by centromere** [comment]
I believe if [my PR](https://github.com/prometheus-operator/kube-prometheus/pull/1769) is merged, this will no longer be an issue.
