### ISSUE TITLE
[kube-prometheus-stack] Uninstalling kube-prometheus-stack is not deleting release1-kube-prometheus-admission secret

### ISSUE THREAD

**Issue by VineethReddy02** [prometheus-community/helm-charts#1156]
**Describe the bug**
It looks like `release1-kube-prometheus-admission` secret is created by Prometheus-Operator on uninstalling the kube-prometheus-stack the secret isn't deleted. It's left as an orphaned resource in the cluster. I think there should be way to delete the resources created by the operator without manually deleting them on uninstalling the chart. 

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
`15.2.4`

**What happened**:
The kube-prometheus-stack is leaving a secret created by prometheus-operator on uninstall. 

**What you expected to happen**:
On uninstall of kube-prometheus-stack it should delete all the resources created by its components. 

**How to reproduce it** (as minimally and precisely as possible):
Just install kube-prometheus-stack helm chart & uninstall it. 

Created a similar [issue](https://github.com/prometheus-operator/prometheus-operator/issues/4161) on prometheus-operator repo too

**Comment by LeonoreMangold** [comment]
The bug is still existing.
