### ISSUE TITLE
[prometheus-kube-stack] Ingress in GKE response 404 (backend NotFound)

### ISSUE THREAD

**Issue by gautamr** [prometheus-community/helm-charts#116]
**Describe the bug**
GKE installation give response 404 (backend NotFound), service rules for [ /login ] non-existent

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.1", GitCommit:"688c6543aa4b285355723f100302d80431e411cc", GitTreeState:"clean", BuildDate:"2020-07-21T02:37:26Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: 
prometheus-community/prometheus
**Which version of the chart**:
 11.13.0 

**What happened**:
Install with ingress with the following commands
```shell
kubectl create ns prometheus

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm repo update
helm upgrade -i prometheus-stack prometheus-community/kube-prometheus-stack \
  -n prometheus \
  --set grafana.service.type=NodePort \
  --set grafana.ingress.enabled=true \
  --set 'grafana.ingress.hosts[0]=dev.grafana.sample.com' \
  --set alertmanager.service.type=NodePort \
  --set alertmanager.ingress.enabled=true \
  --set 'alertmanager.ingress.hosts[0]=dev.alertmanager.sample.com' \
  --set prometheus.service.type=NodePort \
  --set prometheus.ingress.enabled=true \
  --set 'prometheus.ingress.hosts[0]=dev.prometheus.sample.com'
```

Now when accessing the endpoint `http://dev.grafana.sample.com` getting `response 404 (backend NotFound), service rules for [ /login ] non-existent`
**What you expected to happen**:
Should be able to access this properly 

**How to reproduce it** (as minimally and precisely as possible):
When I hit the endpoint every time I'm getting this.

**GKE version**: `1.16.13-gke.1`

**Comment by fert-f** [comment]
I got similar errors, the issue is that you are not specifying path(s) for your ingress. And default is '/' which could be not enough. Be careful, grafana has different ingress template. Try adding something like this (not sure for syntax, as I'm using value file):
```
--set grafana.ingress.path=/*
--set 'prometheus.ingress.paths[0]=/*'
```
