### ISSUE TITLE
[prometheus-pushgateway] Add sidecarContainers support

### ISSUE THREAD

**Issue by tillig** [prometheus-community/helm-charts#1161]
**Is your feature request related to a problem? Please describe.**
The main `prometheus` chart allows sidecar containers to be injected into the server but not into Pushgateway. If you want to enable Istio mTLS or other auto-managed certificate sidecars in for security, you need the same configuration support.

**Describe the solution you'd like**
I'd like to get the Pushgateway chart (and its copy in `prometheus` to also have a `sidecarContainers` option, just like the main `server` portion of the `prometheus` chart.

**Describe alternatives you've considered**
The only alternative I can think of is to fork a `prometheus-pushgateway` chart and own it myself.

**Additional context**
I know you can get the sidecar injected with Istio annotations, but:

- In Prometheus v2.21.0+ [the Istio mTLS negotiation fails due to HTTP/2 being disabled](https://github.com/prometheus/prometheus/issues/9068). I have a feeling I can get straight mTLS (no negotiation) to work if I manually inject the certificates on both ends and bypass the Istio/Envoy stack.
- I may end up only wanting the Istio certificates for TLS, not authentication, which means I don't actually want the sidecar to proxy traffic - I only want it there to mount the certificates for use by the Pushgateway network stack.
- I'm currently on Istio 1.6.14 which doesn't offer some of the fancier/new annotations that allow you to inject the sidecar but bypass traffic proxying. Enabling the ability to inject the sidecar containers in the same way as the Prometheus server chart allows seemed like a reasonable and consistent compromise.

**Comment by thanatchakromsang** [comment]
I can help with this

**Comment by thanatchakromsang** [comment]
I may have to use this in the future as well, I can help implement this

**Comment by tillig** [comment]
Wow, 30 days to mark it stale? It's still alive.

**Comment by monotek** [comment]
Please provide a pr if you need the feature.
