### ISSUE TITLE
open /prometheus/queries.active: permission denied

### ISSUE THREAD

**Issue by satheshs** [prometheus-community/helm-charts#1162]
All,

Getting error using deploying the chart in the AKS. The error happening in the prometheus-prometheus-kube-prometheus-prometheus statefulset pods.

level=info ts=2021-07-13T12:46:05.041Z caller=main.go:426 msg="Starting Prometheus" version="(version=2.27.1, branch=HEAD, revision=db7f0bcec27bd8aeebad6b08ac849516efa9ae02)"
level=info ts=2021-07-13T12:46:05.041Z caller=main.go:431 build_context="(go=go1.16.4, user=root@fd804fbd4f25, date=20210518-14:17:54)"
level=info ts=2021-07-13T12:46:05.041Z caller=main.go:432 host_details="(Linux 5.4.0-1048-azure #50~18.04.1-Ubuntu SMP Fri May 14 15:30:12 UTC 2021 x86_64 prometheus-prometheus-kube-prometheus-prometheus-0 (none))"    
level=info ts=2021-07-13T12:46:05.042Z caller=main.go:433 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-07-13T12:46:05.042Z caller=main.go:434 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2021-07-13T12:46:05.042Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffcbab3a282, 0xb, 0x14, 0x3652100, 0xc000821560, 0x3652100)
        /app/promql/query_logger.go:117 +0x4e8
main.main()
        /app/cmd/prometheus/main.go:462 +0x58b0

**Comment by satheshs** [comment]
$ kubectl  get all -n monitoring
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          43s
pod/prometheus-grafana-6dd79599bf-bz4vl                      2/2     Running   0          44s
pod/prometheus-kube-prometheus-operator-74d99c95c6-xjswz     1/1     Running   0          44s
pod/prometheus-kube-state-metrics-6c46c5d694-9kwm6           1/1     Running   0          44s
**pod/prometheus-prometheus-kube-prometheus-prometheus-0       1/2     Error     2          42s**
pod/prometheus-prometheus-node-exporter-8sff4                1/1     Running   0          44s
pod/prometheus-prometheus-node-exporter-g29tv                1/1     Running   0          44s

NAME                                              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
service/alertmanager-operated                     ClusterIP   None           <none>        9093/TCP,9094/TCP,9094/UDP   44s
service/prometheus-grafana                        ClusterIP   10.0.64.40     <none>        80/TCP                       45s
service/prometheus-kube-prometheus-alertmanager   ClusterIP   10.0.149.85    <none>        9093/TCP                     45s
service/prometheus-kube-prometheus-operator       ClusterIP   10.0.202.15    <none>        443/TCP                      45s
service/prometheus-kube-prometheus-prometheus     ClusterIP   10.0.201.236   <none>        9090/TCP                     45s
service/prometheus-kube-state-metrics             ClusterIP   10.0.51.84     <none>        8080/TCP                     45s
service/prometheus-operated                       ClusterIP   None           <none>        9090/TCP                     43s
service/prometheus-prometheus-node-exporter       ClusterIP   10.0.20.64     <none>        9100/TCP                     45s

NAME                                                 DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/prometheus-prometheus-node-exporter   2         2         2       2            2           <none>          45s

NAME                                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/prometheus-grafana                    1/1     1            1           45s
deployment.apps/prometheus-kube-prometheus-operator   1/1     1            1           45s
deployment.apps/prometheus-kube-state-metrics         1/1     1            1           45s

NAME                                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/prometheus-grafana-6dd79599bf                    1         1         1       45s
replicaset.apps/prometheus-kube-prometheus-operator-74d99c95c6   1         1         1       45s
replicaset.apps/prometheus-kube-state-metrics-6c46c5d694         1         1         1       45s

NAME                                                                    READY   AGE
statefulset.apps/alertmanager-prometheus-kube-prometheus-alertmanager   1/1     45s
**statefulset.apps/prometheus-prometheus-kube-prometheus-prometheus       0/1     44s**

**Comment by satheshs** [comment]
image: quay.io/prometheus-operator/prometheus-config-reloader:v0.48.1
          query log file\" file=/prometheus/queries.active err=\"open /prometheus/queries.active:
          permission denied\"\npanic: Unable to create mmap-ed active query log\n\ngoroutine
          1 [running]:\ngithub.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffdbc1c0282,
          0xb, 0x14, 0x3652100, 0xc0000add70, 0x3652100)\n\t/app/promql/query_logger.go:117
          +0x4e8\nmain.main()\n\t/app/cmd/prometheus/main.go:462 +0x58b0\n"
        reason: Error

**Comment by hakanqq66** [comment]
level=info ts=2021-08-10T08:38:15.183Z caller=main.go:389 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2021-08-10T08:38:15.183Z caller=main.go:443 msg="Starting Prometheus" version="(version=2.28.1, branch=HEAD, revision=b0944590a1c9a6b35dc5a696869f75f422b107a1)"
level=info ts=2021-08-10T08:38:15.183Z caller=main.go:448 build_context="(go=go1.16.5, user=root@37280701f401, date=20210701-15:18:34)"
level=info ts=2021-08-10T08:38:15.183Z caller=main.go:449 host_details=(windows)
level=info ts=2021-08-10T08:38:15.184Z caller=main.go:450 fd_limits=N/A
level=info ts=2021-08-10T08:38:15.184Z caller=main.go:451 vm_limits=N/A
level=error ts=2021-08-10T08:38:15.185Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=data\queries.active err="open data\\queries.active: The requested operation cannot be performed on a file with a user-mapped section open."
panic: Unable to create mmap-ed active query log

wmi exporter kullanıyorum. Bu hatayı nasıl düzeltebilirim ?

**Comment by lodotek** [comment]
Bump

**Comment by xeor** [comment]
I'm having this issue on a new install. Is this still a bug? Or does it have a workaround not shared in this issue?

**Comment by dezzzmond** [comment]
Same for me

**Comment by tapanhalani** [comment]
I am installing prometheus helm chart v14.11.0 , and still facing this issue with default values.yaml (only changed the resource requests and limits of components)

**Comment by timur-enikeev** [comment]
Why do you close the issue without resolving? There are many reports about this issue, but no solution. This issue affects me too.

**Comment by ChampHlab** [comment]
Workaround

```
  server:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
```

**Comment by Gogu32hZ** [comment]
> Workaround
> 
> ```
>   server:
>     securityContext:
>       runAsUser: 0
>       runAsNonRoot: false
>       runAsGroup: 0
>       fsGroup: 0
> ```

So, this seems to work fine, let me detail a little more the fix posted by @ChampHlab :

You need to edit the deployment yaml of prometheus-server, Ctrl + F to 'securityContext' && set all the values mentioned by @ChampHlab 

After that, save && exit & restart the prometheus server pod if it doesn't make it automatically.

&& that would be all







P.S. in my case, i'm deploying the _prometheus-community    https://prometheus-community.github.io/helm-charts_ version 15.14.0 on an EKS cluster v1.23 following the 'EKS Workshop' guide (https://www.eksworkshop.com/intermediate/240_monitoring/deploy-prometheus/). I had this installed before && worked fine just by following the eks workshop guide, without needing to do anything else. The problem came when upgraded the EKS from v1.22 to v1.23. idk what exactly the problem it was, but, after upgrading EKS i had to manually crate persistent volumes && bind them to the PVC's. After doing that, i ran intro the permissions issue we're talking of in this thread.

**Comment by gulecroc** [comment]
By default prometheus is started with this security context :

```
    securityContext:
      runAsGroup: 65534
      runAsNonRoot: false
      runAsUser: 65534
```

Need to set `fsGroup` to mount correctly the volume (and run as non root by the way) :

```
    securityContext:
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      # set fsGroup equal to runAsGroup
      fsGroup: 65534
```

**Comment by asoap** [comment]
I installed via a helm chart, and I by default had the security context of:
```
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
``` 
Which is what guleroc says should fix it.  But that doesn't seem to work for me.  Changing it to what ChampHlab works for me.
```
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      runAsGroup: 0
      fsGroup: 0
```
