### ISSUE TITLE
[kube-prometheus-stack] proposal: serviceMonitor.additionalLabels

### ISSUE THREAD

**Issue by figaw** [prometheus-community/helm-charts#1166]
**Is your feature request related to a problem? Please describe.**
We want the Prometheus to pick up ServiceMonitors created by the chart, but also ServiceMonitors that we add afterwards. We'd like to be able to explicitly chose the labels on both the ones created by the chart (and the ones we create afterwards.) We don't want prometheus to pick up all ServiceMonitors in a namespace, but only the ones we explicitly label.

By default Prometheus is configured with a `serviceMonitorSelector` for the `release: <release name>`.

It feels wrong to add the label `release: team1-kube-prometheus-stack` to the ServiceMonitors that we create,
since they're not part of that release.

We'd rather add a label like `prometheus-scrape: team1-kube-prometheus-stack`, but that means changing the `serviceMonitorSelector` and now it's not picking up the default ServiceMonitors created, e.g. `<release name>-kube-etcd`
because they're missing the label.

Looking at e.g. <https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-etcd/servicemonitor.yaml#L9> the ServiceMonitors include labels from `kube-prometheus-stack.labels`, which, looking at <https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L57> we can extend with `.Values.commonLabels`.

But using `.Values.commonLabels` will then set the `prometheus-scrape: team1-kube-prometheus-stack`-label on every resource created by the helm chart, which feels bloated.

**Describe the solution you'd like**
I propose a variable in the `values.yaml` called `serviceMonitor.additionalLabels` where we can provide additional labels that will be added to the service monitors.

And adding to each of the serviceMonitors something like,

```
  {{- if .Values.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.serviceMonitor.additionalLabels | nindent 4 }}
  {{- end }}
```

This is similiar to what they've done in the `ingress-nginx` helm chart, see:
<https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-servicemonitor.yaml>

**Describe alternatives you've considered**

- Labeling our service monitors with `release: team1-kube-prometheus-stack` but it feels incorrect.
- Labeling _every_ resources created with `prometheus-scrape: team1-kube-prometheus-stack` but it feels bloated.

**Additional context**
I'd like to make a PR for this, but I want to hear if this is something you're interested in first.

**Comment by brujoand** [comment]
I met the same problem, but seem to have found the solution in #952 

```
prometheus:
  prometheusSpec:
    ruleNamespaceSelector:
      matchLabels: {} # any: true
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector:
      matchLabels: {} # any: true
    serviceMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []

```

**Comment by zamnuts** [comment]
Here's why @brujoand's message about `matchLabels` on rule and service monitor selectors works:

- `ruleNamespaceSelector` is used at https://github.com/prometheus-operator/prometheus-operator/blob/v0.49.0/pkg/prometheus/rules.go#L140-L153
- `serviceMonitorNamespaceSelector` is used at https://github.com/prometheus-operator/prometheus-operator/blob/v0.49.0/pkg/prometheus/operator.go#L953-L965
- both are `LabelSelector`s, normal k8s structs so `matchLabels` and `matchExpressions` will both work: https://github.com/kubernetes/apimachinery/blob/v0.22.0/pkg/apis/meta/v1/types.go#L1117-L1126
- `nil` values for these are guarded within prometheus-operator, but non-nil is handled within k8s api machinery; note that an _empty_ struct (`{}`) means "everything": https://github.com/kubernetes/apimachinery/blob/v0.22.0/pkg/apis/meta/v1/helpers.go#L38-L40

**Comment by figaw** [comment]
My issue has not been resolved. Please remove lifecycle/stale.

**Comment by dnutels** [comment]
While @brujoand solution would work, it would pick up ALL `ServiceMonitors` in all relevant namespaces (which suffers from the exact same problem).

⚠️  It is impossible to use `serviceMonitorSelectorNilUsesHelmValues` and `serviceMonitorSelector` at the same time.

This (and it is, again, true for namespace selection) requires, as @figaw mentioned, requires to put `release: <chart release name>` on unrelated objects like `Services`, `Pods` or `Namespaces`.

**Comment by figaw** [comment]
Thank you for the comments. I've tried to update the original post to clarify.

- we do want it to find ServiceMonitors not part of the chart,
- we still want to be explicit about which are being found.
