### ISSUE TITLE
Add kube-thanos chart

### ISSUE THREAD

**Issue by stevehipwell** [prometheus-community/helm-charts#1169]
**Is your feature request related to a problem? Please describe.**
There are no community Helm charts for Thanos based on the output of the Thanos project.

**Describe the solution you'd like**
Add a `kube-thanos` Helm chart into this repo based on the [kube-thanos](https://github.com/thanos-io/kube-thanos) project.

**Describe alternatives you've considered**
Create and host a kube-thanos chart myself in my own repo.

**Additional context**
I'm happy to open a PR to create this chart.

**Comment by irizzant** [comment]
What about https://github.com/bitnami/charts/tree/master/bitnami/thanos/#installing-the-chart ?

**Comment by stevehipwell** [comment]
@irizzant Bitnami use non-standard images and their own patterns. I'm after the same general output that I'd get from kube-thanos but from a Helm chart not jsonet.

**Comment by irizzant** [comment]
@stevehipwell 

> Bitnami use non-standard images and their own patterns
That may be a pro in disguise. We use Bitnami images in our company regularly.
You get security fixes, system updates and more on a regular basis and their images follow their corresponding upstream closely enough.

Plus you have the chart ready!

**Comment by stevehipwell** [comment]
I'm not sure I see it as a pro, personally I see it as a con, but in reality it's probably just another option which is always a good thing.  Also not in disguise, nobody should be using any of this (or anything else) without fully understanding what they're running.

But back to the main point, the Bitnami chart isn't suitable or desirable so I'm looking for an alternative that I'm happy to contribute to.

**Comment by irizzant** [comment]
> Also not in disguise, nobody should be using any of this (or anything else) without fully understanding what they're running.

I don't get your point here. Their images are publicly available and so are their `Dockerfile` so you know what you're running, including the fact that their images are scanned against known vulnerabilities in quay.io.
At the moment I'm writing, there are no vulnerabilities in both images latest tags.

Going back to the main point then, since we're talking about available options, Bitnami chart is suitable because it already provides the Helm chart and also desirable because of the aforementioned points.

**Comment by stevehipwell** [comment]
> I don't get your point here.

You referred to it as a pro in disguise, I was refuting that there was a pro, in my opinion, or that anything should be "in disguise" when making informed decisions.

I don't want the world through the Bitnami lens, I have no other Bitnami charts or images for this reason. I want a faithful representation of Thanos as released by the Thanos team in Helm chart form and I'm willing to write and maintain it. Ideally though I'd like it to be hosted here alongside kube-prometheus-stack which it would be used with.

**Comment by irizzant** [comment]
The purpose you're aiming to reach is getting a subchart added for Thanos, which I share but you're totally misunderstanding the word "disguise".
You said 
> Bitnami use non-standard images and their own patterns

and I replied that this could be a pro instead, explaining the reasons behind this.
This obviously makes my reply all but an "informed decision", actually it's not a "decision" at all to be precise.

The "informed decision" should come after sharing comparing the possible solutions, and also involves the maintainers of this repo.

I also miss an "informed reply", something different than "I don't want the world through the Bitnami lens".
The target here is creating the needed Kubernetes resources to deploy Thanos with a Helm chart, so I'd like to pinpoint and underline what (if any) the missing resources are in Bitnami's chart which are instead available in kube-thanos.

Moreover:
* the issue should be named "Add Thanos as a subchart", since deciding on the implementation is part of the discussion in this issue
* the problem reported in the issue should be rewritten as "Currently Thanos is included in the chart as a sidecar but we miss a complete Helm chart to deploy Thanos components"

Also I'm missing at the moment an "informed" reply

**Comment by stevehipwell** [comment]
@irizzant this issue is for a full Thanos chart and not a sub-chart. The sidecar in kube-prometheus-stack is separate to the components in [kube-thanos](https://github.com/thanos-io/kube-thanos) with the two being complimentary. Thank you for you input on the Bitnami chart, I'm afraid we're going to have to agree to disagree on this, but it's not relevant to this issue other than as a note that there is an alternative way of installing Thanos.

To reiterate; I'm fully aware of the Bitnami Thanos Helm chart and after careful consideration have discounted it's use. I'd like a Helm chart based on kube-thanos, and even more so I'd like it to be in this repo. I'm happy to do the work if the maintainers are interested, otherwise I'll do it in my own repo for now.

**Comment by irizzant** [comment]
> this issue is for a full Thanos chart and not a sub-chart. The sidecar in kube-prometheus-stack is separate to the components in kube-thanos with the two being complimentary. Thank you for you input on the Bitnami chart, I'm afraid we're going to have to agree to disagree on this, but it's not relevant to this issue other than as a note that there is an alternative way of installing Thanos.

If you create and  host your own Thanos chart and then you add it here as a dependency you're creating a subchart, that is, a chart included into another.
This is also exactly what Bitnami Thanos chart is: it does not deploy Thanos as a sidecar, which stays in kube-prometheus-stack, and instead it deploys all other Thanos components as reported in Bitnami's chart readme:

![image](https://user-images.githubusercontent.com/15982257/126343692-b30b4e3f-ed00-4d91-98bf-e101c90ba18b.png)

so the 2 charts are still complementary and my comments are, in my opinion, still relevant.

That being said, I'm waiting for other member's feedback on this

**Comment by stevehipwell** [comment]
>If you create and host your own Thanos chart and then you add it here as a dependency you're creating a subchart, that is, a chart included into another.

I'm confused, the chart isn't intended to be a dependency, it'd be a peer of kube-prometheus-stack; no matter which repo it's created in.

I'm requesting a home for a kube-thanos Helm chart based on the original [kube-thanos](https://github.com/thanos-io/kube-thanos) jsonet code, this is nothing new just a different packaging technology. This move would be in line with the kube-state-metrics chart being moved out of the component repo and rehomed in this repo.

**Comment by irizzant** [comment]
> I'm confused, the chart isn't intended to be a dependency, it'd be a peer of kube-prometheus-stack; no matter which repo it's created in.

Let me rephrase. kube-prometheus-stack already allows to add thanos as a sidecar to Prometheus and has dependencies on other charts like Grafana.
Regardless from using Bitnami chart or your own newly created one it would be a candidate to be added as dependency to allow kube-prometheus-stack users to deploy prometheus with a full monitoring stack.

Consequently, either you create a new chart hosted here or we use Bitnami's one, we would end up the same result from the user's perspective.

**Comment by stevehipwell** [comment]
@irizzant it _could_ be a dependency, but that's not what this issue is about. This issue is just about an alternative to the Bitnami chart based on the Thanos project's own config in kube-thanos.

**Comment by irizzant** [comment]
@stevehipwell it _could_ of course be a dependency and also we _could_ decide to use the already existing Bitnami chart instead.

This is why I brought the alternative into this issue.

**Comment by stevehipwell** [comment]
@irizzant the Bitnami chart isn't based on the [kube-thaonos](https://github.com/thanos-io/kube-thanos) project so while I should have added it to the original issue as an alternative that I'd discounted it isn't a valid answer to my request. If you want to ask the maintainers to add the Bitnami Thanos chart as a dependency to kube-prometheus-stack go for it, but please do so in a separate issue as this one has been hijacked enough.

**Comment by irizzant** [comment]
> If you want to ask the maintainers to add the Bitnami Thanos chart as a dependency to kube-prometheus-stack go for it, but please do so in a separate issue as this one has been hijacked enough.

@stevehipwell provided that Bitnami Thanos chart adds the same functionalities as your newly hosted chart, if the adopted solution will be preferring Bitnami's to the one based on kube-thanos then this issue would be redundant and could be closed so
I don't see the reason why I should open a new one.
Once maintainers will review this they will decide according to the **discussion**, which is something completely different thing than **hijacking**.

**Comment by fktkrt** [comment]
I had similar thoughts as @irizzant when I recently started out with Thanos, and for now, I have settled with bitnami/thanos. 
In my opinion, the best would be to have official thanos helm charts, just like we have kube-thanos by thanos-io.
After that, we can think of ways to integrate it more closely with these charts (dependency/docs/etc.), but I am also not a maintainer, and I am just thinking out loud.

I think opening a [discussion thread](https://github.com/thanos-io/thanos/discussions) at thanos-io could be a good initial move, if you think this is a good direction. What do you think?

**Comment by irizzant** [comment]
@fktkrt I think that the new helm chart based on `kube-thanos` could be hosted at `thanos-io`, opening a discussion there is a good move imho.
Then we can eventually talk about integration of Thanos charts (bitnami / thanos-io) with the kube-prometheus-stack chart.

**Comment by stevehipwell** [comment]
I've not had any responses over at [thanos-io](https://github.com/thanos-io/thanos/discussions/4475).

**Comment by monotek** [comment]
i guess a thanos chart should go to: https://github.com/thanos-community/helm-charts

for reference: https://github.com/thanos-io/thanos/issues/1820

**Comment by stevehipwell** [comment]
Thanks @monotek I hadn't found that repo, I'll look at creating a PR there.

**Comment by fktkrt** [comment]
Yes, that's another option. I was suggesting the official Thanos repo, because we were talking about having an official helm chart.
