### ISSUE TITLE
Could not find configure setting for cAdvisor to --disable_metrics using Kube-prometheus-stack chart?

### ISSUE THREAD

**Issue by chandhukeenz** [prometheus-community/helm-charts#1172]
I want to scrape only a few metrics from the /metrics/cadvisor endpoint. I couldn't find the configuration choices to disable the unwanted metrics.
Basically, how to configure cAdvisor using this helm chart?

**Comment by rkydybets** [comment]
@chandhukeenz  i have issue with cAdvisor,
that it is not sending metrics from time to time, maybe you could help me

**Comment by chandhukeenz** [comment]
Can you show me your metric interval configuration?

**Comment by rkydybets** [comment]
i stop getting some metrics 
here i describe issue
https://github.com/prometheus-community/helm-charts/issues/1235

**Comment by chandhukeenz** [comment]
Hey, I understand that some of the metrics are missing. This is because by default cAdvisor disables some of the metrics types. I tried finding the cAdvisor container args config in the Kube-Prometheus-stack chart but I couldn't.
I would rather suggest you deploy cAdvisor separately as a daemonset to configure all of these cAdvisor related parameters and then add cadvisor as a job to be scraped by prometheus.
check [this](https://github.com/ckotzbauer/helm-charts/tree/9543376ad0800be2624efbfe09513399deeccc01/charts/cadvisor) link for the cAdvisor helm chart.

**Comment by rkydybets** [comment]
it is not missed,
it appears from time to time, so something wrong with configuration, and that's i try to understand
