### ISSUE TITLE
[prometheus-collectd-exporter] Add helm chart for collectd_exporter

### ISSUE THREAD

**Issue by giannoug** [prometheus-community/helm-charts#118]
The repo should contain a helm chart for [collectd_exporter](https://github.com/prometheus/collectd_exporter) to ease the deployment of a more complete Prometheus monitoring solution.

A hacky alternative can be achieved by deploying collectd_exporter in Docker or in another box, seperate from the main Prometheus (helm-based) installation.

What could be the most appropriate existing chart to base this one? Maybe prometheus-snmp-exporter? I'm not Kubernetes/Helm master, but I can give it a go

**Comment by gkarthiks** [comment]
thanks for raising this issue @giannoug. I can take up on this and will work.

/assign gkarthiks

**Comment by giannoug** [comment]
Hey @gkarthiks sorry for the mention, did you have any chance to look into this?

**Comment by gkarthiks** [comment]
Oops, so sorry @giannoug . I will have this created and added to the community by this weekend.

**Comment by gkarthiks** [comment]
@giannoug I am a little stretched this time, do you wanna take a first stab at this chart, please?
