### ISSUE TITLE
[prometheus-kube-stack] terminate istio-proxy container in job pods

### ISSUE THREAD

**Issue by swarren83** [prometheus-community/helm-charts#1183]
**Describe the bug**
kube-prometheus-stack-admission-create does not complete if istio sidecar injection is configured on the cluster.  This causing problems with ArgoCD being able to fully sync the ArgoApplication deploying the prometheus helm chart.

**Version of Helm and Kubernetes**:
Helm 3
v.1.19.10

Helm Version:

```console
helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

Kubernetes Version:

```console
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:27:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-gke.1602", GitCommit:"7164c6beb14d0c950a914bc68f800f1e4a24b9f8", GitTreeState:"clean", BuildDate:"2021-05-11T22:46:09Z", GoVersion:"go1.15.10b5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
16.14.1

**What happened**:
kube-prometheus-stack-admission-create job does not exit cleanly because the istio-proxy sidecar container is not terminated when the job completes.

**What you expected to happen**:
Kubernetes Jobs make API call to /quitquitquit endpoint of istio-proxy or use pkill to terminated the istio-proxy container.

**How to reproduce it** (as minimally and precisely as possible):  On a cluster with istio-proxy, install chart and watch jobs.

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
        - name: alertmanager.enabled
          value: "false"
        - name: grafana.enabled
          value: "false"
        - name: coreDns.enabled
          value: "false"
        - name: kubeDns.enabled
          value: "true"
        - name: prometheusOperator.certManager.enabled
          value: "true"
        - name: prometheusOperator.certManager.issuerRef.name
          value: "xxxxxx"
        - name: prometheusOperator.certManager.issuerRef.kind
          value: "ClusterIssuer"
```

**The helm command that you execute and failing/misfunctioning**:
ArgoCD is executing helm command.  Helm is not failing.

**Helm values set after installation/upgrade:**
Not an issue with Helm.

**Anything else we need to know**:
https://github.com/redboxllc/scuttle has solved this problem and could be integrated in all jobs.

**Comment by swarren83** [comment]
Any update on this?

**Comment by swarren83** [comment]
Bueller?  Bueller...

**Comment by monotek** [comment]
Can't you just disable istio injection via pod annotation?

**Comment by sathieu** [comment]
More context in:
- https://github.com/istio/istio/issues/11659 (and https://github.com/istio/istio.io/issues/10316)
- https://github.com/kubernetes/kubernetes/issues/65502

An alternative to `scuttle` is to do `curl -XPOST http://localhost:15000/quitquitquit` after running the command.

**Comment by sathieu** [comment]
Not stale ...

**Comment by monotek** [comment]
Or add this in the beginning of your container entry point:

```
# Shutdown the Istio Sidecar
                  trap 'curl -sf -XPOST http://127.0.0.1:15020/quitquitquit' EXIT

````

**Comment by sathieu** [comment]
Not stale (but not specific to this repo either)

**Comment by monotek** [comment]
How about creating a pr with a fix?
Imho you just need some var to be able to add the line of my comment to the job.
https://github.com/prometheus-community/helm-charts/issues/1183#issuecomment-963615945

**Comment by CmdrSharp** [comment]
For future Googlers, what worked for me was to control the istio sidecar injection via values.

```
prometheusOperator:
  patch:
    podAnnotations:
      "sidecar.istio.io/inject": "false"
```

With this, I was able to get the deployment running in a namespace with the sidecar being injected on the other containers.

**Comment by TheBritz** [comment]
CmdrSharp got me most of the way there but it looks like the values structure has changed a bit since 2022:

```
prometheusOperator:
  admissionWebhooks:
    patch:
      podAnnotations:
        "sidecar.istio.io/inject": "false"
```
