### ISSUE TITLE
Prometheus-Server is crashing with OOM killed error

### ISSUE THREAD

**Issue by margani007** [prometheus-community/helm-charts#1184]
Hi There,

I'm installing Prometheus on EKS cluster using helm [charts](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus). 
My prometheus-server POD is keep on crashing and when i describe it its showing OOM killed error. 

My EKS cluster is large with 100 plus nodes and 1000 plus deployments running.

Here is the sample of my resources and i incrementally changed Limits all the way to 30GiB my worker node has 32Gb limit) to see if it resolves the issue but no luck.

resources: 
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi

Please advice or share ideas so resolve this issue.

thanks

**Comment by rkydybets** [comment]
@margani007  
it is really poor of memory, for are doing like this
```
resources = {
          requests = {
            cpu    = "1500m"
            memory = var.environment == "alps-prod" ? "35000Mi" : "20000Mi"
          }
          limits= {
            cpu    = "2000m"
            memory = var.environment == "alps-prod" ? "40000Mi" : "25000Mi"
          }
        }
```
