### ISSUE TITLE
[prometheus-adapter] Custom metrics not working with everything set up (+ unable to fetch metrics for query)

### ISSUE THREAD

**Issue by Hukha** [prometheus-community/helm-charts#1185]
**Describe the bug**
With everything exactly how the official chart info says, prometheus-adapter can't reach or get metrics.

**Version of Helm and Kubernetes**:

Helm Version: 

```console
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: prometheus-adapter

**Which version of the chart**: latest

**What happened**:
We have installed Prometheus + Prometheus-adapter.
![image](https://user-images.githubusercontent.com/37509853/126217915-004416e9-4d18-4974-a721-9e577610133c.png)
![image](https://user-images.githubusercontent.com/37509853/126219419-39937f76-b240-4b37-89d6-d78f19b8c5ea.png)

In the adapter logs we can see this ERROR:
```console
provider.go:227] unable to update list of all metrics: unable to fetch metrics for query "{__name__=~\"^container_.*\",container!=\"POD\",namespace!=\"\",pod!=\"\"}": bad_response: unknown response code 404
```
We've tried all the possible URL for prometheus on the adapter config. We can access to the server (Dashboard) and everything is okay. (The red ones is one node that we have disabled)
![image](https://user-images.githubusercontent.com/37509853/126219218-41d17336-b511-4e6b-a9ca-2f95b3f39510.png)
From the cluster host or directly executing a wget from the adapter container, is getting the endpoint.
Obiously, after all of this, the metrics are empty:
```console
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}
```

If we do a curl directly to the pod IP of the prometheus server, is returning metrics (Not custom ones from my discovered pods btw, only the prometheus default ones):
```console
curl  10.244.0.210:9090/metrics
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000128718
go_gc_duration_seconds{quantile="0.25"} 0.000199906
go_gc_duration_seconds{quantile="0.5"} 0.000253938
go_gc_duration_seconds{quantile="0.75"} 0.000356041
go_gc_duration_seconds{quantile="1"} 0.021060694
go_gc_duration_seconds_sum 0.241405034
go_gc_duration_seconds_count 345
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 147
...
```

We've tried the same IP, port and path in the adapter, along with another possibilities.

**What you expected to happen**:
Adapter gets metrics from prometheus, and after that can use it to expose them at the custom path to autoscale.

**Anything else we need to know**:
I don't know... I've searched all google, and there are some threads with no answer with my same problem. I'm not sure if it's a bug or a problem in the docs to be honest.
I hope that can be fixed, maybe some chart is missing...

Thanks in advance!

**Comment by Dolbager** [comment]
Same issue
```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c18ff7bd5227b42c617cf371cf315d0423e91d5e", GitTreeState:"clean", BuildDate:"2021-05-25T17:38:04Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

prometheus chart:
```
prometheus-14.1.1        	2.26.0
```
prometheus-adapter chart:
```
prometheus-adapter-2.15.0	v0.8.4
```

No errors in logs

```
$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq .
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}
```

**Comment by Hukha** [comment]
> @Hukha were you able to fix it? I am facing similar issue on same version of k8s

Sadly, not
We started working in other things since we don't need it for now, but tried a couple of times more and all was the same...
