### ISSUE TITLE
[prometheus-kube-stack] Issue deploying the prometheus

### ISSUE THREAD

**Issue by kvskranthikumar** [prometheus-community/helm-charts#1196]
When running these steps, getting below error -

helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus-service prometheus-community/kube-prometheus-stack

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]

Using the latest Helm version and K8 - 1.20.7 version

**Comment by spc1jh** [comment]
I faced same issue now.

**Comment by mrueg** [comment]
It sounds like your CRDs are outdated. Can you ensure they are the ones deployed with the corresponding version of prometheus-operator (I believe currently 0.48.1)

**Comment by hymgg** [comment]
@mrueg that helped, thanks. installed ok after deleting old crds
