### ISSUE TITLE
[kube-state-metrics] Ability to configure service monitor

### ISSUE THREAD

**Issue by psibi** [prometheus-community/helm-charts#1213]
**Is your feature request related to a problem? Please describe.**

I have a setup of prometheus under Istio where service monitors require the ability to be configured a custom tlsConfig, scheme etc.

**Describe the solution you'd like**

The helm chart current accepts only subset of values to be overriden for the service monitor: https://github.com/prometheus-community/helm-charts/blob/de83ea0ea489f44f2540a13e1b783b93eac62ffd/charts/kube-state-metrics/values.yaml#L200

It would be nice to provide the ability to configure the entire endpoint or just the individual fields within the endpoint via `values.yaml` file. Right now in it's current state, not much is possible: https://github.com/prometheus-community/helm-charts/blob/de83ea0ea489f44f2540a13e1b783b93eac62ffd/charts/kube-state-metrics/templates/servicemonitor.yaml#L23

**Describe alternatives you've considered**

The alternative is to use a kustomization layer to do the custom overrides myself, but it would be nice to have the first class support from the helm chart itself.

**Comment by jr0dd** [comment]
I would love to have the ability to fine tune some of these servicemonitors myself. For example I want to install coredns in my networking namespace, but the yaml's are all hard-coded for kube-system.

**Comment by torstenwalter** [comment]
@psibi just create a PR for it.
