### ISSUE TITLE
[kube-prometheus-stack] AggregatedAPIDown rule only for k8s >= 1.18

### ISSUE THREAD

**Issue by Niksko** [prometheus-community/helm-charts#122]
**Describe the bug**

This is just reopening this issue from the old repo: https://github.com/helm/charts/issues/22948

The AggregatedAPIDown rule constantly fires on Kubernetes < 1.18 due to a bug fixed in 1.18. See kubernetes/kubernetes#87778 and kubernetes/kube-aggregator#23.

Helm chart should enable the rule only for kubernetes >= 1.18

**Version of Helm and Kubernetes**:

Helm Version: Flux Helm Operator 1.2.0

Kubernetes Version: 1.17.

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 9.4.1

**What happened**:

The `AggregatedAPIDown` alarm is constantly firing for the `v1beta.metrics.k8s.io` group.

`An aggregated API v1beta1.metrics.k8s.io/default has been only 0% available over the last 5m.`

**What you expected to happen**:

This should not be firing.

**How to reproduce it** (as minimally and precisely as possible):

Deploy this chart on K8s 1.17

**Anything else we need to know**:

**Comment by lyz-code** [comment]
bump

**Comment by valtlfelipe** [comment]
Any update on this ?

**Comment by rozcietrzewiacz** [comment]
We are seeing the same on EKS. Interestingly, when I query `kubectl get --raw /metrics | grep v1beta1.metrics`, the result alternates between
```
aggregator_unavailable_apiservice{name="v1beta1.metrics.k8s.io"} 1
aggregator_unavailable_apiservice_count{name="v1beta1.metrics.k8s.io",reason="FailedDiscoveryCheck"} 1
aggregator_unavailable_apiservice_count{name="v1beta1.metrics.k8s.io",reason="MissingEndpoints"} 3
```
and
```
aggregator_unavailable_apiservice{name="v1beta1.metrics.k8s.io"} 0
aggregator_unavailable_apiservice_count{name="v1beta1.metrics.k8s.io",reason="FailedDiscoveryCheck"} 1
aggregator_unavailable_apiservice_count{name="v1beta1.metrics.k8s.io",reason="MissingEndpoints"} 1
```

It looks like EKS is running two masters that are out of sync(?)

**Comment by gabecazares-cc** [comment]
Bump. Also seeing this on EKS-deployed instances of this chart.

**Comment by JaseKirby** [comment]
This issue still persists, I am seeing it in `v1.17.17` kubernetes clusters with chart `kube-prometheus-stack` at `v14.9.0`. Looks like a regression caused by https://github.com/prometheus-community/helm-charts/commit/363ab9b6df5f319b3324f07ca4c230216b1ca857#diff-7c0e8dd2f9bb4e9c7a7d5222fd65e07369c01acdb57413ea0fa3b9acaf571929

**Comment by Arkessler** [comment]
I am also seeing this on K8s `v1.17.6`

**Comment by jandersen-plaid** [comment]
Confirming that this is an issue with v1.17.17 as well -- the root issue seems to be that the semver check was not added to the syncing script, so a new release wiped it all out. the linked PR above should fix the regression.

**Comment by yasinlachiny** [comment]
I am also seeing this on K8s v1.22.12

**Comment by sgremyachikh** [comment]
I see the same in v1.28.3

**Comment by sgremyachikh** [comment]
check your NetworkPolicy, because you could hurt yourself by your NetworkPolicies
