### ISSUE TITLE
[prometheus-kafka-exporter] Kafka exporter chart not propagating service labels

### ISSUE THREAD

**Issue by isac-seven** [prometheus-community/helm-charts#1222]
### Is your feature request related to a problem ?

The prometheus-kafka-exporter chart is not propagating service labels, which are useful if you need specific custom labels to your exporter.

### Describe the solution you'd like.

This is done by other charts like [mongodb exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mongodb-exporter/templates/service.yaml#L10
) and [mysql exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/templates/service.yaml#L7).

Also, we need to add [targetLabels](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/templates/servicemonitor.yaml#L19) in the service monitor to propagate the labels.

References:
* https://stackoverflow.com/questions/63852779/how-to-set-a-label-in-service-monitor-so-it-appears-in-prometheus-metrics

### Describe alternatives you've considered.

NONE

### Additional context.

I might open a PR myself when I get the time to do it

**Comment by gkarthiks** [comment]
hi @isac-seven Please feel free to open a PR. I'll be happy to review it.
