### ISSUE TITLE
[kube-prometheus-stack] Bump Grafana chart version

### ISSUE THREAD

**Issue by 1001v** [prometheus-community/helm-charts#1252]
### Is your feature request related to a problem ?

Not quite, it's about Grafana's problem.

### Describe the solution you'd like.

Hello. I'd like you to bump Grafana chart version to 6.15.0, if it's possible, because in version 6.14 (Grafana Dashboard 8.0.5) I have the following issue related to Grafana: https://github.com/grafana/grafana/issues/25205. Thank you.

### Describe alternatives you've considered.

NONE

**Comment by the-scott-hand** [comment]
We would also like this updated asap. Not sure how much more is needed than just bumping the version, tossed out a barebones pull request to maybe help get the ball moving https://github.com/prometheus-community/helm-charts/pull/1263
