### ISSUE TITLE
[prometheus-snmp-exporter] Missing imagePullSecrets property

### ISSUE THREAD

**Issue by AlejandroGarcia95** [prometheus-community/helm-charts#1254]
### Describe the bug a clear and concise description of what the bug is.

Prometheus SNMP exporter Helm chart is missing the `imagePullSecrets` property. This prevents users from setting their own private Docker registry and download the SNMP exporter image from it.

### What's your helm version?

version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

0.1.4

### What happened?

The Prometheus SNMP exporter pod cannot be initiated as it remains on `ImagePullBackOff`.

### What you expected to happen?

That the chart will use the `imagePullSecrets` to download the image.

### Enter the changed values of values.yaml?

```yaml
prometheus-snmp-exporter:
  image:
    repository: gcr.io/myprivateproject/private-snmp-exporter
    tag: latest
    imagePullSecrets:
    - name: my-pull-secret
```

### Enter the command that you execute and failing/misfunctioning.

`helm install -f myvalues.yaml my-snmp-exporter prometheus-community/prometheus-snmp-exporter`

### Anything else we need to know?

The fix is simply to add the `imagePullSecrets` property on `helm-charts/charts/prometheus-snmp-exporter/templates/deployment.yaml` like in other charts:

```yaml
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
    {{- end }}
```

**Comment by jvleminc** [comment]
Still not fixed :-(
