### ISSUE TITLE
[prometheus-kube-stack] Override default configs of kubernetes-mixin

### ISSUE THREAD

**Issue by shaikatz** [prometheus-community/helm-charts#126]
**Describe the bug**
I'm trying to migrate into `prometheus-kube-stack` from `kubernetes-mixin` and I've found that I cannot override any jsonnet configs, few examples:

- My prometheus setup doesn't use `cluster` label as the cluster identifier.
It uses `source_cluster`.
- I want to override the default dashboard refresh interval using this [config](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/e9916660bd4a15fc72bb6debbaf5c41dec22d2ae/config.libsonnet#L71)

How can I still use this chart with ability to configure the mixin?

**Comment by nlamirault** [comment]
Any news ?
