### ISSUE TITLE
[kube-prometheus-stack] Disable default metric endpoint for kubelet

### ISSUE THREAD

**Issue by nikhil-bhat** [prometheus-community/helm-charts#1267]
### Is your feature request related to a problem ?

I want to disable default metric endpoint for kubelet servicemonitor 

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml

Similar to how resource and cadvisor endpoints can be enabled or disabled i want to have the ability for default endpoint as well

### Describe the solution you'd like.

will use something like this to enable disable this block inside servicemonitor for kubelet
```
{{- if .Values.kubelet.serviceMonitor.defaultmetrics }}
- port: https-metrics
    scheme: https
    {{- if .Values.kubelet.serviceMonitor.interval }}
    interval: {{ .Values.kubelet.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.kubelet.serviceMonitor.proxyUrl }}
    proxyUrl: {{ .Values.kubelet.serviceMonitor.proxyUrl }}
    {{- end }}
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
{{- if .Values.kubelet.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.kubelet.serviceMonitor.metricRelabelings | indent 4) . }}
{{- end }}
{{- if .Values.kubelet.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.kubelet.serviceMonitor.relabelings | indent 4 }}
{{- end }}
{{-end}}
```

### Describe alternatives you've considered.

using a fork which imo is a bad idea

**Comment by DanielShor** [comment]
+1. This will be very useful for us as well.

**Comment by nikhil-bhat** [comment]
@marquezika can you have a look

**Comment by yaron-idan** [comment]
+1. This will be very useful for us as well.
