### ISSUE TITLE
[prometheus-cloudwatch-exporter] Implement imagePullSecrets

### ISSUE THREAD

**Issue by rcjames** [prometheus-community/helm-charts#129]
**Is your feature request related to a problem? Please describe.**
`imagePullSecrets` allows us to pull docker images from registries using authorized credentials. Ahead of Docker Hub [introducing rate limiting restrictions](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/) on anonymous users as of the 1st November, it would be useful to use an authenticated user when pulling docker images.

`imagePullSecrets` has already been implemented in other charts in this repo (see [prometheus](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L7-L8)) so hopefully it is straightforward to add elsewhere. This could be added it to all the charts.

**Describe the solution you'd like**
A value to exist in the prometheus-cloudwatch-exporter chart which allows usage of `imagePullSecrets` on deployments, as has already been implemented in prometheus server manifests: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/sts.yaml#L157-L160
```
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
       {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
```

**Describe alternatives you've considered**
A mutating admission controller webhook, but this is less direct and therefore less ideal.

**Comment by torstenwalter** [comment]
@rcjames Sorry this issue passed by unnoticed. PR for this is welcome!
