### ISSUE TITLE
[prometheus-blackbox-exporter] serviceMonitor.enabled doesn't include a ServiceMonitor for the exporter itself

### ISSUE THREAD

**Issue by jeffa5** [prometheus-community/helm-charts#1307]
### Describe the bug a clear and concise description of what the bug is.

When setting `serviceMonitor.enabled: true` for the blackbox exporter I'd expect it to generate a service monitor for the exporter itself. The targets would then be used for extra servicemonitors.

### What's your helm version?

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

### What's your kubectl version?

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} 
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"2afe6eb5d9a37633abc5eb2eaf17959b9528bea7", GitTreeState:"clean", BuildDate:"2021-06-03T00:13:11Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

5.0.3

### What happened?

No service monitor was created for the exporter's metrics.

### What you expected to happen?

A service monitor was created for the exporter's metrics.

### How to reproduce it?

Deploy the helm chart with values `serviceMonitor.enabled: true`.

### Enter the changed values of values.yaml?

```yaml
serviceMonitor:
  enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i blackbox-exporter prometheus-community/prometheus-blackbox-exporter --version 5.0.3 --values values.yaml

**Comment by jindrichskupa** [comment]
Do you have installed https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack before?

**Comment by jeffa5** [comment]
Yes, I do. The CRD for `ServiceMonitor` exists but it just doesn't create one.

**Comment by OneCricketeer** [comment]
If you have no targets defined, no resources will be created - https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml#L2
