### ISSUE TITLE
[prometheus-alertmanager] custom email notification template struggles

### ISSUE THREAD

**Issue by cuzzo333** [prometheus-community/helm-charts#131]
**Describe the bug**
I am attempting to create a custom email notification template for Alertmanager alerts and there seems to be a glaring lack of support and guidance on how to do this.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
v3.1.2
```

Kubernetes Version:

```console
$ kubectl version
v1.15.11
```

**Which chart**: prometheus (alertmanager templates)
**Which version of the chart**: 11.15.0

**What happened**:
Besides the huge gap in really any documentation on both the official Prometheus site as well as community forums, I'm really struggling to create a custom notifications template for our Alertmanager instance.  I've been given a task to customize a template because the default template is too "noisy" which is understandable, it's just a default.

**Volume mounting support**
The first issue I ran into was that the Alertmanager deploy.yaml template doesn't support mounting extra volumes to the alertmanager pod, such as mounting a `configMap` which would contain my custom notification template data.  The Prometheus server deployment supports this but not Alertmanager.  I've worked around this by customizing the deploy.yaml template file to include the necessary syntax to allow for mounting additional volumes.  I intend to open a separate issue for this so that we can hopefully get a PR created to fix this.

**Writing the template**
The second and larger issue is with actually writing the template itself.  I'm fairly comfortable with Go templating but wouldn't say I'm an advanced user. I am attempting to customize the labels that are sent in the email subject and body since the default template seems to range over all labels present in the alert and that's what is sent in the email. 

Since Prometheus label context can change based on the metric (the `instance` label for example might return an IP address for one metric but return a URL for another metric) I am attempting to put some conditional logic into our template so that depending on the alert that was triggered, the email content is a bit more specific to that alert.  

For example if we receive an alert on a pod, the `instance` label is useless to us so we'd like that label data to not be present in the email.  For other alerts, such as those triggered by the Prometheus Blackbox Exporter, the `instance` label returns data we do want.  This then continues for the different types of alerts coming in that I need to implement conditional logic for.

Where this all seems to be going wrong is that Alertmanager doesn't seem to be happy with much of the functions I am attempting to pass in.  These include `define`, `len`, `toUpper`, etc.  I even have issues when I take the raw output of the default.tmpl (found here [https://github.com/prometheus/alertmanager/blob/master/template/default.tmpl](url)) and have that mounted to my Alertmanager pod.  After doing this I received the below error as an example:
```
ts=2020-09-22T22:35:19.187Z caller=coordinator.go:137 component=configuration msg="one or more config change subscribers failed to apply new config" file=/etc/config/alertmanager.yml err="failed to parse templates: template: custom.tmpl:131: unexpected <define> in command"
level=info ts=2020-09-22T22:35:19.187Z caller=cluster.go:632 component=cluster msg="gossip not settled but continuing anyway" polls=0 elapsed=26.788781ms
```
Another example, this generated from copying and pasting much of the default.tmpl syntax and modifying a few things returns the following error:
```
level=error ts=2020-09-22T22:28:09.335Z caller=notify.go:372 component=dispatcher msg="Error on notify" err="cancelling notify retry for \"email\" due to unrecoverable error: execute \"Subject\" header template: template: custom.tmpl:4:38: executing \"__subject\" at <toUpper>: invalid value; expected string" context_err=null
level=error ts=2020-09-22T22:28:09.336Z caller=dispatch.go:301 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="cancelling notify retry for \"email\" due to unrecoverable error: execute \"Subject\" header template: template: custom.tmpl:4:38: executing \"__subject\" at <toUpper>: invalid value; expected string"
```
I would be more than happy to include an example of a template I've tried to write and use but at this point I'm all over the place with adding a template, seeing what error is generated, try to resolve it, rinse and repeat.  I ultimately feel like there's a critical step I'm missing throughout this entire process and based on the lack of documentation, lack of similar issues raised online, and not a huge amount of template examples posted anywhere, it seems that this isn't something that is commonly being done?

I'll take any advice at this part because for a task such as customizing an email template I've spent far too much time already both solving technical challenges with Alertmanager as well as working my through how to do this without much external information to guide me.  

Is there simply a better way to go about this or some resources I'm missing that could give guidance on how to write these templates, the different parts of the template that support different data structurs and functions?  I found this documentation [https://prometheus.io/docs/alerting/latest/notifications/](url) and while I understand it, it ultimately hasn't really helped too much.

Thanks!

**Comment by scottrigby** [comment]
@cuzzo333 did you find a solution to your issue?
