### ISSUE TITLE
[prometheus-redis-exporter] Cannot Upgrade Due to Version in the Selector 

### ISSUE THREAD

**Issue by Gentoli** [prometheus-community/helm-charts#1333]
### Describe the bug a clear and concise description of what the bug is.

Introduced in https://github.com/prometheus-community/helm-charts/pull/1322, the `deployment.sepc.selector` now included a `chart` field which encodes the chart version (like `prometheus-redis-exporter-4.5.0`). This will be updated whenever a new version of the chart is released but `deployment.sepc.selector` is immutable.

### What's your helm version?

version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.12-gke.2100", GitCommit:"82b41aad731f2dda24cc5ca99e09328163474782", GitTreeState:"clean", BuildDate:"2021-07-16T09:23:20Z", GoVersion:"go1.15.13b5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-redis-exporter

### What's the chart version?

4.5.0

### What happened?

if `deployment.sepc.selector.chart` is being updated, Kubernetes give:

```
deployments.apps "redis-metrics-exporter-prometheus-redis-exporter" was not valid:
 * spec.template.metadata.labels: Invalid value: map[string]string{"app":"prometheus-redis-exporter", "chart":"prometheus-redis-exporter-4.5.0", "heritage":"Helm", "release":"redis-metrics-exporter"}: `selector` does not match template `labels`
 * spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"prometheus-redis-exporter", "chart":"prometheus-redis-exporter-4.5.1", "heritage":"Helm", "release":"redis-metrics-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

### What you expected to happen?

Chart to upgrade

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade -n monitor redis-metrics-exporter prometheus-community/prometheus-redis-exporter --reuse-values`

From 4.3.0 to 4.5.0

**Comment by monotek** [comment]
delete the deployment, using "--cascade=false", so the pods are not deleted, before running the helm upgrade....

**Comment by Gentoli** [comment]
I was able to upgrade to `prometheus-redis-exporter-4.6.0` without this issue!
