### ISSUE TITLE
[prometheus] Update kube-state-metrics dependency from 3.4.* to 3.5.*

### ISSUE THREAD

**Issue by waterdrop01** [prometheus-community/helm-charts#1344]
### Is your feature request related to a problem ?

kube-state-metrics version 2.1.1 isn't fully compatible with Kubernetes 1.22 ([source](https://github.com/kubernetes/kube-state-metrics))
![Screenshot from 2021-09-15 00-50-09](https://user-images.githubusercontent.com/47316824/133344067-43677232-a693-4ceb-a4d2-dbe5b82b98df.png)

### Describe the solution you'd like.

Update kube-state-metrics dependency from `3.4.*` to `3.5.*` as it includes `kube-state-metrics@v2.2.0`

### Describe alternatives you've considered.

Thanks for your time! @agermain

**Comment by monotek** [comment]
Would you mind to create an pr please?

**Comment by waterdrop01** [comment]
@monotek https://github.com/prometheus-community/helm-charts/pull/1363

-> Didn't bump the chart version as I'm not sure which version's decimal should be incremented

**Comment by monotek** [comment]
Just follow semver ;)
https://semver.org
