### ISSUE TITLE
 prometheus-node-exporter daemonset tolerations

### ISSUE THREAD

**Issue by spothound** [prometheus-community/helm-charts#1347]
### Is your feature request related to a problem ?

Hello there,

I have some nodes in my K8s cluster with `NoExecute` taints. This prevents my `kube-prometheus-stack-prometheus-node-exporter` daemonset pods from being scheduled in those nodes.

### Describe the solution you'd like.

I was looking for a way to add a toleration for those pods and I found that there is already a generic toleration:

```
tolerations:
  - effect: NoSchedule
    operator: Exists
```
See https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L133

This is OK but to ignore all `NoSchedule` taints but won't be enough for `NoExecute` taints. An option would be to update the toleration to

```
tolerations:
  - operator: Exists
```

### Describe alternatives you've considered.

I think that the chart should have an option to ignore all taints or to add custom tolerations, or maybe the mentioned toleration should be updated to:

Another option would be to add an option to create custom tolerations for the pods or a boolean option to make pods tolerate all taints.

**Comment by monotek** [comment]
It's in the values file so you can just change it like you want?
Or use set in your helm commnad
```
helm install prometheus-node-exporter prometheus-comunity/prometheus-node-exporter --set tolerations[0].operator=Exists
```
