### ISSUE TITLE
[prometheus] Allow for pushgateway.userClusterRole = false

### ISSUE THREAD

**Issue by ecerulm** [prometheus-community/helm-charts#136]
**Is your feature request related to a problem? Please describe.**
As I understand, the current helm chart requires ClusterAdmin permission because it will deploy ClusterRole (if rbac =true). 
alertmanager has a `alertmanager.userClusterRole=false` 

**Describe the solution you'd like**
I wish I had a `pushgateway.useClusterRole=false` equivalent to `alertmanager.useClusterRole` 

**Describe alternatives you've considered**

**Additional context**

I haven't investigated much but I'm guessing there is no real need for pushgateway to have a ClusterRole?

**Comment by gkarthiks** [comment]
@ecerulm apologies for the delayed response. To get the response quickly, please follow the Issue templates.

To your question, yes. Only if your push gateway needs to communicate across namespace. Please feel free to raise a PR. We will review and proceed accordingly.
