### ISSUE TITLE
[prometheus-kube-stack kube-prometheus-stack-18.0.11] Not able to update the tsdb storage path

### ISSUE THREAD

**Issue by puneetmathur-87** [prometheus-community/helm-charts#1379]
### Describe the bug a clear and concise description of what the bug is.

There is no option to update the --storage.tsdb.path parameter for the Prometheus. I could  find the option to update the retention, log leve, log format etc but nop option to update the storage path.

Please suggest.

### What's your helm version?

3.6.3

### What's your kubectl version?

v1.20.10+IKS

### Which chart?

kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-18.0.11

### What happened?

There is no option to update the --storage.tsdb.path parameter for the Prometheus. I could  find the option to update the retention, log leve, log format etc but nop option to update the storage path.

Please suggest.

### What you expected to happen?

There must be an option or some other way to provide/update the tsdb path.

### How to reproduce it?

Install the chart with specific values file.

### Enter the changed values of values.yaml?

alertmanager:
  enabled: false
grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: ["", ]
    path: /
    tls:
      - secretName: prometheus-tls
        hosts: ["", ]
prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: ["", ]
    paths:
      - /
    tls:
      - secretName: prometheus-tls
        hosts: ["", ]
  prometheusSpec:
    retention: 10d
    securityContext:
      runAsGroup: 2000
      runAsNonRoot: false
      runAsUser: 1000
      fsGroup: 2000
      fsGroupChangePolicy: "OnRootMismatch"
    volumes:
      - name: sd-pv
        persistentVolumeClaim:
          claimName: sd-pv-claim
    volumeMounts:
      - name: sd-pv
        mountPath: /sd/config
    configMaps: 
      - "prometheus-sd-scrape"
    additionalScrapeConfigs:
      - job_name: 'service-discovery'
        scrape_interval: 30s
        file_sd_configs:
          - files:
            - '/sd/.=config/sd.json'

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-operator prometheus-community/kube-prometheus-stack --values .\values.yaml

**Comment by felipem1210** [comment]
Same here, any solution?

**Comment by arielvinas** [comment]
I've been trying to modify `--storage.tsdb.max-block-duration=2h` to a smaller size, without any luck as well. I tried editing the created statefulset manually, but it keeps regenerating the 2h size

**Comment by felipem1210** [comment]
According to ![PrometheusCRD-Spec](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) you can modify the container prometheus inside the StatefulSet created by the operator.
I added this part to Prometheus CRD, inside spec and saw modified the args in container:

`    containers:
    - args:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=120d
      - --web.enable-lifecycle
      - --web.external-url=http://kube-prometheus-stack-prometheus.prometheus-stack:9090
      - --web.route-prefix=/
      - --web.config.file=/etc/prometheus/web_config/web-config.yaml
      - --storage.tsdb.max-block-duration=2m
      - --storage.tsdb.min-block-duration=2m
      name: prometheus `

The point is that the chart is not permitting add container configuration in the Prometheus spec

**Comment by felipem1210** [comment]
#1512
