### ISSUE TITLE
[prometheus-blackbox-exporter] config.file values is not correct when providing secret to use

### ISSUE THREAD

**Issue by MCyprien** [prometheus-community/helm-charts#138]
**Describe the bug**

We are using SealedSecret to manage our secrets on our clusters and also the secret containing the blackbox-exporter configuration because it contain basic auth credentials.

The creation of the secret is managed outside the chart so I set :
```
secretConfig: true
config: false
```

the secret is mounted in the pod but the `--config.file` match `/etc/blackbox_exporter/config.yml` instead of the mounted secret `/config/blackbox.yaml`

**Which chart**: prometheus-blackbox-exporter
**Which version of the chart**: 4.5.1

**How to reproduce it** (as minimally and precisely as possible):
create a secret outside the chart, and set :
```
secretConfig: true
config: false
```

**Comment by fmtbkgiddiqq** [comment]
bump
