### ISSUE TITLE
[kube-prometheus-stack] Grafana Alert Notifiers

### ISSUE THREAD

**Issue by linxcat** [prometheus-community/helm-charts#1381]
### Is your feature request related to a problem ?

It is not currently possible to include alert notifiers (already configurable from the grafana chart) in the vales for kube-prometheus-stack. The severely hampers the effectiveness of grafana usability.

### Describe the solution you'd like.

Include a values field in which one can pass notifiers in the same format as already exists in the grafana chart.

### Describe alternatives you've considered.

- Figuring out where the grafana chart automatically reads configuration from and mounting data there via a sideload of some sort
- Including alerting endpoints within dashboards, which can be included in automation via a configmap

### Additional context.

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L472

**Comment by steven-sheehy** [comment]
As Grafana is a sub-chart of kube-prometheus-stack, any value supported by the sub-chart can be set via values.yaml. Just because it's not explicitly in the kube-prometheus-stack values.yaml doesn't mean it's not supported. You would just do:

```yaml
grafana:
  notifiers:
    ...
```
