### ISSUE TITLE
Installing on kubernetes 1.21.2 gives error on fresh install due to usage of policy/v1beta1

### ISSUE THREAD

**Issue by mariusandersen** [prometheus-community/helm-charts#1386]
Using helm install on prometheus-community/kube-prometheus-stack on kubernetes 1.21.2 gives many warnings. In our case we do this using Azure DevOps build and the log has many warnings like this:

`W0930 08:26:58.656126    1843 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

Eventually it gives an error on this warning:

`##[error]W0930 08:26:47.154610    1843 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

The same pipeline using latest version of prometheus-community/kube-prometheus-stack on kubernetes version 1.20.5 works OK. 

EDIT: To clarify, the installation also is a success, but helm writes these errors to **stderr** and the build will indicate failure.

Issue:
policy/v1beta1 will be deprecated in favor of policy/v1. Even though it's supposed to be just a warning until 1.25, it throws an error event stopping the installation of prometheus.

Suggested solution:
This kind of logic for policy version selection:
https://github.com/prometheus-community/helm-charts/blob/383b15a4c60f8cc33975f90d8e705e72052d6713/charts/prometheus/templates/_helpers.tpl#L187-L195

**Comment by glloyd2010f** [comment]
Can confirm this as well. It also happens with batch endpoint. Can the CRDs be updated to leverage the /v1 API instead of the /v1beta1 API?

**Comment by glloyd2010f** [comment]
@stevehipwell mainly seeing it with the PodSecurityPolicy. I have included a code snippet below. Sorry about the items being stared out, however Azure DevOps likes to hide stuff.

`1978 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.***1+, unavailable in v1.***+`

**Comment by stevehipwell** [comment]
@glloyd2010f it's a warning that PSPs have been deprecated in your version and will be removed in v1.25. You should be able to turn the PSP off with a value or live with the warning. See the K8s v1.21 release notes and accompanying blog posts for more details.

**Comment by glloyd2010f** [comment]
@stevehipwell thank you for the follow up!

**Comment by pkit** [comment]
For everyone that stumbles upon this one:

```yaml
kube-state-metrics:
  podSecurityPolicy:
    enabled: false
global:
  rbac:
    pspEnabled: false
prometheus-node-exporter:
  rbac:
    pspEnabled: false
grafana:
  rbac:
    pspEnabled: false
```

**Comment by FrediWeber** [comment]
Can we disable PSPs by default as these are deprecated?
