### ISSUE TITLE
[prometheus] Bump up chart version

### ISSUE THREAD

**Issue by SeungjinYang** [prometheus-community/helm-charts#1403]
### Is your feature request related to a problem ?

I want to use http_sd_config introduced in v2.28 but the chart currently supports v2.26 - I would appreciate if the prometheus image version was bumped up so I can use the latest features

### Describe the solution you'd like.

Bump up chart version similar to https://github.com/prometheus-community/helm-charts/pull/833

### Describe alternatives you've considered.

NONE

**Comment by driv** [comment]
Should we expect updates on the version? I see that the last one happened 6 months ago.

https://github.com/prometheus-community/helm-charts/blame/main/charts/prometheus/values.yaml#L645

**Comment by monotek** [comment]
Feel free to add an pr updating all containers :)

**Comment by vitaliyf** [comment]
@monotek I'm happy to bump the version - is there a policy on what version we should upgrade to?

Looks like:
- [charts/prometheus](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/Chart.yaml#L3) uses 2.26.0
- [charts/kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2058) uses 2.28.1 and there is #1397 to bump it to 2.30.3
- Latest version of Prometheus is 2.31.1, released yesterday (bugfix for 2.31.0 from a week ago); overall release schedule is [here](https://github.com/prometheus/prometheus/blob/main/RELEASE.md)

**Comment by jack-evans** [comment]
Would make sense to go for the same as in kube-prometheus-stack
