### ISSUE TITLE
[prometheus-kube-stack] Stack doesn't update Grafana image

### ISSUE THREAD

**Issue by drehelis** [prometheus-community/helm-charts#1421]
### Describe the bug a clear and concise description of what the bug is.

Grafana helm chart is a dependency of `prometheus-kube-stack`, when I first installed the stack, Grafana image was `8.1.5`.
Grafana was bumped to `8.2.x` in Grafana's helm chart but when I try to upgrade `prometheus-kube-stack`, Grafana image doesn't change.

I thought maybe I need to wait for `prometheus-kube-stack` version bump to receive dependent charts update but that didn't do the trick either.

Is this behaviour by design? What am I missing?

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

kube-prometheus-stack-19.0.2, kube-prometheus-stack-19.0.3

### What happened?

Grafana image sticks to `8.1.5`

### What you expected to happen?

Grafana image to be updated with the version set by Grafana's helm chart.

### Enter the command that you execute and failing/misfunctioning.

```
helm upgrade --install monitoring \
    prometheus-community/kube-prometheus-stack \
    --values values.yaml \
    --namespace prometheus \
    --create-namespace --dry-run
```

**Comment by elwood218** [comment]
Could someone please check this? I guess it should be easy to raise the version in Chart.lock to minimum of 6.6.12 because there is the new Grafana version which fixed a security issue. 
And if it is not that easy then just please mention it here please.

**Comment by drehelis** [comment]
why is `Chart.lock` locking dependencies to specific version, while in `Chart.yaml` it is set with an asterisk?
Why not just locking the version on Chart.yaml and maintaining only one file for dependencies versions etc.?
Just for my personal knowledge ;-)

**Comment by Atem18** [comment]
Hi, any idea ?
