### ISSUE TITLE
[kube-prometheus-stack] Use sub-chart service monitors

### ISSUE THREAD

**Issue by stevehipwell** [prometheus-community/helm-charts#1425]
### Is your feature request related to a problem ?

The current _kube-prometheus-stack_ chart creates custom service monitors for _prometheus-node-exporter_ and _kube-state-metrics_ despite both charts having built in service monitor support and being in this repo (I know this wasn't always the case). This adds additional complexity and the potential for inconsistent behaviour depending on how these components have been installed.

### Describe the solution you'd like.

I'd think that if the _prometheus-node-exporter_ and _kube-state-metrics_ chart service monitors could be brought up to spec with the bundled ones then they could be removed leaving only one service monitor per service to be maintained.

### Describe alternatives you've considered.

NONE

**Comment by monotek** [comment]
Would you mind to create an pr for that?

**Comment by stevehipwell** [comment]
@monotek sure I can take a look at this. It'd need to be 3 PRs, one each for the sub charts and one for the stack chart.
