### ISSUE TITLE
[kube-prometheus-stack] Unauthenticated /metrics endpoint deprecated in k8s 1.23 

### ISSUE THREAD

**Issue by mac-chaffee** [prometheus-community/helm-charts#1431]
### Is your feature request related to a problem ?

Currently, kube-prometheus-stack deploys ServiceMonitors to scrape metrics from the control plane like kube-scheduler, kube-controller-manager, kube-proxy, etc.

The kube-scheduler\* ServiceMonitor currently scrapes /metrics over HTTP, which will be deprecated in 1.23: https://github.com/kubernetes/kubernetes/blob/v1.23.0-alpha.3/CHANGELOG/CHANGELOG-1.23.md#deprecation

Additionally, I have k8s version 1.21 installed, and by default kube-controller-manager uses HTTPS too. So perhaps they've already started moving away from http-only metrics for other control plane components\*.

### Describe the solution you'd like.

Detect the k8s version in the helm chart to determine the port and protocol used to scrape from control plane components.
The default ports can be found in this file for >1.19: https://github.com/kubernetes/kubernetes/blob/v1.23.0-alpha.3/pkg/cluster/ports/ports.go

And this file for <= 1.19: https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/master/ports/ports.go

### Describe alternatives you've considered.

Setting the following values will fix the problem in kube-controller-manager (tested only in 1.21)

```
kubeControllerManager:
  service:
    port: 10257
    targetPort: 10257
  serviceMonitor:
    https: true
    insecureSkipVerify: true
```
Similar values can be set for other control plane components

### Additional context.

EDIT: Originally misread the changelog and thought they moved kube-controller-manager to port 10259. Edited to reflect that kube-scheduler moved to 10259 (its other insecure port 10251 was deprecated). And seems they've started deprecating all the other insecure ports.

**Comment by monotek** [comment]
would you mind to create an pr for that please?

**Comment by giovannicandido** [comment]
I managed to get kubeControllerManager with the config provided, but what about kube-proxy? I'm not locating the new ports to make kube-proxy scrap to work

**Comment by giovannicandido** [comment]
Looks like the problem is becaus kube-proxy is listening on localhost:
```
 netstat -tnlp | grep kube-proxy
tcp        0      0 0.0.0.0:32443           0.0.0.0:*               LISTEN      4001369/kube-proxy
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      4001369/kube-proxy
tcp        0      0 0.0.0.0:32080           0.0.0.0:*               LISTEN      4001369/kube-proxy
tcp6       0      0 :::10256                :::*                    LISTEN      4001369/kube-proxy
```
curl in localhost works but curl from one of the nodes doesn't.

I will search how to change it in kubespray.
Version of kubernetes is 1.21.6

**Comment by giovannicandido** [comment]
For the record, the process to change the listener is:

If using kubespray to setup the k8s add this line in your inventory k8s-cluster.yaml

```
kube_proxy_metrics_bind_address: 0.0.0.0:10249
```
You can eighter rerun the playbook (which takes at last 30 minutes) or you can change manually:

SSH in the hosts
Edit the file: `/etc/kubernetes/kubeadm-config.yaml` change the line `metricsBindAddress: 0.0.0.0:10249`

Repeat the process for all nodes running kube-proxy

Now run the command:

```
 kubectl --kubeconfig /etc/kubernetes/admin.conf -n kube-system get configmap kube-proxy -o yaml | sed 's/metricsBindAddress: 127.0.0.1:10249/metricsBindAddress: 0.0.0.0:10249/g' | kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f -
```
And restart kube-proxy:

```
kubectl --kubeconfig /etc/kubernetes/admin.conf delete pod -n kube-system -l k8s-app=kube-proxy --force --grace-period=0
```

Test if works, and is done

**Comment by mac-chaffee** [comment]
Still relevant IMO. This issue essentially means that the default scrape settings are broken for kube-controller-manager and kube-scheduler for k8s >= 1.19 (aka the only supported k8s versions).

Haven't worked much more on this since a direct mapping between k8s versions and port numbers is proving difficult since the ports changed slowly over many releases.

If we drop support for k8s v1.18 (already not supported by k8s itself), that would make the fix for this bug a lot easier I think.
