### ISSUE TITLE
[all] weekly issue/PR triage?

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#1437]
### Is your feature request related to a problem ?

Follow-up from https://github.com/prometheus-community/helm-charts/issues/1430

@torstenwalter
> I've noticed that there are quite some PRs, which are stuck e.g. because there is no review from a chart maintainer. In those cases a repo admin could help to review and approve PRs.

There is also an additional problem. Charts are not regularly reviewed for ways to make them simpler for end users and easier to maintain. For example, at the outset of this repo we discussed making charts simpler and offering example post-renderer files to close the use case gap, for folks to see how to accomplish the same customizations while allowing charts to become much simpler. A weekly review of open issues and PRs could encourage working toward this direction again as well. This could be a separate follow-up issue if that feels better to anyone.

### Describe the solution you'd like.

- add an issue/PR triage role to this project - folks who would like to do something like weekly rotation taking responsibility for making sure open issues and PRs are directed to the right people labeled correctly (if needed), and addressed properly.
- Since this repo is so active, see if folks would like to do a regular check-in? If not another virtual meeting, could be a scheduled slack check in?

### Describe alternatives you've considered.

Collaborating on this charts repo completely async. It's been very nice, but PRs are often quite behind.

**Comment by monotek** [comment]
I'm not sure if a regular call would work. At least i could not promise to be available every time.
Maybe some on demant appointments with already known schedule is the better option.

Beside a possible automerge workflow we've discussed earlier, maybe something like the binami common (libary) chart could be a way to make things more generic, for all prometheus community charts. See: https://github.com/bitnami/charts/tree/master/bitnami/common

But i guess it would be better to have an own libary, which is under control in this repo?
But this would be again need some maintenance work. If we fear the work, bitnami common chart might be the way to go anyway?

**Comment by monotek** [comment]
Any thoughts about some prometheus community owned helm library?

**Comment by torstenwalter** [comment]
> Any thoughts about some prometheus community owned helm library?

Could make sense if charts would adopt it. Honestly I am a bit afraid that we would create a library which is the not used by individual charts. Also someone needs to maintain it.

**Comment by MPV** [comment]
Curious what you think about the alternative of [Splitting charts into separate repos (one per chart)](https://github.com/prometheus-community/helm-charts/issues/1531), and how it would affect or improve community maintenance.

**Comment by monotek** [comment]
See my answer in: https://github.com/prometheus-community/helm-charts/issues/1531#issuecomment-979937846
