### ISSUE TITLE
[kube-prometheus-stack] Disable etcdHighNumberOfFailedGRPCRequests

### ISSUE THREAD

**Issue by servo1x** [prometheus-community/helm-charts#144]
**Is your feature request related to a problem? Please describe.**

This etcd alert adds a significant amount of noise because of a false positive being returned by the metric.

**Describe the solution you'd like**
I believe by default, this rule should be disabled, just like how it is in openshift.

**Additional context**
- https://github.com/etcd-io/etcd/pull/10629
- https://github.com/openshift/cluster-monitoring-operator/issues/248#issuecomment-474567273
- https://github.com/etcd-io/etcd/issues/10289

**Comment by atsai1220** [comment]
Running into this scenario too.

**Comment by immanuelfodor** [comment]
Same issue with RKE and Rancher Monitoring V2 stack
