### ISSUE TITLE
[kube-prometheus-stack] AggregatedAPIDown is firing every night for few minutes

### ISSUE THREAD

**Issue by jeggers-88** [prometheus-community/helm-charts#1453]
### Describe the bug a clear and concise description of what the bug is.

Since a few weeks our azure k8s cluster (running kubernetes v1.20.7) every night emits an "AggregatedAPIDown" alert.

The underlying metric for only a few minutes is triggering this alert: 

aggregator_unavailable_apiservice{job="apiserver", name="v1beta1.metrics.k8s.io", service="kubernetes" ...}
 
We searched for corresponding k8s events / container logs etc. but until now we don`t have any idea where this periodic false positive "AggregatedAPIDown" alerts might come from. 
Is maybe something in the kube-prometheus-stack inside running on a nightly periodic schedule, which could  responsible for that ? 
Do you have any hints to solve this problem ?  Any help would really be great! 

### What's your helm version?

3.2.3

### What's your kubectl version?

1.18.20

### Which chart?

17.2.2

### What's the chart version?

17.2.2

### Enter the command that you execute and failing/misfunctioning.

No special command was used.

**Comment by Vandersteen** [comment]
Did you find a solution for this ?
I'm facing the same issue

**Comment by jeggers-88** [comment]
@Vandersteen , we didn't found a solution until now. Maybe we should reopen the ticket ?

**Comment by Xuezenghuigithub** [comment]
Can this issue be reopened? 
We had the same issue.
