### ISSUE TITLE
[prometheus-kube-stack] Issue alertmanagerConfig CRD doesn't have configuration for new version of Alertmanager

### ISSUE THREAD

**Issue by alexponomarevseph** [prometheus-community/helm-charts#1454]
### Describe the bug a clear and concise description of what the bug is.

Last version of Alertmanager 0.22.0+  has the ability to mute alerts based on schedule:
mute_time_intervals (https://github.com/prometheus/alertmanager/issues/876)
But it doesn’t work via AlertmanagerConfig
`error validating data: ValidationError(AlertmanagerConfig.spec): unknown field "mute_time_intervals" in com.coreos.monitoring.v1alpha1.AlertmanagerConfig.spec`

Could you help with this aeustion?

### What's your helm version?

We use ArgoCD

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

18.0.0

### Enter the command that you execute and failing/misfunctioning.

We use GitOPS approach for deployment, and ArgoSD as GitOPS operator

**Comment by mac-chaffee** [comment]
See https://github.com/prometheus-operator/prometheus-operator/pull/4335

Looks like it will be in the next release of prometheus-operator (current release at the time of writing is 0.52)

**Comment by siegenthalerroger** [comment]
Would this also be related to the missing (new) values on the AlertManagerConfig CRD. Specifically in the `matchers` there is now a `matchType` field that isn't available.

**Comment by melkosoft** [comment]
the same for me: I was not able to use "matchers" in alertmanager configuration

**Comment by siegenthalerroger** [comment]
Yeah this was included in one of the newer releases :)

**Comment by pcornelissen** [comment]
But it doesn't seem to work. We have added the mute interval and it was definively validated because we got the syntax wrong at first, but it's not written to the config file. We are using the latest version of the helm chart and prometheus is as a result in version 23+

Any idea, why that is not in the config file?
