### ISSUE TITLE
[prometheus] persistent volume with existing claim is not working

### ISSUE THREAD

**Issue by tplazaro** [prometheus-community/helm-charts#1457]
### Describe the bug a clear and concise description of what the bug is.

Hi, I'm new to prometheus. I've been trying to test persistent volume and I created a PVC manually and updated persistentVolume.existingClaim with the one I created. However, when trying to helm delete the release, and installing again, the metrics data doesn't persist when I do query. I can see that it's still there in /data though, but for some reason, I lost the history of the scraped metrics. Thanks
![image](https://user-images.githubusercontent.com/60155079/138535780-6b981f4b-895c-4e24-98f6-179a82c67d28.png)

### What's your helm version?

3

### What's your kubectl version?

1.19

### Which chart?

prometheus

### What's the chart version?

9.0

### What happened?

Metrics data is not persisting when trying to reinstall Prometheus using helm with setting prometheus.server.persistentVolume.existingClaim

### What you expected to happen?

Metrics data history to persist

### How to reproduce it?

Create PVC manually
helm install prometheus with prometheus.server.persistentVolume.existingClaim
helm delete prometheus 
helm install with prometheus.server.persistentVolume.existingClaim

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus --set prometheus.alertmanager.enabled=false --set prometheus.server.persistentVolume.existingClaim=invsys-prometheus-server --set prometheus.kubeStateMetrics.enabled=false --set prometheus.nodeExporter.enabled=false --set prometheus.pushgateway.enabled=false --set-file prometheus.extraScrapeConfigs=extScrapeConfig.yaml helm-charts/prometheus

**Comment by mohan-nagandlla** [comment]
Hi TIM 
When I see your file owner's name it's still belongs to nobody which menas the persistence not at attached to your Prometheus.
Could you please go through this command

dh -h ---> to see the provisoner 
Kubectl get prometheus -o yaml -n [namespace name] ---> to see the persistence incling in manifest file.
