### ISSUE TITLE
prometheus-operator uses incorrect flag as of version >= 18

### ISSUE THREAD

**Issue by cmagorian** [prometheus-community/helm-charts#1474]
### Describe the bug a clear and concise description of what the bug is.

It looks like the binary for `operator` doesn't use 4 flags that are left in the helm-charts:

```
-config-reloader-cpu-request
-config-reloader-cpu-limit
-config-reloader-memory-request
-config-reloader-memory-limit
```

and instead needs them as

```
-config-reloader-cpu
-config-reloader-memory
```

The values in the request and limit were defined as the same for the defaults.

Dump:

```
flag provided but not defined: -config-reloader-cpu-request
Usage of /bin/operator:
  -alertmanager-default-base-image string
    	Alertmanager default base image (path without tag/version) (default "quay.io/prometheus/alertmanager")
  -alertmanager-instance-namespaces value
    	Namespaces where Alertmanager custom resources and corresponding StatefulSets are watched/created. If set this takes precedence over --namespaces or --deny-namespaces for Alertmanager custom resources.
  -alertmanager-instance-selector string
    	Label selector to filter AlertManager Custom Resources to watch.
  -apiserver string
    	API Server addr, e.g. ' - NOT RECOMMENDED FOR PRODUCTION - http://127.0.0.1:8080'. Omit parameter to run in on-cluster mode and utilize the service account token.
  -ca-file string
    	- NOT RECOMMENDED FOR PRODUCTION - Path to TLS CA file.
  -cert-file string
    	 - NOT RECOMMENDED FOR PRODUCTION - Path to public TLS certificate file.
  -cluster-domain string
    	The domain of the cluster. This is used to generate service FQDNs. If this is not specified, DNS search domain expansion is used instead.
  -config-reloader-cpu string
    	Config Reloader CPU request & limit. Value "0" disables it and causes no request/limit to be configured. (default "100m")
  -config-reloader-memory string
    	Config Reloader Memory request & limit. Value "0" disables it and causes no request/limit to be configured. (default "50Mi")
```

### What's your helm version?

version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4-gke.2300", GitCommit:"b4e407e768299b79bc8ed8edf889f39bac1ea05f", GitTreeState:"clean", BuildDate:"2021-09-14T09:23:05Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-operator

### What's the chart version?

19.2.2

### What happened?

Using the default values caused the prometheus-operator deployment to fail at initialization because the flags were incorrect.

### How to reproduce it?

Generate the kube-prometheus-stack charts from the default values in a fresh namespace.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml --install -create-namespace --namespace=<whatever>

**Comment by mathiasringhof** [comment]
Just hit the same thing and noticed that a default deploy without values work. I somehow ended up with an older values.yaml that pulled in the wrong version of the operator etc.

I tried the values.yaml from github and that worked fine:
https://raw.githubusercontent.com/prometheus-community/helm-charts/a9ee21df9bf490d73997b9efcdbca522778dddb3/charts/kube-prometheus-stack/values.yaml
