### ISSUE TITLE
[prometheus-kube-stack] Annotation-field defined multiple times

### ISSUE THREAD

**Issue by AndersBennedsgaard** [prometheus-community/helm-charts#1493]
### Describe the bug a clear and concise description of what the bug is.

In [templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml#L6), annotations are defined multiple times when using `global.rbac.pspAnnotations`. 
A quick fix is to move lines 13 and 15 up to line 8, and remove lines 11-15.

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

19.2.2

### What happened?

Helm upgrade with `pspAnnotations` used, results in `Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 13: mapping key "annotations" already defined at line 6`

### What you expected to happen?

"Helm upgrade succeeded"

### How to reproduce it?

Set `global.rbac.pspAnnotations` while the Operator is enabled

### Enter the changed values of values.yaml?

```yaml
global:
  rbac:
    pspAnnotations:
      seccomp.security.alpha.kubernetes.io/defaultProfileName: "docker/default"
```

### Enter the command that you execute and failing/misfunctioning.

`helm template test prometheus-community/kube-prometheus-stack --set global.rbac.pspAnnotations='seccomp.security.alpha.kubernetes.io/defaultProfileName: "docker/default"' --debug`

### Anything else we need to know?

PS. in many template files, `{{ include "kube-prometheus-stack.labels" . | indent 4 }}` are placed in the annotations. Shouldn't this be moved up to the labels field?

**Comment by monotek** [comment]
will be fixed with: https://github.com/prometheus-community/helm-charts/pull/1579
