### ISSUE TITLE
[prometheus-elasticsearch-exporter] Upgrade image version to 1.3.0 in helm chart 

### ISSUE THREAD

**Issue by sdwerwed** [prometheus-community/helm-charts#1496]
### Describe the bug a clear and concise description of what the bug is.

The chart is using an old image version. If you would like I could create a PR

### Which chart?

prometheus-elasticsearch-exporter

### What's the chart version?

4.7.0

### What happened?

The chart is using an old image version

### What you expected to happen?

To use the latest 1.3.0 version

**Comment by applike-ss** [comment]
fixed with #1546
