### ISSUE TITLE
[prometheus-kafka-exporter] add imagePullSecrets option

### ISSUE THREAD

**Issue by codehimanshu** [prometheus-community/helm-charts#1506]
### Is your feature request related to a problem ?

Flux agent (v1) keeps fetching meta data for all images, and it rate limits every now and then. This affects other workloads running in the cluster as well

### Describe the solution you'd like.

The template file can have an option of adding image pull secrets if available:
```
{{- if .Values.imagePullSecrets }}
 imagePullSecrets:
 - name: {{ .Values.imagePullSecrets }}
{{- end }}
```

### Describe alternatives you've considered.

Manually editing the deployment using kubectl is an option, but that is something not suggested and impractical (its making fun of the complete gitops concept)

**Comment by monotek** [comment]
Would you mind to create a pr please?

**Comment by codehimanshu** [comment]
Sorry for the delayed response.
Will send a fix ASAP.
