### ISSUE TITLE
[prometheus-kube-stack] Alertmanager's Service label doesn't match the pod label

### ISSUE THREAD

**Issue by renatosis** [prometheus-community/helm-charts#1511]
### Describe the bug a clear and concise description of what the bug is.

When upgrading the CRDs from 0.48.0 to 0.52.0 and deploying the newest version of prometheus-kube-stack 20.0.1 from a 16.9.0, we noticed that the Alertmanager's services LBs were getting a "Connection refused" error. After debbuging, we observed that the service.spec.selector is using a key "app" and the pod's label has an "app.kubernetes.io/name" key. This makes the LB/service unresponsive.

Ref: https://github.com/prometheus-community/helm-charts/blob/09b3de4d351d81841e0d5231dad184e2902ba64f/charts/kube-prometheus-stack/templates/alertmanager/serviceperreplica.yaml#L41

### What's your helm version?

3.1.2

### What's your kubectl version?

v1.16.15

### Which chart?

prometheus-kube-stack

### What's the chart version?

20.0.1

### What happened?

After upgrading prometheus-kube-stack the service LB's became unresponsive given the wrong service.spec.selector or pod's label

### What you expected to happen?

The service's LB should have keep responding normally

### How to reproduce it?

Helm install the kube-prometheus-stack on 20.0.1 version and try to netcat the LB on the port 9093

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install my-release prometheus-kube-stack --version 20.0.1 --values values.yaml

### Anything else we need to know?

This label change might impact on other component/systems of kube-prometheus-stack

**Comment by monotek** [comment]
Would you mind to provide a PR which fixes the problem?

**Comment by renatosis** [comment]
I could provide a PR but I think it requires from you a revision/decision of all components(prometheus, grafana, alertmanager, etc) to make sure this label the selector changed from "app" to "app.kubernetes.io/name"
