### ISSUE TITLE
[kube-prometheus-stack] serviceMonitorSelector with specific label causes all prometheus metrics/queries to fail

### ISSUE THREAD

**Issue by hughhm** [prometheus-community/helm-charts#1513]
### Describe the bug a clear and concise description of what the bug is.

In the helm chart when setting:
```
serviceMonitorSelector:
  matchLabels:
    prometheus: serviceMonitor
```
All metrics suddenly stop being collected and prometheus cannot be queried. Same occurs with all lowercase label value. 

No issues with using `serviceMonitorSelectorNilUsesHelmValues: false` or `true` however it would be nice to select only specific serviceMonitors that do not use the release name.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-eks-d88609", GitCommit:"d886092805d5cc3a47ed5cf0c43de38ce442dfcb", GitTreeState:"clean", BuildDate:"2021-07-31T00:29:12Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

19.1.0

### What happened?

When ServiceMonitor matchlabels selector was added under `prometheusSpec` all metrics stopped being collected and the historical metrics were no longer accessible. The ServiceMonitor with the added label however **were** added to prometheus as targets and i could see they had discovered the ServiceMonitor objects. No apparent issues with the default release label or when setting `serviceMonitor` to `{}`. As soon as the custom label was removed, it all started working again and historical metrics were visible but not during the period that the ServiceMonitor matchlabels selector was applied. 

### What you expected to happen?

ServiceMonitor targets should be picked up and metrics collection and historical data should continue working. 

### How to reproduce it?

Enter the custom `serviceMonitorSelector` as defined below. 

### Enter the changed values of values.yaml?

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: serviceMonitor

### Enter the command that you execute and failing/misfunctioning.

No command, the chart is applied with `argoCD`.

**Comment by nekomaruh** [comment]
Make sure when you are using spec inside prometheus, you have also declare it as common label:

```
commonLabels:
  prometheus: myLabel

prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: myLabel
```

**Comment by hughhm** [comment]
Why do i need to declare it as a common label? I don't want to apply this to all resources:
```
## Labels to apply to all resources
##
commonLabels: {}
# scmhash: abc123
# myLabel: aakkmd
```
