### ISSUE TITLE
[prometheus-kube-stack] Prometheus in Agent Mode

### ISSUE THREAD

**Issue by sherifkayad** [prometheus-community/helm-charts#1519]
### Is your feature request related to a problem ?

Not a problem by any means; rather an enhancement. This issue here is to enable (in the future once all perquisites are met) Prometheus running in the new so-called `agent` mode.

Following the links below:
- The announcement from Prometheus (https://prometheus.io/blog/2021/11/16/agent/) that a new mode of operation `agent` will be available in the next release
- The Issue created and currently WIP at https://github.com/prometheus-operator/prometheus-operator/issues/3989
- The PR related to the issue above at https://github.com/prometheus-operator/prometheus-operator/pull/4417

### Describe the solution you'd like.

Introducing the relevant values in the helm chart to enable Prometheus running in `agent` mode with the possibility to define a remote write endpoint for it once the `prometheus-operator` project enables that

### Describe alternatives you've considered.

maintaining the status quo => running a fully fledged Prometheus Server (+ Thanos Sidecar) in all cattle clusters

**Comment by paulfantom** [comment]
Also kube-prometheus is adding support as soon as prometheus-operator changes land: https://github.com/prometheus-operator/kube-prometheus/pull/1472

**Comment by sherifkayad** [comment]
Reviving this issue ..

**Comment by sherifkayad** [comment]
It seems that as of now, the Prometheus Operator and Kube Promtheus support in a way running Prometheus (with the current CRD) in an agent mode. Yet the separate CRD (e.g. `PrometheusAgent`) is still in design.

@project_maintainers What do you think .. should the Helm Charts start supporting the Agent now and use what's there until the new CRD lands or better wait?

**Comment by monotek** [comment]
i would wait for the final solution.

**Comment by sherifkayad** [comment]
Again keeping this one alive

**Comment by mahmoud-hafez-aws** [comment]
Keeping this issue alive

**Comment by sharathfeb12** [comment]
Again keeping this one alive

**Comment by nikoul** [comment]
> Trying to configure and seeing this error: "field alerting is not allowed in agent mode".
> 
> That field is hardcoded into the code, I don't see how to remove it:
> 
> https://github.com/prometheus-community/helm-charts/blob/ee700113d070664053bb041f97ae5356e6072fe6/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L14-L16

The same issue will happen with the `ruleSelector` field, with this error : "field rule_files is not allowed in agent mode" . It's also hardcoded into the code : https://github.com/prometheus-community/helm-charts/blob/ee700113d070664053bb041f97ae5356e6072fe6/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L206-L207

**Comment by utkuozdemir** [comment]
Looking forward for this feature as well.

**Comment by r12f** [comment]
It will be so nice to have this feature!

**Comment by maxpain** [comment]
Any updates?

**Comment by nedl86** [comment]
I ran into the same problem with the `prometheus` chart so have raised #2290. I suspect that the two will have a very similar solution.

**Comment by mariana-mendes** [comment]
I tried to use the same config as @datlife, but still on the same error `field rule_files is not allowed in agent mode.` Has anyone tried another way?  😢

**Comment by bryanasdev000** [comment]
> I tried to use the same config as @datlife, but still on the same error `field rule_files is not allowed in agent mode.` Has anyone tried another way? cry

I tried the same config in the past for testing and it worked like a charm (thanks @datlife!), just tried again a quick run with a Kind 1.24 cluster (with a false remote, just to check if it starst), overriding just the Prometheus version, and it worked too.

You can check if you are using latest helm chart version (15.12.0) and optionally latest Prometheus version (v2.38.0, setting it via `server.image.tag`).

For the sake of completeness, here are the exact commands:

agent.yaml:

```
server:
  enabled: true
  image:
    tag: v2.38.0
  defaultFlagsOverride:
  - --enable-feature=agent
  - --storage.agent.retention.max-time=30m
  - --config.file=/etc/config/prometheus.yml
  configPath: /etc/config/prometheus.yml

serverFiles:
  prometheus.yml:
    remote_write:
    - url: http://10.138.0.103/api/v1/write
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
    rule_files:


pushgateway:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false

defaultRules:
  create: false

```

cluster.yaml:

```kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: tcp
```

Cluster create:

```
kind create cluster --config cluster.yaml
```

Helm install:

```
helm upgrade --install -n monitoring prometheus prometheus-community/prometheus --version 15.12.0 --create-namespace -f agent.yaml
```

Proofs:

```
$ kubectl get pods -A                

NAMESPACE            NAME                                                READY   STATUS    RESTARTS   AGE
kube-system          coredns-6d4b75cb6d-f4j4x                            1/1     Running   0          61m
kube-system          coredns-6d4b75cb6d-q52f7                            1/1     Running   0          61m
kube-system          etcd-app-cluster-control-plane                      1/1     Running   0          62m
kube-system          kindnet-n6dsx                                       1/1     Running   0          61m
kube-system          kube-apiserver-app-cluster-control-plane            1/1     Running   0          62m
kube-system          kube-controller-manager-app-cluster-control-plane   1/1     Running   0          62m
kube-system          kube-proxy-ms7vv                                    1/1     Running   0          61m
kube-system          kube-scheduler-app-cluster-control-plane            1/1     Running   0          62m
local-path-storage   local-path-provisioner-9cd9bd544-mgdj9              1/1     Running   0          61m
monitoring           prometheus-kube-state-metrics-774f8c7564-8k4px      1/1     Running   0          60m
monitoring           prometheus-node-exporter-54wzh                      1/1     Running   0          60m
monitoring           prometheus-server-f65746fd9-wl9rz                   2/2     Running   0          54m
```

![agent](https://user-images.githubusercontent.com/53131727/188823655-7f9d774c-331c-4c1c-9039-17f742a25d32.png)

**Comment by hoerup** [comment]
still relevant

**Comment by phyber** [comment]
Are there equivalent flags that we can set in Prometheus server mode that make it behave close to the agent mode? A lot of features are lost by not running `prometheus` the `kube-prometheus-stack`.

Or maybe it's possible to run Prometheus in agent mode via the `prometheus` chart, and just use `prometheus-operator` from the `kube-prometheus-stack`?

It would be nice to have a piece of documentation about what we can do while waiting for the `kube-prometheus-stack` stack chart to catch up with the Prometheus Agent mode.

**Comment by hoerup** [comment]
Still relevant

**Comment by sharathfeb12** [comment]
still relevant.

**Comment by clarkezone** [comment]
Still relevant to me

**Comment by kgogolek** [comment]
still relevant to me

**Comment by ranryl** [comment]
still relevant to me

**Comment by alessioga** [comment]
please

**Comment by dnaprawa-capgemini** [comment]
Still relevant for me.

**Comment by clarkezone** [comment]
Please

**Comment by zerodayyy** [comment]
bump

**Comment by philiptrovato** [comment]
Works for me as well. Few more notes on @datlife comments.

1) Need to set a few "defaultFlagsOverride" - what I run below, suspect only the first two are required.

```defaultFlagsOverride: 
  - --enable-feature=agent
  - --storage.agent.retention.max-time=30m
  - --config.file=/etc/config/prometheus.yml
  - --web.enable-lifecycle
  - --enable-feature=expand-external-labels
```

2) Comment out / remove any under "rules_files:"
```
  prometheus.yml:
    rule_files:
    #  - /etc/config/recording_rules.yml
    #  - /etc/config/alerting_rules.yml
    ## Below two files are DEPRECATED will be removed from this default values file
    #  - /etc/config/rules
    #  - /etc/config/alerts
```

3) If there are any other extra flags your setting (--storage.tsdb*), that may not be prom agent compatible, remove them.
Dont know the whole list, whatch out for below.

--storage.tsdb.retention.time --storage.tsdb.retention.size

4) I use to set "extraFlags:" for like "web.enable-lifecycle" and "expand exteral labels" - didnt seem to work any longer. Moved them under "defaultFlagsOverride" and worked aok. Did not poke at it, too much. Suspect thats how the chart is designed to work. If you set "defaultFlagsOverride" - you lose whatever is set by below.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/deploy.yaml#L105
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/sts.yaml#L105

**Comment by onedr0p** [comment]
Appears as this is in the new release of prometheus operator, although it is alpha...

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.64.0

**Comment by suraj2410** [comment]
very much relevant feature

**Comment by alessioga** [comment]
not stale

**Comment by hakuno** [comment]
@hoerup Interesting. Did you added into `serviceMonitorSelector` manually?

**Comment by eshutov** [comment]
@CygnusHyoga Here it is:
```
prometheus:
  agentMode: true
  prometheusSpec:
    remoteWrite:
      - name: ${name}
        url: http://${host}:9090/api/v1/write
```

**Comment by CygnusHyoga** [comment]
> @CygnusHyoga Here it is:
> 
> ```
> prometheus:
>   agentMode: true
>   prometheusSpec:
>     remoteWrite:
>       - name: ${name}
>         url: http://${host}:9090/api/v1/write
> ```

Thanks! It's working :-)
