### ISSUE TITLE
[kube-prometheus-stack] - Specifying additional volumes or volumemounts for Alert Manager is broken

### ISSUE THREAD

**Issue by BryanEllington** [prometheus-community/helm-charts#152]
**Describe the bug**

The fix in [#23047](https://github.com/helm/charts/pull/23047) does not appear to be correct. This issue exists in this new chart as well.

When volumes/volumeMounts are specified, you get:

```console
Error: UPGRADE FAILED: YAML parse error on prometheus-operator/templates/alertmanager/alertmanager.yaml: error converting YAML to JSON: yaml: line 71: did not find expected ',' or ']'
```

One fix is to put the values on the next line:

**Before** (https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/alertmanager.yaml#L110):

`
{{- if .Values.alertmanager.alertmanagerSpec.volumes }}
  volumes: {{.Values.alertmanager.alertmanagerSpec.volumes }}
{{- end }}
{{- if .Values.alertmanager.alertmanagerSpec.volumeMounts }}
  volumeMounts: {{.Values.alertmanager.alertmanagerSpec.volumeMounts }}
{{- end }}
`

**After**
`
{{- if .Values.alertmanager.alertmanagerSpec.volumes }}
  volumes:
{{ toYaml .Values.alertmanager.alertmanagerSpec.volumes | indent 4 }}
{{- end }}
{{- if .Values.alertmanager.alertmanagerSpec.volumeMounts }}
  volumeMounts:
{{ toYaml .Values.alertmanager.alertmanagerSpec.volumeMounts | indent 4 }}
{{- end }}
`

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 9.4.4

**What happened**: See description above

**What you expected to happen**: See description above

**How to reproduce it** (as minimally and precisely as possible):

Specify additional volumes and/or volumemounts for Alert Manager

**Anything else we need to know**:

This issue is the re-opening of https://github.com/helm/charts/issues/22939 in the deprecated chart.

**Comment by BryanEllington** [comment]
Still an issue

**Comment by BryanEllington** [comment]
Still an issue

**Comment by AbrohamLincoln** [comment]
This is still an issue as far as I can tell.
