### ISSUE TITLE
[prometheus-kube-stack] Kubelet Service is not deleted on uninstall

### ISSUE THREAD

**Issue by swiatekm-sumo** [prometheus-community/helm-charts#1523]
### Describe the bug a clear and concise description of what the bug is.

`prometheus-operator` creates a Service for monitoring Kubelets (unless [disabled](https://github.com/prometheus-community/helm-charts/blob/b1b6cf89edc267be936c6c67cce7307491215a87/charts/kube-prometheus-stack/values.yaml#L1542)). However, this Service is not removed on uninstall, nor is It mentioned in the documentation section for manual uninstallation steps. More annoyingly, the respective ServiceMonitor doesn’t use any release-specific labels, resulting in duplicated Kubelet metrics if the chart is uninstalled and then reinstalled with a different release name.

### What's your helm version?

version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.6-3+dd57cd4fdc581a", GitCommit:"dd57cd4fdc581a8331af7f6ff7feaa7b107ff1a6", GitTreeState:"clean", BuildDate:"2021-11-03T10:20:58Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.6-3+dd57cd4fdc581a", GitCommit:"dd57cd4fdc581a8331af7f6ff7feaa7b107ff1a6", GitTreeState:"clean", BuildDate:"2021-11-03T10:16:58Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

20.0.1

### What happened?

The kubelet Service created by `prometheus-operator` wasn't deleted upon uninstalling the Helm release. After installing a differently-named release, metrics from two kubelet Services are recorded by Prometheus.

### What you expected to happen?

That the kubelet Service would be deleted when uninstalling the Chart and/or that Prometheus would only collect metrics from the release-specific Service via the default ServiceMonitors. Alternatively, that the documentation would mention needing a manual uninstallation step for it. 

### How to reproduce it?

```bash
helm install first prometheus-community/kube-prometheus-stack
helm uninstall first prometheus-community/kube-prometheus-stack
helm install second prometheus-community/kube-prometheus-stack
```
Then to see both services:
```bash
kubectl get svc -n kube-system --selector=k8s-app=kubelet --no-headers -o custom-columns=":metadata.name"
```
And to see the duplicated metrics:
```bash
curl -G http://localhost:9090/api/v1/query?query=kubelet_running_pods
```
Assuming Prometheus is forwarded to localhost on the default port.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

```bash
helm install first prometheus-community/kube-prometheus-stack
helm uninstall first prometheus-community/kube-prometheus-stack
helm install second prometheus-community/kube-prometheus-stack
```

### Anything else we need to know?

As the chart explicitly sets the service name and namespace, deleting it should be straightforward, though rather awkward. The old prometheus-operator chart cleaned up CRDs [this way](https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus-operator/cleanup-crds.yaml).

Alternatively, prometheus-operator allows setting labels on all resources it creates via a [command-line argument](https://github.com/prometheus-operator/prometheus-operator/blob/35c9101c332b9371172e1d6cc5a57c065f14eddf/cmd/operator/main.go#L185). If we put some release-specific labels there and scoped the respective [ServiceMonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kubelet/servicemonitor.yaml#L169) to them, we'd avoid the duplicated metrics.

I don't think there's any mention of this in the documentation, but this also illustrates a problem - downstream charts need to reproduce this warning in their own documentation, which isn't ideal.

**Comment by pmalek-sumo** [comment]
I believe that's not stale :)

**Comment by swiatekm-sumo** [comment]
FYI I can submit a PR to fix this, but I'd like to get some feedback on the suggested approaches. My go to would be to scope the ServiceMonitors to only the specific release and document the fact that the old services need to be deleted manually.

**Comment by kanhayaKy** [comment]
Any update on this bug?
The services are still not being deleted and I'm not sure if there's any other component that's not being deleted. If anybody is aware, please let me know .

**Comment by HummingMind** [comment]
This should be reopened. Still an issue.
In fact, a k8s Service gets created for the Kubelet, even if kubelet.eanbled is set to false in the helm chart.

**Comment by gireassen** [comment]
How to set up metrics collection with Kubelet, which runs as a Linux service?

```
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/0 (0/6 up)
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/1 (0/6 up)
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/2 (0/6 up)
```

**Comment by gireassen** [comment]
> How to set up metrics collection with Kubelet, which runs as a Linux service?
> 
> ```
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/0 (0/6 up)
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/1 (0/6 up)
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/2 (0/6 up)
> ```

found a solution [here](https://www.henryxieblogs.com/2018/11/how-to-fix-server-returned-http-status.html)

**Comment by pistle99** [comment]
Still an issue causing me a headache when using with terraform, because the ApiService keeps a namespace from being destroyed.
