### ISSUE TITLE
[alertmanager] missing maintainer

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#153]
**Describe the bug**
@monotek you're in the CODEOWNERS file for `alertmanager` but not in the `maintainers` list in Chart.yaml. I'm guessing this was an oversight since you added an approving review on the PR to add the chart. Correct me if I'm wrong about that though and you don't want to co-maintain it.

**Proposed solution**
Open a PR adding @monotek to the `alertmanager` Chart.yaml `maintainers` list.

**Anything else we need to know**:
See:
- https://github.com/prometheus-community/helm-charts/pull/147#discussion_r496169594
- and https://github.com/prometheus-community/helm-charts/pull/64#issuecomment-699707917

**Comment by monotek** [comment]
Thanks for the hint. 
I'll do it later today...

**Comment by monotek** [comment]
Oops. Forgot this one but it's solved anyway :)
