### ISSUE TITLE
[prometheus-kube-stack / prometheus-pushgateway] Missing securityContext in podSpec

### ISSUE THREAD

**Issue by saginoibaor** [prometheus-community/helm-charts#1530]
### Describe the bug a clear and concise description of what the bug is.

In both prometheus-kube-stack and prometheus-pushgateway the securityContext in the helm chart is for the podSpec and not for the container spec, therefore it is not possible to set allowPrivilegeEscalation=false on the container spec securityContext.
This makes it possible for the parent process to start a child process with elevated privileges, giving the child process elevated privileges on the host machine.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"32a137c122b0474c719988922410f4027a4b002e", GitTreeState:"clean", BuildDate:"2021-11-01T16:43:17Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack: 17.1.1 / prometheus-pushgateway: 1.11.0

### What's the chart version?

prometheus-kube-stack:  / prometheus-pushgateway

### What happened?

Unable to set allowPrivilegeEscalation=false on container spec

### What you expected to happen?

Set allowPrivilegeEscalation=false on container spec

### How to reproduce it?

No option to pass allowPrivilegeEscalation=false on container spec in helm charts value file

### Enter the changed values of values.yaml?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

N/A

**Comment by GlenColby** [comment]
This also prevents setting capabilities: deny: -All as well, which causes Microsoft Defender and other tools to flag the container as unsafe
