### ISSUE TITLE
Splitting charts into separate repos (one per chart)

### ISSUE THREAD

**Issue by MPV** [prometheus-community/helm-charts#1531]
### Is your feature request related to a problem ?

I'm always frustrated when I try to compare changes between chart versions using the GitHub web.

For example, doing something like this isn't very helpful when quickly trying to determine differences in `kube-prometheus-stack` between two versions: https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-17.2.2...kube-prometheus-stack-18.1.1 (as it shows diffs for many charts having changed between those tags)

### Describe the solution you'd like.

Each chart moved to its own separate repository (since each one has its own lifecycle).

For example from:
`prometheus-community/helm-charts/charts/kube-prometheus-stack`
Into:
`prometheus-community/helm-chart-kube-prometheus-stack`

### Describe alternatives you've considered.

Cloning the repo locally and diffing between tags in particular folders solves this particular issue, but it's not very "shareable" compared to just sending a link to the GitHub web diff between versions.

### Additional context.

Curious to hear your thoughts on this.

**Comment by monotek** [comment]
Sorry, but i don't like the idea. 
Would be to much overhead for the maintainers. 
Alone having to maintain the same CI job over and over again. 
Would also be unnecessary breaking change for all users.
