### ISSUE TITLE
prometheus-postgres-exporter Service monitor label not applied

### ISSUE THREAD

**Issue by c0mrade** [prometheus-community/helm-charts#1535]
### Describe the bug a clear and concise description of what the bug is.

When I provide a label for a service monitor (like I did for [mongodb-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mongodb-exporter) and it worked) the label does not apply. Here is my servicemonitor config:

```
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
```

This is the result:

```
kubectl get servicemonitor postgresql-exporter-prometheus-postgres-exporter -oyaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: postgresql-exporter
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-11-24T19:43:38Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: postgresql-exporter-prometheus-postgres-exporter
  namespace: default
  resourceVersion: "45828"
  uid: 8ee4f271-9186-4d2c-bf1d-85d403e67997
spec:
  endpoints:
  - targetPort: http
  jobLabel: postgresql-exporter-prometheus-postgres-exporter
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: postgresql-exporter
```

I was expecting additional label below `app.kubernetes.io/managed-by: Helm` to be `release:prometheus`. As a result my exporter does not get picked up by prometheus. As stated before, I did exact same thing for mongodb-exporter and the label is correctly applied. Everything else is working fine and I can see the metrics when using port-forward.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}

### Which chart?

https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-postgres-exporter

### What's the chart version?

prometheus-postgres-exporter-2.3.7

### How to reproduce it?

Need to have postgresql installed in your cluster, running as some service. 
Need to have a secret file with password key, that corresponds to your PostgreSQL user password.

Used this config file (values.yaml):

```
config:
  datasource:
    # Specify one of both datasource or datasourceSecret
    host: 10.99.35.49 
    user: postgres
    # Specify passwordSecret if DB password is stored in secret.
    passwordSecret: {
        name: postgres-secret-config,
        key: password
    }
    # Secret name
    #  name:
    # Password key inside secret
    #  key:
    port: "5432"
    database: 'api'
    sslmode: disable
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prometheus
service:
  port: 9187
  targetPort: 9187
  name: http
  metadata:
    labels:
      release: prometheus
```

Install command:
```
helm install postgresql-exporter prometheus-community/prometheus-postgres-exporter -f values.yaml
```

Get servicemonitor yaml:

```
kubectl get servicemonitor postgresql-exporter-prometheus-postgres-exporter -oyaml
```

This is the output:

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: postgresql-exporter
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-11-24T19:43:38Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: postgresql-exporter-prometheus-postgres-exporter
  namespace: default
  resourceVersion: "45828"
  uid: 8ee4f271-9186-4d2c-bf1d-85d403e67997
spec:
  endpoints:
  - targetPort: http
  jobLabel: postgresql-exporter-prometheus-postgres-exporter
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
      release: postgresql-exporter
```

### Enter the command that you execute and failing/misfunctioning.

helm install postgresql-exporter prometheus-community/prometheus-postgres-exporter -f postgres-values.yaml

**Comment by arbianqx** [comment]
> ### Describe the bug a clear and concise description of what the bug is.
> When I provide a label for a service monitor (like I did for [mongodb-exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-mongodb-exporter) and it worked) the label does not apply. Here is my servicemonitor config:
> 
> ```
> serviceMonitor:
>   enabled: true
>   additionalLabels:
>     release: prometheus
> ```
> 
> This is the result:
> 
> ```
> kubectl get servicemonitor postgresql-exporter-prometheus-postgres-exporter -oyaml
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   annotations:
>     meta.helm.sh/release-name: postgresql-exporter
>     meta.helm.sh/release-namespace: default
>   creationTimestamp: "2021-11-24T19:43:38Z"
>   generation: 1
>   labels:
>     app.kubernetes.io/managed-by: Helm
>   name: postgresql-exporter-prometheus-postgres-exporter
>   namespace: default
>   resourceVersion: "45828"
>   uid: 8ee4f271-9186-4d2c-bf1d-85d403e67997
> spec:
>   endpoints:
>   - targetPort: http
>   jobLabel: postgresql-exporter-prometheus-postgres-exporter
>   namespaceSelector:
>     matchNames:
>     - default
>   selector:
>     matchLabels:
>       app: prometheus-postgres-exporter
>       release: postgresql-exporter
> ```
> 
> I was expecting additional label below `app.kubernetes.io/managed-by: Helm` to be `release:prometheus`. As a result my exporter does not get picked up by prometheus. As stated before, I did exact same thing for mongodb-exporter and the label is correctly applied. Everything else is working fine and I can see the metrics when using port-forward.
> 
> ### What's your helm version?
> version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}
> 
> ### What's your kubectl version?
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/arm64"}
> 
> ### Which chart?
> https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-postgres-exporter
> 
> ### What's the chart version?
> prometheus-postgres-exporter-2.3.7
> 
> ### What happened?
> _No response_
> 
> ### What you expected to happen?
> _No response_
> 
> ### How to reproduce it?
> Need to have postgresql installed in your cluster, running as some service. Need to have a secret file with password key, that corresponds to your PostgreSQL user password.
> 
> Used this config file (values.yaml):
> 
> ```
> config:
>   datasource:
>     # Specify one of both datasource or datasourceSecret
>     host: 10.99.35.49 
>     user: postgres
>     # Specify passwordSecret if DB password is stored in secret.
>     passwordSecret: {
>         name: postgres-secret-config,
>         key: password
>     }
>     # Secret name
>     #  name:
>     # Password key inside secret
>     #  key:
>     port: "5432"
>     database: 'api'
>     sslmode: disable
> serviceMonitor:
>   enabled: true
>   additionalLabels:
>     release: prometheus
> service:
>   port: 9187
>   targetPort: 9187
>   name: http
>   metadata:
>     labels:
>       release: prometheus
> ```
> 
> Install command:
> 
> ```
> helm install postgresql-exporter prometheus-community/prometheus-postgres-exporter -f values.yaml
> ```
> 
> Get servicemonitor yaml:
> 
> ```
> kubectl get servicemonitor postgresql-exporter-prometheus-postgres-exporter -oyaml
> ```
> 
> This is the output:
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   annotations:
>     meta.helm.sh/release-name: postgresql-exporter
>     meta.helm.sh/release-namespace: default
>   creationTimestamp: "2021-11-24T19:43:38Z"
>   generation: 1
>   labels:
>     app.kubernetes.io/managed-by: Helm
>   name: postgresql-exporter-prometheus-postgres-exporter
>   namespace: default
>   resourceVersion: "45828"
>   uid: 8ee4f271-9186-4d2c-bf1d-85d403e67997
> spec:
>   endpoints:
>   - targetPort: http
>   jobLabel: postgresql-exporter-prometheus-postgres-exporter
>   namespaceSelector:
>     matchNames:
>     - default
>   selector:
>     matchLabels:
>       app: prometheus-postgres-exporter
>       release: postgresql-exporter
> ```
> 
> ### Enter the changed values of values.yaml?
> _No response_
> 
> ### Enter the command that you execute and failing/misfunctioning.
> helm install postgresql-exporter prometheus-community/prometheus-postgres-exporter -f postgres-values.yaml
> 
> ### Anything else we need to know?
> _No response_

Did you manage to solve the issue, because I'm having the same.

**Comment by micheljung** [comment]
As per the [configuration documentation](https://github.com/helm/charts/tree/master/stable/prometheus-postgres-exporter#configuration), the correct key is:

    serviceMonitor.labels

not
    
    serviceMonitor.additionalLabels
