### ISSUE TITLE
prometheus upgrade to 15.0.0 fails

### ISSUE THREAD

**Issue by alexjplant** [prometheus-community/helm-charts#1538]
### Describe the bug a clear and concise description of what the bug is.

When attempting to upgrade `prometheus` Helm chart from `14.11.1` to `15.0.0` we get the following error:

```
Error: cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

### What's your helm version?

N/A (using Terraform Helm provider)

### What's your kubectl version?

N/A (using Terraform Helm provider)

### Which chart?

prometheus

### What's the chart version?

15.0.0

### What happened?

I attempted to upgrade Prometheus via the Helm chart and it errored (see above).

### What you expected to happen?

A successful upgrade.

### How to reproduce it?

Deploy `14.11.1` and attempt to upgrade it to `15.0.0`.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

N/A (Using Terraform Helm provider)

**Comment by monotek** [comment]
Updated readme to provide a fix in: https://github.com/prometheus-community/helm-charts/pull/1541

**Comment by alexjplant** [comment]
@monotek Thanks so much! I'll give this a shot first thing tomorrow.

**Comment by hmojicag** [comment]
Thanks.
I recently upgraded our EKS cluster from v1.19 to v1.20 and while running:
`helm upgrade --install prometheus prometheus-community/prometheus`

This issue popped up.
The "fix" was just to uninstall prometheus release first before running the `helm upgrade --install` again

**Comment by vhosakot** [comment]
saw same error when helm upgrading prometheus `14.6.0` to `15.6.0`:
```
Error: UPGRADE FAILED: cannot patch "monitor-kube-state-metrics" with kind Deployment: Deployment.apps "monitor-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitor", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
per https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150, deleting `kube-state-metrics` deployment and then re-trying helm upgrade worked and prometheus was successfully upgraded to `15.6.0`.
