### ISSUE TITLE
[prometheus] Error: UPGRADE FAILED: cannot patch "prometheus-kube-state-metrics" with kind Deployment:

### ISSUE THREAD

**Issue by nkol** [prometheus-community/helm-charts#1542]
### Describe the bug a clear and concise description of what the bug is.

can not update Prometheus even with fix for 15.0.1 image same error

Error: UPGRADE FAILED: cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

### What's your helm version?

v3.7.1

### What's your kubectl version?

1.21.2

### Which chart?

prometheus

### What's the chart version?

15.0.1

### What you expected to happen?

update

### How to reproduce it?

helm upgrade prometheus

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/prometheus --namespace prometheus --values ......

### Anything else we need to know?

fix for this still not fixed

**Comment by cyanidium** [comment]
Hit the same issue. Workaround by Skaronator in #568 solved it.

**Comment by monotek** [comment]
The readme already describes what to do: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150

**Comment by LarsBingBong** [comment]
@monotek I'm a bit confused here. How can one identify whether there are changes to the relabeling config? As the *To 15.0* ReadMe says:

```txt
made manual changes to the relabeling config,  you have to adapt your changes.
```

I do not believe we've made such relabeling changes. How can I identify this? As we haven't touched any labeling conf. in our Helm values configuration.

Thank you very much.

**Comment by kaajrot** [comment]
Hello

Any idea what should be changed in order to have the old labels? eg. kubernetes_namespace instead of namespace?

**Comment by ruckc** [comment]
I'm getting this going from a clean install of 21.x to 24.0.1.  I've had this quite frequently for some reason.

**Comment by vhosakot** [comment]
saw same error when helm upgrading prometheus `14.6.0` to `15.6.0`:
```
Error: UPGRADE FAILED: cannot patch "monitor-kube-state-metrics" with kind Deployment: Deployment.apps "monitor-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitor", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
per https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150, deleting `kube-state-metrics` deployment and then re-trying helm upgrade worked and prometheus was successfully upgraded to `15.6.0`.
