### ISSUE TITLE
[prometheus] Collisions caused by relabeling

### ISSUE THREAD

**Issue by zerkms** [prometheus-community/helm-charts#1548]
### Describe the bug a clear and concise description of what the bug is.

In https://github.com/prometheus-community/helm-charts/pull/1520 targets were relabeled and it now causes collisions with some metrics.

For instance `kube_pod_info` already has `node`, and the originally fine `kubernetes_node` was renamed in PR 1520 to `node` too.

The same for `kube_pod_annotations` and `namespace`.

All of them are from `kube-state-metrics`.

### What's your helm version?

n/a

### What's your kubectl version?

n/a

### Which chart?

prometheus

### What's the chart version?

15.0.1

### What happened?

Relabeling causes collisions

### What you expected to happen?

It should not happen

### How to reproduce it?

Install the chart and check `kube_pod_info`

### Enter the changed values of values.yaml?

n/a

### Enter the command that you execute and failing/misfunctioning.

n/a

### Anything else we need to know?

n/a

**Comment by paulfantom** [comment]
kube-state-metrics should use `honor_labels: true` in its scrape configuration to prevent such issues.

**Comment by zerkms** [comment]
> Bear in mind that kubernetes_node label didn't make any sense on kube_pod_info 

It's for instance is used in kubernetes-mixin's `KubeletTooManyPods` https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/2b27a09a667091cef74776b690ccceaf55995e29/alerts/kubelet.libsonnet#L51

That's actually how I discovered that very problem.

**Comment by paulfantom** [comment]
> It's for instance is used in kubernetes-mixin's KubeletTooManyPods kubernetes-monitoring/kubernetes-mixin@2b27a09/alerts/kubelet.libsonnet#L51

That's a confirmation of what I was saying. `kubernetes_node` label doesn't make any sense on `kube_pod_info` as the `kubernetes_node` label relates to node on which KSM is running and not to the pod described by `kube_pod_info`. This is also why `honor_labels` should be set to true for KSM.

Bear in mind that previously `kube_pod_info` had both `node` and `kubernetes_node` labels with possibly different values. Which is confusing.

> Does it mean this chart's default config should be updated then?

Yes, I suppose so.

**Comment by zerkms** [comment]
Oh, I see what you mean now, sorry if my messages sounded rude.

**Comment by mnorrsken** [comment]
I moved back to version 14 for now, is exported_namespace because of collision here to stay? (should I rewrite grafana dashboards or is this actually a bug?)

**Comment by zerkms** [comment]
Not stale.

**Comment by pierluigilenoci** [comment]
For sure not stale 😜

**Comment by zerkms** [comment]
Not stale?

**Comment by mnorrsken** [comment]
I have a feeling that our concerns are not understood. I've resorted to using my own modified scrape config instead of the one that comes with the chart to get around this problem and still get application updates.

**Comment by zerkms** [comment]
@mnorrsken I just cannot believe it's just 2 users affected? Isn't everybody should experience problems?

**Comment by Gerrit-K** [comment]
@zerkms You have to remind yourself that this boils down to the users that (1) use this standalone chart instead of the (arguably more popular) full stack chart, (2) already upgraded to version 15, (3) don't have a custom scraping config and (4) found this issue and (5) upvoted it. It might really well be that this is just a handful of users.

@mnorrsken I think they are understood, but deprioritized due to the lack of common interest - which is often seen in open source projects. The cool thing about open source, though, is that you can dive into the code and actively propose a solution :) (given that you have the time to do that, though).

**Comment by zerkms** [comment]
@Gerrit-K right, which one is `full stack` you're referring to though?

**Comment by mnorrsken** [comment]
@Gerrit-K  I do have a solution, but that is a simple revert of #1520, which would break the full stack chart. I can't really add these label names as chart values either (?) because the whole config is a single value, or maybe I just don't understand how helm charts work.

**Comment by mnorrsken** [comment]
The full stack is this one:

[kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack)

But I don't want to use that, it's way overkill for my clusters and I generally dislike operators and the way they work (hiding configuration and adding complexity).

**Comment by pierluigilenoci** [comment]
@mnorrsken we also use the Prometheus plain chart for multiple reasons.
To name one, we don't need a Grafana installation for every cluster we have.
We prefer to have one and add all clusters as external datasource.

**Comment by ekadas** [comment]
We also use the standalone Prometheus chart along with the Kube State Metric chart and now need to overwrite the default `scrape_configs` with ones that have `honor_labels: true`, whereas prior to version 15 we just used the default scrape configs. I wonder if `honor_labels: true` should be the default behaviour, or if it is reasonable to make this configurable at a higher level?

**Comment by monotek** [comment]
Yes, "honor_labels: true" should be the default behaviour.
Do you wan't to create a pr for that?
