### ISSUE TITLE
[kube-prometheus-stack] Option to add grafana plugins

### ISSUE THREAD

**Issue by Myothas** [prometheus-community/helm-charts#1549]
### Is your feature request related to a problem ?

I've been looking through the kube-prometheus-stack but I can't seem to find the option to enable any grafana plugins.

### Describe the solution you'd like.

Some sort of list where you can list plugins you would like to be installed on startup.

### Describe alternatives you've considered.

NONE

### Additional context.

Something simliar to: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L447

**Comment by gagarinfan** [comment]
Hey! As kube-prometheus-stack actually has this Grafana chart as [dependency](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml#L46-L49) you can use [plugins](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L447) key under [grafana](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L624) section. Also described [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L622)

**Comment by BoKKeR** [comment]
Has this gotten removed?

**Comment by qj0r9j0vc2** [comment]
> Has this gotten removed?

I found plugins key on here.

https://github.com/grafana/helm-charts/blob/d0d0cb284ae2ac78788a8ee18e5e2f795d5ee3fa/charts/grafana/values.yaml#L590

**Comment by valentin-perez** [comment]
> Has this gotten removed?

You can add plugins under the grafana definition on the values.yaml as a new field.

Example for adding the opensearch plugin:
```
grafana:
  plugins:
    - grafana-opensearch-datasource
```

**Comment by ska-ops** [comment]
> > Has this gotten removed?
> 
> You can add plugins under the grafana definition on the values.yaml as a new field.
> 
> Example for adding the opensearch plugin:
> 
> ```
> grafana:
>   plugins:
>     - grafana-opensearch-datasource
> ```

this works, thanks
