### ISSUE TITLE
[prometheus-community/kube-prometheus-stack] manifest_sorter.go:192: info: skipping unknown hook: "crd-install"

### ISSUE THREAD

**Issue by NickGraham101** [prometheus-community/helm-charts#155]
**Describe the bug**
Deployment of kube-prometheus-stack fails with error manifest_sorter.go:192: info: skipping unknown hook: "crd-install".  The CustomResourceDefinitions are still created

**Version of Helm and Kubernetes**:

Helm Version: 3.3.1
Kubernetes Version: 1.18.8

**Which chart**: prometheus-community/kube-prometheus-stack
**Which version of the chart**: 9.4.4

**What happened**: Deployment of chart returns an error:
```
helm.exe upgrade --install --wait --namespace prometheus-stack --version v9.4.4 kube-prometheus-stack prometheus-community/kube-prometheus-stack
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Release "kube-prometheus-stack" does not exist. Installing it now.
NAME: kube-prometheus-stack
LAST DEPLOYED: Mon Sep 28 16:45:30 2020
NAMESPACE: prometheus-stack
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace prometheus-stack get pods -l "release=kube-prometheus-stack"
```
Though it still seems to install all resources and Prometheus is functional, CRDs are installed:
```
kubectl get CustomResourceDefinition
NAME                                    CREATED AT
alertmanagers.monitoring.coreos.com     2020-09-28T16:45:27Z
podmonitors.monitoring.coreos.com       2020-09-28T16:45:27Z
prometheuses.monitoring.coreos.com      2020-09-28T16:45:27Z
prometheusrules.monitoring.coreos.com   2020-09-28T16:45:27Z
servicemonitors.monitoring.coreos.com   2020-09-28T16:45:27Z
thanosrulers.monitoring.coreos.com      2020-09-28T16:45:27Z
```

**What you expected to happen**: The chart to deploy without returning an error

**How to reproduce it** (as minimally and precisely as possible):
```
helm.exe upgrade --install --wait --namespace prometheus-stack --version v9.4.4 kube-prometheus-stack prometheus-community/kube-prometheus-stack
```

**Comment by Kerwood** [comment]
Can confirm on:

Helm Version: 3.3.0
Kubernetes Version: 1.18.6

With below command.
```
helm install prometheus stable/prometheus-operator --namespace prometheus
```

**Comment by NickGraham101** [comment]
I've retried this with version 9.4.9 of the chart but still getting the same issues

**Comment by yosefy** [comment]
confirm

**Comment by kkreso** [comment]
Can confirm on:

Helm Version: 3.3.4
Kubernetes Version: 1.18.8

**Comment by Jacob1r** [comment]
Confirmed same on: helm v3.3.4, kubectl v1.19.2

**Comment by scottrigby** [comment]
You can safely ignore this warning. See https://v3.helm.sh/docs/topics/charts_hooks/#the-available-hooks
> Note that the crd-install hook has been removed in favor of the crds/ directory in Helm 3.

This hook is still part of the chart because Helm 2 support is not yet finished. After 13 Nov 2020, we can safely remove this hook from the chart. Until then, this is by design.

For more context, see https://github.com/helm/charts/issues/19008

**Comment by nickjmv** [comment]
We still see this warning, is that normal?

**Comment by kubealex** [comment]
In my case, it's not a warning, it's an error

```
> helm install prom prometheus-community/kube-prometheus-stack -n monitoring
Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "https://monitoring-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": service "monitoring-kube-prometheus-operator" not found
```
