### ISSUE TITLE
[prometheus] Ingress class extraPaths are not compatible with networking.k8s.io/v1

### ISSUE THREAD

**Issue by andormarkus** [prometheus-community/helm-charts#1550]
### Describe the bug a clear and concise description of what the bug is.

I tried to update helm chart from 14.1.0 to 15.0.1 and I got the following error.

```shell
error validating data: [
ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, 
ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend, 
ValidationError(Ingress.spec.rules[0].http.paths[1].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, 
ValidationError(Ingress.spec.rules[0].http.paths[1].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend
]
```

The 383b15a4c60f8cc33975f90d8e705e72052d6713 commit implemented the ingress version selection based on k8s version, but the ingress template did not changed. 

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.17"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.0.1

### Enter the command that you execute and failing/misfunctioning.

I tried to update the helm chart from 14.1.0 to 15.0.1

**Comment by andormarkus** [comment]
Up

**Comment by monotek** [comment]
PR welcome :)

**Comment by jhuebner79** [comment]
Still an issue during update from 14.0.0 to 15.1.3.
