### ISSUE TITLE
Prometheus operator always raising KubeControllerManagerDown or KubeSchedulerDown

### ISSUE THREAD

**Issue by woody3549** [prometheus-community/helm-charts#1554]
### Describe the bug a clear and concise description of what the bug is.

Hello,

I currently have two alerts raising because of a "Target disappeared from Prometheus target discovery".
Alertnames are KubeControllerManagerDown and KubeSchedulerDown.

My current configuration is GKE v1.19.16-gke.1500 and kube-prometheus-stack 20.0.1.
Can you please let me know what could be the reason ?
Is anyway I could mute these alerts ?

Thanks

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.20.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

20.0.1

### Enter the command that you execute and failing/misfunctioning.

Prometheus operator always raising KubeControllerManagerDown or KubeSchedulerDown.

For instance:
alertname = KubeControllerManagerDown
prometheus = monitoring/prometheus-operator-kube-p-prometheus
severity = critical
Annotations
description = KubeControllerManager has disappeared from Prometheus target discovery.
runbook_url = https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecontrollermanagerdown
summary = Target disappeared from Prometheus target discovery.
Source

**Comment by PeeK1e** [comment]
In case anyone runs over this issue, check your Service Monitors if they are scraping the correct ports and if you use the kube-prometheus-stack, check that if you enabled the service, that the port mapping is correct.

**Comment by rudolfbyker** [comment]
@PeeK1e would you elaborate? Which helm values should I check if I'm using the `kube-prometheus-stack` chart? Which service are you referring to?

**Comment by PeeK1e** [comment]
> @PeeK1e would you elaborate? Which helm values should I check if I'm using the `kube-prometheus-stack` chart? Which service are you referring to?

I don't quite remember exactly which services you had to delete/check but check your Kube-System namespace for duplicate services. And also Service Monitors. If the services created by the kube-prom-stack are equal to the kube system services, then you may just delete the one created by the chart.

**Comment by rudolfbyker** [comment]
Thanks for your time. I can't see an issue here:

### `kubectl -n kube-system get svc`

```
NAME                                                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                        AGE
kube-dns                                             ClusterIP   10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP         647d
metrics-server                                       ClusterIP   10.43.84.247   <none>        443/TCP                        647d
prometheus-stack-kube-prom-kubelet                   ClusterIP   None           <none>        10250/TCP,10255/TCP,4194/TCP   183d
prometheus-stack-kube-prom-coredns                   ClusterIP   None           <none>        9153/TCP                       3d
prometheus-stack-kube-prom-kube-etcd                 ClusterIP   None           <none>        2381/TCP                       3d
prometheus-stack-kube-prom-kube-controller-manager   ClusterIP   None           <none>        10257/TCP                      3d
```

### `kubectl get servicemonitor --all-namespaces`

```
NAMESPACE          NAME                                                 AGE
prometheus-stack   prometheus-stack-kube-prom-apiserver                 3d
prometheus-stack   prometheus-stack-kube-prom-prometheus                3d
prometheus-stack   prometheus-stack-prometheus-node-exporter            3d
prometheus-stack   prometheus-stack-kube-prom-operator                  3d
prometheus-stack   prometheus-stack-kube-prom-kubelet                   3d
prometheus-stack   prometheus-stack-kube-prom-kube-etcd                 3d
prometheus-stack   prometheus-stack-kube-prom-kube-controller-manager   3d
prometheus-stack   prometheus-stack-kube-prom-coredns                   3d
prometheus-stack   prometheus-stack-grafana                             3d
prometheus-stack   prometheus-stack-kube-prom-alertmanager              3d
prometheus-stack   prometheus-stack-kube-state-metrics                  3d
```

**Comment by bernatvadell** [comment]
I've the same issue. Workaround?
