### ISSUE TITLE
grafana persistence

### ISSUE THREAD

**Issue by wu105** [prometheus-community/helm-charts#1571]
grafana at https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml seems to allow persistence.
is there a way to do the same for grafana in prometheus?
This may help to persist user passwords and dashboard customizations over pods restarting..

**Comment by ws-prive** [comment]
Maybe this will help? using helm:

```
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack \
  --install \
  --set grafana.enabled=true \
  --set grafana.persistence.enabled=true \
  --set grafana.persistence.size=10Gi \
```

**Comment by wu105** [comment]
The output of `helm3 get manifest prometheus -n monitoring` showed no material difference after installing the prometheus with or without similar flags below:
```
# --set grefana.persistence.enabled=true \
# --set grefana.persistence.storageClassName="default" \
# --set grefana.persistence.size="1Gi" \
```

**Comment by kfox1111** [comment]
Typo.

s/grefana/grafana/

________________________________________

**Comment by wu105** [comment]
Thanks for the eagle eye!  Now I got the pv for grafana!
May be you want to update the promenteus values or other docs.
You may close this issue once the doc/values are taken care of.

**Comment by ws-prive** [comment]
I am not a maintainer. This is all documented in the grafana helm chart which is used in this prometheus chart, so you can use that chart as reference.

**Comment by wu105** [comment]
I was not sure that the grafana chart is in effect a "sub chart" of the prometheus chart.   That probably is why I did not watch closely for the typo when the first attempt did not work.  Are the subcharts of prometheus documented somewhere?

**Comment by ws-prive** [comment]
Please look at Chart.yaml in every helm config. The subcharts are mentioned there and that's were your starting point is to look for the helm config of the subcharts.

**Comment by wu105** [comment]
Thanks for the reminder to look at the dependencies section of the Chart.yaml.
It takes quite some knowhow to follow the dependencies and reach to the information needed for enabling grafana persistence.  Googling might be easier but less certain.  In any case, it may be a good idea to expose the grafana persistence on the Prometheus values along with the other two persistence values.  

I am closing this issue.  Hope this issue would provide sufficient help even if there is no updates to promethues doc or values.

**Comment by wu105** [comment]
see my last comment.
