### ISSUE TITLE
[kube-state-metrics, prometheus-node-exporter] Inconsistent names for psp-related cluster roles

### ISSUE THREAD

**Issue by ww3pl** [prometheus-community/helm-charts#1578]
### Is your feature request related to a problem ?

The names for Pod Security Policy related ClusterRoles are inconsistent. Some of them begin with "psp-", the others end with "-psp". The latter seem to be in majority. 

Examples: 

1. Kube State Metrics
```
psp-{{ template "kube-state-metrics.fullname" . }}
```

2. Kube Prometheus Stack
```
{{ template "kube-prometheus-stack.fullname" . }}-operator-psp
{{ template "kube-prometheus-stack.fullname" . }}-prometheus-psp
```

3. Prometheus Node Exporter
```
psp-{{ template "prometheus-node-exporter.fullname" . }}
```

4. Prometheus Blackbox Exporter
```
{{ template "prometheus-blackbox-exporter.fullname" . }}-psp
```

### Describe the solution you'd like.

I'd love to see the names unified, especially considering the fact those charts are all maintained on the same GitHub repo. 

I believe that there's the suffix "-psp" occurs slightly more often in the repository, so we could choose that. 

### Describe alternatives you've considered.

NONE

### Additional context.

This issue is by no means critical - I just think that one consistent format in naming would make it just a bit easier to manage the cluster roles.

I am willing to put forward the MRs for both of the Charts to use the "-psp" ending.

**Comment by monotek** [comment]
As most charts have different maintainers and we have no rules for that it would be kinda hard to implement.

The only way is see would be to use some library chart, like [bitnami common](https://github.com/bitnami/charts/tree/master/bitnami/common), as template for all resources.

We already talked about iit (https://github.com/prometheus-community/helm-charts/issues/1437#issuecomment-945120522) but it was never implemented, as it would be a lot of work to change all charts using such library.

**Comment by dotdc** [comment]
@mrueg @tariq1890 @monotek What's your call on this? 

Should we close this issue or make the necessary changes?

If we decide to do the changes:
- `psp-` or `-psp` ?
- as it's a potentially breaking change, it's a major version update on semver right?

**Comment by mrueg** [comment]
I don't have a strong preference there as pod security policies eventually will go away https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ 
Maybe we should keep the status quo and phase it out instead?

**Comment by dotdc** [comment]
Thanks, we are closing this :+1:
