### ISSUE TITLE
[name of the chart e.g. prometheus-kube-stack] issue title

### ISSUE THREAD

**Issue by rieger-jared** [prometheus-community/helm-charts#158]
**Describe the bug**
*Grafana ingress value overrides not applied.*

Helm Version:

```console
$ helm version
Client: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Kubernetes Version:

**Kubernetes** : `v1.15.1`

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:`kube-prometheus-stack`
**Which version of the chart**: ` 9.4.4`

**What happened**: As the title suggest when applying value overrides for the grafana ingress, they are not enacted. 
no ingress is created within the namespace of the chart nor anywhere in the cluster.

**What you expected to happen**: A ingress object with the defined values in the values supplied to the chart

**How to reproduce it** (as minimally and precisely as possible): run the chart with the values below.

```yaml
This could be something like:
    values:
      grafana:
        enabled: true
        adminPassword: admin
        ingress:
          enabled: true
          hosts:
            - www.company.com 
          path: /
          tls:
          - secretName: my-secret
            hosts:
            - www.company.com 
```

```
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**: I could not find an ingress resource for Grafana in the chart. Has someone forgotten to make it?

**Comment by zffocussss** [comment]
same here

**Comment by JonasJW** [comment]
I have a similar issue when overriding the alert manager. This is my values.yaml:

    alertmanager:
      config:
        receivers:
        - name: 'web.hook'
          webhook_configs:
          - url: 'http://localhost:7200/'

        route:
          receiver: 'web.hook'
