### ISSUE TITLE
[prometheus-pushgateway] Update to latest version

### ISSUE THREAD

**Issue by MxNxPx** [prometheus-community/helm-charts#1588]
### Is your feature request related to a problem ?

It seems like the helm chart for prometheus-pushgateway is using a ~6 months old image: prom/pushgateway:v1.4.1

Per: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/values.yaml#L13

### Describe the solution you'd like.

Update the helm chart to use the latest version available prom/pushgateway:v1.4.2 

https://hub.docker.com/layers/prom/pushgateway/v1.4.2/images/sha256-0604285851ff4871d2bd740a89c00e49098939f5f648f78f42c0a450a7a987fc?context=explore

### Describe alternatives you've considered.

NONE

**Comment by monotek** [comment]
Would you mind to create a pr please?

**Comment by MxNxPx** [comment]
> Would you mind to create a pr please?

@monotek - sure, just created one.  thanks!

**Comment by MxNxPx** [comment]
merged now, closing.  thanks @monotek!
