### ISSUE TITLE
[kube-prometheus-stack]   How to set values in helm to custmizing? 

### ISSUE THREAD

**Issue by HanHoRang** [prometheus-community/helm-charts#1608]
hi. I want to edit the helm values ​​and do the following, but there is no value in the values.

1. Modify grafana service type (Loabalancer) and add annotation

2. Add grafana dashboard config.

Let me know if that option already exists..

**Comment by ww3pl** [comment]
Hey @HanHoRang!

kube-prometheus-stack Helm chart uses Grafana's Helm Chart as a dependency. This means that the original values come from the Grafana's Helm Chart values.yaml files - [just like it's stated in the comment](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L622)!

This means you can simply add another key to the [Grafana's service config in kube-prometheus-stack's values.yaml file](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L746), like so:

```yaml
  service:
    portName: http-web
    type: LoadBalancer  # This is the line we've added
```

You can overwrite any other values in the exact same way. 

Did that answer your question?

**Comment by HanHoRang** [comment]
Thanks a lot, it was very helpful, I'll share the link for those in the same situation as me.
https://github.com/prometheus-community/helm-charts/issues/113

**Comment by ww3pl** [comment]
@HanHoRang - I also recommend reading docs linked [in the issue you've linked ](https://github.com/prometheus-community/helm-charts/issues/113#issuecomment-695113299), as this is just a part of how dependencies are managed when using Helm.
