### ISSUE TITLE
How to add extra TSDB Parameters for Wal log archive

### ISSUE THREAD

**Issue by vmalhotra22** [prometheus-community/helm-charts#161]
Hi,

I was checking the Wal log Archive args today in the template and values.yml for Prometheus and didn't find much.

I want to use another arg called --storage.tsdb.retentionSize to fix the Size of the WAL archive logs but I cannot set its value in the values.yml file.

I tried changing the template/deployment/server.yml and called using below command but it failed.

> helm install prometheus --namespace default -f values.yaml -f templates/deployments/server.yaml prometheus-community/prometheus 
Error: failed to parse templates/deployments/server.yaml: error converting YAML to JSON: yaml: did not find expected node content

Please help me how to add the new arguments for the tsdb.

Cheers

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/deploy.yaml#L90

**Comment by vmalhotra22** [comment]
@monotek  I tried adding that  

           {{- if .Values.server.retention }}
            - --storage.tsdb.retention.time={{ .Values.server.retention }}
          {{- end }}
          **{{- if .Values.server.retentionSize }}
            - --storage.tsdb.retention.size={{ .Values.server.retentionSize }}
          {{- end }}**

in deploy.yml and added value to above variables in values.yml

as 

  ## Prometheus data retention period (default if not specified is 15 days)
  ##
  retention: "1d"
  retentionSize: "60MB"

and called the helm chart as 
> helm install prometheus --namespace default -f values.yaml -f templates/deployments/server.yaml prometheus-community/prometheus

but I got following error.
Error: failed to parse templates/deployments/server.yaml: error converting YAML to JSON: yaml: did not find expected node content

**Comment by vmalhotra22** [comment]
I think if we do any changes other than values.yml, the helm chart throws error :(

**Comment by kfirfer** [comment]
How can I add extraFlags in the kube-prometheus-stack chart?
