### ISSUE TITLE
[prometheus-adapter] Empty custom metrics

### ISSUE THREAD

**Issue by Igec1** [prometheus-community/helm-charts#1615]
Hi, I've installed prometehus adapter with the following command:  
**helm install prometheus-adapter prometheus-community/prometheus-adapter --namespace monitoring 
-f adapter_custom_values.yaml** 
However when checking with kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1, I dont see any metrics being registered.  Here is a preview of the adapter_custom_values.yaml file: 
![adapter_custom_values](https://user-images.githubusercontent.com/96411896/146732538-056a2410-4ee7-4d56-a3c2-d2edd01f0479.PNG)

This is the response I am getting while running the command kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1: 

![Response from Custom Metrics API](https://user-images.githubusercontent.com/96411896/146732579-193e4eb6-7f59-4349-92f6-5b833bf76fe4.PNG)
I've also checked the logs of the prometheus-adapter pod, no errors in the logs. Additionally I've checked the prometheus url and it is correct.

My question is why the custom metrics are not registered ? Any help will be appreciated.

**Comment by junaid-ali** [comment]
@Igec1 you could try enabling verbose logging and check what's the exact query from the adapter to prometheus server, and the response of that

**Comment by junaid-ali** [comment]
@Igec1 you could try enabling verbose logging and check what's the exact query from the adapter to prometheus server, and the response of that
