### ISSUE TITLE
[prometheus-kube-stack] Lack of Alertmanger.probeHeaders makes checks fails 4xx

### ISSUE THREAD

**Issue by brsolomon-deloitte** [prometheus-community/helm-charts#1621]
### Describe the bug a clear and concise description of what the bug is.

As discussed in https://github.com/prometheus-community/helm-charts/issues/1255 and https://github.com/prometheus-community/helm-charts/issues/1186, there is no `Alertmanger.probeHeaders` exposed for Prometheus in `values.yaml`, so liveness & readiness checks fail with a 4xx when [basic auth](https://prometheus.io/docs/guides/basic-auth/) is enabled.

Additionally, both the `prometheus` and `prometheus-stack` charts would greatly benefit from a fully reproducible YAML config for enabling basic auth. (as also requested in https://github.com/prometheus-community/helm-charts/issues/1255#issuecomment-999156093).

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.0.2

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by brsolomon-deloitte** [comment]
no stale

**Comment by albert0815** [comment]
this is still a issue for us
