### ISSUE TITLE
[prometheus-kube-stack] KubeProxyDown constantly firing

### ISSUE THREAD

**Issue by mindrunner** [prometheus-community/helm-charts#1622]
### Describe the bug a clear and concise description of what the bug is.

I did some upgrades yesterday. K8S 1.21.2.

Since then, the KubeProxyDown alert is constantly firing. I do see kube-proxy pods. This happens on two clusters.

I am on Azure if that matters.

How can I investigate that?

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.4"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

25.0.0

### Enter the command that you execute and failing/misfunctioning.

-

**Comment by mrueg** [comment]
Thanks, we are aware of this issue. Feel free to chime in on: https://github.com/prometheus-community/helm-charts/issues/1618 and contribute.
