### ISSUE TITLE
[kube-prometheus-stack] file name has .rules

### ISSUE THREAD

**Issue by fusida** [prometheus-community/helm-charts#1633]
### Describe the bug a clear and concise description of what the bug is.

why 
helm-charts/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/alertmanager.rules.yaml
not be 
alertmanager.yaml.

And general.rules.yaml not general.yaml

### What's your helm version?

0.47

### What's your kubectl version?

1.19

### Which chart?

kube-prometheus-stack

### What's the chart version?

0.47

### Enter the command that you execute and failing/misfunctioning.

the file name should be diff alertrule and metricrule.

**Comment by shinebayar-g** [comment]
If you go to Prometheus UI -> Rules, you'd notice there are tons of rules. From my observation `.rules` extension group are used for Prometheus recording rules. Other extensionless groups are used for alert group names.
