### ISSUE TITLE
[prometheus-node-exporter] Removal or configuration of the ports option in the daemonset 

### ISSUE THREAD

**Issue by alviss7** [prometheus-community/helm-charts#1636]
### Is your feature request related to a problem ?

I would like to not expose the node-exporter port 9100 on my Kubernetes nodes, but only use the Kubernetes service to consume it in the internal Kubernetes network.

### Describe the solution you'd like.

I don't know what is the best approach between deleting or adding an option to disable this feature. https://github.com/prometheus-community/helm-charts/blob/7fd5d01548609cd4297f76ddfe080024b749944c/charts/prometheus-node-exporter/templates/daemonset.yaml#L64-L67 

For me this configuration is duplicated with hostNetwork which indirectly exposes the daemon https://github.com/prometheus-community/helm-charts/blob/7fd5d01548609cd4297f76ddfe080024b749944c/charts/prometheus-node-exporter/templates/daemonset.yaml#L131 

### Describe alternatives you've considered.

NONE

### Additional context.

I am ready to contribute, this issue is mainly here to know how I could do it, this is my first contribution.

**Comment by adyprico** [comment]
+1. I will also like this option.

**Comment by ashemenev** [comment]
+1

**Comment by jemand771** [comment]
the way I understand it, adding the scrape=true label to the daemonset's pods instead of a service would be the more self-contained approach anyway. in that case, no service is needed at all

(I'm new to helm/k8s, so I might be missing something obvious here)
