### ISSUE TITLE
[kube-prometheus-stack] node-exporter ServiceMonitor was not created

### ISSUE THREAD

**Issue by kespineira** [prometheus-community/helm-charts#1638]
### Describe the bug a clear and concise description of what the bug is.

I have installed the latest version of the stack and it doesn't create the ServiceMonitor for the node-exporter, however if it launches the daemonset and the pods get up.

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

25.2.0

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring

**Comment by brokenjacobs** [comment]
For whatever reason the serviceMonitor is not enabled by default in the new chart. You can update your values.yml and force it on. See here:
https://github.com/prometheus-community/helm-charts/blob/7fd5d01548609cd4297f76ddfe080024b749944c/charts/kube-prometheus-stack/values.yaml#L1365

**Comment by kespineira** [comment]
@brokenjacobs Thank you!

**Comment by mrueg** [comment]
It should probably be enabled in the chart by default still.

**Comment by indreek** [comment]
Or atleast say in red in documentation that it's disabled now. Spent a lot of hours trying to figure out what might be wrong.

**Comment by monotek** [comment]
I've added a fix: https://github.com/prometheus-community/helm-charts/pull/1640

**Comment by Xtigyro** [comment]
Thank you, guys!
Should be OK now.
