### ISSUE TITLE
[ prometheus-kube-stack] not etcd in prometheus target

### ISSUE THREAD

**Issue by lihc520** [prometheus-community/helm-charts#1639]
### Describe the bug a clear and concise description of what the bug is.

I use helm install prometheus -n monitoring --values kube-prometheus-stack/values.yaml kube-prometheus-stack/
just change pvc.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:22:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack-23.1.3

### What's the chart version?

kube-prometheus-stack-23.1.3

### What happened?

![image](https://user-images.githubusercontent.com/69955018/147560582-50590262-39f0-46bc-b9e5-fe2e4fcb0b38.png)
![Uploading image.png…]()

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus -n monitoring --values kube-prometheus-stack/values.yaml kube-prometheus-stack/

**Comment by lihc520** [comment]
![image](https://user-images.githubusercontent.com/69955018/147560839-b208fd7e-5725-4648-8e08-81be853574b4.png)

**Comment by monotek** [comment]
If you're on a managed k8s of some cloud provider you might not even "see" etcd. 
So just disable it in: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1123
