### ISSUE TITLE
[kube-prometheus-stack] More sane versioning with chart

### ISSUE THREAD

**Issue by samip5** [prometheus-community/helm-charts#1642]
### Is your feature request related to a problem ?

I'm beyond frustrated when there's multiple major version updates to the Chart even though, they might not be even breaking and when there's multiple version number jumps out of nowhere.

Like for example, why is the version jump from 25.2 -> 26.0.0 a breaking one?

### Describe the solution you'd like.

I would like an version situation where there's no version jumping, and when it's a major one, it should actually be considered breaking.

### Describe alternatives you've considered.

Maintaining own manifests, which is sub optimal.

**Comment by 0dragosh** [comment]
We're also concerned about the rate of major version upgrades.

I'd love an explanation around the versioning.

**Comment by monotek** [comment]
Because it changed a default value of the chart affecting all users who are upgrading the chart.
Therefore its a breaking change and needs to upgrade the major version.

**Comment by samip5** [comment]
I don't think this should have been closed. That's not how it's supposed to be used to my knowledge.

**Comment by monotek** [comment]
See: https://semver.org/

**Comment by mrueg** [comment]
@samip5
If you are "beyond frustrated", this project is eagerly awaiting your contributions and we are looking forward to seeing you step up as a maintainer.

Raising major is a common way of communicating to users that defaults have changed and to upgrade with caution. Also if charts depend on this one it makes sense as it could cause conflicts.
