### ISSUE TITLE
[loki-stack] pinned version of prometheus too old to support Kubernetes 1.22

### ISSUE THREAD

**Issue by fanzynoodle** [prometheus-community/helm-charts#1643]
### Describe the bug a clear and concise description of what the bug is.

Chart version doesn't work on 1.22 due to child charts using removed v1beta apis.

### What's your helm version?

3.6.1

### What's your kubectl version?

1.22.2

### Which chart?

loki-stack

### What's the chart version?

loki-stack-2.5.0

### What happened?

The current loki-stack chart pins an older version of the prometheus chart that has hard-coded references to rbac.authorization.k8s.io/v1beta1 objects. The new version of prometheus has fixed those. This API has been stable since Kubernetes 1.8 and all those old versions without the stable version are long-since EOL'd so I'd think you could just strip the beta and call it a day without needing to make it configurable.

The following worked-for-me:

diff --git a/charts/loki-stack/requirements.yaml b/charts/loki-stack/requirements.yaml
index af6082f..0111f37 100644
--- a/charts/loki-stack/requirements.yaml
+++ b/charts/loki-stack/requirements.yaml
@@ -17,7 +17,7 @@ dependencies:
   repository:  "https://grafana.github.io/helm-charts"
 - name: "prometheus"
   condition: prometheus.enabled
-  version: "~11.16.0"
+  version: "~15.0.2"
   repository:  "https://prometheus-community.github.io/helm-charts"
 - name: "filebeat"

# now this looks to be happy
loki-stack% helm template loki .   --set 'fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=falsebit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false'

### What you expected to happen?

It to install :)

### How to reproduce it?

Try to install it kubernetes 1.22 with  --set 'fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=falsebit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false'

### Enter the command that you execute and failing/misfunctioning.

helm template loki .   --set 'fluent-bit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=falsebit.enabled=true,promtail.enabled=false,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false'

### Anything else we need to know?

nope.

**Comment by mrueg** [comment]
The loki-stack is not part of this repository, you probably want to report this in https://github.com/grafana/helm-charts
