### ISSUE TITLE
[name of the chart e.g. prometheus-kube-stack] Issue Title

### ISSUE THREAD

**Issue by Sarraksh** [prometheus-community/helm-charts#1647]
### Describe the bug a clear and concise description of what the bug is.

The new `KubeProxyDown` alert can be disabled only by disabling all built-in rules.
I am sure that it should be disabled separately and most likely together with the `defaultRules.rules.kubernetesSystem` group.
This alert should definitely not be required, since there are `kubernetes` configurations that do not use kube-proxy at all.
For example, we use `GKE Dataplane V2`, which does not have `kube-proxy`, and at the same time we use part of the standard rules provided by `kube-prometheus-stack`.

I am sure that it is enough to change the line in the file ./templates/prometheus/rules-1.14/kubernetes-system-kube-proxy.yaml from
```
{{- if and (semverCompare ">=1.14.0-0" $kubeTargetVersion) (semverCompare "<9.9.9-9" $kubeTargetVersion) .Values.defaultRules.create }}
```
to

```
{{- if and (semverCompare ">=1.14.0-0" $kubeTargetVersion) (semverCompare "<9.9.9-9" $kubeTargetVersion) .Values.defaultRules.create .Values.defaultRules.rules.kubernetesSystem }}
```

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

v1.22.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

v25.2.0

### What happened?

After updating the chart to v25.2.0, an alert appeared, which cannot be disabled separately from all other alerts and rules and, depending on the cluster configuration, may be redundant.

### What you expected to happen?

Alert `KubeProxyDown` can be disabled individually or as part of a group.

### How to reproduce it?

Run the chart in a cluster that does not require `kube-proxy`, for example, in` GKE Dataplane V2`

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

The way the chart is launched definitely does not affect the reproduction of the described problem.

**Comment by monotek** [comment]
fixed in: https://github.com/prometheus-community/helm-charts/pull/1629
