### ISSUE TITLE
[kube-prometheus-stack] ApiServer rules are no longer available

### ISSUE THREAD

**Issue by AlexanderBabel** [prometheus-community/helm-charts#1650]
### Describe the bug a clear and concise description of what the bug is.

With v27 of the `kube-prometheus-stack` #1646 introduced a new bug.

The setting `.Values.defaultRules.rules.kubeApiserver` has been removed but is still used in the code. Therefore, the default installation does not install the `kube-apiserver.rules` any more.

https://github.com/prometheus-community/helm-charts/blob/ce83c3726b917e0a7c3237c8222ac2bca7e50cc0/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/kube-apiserver.rules.yaml#L7

### What's your helm version?

3.7.2

### What's your kubectl version?

1.22.5

### Which chart?

kube-prometheus-stack

### What's the chart version?

27.0.0

### What happened?

See above

### What you expected to happen?

The ApiServer rules should be installed again.

### How to reproduce it?

Just install the latest version of the chart.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Default

**Comment by monotek** [comment]
Will be fixed in: https://github.com/prometheus-community/helm-charts/pull/1651
