### ISSUE TITLE
Chart maintainers needed

### ISSUE THREAD

**Issue by mrueg** [prometheus-community/helm-charts#1656]
The goal of this issue is to provide an overview on current maintainers, to see if there are additional maintainers needed and attract potential contributors to join the maintainer team.

If you are interested in contributing, feel free to take a look at the table below for needs and comment here. Ideally you have already contributed to this repository and the chart directly (contributions are not necessarily only code but can also happen in form of issues, PR reviews, helpful comments on issues, documentation, blog posts etc.).

| Chart | Maintainer | Maintainers needed? |
| --- | --- | --- |
| alertmanager | @monotek @naseemkullah | |
| alertmanager-snmp-notifier | @maxwo | Yes |
| jiralert | @jkroepke @zanhsieh | |
| kube-prometheus-stack | @andrewgkew @gianrubio @gkarthiks @GMartinez-Sisti @scottrigby @Xtigyro @QuentinBisson | |
| kube-state-metrics | @tariq1890 @mrueg @dotdc | Yes |
| prom-label-proxy | @jkroepke | Yes |
| prometheus | @gianrubio @zanhsieh @Xtigyro @naseemkullah | |
| prometheus-adapter | @mattiasgees @steven-sheehy @hectorj2f | |
| prometheus-blackbox-exporter | @desaintmartin @gianrubio @rsotnychenko @monotek | |
| prometheus-cloudwatch-exporter | @gianrubio @torstenwalter @asherf | |
| prometheus-conntrack-stats-exporter | @monotek | Yes |
| prometheus-consul-exporter | @timm088 @gkarthiks | |
| prometheus-couchdb-exporter | @gkarthiks | Yes |
| prometheus-druid-exporter | @iamabhishek-dubey @sandy724 | |
| prometheus-elasticsearch-exporter | @svenmueller @desaintmartin | |
| prometheus-fastly-exporter | @arslanbekov | Yes |
| prometheus-json-exporter | @schmiddim @zanhsieh | |
| prometheus-kafka-exporter | @gkarthiks @golgoth31 | |
| prometheus-mongodb-exporter | @steven-sheehy | Yes |
| prometheus-mysql-exporter | @juanchimienti @monotek | |
| prometheus-nats-exporter | @okgolove @caarlos0 | |
| prometheus-nginx-exporter | @nlamirault | Yes |
| prometheus-node-exporter | @gianrubio @zanhsieh | Yes |
| prometheus-operator-admission-webhook | @zeritti | Yes |
| prometheus-operator-crds | @dacamposol @desaintmartin | |
| prometheus-pgbouncer-exporter | @stewartshea | Yes |
| prometheus-pingdom-exporter | @monotek @rpahli | |
| prometheus-postgres-exporter | @gianrubio @zanhsieh | Yes |
| prometheus-pushgateway | @gianrubio @cstaud | Ys |
| prometheus-rabbitmq-exporter | @desaintmartin @iamabhishek-dubey @juanchimienti @monotek | |
| prometheus-redis-exporter | @acondrat @zanhsieh | |
| prometheus-smartctl-exporter | @kfox1111 | Yes |
| prometheus-snmp-exporter | @miouge1 | Yes |
| prometheus-stackdriver-exporter | @apenney @rpahli | |
| prometheus-statsd-exporter | @scDisorder | Yes |
| prometheus-to-sd | @acondrat | Yes |

Current maintainers: Feel free to comment on this issue if you need additional help.

Maintenance note: 
regenerate table with:
```
# In chart directory
echo -n "| Chart | Maintainer | Maintainers needed? |\n| --- | --- | --- |"; for i in *; do echo -n "\n| $i | "; yq '.maintainers[]|.name' ${i}/Chart.yaml | sed -e "s/\"//g" -e "s/^/@/" | tr '\n' ' '; echo -n "| |"; done
```

**Comment by dotdc** [comment]
Hi! Email sent to @mrueg for `kube-state-metrics`

**Comment by desaintmartin** [comment]
I could help on kube-prometheus-stack, being a daily user of this chart, even if I probably won't be able to answer to all PRs.

**Comment by jmichalek132** [comment]
Also willing to help since I use this in my home cluster.

**Comment by Xtigyro** [comment]
@mrueg A very nice idea. I've just put `Yes` for the Kube-Prometheus Stack Chart too.

**Comment by monotek** [comment]
You can add me to kube-prometheus-stack and remove me from prometheus chart.

**Comment by scottrigby** [comment]
Thanks @mrueg ❤️  This is a good follow-up from https://github.com/prometheus-community/helm-charts/issues/21

Several people have reached out to me about the `kube-prometheus-stack` chart. A few things:

* Reaching out to chart maintainers directly – Slack etc – is fine. However you may be better results commenting here publicly. There is also a process listed here:

    > 1. Open a PR proposing yourself as a co-maintainer of one of the charts in need
    > 2. Use the PR to discuss with current maintainer(s)
    > 3. We prefer to see a history of contributing to the prometheus charts or other prometheus projects (not only typo PRs etc), to ensure the maintainers of charts have a good understanding of using and supporting these projects. This will make successful co-maintainership more likely, which will in turn help the end user community
    
    Some of this is documented in https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#adding-chart-maintainers. It may be a good idea to add a little more of this there as well.

    Please note the additional steps needed for all new maintainers, which is documented in this file as well. See https://github.com/prometheus-community/helm-charts/issues/905 for an example issue for this.

*  There are not a limited number of maintainer spots for any chart, however I should probably step down as a maintainer of the `kube-prometheus-stack` chart. I was hesitant to accept it to begin with, since my involvement was mainly in setting up the helm repo, automation, helping rename that chart, and have an overall goal of helping simplify the charts in this repo.
* I am however happy to continue to help administer this repo as needed if folks would like me to continue doing that 😸

**Comment by zanhsieh** [comment]
I think I could help with:

- prometheus-json-exporter
- prometheus-node-exporter
- prometheus-mongodb-exporter
- prometheus-pushgateway
- prometheus-snmp-exporter
- prometheus-statsd-exporter

**Comment by GMartinez-Sisti** [comment]
I'm happy to help with kube-prometheus-stack and/or kube-state-metrics if still needed. Looks like there are now more maintainers on those charts than the ones on the first post.

**Comment by desaintmartin** [comment]
> I'm happy to help with kube-prometheus-stack and/or kube-state-metrics if still needed. Looks like there are now more maintainers on those charts than the ones on the first post.

This one is huge and gets a lot of PRs, so I suppose this is still a good idea.

**Comment by GMartinez-Sisti** [comment]
I just realized I'm not getting emails for PRs and such.

Some of the new maintainers need write access to the repository. The [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS) file reflects the ones with missing permissions.

**Comment by nikhil-bhat** [comment]
I could help with kube-prometheus-stack

**Comment by monotek** [comment]
Thanks for the offer but imho we look for people who have contributed to the kube-prometheus-stack chart or the repo regularly before.

**Comment by GMartinez-Sisti** [comment]
> I just realized I'm not getting emails for PRs and such.
> 
> Some of the new maintainers need write access to the repository. The [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS) file reflects the ones with missing permissions.

This is still an issue. If the new maintainers don't have write access this effort had no results 😢 

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/19713226/166666338-32e5baa8-10db-4e3b-a9d5-a1df20aba170.png">

**Comment by monotek** [comment]
I guess the maintainers which are marked ass error need to be add to the github group too: https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers

But i can't do it.

@torstenwalter 
can you help?

**Comment by torstenwalter** [comment]
@monotek I also do not have permission to add people. @scottrigby do you know to whom to reach out to?

**Comment by SuperQ** [comment]
Yes, we have a prometheus-dev channel, but it's preferred to track requests to add people via issues. GitHub only allows "Owners" to invite new collaborators.

**Comment by monotek** [comment]
@scottrigby i'll put it on my todo list but might take some time. 
first off to kubecon :)

**Comment by subbuprasantp** [comment]
Hi i could help with
--> kube-prometheus-stack

**Comment by monotek** [comment]
> Hi i could help with --> kube-prometheus-stack

we're looking for people which are already activly contributing to the repo. 
without [any contributions](https://github.com/prometheus-community/helm-charts/commits?author=subbuprasantp) it's hard to evaluate a new maintainer.

**Comment by arslanbekov** [comment]
Hey, if need any help, I can help with `kube-prometheus-stack` too.

**Comment by GMartinez-Sisti** [comment]
> @scottrigby i'll put it on my todo list but might take some time. first off to kubecon :)

Kind ping on the missing permissions 😊

**Comment by GMartinez-Sisti** [comment]
Hi All,

According to the latest revision to date of the [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/6b76e2ae77d944a81859097836a6301538d73ebb/.github/CODEOWNERS) file, the following users still require being added to [@prometheus-community/helm-charts-maintainers](https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers) in order to be able to help maintaining the charts (in order from file):

- @jkroepke
- @GMartinez-Sisti
- @iamabhishek-dubey
- @sandy724
- @svenmueller
- @arslanbekov
- @schmiddim
- @golgoth31
- @nlamirault
- @cstaud
- @iamabhishek-dubey
- @kfox1111
- @miouge1
- @apenney
- @scDisorder

I've checked that they are already part of the specific `Chart.yaml` files as maintainers.

Would really like to help getting this sorted to start contributing back to this awesome community.

Thank you

**Comment by zanhsieh** [comment]
@scottrigby 
Are you able to do that? ^^^

**Comment by GMartinez-Sisti** [comment]
I just realised at least one year has passed since a lot of us volunteered to help 😢 ... This effort is very valuable for the community. Would really like to see this happening. 🙏

**Comment by SuperQ** [comment]
Yes, it would be nice to get some issues filed to track invites.

**Comment by GMartinez-Sisti** [comment]
From what I gathered, now we only need to add the users listed here to the [@prometheus-community/helm-charts-maintainers](https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers) group: https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1316671239.

**Comment by QuentinBisson** [comment]
Do we need to create an issue per person to invite?

**Comment by SuperQ** [comment]
Yes, that would be preferred.

**Comment by GMartinez-Sisti** [comment]
Created mine here https://github.com/prometheus-community/helm-charts/issues/3231. Thanks!

**Comment by gracedo** [comment]
I'm not sure if chart maintainers are still needed, but I'd be happy to help maintain `kube-prometheus-stack` :)

**Comment by zeritti** [comment]
I can help maintain
- prometheus-smartctl-exporter
- prometheus-postgres-exporter
- prometheus-pgbouncer-exporter
- prometheus-mongodb-exporter
- prometheus-nginx-exporter
- prometheus-couchdb-exporter

**Comment by zanhsieh** [comment]
> I can help maintain
> 
> * prometheus-smartctl-exporter
> * prometheus-postgres-exporter
> * prometheus-pgbouncer-exporter
> * prometheus-mongodb-exporter
> * prometheus-nginx-exporter
> * prometheus-couchdb-exporter

@zeritti Please create a PR per chart.  For example, https://github.com/prometheus-community/helm-charts/issues/3231 .
Thanks.

**Comment by xiu** [comment]
Hi! If possible, I'd be happy to help on `prometheus-snmp-exporter` and `prometheus-json-exporter`. Created two PRs: 
* #3405 
* #3406
