### ISSUE TITLE
policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by srfrnk** [prometheus-community/helm-charts#1658]
### Describe the bug a clear and concise description of what the bug is.

When installing chart you get lots of:
```
W0103 10:29:29.103757 2187366 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
````
In the future these would probably turn into errors preventing installation rendering the chart unusable.
Any plans of addressing this?

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

27.1.0

### What happened?

When installing chart you get lots of:
```
W0103 10:29:29.103757 2187366 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
````

### What you expected to happen?

No warning. Chart should stop using `PodSecurityPolicy`.
See [here](https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/) and [here](https://kubernetes.io/docs/concepts/policy/pod-security-policy/)

Probably could be replaced with [`PodSecurityContext`](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context)

### How to reproduce it?

Install chart using helm on any K8s cluster using version v1.21+
```bash
helm upgrade -i --wait -n monitoring kube-prometheus-stack kube-prometheus-stack --repo https://prometheus-community.github.io/helm-charts \
        --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.probeSelectorNilUsesHelmValues=false
```

### Enter the command that you execute and failing/misfunctioning.

```bash
helm upgrade -i --wait -n monitoring kube-prometheus-stack kube-prometheus-stack --repo https://prometheus-community.github.io/helm-charts \
        --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
        --set prometheus.prometheusSpec.probeSelectorNilUsesHelmValues=false
```

**Comment by ChristoPedro** [comment]
I'm facing the same issue after updating the Kubernetes to version 1.21.5. It seems we need to use the kube-prometheus release 9.0 according to the documentation [Kube-Prometheus](https://github.com/prometheus-operator/kube-prometheus#compatibility) But I don't know how to refer this release during helm install.

**Comment by monotek** [comment]
That's just a warning. Can be ignored.

There is also already a PR disabling it by default: https://github.com/prometheus-community/helm-charts/pull/1657

**Comment by srfrnk** [comment]
> That's just a warning. Can be ignored.
> 
> There is also already a PR disabling it by default: #1657

Will become an **error** in K8s 1.25+

**Comment by srfrnk** [comment]
@ChristoPedro I was looing throught the PR mentioned by @monotek and it seems you can use this to workaround this issue:
```bash
helm upgrade -i --wait -n monitoring kube-prometheus-stack kube-prometheus-stack --repo https://prometheus-community.github.io/helm-charts \
--set kube-state-metrics.podSecurityPolicy.enabled=false \
--set prometheus-node-exporter.rbac.pspEnabled=false \
--set grafana.rbac.pspEnabled=false \
--set global.rbac.pspEnabled=false
```

**Comment by sander1095** [comment]
A workaround is mentioned, but I think we need an official release because 1.25 is now upon us ;) 

Any updates on this?

**Comment by devmanuelgonzalez** [comment]
Hello everyone, Im facing the same issue right now, do you guys manage to figure it out? the workaround that @srfrnk mentioned didnt work for me :(
