### ISSUE TITLE
[prometheus-kube-stack] CPU metrics don't show up in Grafana

### ISSUE THREAD

**Issue by devent** [prometheus-community/helm-charts#1661]
### Describe the bug a clear and concise description of what the bug is.

Hi. I have tried the prometheus-kube-stack, most metrics are available, but the CPU Usage in Kubernetes / Compute Resources / Cluster dashboard is not. The query in Grafana is as following:

`sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster"}) by (namespace)`

But if I run this in Prometheus then nothing is shown:

`sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate) by (namespace)`

This runs fine:

`sum(container_cpu_usage_seconds_total) by (namespace)`

Do I have the wrong Kubernetes version with the wrong prometheus-kube-stack version? Is there a version matrix?

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

27.1.0

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n kube-prometheus

**Comment by groundhog2k** [comment]
I can confirm that this bug seems to start with kube-prometheus-stack version 24.0.0 and CPU metrics was working before in 23.3.2.

How to reproduce?
Install kube-prometheus-stack-version 23.3.2 first:
`helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n kube-prometheus --version="23.3.2"`
Wait until all services are up and running and CPU metrics are shown in Grafana.

Upgrade the installed version to 24.0.0:
`helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -n kube-prometheus --version="24.0.0"`
Wait until all services are up a few minutes later the CPU metrics will be ZERO/n.a.

A downgrade to 23.3.2 fixed it for me.

**Comment by devent** [comment]
Can it be something to do with kube-state-metrics? Because in Grafana there is the variable `cluster` that you get from `label_values(up{job="kube-state-metrics"}, cluster)`. But there is no `job="kube-state-metrics"` in Prometheus.

There is also no target in Prometheus to kube-state-metrics. 

![image](https://user-images.githubusercontent.com/82924/147950989-54887775-725e-4bda-9f5d-d624d75679e2.png)

(ignore the red targets, they are running. The ports are just not available)

But Pod, ServiceMonitor, and Service for kube-state-metrics are running and seems to have the correct label.

```
kubectl -n$ns get svc 
NAME                                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
alertmanager-operated                            ClusterIP   None             <none>        9093/TCP,9094/TCP,9094/UDP   20h
kube-prometheus-stack-alertmanager               ClusterIP   10.105.84.178    <none>        9093/TCP                     20h
kube-prometheus-stack-grafana                    ClusterIP   10.104.39.209    <none>        80/TCP                       20h
kube-prometheus-stack-kube-state-metrics         ClusterIP   10.99.107.147    <none>        8080/TCP                     20h
kube-prometheus-stack-operator                   ClusterIP   10.96.94.59      <none>        443/TCP                      20h
kube-prometheus-stack-prometheus                 ClusterIP   10.101.126.144   <none>        9090/TCP                     20h
kube-prometheus-stack-prometheus-node-exporter   ClusterIP   10.104.42.193    <none>        9100/TCP                     20h
prometheus-operated                              ClusterIP   None             <none>        9090/TCP                     20h
```

```kubectl -n$ns get ServiceMonitor
NAME                                             AGE
kube-prometheus-stack-alertmanager               20h
kube-prometheus-stack-apiserver                  20h
kube-prometheus-stack-coredns                    20h
kube-prometheus-stack-grafana                    20h
kube-prometheus-stack-kube-controller-manager    20h
kube-prometheus-stack-kube-etcd                  20h
kube-prometheus-stack-kube-proxy                 20h
kube-prometheus-stack-kube-scheduler             20h
kube-prometheus-stack-kube-state-metrics         20h
kube-prometheus-stack-kubelet                    20h
kube-prometheus-stack-operator                   20h
kube-prometheus-stack-prometheus                 20h
kube-prometheus-stack-prometheus-node-exporter   20h
```

```
kubectl -n$ns get pods
NAME                                                        READY   STATUS    RESTARTS   AGE
alertmanager-kube-prometheus-stack-alertmanager-0           2/2     Running   0          20h
kube-prometheus-stack-grafana-7c57674669-prx25              3/3     Running   0          20h
kube-prometheus-stack-kube-state-metrics-7979c567fd-pthwk   1/1     Running   0          20h
kube-prometheus-stack-operator-f68c5d897-xzsr5              1/1     Running   0          3h16m
kube-prometheus-stack-prometheus-node-exporter-5wcl8        1/1     Running   0          20h
kube-prometheus-stack-prometheus-node-exporter-ts4j7        1/1     Running   0          20h
kube-prometheus-stack-prometheus-node-exporter-x4nl9        1/1     Running   0          20h
prometheus-kube-prometheus-stack-prometheus-0               2/2     Running   0          168m
```

**Comment by devent** [comment]
Yes, it was kube-state-metrics. See also https://github.com/prometheus-community/helm-charts/issues/1631
With the workaround it works now. I will close this issue. But I still have another problem.
