### ISSUE TITLE
prometheus-pushprox request to integrate in charts

### ISSUE THREAD

**Issue by paul-bormans** [prometheus-community/helm-charts#1663]
### Is your feature request related to a problem ?

When running kube-prometheus-stack on a RKE2 powered k8s stack the metrics for etcd, controller-manager and scheduler don't show up (failed to scrape). The reason is that these services are running on the host network on the control-plane and so additional network openings wold be required which isn't always possible.

A solution that rancher includes (i believe to refer to it as rancher/monitoring) is to integrate the PushProx from prometheus-community. See https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/how-monitoring-works/#5-5-scraping-metrics-with-pushprox and in code (chart) here: https://github.com/rancher/charts/tree/dev-v2.6/packages/rancher-pushprox.

### Describe the solution you'd like.

Extend the helm-charts with an optional Proxy deployment to enable a route to the host network over the overlay network (canal).

### Describe alternatives you've considered.

Alternative would be to connect directly over the hostnetwork, thus requiring additional network connections to be made; while i prefer to stay on the overlay network.

**Comment by dragoangel** [comment]
Unstale it please

**Comment by kiumarsj** [comment]
I'm having exactly same problem. I also think the solution is to have PushProx in the chart. How possible is it to be implemented?
