### ISSUE TITLE
[kube-prometheus-stack] Can't scrape kube-state-metrics

### ISSUE THREAD

**Issue by briankosw** [prometheus-community/helm-charts#1666]
### Describe the bug a clear and concise description of what the bug is.

I installed Prometheus and Grafana using `kube-prometheus-stack`, and I'm able to successfully access both using ingress. However, I can't I query any metrics exposed by `kube-state-metrics` such as `kube_pod_info`. Other metrics are working perfectly fine.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

27.2.0

### Enter the changed values of values.yaml?

```
prometheus:
  prometheusSpec:
    externalUrl: https://prometheus.{domain}
```

### Enter the command that you execute and failing/misfunctioning.

`helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace -f kube-prometheus-stack-values.yaml`

### Anything else we need to know?

Kubernetes version: 1.21
Kubernetes platform: EKS

**Comment by devent** [comment]
I think it's the same issue as in https://github.com/prometheus-community/helm-charts/issues/1631
There is a workaround.

**Comment by briankosw** [comment]
Ah thank you very much - that works perfectly!
