### ISSUE TITLE
[kube-prometheus-stack] Add maintainer to org

### ISSUE THREAD

**Issue by andrewgkew** [prometheus-community/helm-charts#1676]
Hi @brancz or @SuperQ  

Could one of you please add @andrewgkew to the prometheus-community/helm-charts-maintainers GitHub team as per https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#adding-chart-maintainers

https://github.com/prometheus-community/helm-charts/blob/a094c9d906fb3aec2b206a161bd7aa920a2ff693/.github/CODEOWNERS#L10

Related to https://github.com/prometheus-community/helm-charts/pull/1672

Thank you

**Comment by SuperQ** [comment]
Invite sent.
