### ISSUE TITLE
[prometheus-kube-stack] node-exporter pod does not run by default on master node

### ISSUE THREAD

**Issue by divick** [prometheus-community/helm-charts#1685]
### Describe the bug a clear and concise description of what the bug is.

After deploying the chart I expected the node-exporter to run on all nodes but probably it unable to run on master node because the master node is tainted with:

```
Taints:             node-role.kubernetes.io/master:NoSchedule
```

when I describe the pod which is unscheduled, I see this:

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  44s (x9 over 6m52s)  default-scheduler  0/4 nodes are available: 1 Too many pods, 3 node(s) didn't match Pod's node affinity/selector.
```

I can see node-exporter pod running on non master nodes but not on master when I describe the master node. I am not sure how to run node-exporter on master node without removing the taint or if at all that is the reason for the taint.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

27.2.1

### What happened?

The deployment of node-exported daemonset does not complete.

### What you expected to happen?

I expected it to run on all nodes including master.

### How to reproduce it?

I simply provisioned a simple k8s cluster using kops and then simply installed the said helm chat for kube-prometheus and I immediately get this error.

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus prometheus-community/kube-prometheus-stack --version 27.2.1

**Comment by monotek** [comment]
This should not work by default.
You woul need to add an toleration.
See: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L141

**Comment by divick** [comment]
@monotek Since I installed prometheus-community/kube-prometheus-stack, I presume you mean I mean to update the values.yaml from this stack instead of applying changes to prometheus-nodes-exporter/values.yaml?

**Comment by monotek** [comment]
Yes, waht you can do here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1363 with the values from here: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L141

**Comment by divick** [comment]
@monotek It seems to work now. I am wondering is there some documentation on this community chart so that it works out of the box for a given k8s cluster?

**Comment by monotek** [comment]
Normally it's unwanted to run workloads on the master node therefore such tolerations are not set by default.

It also depends on the cluster you use.

**Comment by divick** [comment]
My problem was not just having :NoSchedule taint on master node but also that there were too many pods on master and using awsvpc limits the number of pods to eni*number_of_ip_addresses_per_eni, which varies from machine type to machine type. Since I was running t3.small machines for master, it was limiting it to 12 pods. Changing the machine type to t3.medium solved the issue for me.
