### ISSUE TITLE
[kube-prometheus-stack] incorrect cluster selector in etcd dashboard

### ISSUE THREAD

**Issue by maxpain** [prometheus-community/helm-charts#1689]
### Which chart?

kube-prometheus-stack

### What's the chart version?

28.0.1

### What happened?

`etcd` dashboard uses `job` label instead of `cluster`.
When you have multiple Kubernetes clusters, all metrics on `etcd` dashboard are aggregated by `job` label (in my case "etcd-metrics"), rather than by `cluster` label.

<img width="652" alt="Screenshot 2022-01-07 at 16 34 00" src="https://user-images.githubusercontent.com/5875582/148551393-ccc08ed0-ac07-4dc8-93df-ea2d6333ce13.png">
 

### What you expected to happen?

`etcd` dashboard should use `cluster` label instead of `job`.

<img width="1116" alt="Screenshot 2022-01-07 at 16 36 44" src="https://user-images.githubusercontent.com/5875582/148551708-69ce9b01-59e3-42e7-9f32-dbcb9d31cb8f.png">

### How to reproduce it?

Just install pure kube-prometheus-stack chart with `grafana.sidecar.dashboards.multicluster.etcd.enabled=true` and open `etcd` dashboard in grafana.

### Enter the changed values of values.yaml?

```yaml
grafana:
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
        etcd:
          enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack

### Anything else we need to know?

https://github.com/prometheus-community/helm-charts/blob/46c3cfaa6b845f25f9d182ff8bce591c2fb89566/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/etcd.yaml#L1070

**Comment by maxpain** [comment]
Up

**Comment by maxpain** [comment]
Up

**Comment by maxpain** [comment]
Up

**Comment by Aslan-Liu** [comment]
Why close this issue? I think this issue still existing. Does anyone know how to fix it quickly?

**Comment by davit-space** [comment]
Please reopen this issue. It still exists in 69.2.4
