### ISSUE TITLE
The servicemonitor under other ns cannot be found automatically

### ISSUE THREAD

**Issue by my1990** [prometheus-community/helm-charts#1694]
### Describe the bug a clear and concise description of what the bug is.

Already set：
prometheus：
  prometheusSpec：
    serviceMonitorNamespaceSelector: {}
But prometheus does not automatically discover the servicemonitor under other ns

### What's your helm version?

v3.2.0

### What's your kubectl version?

v1.21.2

### Which chart?

prometheus

### What's the chart version?

 v2.32.1

### What you expected to happen?

Prometheus can automatically discover the servicemonitor under other ns

### Enter the changed values of values.yaml?

prometheus：
  prometheusSpec：
    serviceMonitorNamespaceSelector: {}

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus   -n monitoring prometheus/kube-prometheus-stack/

**Comment by andrewgkew** [comment]
@my1990 this is not a bug. By default the following field is set to true:

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2224

This sets up the auto discovery of the service monitor resources to be filtered by values from within the helm deployment.

If you want to open up your auto discovery to all SM resources from every namespace then set this field to false either in your own values file or using the --set switch when installing the helm chart

```
promtheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
```
