### ISSUE TITLE
[prometheus-kube-stack] Memory Utilisation expression evaluating to N/A

### ISSUE THREAD

**Issue by aidan-og** [prometheus-community/helm-charts#1695]
### Describe the bug a clear and concise description of what the bug is.

The "Memory Utilization" gauge in "Kubernetes / Compute Resources / Cluster" dashboard consistently evaluates to "N/A"

Link to expression: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml#L334

Screenshot of expression + result in Grafana query inspector:
![image](https://user-images.githubusercontent.com/85623957/148767024-9c5939f4-9413-45c5-a3ec-534e8d250d9d.png)

### What's your helm version?

3.4.2

### What's your kubectl version?

1.21.2

### Which chart?

prometheus-kube-stack

### What's the chart version?

30.0.0

### What happened?

The memory utilisation gauge metric in the "Kubernetes / Compute Resources / Cluster" dashboard in Grafana is evaluating to N/A. This is consistent across different time intervals. I tried changing the expression in Grafana's query inspector from:

```
1 - sum(:node_memory_MemAvailable_bytes:sum{cluster="$cluster"}) / sum(kube_node_status_allocatable_memory_bytes{cluster="$cluster"})
```
to
```
1 - sum(node_memory_MemAvailable_bytes{cluster="$cluster"}) / sum(kube_node_status_allocatable_memory_bytes{cluster="$cluster"})
```

and it evaluates to a number which appears reasonable. Both  `sum(node_memory_MemAvailable_bytes{cluster="$cluster"})` and `sum(kube_node_status_allocatable_memory_bytes{cluster="$cluster"})` return values individually, so the issue appears to be related to the format of the expression `:node_memory_MemAvailable_bytes:sum`.

### What you expected to happen?

I expect the expression to return a valid percentage value for memory utilisation.

### How to reproduce it?

1.  deploy prometheus node exporter, grafana and kube-state-metrics using the 'kube-prometheus-stack' chart specified above.
2. navigate to Grafana --> "Kubernetes / Compute Resources / Cluster" dashboard
3. look at the "Memory Utilisation" gauge at the top of the dash

### Enter the command that you execute and failing/misfunctioning.

The expression (found here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml#L345
```
"expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\",cluster=\"$cluster\"})"
```

**Comment by djablonski-moia** [comment]
Had the same problem, but found the solution here: https://changelog.skyscrapers.eu/kubernetes/2021/08/10/component-upgrades.html
Just replace `kube_node_status_allocatable_memory_bytes` with `kube_node_status_allocatable{resource="memory", unit="byte"}`. At least it worked for me 😄

**Comment by aidan-og** [comment]
That is very strange. @shinebayar-g can you confirm that it is the same command as below when you open the query inspector for "Memory Utilisation"? 

```
1 - sum(:node_memory_MemAvailable_bytes:sum{cluster="$cluster"}) / sum(kube_node_status_allocatable_memory_bytes{cluster="$cluster"})
```

**Comment by shinebayar-g** [comment]
```
1 - sum(:node_memory_MemAvailable_bytes:sum{cluster="$cluster"}) / sum(node_memory_MemTotal_bytes{job="node-exporter",cluster="$cluster"})
```

What's your k8s server version?

**Comment by monotek** [comment]
Prometheus sharding + Thanos and recording rules cab be a problem too. 
Try to set grafana timrange to 1 day.

**Comment by aidan-og** [comment]
@shinebayar-g we have multiple clusters each running the same version of Prometheus and Grafana. Some clusters are running Kubernetes server version 1.20.7, others are running 1.21.2. We're seeing this issue on all Grafana instances.

@monotek thanks for the suggestion but no time range produces a valid result. I'll try a fresh re-deploy via Helm and see if that fixes the issue.
