### ISSUE TITLE
Request for changelog

### ISSUE THREAD

**Issue by githubcdr** [prometheus-community/helm-charts#1697]
### Is your feature request related to a problem ?

I'd like to see a changelog for releases, the chart versions move fast without logs it's hard to estimate the impact of a release.

### Describe the solution you'd like.

Like to see a list

- breaking changes, if any
- new features
- upgrade steps

It would also be nice to be able to detect what a new major version would differ from a minor version upgrade. It seems every upgrade is a major release.

### Describe alternatives you've considered.

doing git logs :|

**Comment by monotek** [comment]
For major version changes there is the upgrading section in the charts readme. 
Example: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart

All other changes are bugfixes or feature additions which do not necessarily need a changelog as updates will not change anything for a user.
