### ISSUE TITLE
[prometheus-adapter] Starting 3.0.1 horizontal pod autoscaler can't access external metrics

### ISSUE THREAD

**Issue by mfamador** [prometheus-community/helm-charts#1739]
### Describe the bug a clear and concise description of what the bug is.

Updating to helm chart version `3.0.1`, the hpa aren't able to access the external metrics.

```
Warning  FailedGetExternalMetric  3m35s (x843 over 3h38m)  horizontal-pod-autoscaler  unable to get external metric data/kafka_consumergroup_lag/&LabelSelector{MatchLabels:map[string]string{consumergroup: readings,topic: readings-enricher-integrations,},MatchExpressions:[]LabelSelectorRequirement{},}: unable to fetch metrics from external metrics API: kafka_consumergroup_lag.external.metrics.k8s.io is forbidden: User "system:serviceaccount:kube-system:horizontal-pod-autoscaler" cannot list resource "kafka_consumergroup_lag" in API group "external.metrics.k8s.io" in the namespace "data"
```

I believe this was introduced on this commit: https://github.com/prometheus-community/helm-charts/commit/085ea5d139597a1acf4ec87d1f3ebc3f5fcacb9a

Reverting to chart `3.0.0` everything goes back to normal and the HPA is able to fetch the external metrics.

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"a5e4de7e277a707bd28d448bd75de58b4f1cdc22", GitTreeState:"clean", BuildDate:"2021-11-16T01:09:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-adapter

### What's the chart version?

3.0.1

### Enter the command that you execute and failing/misfunctioning.

describe hpa my-hpa

**Comment by bernard-blackpoint** [comment]
+1

Prior to `3.0.1` the [cluster role granting access to external metrics](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/templates/external-metrics-cluster-role.yaml) was correctly bound to the `system:serviceaccount:kube-system:horizontal-pod-autoscaler` user, which K8S uses to fetch HPA metrics

**Comment by yiyan-wish** [comment]
+1
