### ISSUE TITLE
[Question] Thanos sidecars exposed over ingress in Prometheus HA configuration with 2 Replicas

### ISSUE THREAD

**Issue by mattheews** [prometheus-community/helm-charts#1740]
Hi,

I have the configuration of kube-prometheus-stack with two replicas of Prometheus. Now I decided to integrate thanos to centrally collect metrics from both Prometheus instances. My first thought was that I need to expose each replica thanos-sidecar over ingress thanks this on the central thanos instance I will be able to add each sidecar as source eq thanos-1.mysetup & thanos-2.mysetup.
However from the available helm templates I can't see relevant templates that will create two ingress for thanos-sidecars (something like thanosIngresPerReplica as it is IngresPerReplica for Prometheus instances). Am I missing something important in thanos architecture and exposing each thanos-sidecar is not required and can be done different way?

Thank You for all the thoughts

**Comment by justin-chizer** [comment]
@mattheews Were you able to resolve this? Having a similar issue

**Comment by bdols** [comment]
is it possible to expose the thanos sidecars with any ingress class currently? I'm not seeing that it's possible without something like the above idea implemented
