### ISSUE TITLE
[prometheus] Cannot update from 15.1.0 to 15.1.1: cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid

### ISSUE THREAD

**Issue by headyj** [prometheus-community/helm-charts#1747]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to update from 15.1.0 to 15.1.1, but having the following issue: 
```cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable```

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.1.1

### What happened?

When trying to update from 15.1.0 to 15.1.1, having the following issue: 
```cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable```

### What you expected to happen?

update from 15.1.0 to 15.1.1 should not have breaking changes

### How to reproduce it?

just try a regular update from 15.1.0 to 15.1.1 using helm upgrade

### Enter the changed values of values.yaml?

no changes

### Enter the command that you execute and failing/misfunctioning.

Actually it's done by terraform, but the command should be:
helm upgrade -n prometheus prometheus prometheus-community/prometheus --reuse-values

**Comment by headyj** [comment]
forget it, update was blocked since upgrade from 14.8 to 15.0 but didn't had the notification. Executed the migration kubectl command and everything works perfectly

**Comment by FireFart** [comment]
@headyj having the same problem, how did you fix it?

**Comment by vhosakot** [comment]
saw same error when helm upgrading prometheus `14.6.0` to `15.6.0`:
```
Error: UPGRADE FAILED: cannot patch "monitor-kube-state-metrics" with kind Deployment: Deployment.apps "monitor-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitor", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
per https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150, deleting `kube-state-metrics` deployment and then re-trying helm upgrade worked and prometheus was successfully upgraded to `15.6.0`.
