### ISSUE TITLE
externallabels not set for some alerts

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-community/helm-charts#175]
We have externallabels set in PrometheusSpec as below,
<img width="699" alt="image" src="https://user-images.githubusercontent.com/14121261/94976534-23797780-04ca-11eb-8848-f3ad9e0a5070.png">

"cluster" is set in external_labels.

Issue:
The issue we are facing is the label is not set in daemonset pods when there is CPUThrottlingHIGH alert.This is not happening for all the alerts in daemonset.
![image](https://user-images.githubusercontent.com/14121261/94976688-9387fd80-04ca-11eb-9445-3d4b1ef56b0a.png)

But the deployment object pods shows the label,
![image](https://user-images.githubusercontent.com/14121261/94976747-caf6aa00-04ca-11eb-85ba-7e4664ec5ca7.png)

The same issue happens in Cronjob alert "KubeCronJobRunning",
![image](https://user-images.githubusercontent.com/14121261/94976798-f083b380-04ca-11eb-8085-3f66273ca054.png)

Expectation:
All the alerts must show the external_labels

Kube-Prometheus-stack version 9.4.0
Kubernetes version 1.15
EKS

**Comment by KR411-prog** [comment]
Could anyone help on this?

**Comment by ramvibhulaanandh** [comment]
@KR411-prog how did you solved
