### ISSUE TITLE
[prometheus] [FR] Allow the Chart to create extra manifest

### ISSUE THREAD

**Issue by pierluigilenoci** [prometheus-community/helm-charts#1753]
### Is your feature request related to a problem ?

Sometimes, accessory to the installation there may be manifest to be installed (for example a SecretProviderClass or a PVC).

### Describe the solution you'd like.

It would be nice to be able to do this directly via the Chart using the approach that ArgoCD also uses.

Ref: https://github.com/argoproj/argo-helm/blob/cf57a71a154a1a8a19f5f9d3980d60eb3efd80c8/charts/argo-cd/values.yaml#L62-L87

### Describe alternatives you've considered.

I don't think there are alternatives

**Comment by pierluigilenoci** [comment]
@ranjith-ka @snowzach what do you think about it?

**Comment by pierluigilenoci** [comment]
@ranjith-ka @snowzach what do you think about it?

**Comment by pierluigilenoci** [comment]
@ranjith-ka @snowzach what do you think about it?

**Comment by ranjith-ka** [comment]
@pierluigilenoci  Yes thats true, we might need this feature. It could be handy !! If i look at operators,  But we have operators helm charts as well.

**Comment by pierluigilenoci** [comment]
Still a valid FR.

**Comment by pierluigilenoci** [comment]
@snowzach thank you a lot!

**Comment by pierluigilenoci** [comment]
This is still an open issue
