### ISSUE TITLE
kube-prometheus-stack Upgrade notes from 23-24 are misleading

### ISSUE THREAD

**Issue by BrianKopp** [prometheus-community/helm-charts#1758]
### Describe the bug a clear and concise description of what the bug is.

Hi there! We just walked our kube-prometheus-stack helm chart from version 19 to version 30, and hit a confusing stumbling block from version 23 to 24.

The existing upgrade notes say:
>The custom ServiceMonitor for the kube-state-metrics & prometheus-node-exporter charts have been removed in favour of the built in sub-chart ServiceMonitor; for both sub-charts this means that ServiceMonitor customisations happen via the values passed to the chart. If you haven't directly customised this behaviour then there are no changes required to upgrade, but if you have please read the following.

We did not have any customized behavior on the subchart keys in our `values.yaml` file. Specifically, we didn't have anything for kube-state-metrics or prometheus-node-exporter except for pinned docker image tags, which we upgraded according to the sub-chart values version.

However, post-upgrade, tons of metrics were gone, and our grafana dashboards were mostly blank.

This ultimately was caused by the new ServiceMonitor not being discovered by our prometheus instance. We have the following config in our values.yaml file for the prometheus config:

```yaml
commonLabels:
  prometheus: operator
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchExpressions:
      - key: prometheus
        operator: In
        values:
        - operator
        - scrape
```

And so in our case, the ServiceMonitors installed by helm chart version 23 had the label `prometheus: operator` and therefore was discovered by our prometheus instances. However, in version 24 of the helm chart, the ServiceMonitors for kube-state-metrics and prometheus-node-exporter *did not* have these labels, and therefore weren't discovered.

This was confusing since the upgrade notes seemed to suggest that we wouldn't need to touch anything. It wasn't clear that the `commonLabels` or `serviceMonitorSelector` were relevant customizations that affected these two ServiceMonitors.

Could I propose a PR to improve the wording in the 23->24 upgrade notes here to help someone else avoid this confusion?

Thanks!

### What's your helm version?

version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"archive", BuildDate:"2022-01-27T18:26:18Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.11-eks-f17b81", GitCommit:"f17b810c9e5a82200d28b6210b458497ddfcf31b", GitTreeState:"clean", BuildDate:"2021-10-15T21:46:21Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

24.0.1

### What you expected to happen?

Expected the upgrade notes to be more clear to prevent losing ServiceMonitors from my prometheus discovery.

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by thinkernel** [comment]
I have the same issue. In my case, "release: prometheus" seems to be the missing label.
