### ISSUE TITLE
[kube-prometheus-stack] How add additional labels to external node-exporters, outside k8s cluster

### ISSUE THREAD

**Issue by allanian** [prometheus-community/helm-charts#1764]
### Is your feature request related to a problem ?

Hello, we have k8s cluster, what monitored prometheus, from helm kube-prometheus-stuck.
Also we have additional servers outside our k8s cluster, like
- server1-dev
- server2-prod
we installed node-exporters on that servers and create servicemonitor,service and endpoints.
We want to sort it in grafana with label, example:
env - dev or prod
can you help us with that issue?

### Describe the solution you'd like.

need a solution what can provide additional labels to grafana, like env name.

### Describe alternatives you've considered.

for now, we can split them with creating new servicemonitor, service and endpoint.

**Comment by allanian** [comment]
resolved, thx

**Comment by labaq** [comment]
Hi @allanian 
can you tell me how to solved?
i want to filter my k8s node, but i also found that node-exporter no record the labels

**Comment by allanian** [comment]
@labaq prometheus supported additional-scrape-configs, so you just create a secret from prometheus targets with addaitional labels and its working

**Comment by labaq** [comment]
i'm not familiar with prometheus scrape setting. will you like to share example abount how to scrape the node labels for me?

**Comment by labaq** [comment]
@allanian thx, I found a way

**Comment by allanian** [comment]
@labaq nice, yep, just use default prometheus config with targets and import as additional scrape config
```
- job_name: node-exporter-external
  scheme: http
  static_configs:
  - targets:
    - efk:9100
    - efk2:9100
    labels:
      target_severity: non-critical

```
