### ISSUE TITLE
I am not able to set extraArgs for alertmanager sts 

### ISSUE THREAD

**Issue by barantomasz83** [prometheus-community/helm-charts#1771]
### Describe the bug a clear and concise description of what the bug is.

Hi,
I want to set --web.config.file argument for alertmanager and use https [https://prometheus.io/docs/alerting/latest/https/](https://prometheus.io/docs/alerting/latest/https/) but when I try to set it in values file (or through set in terraform helm_release) it doesn't work. I tried to place it ,in values file, under "alertmanager" and "alertmanager.alertmanagerSpec" as on example below:
![image](https://user-images.githubusercontent.com/67588485/152655019-c358b9e2-fe41-4cd3-a9f4-f6ae6ca66c79.png)

When I do the same directly for alertmanager chart it works fine:
![image](https://user-images.githubusercontent.com/67588485/152655064-fe15302c-5387-44ec-adef-963f1c5accd4.png)

Is it bug or I am doing something wrong?

### What's your helm version?

v3.6.3

### What's your kubectl version?

1.21

### Which chart?

kube-prometheus-stack

### What's the chart version?

31.0.0

### What you expected to happen?

pass --web.config.file argument for alertmanager STS

### Enter the changed values of values.yaml?

alertmanager:
  extraArgs:
    web.config.file: "/etc/alertmanager/configmaps/alertmanager-web-config/web_config.yaml"
   
  alertmanagerSpec:
    extraArgs:
      web.config.file: "/etc/alertmanager/configmaps/alertmanager-web-config/web_config.yaml"

### Enter the command that you execute and failing/misfunctioning.

I am using terraform

**Comment by ilovemysillybanana** [comment]
@barantomasz83 did you ever find a solution? I'm having this problem now as well

**Comment by barantomasz83** [comment]
@ilovemysillybanana Unfortunately not. Probably you can deploy alertmanager from separate chart (then it works) and connect it with prometheus, but for me it wasn't so important.
