### ISSUE TITLE
[kube-prometheus-stack] Info alert inhibition rule evaulation failures

### ISSUE THREAD

**Issue by timbuchwaldt** [prometheus-community/helm-charts#1773]
### Describe the bug a clear and concise description of what the bug is.

Hey! We love the newest release with the rule inhibition feature. We sadly see rule evaluation failures:

```
ts=2022-02-07T14:42:17.636Z caller=manager.go:609 level=warn component="rule manager" group=general.rules msg="Evaluating rule failed" rule="alert: InfoInhibitor\nexpr: ALERTS{severity=\"info\"} == 1 unless on(namespace) ALERTS{alertname!=\"InfoInhibitor\",alertstate=\"firing\",severity=~\"warning|critical\"}\n  == 1\nlabels:\n  severity: none\nannotations:\n  description: |\n    This is an alert that is used to inhibit info alerts.\n    By themselves, the info-level alerts are sometimes very noisy, but they are relevant when combined with\n    other alerts.\n    This alert fires whenever there's a severity=\"info\" alert, and stops firing when another alert with a\n    severity of 'warning' or 'critical' starts firing on the same namespace.\n    This alert should be routed to a null receiver and configured to inhibit alerts with severity=\"info\".\n  runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/infoinhibitor\n  summary: Info-level alert inhibition.\n" err="vector contains metrics with the same labelset after applying alert labels"
```

### What's your helm version?

3.8.0

### What's your kubectl version?

1.23

### Which chart?

kube-prometheus-stack

### What's the chart version?

v32

### Enter the command that you execute and failing/misfunctioning.

 none

**Comment by onedr0p** [comment]
I am receiving something simulair everyone once in awhile since upgrading to `32.0.0`

![image](https://user-images.githubusercontent.com/213795/152842053-d45fbd34-f0c3-44af-9fb3-2510b3fd9034.png)

**Comment by cortex3** [comment]
hi, im running into the same issue. What does your config look like and have you resolved it already?

**Comment by cortex3** [comment]
So I think the following works for me as a workaround. But I'm not sure why I need this extra configuration on a fresh install.
```      routes:
      - match:
          alertname: 'InfoInhibitor'
        receiver: 'null'
```

**Comment by irizzant** [comment]
This comes from Prometheus Operator, they added this alert to a `null` receiver themselves see [here](https://github.com/prometheus-operator/kube-prometheus/blob/0ac0d7f9bf5ab1de3e596ff3bdd4b36c52e27267/jsonnet/kube-prometheus/components/alertmanager.libsonnet#L51).

**Comment by theadzik** [comment]
I configured the rule and still get the alert:

```yaml
route:
  group_by:
    - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: 'some-receiver'
  repeat_interval: 24h
  routes:
    - match:
        alertname: 'Watchdog'
      receiver: 'null'
    - match:
        alertname: 'InfoInhibitor'
      receiver: 'null'
    - match:
        severity: 'info'
      receiver: 'null'
    - match:
        namespace: 'staging'
      receiver: 'some-other-receiver'
    - match:
        severity: 'critical'
      receiver: 'yet-another-receiver'
```

Not sure what else do I have to do?

**Comment by cortex3** [comment]
@theadzik have you added null to the list of receivers? eg.
```
    receivers:
    - name: 'null'
```

**Comment by theadzik** [comment]
> @theadzik have you added null to the list of receivers? eg.
> 
> ```
>     receivers:
>     - name: 'null'
> ```

I wanted to say "Of course!" But it turned out I messed up the kustomize patching and it got overwritten :)

Thanks for pointing that out!

**Comment by onedr0p** [comment]
Also, note that `match` is being deprecated in alert manager, you should migrate to using `matchers` :)

**Comment by rdavyd** [comment]
I have the same issue and routing to `null` does not help. The question is how the proposed workaround by @cortex3 is supposed to work? Prometheus still tries to evaluate rule before it is sent to `null` and raises `PrometheusRuleFailures` alert.

**Comment by pseymournutanix** [comment]
I am getting this as well 
```
      routes:
      - receiver: 'null'
        matchers:
        - alertname=~"Watchdog|InfoInhibitor"
```

**Comment by darox** [comment]
I have the same issue despite the fact that I'm using the following example: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-secret.yaml

**Comment by X-Siro** [comment]
I faced a situation when I can't route this alert to null due to using alertmanagerconfig objects. Routes configured in such objects contain `continue: true` and are located at the top of the routes array.

**Comment by joulaud** [comment]
The problem is that the alert rule for InfoInhibitor is not correct as it generates one vector per alertname but the field alertname itself is erased by the created alert. E.g. with alerts 
```
ALERTS{alertname="CPUAboveRequest", alertstate="pending", container="test", namespace="test", pod="test01",severity="info"} 4
```
and
```
ALERTS{alertname="CPUThrottlingHigh", alertstate="pending", container="test", namespace="test", pod="test01",severity="info"} 6
```
The current rule for InfoInhibitor gives two new vectors which differs only by alertname. The alertname being replaced by "InfoInhibitor" this makes two vector with same set of labels.

```
ALERTS{alertname="InfoInhibitor", alertstate="pending", container="test", namespace="test", pod="test01",severity="info"} 4
ALERTS{alertname="InfoInhibitor", alertstate="pending", container="test", namespace="test", pod="test01",severity="info"} 6
```
for which Prometheus rightfully warns.

The fix is to change InfoInhibitor rule e.g. by excluding alertname from the result :
```
      rules:
        - alert: InfoInhibitor
          annotations:
            description: "This is an alert that is used to inhibit info alerts.\n\
              By themselves, the info-level alerts are sometimes very noisy, but they\
              \ are relevant when combined with\nother alerts.\nThis alert fires whenever\
              \ there's a severity=\"info\" alert, and stops firing when another alert\
              \ with a\nseverity of 'warning' or 'critical' starts firing on the same\
              \ namespace.\nThis alert should be routed to a null receiver and configured\
              \ to inhibit alerts with severity=\"info\".\n"
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/general/infoinhibitor
            summary: Info-level alert inhibition.
          # DEFAULT :
          # expr: ALERTS{severity = "info"} == 1 unless on (namespace) ALERTS{alertname
          #   != "InfoInhibitor", severity =~ "warning|critical", alertstate="firing"}
          #   == 1
          expr: |
            count without(alertname, alertstate) (
                ALERTS{severity = "info"} == 1
                unless on (namespace) ALERTS{alertname != "InfoInhibitor", severity =~ "warning|critical", alertstate="firing"} == 1
            )
          labels:
            severity: none
```

**Comment by pschwarzpp** [comment]
This issue also affected us with prometheus-community/kube-prometheus-stack 57.2.0. We applied the workaround described in https://github.com/prometheus-community/helm-charts/issues/1773#issuecomment-1944302431.

This issue should not be closed.

**Comment by vexsx** [comment]
i did it in helm values by adding this :
```
defaultRules:
  create: true
  disabled:
    InfoInhibitor: true
  rules:
    alertmanager: true
    ....
```

then i check it trough :
```
helm get manifest -n monitoring promstack | grep -n "alert: InfoInhibitor" || echo "✅ InfoInhibitor rule not rendered"
```
