### ISSUE TITLE
[kube-state-metrics] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+

### ISSUE THREAD

**Issue by maven2016** [prometheus-community/helm-charts#1774]
### Describe the bug a clear and concise description of what the bug is.

The following warning is printed when deploying kube-state-metrics in k8s cluster version v1.21.6-gke.1500
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

### What's your helm version?

version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-state-metrics

### What's the chart version?

4.3.0

### What happened?

The following warning is printed when deploying kube-state-metrics in k8s cluster version v1.21.6-gke.1500
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

### What you expected to happen?

No warning

### How to reproduce it?

Deploy on k8s cluster v1.21+

### Enter the command that you execute and failing/misfunctioning.

helm install my-release prometheus-community/kube-state-metrics

### Anything else we need to know?

possible fix:
in: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/pdb.yaml
change:
apiVersion: policy/v1beta1
to:
apiVersion: policy/v1

**Comment by dotdc** [comment]
Hi @maven2016,

It seems that we currently don't have a clear policy for the Kubernetes versions we aim to support for the charts in this repository.
I think this is a good question and it could be useful to talk and make a clear statement about it.

For now, I think we shouldn't rush into updating PodDisruptionBudget API version. This will break compatibility for people using this/theses charts on k8s 1.19/1.20 with little to no gain for people using this feature on 1.21+.
Also, the deprecation just started with 1.21 and we have quite some time before it get's removed in 1.25. 

If you think we should update this anyway, please tell us why.

I will open an issue later today about creating a Kubernetes support policy.

**Comment by dotdc** [comment]
Closing this but we will automatically do it for Kubernetes 1.25 when it's there.
Will also work on a compatibility matrix for kube-state-metrics.
