### ISSUE TITLE
[all] Supported Kubernetes versions policy

### ISSUE THREAD

**Issue by dotdc** [prometheus-community/helm-charts#1781]
### Is your feature request related to a problem ?

Hi everyone,
After the issue https://github.com/prometheus-community/helm-charts/issues/1774, I wanted to know if we had a policy or a list of supported version of Kubernetes but couldn't find it.

Currently, each chart has a Kubernetes version in the "Pre-requisites" section of their README.md, but I think most of them are not up-to-date (a few claim to support 1.8+).

As some charts of this repository works together, I think it would make sense to have a global policy to let users know what to expect from the charts included in this repository.

### Describe the solution you'd like.

Create a global policy that informs users on what versions are likely to be supported by the charts of this repository.

Kubernetes supports the last 3 minor version ([source](https://kubernetes.io/releases/version-skew-policy/) + 1 year of patch support on 1.19+.
I think it would make sense to match this policy, as most users and components of the Kubernetes ecosystem will already try to match it.

We could also consider do to a "best effort" support for older versions on some charts, if this doesn't impact the up-to-date users.

What to you think about this?

@scottrigby @monotek @torstenwalter @mrueg 

### Describe alternatives you've considered.

Otherwise, we could keep the way it works right now and just checks and update the README.md in each chart.

**Comment by XC-** [comment]
This is something that I have been looking for as well. In our use case, we have clusters with different versions and need to figure out which version of prometheus-community/prometheus is compatible with which version of kubernetes. Somehow, I once managed to dig this for one of our clusters, but sadly forgot to bookmark the page I used as a starting point and now I cannot find this information from anywhere. It would be really useful to have a compatibility matrix (such as kubernetes-operator has) for each chart.

**Comment by dotdc** [comment]
not stale, will make a compatibility matrix for kube-state-metrics to start with

**Comment by dotdc** [comment]
Closing this issue related to https://github.com/prometheus-community/helm-charts/pull/1930
