### ISSUE TITLE
prometheus-kube-state-metric - .Values.collectors>: error calling has: Cannot find has on type map

### ISSUE THREAD

**Issue by efliction** [prometheus-community/helm-charts#1808]
### Describe the bug a clear and concise description of what the bug is.

Error: malformed chart or values: 

templates/: template: prometheus/charts/kube-state-metrics/templates/role.yaml:18:6: executing "prometheus/charts/kube-state-metrics/templates/role.yaml" at <has "certificatesigningrequests" $.Values.collectors>: error calling has: Cannot find has on type map

### What's your helm version?

helm v1.2.0

### What's your kubectl version?

kubernetes v1.11.3

### Which chart?

prometheus/charts/kube-state-metrics/templates/role.yaml

### What's the chart version?

15.2.0

### What happened?

When we run our pipeline in Azure Devops we get the flowing error:

templates/: template: prometheus/charts/kube-state-metrics/templates/role.yaml:18:6: executing "prometheus/charts/kube-state-metrics/templates/role.yaml" at <has "certificatesigningrequests" $.Values.collectors>: error calling has: Cannot find has on type map

We recently moved over to the https://prometheus-community.github.io/helm-charts
 as https://charts.helm.sh/stable is deprecated.

### What you expected to happen?

This used to work fine when we used the stable repo

### How to reproduce it?

We will need to re-run the pipeline.

### Enter the changed values of values.yaml?

Overrides in Terraform:

  version   = "15.2.0"
  namespace = kubernetes_namespace.monitoring.id

  # Alerting is handled by StackDriver. Alert Manager not required.
  set {
    name  = "alertmanager.enabled"
    value = false
  }

  # All metrics should be pull-only. Push Gateway not required.
  set {
    name  = "pushgateway.enabled"
    value = false
  }

  # ConfigMap Reload not required.
  set {
    name  = "configmapReload.prometheus.enabled"
    value = false
  }

  # All images are stored in-house in DeveloperHub GCR
  set {
    name  = "nodeExporter.image.repository"
    value = "eu.gcr.io/developerhub/third-party/prom/node-exporter"
  }

  set {
    name  = "nodeExporter.image.tag"
    value = "v1.3.0"
  }

  set {
    name  = "kubeStateMetrics"
    value = false
  }

  set {
    name  = "kube-state-metrics.image.repository"
    value = "eu.gcr.io/developerhub/third-party/bitnami/kube-state-metrics"
  }

  # Kube State Metrics Version must be compatible with GKE version (https://github.com/kubernetes/kube-state-metrics#compatibility-matrix)
  set {
    name  = "kube-state-metrics.image.tag"
    value = "v2.1.1"
  }

  # certificatesigningrequests not supported by GKE 1.14
  set {
    name  = "kube-state-metrics.collectors.certificatesigningrequests"
    value = false
  }

  # mutatingwebhookconfigurations not supported by GKE 1.14
  set {
    name  = "kube-state-metrics.collectors.mutatingwebhookconfigurations"
    value = false
  }

  # networkpolicies not supported by GKE 1.14
  set {
    name  = "kube-state-metrics.collectors.networkpolicies"
    value = false
  }

  # validatingwebhookconfigurations not supported by GKE 1.14
  set {
    name  = "kube-state-metrics.collectors.validatingwebhookconfigurations"
    value = false
  }

  # volumeattachments not supported by GKE 1.14
  set {
    name  = "kube-state-metrics.collectors.volumeattachments"
    value = false
  }

  # Monitor only defined namespaces
  set {
    name  = "kube-state-metrics.namespace"
    value = kubernetes_namespace.portal.id
  }

  set {
    name  = "server.image.repository"
    value = "eu.gcr.io/developerhub/third-party/prom/prometheus"
  }

  set {
    name  = "server.image.tag"
    value = "v2.31.1"
  }

  # Storage volume is emptyDir in order to be shared by StackDriver Sidecar
  set {
    name  = "server.persistentVolume.enabled"
    value = false
  }

  # StackDriver Prometheus Sidecar container configuration (https://cloud.google.com/stackdriver/docs/solutions/gke/prometheus)
  set {
    name  = "server.sidecarContainers[0].name"
    value = "sidecar"
  }

  set {
    name  = "server.sidecarContainers[0].image"
    value = "eu.gcr.io/developerhub/third-party/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.8.0"
  }

  set {
    name  = "server.sidecarContainers[0].imagePullPolicy"
    value = "IfNotPresent"
  }

  set {
    name  = "server.sidecarContainers[0].args[0]"
    value = "--stackdriver.project-id=${var.portal_project_name}"
  }

  set {
    name  = "server.sidecarContainers[0].args[1]"
    value = "--stackdriver.kubernetes.location=${var.region}"
  }

  set {
    name  = "server.sidecarContainers[0].args[2]"
    value = "--stackdriver.kubernetes.cluster-name=${google_container_cluster.cluster.name}"
  }

  set {
    name  = "server.sidecarContainers[0].args[3]"
    value = "--prometheus.wal-directory=${local.prometheus_data_directory}/wal"
  }

  set {
    name  = "server.sidecarContainers[0].args[4]"
    value = "--prometheus.api-address=http://127.0.0.1:9090"
  }

  # Reducing costs of StackDriver Monitoring (https://cloud.google.com/stackdriver/docs/solutions/gke/prometheus#managing-costs)
  set {
    name  = "server.sidecarContainers[0].args[5]"
    value = "--include={job=~\"kubernetes-pods\"}"
  }

  set {
    name  = "server.sidecarContainers[0].ports[0].name"
    value = "sidecar"
  }

  set {
    name  = "server.sidecarContainers[0].ports[0].containerPort"
    value = 9091
  }

  set {
    name  = "server.sidecarContainers[0].volumeMounts[0].name"
    value = "storage-volume"
  }

  set {
    name  = "server.sidecarContainers[0].volumeMounts[0].mountPath"
    value = local.prometheus_data_directory
  }

}

### Enter the command that you execute and failing/misfunctioning.

This was done via a pipeline using terraform calling on the public helm charts and setting the vaules for the values.yaml

### Anything else we need to know?

N/A

**Comment by infa-kparida** [comment]
I am also facing the same issue.Any update  ?

**Comment by efliction** [comment]
In version 14.2.2 has function has been introduced you need to user version 14.2.1.  Shame this hasn't been looked at.

**Comment by aignatovich** [comment]
Same issue while installing chart version 4.20.0.

**Comment by ljpowlett** [comment]
For upgrading to this chart I had to update the `collectors` in my values file - they we're updated from a map to a list in https://github.com/prometheus-community/helm-charts/pull/997.
