### ISSUE TITLE
[kube-prometheus-stack] Add migration documentation

### ISSUE THREAD

**Issue by baurmatt** [prometheus-community/helm-charts#181]
**Is your feature request related to a problem? Please describe.**
As a user of stable/prometheus-operator I'd like to have an easy way to migrate to prometheus-community/kube-prometheus-stack without data loss.

**Describe the solution you'd like**
Please add documentation similar to [Migrating from coreos/prometheus-operator chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#migrating-from-coreosprometheus-operator-chart).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by gkarthiks** [comment]
Hi @baurmatt there's a similar effort going on and is carried by @fktkrt. 

Please take a look here https://github.com/prometheus-community/helm-charts/pull/119 and feel free to close this issue if it's duplicate and hope to see your opinions and contributions there.

**Comment by baurmatt** [comment]
Hey @gkarthiks, thank you! :) This is exactly what I'm looking for. Seems like I only search in "Issues" but not in "Pull Requests"
