### ISSUE TITLE
pod/prome-prometheus-node-exporter CreateContainerError Issue Title

### ISSUE THREAD

**Issue by gencube** [prometheus-community/helm-charts#1814]
### Describe the bug a clear and concise description of what the bug is.

After installation which does NOT show any error, the pod error as shown occurred. Also, cannot perform port-forwarding for 
service/prome-prometheus-node-exporter because the pod has error to start up.

### What's your helm version?

v3.7.0

### What's your kubectl version?

v1.23.1

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

32.2.1 

### What happened?

After installation which does NOT show any error, the pod error as shown occurred. Also, cannot perform port-forwarding for 
service/prome-prometheus-node-exporter because the pod has error to start up.

![image](https://user-images.githubusercontent.com/663792/154923539-31b4adc4-eed5-4b7d-8363-e0f4d079e0e7.png)

### What you expected to happen?

Node exporter service is working and can gain access to Prometheus UI

### How to reproduce it?

~$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
~$ helm repo update
~$ helm install prome prometheus-community/kube-prometheus-stack --namespace=prometheus --create-namespace --wait
~$ kubectl get all,sc,pv,pvc --all-namespaces

### Enter the command that you execute and failing/misfunctioning.

~$ kubectl get all,sc,pv,pvc --all-namespaces 

....
prometheus    pod/prome-prometheus-node-exporter-4l7pb                     0/1     CreateContainerError   0               38m

**Comment by gencube** [comment]
FYI: The highlight was shown after investigation of event logs.
![image](https://user-images.githubusercontent.com/663792/155044814-ac976a10-eda3-4691-b74d-3cdf4227aa2e.png)

**Comment by monotek** [comment]
Whats the output of "kubectl describe po"?

**Comment by gencube** [comment]
Name:         prome-prometheus-node-exporter-2g4fw
Namespace:    prometheus
Priority:     0
Node:         ac-boonpangong/172.30.6.183
Start Time:   Mon, 21 Feb 2022 22:44:04 +0800
Labels:       app=prometheus-node-exporter
              chart=prometheus-node-exporter-2.5.0
              controller-revision-hash=76cdfc4684
              heritage=Helm
              jobLabel=node-exporter
              pod-template-generation=1
              release=prome
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: true
Status:       Pending
IP:           172.30.6.183
IPs:
  IP:           172.30.6.183
Controlled By:  DaemonSet/prome-prometheus-node-exporter
Containers:
  node-exporter:
    Container ID:
    Image:         quay.io/prometheus/node-exporter:v1.3.1
    Image ID:
    Port:          9100/TCP
    Host Port:     9100/TCP
    Args:
      --path.procfs=/host/proc
      --path.sysfs=/host/sys
      --path.rootfs=/host/root
      --web.listen-address=$(HOST_IP):9100
      --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
      --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    State:          Waiting
      Reason:       CreateContainerError
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HOST_IP:  0.0.0.0
    Mounts:
      /host/proc from proc (ro)
      /host/root from root (ro)
      /host/sys from sys (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:
  root:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:
QoS Class:         BestEffort
Node-Selectors:    <none>
Tolerations:       :NoSchedule op=Exists
                   node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                   node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                   node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                   node.kubernetes.io/not-ready:NoExecute op=Exists
                   node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                   node.kubernetes.io/unreachable:NoExecute op=Exists
                   node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason  Age                   From     Message
  ----    ------  ----                  ----     -------
  Normal  Pulled  73s (x5103 over 18h)  kubelet  Container image "quay.io/prometheus/node-exporter:v1.3.1" already present on machine

**Comment by alexdresko** [comment]
I have the exact same problem. 

My hunch is that it has something to do with the readiness and/or liveness probes. 

```
    Liveness:       http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9100/ delay=0s timeout=1s period=10s #success=1 #failure=3
```

I'd like to get this fixed, but honestly, I'm not surprised I'm having trouble with the node exporter. Mine is a k3d cluster running inside a Docker container (VSCode "remote container development"), so it's not exactly a standard "node".
