### ISSUE TITLE
[prometheus-kube-stack] Please update grafana version in chart.lock file

### ISSUE THREAD

**Issue by Keramblock** [prometheus-community/helm-charts#1818]
### Describe the bug a clear and concise description of what the bug is.

There is a bug in current version: https://github.com/grafana/grafana/issues/44608
That would be cool, if we will get newer version to fix it.

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3-gke.700", GitCommit:"e21de5d6cf1b351bc99285c3c762098b8617b773", GitTreeState:"clean", BuildDate:"2021-11-05T09:25:32Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

32.2.1

### Enter the command that you execute and failing/misfunctioning.

---

**Comment by monotek** [comment]
pull request welcome ;-)

**Comment by Keramblock** [comment]
already done
