### ISSUE TITLE
k8s.gcr.io/ingress-nginx/kube-webhook-certgen - prometheus-operator - old webhook image v1.0

### ISSUE THREAD

**Issue by stefanjavor** [prometheus-community/helm-charts#1820]
### Describe the bug a clear and concise description of what the bug is.

Hi All,
in the Helm chart version 32.2.1 prometheus-kube-stack.values.yaml file, in row 1453 is pointing to the old webhook image version v1.0 what should be updated to min. v1.5.2 because k8s.io/api/admissionregistration/v1beta1 is deprecated since Kubernetes 1.16+ and will be removed in 1.22+. 
Helm chart should be updated to use new API types. 

Thank you very much for your great work!

### What's your helm version?

Version 3

### What's your kubectl version?

1.21.7

### Which chart?

prometheus-kube-stack

### What's the chart version?

32.2.1

## rules from making their way into prometheus and potentially preventing the container from starting
  admissionWebhooks:
    failurePolicy: Fail
    enabled: true
    ## A PEM encoded CA bundle which will be used to validate the webhook's server certificate.
    ## If unspecified, system trust roots on the apiserver are used.
    caBundle: ""
    ## If enabled, generate a self-signed certificate, then patch the webhook configurations with the generated data.
    ## On chart upgrades (or if the secret exists) the cert will not be re-generated. You can use this to provide your own
    ## certs ahead of time if you wish.
    ##
    patch:
      enabled: true
      image:
        repository: k8s.gcr.io/ingress-nginx/kube-webhook-certgen
        tag: v1.0
        sha: "f3b6b39a6062328c095337b4cadcefd1612348fdd5190b1dcbcb9b9e90bd8068"
        pullPolicy: IfNotPresent

### What you expected to happen?

It will not work because API deprecated since Kubernetes 1.16+ and will be removed in 1.22+. 
We have a lot of Kubernetes installation with 1.22 there are many new release. 

### How to reproduce it?

Install Kubernetes 1.22 and use Helm chart 32.2.1 kube.prometheus-stack 

### Enter the changed values of values.yaml?

image:
        repository: k8s.gcr.io/ingress-nginx/kube-webhook-certgen
        tag: v1.5.2
        sha: ""

### Enter the command that you execute and failing/misfunctioning.

proactive change

### Anything else we need to know?

update the documentation/ support matrix

**Comment by monotek** [comment]
Pull request welcome ;-)

**Comment by frittenlab** [comment]
@stefanjavor were did you find the image tag v1.5.2. I checked the repo and I can only find these tags :

` curl -k -s -X GET https://k8s.gcr.io/v2/ingress-nginx/kube-webhook-certgen/tags/list | jq -r '.tags[]'`

`v1.0
v1.1
v1.1.1`

**Comment by stefanjavor** [comment]
Thank you very much for the reply frittenlab,

yes, i am aware of this version - i was checking this one https://hub.docker.com/r/jettech/kube-webhook-certgen/tags
because it looks for me there is an update required - or?

**Comment by SippieCup** [comment]
I found someone who had already made the fixes required in kube-webhook-certgen, but did not upload it to docker hub or anything.

I forked it, made it available on docker hub, and was able to put that into my helm chart to get it working.

Seeing how I am probably not trustworthy, someone should probably upstream these changes to jettech and have them release a new build. But I have a lot to do and trust myself.

Then i overrode the defaults to my new dockerhub repo with the needed changes. Now everything works without much issue for me.
```
  admissionWebhooks:
    patch:
      image:
        repository: sippiecup/kube-webhook-certgen
        tag: v1.6.0
        sha: 78a28148365a2b602ac4c38d9b9ca920046d236c9bad67fe3ae7800acb921e02
```

Hopefully this information can help you guys as well.

**Comment by tspearconquest** [comment]
Please don't close this

**Comment by DerRockWolf** [comment]
The original image has been forked to [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/images/kube-webhook-certgen). But there sadly isn't a changelog.

**Comment by ttasharski73** [comment]
@SippieCup do you know which repo the changes originated from?

**Comment by SippieCup** [comment]
@ttasharski73 

Sorry for the late response, was on vacation.

Original developer / commit is here: https://github.com/oam-dev/kube-webhook-certgen/commit/1bb397822df2ccaef1e38909b5c8fdc9e8de2c91

**Comment by tspearconquest** [comment]
Please don't close this.
