### ISSUE TITLE
[kube-state-metrics] Autosharding fails unless statefulsets is enabled as a collector

### ISSUE THREAD

**Issue by jmmk** [prometheus-community/helm-charts#1825]
### Description

When autosharding is enabled, a `Role` and `RoleBinding` are created that are meant to give the kube-state-metrics pods read access (`get`, `list`, `watch`) to the kube-state-metrics `StatefulSet`.  However, unless `statefulsets` is enabled as a collector, the permissions are not granted and sharding fails.

With this configuration:

```yml
# values.yml
autosharding:
  enabled: true

replicas: 3

collectors:
  - deployments
  - pods
  # - statefulsets
```

The logs contained errors like:
> 2022-02-24 12:28:13 | W0224 18:28:13.619659       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:\<namespace\>:\<release name\>" cannot list resource "statefulsets" in API group "apps" in the namespace "\<namespace\>"

I can see that the `Role` and `RoleBinding` were properly created, and they seem to be written correctly, i.e. granting the proper permissions to the kube-state-metrics service account. I'm not sure where the failure is.

### Which chart?
kube-state-metrics

### What's the chart version?
4.5.0

### Workaround

Adding `statefulsets` as a collector adds sufficient permissions to the `ClusterRole` to allow the pods to query the `StatefulSet` and perform the sharding.

**Comment by dotdc** [comment]
Hi @jmmk :wave: 
The default behavior of the chart is to have all the collectors enabled.
As I see it, the only thing we could do is to add a comment explaining the dependency for autosharding.
Is that ok for you?

**Comment by jmmk** [comment]
From what I can tell, `stsdiscovery-role.yaml` and `stsdiscovery-rolebinding.yaml` are meant to handle the permissions for autobinding to work (i.e. discover the other members of the kube-state-metrics StatefulSet), regardless of what collectors are enabled. This part is what seems to be broken.

Saying that the statefulset collector must be enabled to allow autobinding is a potential solution, but it is not how the Chart is currently designed.
