### ISSUE TITLE
[prometheus-kube-stack] turning off admissionWebhooks breaks install

### ISSUE THREAD

**Issue by Morriz** [prometheus-community/helm-charts#1840]
### Describe the bug a clear and concise description of what the bug is.

When installing the chart with `prometheusOperator.admissionWebhooks.enabled: false` the deployment can't find it's referenced secret `{{ .Release.Name }}-admission`, because it is not created.

The following logic is incongruent:

templates/prometheus-operator/job-createSecret.yaml[L0]:
```yaml
{{- if and .Values.prometheusOperator.enabled .Values.prometheusOperator.admissionWebhooks.enabled .Values.prometheusOperator.admissionWebhooks.patch.enabled (not .Values.prometheusOperator.admissionWebhooks.certManager.enabled) }}
```

templates/prometheus-operator/deployment.yaml[L116]:
```yaml
{{- if .Values.prometheusOperator.tls.enabled }}
```

### What's your helm version?

version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

### What's your kubectl version?

1.21

### Which chart?

prometheus-kube-stack

### What's the chart version?

33.1.0

### Enter the command that you execute and failing/misfunctioning.

helm install my-release prometheus-community/prometheus-kube-stack --set 'prometheusOperator.admissionWebhooks.enabled=false"

**Comment by Morriz** [comment]
...

**Comment by ninjaslothx** [comment]
Just ran into this same issue. 
The only work around currently looks to be to disable tls for the operator component as well.

**Comment by Morriz** [comment]
Bump

**Comment by antokarev** [comment]
+1

experiencing the same issue
