### ISSUE TITLE
[prometheus-postgres-exporter] Support custom DB connection parameters for DATA_SOURCE_URI

### ISSUE THREAD

**Issue by atsu85** [prometheus-community/helm-charts#1845]
### Is your feature request related to a problem ?

I'd like to add custom DB connection parameters, for example `application_name` and likely some other related to timeouts.

### Describe the solution you'd like.

Currently value for `DATA_SOURCE_URI` is created on 
[this line](https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/prometheus-postgres-exporter/templates/_helpers.tpl#L51)
, that only allows customizing `sslmode` via `.Values.config.datasource.sslmode`. 

I'm proposing indroducing new datasource configuration parameter, for example `.Values.config.datasource.extraParams` with empty default value (for backward compatibility). If custom parameters are desired by some users, they would override `.Values.config.datasource.extraParams` with for example `&application_name=my-app` or `&application_name=my-app&some_other_param=some_other_value` 

### Describe alternatives you've considered.

Enlisting all possible datasource configuration parameters (like currently done for
[sslmode](https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/prometheus-postgres-exporter/templates/_helpers.tpl#L51)
would be too much work (and possibly later maintenance overhead).

**Comment by atsu85** [comment]
@gianrubio, @zanhsieh, i'm tagging you, as [you seem to be the maintainers](https://github.com/prometheus-community/helm-charts/issues/1656) of prometheus-postgres-exporter :)

**Comment by zanhsieh** [comment]
@atsu85 
Why don't you just PR it ^^^  and let's review the outcome?

**Comment by atsu85** [comment]
@zanhsieh, created [the PR](https://github.com/prometheus-community/helm-charts/pull/1850) as you proposed
