### ISSUE TITLE
chain variables in grafana dashboard for postgres and prometheus datasource

### ISSUE THREAD

**Issue by Bharath4297** [prometheus-community/helm-charts#1848]
### Describe the bug a clear and concise description of what the bug is.

not getting exactly when I am using all option in filtering the team variable

### What's your helm version?

no helm

### What's your kubectl version?

no kube

### Which chart?

n/a

### What's the chart version?

n/a

### What happened?

Hello @torkelo

I am using prometheus and postgres as data sources.
In postgres I am using IP, Team, Owner, and Os as attributes.
I am scraping node exporter metrics through prometheus. I want to filter through teams. like If I select one team I have to get owner, ip address and node exporter metrics too.. similarly If I select all option in team variable I have to get all teams details and each teams have to display owner ip and node exporter metrics. But I am facing issue with all option

Owner and IP are dependent on team. I declared variables as follows:

team: select team from server;
owner: select owner from server where team=$team;
ip: select ip from server where team=$team;

below pics are the data which I am getting. could you please help me? if I select all option I am getting only postgres data I am not getting prometheus data.
![Screenshot (138)](https://user-images.githubusercontent.com/94895356/156791381-252dc479-50cc-426e-b9d2-9d3c309845ee.png)
![Screenshot (139)](https://user-images.githubusercontent.com/94895356/156791407-89fff245-2545-4c43-b52e-766d67221bfd.png)
![Screenshot (142)](https://user-images.githubusercontent.com/94895356/156791412-a79c302c-16af-46d6-8874-e241111a08bf.png)
![Screenshot (143)](https://user-images.githubusercontent.com/94895356/156791415-e518ccbb-d72e-4632-b729-a145fa2fb3fa.png)
![Screenshot (144)](https://user-images.githubusercontent.com/94895356/156791419-871ecdd8-7de6-412d-9973-8bf9f2957b61.png)
![Screenshot (145)](https://user-images.githubusercontent.com/94895356/156791425-d19b27b6-639b-4cda-a1e1-6f83d75d12d8.png)
![Screenshot (146)](https://user-images.githubusercontent.com/94895356/156791427-bf9e18dd-da5d-4083-a9f6-f596fbdc2941.png)

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by torkelo** [comment]
the owner variable looks to be unused. 

When you change the team variable, what network requests are made? can you open chrome dev tools?

**Comment by Bharath4297** [comment]
@torkelo I am using owner variable.. if I change team variable it should select respective owner name and ip details. shall I need to do anything in chrome dev tools?

**Comment by torkelo** [comment]
I don't see owner variable being used anywhere. Chrome dev tools network tab, clear all existing network traces, then change the team option from a single value to All, inspect all network requests (and include some details here).

See an example here, when I change the tag variable to All I see a request for the postgres variable query `select * from asd where in($tag)` , and it triggered with the right All interpolation. 
![Screenshot from 2022-03-07 09-46-14](https://user-images.githubusercontent.com/10999/156997760-a1f841b9-d918-433c-bcca-3a8f4c36ffb0.png)

**Comment by Bharath4297** [comment]
@torkelo Ok sir.... got it... but what to do to make use of owner variable. am I declaring anything wrong?

**Comment by torkelo** [comment]
@Bharath4297 just that I cannot see it used in a query anywhere

**Comment by Bharath4297** [comment]
@torkelo can we mix two different datasources variables in a query? Actually owner is avariable from postgres datasource.

**Comment by torkelo** [comment]
@Bharath4297 why have you added it if it's not used anywhere?
