### ISSUE TITLE
[prometheus-alertmanager] Add sidecarContainers support

### ISSUE THREAD

**Issue by nic-chen** [prometheus-community/helm-charts#1849]
### Is your feature request related to a problem ?

The main Prometheus chart allows sidecar containers to be injected into the server but not into Alertmanager. 
If you want to generate alert configurations both for Prometheus and Alertmanager, you also need a sidecar container to do the generating.

### Describe the solution you'd like.

I'd like to get the Alertmanager chart (and its copy in Prometheus to also have a sidecar container option, just like the main server portion of the Prometheus chart.

### Describe alternatives you've considered.

The only alternative I can think of is to fork a prometheus-alertmanager chart and own it myself.

**Comment by nic-chen** [comment]
hi

**Comment by CrazyTushkan** [comment]
bump

**Comment by nic-chen** [comment]
up
