### ISSUE TITLE
Default Passwords

### ISSUE THREAD

**Issue by gurdeepsira** [prometheus-community/helm-charts#185]
Hi,
I have install kube-prometheus-stack via Helm. However, what are the passwords? The username password admin admin for Grafana doesn't work, for example.

**Comment by monotek** [comment]
A look into the values file should help ;-)

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L513

**Comment by usersina** [comment]
> A look into the values file should help ;-)
> 
> https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L513

The line can change. Future readers simply search for `adminPassword`
