### ISSUE TITLE
[kube-prometheus-stack] grafana and kube-state-metrics cannot change nodeSelector/affinity/tolerations.

### ISSUE THREAD

**Issue by chattytak** [prometheus-community/helm-charts#1853]
### Is your feature request related to a problem ?

Except for grafana and kube-state-metrics, you can change nodeSelector/affinity/tolerations, but only these two cannot change those parameters.

### Describe the solution you'd like.

Allow grafana and kube-state-metrics to change their parameters as well.

### Describe alternatives you've considered.

Patching with a regular manifest file.
But that would eliminate the advantages of helm.

**Comment by hydeenoble** [comment]
Hello @chattytak, I probably don't totally understand the issue you created but I see how to configure the nodeSelector/affinity/tolerations for `kube-state-metrics` here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml#L111-L119

**Comment by dotdc** [comment]
Hi @chattytak, 
I don't really understand the issue.
Could you please re-explain and maybe share more context.
Thanks

**Comment by chattytak** [comment]
Hello @hydeenoble @dotdc 
My problem is with `kube-prometheus-stack`, not `kube-state-metrics`.

[https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)

There are places in this chart where more than one `tolerations` can be set, but `grafana` and `kube-state-metrics` do not have such a setting.
[grafana](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L645)
[kube-state-metrics](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1336)

Could it be that these are just not in the Default Value display, but actually work if set?

**Comment by dotdc** [comment]
Hi @chattytak,

Thank you for clarifying, if think I got it this time :smiley: 
Of course you can use any values from the sub-charts even if they are not in the `kube-prometheus-stack` default values.

In your `kube-prometheus-stack` values you can set:

```
kube-state-metrics:
  nodeSelector: {}
  affinity: {}
  tolerations: []
grafana:
  nodeSelector: {}
  affinity: {}
  tolerations: []
```

like describe in the subcharts values:
- grafana: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L234-L237
- kube-state-metrics: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml#L111-L119

Let me know if this solves your problem.

**Comment by chattytak** [comment]
To be honest, I had not seen the chart structure of this and did not think it was running on the concept of subcharts.
I understood that each one was a subchart and that it was calling them.
I configured the subcharts as you showed me, also referring to the values.yaml for the subcharts, and was able to configure the settings for grafana and kube-state-metrics as well. Thanks.
