### ISSUE TITLE
[prometheus] Installation example

### ISSUE THREAD

**Issue by erikmartino** [prometheus-community/helm-charts#1854]
### Is your feature request related to a problem ?

Following your installation example in https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus then prometheus is installed in the default namespace. That is unfortunate.

### Describe the solution you'd like.

Could you do a more "best practice" / TL;DR installation example.

### Describe alternatives you've considered.

Let the helm chart be opinionated.

**Comment by achede22** [comment]
un the values file, set:

## Override the deployment namespace
##
namespaceOverride: "my-namespace"
