### ISSUE TITLE
[kube-prometheus-stack] Setting grafana.adminPassword from existing Secret

### ISSUE THREAD

**Issue by brsolomon-deloitte** [prometheus-community/helm-charts#1860]
### Is your feature request related to a problem ?

kube-prometheus-stack does not (seem to) allow any way to configure `grafana.adminPassword` from a Kubernetes `Secret`. I must either accept the default (not secure), change it afterwards (not idiomatic for configuration as code), or pass it a custom string (doesn't work to store in Git).

### Describe the solution you'd like.

Expose `grafana.existingSecret` parameter as is done in many other charts such as https://github.com/bitnami/charts/tree/master/bitnami/influxdb.

### Describe alternatives you've considered.

None.

**Comment by brsolomon-deloitte** [comment]
It looks like https://artifacthub.io/packages/helm/grafana/grafana exposes `admin.existingSecret` so it would be nice to be able to pass this through.

**Comment by zeritti** [comment]
That should already be possible as we have been using the dict since version 21.0.0, e.g.:
```
grafana:
  admin:
    existingSecret: "secret-name"
    userKey: admin-user
    passwordKey: admin-password
```
Any value supported by the grafana chart at the given version can be entered for the `grafana` subchart.

**Comment by brsolomon-deloitte** [comment]
> Any value supported by the grafana chart at the given version can be entered for the `grafana` subchart.

Thanks @zeritti, that did the trick. I am continually reminded of how terrible my Helm knowledge actually is :)

**Comment by gangstead** [comment]
Additional note: if you change that `existingSecret` values Grafana will not update the admin credentials.  Your side cars will try to use the new values from the secret and will get denied since the admin user was never updated.

I don't know if this is a problem in the chart, in Grafana, or just "works as designed."
