### ISSUE TITLE
[kube-prometheus-stack] grafana's metrics are not collected by default

### ISSUE THREAD

**Issue by branden** [prometheus-community/helm-charts#1867]
### Describe the bug a clear and concise description of what the bug is.

Deploying kube-prometheus-stack with the default chart values results in Grafana's metrics not being collected. Its ServiceMonitor is created, but it's missing the `release` label that the default Prometheus `serviceMonitorSelector` is matching against, so prometheus-operator ignores it.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

33.2.0

### What happened?

There was no scrape target for Grafana in the Prometheus UI, and none of its metrics could be queried.

### What you expected to happen?

I expected that Prometheus would have a scrape target for Grafana and that its metrics could be queried.

### How to reproduce it?

Deploy kube-prometheus-stack with the default chart values, browse to the Prometheus targets page, and observe that there is no target for Grafana.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack

**Comment by barzog** [comment]
It seems that as of 39.12.1 this one still not fixed. After setting in helm values:
grafana:
  service:
    labels:
      release: 'kube-prometheus-stack'
  serviceMonitor:
    labels:
      release: kube-prometheus-stack

All is working as intended
