### ISSUE TITLE
[prometheus] When using prometheus in statefulset, the service isn't working due to selector error

### ISSUE THREAD

**Issue by axelczk** [prometheus-community/helm-charts#1868]
### Describe the bug a clear and concise description of what the bug is.

Hello,

Recently, in our deployment using prometheus in statefulset we encountered an error with the ingress not working. The target group was empty and it was impossible to access prometheus through the ingress.

After some research, we found the cause of the error inside the service.yml file here:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/server/service.yaml

Here is the part of the chart that doesn't work:
`
 selector:
  {{- if and .Values.server.statefulSet.enabled .Values.server.service.statefulsetReplica.enabled }}
    statefulset.kubernetes.io/pod-name: {{ template "prometheus.server.fullname" . }}-{{ .Values.server.service.statefulsetReplica.replica }}
`

For example, if we have a replica of 2, we will have two pod: prometheus-0 and prometheus-1. Whereas, the service will have the  following selector: statefulset.kubernetes.io/pod-name: prometheus-2. 

With this, no pod can be targeted, thus the service doesn't work as expected and therefore the ingress. 

In order to fix this, we can delete the condition for the statefulset and use the same behavior than non stateful. 

`
{{- include "prometheus.server.matchLabels" . | nindent 4 }}
`

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.5.3

### What happened?

Ingress not working due to error in service configuration

### What you expected to happen?

Ingress working

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install test prometheus-community/prometheus --version 15.5.3 --values values.yaml

**Comment by axelczk** [comment]
Any help from the prometheus team ?

**Comment by zanhsieh** [comment]
@axelczk 
Why don't you PR this?

**Comment by maleksan** [comment]
In my case the root cause of this issue with StatefulSet and Service was in Liveness/Readiness probes fails, cause that I have configured [Basic authentication ](https://prometheus.io/docs/guides/basic-auth/) and in StatefulSet helm manifest is missing `Values.server.probeHeaders` parameter, which is in Deployment helm manifest. So, after manual adding this parameter in manifests,  Liveness/Readiness probes are now ok and  StatefulSet and Service are working as expected.
