### ISSUE TITLE
[prometheus-adapter] Unable to instantiate multiple copies of chart

### ISSUE THREAD

**Issue by xrl** [prometheus-community/helm-charts#1869]
### Describe the bug a clear and concise description of what the bug is.

The name of the apiservice is hardcoded to `v1beta1.custom.metrics.k8s.io` and we have multiple prometheus clusters in our kube cluster but the first prometheus-adapter chart installed has taken this coveted name. We are unable to add more prom adapters using our many self-hosted prom clusters.

We should make the APIService name customizeable.

### What's your helm version?

v3.8.0

### What's your kubectl version?

v1.22.5

### Which chart?

prometheus-adapter

### What's the chart version?

3.0.2

### What happened?

helm upgrade --install prometheus-adapter prometheus-community/prometheus-adapter -f prometheus-adapter.yaml
Release "prometheus-adapter" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: APIService "v1beta1.custom.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "prometheus-adapter": current value is "rancher-monitoring"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "maas-default": current value is "cattle-monitoring-system"
make: *** [ents-eu-dev] Error 1

### What you expected to happen?

It should have installed a prom adapter in my namespace

### How to reproduce it?

Run multiple prom-adapters, pointed at different prom clusters, and you will see you can only stand up one prom adapter

### Enter the changed values of values.yaml?

fullnameOverride: maas-prom-adapter

rbac:
  create: false

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-adapter prometheus-community/prometheus-adapter -f prometheus-adapter.yaml

**Comment by sepaper** [comment]
Do you think providing an option to deploy resources except the APIService(v1beta1.custom.metrics.k8s.io) could be a solution in your case?

**Comment by vvs82** [comment]
The issue is still presented:
`Unable to continue with install: APIService "v1beta1.custom.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release...`
Any solution for this moment?
