### ISSUE TITLE
[prometheus-cloudwatch-exporter] Ingress doesn't have option to use networking.k8s.io/v1

### ISSUE THREAD

**Issue by rendhalver** [prometheus-community/helm-charts#1882]
### Describe the bug a clear and concise description of what the bug is.

prometheus-cloudwatch-exporter doesn't have option to use networking.k8s.io/v1 for Ingress.
This make it incompatible with kubernetes 1.22 and above

### What's your helm version?

3.6.3

### What's your kubectl version?

1.21

### Which chart?

prometheus-community/prometheus-cloudwatch-exporter

### What's the chart version?

0.18.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-community/prometheus-cloudwatch-exporter

**Comment by Spacebjorn** [comment]
Same thing is happening for the prometheus-snmp-exporter. I can make another issue if required

**Comment by monotek** [comment]
please create pr instead of issue.
