### ISSUE TITLE
[prometheus-node-exporter] Prometheus node exporter support tls config

### ISSUE THREAD

**Issue by Tianhao-intel** [prometheus-community/helm-charts#1883]
### Is your feature request related to a problem ?

I'd like to add TLS config for Prometheus node exporter. But even if I add TLS config in node exporter chart and add "scheme: HTTPS" config for liveness and readiness probe. The liveness and readiness check still failed. The error in pod is "Readiness probe failed: Get "https://127.0.0.1:9100/": remote error: tls: bad certificate"

### Describe the solution you'd like.

Prometheus node exporter should support TLS config either in values.yaml or pass the https check if liveness and readiness probe scheme is HTTPS

### Describe alternatives you've considered.

NONE

**Comment by kartikiyyer** [comment]
Any update? We are also facing this issue?

**Comment by kiyyer1** [comment]
Any update on this? how to reopen this issue? We are also facing this issue.

**Comment by refucktor** [comment]
has anybody managed to solve this issue?
