### ISSUE TITLE
[kube-prometheus-stack] Enable Multi-Cluster Alerting / Recording Rules

### ISSUE THREAD

**Issue by sherifkayad** [prometheus-community/helm-charts#1886]
### Is your feature request related to a problem ?

Well, we are at the moment trying to setup Thanos Receiver and Thanos Ruler, however, the Prometheus rules in the Helm Chart don't reflect the external labels we do have e.g. `cluster` and `region`.

Similar to the multicluster support in the dashboards, that would also be great to have a multi-cluster view in the Prometheus Alert and Recording Rules.

### Describe the solution you'd like.

some property that controls if multi-cluster alerts should be available and if so, then which labels should be used. In that case the alerts / rules configured should e.g. use BY(*, multicluster_label1, multicluster_label1, ..)

### Describe alternatives you've considered.

Nothing yet except from using multiple alert managers in the different clusters and local rule evaluation by Prometheus.

**Comment by sherifkayad** [comment]
Keep alive

**Comment by kishoreinvits** [comment]
Addressed by #2993
