### ISSUE TITLE
[prometheus-kube-stack] Error update helm with RBAC

### ISSUE THREAD

**Issue by olahouze** [prometheus-community/helm-charts#1889]
### Describe the bug a clear and concise description of what the bug is.

After deploying for the first time the **kube-prometheus-stack** chart, when I want to update it by performing a diff (helm diff upgrade) I get error message

### What's your helm version?

version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.15-eks-9c63c4", GitCommit:"9c63c4037a56f9cad887ee76d55142abd4155179", GitTreeState:"clean", BuildDate:"2021-10-20T00:21:03Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

13.7.2

### What happened?

After deploying for the first time the kube-prometheus-stack chart, when I want to update it by performing a diff (helm diff upgrade) I get the following error message:

```
Error: template: XXX-prometheus/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount. yaml:1:130: executing "XXX-prometheus/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml" at <.Values.global.rbac.create>: nil pointer evaluating interface {}.rbac
```

To solve this problem, I need to override in my Values.yaml file the value already present in the file: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

I have to add 
```
  global:
    rbac:
      create: true
```

By passing this values file to the HELM chart I don't have any more problem (while it is the same value as the default one in the Value.yaml file of the chart...)

### What you expected to happen?

No need to add these values in my values.yaml

### How to reproduce it?

1. Make a chart that uses the **kube-prometheus-stack** as chart dependency
2. Make a clean installation without adding the RBAC values in the values.yaml of the chart
3. Update this chart without adding the above mentioned values

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm diff upgrade HELM_NAME . --namespace $HELM_NAMESPACE --kubeconfig KUBECONFIG

**Comment by yardenws** [comment]
Used this in parallel with using ServerSideApply=true which fixes the long CRD names issue and it helped:

ignoreDifferences:
  - group: monitoring.coreos.com
    kind: Prometheus
    jqPathExpressions:
    - .spec.remoteWrite[]?.writeRelabelConfigs[]?.action
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: apps
    kind: Deployment
    name: kube-prometheus-stack-kube-state-metrics
    namespace: monitoring
    jqPathExpressions:
      - '.spec.template.spec.containers[]?.resources'
  - group: apps
    kind: DaemonSet
    name: kube-prometheus-stack-prometheus-node-exporter
    namespace: monitoring
    jqPathExpressions:
      - '.spec.template.spec.containers[]?.resources'
