### ISSUE TITLE
[kube-prometheus-stack] Collection of metrics with authorization.

### ISSUE THREAD

**Issue by rickyticky2** [prometheus-community/helm-charts#1890]
### Is your feature request related to a problem ?

I can not find how to set up the collection of metrics with authorization (basic_auth).

### Describe the solution you'd like.

In the helm chart I found a collection of metrics with authorization through a token - bearerTokenFile. But my task is to collect metrics with authorization - login / password. maybe I didn't find how to set it up. I will be glad for any help

### Describe alternatives you've considered.

NONE

**Comment by zeritti** [comment]
As per prometheus-operator API, `basicAuth`, i.e. user name and password, is supported in a few resources, including `serviceMonitor.spec.endpoints.basicAuth` which is of interest to you. Please, see the [Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#endpoint) spec. 
Using the `kubectl explain servicemonitor.spec.endpoints.basicAuth` command will give you the same description assuming the CRDs are present.

**Comment by rickyticky2** [comment]
@zeritti  this does not work for me .. 
![image](https://user-images.githubusercontent.com/79316032/160163140-b658fbbd-d8dd-4ff2-8e0a-391f8dea2196.png)
![image](https://user-images.githubusercontent.com/79316032/160163268-f93f88f2-2030-4e18-8c2c-582a6e0d0bac.png)
secret is created

**Comment by rickyticky2** [comment]
syntax error )
