### ISSUE TITLE
[kube-prometheus-stack] How to configure Prometheus CDR to pickup all ServiceMonitors located in the same namespace ?

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1911]
### Is your feature request related to a problem ?

This is a question b/c maybe the feature already exists which I don't know how to use properly.

Let's assume the `kube-prometheus-stack` is installed in the Kubernetes namespace `monitoring`. In that namespace, I have a certain number of `ServiceMonitor`:

- "core" ServiceMonitor created by `kube-prometheus-stack`: alertmanager, grafana, prometheus, node-exportet, operator, etc)
- additional ServiceMonitor enabled by default, aslo created by `kube-prometheus-stack`: apiserver, coredns, kube-controller-manager, kube-proxy, kubelet, kube-state-metrics, etc.
- optional ServiceMonitor aslo created by `kube-prometheus-stack`, which we enable in helm values: thanos-bucketweb, thanos-compactor, thanos-query, thanos-storegateway, etc.)
- **My own ServiceMonitors** 

Currently I configure the helm value for `kube-prometheus-stack` version 34.1.1 as

```
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchExpressions:
      - key: "release"
        operator: In
        values:
          - myown-svcmon-label
          - my-kubepromstack-helmrelease-name
```

The problem with the above config is that every ServiceMonitor must have a label with a key `release`. This is not always practical or possible to add that `release` label in every ServiceMonitor, for example those from Thanos don't have that `release` label.
 

### Describe the solution you'd like.

Is there a way to tell Prometheus to pickup any ServiceMonitor which are installed in the same namespace than the Prometheus Operator? In the above example this would be all ServiceMonitor in the `monitoring` namespace.

If there is such a solution, this would fix nicely the issue https://github.com/prometheus-community/helm-charts/issues/1905  as well.

### Describe alternatives you've considered.

So far, must find a way so that ALL ServiceMonitor must have a common label. This is not a sustainable solution because there are many ServiceMonitors where I can't have control.

**Comment by konstantinwirz** [comment]
you need to set **serviceMonitorSelectorNilUsesHelmValues** to false

see https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2282

**Comment by tringuyen-yw** [comment]
@konstantinwirz  Thanks, I have of course read the comments about `serviceMonitorSelectorNilUsesHelmValues` But the use-case for `false` is not documented. Let me try this and will confirm.

**Comment by tringuyen-yw** [comment]
@konstantinwirz confirmed working, with `prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues: false` 
all ServiceMonitors in the same namespace as the Prometheus CRD are now selected regardless of their labels. Such a simple solution, thanks very much. I will make a pull request to add a comment in the 
[kube-prometheus-stack/values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2282) for the benefit of future users.

**Comment by missourian55** [comment]
@tringuyen-yw  Thank you. It has been a painful couple of hours trying to determine why my service monitor was not chosen for scraping by Prometheus.  I am not sure why this is not a *sane default*?

**Comment by sachasmart** [comment]
Just ran into this as well, confirming `serviceMonitorSelectorNilUsesHelmValues` -> false solved the issue. I looked at this originally when I was debugging but moved on as the I didn't believe the description fit what the issue was.. I think a better comment description would be useful for others.

**Comment by alecgerona** [comment]
+1 on updating the comment in values.yaml for this. Also had me scratching my head.

**Comment by PaulRudin** [comment]
Just to be clear: with:
```
prometheusSpec:
   serviceMonitorSelectorNilUseHelmValues: true
   serviceMonitorSelector: {}
   serviceMonitorNamespaceSelector: {}
```
all serviceMonitors in all namespaces should be included?

**Comment by orarbel** [comment]
> Just to be clear: with:
> 
> ```
> prometheusSpec:
>    serviceMonitorSelectorNilUseHelmValues: true
>    serviceMonitorSelector: {}
>    serviceMonitorNamespaceSelector: {}
> ```
> 
> all serviceMonitors in all namespaces should be included?

`serviceMonitorSelectorNilUsesHelmValues` rather than `serviceMonitorSelectorNilUseHelmValues`
