### ISSUE TITLE
[kube-prometheus-stack] missing thanos sidecar secrets in values.yaml

### ISSUE THREAD

**Issue by hernan-cision** [prometheus-community/helm-charts#1912]
### Describe the bug a clear and concise description of what the bug is.

There is NO WAY to add a k8s Secret to the thanos sidecar container from[ kube-prometheus-stack values file](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)

But a mounted secret is needed to connect to the cloud trough [objectStorageConfigFile](https://github.com/prometheus-community/helm-charts/blob/6fd81bdd99967dafd72fa18be5daff8ec72d6d44/charts/kube-prometheus-stack/values.yaml#L2570) value

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6-gke.300", GitCommit:"df413ee6225aa3fc539e18ca3464a48d723bd3ea", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:08Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

latest

### What happened?

There is NO WAY to add a k8s Secret to the thanos sidecar container from[ kube-prometheus-stack values file](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)

I modified the values file, 
uncommented [objectStorageConfigFile:](https://github.com/prometheus-community/helm-charts/blob/6fd81bdd99967dafd72fa18be5daff8ec72d6d44/charts/kube-prometheus-stack/values.yaml#L2570) /etc/prometheus/secrets/thanos-storage-config
line 

The file will never be mounted inside the thanos sidecar
there is no way to add a secret into the thanos sidecar

### What you expected to happen?

as you can add a secret to the prometheus container, you should be able to add a secret into the thanos sidecar container

prometheus pod
prometheus container
secret
{{- if .Values.prometheus.prometheusSpec.secrets }}
  secrets:
{{ toYaml .Values.prometheus.prometheusSpec.secrets | indent 4 }}
{{- end }}

### How to reproduce it?

try to add a secret into the thanos sidecar only modifying the values file

try to connect to an AWS or CGP bucket

there is no way

### Enter the changed values of values.yaml?

objectStorageConfigFile

### Enter the command that you execute and failing/misfunctioning.

.

### Anything else we need to know?

.

**Comment by zeritti** [comment]
This prometheus-operator's documentation on [Thanos Object Storage](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/thanos.md#configuring-thanos-object-storage) may help.

**Comment by brunopadz** [comment]
I guess it'd be nice to add annotations to Thanos sidecar container, so features like IRSA could be used.

**Comment by mogaal** [comment]
@brunopadz Thanos sidecar run as a sidecar for Prometheus container. It means it uses the same `serviceAccount` and therefore if your SA has the right annotations for IRSA the Thanos sidecar will be able to upload the TSDB blocks without issues. I hope it helps
