### ISSUE TITLE
How is it a HELM chart without an index.yaml file??

### ISSUE THREAD

**Issue by achede22** [prometheus-community/helm-charts#1913]
### Describe the bug a clear and concise description of what the bug is.

How is this a HELM chart without an index.yaml file??

I forked the repo and tried to add my FORK as a helm repo

`helm repo add my-helm-chart-fork https://github.com/achede22/helm-charts`

`# Error: looks like "https://github.com/achede22/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/achede22/helm-charts/index.yaml : 404 Not Found`

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

all

### What's the chart version?

latest

### What happened?

ho way to add my public fork as a repo

```
helm repo add my-helm-chart-fork https://github.com/achede22/helm-charts
Error: looks like "https://github.com/achede22/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/achede22/helm-charts/index.yaml : 404 Not Found
```

I cloned it 
`git clone https://github.com/achede22/helm-charts.git`
but I can't add it as a local repo

### What you expected to happen?

I expect a index.yaml file so I can add my fork as a helm repo

As https://helm.sh/docs/topics/chart_repository/
It says:
"Note: A repository will not be added if it does not contain a valid index.yaml"

### How to reproduce it?

make a fork of this project

run
`helm repo add "your fork"`

Error: looks like "https://github.com/achede22/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/achede22/helm-charts/index.yaml : 404 Not Found

### Enter the changed values of values.yaml?

none

### Enter the command that you execute and failing/misfunctioning.

helm repo add my-helm-chart-fork https://github.com/achede22/helm-charts

### Anything else we need to know?

It's public

**Comment by zeritti** [comment]
A Helm chart does not include an `index.yaml`, a chart repository does. Please, refer to Helm documentation on [chart repository](https://helm.sh/docs/topics/chart_repository/).

**Comment by Markieta** [comment]
They are using [GitHub Actions](https://github.com/prometheus-community/helm-charts/blob/main/.github/workflows/release.yaml) with [helm/chart-releaser-action](https://github.com/helm/chart-releaser-action):

> This uses [@helm/chart-releaser-action](https://www.github.com/helm/chart-releaser-action) to turn your GitHub project into a self-hosted Helm chart repo. It does this – during every push to `main` – by checking each chart in your project, and whenever there's a new chart version, creates a corresponding [GitHub release](https://help.github.com/en/github/administering-a-repository/about-releases) named for the chart version, adds Helm chart artifacts to the release, and creates or updates an `index.yaml` file with metadata about those releases, which is then hosted on GitHub Pages. **You do not need an `index.yaml` file in `main` at all because it is managed in the `gh-pages` branch.**

[The index can be found on the `gh-pages` branch.](https://github.com/prometheus-community/helm-charts/tree/gh-pages)
