### ISSUE TITLE
prometheus-kube-stack

### ISSUE THREAD

**Issue by hd-sharma** [prometheus-community/helm-charts#1921]
### Describe the bug a clear and concise description of what the bug is.

Hi,

I am trying to deploy [prometheus-kube-stack] using below command to host Grafana service on aws application load balancer:

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.service.type=LoadBalancer --set grafana.persistence.enabled=true --set grafana.persistence.type=statefulset --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set global.rbac.pspEnabled=false --set grafana.rbac.pspEnabled=false --set kube-state-metrics.rbac.podSecurityPolicy.enabled=false --set prometheus-node-exporter.rbac.pspEnabled=false -n metrics

But this code deploys Grafana service over aws classic load balancer. 

### What's your helm version?

v3.4.1

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack-23.1.3

### What's the chart version?

0.52.0

### What happened?

Using this code Grafana service is getting hosted on aws classic load balancer.

### What you expected to happen?

Need to install Grafana service over application load balancer.

### How to reproduce it?

Install prometheus-kube-stack using below command 

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.service.type=LoadBalancer --set grafana.persistence.enabled=true --set grafana.persistence.type=statefulset --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set global.rbac.pspEnabled=false --set grafana.rbac.pspEnabled=false --set kube-state-metrics.rbac.podSecurityPolicy.enabled=false --set prometheus-node-exporter.rbac.pspEnabled=false -n metrics

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.service.type=LoadBalancer --set grafana.persistence.enabled=true --set grafana.persistence.type=statefulset --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set global.rbac.pspEnabled=false --set grafana.rbac.pspEnabled=false --set kube-state-metrics.rbac.podSecurityPolicy.enabled=false --set prometheus-node-exporter.rbac.pspEnabled=false -n metrics

**Comment by zeritti** [comment]
@hd-sharma By provisioning an ALB I meant deploying it via your usual IaC tools. i.e. terraform, cloudformation, etc., if it makes sense for your environment.

**Comment by aaroniscode** [comment]
Hi @hd-sharma 

AWS Classic Load Balancer will not be deprecated in Aug 2022. EC2-Classic Networking is being retired. But Classic Load Balancers in VPC will still be available.

**Comment by pavan-datazip** [comment]
Hey @zeritti @aaroniscode  A nlb is not being created even if I give the annotation to provide an nlb.

  set {
    name  = "grafana.service.type"
    value = "LoadBalancer"
    type  = "string"
  }

  set  {
    name      = "service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-type"
    value     = "nlb"
    type      = "string"
  }

This is how I have mentioned. Is there any mistake in it
