### ISSUE TITLE
failed: clusterroles.rbac.authorization.k8s.io "prometheus-kube-prometheus-admission" is forbidden: user 

### ISSUE THREAD

**Issue by ghost** [prometheus-community/helm-charts#1934]
### Describe the bug a clear and concise description of what the bug is.

When trying to install prometheus-community/kube-prometheus-stack getting: 
Error: INSTALLATION FAILED: failed pre-install: warning: Hook pre-install kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml failed: clusterroles.rbac.authorization.k8s.io "prometheus-kube-prometheus-admission" is forbidden: user "x" ("system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["admissionregistration.k8s.io"], Resources:["mutatingwebhookconfigurations"], Verbs:["update"]}

### What's your helm version?

3.7.2

### What's your kubectl version?

1.21.1

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

34.6.0

### What happened?

helm install prometheus prometheus-community/kube-prometheus-stack

Error: INSTALLATION FAILED: failed pre-install: warning: Hook pre-install kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml failed: clusterroles.rbac.authorization.k8s.io "prometheus-kube-prometheus-admission" is forbidden: user "x" ("system:authenticated" "system:cattle:authenticated"]) is attempting to grant RBAC permissions not currently held:
{APIGroups:["admissionregistration.k8s.io"], Resources:["mutatingwebhookconfigurations"], Verbs:["update"]}

### What you expected to happen?

succeded

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack

**Comment by zeritti** [comment]
The deployer's (your) privileges are not sufficient to create cluster role `prometheus-kube-prometheus-admission` with verb `update` on resource `mutatingwebhookconfigurations`. In other words, one cannot grant what one does not have. You'd need to extend your current cluster roles with that privilege or assume a more privileged account.
