### ISSUE TITLE
prometheus-kube-stack CPU Usage chart shows No Data

### ISSUE THREAD

**Issue by smacz42** [prometheus-community/helm-charts#1938]
### Describe the bug a clear and concise description of what the bug is.

![Screenshot from 2022-03-30 17-37-10](https://user-images.githubusercontent.com/10110994/160935297-669d17b1-09aa-4f10-baa6-812c0f100d97.png)

Despite showing the utilization percentage, the graph shows no data.

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

\>=30.0.1

### What happened?

When I went to browse through the dashboards, a lot of them were missing information.

Specifically, on "General / Kubernetes / Compute Resources / Cluster", the following graphs show "No data":

- CPU Usage
- Current Network Usage
- Bandwidth (all graphs)
- Average Container Bandwidth by Namespace (all graphs)
- Rate of Packets (all graphs)
- Rate of Packets Dropped (all graphs)
- Storage IO (all graphs)
- Storage IO - Distribution

This repeats on multiple other dashboards, which show the same behavior, where the Memory fields are reporting, but the CPU and storage fields seem to have reporting errors.

### What you expected to happen?

I expected all the graphs to have information.

### How to reproduce it?

1. Install Ubuntu 20.04
2. Install Docker latest
3. Install minikube latest
4. Install helm latest
5. Installed prometheus-kube-stack helm chart version 30.0.1
6. Expose grafana (`kubectl expose deployment kube-prometheus-stack-1648523012-grafana --type=NodePort --name=grafana`)
7. Find the service URL (`minikube service list`)
8. Login and view the dashboard "General / Kubernetes / Compute Resources / Cluster"
9. Observe that there is "No data" in the graph

### Enter the changed values of values.yaml?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by smacz42** [comment]
Another thing that's weird is that one of the default rules has a state of OK, but it's not returning anything. It is the first one in the `k8s.rules` section:

```
record:[node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate](http://192.168.49.2:32736/graph?g0.expr=node_namespace_pod_container%3Acontainer_cpu_usage_seconds_total%3Asum_irate&g0.tab=1&g0.stacked=0&g0.show_exemplars=0.g0.range_input=1h.)
expr:sum by(cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on(cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```

The odd thing is the next monitor works, that is checking the memory:

```
record:[node_namespace_pod_container:container_memory_working_set_bytes](http://192.168.49.2:32736/graph?g0.expr=node_namespace_pod_container%3Acontainer_memory_working_set_bytes&g0.tab=1&g0.stacked=0&g0.show_exemplars=0.g0.range_input=1h.)
expr:container_memory_working_set_bytes{image!="",job="kubelet",metrics_path="/metrics/cadvisor"} * on(namespace, pod) group_left(node) topk by(namespace, pod) (1, max by(namespace, pod, node) (kube_pod_info{node!=""}))
```

The only CPU monitor that seems to work is the following:

```
1 - sum(avg by (mode) (rate(node_cpu_seconds_total{job="node-exporter", mode=~"idle|iowait|steal", cluster="$cluster"}[$__rate_interval])))
```

**Comment by badyag** [comment]
Hello there, I observe the same behaviour in Minikube, but in a "real" cluster (tested in EKS) it works just fine, `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` rule shows data as expected and Grafana also displays the graphs well.

Also, while running it in Minikube, if query the rule expression with a wider time range (tested with 6-10 minutes), some data is returned. E.g., `sum by(cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on(cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))`

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/19862976/163493160-dc4dd273-bb1f-4843-947f-f13211c8870f.png">

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/19862976/163493195-41f9e0ea-2cd0-4395-b24e-c52a063751b8.png">

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/19862976/163493236-4c697327-919f-43be-ba3c-6a10566987e6.png">

**Comment by B1ue-W01f** [comment]
> FWIW I get an "Empty query result" for this in Prometheus:
> 
> ```
> rate(node_cpu_seconds_total{job="node"}[1m])
> ```
> 
> When that's the first example at https://www.robustperception.io/understanding-machine-cpu-usage, which seems to be pointed to in many places around the internet.

Searching around a little there doesn't appear to be a job: "node" but there is a job: "node-exporter".

**Comment by B1ue-W01f** [comment]
I assume this relates to this line here:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1531

**Comment by harshavardhanc** [comment]
Facing a similar issue with the latest kube-prometheus-stack, not getting CPU metrics for pods. Any update on how to fix this issue?

**Comment by emmanuel-messegue** [comment]
Hi,
Same problem here.
All targets are fine in promotheus but in grafana there is no data in all dashboards for cpu or memory utilization.

**Comment by jgillich** [comment]
If you're on minikube+docker, the problem is most likely missing container labels: https://github.com/rancher/rancher/issues/38934#issuecomment-1294585708

**Comment by emmanuel-messegue** [comment]
Thanks for your answer.
I deployed a bare metal kubernetes with metallb and flannel.

**Comment by jithindevasia** [comment]
@emmanuel-messegue Were you able to resolve this issue? I'm having the same problem.
