### ISSUE TITLE
[kube-prometheus-stack] metric indicating some PODs down while they're up

### ISSUE THREAD

**Issue by dchiaramello** [prometheus-community/helm-charts#1943]
### Describe the bug a clear and concise description of what the bug is.

The 'up' metric of some deployed PODs shows a 0 value, while kubectl indicates that these PODs are running.

Result of corresponding '**kubectl get pod <xxx>**' command:
```
NAME                                                  READY   STATUS    RESTARTS   AGE
crypto-keys-57bd4cfc7f-9ncfr                          1/1     Running   0          6h38m
prometheus-prometheus-operator-kube-p-prometheus-0    2/2     Running   0          2d9h
prometheus-prometheus-operator-kube-p-prometheus-1    2/2     Running   0          2d9h
```
Corresponding metrics:
`up{container="crypto-keys",endpoint="jolokia-http",env="prod",exporter="prometheus",instance="10.43.7.14:8778",job="crypto-keys",namespace="ota-cloud",pod="crypto-keys-57bd4cfc7f-9ncfr",prometheus="monitoring/prometheus-operator-kube-p-prometheus",prometheus_replica="prometheus-prometheus-operator-kube-p-prometheus-1",service="crypto-keys",tenant="gtodfw71",tenant_type="app"} 0 1648733360057
up{container="prometheus",endpoint="web",env="prod",exporter="prometheus",instance="10.43.5.3:9090",job="prometheus-operator-kube-p-prometheus",namespace="monitoring",pod="prometheus-prometheus-operator-kube-p-prometheus-0",prometheus="monitoring/prometheus-operator-kube-p-prometheus",prometheus_replica="prometheus-prometheus-operator-kube-p-prometheus-1",service="prometheus-operator-kube-p-prometheus",tenant="gtodfw71",tenant_type="app"} 0 1648733358917
up{container="prometheus",endpoint="web",env="prod",exporter="prometheus",instance="10.43.7.6:9090",job="prometheus-operator-kube-p-prometheus",namespace="monitoring",pod="prometheus-prometheus-operator-kube-p-prometheus-1",prometheus="monitoring/prometheus-operator-kube-p-prometheus",prometheus_replica="prometheus-prometheus-operator-kube-p-prometheus-1",service="prometheus-operator-kube-p-prometheus",tenant="gtodfw71",tenant_type="app"} 0 1648733369553
`
All the other deployed PODs have the expected 1 value, but not these ones....

_I also noted that the **endpoint** labels are set to strange values - but I have many other PODs which also have a weird value in that label (example of **endpoint** values: 8443, https, http...). I'm ignoring that label, anyways._

I'm not sure that's the right place for that issue - sorry in advance if that's not the case...
Thanks for your attention!

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:50:27Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.5.0

### What happened?

'up' metric show a 0 value for runnnig PODS

### What you expected to happen?

'up' metric showing 1 value for running PODS

### How to reproduce it?

Unpredictable

### Enter the changed values of values.yaml?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by kfox1111** [comment]
up means prometheus can contact the http endpoint to gather metrics, not that kubernetes thinks the state is ready. That usually is a result of a misconfiguration of the app/servicemonitor or something wrong on the network.

**Comment by zeritti** [comment]
When a scrape of an endpoint (instance) fails, i.e. `up == 0` for that endpoint, Prometheus also shows the related error in the Prometheus UI under Status/Targets.

**Comment by dchiaramello** [comment]
Hello.

This is the piece of information I was missing.
I'm closing the ticket, then - at least I know what I have to look for!

Thanks a lot!
