### ISSUE TITLE
[prometheus-adapter] upgrade to 3.0.3 failed even with --force

### ISSUE THREAD

**Issue by pitiwari** [prometheus-community/helm-charts#1945]
### Describe the bug a clear and concise description of what the bug is.

we are trying to upgrade prometheus-adapter from 2.17.1 to 3.0.3 but upgrade fails, based on linkebelow we tried setting force true but sill the same issue. For upgrade to work we have to delete the chart which is not feasible in production 

https://github.com/prometheus-community/helm-charts/commit/accabfb2d3402cb915ff3a77c9b433fc929a7d38#diff-1df123afe3fda565598030ba365eafb886aeb665489b2d96083a75b9fbf1a238R57

STDERR:
  Error: UPGRADE FAILED: failed to replace object: Deployment.apps "prometheus-adapter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus-adapter", "app.kubernetes.io/name":"prometheus-adapter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

COMBINED OUTPUT:
  Error: UPGRADE FAILED: failed to replace object: Deployment.apps "prometheus-adapter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus-adapter", "app.kubernetes.io/name":"prometheus-adapter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
make: *** [prometheus-adapter-apply] Error 1

### What's your helm version?

v3.7.1

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-adapter

### What's the chart version?

3.0.3

### What happened?

we are trying to upgrade prometheus-adapter  from 2.17.1 to 3.0.3 but upgrade fails, based on linke below we tried setting force true but sill the same issue. For upgrade to work we have to delete the chart which is not feasible in production 

https://github.com/prometheus-community/helm-charts/commit/accabfb2d3402cb915ff3a77c9b433fc929a7d38#diff-1df123afe3fda565598030ba365eafb886aeb665489b2d96083a75b9fbf1a238R57

STDERR:
  Error: UPGRADE FAILED: failed to replace object: Deployment.apps "prometheus-adapter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus-adapter", "app.kubernetes.io/name":"prometheus-adapter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

COMBINED OUTPUT:
  Error: UPGRADE FAILED: failed to replace object: Deployment.apps "prometheus-adapter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus-adapter", "app.kubernetes.io/name":"prometheus-adapter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
make: *** [prometheus-adapter-apply] Error 1

### What you expected to happen?

errorless upgrade 

### How to reproduce it?

run upgrade

### Enter the changed values of values.yaml?

2.17.1 to 3.0.3 version

### Enter the command that you execute and failing/misfunctioning.

custom commands

**Comment by monotek** [comment]
before the upgrade do:

```
kubectl delete deploy prometheus-adapter --cascade=orphan
```

**Comment by pitiwari** [comment]
@monotek thanks is there any other workaround, we dont want to delete the chart since it is taking production traffic

**Comment by monotek** [comment]
I was not talking about the chart but about the deployment and --cascade=orphan will keep your pods and only delete the deployment resource. 

Some cleanup afterwards might be needed, if you don't add the new labels to the pods.

**Comment by pitiwari** [comment]
ok thanks, we will try it out

**Comment by bseenu** [comment]
Can you please update README as well

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/README.md#to-300
