### ISSUE TITLE
[kube-prometheus-stack] Scraping not Functional for Host-Network Components

### ISSUE THREAD

**Issue by linus365** [prometheus-community/helm-charts#1946]
### Describe the bug a clear and concise description of what the bug is.

Hey,
i have the problem, that the monitoring does not work for some components which use the host network.
Those pods bind to the public ip of each node.
Affected are the following components:

- kubeControllerManager
- kubeScheduler
- kubeEtcd
- kubeProxy
- nodeExporter

I get these alerts targeting those components:

- KubeControllerManagerDown
- KubeProxyDown
- EtcdInsufficientMembers
- TargetDown warning (node-exporter)

This is on a rke2 cluster on root servers from netcup. 
I would greatly appreciate any help, thanks a lot in advance :)

### What's your helm version?

v3.6.3

### What's your kubectl version?

v1.23.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.6.0

### What happened?

Using the default values for 

- kubeControllerManager
- kubeScheduler
- kubeEtcd
- kubeProxy
- nodeExporter

the monitoring does not work.

### What you expected to happen?

The monitoring should work without alerts informing about malfunctions in the mentioned components.

### How to reproduce it?

- create an rke2 cluster (or create other host network load manually)
- rollout the kube-prometheus-stack chart with the default values
- alerts should trigger

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install monitoring \
     --atomic \
     --debug \
     --timeout 600s \
     --create-namespace \
     --namespace monitoring \
     --version 34.6.0 \
     prometheus-community/kube-prometheus-stack

**Comment by zeritti** [comment]
For components
```
kubeControllerManager
kubeScheduler
kubeEtcd
kubeProxy
```
you can use `endpoints` at each of them in the values file, e.g. `kubeProxy.endpoints`, to specifiy the IP addresses at which these are reachable. One has to make sure that they listen on non-loopback IPs. Typically, kube-proxy uses flag `--metrics-bind-address 127.0.0.1:10249` by default. 

The chart will then create endpoints in the `kube-system` namespace that will be scraped by Prometheus discovered through the corresponding service monitors. All this assumes that you own the control plane.

For an external node exporter, the chart does not support creating an endpoint. You may wish to look into using  `prometheus.prometheusSpec.additionaScrapeConfigs`, though.

**Comment by linus365** [comment]
Hey, thanks for the tips @zeritti. I will try them out :)
