### ISSUE TITLE
[prometheus-rabbitmq-exporter] Add support for Service Account

### ISSUE THREAD

**Issue by danielcrisap** [prometheus-community/helm-charts#1948]
### Is your feature request related to a problem ?

I'd love to have support for a service account creation directly in Chart `Prometheus-RabbitMQ-exporter` like in `Prometheus-Postgres-exporter`
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-postgres-exporter/templates/serviceaccount.yaml

### Describe the solution you'd like.

Include the template to generate a service account in Helm Chart

### Describe alternatives you've considered.

NONE

### Additional context.

I'm using HashiCorp Vault to store and manage my credentials and to be able to authenticate on Vault I need a Service Account, that will be used by an init-container injected by Vault Controller.

**Comment by monotek** [comment]
PR welcome ;-)

**Comment by bilalcaliskan** [comment]
very good idea. if it is OK for you, i can create a PR @danielcrisap WDYT?

**Comment by danielcrisap** [comment]
> very good idea. if you are not available to create a PR, i will be honored to create a one @danielcrisap WDYT?

Hi @bilalcaliskan,
I was creating this PR this morning, but thanks for the help.
