### ISSUE TITLE
[prometheus-redis-exporter] ServiceMonitor not generate when set flag true

### ISSUE THREAD

**Issue by dbvan** [prometheus-community/helm-charts#1949]
### Describe the bug a clear and concise description of what the bug is.

I set in values.yaml:
serviceMonitor:
  enabled: true
And facing issue serviceMonitor object not created

### What's your helm version?

v3.4.0

### What's your kubectl version?

v1.21.9

### Which chart?

prometheus-redis-exporter

### What's the chart version?

4.6.0

### What happened?

I set in values.yaml:
serviceMonitor:
  enabled: true
And facing issue serviceMonitor object not created

### What you expected to happen?

serviceMonitor should be create when set flag true in values.yaml

### How to reproduce it?

Remove "and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" )" in templates/servicemonitor.yaml

### Enter the changed values of values.yaml?

serviceMonitor:
  enabled: true

### Enter the command that you execute and failing/misfunctioning.

kustomize build . --enable-helm

**Comment by nevarsin** [comment]
For future people: 'helm template' cannot assess conditions like the one mentioned above as they are strictly related to the capabilities of the target cluster.

In order to mock the presence of a specific api, you can set ' --api-versions monitoring.coreos.com/v1' to your helm template command.
