### ISSUE TITLE
kube-prometheus-stack

### ISSUE THREAD

**Issue by bhttraku4** [prometheus-community/helm-charts#1956]
### Describe the bug a clear and concise description of what the bug is.

I am upgrading the kube-prometheus-stack from the repo https://prometheus-community.github.io/helm-charts to 18.0.0 version.
So i did upgrade it from 15 to 17 there was no problem but while upgrading to 18 i got an error given below-:

 **Error: template: kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml:1206:41: executing "kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml" at <.Values.grafana.sidecar.dashboards.multicluster.global.enabled>: can't evaluate field global in type interface {}**

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"f74784f1eaf1e02b651778d6ee2df1ae5ee729ae", GitTreeState:"clean", BuildDate:"2022-03-10T07:58:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

version    = "18.0.0" even in 19 also

### What happened?

So i am upgarding the kube-prometheus-stack and it works fine while upgrading from 15 to 17 but at 18 it gives me an error given below-:
 Error: template: kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml:1206:41: executing "kube-prometheus-stack/templates/grafana/dashboards-1.14/workload-total.yaml" at <.Values.grafana.sidecar.dashboards.multicluster.global.enabled>: can't evaluate field global in type interface {}

### What you expected to happen?

it should upgrade to the 18 and so on later version 
FYI- I am running terraform to upgrade the version over helm 

### How to reproduce it?

Upgrade the kube-prometheus-version to 18 19 from the previous verison and then change the version andrun terraform while changing the version to 18 or 19 ...

### Enter the changed values of values.yaml?

 version    = "18.0.0"

### Enter the command that you execute and failing/misfunctioning.

terraform apply -target=helm_release.kube-prometheus

### Anything else we need to know?

So i am upgarding the kube-prometheus-stack by running the terraform.

**Comment by bhttraku4** [comment]
maybe not a bug but would be really grateful if you can help me out to fix this issue

**Comment by zeritti** [comment]
The value `grafana.sidecar.dashboards.multicluster` was [changed](https://github.com/prometheus-community/helm-charts/blob/0b0956ec3fb3f2af1a61f652d9c0e0a350cf988e/charts/kube-prometheus-stack/values.yaml#L681) in 17.2.0 from a string to a map. You may need to adjust your values file.

**Comment by bhttraku4** [comment]
Can you please be precise what needs to be changed in the values file?

**Comment by yogesh-pal** [comment]
@bhttraku4 i'm also facing the same issue. Could you please share it's exact value.

**Comment by yogesh-pal** [comment]
multicluster:
     global:
i have use this but i'm getting below error now:
Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 671: mapping values are not allowed in this context
