### ISSUE TITLE
[kube-prometheus-stack] Inconsistent naming of kubernetes resources created by the stack

### ISSUE THREAD

**Issue by tringuyen-yw** [prometheus-community/helm-charts#1960]
### Describe the bug a clear and concise description of what the bug is.

`kube-prometheus-stack` has an inconsistent naming convention when creating kubernetes resources (pods , deployment, statefulset, etc). Example, let assume the helm release is named `kubepromstack` which was installed by:

```
helm install kubepromstack prometheus-community/kube-prometheus-stack -n monitoring
```
Helm then creates various kubernetes resources which different naming convention. For sub-charts which are NOT directly dependent on Prometheus, the name = `helm-release-name` + `component-name`:

- **kubepromstack**-grafana
- **kubepromstack**-kube-state-metrics
- **kubepromstack**-prometheus-node-exporter-?????

For component directly linked to prometheus, the prefix =  `helm-release-name` + `-kube-prometheus`, then thruncated to 26 chars:

- **kubepromstack-kube-prometh**-operator (pod)
- **kubepromstack-kube-prometh**-prometheus (service)
- **kubepromstack-kube-prometh**-alertmanager (service)
- prometheus-**kubepromstack-kube-prometh**-prometheus (Daemonset)

One of the consequence of this naming convention is in case we need to refer BY NAME to the resources created by `kube-prometheus-stack`, For example when configuring Thanos. The way to address the resource is rather complicated because of this arbitrary naming convention.

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"4d46ddba34543ef2253f4f0b33ccad59e997efa4", GitTreeState:"clean", BuildDate:"2022-02-10T03:18:31Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.8.0

### What happened?

(described above)

### What you expected to happen?

Use the same naming convention for all components = `helm-release-name` + `-` + `component-name`. Which is already used by components such as `grafana`, `kube-state-metrics` shown in the bug description above.

More exactly, align the naming of resources for `prometheus`, `alertmanager`, prometheus operator to that of `grafana`. Example:

- Instead of: **kubepromstack-kube-prometh**-prometheus (for Prometheus service)
- Better name would be: **kubepromstack**-prometheus

### How to reproduce it?

```
helm install kubepromstack prometheus-community/kube-prometheus-stack -n monitoring
```
Then inspect the objects created in the `monitoring` namespace. Then compare the prefixes of the resource names

```
kubectl get all -n monitoring
```

### Enter the command that you execute and failing/misfunctioning.

(shown in How to reproduce it?)

**Comment by tringuyen-yw** [comment]
**GOOD ENOUGH WORKAROUND**

The naming logic of Kubernetes resources directly related to Prometheus (operator, prometheus, alertmanager) is defined in the method `define "kube-prometheus-stack.fullname"` in [charts/kube-prometheus-stack/templates/_helpers.tpl](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/_helpers.tpl#L14-L25)

To make the naming consistent with the subcharts (grafana, kube-state-metrics, prometheus-node-exporter), ie naming the kubernetes resources  with the simplified pattern <RELEASE-NAME>-component-name (eg. `kubepromstack-prometheus` or `kubepromstack-operator`

The `kube-prometheus-stack` custom helm value `fullnameOverride` should have the same name as the helm release name

```yaml
fullnameOverride: kubepromstack 
```

Not sure what is the rationale of the object naming convention logic used in `kube-prometheus-stack.fullname` but this seems overly complicate for no apparent useful purpose.

**Comment by lusson-luo** [comment]
@tringuyen-yw i have same question, how do you relsove this?
i edit nameOverride: "prometheus" in kube-prometheus-stack, 
alertmanagers.monitoring.coreos.com and prometheuses.monitoring.coreos.com name is normal, "observable1-prometheus-prometheus" and "observable1-prometheus-alertmanager ", 
but pod name add preffix prometheus, alertmanager, is "alertmanager-observable1-prometheus-alertmanager-0", "prometheus-observable1-prometheus-prometheus-0"
how to remove the prefix  prometheus, alertmanager ?
