### ISSUE TITLE
[kube-prometheus-stack] Option to customize Prometheus rules

### ISSUE THREAD

**Issue by mafaz-udayar-woolworths** [prometheus-community/helm-charts#1970]
### Is your feature request related to a problem ?

We use kube-prometheus-stack helm chart through kustomize and flux to create our Prometheus operator and the CRDs. We have a requirement to update the alerting rule expression or "for" time period on different alerts. The current kube-prometheus-stack chart has these values hard coded, which doesn't allow it to modified for the consumers of this chart.

### Describe the solution you'd like.

Each alerting rule in Prometheus alert should have an entry in values file where certain properties can be customized from the consumers

### Describe alternatives you've considered.

NONE

**Comment by spjspjspj** [comment]
Thanks for raising the request here. We're having the same issue and wish for the same thing.

**Comment by askoriy** [comment]
I have the same issue too. Is it any solution?
