### ISSUE TITLE
Prometheus not scraping metrics from all namespaces

### ISSUE THREAD

**Issue by Anusha-Kolli** [prometheus-community/helm-charts#1985]
We have upgraded kube-stack prometheus chart form 17.1.0 to 32.2.1
Previously it used to scrape metrics from all our namespaces but after the upgrade it only scraping metrics from monitoring namespace.

Not sure which configs need to be updated to scrape metrics from all namespace.
Any help would be appreciated

**Comment by dbg-raghulkrishna** [comment]
any update on this?
