### ISSUE TITLE
[prometheus] Host namespaces usage in nodeExporter Pod

### ISSUE THREAD

**Issue by sunnygoel87** [prometheus-community/helm-charts#1986]
Hi Team,

I installed the prometheus chart on EKS clustrer in prometheus namespace using the following command. 

`helm install <Release_Name> prometheus-community/prometheus -n prometheus`

I noticed in NodeExporter pods specification that they do leverage **host namespaces** on Linux machine. But i think, as per k8s best practices, PODS shouldn't consume the Host namespace on worker nodes. Is my understanding correct? If yes, then if i set the hostNetwork and hostPID attributes to false in values.yaml file, will it affect anything on capturing the Node related metrics? Please let me know. 

`
hostNetwork: true
hostPID: true
`

**Comment by luislhl** [comment]
I have the same question. Did you try disabling them, @sunnygoel87 ?
