### ISSUE TITLE
[prometheus-server] serverContext not available on container level

### ISSUE THREAD

**Issue by caisindenis** [prometheus-community/helm-charts#1990]
### Is your feature request related to a problem ?

can we allow inputing securityContext on container level for Prometheus server?
Right now functionality exists only on the Pod level.
From k8s documentation: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

### Describe the solution you'd like.

Add .Values.server.containerSecurityContext variable in templates.

### Describe alternatives you've considered.

NONE

**Comment by sunnygoel87** [comment]
@caisindenis - I believe there is a typo in the title. It says **serverContext** instead of **securityContext**
