### ISSUE TITLE
Give chart maintainer collaborators correct GitHub repo access level

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#20]
After #11 

See related #12 and #15 

## Context

Until #11 this repo is under my individual user account, therefore there is only one "collaborator" access level. But after this transfer, we will have options. One suggestion https://github.com/scottrigby/prometheus-helm-charts/issues/12#issuecomment-676499306 was that all chart maintainers be given repo "Maintain" access level.

**Example options list:**
<img width="325" alt="Screen Shot 2020-08-19 at 11 44 35 AM" src="https://user-images.githubusercontent.com/407675/90675104-08a7b800-e228-11ea-8611-875c5186e151.png">

## Open questions
1. GitHub docs for [Maintain access](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level) says it allows members to [Push to protected branches](https://docs.github.com/en/articles/about-protected-branches). Does this mean bypassing the rules in `CODEOWNERS`? I don't have a current repo set up for testing this

**Comment by monotek** [comment]
Imho you can disable push access for admins too. I hope I can try later. I'm in the phone most of the time as I'm on vacation.

**Comment by scottrigby** [comment]
Update, now that #11 is complete, there is a new team set up for this – all current chart maintainers will be invited soon. Until then, you are all still "collaborators" on this repo.

**Comment by scottrigby** [comment]
All existing chart maintainers have been invite to the @prometheus-community/helm-charts-maintainers team 👍 I'll remove your old collaborator status. You will all need to accept the invite to maintain Write access to your charts.

**Comment by gkarthiks** [comment]
@scottrigby aah, that makes sense. All of a sudden git started complaining about the write access 🤣 . I will accept that now.

**Comment by scottrigby** [comment]
@gkarthiks ok great. Please lmk if you run into any trouble- feel free to ping me on slack 🙂

**Comment by scottrigby** [comment]
This is done

**Comment by desaintmartin** [comment]
I don't think I've been invited, as I don't see any mail nor invitation in the github notifications pages, could you double check?

**Comment by scottrigby** [comment]
Thanks @desaintmartin you should have an invite now

**Comment by desaintmartin** [comment]
Done, thanks!
