### ISSUE TITLE
[prometheus-kube-stack] memory usage Grafana VS kubectl top

### ISSUE THREAD

**Issue by PrettySolution** [prometheus-community/helm-charts#2006]
### Describe the bug a clear and concise description of what the bug is.

Hello, I see different numbers in Grafana dashboard as opposite to `kubectl top`. For example the time-t-s-proc-3 pod utilizes ~8Gib according to `top` VS 16Gib in Grafana.
```
NAME                               CPU(cores)   MEMORY(bytes)
time-t-s-proc-1-8488c9f945-kpgg6   98m          1782Mi
time-t-s-proc-2-57b5dc97b9-2jsbn   85m          2296Mi
time-t-s-proc-3-645bc87d4f-bl6k7   203m         8342Mi
time-t-s-proc-4-7c8c9f94df-7wnmt   94m          1815Mi
```
<img width="1852" alt="image" src="https://user-images.githubusercontent.com/57800300/164933937-8db2ef26-f1ed-4b10-98db-c6205dbfcc8d.png">

### What's your helm version?

v3.8.1

### What's your kubectl version?

v1.23.6

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

34.9.1

### How to reproduce it?

`helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`
`helm repo update`
`helm search repo prometheus-community --versions`
`helm -n prometheus install prometheus prometheus-community/kube-prometheus-stack --create-namespace --version 34.9.1  --values microk8s-monitoring/values.yml`

### Enter the changed values of values.yaml?

```
grafana:
  persistence:
    enabled: true
  adminPassword: admin
  grafana.ini:
    auth.anonymous:
      enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

kubectl top pod

### Anything else we need to know?

running in microk8s
`sudo snap install microk8s --classic --channel=1.23/stable`
`microk8s.enable dns helm3 metallb storage`

**Comment by nicholas-r-king** [comment]
Having this exact same issue on "34.10.0" on EKS.

**Comment by monotek** [comment]
Kubectl top uses metrics-server and grafana uses Prometheus. Both getting the data from k8s API but they could get them on different times. Also check what time interval you use in the Prometheus query in grafana so your metric is not flattened. Shorter is better.
