### ISSUE TITLE
[prometheus-kube-stack] Error: cannot update resource "prometheuses/status"

### ISSUE THREAD

**Issue by sgolod** [prometheus-community/helm-charts#2010]
### Describe the bug a clear and concise description of what the bug is.

The latest version prometheus-operator support subresource 'status', but ClusterRole doesn't permission to use this field:
`
level=error ts=2022-04-26T11:07:50.444926796Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"k8s-monitoring/monitoring-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"monitoring-kube-prometheus-prometheus\" is forbidden: User \"system:serviceaccount:k8s-monitoring:monitoring-kube-prometheus-operator\" cannot update resource \"prometheuses/status\" in API group \"monitoring.coreos.com\" in the namespace \"k8s-monitoring\""
`

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.200", GitCommit:"87bd5277f85536686030dd1fd7d6e39776dd44d1", GitTreeState:"clean", BuildDate:"2022-03-17T20:42:25Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

35.0.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade k8s-monitoring prometheus-community/kube-prometheus-stack --install --create-namespace --namespace k8s-monitoring --values values.yaml

### Anything else we need to know?

How to fix this error:
add 
`  - prometheuses/status
`
to clusterrole.yaml in templates/prometheus-operator/

**Comment by rmartinez3** [comment]
you will need to update your chart to include this rbac

currently
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml

does not include the recent changes. 
If no one does PR I can quickly check to see what new rbac is needed 

overall should be adding 

`rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagerconfigs
  - prometheuses
  - prometheuses/finalizers
  - prometheuses/status
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules`

**Comment by erkules** [comment]
I've got the same error. To my understanding the mapping is ok. It is the latest chartversion and the ClusterRole seems to be the same.

```
$ kubectl get ClusterRoleBinding/monitoring-kube-prometheus-operator -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 35.0.0
    chart: kube-prometheus-stack-35.0.0
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-kube-prometheus-operator
subjects:
- kind: ServiceAccount
  name: monitoring-kube-prometheus-operator
  namespace: monitoring
```

I'm also not sure what there is missing:

```
 $ kubectl get clusterrole  monitoring-kube-prometheus-operator   -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2022-04-25T18:27:14Z"
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 35.0.0
    chart: kube-prometheus-stack-35.0.0
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-operator
  resourceVersion: "107172"
  uid: ad937211-7ee6-48bb-8733-a9f054cf31c8
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagerconfigs
  - prometheuses
  - prometheuses/finalizers
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
 ```

**Comment by rmartinez3** [comment]
@erkules  chart needs to have prometheuses/status under

rules:
- apiGroups:
  - monitoring.coreos.com
  
  im going to quickly try PR now

**Comment by rmartinez3** [comment]
https://github.com/prometheus-community/helm-charts/pull/2012

**Comment by rmartinez3** [comment]
@erkules  that is the change you need to fix rbac error

**Comment by fcecagno** [comment]
Hi, although I'm running the updated kube-prometheus-stack, I still see the following error on the operator:

```
$ kubectl logs pod/monitoring-kube-prometheus-operator-7668c989f7-wxjrw
level=info ts=2022-08-06T21:50:28.043527747Z caller=operator.go:1559 component=prometheusoperator key=monitoring/monitoring-kube-prometheus-prometheus msg="update prometheus status"
level=error ts=2022-08-06T21:50:28.057868675Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/monitoring-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"monitoring-kube-prometheus-prometheus\" not found"
```
Here is the ClusterRole:

```
$ k get clusterrole monitoring-kube-prometheus-operator -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2022-07-12T19:21:51Z"
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 39.4.0
    chart: kube-prometheus-stack-39.4.0
    helm.toolkit.fluxcd.io/name: monitoring
    helm.toolkit.fluxcd.io/namespace: flux-system
    heritage: Helm
    release: monitoring
  name: monitoring-kube-prometheus-operator
  resourceVersion: "12819572"
  uid: bf5cc039-e20a-459c-adec-2d478ff002fc
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagerconfigs
  - prometheuses
  - prometheuses/status
  - prometheuses/finalizers
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
```

What am I missing?

**Comment by Spinestars** [comment]
> Hi, although I'm running the updated kube-prometheus-stack, I still see the following error on the operator:
> 
> ```
> $ kubectl logs pod/monitoring-kube-prometheus-operator-7668c989f7-wxjrw
> level=info ts=2022-08-06T21:50:28.043527747Z caller=operator.go:1559 component=prometheusoperator key=monitoring/monitoring-kube-prometheus-prometheus msg="update prometheus status"
> level=error ts=2022-08-06T21:50:28.057868675Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/monitoring-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"monitoring-kube-prometheus-prometheus\" not found"
> ```
> 
> Here is the ClusterRole:
> 
> ```
> $ kubectl get clusterrole monitoring-kube-prometheus-operator -o yaml
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRole
> metadata:
>   annotations:
>     meta.helm.sh/release-name: monitoring
>     meta.helm.sh/release-namespace: monitoring
>   creationTimestamp: "2022-07-12T19:21:51Z"
>   labels:
>     app: kube-prometheus-stack-operator
>     app.kubernetes.io/instance: monitoring
>     app.kubernetes.io/managed-by: Helm
>     app.kubernetes.io/part-of: kube-prometheus-stack
>     app.kubernetes.io/version: 39.4.0
>     chart: kube-prometheus-stack-39.4.0
>     helm.toolkit.fluxcd.io/name: monitoring
>     helm.toolkit.fluxcd.io/namespace: flux-system
>     heritage: Helm
>     release: monitoring
>   name: monitoring-kube-prometheus-operator
>   resourceVersion: "12819572"
>   uid: bf5cc039-e20a-459c-adec-2d478ff002fc
> rules:
> - apiGroups:
>   - monitoring.coreos.com
>   resources:
>   - alertmanagers
>   - alertmanagers/finalizers
>   - alertmanagerconfigs
>   - prometheuses
>   - prometheuses/status
>   - prometheuses/finalizers
>   - thanosrulers
>   - thanosrulers/finalizers
>   - servicemonitors
>   - podmonitors
>   - probes
>   - prometheusrules
>   verbs:
>   - '*'
> - apiGroups:
>   - apps
>   resources:
>   - statefulsets
>   verbs:
>   - '*'
> - apiGroups:
>   - ""
>   resources:
>   - configmaps
>   - secrets
>   verbs:
>   - '*'
> - apiGroups:
>   - ""
>   resources:
>   - pods
>   verbs:
>   - list
>   - delete
> - apiGroups:
>   - ""
>   resources:
>   - services
>   - services/finalizers
>   - endpoints
>   verbs:
>   - get
>   - create
>   - update
>   - delete
> - apiGroups:
>   - ""
>   resources:
>   - nodes
>   verbs:
>   - list
>   - watch
> - apiGroups:
>   - ""
>   resources:
>   - namespaces
>   verbs:
>   - get
>   - list
>   - watch
> - apiGroups:
>   - networking.k8s.io
>   resources:
>   - ingresses
>   verbs:
>   - get
>   - list
>   - watch
> ```
> 
> What am I missing?

prometheus-community/kube-prometheus-stack      39.5.0          0.58.0 ：The same error occurred

```
level=info ts=2022-08-12T04:23:38.435904424Z caller=operator.go:1559 component=prometheusoperator key=monitoring/kube-prometheus-stack-prometheus msg="update prometheus status"
level=error ts=2022-08-12T04:23:38.449997142Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/kube-prometheus-stack-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"kube-prometheus-stack-prometheus\" not found"
```
The discovery process:

I was applying a Servicemonitor object, but I found that Prometheus didn't see it, so I went to check for errors and found the above

**Comment by knweiss** [comment]
I had the same error using kube-prometheus-stack-39.11.0 on a k8s system where the kube-prometheus-stack was initially deployed as version 32.2.1 and then updated in several steps up to 39.11.0.

I think the root cause may be that helm is not able to update the CRDs shipped in the kube-prometheus-stack helm chart:
```
$ ls kube-prometheus-stack-39.11.0/crds/
crd-alertmanagerconfigs.yaml  crd-alertmanagers.yaml  crd-podmonitors.yaml  crd-probes.yaml
crd-prometheuses.yaml  crd-prometheusrules.yaml  crd-servicemonitors.yaml  crd-thanosrulers.yaml
```
YMMV but I just decided to update the crds manually using `kubectl replace -f CRDFILE` and then upgraded/re-deployed the kube-prometheus-stack helm chart and restarted the pods (`kubectl rollout restart ...`) and so far the operator's error messages disappeared.

**Comment by Rohlik** [comment]
Having the same issue with `kube-prometheus-stack-35.0.3` chart 😢.

**Comment by quangthe** [comment]
Having same issue with chart `kube-prometheus-stack-36.0.3`

**Comment by giorgiocerruti** [comment]
Having the same issue with chart `kube-prometheus-stack-45.0.0`

**Comment by zeritti** [comment]
> Having the same issue with chart `kube-prometheus-stack-45.0.0`

The cluster role for the operator was fixed in 45.1.1 (alertmanagers/status) and 35.0.2 (prometheuses/status). Please, see that Prometheus operator CRDs are up to date, i.e. at 0.63.0. Remember that Helm, apart from a fresh install, never touches CRDs if delivered with a chart in directory `crds`, so upgrading them has to be dealt with separately. HTH

**Comment by giorgiocerruti** [comment]
Thanks @zeritti it's a test installation on my local env and I forgot to update the repo 🤦🏻 .

**Comment by tirelibirefe** [comment]
Having the same issue with chart 48.3.1
