### ISSUE TITLE
how to manipulate web config secret in kube-prometheus stack?

### ISSUE THREAD

**Issue by shvenktesh9** [prometheus-community/helm-charts#2016]
have deployed the latest chart[these are all the secrets](https://i.stack.imgur.com/Uptd8.png)

how to change prometheus-kube-prometheus-stack-1651-prometheus-web-config this secret through the helm chart?

[this is secret without any changes](https://i.stack.imgur.com/KFFUc.png)

**Comment by tanmx** [comment]
Facing the same problem

**Comment by zeritti** [comment]
The secret gets created by the Operator with the contents specified by [WebTLSConfig](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#webtlsconfig) which corresponds to resource field `prometheus.spec.web.tlsConfig`. 

In the values file, setting [WebSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#webspec) is possible through field `prometheus.prometheusSpec.web`.
