### ISSUE TITLE
Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com

### ISSUE THREAD

**Issue by cconnert** [prometheus-community/helm-charts#2020]
### Describe the bug a clear and concise description of what the bug is.

When the chart is configured to use cert-manager for the addmision webhook helm install fails:

`helm install  kube-prometheus-stack prometheus-community/kube-prometheus-stack --create-namespace --namespace monitoring \ 
--set grafana.persistence.enabled=true --set grafana.testFramework.enabled=false \
--set grafana.adminUser=admin --set grafana.adminPassword=password \
--set prometheusOperator.admissionWebhooks.patch.enabled=false --set prometheusOperator.admissionWebhooks.certManager.enabled=true \
--set prometheusOperator.admissionWebhooks.certManager.admissionCert.duration=2160h \
--set prometheusOperator.admissionWebhooks.certManager.issuerRef.name="some-issuer" \
--set prometheusOperator.admissionWebhooks.certManager.issuerRef.kind="ClusterIssuer"`

Fails with: 
`Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://kube-prometheus-stack-operator.cluster-base-monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s": no endpoints available for service "kube-prometheus-stack-operator"`

A subsequent upgrade does the work ok:

`helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --create-namespace --namespace monitoring \ 
--set grafana.persistence.enabled=true --set grafana.testFramework.enabled=false \
--set grafana.adminUser=admin --set grafana.adminPassword=password \
--set prometheusOperator.admissionWebhooks.patch.enabled=false --set prometheusOperator.admissionWebhooks.certManager.enabled=true \
--set prometheusOperator.admissionWebhooks.certManager.admissionCert.duration=2160h \
--set prometheusOperator.admissionWebhooks.certManager.issuerRef.name="some-issuer" \
--set prometheusOperator.admissionWebhooks.certManager.issuerRef.kind="ClusterIssuer"
Release "kube-prometheus-stack" has been upgraded. Happy Helming!
NAME: kube-prometheus-stack
LAST DEPLOYED: Mon May  2 12:09:55 2022
NAMESPACE: cluster-base-monitoring
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --monitoring get pods -l "release=kube-prometheus-stack"
Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.`

### What's your helm version?

version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"8211ae4d6757c3fedc53cd740d163ef65287276a", GitTreeState:"clean", BuildDate:"2022-03-31T20:28:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.0.3

### What you expected to happen?

I would expect the first install to succeed

### Enter the command that you execute and failing/misfunctioning.

see description

**Comment by stazdx** [comment]
Hi, 

I have the same problem. We need to set `timeoutSecond` in helm template for admission MutatingWebhookConfiguration.
I have added this PR https://github.com/prometheus-community/helm-charts/pull/2233 for solving it.
