### ISSUE TITLE
Will move from stable/prometheus-operator to prometheus-community/kube-prometheus-stack

### ISSUE THREAD

**Issue by kimcagayat** [prometheus-community/helm-charts#2022]
Will move from stable/prometheus-operator to prometheus-community/kube-prometheus-stack

Do I need to check something before I move to the new repo?
I just noticed few things:

![image](https://user-images.githubusercontent.com/96174080/166398583-077b4c87-235b-46ee-a80f-e81e171922d4.png)

Is there any issues moving? Thanks!

**Comment by kimcagayat** [comment]
Also, I was trying to migrate but having below errors:

$ helm upgrade prometheus prometheus-community/kube-prometheus-stack -n espr-prometheus-nonprod --reuse-values --set nameOverride=prometheus
coalesce.go:160: warning: skipped value for collectors: Not a table.
coalesce.go:160: warning: skipped value for collectors: Not a table.
coalesce.go:160: warning: skipped value for collectors: Not a table.
Error: UPGRADE FAILED: template: kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml:1:197: executing "kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml" at <.Values.prometheusOperator.admissionWebhooks.certManager.enabled>: nil pointer evaluating interface {}.enabled


Here's my running pods:
[kcaga00@esco-jumphost-prod-svc-vm-01-escojump000001 espr-prometheus]$ kubectl get po
NAME                                                     READY   STATUS    RESTARTS      AGE
alertmanager-prometheus-prometheus-oper-alertmanager-0   2/2     Running   0             17d
prometheus-kube-state-metrics-6b46f67bf6-p6jcg           1/1     Running   0             17d
prometheus-prometheus-node-exporter-286gc                1/1     Running   0             17d
prometheus-prometheus-node-exporter-b8tsg                1/1     Running   0             17d
prometheus-prometheus-node-exporter-pmlgc                1/1     Running   0             17d
prometheus-prometheus-node-exporter-qqlxb                1/1     Running   0             17d
prometheus-prometheus-node-exporter-rmdw8                1/1     Running   0             17d
prometheus-prometheus-prometheus-oper-prometheus-0       4/4     Running   1 (17d ago)   17d

NOTE: Currently prometheus operator is not running because there was an upgrade to Kubernetes 1.22.

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#migrating-from-coreosprometheus-operator-chart

**Comment by kimcagayat** [comment]
Thanks for your feedback @monotek, i tried above command but having an error. Mentioned above.

**Comment by kimcagayat** [comment]
I'm having these errors:

[kcaga00@esco-jumphost-prod-svc-vm-01-escojump000001 espr-prometheus]$ helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack -f prometheus-operator-nonprod-tools-cluster-values.yaml -n espr-prometheus-nonprod
Release "kube-prometheus-stack" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec]
