### ISSUE TITLE
[alertmanager] Latest chart not available

### ISSUE THREAD

**Issue by RomainBelorgey** [prometheus-community/helm-charts#2027]
### Describe the bug a clear and concise description of what the bug is.

The alertmanager chart `0.17.0` is not available.

It explained why I can't use this chart as a dependency.
How is that possible to deploy this release ?

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}

### What's your kubectl version?

1.20

### Which chart?

alertmanager

### What's the chart version?

0.17.0

### What happened?

I can't find the version `0.17.0`.

Doing `helm search repo prometheus-community`:
```
NAME                                                    CHART VERSION   APP VERSION     DESCRIPTION                                       
prometheus-community/alertmanager                       0.15.0          v0.23.0         The Alertmanager handles alerts sent by client ...
...
```

### Enter the command that you execute and failing/misfunctioning.

Having a file `chart.yaml` with this configuration:
```
dependencies:
  - name: alertmanager
    version: 0.17.0
    repository: https://prometheus-community.github.io/helm-charts/
```

Could not find this version of the chart.

**Comment by monotek** [comment]
The release is there but the index.yaml was not updated because of some githu issue.
We triggered a new release via: https://github.com/prometheus-community/helm-charts/pull/2028

Looks good now. 0.17.1 can be used:

```
 helm repo update;helm search repo alertmanager
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "metrics-server" chart repository
...Successfully got an update from the "zammad" chart repository
...Successfully got an update from the "jetstack" chart repository
...Successfully got an update from the "strimzi" chart repository
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "grafana" chart repository
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
NAME                             	CHART VERSION	APP VERSION	DESCRIPTION                                       
prometheus-community/alertmanager	0.17.1       	v0.23.0    	The Alertmanager handles alerts sent by client ...
bitnami/kube-prometheus          	6.10.2       	0.56.1     	Prometheus Operator provides easy monitoring de...
bitnami/prometheus-operator      	0.31.1       	0.41.0     	DEPRECATED The Prometheus Operator for Kubernet...

```

**Comment by RomainBelorgey** [comment]
Thanks for the quick fix :+1:
