### ISSUE TITLE
[kube-prometheus-stack] possible to support Pushgateway?

### ISSUE THREAD

**Issue by spjspjspj** [prometheus-community/helm-charts#2030]
### Is your feature request related to a problem ?

We use pushgateway to collect metrics from our cron jobs. Right now, it seems Pushgateway is missing in this chart and we'd have to use another chart to manage Pushgateway. Would be great if it is easily supported using this chart as well.

### Describe the solution you'd like.

Add support and configuration for Pushgateway in this chart.

### Describe alternatives you've considered.

Curious if there's any suggestions.

**Comment by u0324020** [comment]
I have the same request for this chart

**Comment by danbopes** [comment]
Sad this was closed with no reply. This is a feature that I would have liked :(

**Comment by kengz** [comment]
`kube-prometheus-stack` matches servicemonitors with `labels = {release name}` to scrape; see: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L151-L153C34

So you need to create a servicemonitor for pushgateway with the matching label. For example, if you installed the stack with `helm upgrade -i prom-stack prometheus-community/kube-prometheus-stack`
Then add this to the values of `prometheus-pushgateway`:
```yaml
serviceMonitor:
  enabled: true
  additionalLabels:
    release: prom-stack
```

and run `helm upgrade -i prom-pushgateway prometheus-community/prometheus-pushgateway -f values.yaml`
