### ISSUE TITLE
Unable to install prometheus helm chart

### ISSUE THREAD

**Issue by boukisge** [prometheus-community/helm-charts#2035]
### Describe the bug a clear and concise description of what the bug is.

 $ helm install prometheus prometheus-community/prometheus-operator
WARNING: This chart is deprecated
Error: INSTALLATION FAILED: failed to install CRD crds/crd-alertmanager.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
 

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.17.2"}

### What's your kubectl version?

lient Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus-operator

### What's the chart version?

latest

### What happened?

 $ helm install prometheus prometheus-community/prometheus-operator
WARNING: This chart is deprecated
Error: INSTALLATION FAILED: failed to install CRD crds/crd-alertmanager.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

### What you expected to happen?

deploy prometheus and all of its components including grafana

### Enter the command that you execute and failing/misfunctioning.

 helm install prometheus prometheus-community/prometheus-operator

**Comment by caddymofo** [comment]
This is not a bug, the chart was deprecated and transitioned into the kube-prometheus-stack chart that uses the prometheus operator. https://github.com/prometheus-operator/prometheus-operator/blob/main/helm/README.md

**Comment by boukisge** [comment]
Please provide instructions on how to install the Prometheus operator to
minikube

**Comment by caddymofo** [comment]
`helm install prometheus prometheus-community/kube-prometheus-stack`

**Comment by Kumaraditya-cardbyte** [comment]
@caddymofo I am trying your solution but it is giving me the error that repo prometheus-community not found.

**Comment by colinmkeith** [comment]
You need to run `helm repo add <name> <url>`

In this case `helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`

See https://github.com/prometheus-community/helm-charts

```
colin% helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
"prometheus-community" has been added to your repositories
colin% helm install prometheus prometheus-community/kube-prometheus-stack 
NAME: prometheus
LAST DEPLOYED: Sat Mar 18 21:49:48 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=prometheus"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```
