### ISSUE TITLE
kube-Prometheus-stack  Issue found duplicate series for the match group 

### ISSUE THREAD

**Issue by Shiva2199** [prometheus-community/helm-charts#2038]
### Describe the bug a clear and concise description of what the bug is.

when I am running two instance of Prometheus one of the recording rule is failing with below error 

found duplicate series for the match group {instance="10.247.180.204:10250"} on the right hand-side of the operation: [{__name__="machine_memory_bytes", boot_id="aaa26d0-chjefi-484a-91d7-1ee7abb87014", endpoint="https-metrics", instance="10.247.180.246:10250", job="kubelet", machine_id="6cea22df5a08f8334b6b68d5", metrics_path="/metrics/cadvisor", namespace="kube-system", node="node1-10338-03-03-2022", prometheus="harmonia/platform-prometheus-operat-prometheus", prometheus_replica="prometheus-platform-prometheus-operat-prometheus-1", service="platform-prometheus-operat-kubelet", system_uuid="e1ca612a-6588-4374-8d57-003b5d6"}, {__name__="machine_memory_bytes", boot_id="aaa26d0c-8yu5-468a-91z7-1ee7abb87014", endpoint="https-metrics", instance="10.247.180.246:10250", job="kubelet", machine_id="6cea22df5a0c4c934b6b68d5", metrics_path="/metrics/cadvisor", namespace="kube-system", node="node1-10338-03-03-2022", prometheus="harmonia/platform-prometheus-operat-prometheus", prometheus_replica="prometheus-platform-prometheus-operat-prometheus-0", service="platform-prometheus-operat-kubelet", system_uuid="e1ca612a-6588-4374-8d57-003btr65a75d6"}];many-to-many matching not allowed: matching labels must be unique on one side

rule :
((container_memory_usage_bytes{container_name!="POD",job="kubelet"}) * (container_spec_memory_limit_bytes{container_name!="POD",job="kubelet",pod_name!=""} == bool 0) / on(instance) group_left(name) machine_memory_bytes{job="kubelet"}) * 100

please suggest how can I fix this ?
  

### What's your helm version?

3.8

### What's your kubectl version?

1.21

### Which chart?

kube-prometheus-stack

### What's the chart version?

version: 31.0.2

### How to reproduce it?

run with two replicas of Prometheus 

### Enter the changed values of values.yaml?

 kube-prometheus-stack:
     prometheus:
       prometheusSpec:
         replicas: 2

### Enter the command that you execute and failing/misfunctioning.

it is installing with no failure but the rule is failing

**Comment by eric-engberg** [comment]
I'm also getting this for a large number of rules.

**Comment by eric-engberg** [comment]
Turns out they were all kubelet related alerts which EKS doesn't have.  Disabling kubelet in the helm chart fixed it
