### ISSUE TITLE
Unable to modify helm chart of kube-prometheus-stack

### ISSUE THREAD

**Issue by srikanthankam** [prometheus-community/helm-charts#2064]
Hello Everyone, a need a quick help.
I installed kube-prometheus-stack using helm chart with the following command. 
Note: I didn't use values.yaml file for installation, means chose default configuration.
-----------
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts -n monitoring
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring
----------
By default,  retention=10d  is set.
I also removed emptyDir configuration in Promethues-Grafana deployment and added 3 EFS volumes.
-------
volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-grafana
        name: config
      - name: storage
	    persistentVolumeClaim:
               claimName: storage
      - name: sc-dashboard-volume
        persistentVolumeClaim:
          claimName: sc-dashboard-volume
      - configMap:
          defaultMode: 420
          name: prometheus-grafana-config-dashboards
        name: sc-dashboard-provider
      - name: sc-datasources-volume
	 persistentVolumeClaim:
            claimName: sc-datasources-volume
--------------
My requirement is I want to modify only one value in the installed helm chart without affecting other values, like added persistentVolumeClaims in Grafana deployment.
Want to change the value from "retention=10d" to "retention=30d".
Please help me in this scenario

**Comment by vyom-soft** [comment]
Hello,
When I perform 

`helm install --dry-run prometheus prometheus-community/kube-prometheus-stack -n monitoring`

I see following error

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]`

Any input why installation is failing
thank you.
