### ISSUE TITLE
kube-prometheus-stack wrong selector in kube-proxy service monitor

### ISSUE THREAD

**Issue by gadisn** [prometheus-community/helm-charts#2068]
### Describe the bug a clear and concise description of what the bug is.

The kube-proxy service monitor selector should identify the kube proxy pods.

However, the selection uses labels values which are specific to the kube-prometheus-stack chart/release, see [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/exporters/kube-proxy/servicemonitor.yaml#L14-L15)

kube proxy pods aren't part of the kube-prometheus-stack release, so they don't have these labels.

As a result, the service monitor fails to find the kube proxy pods, it has 0 active targets, and an alert about this is fired - KubeProxyDown

### What's your helm version?

v3.8.1

### What's your kubectl version?

v1.20.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

34.9.1

### What happened?

I get alert that kube proxy target is down

### What you expected to happen?

No such alert should be fired - if the service monitor target wouldn't be empty

### Enter the command that you execute and failing/misfunctioning.

na

**Comment by joncotton** [comment]
I don't know why it's not ultimately finding these Pods, but this specific issue isn't a bug.

The ServiceMonitor selectors target a Service and, in this case for kube-proxy, the Service is managed by this chart. `matchLabels.app` and `matchLabels.release` target the Service. Look at that Service and you'll find those selectors match the correct Pods.

**Comment by gadisn** [comment]
Thanks for the tip.
I've updated the service selector to find the pods by the labels below, and the problem is fixed.
`app: kubernetes, role: proxy`
