### ISSUE TITLE
prometheus-kube-stack: CoreDNS dashboard failed to retrieve metrics due to the breaking change of CoreDNS  1.7.0 metrics naming

### ISSUE THREAD

**Issue by TheKangaroo** [prometheus-community/helm-charts#207]
**Describe the bug**
With the [braking changes in CoreDNS metrics](https://coredns.io/2020/06/15/coredns-1.7.0-release/#metric-changes) the dashboard will fail to show some of the graphs.
Same issue was reported here https://github.com/helm/charts/issues/23474, but closed since the helm charts moved to this new location.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-kube-stack

**Which version of the chart**:
latest

**What happened**:
CoreDNS Dashboard fails to show all graphs

**What you expected to happen**:
CoreDNS Dashboard should still work with CoreDNS 1.7.x metrics.

**How to reproduce it** (as minimally and precisely as possible):
Update CoreDNS to 1.7.x .

**Comment by gkarthiks** [comment]
could this https://github.com/prometheus-community/helm-charts/pull/264 be a fix for this issue?

**Comment by TheKangaroo** [comment]
Yes, this should definitely address exactly this issue. It was already mentioned in the PR :)
