### ISSUE TITLE
[kube-prometheus-stack] Prometheus-Operator - Basic Auth

### ISSUE THREAD

**Issue by qdupuy** [prometheus-community/helm-charts#2073]
### Describe the bug a clear and concise description of what the bug is.

Basic Auth into prometheus instances

### What's your helm version?

v3.6.2

### What's your kubectl version?

v1.23.6

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

34.2.0

### What happened?

Hello,
I would like to set up an authentication with an htaccess (https://prometheus.io/docs/guides/basic-auth/) from the prometheus instance.
How can I set it up?
I would like to modify the prometheus servicemonitor, but it does not give the possibility to set up an authentication with helm charts

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install -n monitoring --create-namespace prom-operator-x prometheus-community/kube-prometheus-stack --version 34.2.0 -f apps/monitoring/prometheus-operator/values.yaml

**Comment by zeritti** [comment]
Prometheus Operator does not currently implement basicAuth for access to Prometheus. Please, see [#4200](https://github.com/prometheus-operator/prometheus-operator/issues/4200) for possible work-arounds.

Authentication with scrape targets is supported by serviceMonitor, #1890 may help.
