### ISSUE TITLE
[kube-prometheus-stack] kube-controller-manager and kube-scheduler endpoints are not configured automatically according to targeted k8s version

### ISSUE THREAD

**Issue by jabbors** [prometheus-community/helm-charts#2079]
### Describe the bug a clear and concise description of what the bug is.

@invidian did a great job in https://github.com/prometheus-community/helm-charts/pull/1393 but today I discovered that when you specify endpoints for kubeControllerManager and kubeScheduler, for a k8s cluster provisioned with eg Rancher, where these services doesn't run as a pod but as a docker service on the host, you get an error that the required port is not defined.

A workaround is to specify the port manually in the values file, eg

```
kubeControllerManager:
  endpoints:
    - 10.10.10.10
    - 10.10.10.11
    - 10.10.10.12
  service:
    port: 10257
```

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

Kube-prometheus-stack

### What's the chart version?

35.2.0

### What happened?

Errors out with a dry-run error that a required endpoint port is not defined.

### What you expected to happen?

Not having to specify the port and make it dynamic based on detected k8s version.

### How to reproduce it?

Deploy the chart specifying endpoints but not the service port, eg

```
kubeControllerManager:
  endpoints:
    - 10.10.10.10
    - 10.10.10.11
    - 10.10.10.12
```

### Enter the command that you execute and failing/misfunctioning.

ArgoCD takes care of deploying so don't know the exact command it uses.

**Comment by invidian** [comment]
Good point. It seems I have forgotten to update https://github.com/prometheus-community/helm-charts/blob/2e86d1618eb5d599576789c1202853dc5bc808c0/charts/kube-prometheus-stack/templates/exporters/kube-controller-manager/endpoints.yaml#L18 to also use new port helpers.

That seem like a simple enough issue for everyone to pick up.

**Comment by jabbors** [comment]
Fixed in https://github.com/prometheus-community/helm-charts/pull/2162
