### ISSUE TITLE
[ kube-prometheus-stack ] daemonset tolerations

### ISSUE THREAD

**Issue by pratikbin** [prometheus-community/helm-charts#2081]
### Describe the bug a clear and concise description of what the bug is.

Override `.nodeExporter.tolerations` is not honoring.

```yaml
...
## Deploy node exporter as a daemonset to all nodes
##
nodeExporter:
  enabled: true
  tolerations: []
...
```

Values in prometheus-node-exporter

https://github.com/prometheus-community/helm-charts/blob/2e86d1618eb5d599576789c1202853dc5bc808c0/charts/prometheus-node-exporter/values.yaml#L160-L162

Values in kube-prometheus-stack

https://github.com/prometheus-community/helm-charts/blob/2e86d1618eb5d599576789c1202853dc5bc808c0/charts/kube-prometheus-stack/values.yaml#L1394-L1398

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.3.1

### What happened?

I want to remove default toleration in `prometheus-node-exporter` by overriding `kube-prometheus-stack` values

### What you expected to happen?

It should override tolerations

### Enter the changed values of values.yaml?

nodeExporter:
  enabled: true
  tolerations: []

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prom prometheus/kube-prometheus-stack --version 35.3.1 --namespace monitoring --create-namespace --wait -f override-values.yaml --dry-run

**Comment by Clusiv** [comment]
+

**Comment by Clusiv** [comment]
> `nodeExporter` is not expected to hold the subchart's values, `prometheus-node-exporter` is. I'd suggest that you give this a go:
> 
> ```
> prometheus-node-exporter:
>   tolerations: []
> ```

that works good
