### ISSUE TITLE
[prometheus-kube-stack] grafana servicemonitor label is hardcoded to "grafana"

### ISSUE THREAD

**Issue by Morriz** [prometheus-community/helm-charts#209]
**Describe the bug**

grafana servicemonitor label is hardcoded to "grafana"

this prevents multiple grafana instances deployed with this chart to not have their own servicemonitor...

**Comment by monotek** [comment]
Might be related: https://github.com/prometheus-community/helm-charts/issues/199

**Comment by Morriz** [comment]
No, not related. This is the other way around: not possible to deploy multiple grafana instances because of hardcoded name.

**Comment by monotek** [comment]
OK, but could likely be fixed together anyway...

**Comment by WilliamCassanova** [comment]
Would not overriding fix this problem?  https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L7 and/or https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L19

Likewise would that perhaps also not fix the issue/question I brought up in https://github.com/prometheus-community/helm-charts/issues/199

**Comment by Morriz** [comment]
> Would not overriding fix this problem?  https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L7 and/or https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L19
> 
> 
> 
> Likewise would that perhaps also not fix the issue/question I brought up in https://github.com/prometheus-community/helm-charts/issues/199

Nope, please read my report. The name "grafana" is **hardcoded** in the service monitor in the grafana templates included in the `kube-prometheus-stack`. All the other resources use the helper templates to generate the name.

**Comment by Morriz** [comment]
bump

**Comment by Morriz** [comment]
bump to self

**Comment by monotek** [comment]
I guess bumping won't help. Would you mind to add a pr by yourself please?

**Comment by Morriz** [comment]
I want to, but gave it a bump to have it remind me as I am flooded with work

**Comment by Morriz** [comment]
...
