### ISSUE TITLE
[prometheus-kube-stack] High Availability

### ISSUE THREAD

**Issue by Yalafeg** [prometheus-community/helm-charts#210]
Hello,

Please I need to get more details about the HA implementation using the chart prometheus-kube-stack.
What is recommended to have a HA setup?
In my topology, I am using InfluxDB as external storage.
If I create multiple replica for the same prometheus instance, each replica will scrape the metrics independently from the others? So, if the scrape interval is 20 seconds and I have 4 replicas, we will get the metrics from the target 4 times within 20 seconds?

What is the best solution for the best scalability while avoind high data deduplication and high numbers of scrape targets metrics within seconds?

Please advise as I need to setup the most appropriate architecture, scalable and with data storage optimization.

For the external storage, influxdb is not a requirement if you would propose to use alternative solution.

Regards,

**Comment by fktkrt** [comment]
The question here really is about how do you want to implement HA for Prometheus itself.
You can take a look at:

- Thanos, https://github.com/thanos-io/thanos
- VictoriaMetrics, https://github.com/VictoriaMetrics/VictoriaMetrics

among other projects aiming to solve this issue.

These all can be used with the Prometheus-operator shipped by kube-prometheus-stack to achieve HA (and many other features as well).

**Comment by Yalafeg** [comment]
Thank you for your reply
