### ISSUE TITLE
[kube-prometheus-stack] alertmanager v0.24.0, telegram not working 

### ISSUE THREAD

**Issue by tinhbuon1102** [prometheus-community/helm-charts#2101]
### Describe the bug a clear and concise description of what the bug is.

I use the latest kube-prometheus-stack. But when i config for telegram with config like below, the alertmanager have not installed into the k8s.

- name: 'telegram-bot'
      telegram_configs:
      - send_resolved: true 
        bot_token: xxx        
        chat_id: xxx

When i remove, the alertmanager pod, statefullset will working well. 

Please help to solve this issue

### What's your helm version?

3.8.2

### What's your kubectl version?

1.24.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.4.2

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install monitoring ./monitoring/ --values ./monitoring/values.yaml --debug  --namespace monitoring --create-namespace

**Comment by bryanasdev000** [comment]
We will need to wait until a version of Prometheus Operator is out with support, from a quick look at the current release ([0.56.3](https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.56.3) it does not seems to support it.

Related PR: https://github.com/prometheus-operator/prometheus-operator/pull/4726 and master versus release https://github.com/prometheus-operator/prometheus-operator/compare/v0.56.3...main (ctrl+f for Telegram).

**Comment by lastdil** [comment]
Same issue...
[0.56.3] CRD does not contains the telegram_configs

**Comment by megabotan** [comment]
Prometheus Operator version 0.57.0 was released, adding support for Telegram receiver in the AlertmanagerConfig CRD

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.57.0

**Comment by sebastiangaiser** [comment]
There is a major version bump required, right?
