### ISSUE TITLE
[kube-prometheus-stack]  Shards are not being created

### ISSUE THREAD

**Issue by devops-matriz** [prometheus-community/helm-charts#2111]
### Describe the bug a clear and concise description of what the bug is.

The shards of the prometheus server aren't being created. The operator only creates one prometheus pod per replica configured. For example, with `replicas: 1` and `shards: 2` this pods are created:

```
NAME                                                    READY   STATUS    RESTARTS   AGE
prometheus-prometheus-system-kube-pro-prometheus-0      2/2     Running   0          9m39s
prometheus-system-kube-pro-operator-76856f78db-6x272    1/1     Running   0          9m42s
prometheus-system-kube-state-metrics-6cd78f8d85-84x4q   1/1     Running   0          9m42s
```

I'm using the default `values.yaml` and I only disabled alertmanager, grafana and nodeExporter.

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

35.5.1

### Enter the changed values of values.yaml?

alertmanager:
  enabled: false

grafana:
  enabled: false

nodeExporter:
  enabled: false

prometheus:
  prometheusSpec:
    shards: 2

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus-system ./kube-prometheus-stack -n prometheus-system

**Comment by kartik-moolya** [comment]
@devops-matriz  were you able to get this working? I'm facing a similar issue too

**Comment by devops-matriz** [comment]
Hi @kartik-moolya!

No, I kept my setup with only 1 replica and 1 shard. However, I haven't tested again with the latest versions of the stack. I also don't know if it's a bug in the helm chart or the prometheus operator.

**Comment by 873307947** [comment]
This problem also occurs when using charts version 39.9.0

**Comment by eliotohme** [comment]
I have had the same issue 
if you describe the stateful set the error should be related to the length of the name of the deployment
therefore setting `nameOverride`  to something like `prom` will fix the issue

**Comment by ElioTohm** [comment]
I have had the same issue
if you describe the stateful set the error should be related to the length of the name of the deployment
therefore setting nameOverride to something like prom will fix the issue
