### ISSUE TITLE
[kube-prometheus-stack] need a way to change the node-exporter image through values.yaml

### ISSUE THREAD

**Issue by mpjkrishna** [prometheus-community/helm-charts#212]
**Describe the bug**
I am installing the kube-prometheus-stack through the following command:

helm install my-stack prometheus-community/kube-prometheus-stack -f kube-prometheus-stack-values-used.yaml -n observability

The values.yaml does not have any parameter to set the node-exporter image. My cluster does not have access to quay.io docker repo. Instead I have the required images in my local repo. So I would like to pass the correct image path for node-exporter through the values file of the kube-prometheus-stack.

The same issue exists for kube-state-metrics and grafana images as well. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"65bea96239d3fa3dc1d00f3407041719fc736fce", GitTreeState:"clean", BuildDate:"2020-07-30T12:20:29Z", GoVersion:"go1.13.9 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: prometheus-community/kube-prometheus-stack
**Which version of the chart**: 10.0.2

**What happened**: Since there is no way to specify the image of the node-exporter through the kube-prometheus-stack's values.yaml, it is defaulting to "quay.io/prometheus/node-exporter:v1.0.1. As mentioned my cluster does not have access to quay.io repo. So I should be able to override the image path with my local repo which has all required images already pushed to.

**What you expected to happen**:
If I have a way to provide override the default image path through values.yaml for node-exporter, kube-state-metrics, and grafana, that would be great!

**How to reproduce it** (as minimally and precisely as possible):
Install the kube-prometheus-stack on a cluster that does not have direct access to public repos such as quay.io and docker.io.

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
key: value
```

```
helm install my-stack prometheus-community/kube-prometheus-stack -f values.yaml -n observability
```

-->

**Anything else we need to know**:

**Comment by gleichda** [comment]
Hi @mpjkrishna 
took me also some time to figure it out, but this is possible via

```yaml
prometheus-node-exporter:
  image:
    repository: docker.io/prom/node-exporter
    tag: v1.0.1
```

As these values just get passed through to the node exporter sub chart
