### ISSUE TITLE
[kube-prometheus-stack] Some URLs return 404

### ISSUE THREAD

**Issue by wi1dcard** [prometheus-community/helm-charts#213]
**Describe the bug**

Here some links in docs and codes respond 404.

1. <https://github.com/prometheus-community/helm-charts/blob/64dfb1a2e8b37e120ac536d6efda3ee17d3e3066/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L33>

2. <https://github.com/prometheus-community/helm-charts/blob/64dfb1a2e8b37e120ac536d6efda3ee17d3e3066/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L44>

3. In README.md, `prometheus-operator/kube-prometheus rules set` and `prometheus-operator/kube-prometheus dashboards`. 

**Version of Helm and Kubernetes**:

Not relevant.

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 10.1.0

**What happened**:

The URLs are incorrect.

**What you expected to happen**:

The URL leads to the rules file.

**How to reproduce it** (as minimally and precisely as possible):

Open the URL.

**Anything else we need to know**:

**Comment by invidian** [comment]
I hit the same. I wanted to sync the dashboards from upstream to import some changes and I'm not sure how to do that anymore because of broken links.

**Comment by invidian** [comment]
Not stale..

**Comment by invidian** [comment]
Not stale.

**Comment by monotek** [comment]
Have you found the correct links meanwhile and could provide a pr with the fix?

**Comment by invidian** [comment]
Not stale, I'll try to have a look into it :smile:

**Comment by invidian** [comment]
Created #665 :)
