### ISSUE TITLE
[kube-prometheus-stack] Allow custom env vars for operator

### ISSUE THREAD

**Issue by snuggie12** [prometheus-community/helm-charts#2132]
### Is your feature request related to a problem ?

I wanted to tweak GOMAXPROCS for the operator `Pod` and need to use kustomize to patch in env variables.

### Describe the solution you'd like.

Curious if there's any reason not to allow custom env vars on the operator pod.

### Describe alternatives you've considered.

I already have this solved, just curious if others who don't have kustomize could benefit from this customization in the helm chart.

**Comment by MarkusBauerBE** [comment]
This could potentially also be a workaround for providing CA certificates for selfhosted S3 services like MinIO which currently doesn't work in the helm deployment at all.
