### ISSUE TITLE
[prometheus] statefulSet deployment fails

### ISSUE THREAD

**Issue by Subetov** [prometheus-community/helm-charts#2135]
### Describe the bug a clear and concise description of what the bug is.
```
Error: UPGRADE FAILED: failed to create resource: Service "qqq-release-qqq-metrics-qqq-monitoring-prometheus-server-headless" is invalid: metadata.name: Invalid value: "qqq-release-qqq-metrics-qqq-monitoring-prometheus-server-headless": must be no more than 63 characters
```

Seems some _helpers needed to truncate the name...

### What's your helm version?

v3.9.0

### What's your kubectl version?

v1.21.4

### Which chart?

prometheus

### What's the chart version?

15.9.1

### What happened?

I can't do upgrade while using Deployment. Got this error:
```
prometheus-server ts=2022-06-08T14:47:14.211Z caller=main.go:1077 level=error err="opening storage failed: lock DB directory: resource temporarily unavailable"
```

So I've tried to use statefulSet, and got another error.

### What you expected to happen?

The upgrade is successful, no errors.

### How to reproduce it?

Run:
helm upgrade -i qqq-release-qqq-metrics-qqq-monitoring prometheus-community/prometheus --version 15.9.1 -f values.yaml

```
server:
    statefulSet:
      enabled: true
```

### Enter the changed values of values.yaml?

```
server:
    statefulSet:
      enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i qqq-release-qqq-metrics-qqq-monitoring prometheus-community/prometheus --version 15.9.1 -f values.yaml

**Comment by haghighi-ahmad** [comment]
Duplicate of #1033
