### ISSUE TITLE
[kube-prometheus-stack] template "abc.template" not defined

### ISSUE THREAD

**Issue by sinhblue** [prometheus-community/helm-charts#2136]
### Describe the bug a clear and concise description of what the bug is.

I tried to install prometheus stack using helm, but got an error like below
```
templates:\n- /etc/alertmanager/config/*.tmpl": template: kube-prometheus-stack/templates/alertmanager/secret.yaml:9:26: executing "kube-prometheus-stack/templates/alertmanager/secret.yaml" at <{{template "abc.template" .}}>: template "abc.template" not defined
```

### What's your helm version?

v3.8.2

### What's your kubectl version?

1.23

### Which chart?

kube-prometheus-stack

### What's the chart version?

4

### What happened?

template "abc.template" not defined

### What you expected to happen?

the release is installed successfully

### Enter the changed values of values.yaml?

prometheusOperator:
  image:
    repository: quay.io/prometheus-operator/prometheus-operator
    tag: v0.57.0
    sha: ""
    pullPolicy: IfNotPresent

grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/subnets: ***
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
      alb.ingress.kubernetes.io/certificate-arn: ***
    path: /

prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/subnets: ***
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /
      alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
      alb.ingress.kubernetes.io/certificate-arn: ***
    paths: 
      - /
    pathType: Prefix

  prometheusSpec:
    nodeSelector: {
      node: tool
    }
    retention: 30d
    storageSpec: 
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

alertmanager:
  config:
    route:
      receiver: 'telegram-notifications'
      group_by: ['alertname']
      routes:
        - receiver: 'telegram-notifications'
          continue: true
          matchers:
            - alertname != InfoInhibitor
            - alertname != Watchdog
            - alertname != CPUThrottlingHigh
            - alertname != KubeProxyDown
            - alertname != KubeControllerManagerDown
            - alertname != TargetDown
            - alertname != KubeSchedulerDown
        - receiver: 'blackhole'
          continue: true
          match_re:
            alertname: "InfoInhibitor|Watchdog|CPUThrottlingHigh|KubeProxyDown|KubeControllerManagerDown|TargetDown|KubeSchedulerDown"
        
    receivers:
      - name: 'telegram-notifications'
        telegram_configs:
          - bot_token: ***
            chat_id: ***
            api_url: "https://api.telegram.org"
            parse_mode: 'HTML'
            message: '{{ template "abc.template" .}}'
      - name: 'blackhole'
    templates:
      - '/etc/alertmanager/config/*.tmpl'
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    nodeSelector:
      node: tool

  tplConfig: true
  templateFiles:
    abc.tmpl: |-
      {{ define "abc.template" }}
      {{if eq .Status "firing"}}
      <b>Status:</b> {{.Status | toUpper}} 🔥
      {{end -}}
      {{if eq .Status "resolved"}}
      <b>Status:</b> {{.Status | toUpper}} ✅
      {{end }}
      {{ range .Alerts }}
      <b>Alert:</b> {{ .Labels.alertname }}
      <b>Description:</b> {{ .Annotations.description }}
      {{$severity := .Labels.severity -}}
      {{if eq $severity "Warning" -}}
      <b>Severity:</b> {{$severity}} ⚠️
      {{else if eq $severity "Critical" -}}
      <b>Severity:</b> {{$severity}} 🚨
      {{else -}}
      <b>Severity:</b> {{$severity}}
      {{- end -}}
      {{ end }}
      {{ end }}

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus -f values.yaml -n monitor prometheus/kube-prometheus-stack

**Comment by ball-hayden** [comment]
@zanhsieh why was this closed?

Was this fixed, or is there a solution?
