### ISSUE TITLE
Update the issue template with an accurate chart name example

### ISSUE THREAD

**Issue by wi1dcard** [prometheus-community/helm-charts#214]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

In the current issue template of bug reporting, the default title is `[name of the chart e.g. prometheus-kube-stack] issue title`. The example chart name `prometheus-kube-stack` is a little bit strange. I checked the issue list, it seems people are pretty easy to get confused with the real existing chart `kube-prometheus-stack` and the "misleading" example `prometheus-kube-stack`.

Can we update the name in the example to the real chart name `kube-prometheus-stack`? Does it sound ideal?

**Comment by gkarthiks** [comment]
Thank you for bringing this up. Please feel free to Open a PR.

**Comment by torstenwalter** [comment]
I suggest to replace `[name of the chart e.g. prometheus-kube-stack]` with `<chart-name>` or something like this. No idea how to make it more obvious to people that they have to change it.

I would avoid using the name of the real chart as that would make it harder for maintainers of that chart to search for issues. As every time somebody forgets to change it it would contain the wrong chart.

An alternative to requesting people to mention the chart name in the title would be to set up a GitHub action, which checks which chart(s) have been modified and tags PRs with a `chart-<chart-name>` label. Obviosly that only works for PRs and not for issues.

For issues we could check if the title is correct and label based on that.
