### ISSUE TITLE
[prometheus-node-exporter] Allow adding annotations to the daemonset using values

### ISSUE THREAD

**Issue by Robsta86** [prometheus-community/helm-charts#2141]
### Is your feature request related to a problem ?

We are using gatekeeper to prevent the creation of resources in our cluster that do not comply with our standards. However in some scenarios there is a need to make exceptions, for instance for node-exporter that wants to interact closely with the host the pods are running on.

In such cases we can exempt the resources from the gatekeeper checks by adding annotations to the resources. I've been able to add them to the pod configuration using the podAnnotation key, however I cannot add them to the daemonset, and therefore the deployment of node-exporter is blocked.

```
warning: Upgrade "kube-prometheus-stack" failed: failed to create resource: admission webhook "validation.gatekeeper.sh" denied the request: 
[poddenyhostnetwork] DaemonSet/kube-prometheus-stack-prometheus-node-exporter: Pod allows for accessing the host network
[poddenyhostpid] DaemonSet/kube-prometheus-stack-prometheus-node-exporter: Pod allows for accessing the host PID namespace
```

### Describe the solution you'd like.

Make annotations for the daemonset configurable through the values file.

### Describe alternatives you've considered.

NONE

**Comment by rmvangun** [comment]
/remove-lifecycle stale

Also encountering this when using Polaris
