### ISSUE TITLE
[kube-prometheus-stack] Update Grafana to a newer version

### ISSUE THREAD

**Issue by martinbeentjes** [prometheus-community/helm-charts#2160]
### Is your feature request related to a problem ?

Today, Grafana 9 has been released. In the `kube-prometheus-stack` we are currently using Grafana 6. That is three major versions in difference. If we keep this gap growing, that will become a bigger problem and a bigger block of work.

https://github.com/prometheus-community/helm-charts/blob/ee360207bd134ead3c51828c5562e15226c3f149/charts/kube-prometheus-stack/Chart.yaml#L51-L54

### Describe the solution you'd like.

I'd like to take time to update the grafana dependency to a newer version, and attempt to fix any issues I encounter on the way. We can go forward to 8 or 9 immediately in one breaking change. Or do this in steps. I do not know what is a better approach for OSS.

### Describe alternatives you've considered.

NONE

**Comment by gazab** [comment]
That version refers to the chart version and for example chart version **6.29.11** points to version **8.5.3** of Grafana, which isn't that old at all.

Grafana haven't updated their own Helm charts for Grafana 9 yet. It should be simple task to bump the chart version for kube-prometheus-stack once they do.

**Comment by martinbeentjes** [comment]
I did read that wrong again, that clears it up. Thanks a lot for pointing this out. I will close this issue as a won't fix as it is not that big of a problem.
