### ISSUE TITLE
[kube-prometheus-stack/] Grafana dashboards: Configurable interval and intervalFactor

### ISSUE THREAD

**Issue by StianOvrevage** [prometheus-community/helm-charts#2176]
### Is your feature request related to a problem ?

We use the standard included dashboards from https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14 a lot.

However, many of them have hardcoded `interval` ( https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml#L53 ) and `intervalFactor` ( https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-cluster.yaml#L87 ).

The default scrape interval is 30s and we have increased scraping to every 10s, like I guess many others have.

The problem then is that to be able to actually get the full resolution in graphs we first need to make dashboards editable, and then adjust both the interval and intervalFactor on each dashboard and panel.

Apart from being a lot of work most of the people in our org that uses these dashboards are probably not even aware that these settings exist, and are limiting the quality/resolution of the graphs they are looking at.

I'm not sure why some of the dashboards have 1m minimum interval and 1/2 resolution, but I'm sure someone has decided it's a good default. It would however be great to be able to configure and override this for those who are willing and able to live with the trade offs.

There is also the issue if doing this manually to always go in and update and fix across environments and updates. So I'm never really sure I can trust the dashboards to be "true" (that is, not aggregating more than necessary).

### Describe the solution you'd like.

Optionally remove `"interval": "1m",` and `"intervalFactor": 2,` from generated dashboards or at least be able to override them on installation.

### Describe alternatives you've considered.

I've created a hacky script that templates the chart and removes these lines from the generated ConfigMaps:

```
# Tool to patch default dashboards from the `kube-prometheus-stack` Helm chart to increase resolution
# Dashboards come from here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14
# But many of them have hardcoded 1 minute minimum interval as well as a resolution of 1/2
# 
# Usage:
# 
# Generate templated files from the chart:
#   helm template promstack --namespace monitoring prometheus-community/kube-prometheus-stack --output-dir generated
# Run this script:
#   ./patch-dashboards.sh
# Apply the patched dashboard ConfigMaps:
#   kubectl apply -n monitoring -f generated/kube-prometheus-stack/templates/grafana/dashboards-1.14/patched
# Cleanup templated files:
#   rm -rf generated
# 
# 
# Optionally disable the installation of dashboards from the original helm chart by passing this to `helm` on installation:
#   grafana.defaultDashboardsEnabled=false
# 

DASHBOARD_DIR=generated/kube-prometheus-stack/templates/grafana/dashboards-1.14

cd $DASHBOARD_DIR
mkdir -p patched
pwd

for file in *; do

  echo $file
  cat $file | grep -v '\"interval\": \"1m\",' | grep -v '\"intervalFactor\":'  > patched/$file

done
```

But ideally we would be able to do without this :)

**Comment by StianOvrevage** [comment]
Bump

**Comment by towolf** [comment]
Just so you don't feel alone, I have the same pet peeve.

The source of this default is here: https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/a6afee826e00e0b73059a21ac700f0a039a586de

When you recompile the dashboards yourself, you can override them, but in the chart, they come precompiled, with hard-coded defaults.

`intervalFactor=2` is a Grafana default, I think.

**Comment by jordo** [comment]
+1 to have this configurable in the chart, or at least configured to what prometheus `scrapeInterval` is...
