### ISSUE TITLE
[kube-state-metrics] some metrics appear to be duplicated

### ISSUE THREAD

**Issue by tomsucho** [prometheus-community/helm-charts#2181]
### Describe the bug a clear and concise description of what the bug is.

Hello,

getting duplicate like metrics, e.g. some labels are a bit different but it is one and the same thing:
- kube_daemonset_status_number_ready{app_kubernetes_io_component="metrics", app_kubernetes_io_instance="prometheus", app_kubernetes_io_managed_by="Helm", app_kubernetes_io_name="kube-state-metrics", app_kubernetes_io_part_of="kube-state-metrics", app_kubernetes_io_version="2.3.0", daemonset="fluent-bit", deployment_level="cluster_overlays", helm_sh_chart="kube-state-metrics-4.5.0", instance="10.0.67.200:8080", job="kubernetes-service-endpoints", kubernetes_name="prometheus-kube-state-metrics", kubernetes_namespace="forge", kubernetes_node="ip-10-0-67-143.eu-west-1.compute.internal", namespace="fluent-bit", release="prometheus", team_owner="forge"}
- kube_daemonset_status_number_ready{container="kube-state-metrics", daemonset="fluent-bit", endpoint="http", instance="10.0.67.200:8080", job="kube-state-metrics", namespace="fluent-bit", pod="prometheus-kube-state-metrics-795b7f97bf-fqtrd", service="prometheus-kube-state-metrics"}

the latter one has endpoint="http" and pod="prometheus-kube-state-metrics-795b7f97bf-fqtrd" and I think is result of a serviceMonitor that we got configured for it, but wonder why this job="kubernetes-service-endpoints" gets to scrape the endpoints in addition to the job="kube-state-metrics" since in Prometheus cfg we got the below, and the endpoints are not having prometheus.io/scrape: "true" annotation on them.
```- job_name: kubernetes-service-endpoints
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
```

### What's your helm version?

v3.7.1

### What's your kubectl version?

v1.21.12

### Which chart?

kube-state-metrics

### What's the chart version?

kube-state-metrics-4.5.0

### What happened?

Two endpoints are defined in the servicemonitor for kube-state-metrics. Based on my observations it results in duplicating the metrics.

### What you expected to happen?

kube-state-metrics not being duplicated.

### How to reproduce it?

deploy and check metric provided by kube-state-metrics example the ones that start with kube_*

### Enter the command that you execute and failing/misfunctioning.

NA

**Comment by ognjenVlad** [comment]
I am having the same issue, kube-state-metrics-4.7.0

**Comment by ognjenVlad** [comment]
@tomsucho `kube-state-metrics.prometheus.monitor.enabled = false` fixed it for me, removed the kube-state-metrics job

**Comment by cebidhem** [comment]
Hi,

I'm experiencing the same thing, but it's not really a duplication. You can see the `job` label being different, one is `"kubernetes-service-endpoints"` and the other is `"kube-state-metrics"`, indicating those metrics are actually scraped twice.

You should look into your configurations if you have an `additionalScrapeConfigs` defined for `kubernetes-service-endpoints`, and if not in your config, you can also check in Prometheus UI in the Configuration section.

For me, it was a legacy scrape config we used to have before using the operator, that we didn't removed. And if you can't remove this configuration, you may instead add the job dimension in your queries (in Grafana or else).

**Comment by tomsucho** [comment]
@cebidhem yes, correct I had to remove the job `"kubernetes-service-endpoints"` to avoid this, but my original question was why it was scraping pods that didn't even have `prometheus.io/scrape: true`. Also it wasn't scarping all the pods, only node-exporter and kube-state-metrics pod, resulting in having 2 sets of those with diff labels, including the job label of course. But anyways, removing the job `"kubernetes-service-endpoints"` didn't seem to cause we lost anything, so looks like it was just there redundant, tho it should not be scraping anything..

**Comment by Jaypers** [comment]
For us the problem was having the `prometheus.io/scrape: "true"` annotation in the `kube-state-metrics` service.
We already had a scrape config for `kube-state-metrics` and this annotation caused `kubernetes-service-endpoints` to scrape `kube-state-metrics` again.

**Comment by bimax** [comment]
> For us the problem was having the `prometheus.io/scrape: "true"` annotation in the `kube-state-metrics` service.

I see the same issue in my case. We have 2 replicas for kube-state-metrics, both of the exposing the same set of metrics :8080/metrics and they are added for prometheus scrape config as a ServiceMonitor CRD:
```
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/instance: kps
      app.kubernetes.io/name: kube-state-metrics
```
and the service kps-kube-state-metrics has annotation:
```
  annotations:
    meta.helm.sh/release-name: kps
    meta.helm.sh/release-namespace: monitoring-system
    prometheus.io/scrape: "true"
```
So, it's all looks logica apart of the fact that metrics are being duplicated with the factor of `replicas` with exactly same set of labels except `pod` and `instance`.
I do not feel it's the right behaviour but have no idea how to fix it.

Thanks.

**Comment by Jaypers** [comment]
If you remove `prometheus.io/scrape: "true"` does it work as expected?

**Comment by bimax** [comment]
Actually I found another solution for it. Which looks better.
I have added 'ScrapeConfig' resource definition for prometheus to pull the metrics from the kube-state-metrics service rather than having it added as ServiceMonitor. This way we can scale kube-state-metrics replicase as much as we need and let prometheus scrape it just from one of the instance rather than pulling duplicates from each of the pod (when using ServiceMonitor).
And the annotation: prometheus.io/scrape: "true" is still in place.
Here is example of scrape config:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  creationTimestamp: "2025-02-19T12:14:51Z"
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: monitoring-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
    prometheus: monitoring-system
  name: kube-state-metrics-cluster-metrics
  namespace: monitoring-system
  resourceVersion: "621533171"
  uid: f9008c37-05a5-41c5-9a24-5ef6b4c319a9
spec:
  honorLabels: true
  jobName: scrapeconfig-kube-state-metrics
  staticConfigs:
  - targets:
    - kps-kube-state-metrics.monitoring-system.svc:8080
```
