### ISSUE TITLE
[kube-prometheus-stack] CPU Utilisation "No Data" due to bad recording rules

### ISSUE THREAD

**Issue by knack-roque** [prometheus-community/helm-charts#2182]
### Describe the bug a clear and concise description of what the bug is.

The recording rule to create cluster:node_cpu:ratio_rate5m drops the `cluster` label from the resultant metric. This causes some grafana dashboard panels to report No Data as they're searching for `cluster="$cluster'`.

### What's your helm version?

version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

### What's your kubectl version?

v1.20.10

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.0.1

### What happened?

Dashboards are showing No Data for General/Kubernetes/Compute Resources/Cluster: CPU Utilisation.

### What you expected to happen?

To see CPU Utilisation

### How to reproduce it?

Install kube-prometheus-stack 36.0.1 with node-exporter (we're using the puppetdb exporter but the issue is at the recording rules, not the source) and grafana enabled.

### Enter the command that you execute and failing/misfunctioning.

Not a command, but simple looking at the grafana dashboards

### Anything else we need to know?

Pretty sure if the recording rule is changed to below it will work
* Current
  * rule: `sum(rate(node_cpu_seconds_total{job="node-exporter",mode!="idle",mode!="iowait",mode!="steal"}[5m])) / count(sum by(cluster, instance, cpu) (node_cpu_seconds_total{job="node-exporter"}))`
  * result: {} 0.10346337677179257
* Recommendation:
  * rule: `sum by (cluster) (rate(node_cpu_seconds_total{job="node-exporter",mode!="idle",mode!="iowait",mode!="steal"}[5m])) / count by (cluster) (sum by(cluster, instance, cpu) (node_cpu_seconds_total{job="node-exporter"}))`
  * result: {cluster="cluster"} 0.09313381330561242

**Comment by travnewmatic** [comment]
i think i'm experiencing something similar

nuked my kube-prometheus-stack and started from scratch just to be sure

v36.0.3 of the helm chart

nothing for cpu, memory, networking, or storage showing in the default dashboards

interestingly, the 'headlines' section at the top of 'compute resources' does show percentages.

otherwise, its mostly 'no data' in the panels.

**Comment by jfklingler** [comment]
This is still a problem with chart version 41.7.0

**Comment by akash123-eng** [comment]
why this issue is closed ?
i am also getting same issue

**Comment by andrejvanderzee** [comment]
Seeing the same issue with chart 41.7.4

**Comment by jeremydescamps** [comment]
I also have this behavior !

**Comment by maxpain** [comment]
The same problem

**Comment by alter** [comment]
same this here 51.4.0

**Comment by zbikmarc** [comment]
Looks like same problem with 55.5.1 on default values (only change I made is to use PVC and enabled ingress)

**Comment by bashtian-fr** [comment]
same problem with prometheus chart "25.28.0" node_cpu_seconds_total no data with node-exporter

**Comment by LeonOlbrueck** [comment]
The problem for me was that i configured a custom ruleSelector for prometheus in the values.yaml, so the default rules from the chart did not get processed by prometheus. Reverted the ruleSelector back to default and everything worked again. Chart Version 77.12.0
