### ISSUE TITLE
[kube-prometheus-stack] Add ability to inject custom CAs - specifically for Thanos Sidecar

### ISSUE THREAD

**Issue by MarkusBauerBE** [prometheus-community/helm-charts#2185]
### Is your feature request related to a problem ?

Right now self-hosted S3 services such as MinIO are not trusted by the Thanos sidecar when using a private CA. Injecting a custom CA certificate is not possible without touching or modifying the actual deployments. The helm chart doesn't currently allow for any injection of CA certs as far as I could tell - if so documentation for this is lacking.

[This](https://github.com/thanos-io/thanos/pull/4946) PR shows that this feature was implemented in Thanos itself and it theoretically should be as simple as adding a volume mount. 

### Describe the solution you'd like.

Ideally there'd be a way to either provide a secret or configmap to the prometheus or thanossidecar container that already mounts in the proper place. 
If that is deemed to unflexible, then at least a way to mount secrets or configmaps with custom paths should be parsed through.

### Describe alternatives you've considered.

From what I was able to gather an alternative is to set an environment variable that contains a path to the ca-bundle file. Setting env variables is however also not possible via the helm chart.

**Comment by MarkusBauerBE** [comment]
Ping

**Comment by cowjen01** [comment]
The same issue here.
