### ISSUE TITLE
[prometheus-postgres-exporter] Wrong port in NOTES.txt

### ISSUE THREAD

**Issue by bisgardo** [prometheus-community/helm-charts#2187]
In in the ClusterIP case, the suggested command forwards to the pod but uses the service's port (80) instead of the pod's (9187).

https://github.com/prometheus-community/helm-charts/blob/c4ff06ba2364f86ee3dad867d9c1b2e947151743/charts/prometheus-postgres-exporter/templates/NOTES.txt#L14

I believe the correct solution is to forward to port 9187 or alternatively actually forward to the service.

**Comment by monotek** [comment]
Would you mind to create a PR with a fix?
