### ISSUE TITLE
[kube-state-metrics] Allow volume-mounts (relates to `--custom-resource-state-config-file`)

### ISSUE THREAD

**Issue by withnale** [prometheus-community/helm-charts#2190]
### Is your feature request related to a problem ?

With the new custom resources support in kube-state-metrics we'd like to try this out in sustainable manner

### Describe the solution you'd like.

Ultimately, it might be nice to have an explicit helm definition of the custom-resources state file, and to be managed in helm values.

However, since this is still an experimental feature this may be jumping the gun a little. Right now, probably the appropriate solution would be to allow additional volumes and volume mounts to be specified in helm values.

### Describe alternatives you've considered.

At present the inlining of the custom resources (via `--custom-resource-state-config`) may be possible, but this seems very unwieldy to pass large config files in as embedded command line arguments.

**Comment by aleksandr-orca** [comment]
Hello guys, is there any plans on implementing this?
