### ISSUE TITLE
[kube-prometheus-stack] Cryptic grafana chart error upgrading from 32.2.0 to 36.2.0

### ISSUE THREAD

**Issue by llamahunter** [prometheus-community/helm-charts#2204]
### Describe the bug a clear and concise description of what the bug is.

Did the manual steps of applying the new CRDs. Just updating the helm chart to the latest. Getting a cryptic error from the grafana subchart.

```
Error: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:49:10: executing "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include "grafana.pod" .>: error calling include: template: kube-prometheus-stack/charts/grafana/templates/_pod.tpl:426:25: executing "grafana.pod" at <.subPath>: wrong type for value; expected string; got interface {}
```

I am setting `grafana.extraConfigmapMounts` to include a custom ssl ca chain.  There does appear to have been a syntax bug in the grafana chart 6.31.0 that was fixed in 6.31.1, but the kube-prometheus-stack chart appears to use 6.31.*, so should be picking up the fix? 

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.0

### What happened?

Error from grafana subchart on upgrade.

### What you expected to happen?

No errors

### How to reproduce it?

apply the helm chart using same configs as before

### Enter the changed values of values.yaml?

there are many changed value, some via terraform, some via a yaml file. 

### Enter the command that you execute and failing/misfunctioning.

terraform apply (using terraform helm provider)

**Comment by llamahunter** [comment]
Had to roll back to 35.1.0 to find a working version with the grafana subchart setup including grafana.extraConfigMounts

**Comment by llamahunter** [comment]
seems to require explicitly setting the subPath value to an empty string:

```
  extraConfigmapMounts:
    - name: <name>
      mountPath: <mount-path>
      configMap: <configmap>
      readOnly: true
      subPath: ''  
```

**Comment by maxemann96** [comment]
Is this intentional behaviour to use the workaround described in https://github.com/prometheus-community/helm-charts/issues/2204#issuecomment-1200316833 or should this reopened?
