### ISSUE TITLE
[prometheus-blackbox-exporter] Incorrect NetworkPolicy behavior

### ISSUE THREAD

**Issue by verdel** [prometheus-community/helm-charts#221]
**Describe the bug**
If you use the following options in `values.yaml`:
```yaml
## Network policy for chart
networkPolicy:
  # Enable network policy and allow access from anywhere
  enabled: true
  # Limit access only from monitoring namespace
  allowMonitoringNamespace: true
```
and don't create a label `name` for monitoring namespace beforehand, the selection rule in Network Policy won't work.

The `namespaceSelector` applies to labels on a Namespace, not fields on a Namespace.
There is a discussion about this in the kubernetes repository - https://github.com/kubernetes/kubernetes/issues/88253

I think it's worth describing this in more detail in the comments to the options in `values.yaml`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"dirty", GoVersion:"go1.14.3"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-community/prometheus-blackbox-exporter
**Which version of the chart**:
4.8.0

**What happened**:
Traffic to the pod from monitoring namespace does not pass

**What you expected to happen**:
Traffic to the pod is allowed within monitoring namespace

**How to reproduce it** (as minimally and precisely as possible):
```console
helm install -n monitoring prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter --version 4.8.0 --values values.yaml 

kubectl run -n monitoring busybox --rm -ti --image=busybox -- /bin/sh

wget --timeout=1 http://prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115/probe
Connecting to prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115 (ip:9115)
wget: download timed out
```

**Comment by monotek** [comment]
Would you mind to create an pr?

**Comment by verdel** [comment]
I will try to make changes to the documentation and make a PR in the next few days
