### ISSUE TITLE
helm install  prometheus-community/prometheus-operator  "error getting secret"

### ISSUE THREAD

**Issue by icexk** [prometheus-community/helm-charts#2214]
### Describe the bug a clear and concise description of what the bug is.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/43198678/176606732-98746759-b342-4d8a-b580-998890ed4015.png">

 helm install -name prometheus-operator  prometheus-community/prometheus-operator -n monitoring

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/43198678/176607471-bb8bdbea-4a32-4132-9fb1-171403b64784.png">
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/43198678/176607532-3ccfc984-522d-4a05-adf0-44df9cf1c190.png">

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

 prometheus-community/prometheus-operator 

### What's the chart version?

9.3.2

### What happened?

{"err":"Get https://10.9.0.1:443/api/v1/namespaces/monitoring/secrets/prometheus-operator-admission: dial tcp 10.9.0.1:443: i/o timeout","level":"fatal","msg":"error getting secret","source":"k8s/k8s.go:104","time":"2022-06-30T06:09:45Z"}

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/43198678/176605556-08e3c449-21fe-431c-acbc-70e5176be731.png">

### Enter the command that you execute and failing/misfunctioning.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/43198678/176606457-2e170a93-771b-4658-af58-a474663adba4.png">

**Comment by monotek** [comment]
Please fix the issu title.
Also use the latest version of the chart please.

**Comment by icexk** [comment]
I use the latest charts
 helm install -name prometheus-operator  prometheus-community/prometheus-operator --version 9.3.2 -n monitoring
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/43198678/176614591-72eb9342-2e84-4256-a129-333ab9f97596.png">

**Comment by icexk** [comment]
I now install  kube-prometheus-stack version is: 36.2.0
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/43198678/176651275-f3f924c5-9e36-4a0c-8e4d-c41f83acc05b.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/43198678/176650598-80a56bc0-51e5-4ad5-938d-eca61c0e1e72.png">

**Comment by robinzoncruzo** [comment]
@icexk have you solved this issue?

**Comment by robinzoncruzo** [comment]
I solved the issue for me. I've had manually configured INPUT chain with DROP rule on one of cluster worker hosts. After deletion of this rule, everything worked fine. But it's still puzzle for me, cause host with DROP rule wasn't master with API pod.

**Comment by icexk** [comment]
I didn't solve the problem
