### ISSUE TITLE
[prometheus-kube-stack] Fresh install via helmfile fails due to crd

### ISSUE THREAD

**Issue by Dunge** [prometheus-community/helm-charts#2217]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to set up an helmfile structure that would includes prometheus-kube-stack instead of via helm directly in order to have some declarative infrastructure of all my releases that I can re-use.

This is a snippet of my helmfile:
```
repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  
releases:
- name: kube-prometheus-stack
  namespace: default
  chart: prometheus-community/kube-prometheus-stack
  labels:
    name: kube-prometheus-stack
  version: ~36.2.0
```

It end up with this error:
> Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

I've read a few posts from 2018 that said we needed to manually install the crd before, but seems like this was fixed. I saw other posts (and the official upgrade guide) saying we need to manually update them if we have old versions, but I can confirm I did not have them installed before (fresh cluster):
```
>kubectl get crd
No resources found
```

Thing is, if I then try to install it "normally" via helm, it works!
```
>helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack
NAME: kube-prometheus-stack
LAST DEPLOYED: Thu Jun 30 19:10:49 2022
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=kube-prometheus-stack"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.
```

So I assume the actual helm chart is installing the crd correctly, but helmfile fails at the `diff` operation when the crd aren't installed beforehand.

Any way do that so we can have the installation working without installing this chart independently from the rest?

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

36.2.0

### Enter the changed values of values.yaml?

none

### Enter the command that you execute and failing/misfunctioning.

helmfile apply

**Comment by monotek** [comment]
Likely not a problem the chart can solve.
If the crd can be applied it's likely that helmfile does this via kubectl apply in client side mode.
This will not work, as the CRD is to big for that. 
See Readme of the chart. kube-prometheus-stack CRDs needs to be applied with server side mode.

**Comment by Dunge** [comment]
I found this issue in the helmfile repo about it:

roboll/helmfile#1353 

And the related resolution which recommend adding `disableValidationOnInstall: true` on the promotheus stack release. I haven't tested it yet, but I assume that will do.
