### ISSUE TITLE
[prometheus] CPU usage and Memory usage metrics missing

### ISSUE THREAD

**Issue by marcofranssen** [prometheus-community/helm-charts#2218]
### Describe the bug a clear and concise description of what the bug is.

The CPU usage and memory usage metrics are missing. We have installed the helm chart with all the default values.

```shell
helm install --namespace prometheus prometheus-community/prometheus --version 15.10.1
```

See following screenshot of Lens that shows these metrics are missing.

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/694733/176845171-866bc588-4f26-4626-984f-4745bda69193.png">

### What's your helm version?

v3.9.0

### What's your kubectl version?

1.23.3

### Which chart?

prometheus

### What's the chart version?

15.10.1

### What happened?

CPU usage and CPU memory not available.

### What you expected to happen?

The metrics are available.

### How to reproduce it?

- Install the helm chart
  
  ```shell
  helm install --namespace prometheus prometheus-community/prometheus --version 15.10.1
  ```

- Open Lens
- See at the cluster tab the usage metrics are missing.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Installation itself succeeds, but no usage metrics are available.

### Anything else we need to know?

We did also install https://kubernetes-sigs.github.io/metrics-server/ with the default values.
Our cluster nodes are provisioned via https://karpenter.sh

**Comment by reefland** [comment]
I had similar issue that I started asking about https://github.com/lensapp/lens/issues/5660#issuecomment-1159155466

**Comment by marcofranssen** [comment]
An important note might be that we are running on EKS. Which might also be the cause of not having those metrics.

**Comment by gjkamstra** [comment]
Metrics are actually there, but with the wrong label. I submitted  #2321 for the same.
