### ISSUE TITLE
[kube-prometheus-stack] How to configure kube-state-metrics relabel drop action

### ISSUE THREAD

**Issue by msharma24** [prometheus-community/helm-charts#2220]
### Is your feature request related to a problem ?

We are ingesting the  prometheus metrics to AWS Managed Prometheus Service (AMP)  and looking to figure out  how can we drop the `kube_*_*`  metrics from ingesting  into  AMP  to optimise the Cloud Provider Cost 

We would like to drop the following metrics:- 
![image](https://user-images.githubusercontent.com/1450919/177018006-1261253a-0b37-4f7f-a99d-e1bc1cff2f7f.png)

We have tried the following configuration in the `values.yaml` to no avail—Please advise if you have a solution to this problem.

```yaml
kube-state-metrics:
  metricRelabelings:
    - action: drop
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      sourceLabels: [__name__]
  relabelings:
    - action: drop
      regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      sourceLabels: [__name__]




### Describe the solution you'd like.

Helm chart configuration for kube-state-metrics allow and denylist.

### Describe alternatives you've considered.

`None`

### Additional context.

_No response_

**Comment by danielstankw** [comment]
@msharma24 I know this is super old, but mind sharing how you solved it ?
