### ISSUE TITLE
[prometheus] Broken configurations for alert manager probeHeaders

### ISSUE THREAD

**Issue by RomanBats** [prometheus-community/helm-charts#2228]
### Describe the bug a clear and concise description of what the bug is.

It looks like that [this commit](https://github.com/prometheus-community/helm-charts/commit/5a53f70d16fb22f7f817b901a7d8c6efb00a1da4) (@snk-actian) has broken alert manager probeHeaders configurations.
It should use 
`{{- if .Values.alertmanager.probeHeaders }}`
instead of 
`{{- with .Values.server.probeHeaders }}`

### What's your helm version?

version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}

### What's your kubectl version?

version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.10.2

### Enter the command that you execute and failing/misfunctioning.

helm install release prometheus-comunity/prometheus --version 15.10.2 --values values.yaml

**Comment by snk-actian** [comment]
Sincere apologies. My bad typo... Fix is on its route..
