### ISSUE TITLE
Exporters' containerPort values alignment

### ISSUE THREAD

**Issue by pburgisser** [prometheus-community/helm-charts#223]
I've been adding the possibility extra containers to the pushgateway and the blackbox exporter so I could authenticate access with the oAuthProxy container (especially on OpenShift. I noticed that the way the container port is assigned is always different: In pushgateway, the container port is hard coded [1], in consul-exporter the container port is using the port set in the service values [2] and in the cloudwatch-export has a dedicated value [3].

I would suggest to align these parameters as the following:

- We allow the user to specify the container port with a value like `$.Values.containerPort`
- We allow the user to specify the target port of the service:
<pre><code>service:
    port: 9115
    targetPort: 9116</code></pre>

Do you have other suggestion?

I would align with parameters with pleasure if you see any interest into it?

[1] https://github.com/prometheus-community/helm-charts/blob/1d66906e0f792372e0f76e7e058a5dd507778fe4/charts/prometheus-pushgateway/templates/deployment.yaml#L40
[2] https://github.com/prometheus-community/helm-charts/blob/1d66906e0f792372e0f76e7e058a5dd507778fe4/charts/prometheus-consul-exporter/templates/deployment.yaml#L38
[3] https://github.com/prometheus-community/helm-charts/blob/1d66906e0f792372e0f76e7e058a5dd507778fe4/charts/prometheus-cloudwatch-exporter/templates/deployment.yaml#L72

**Comment by pburgisser** [comment]
cc: @monotek @gianrubio

**Comment by monotek** [comment]
Not sure if we want to have it the same way everywhere. Could mean breaking change /new major version for some charts. 

@scottrigby @torstenwalter 

Thoughts? Imho if we start with a standard it should apply to all of the charts. Not sure if it's worth it.

**Comment by torstenwalter** [comment]
If you really want to align ports one could try:


````
oldPort: 8080
service
  port: "{{ .Values.oldPort }}
```

And use it in templates with tpl function. 

```
{{ tpl .Values.servicePort . }} 
```

https://helm.sh/docs/howto/charts_tips_and_tricks/

This would make it possible to introduce it as non breaking change.
People could override the port using the new value already.

One could even render a message in NOTES.txt that service.port should be used to specify a port in case it does not contain a numeric value and oldPort is not the default value.

During the next major version bump the compatibility mode could be removed.

If that's worth the effort? I really don't know.

Also helm chart best practices do not prescribe how ports should be defined. https://helm.sh/docs/chart_best_practices/values/ contain some examples, but do not recommend something directly. So one would need to check what most charts are using and come up with a proposal.
