### ISSUE TITLE
[kube-prometheus-stack] additionalScrapeConfig for clickhouse monitoring

### ISSUE THREAD

**Issue by xgengsjc2021** [prometheus-community/helm-charts#2236]
Hi followed the link below to configure prometheus to monitor clickhouse

https://github.com/Altinity/clickhouse-operator/blob/eb3fc4e28514d0d6ea25a40698205b02949bcf9d/docs/prometheus_setup.md#prometheus-already-available

But not sure how we configure on prometheus side. I tried to add **additionalScrapeConfigs** but it did not work as expected. 
My prometheus is in monitoring ns. The clickhouse-operator is in the kube-system. 
Based on the link above, looks like we do not need to configure service monitor. how can I configure prometheus to point to the operator to collect metrics?

**Comment by zozo6015** [comment]
Have the same issues. I have tried adding the label monitoring: true to the clickhouse-operator service but did nto changed anything.
