### ISSUE TITLE
[kube-prometheus-stack] etcd rules can no longer be updated using python script

### ISSUE THREAD

**Issue by gmintoco** [prometheus-community/helm-charts#225]
**Describe the bug**
When attempting to update the etcd rules with the instructions as described here:  https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack

The script returns:
`Generating rules from https://raw.githubusercontent.com/etcd-io/etcd/master/Documentation/op-guide/etcd3_alert.rules.yml
Skipping the file, response code 404 not equals 200`

This is because etcd upstream no longer publishes the file `etcd3_alert.rules.yml` and instead provides a jsonnet mixin.

I think the script will need to be modified/or something else to process the alerts.

**Version of Helm and Kubernetes**:

**Which chart**:  kube-prometheus-stack
**Which version of the chart**: v10.1.0

**What happened**: Did not sync updated rules

**What you expected to happen**: Rules updated

**How to reproduce it** (as minimally and precisely as possible):
1) Clone repo
2) Run prometheus rule update script in hack/

**Comment by aiyengar2** [comment]
Related to https://github.com/rancher/rancher/issues/29939, since the `kube-prometheus-stack` chart has not pulled in the latest changes to the etcd rules, including the fix in https://github.com/etcd-io/etcd/pull/12122.

**Comment by invidian** [comment]
Can we reopen?

**Comment by gmintoco** [comment]
Yeah can we reopen this one, seems to still be an issue

**Comment by allenporter** [comment]
Yes, definitely still an issue. https://github.com/rancher/rancher/issues/29939 seems to describe the current state pretty well. As improvements such as https://github.com/etcd-io/etcd/pull/13127 roll into the etcd rules, the kube-prometheus-stack rules are out of date. The newer approach of mixing in rules from other projecs seems very different, using jsonnet.

**Comment by invidian** [comment]
This issue has been resolved in https://github.com/prometheus-community/helm-charts/pull/665, it seems like a duplicate of #213.
