### ISSUE TITLE
Secure Prometheus Server With Basic Password Authentication

### ISSUE THREAD

**Issue by rajivram89** [prometheus-community/helm-charts#2250]
Hi Team,

I am trying to enable basic authentication to the Prometheus application. I am following the steps as per the Prometheus Documentation [https://prometheus.io/docs/guides/basic-auth/].  I have configured the web-config.xml as per the documentation.

Below is the content of web-config.xml:

basic_auth_users:
         admin: "##$#$#$#$#$#$#$"

But when I am validating the configuration, it fails and throws me the below error:

[root@Promethus-server prometheus-2.17.0-rc.0.linux-amd64]# ./promtool check config /etc/prometheus/web-config.yml
Checking /etc/prometheus/web-config.yml
  FAILED: parsing YAML file /etc/prometheus/web-config.yml: yaml: unmarshal errors:
  line 1: field basic_auth_users not found in type config.plain

Can someone help me on this?

Regards
Rajiv

**Comment by chegde20121** [comment]
Even I am facing same issue

**Comment by zeritti** [comment]
As far as I know, `promtool check config` does not understand web config's scheme. You'd need to use `promtool check web-config` against a web config file but this argument has been available since ~2.24. Release 2.17 is quite outdated.
