### ISSUE TITLE
[prometheus-kube-stack] failed to update status subresource: prometheuses.monitoring.coreos.com

### ISSUE THREAD

**Issue by MariusMiricaBE** [prometheus-community/helm-charts#2272]
### Describe the bug a clear and concise description of what the bug is.

The logs of the Prometheus operator are full of messages like this: 

```
level=error ts=2022-07-13T07:34:26.62492094Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/prometheus-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"prometheus-kube-prometheus-prometheus\" not found"
```

### What's your helm version?

v3.8.1

### What's your kubectl version?

v1.23.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

37.0.0

### What happened?

The logs of the Prometheus operator are full of messages like this: 

``` level=error ts=2022-07-13T07:34:26.62492094Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"monitoring/prometheus-kube-prometheus-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"prometheus-kube-prometheus-prometheus\" not found"
```

### What you expected to happen?

Not having the mentioned error in the logs. 

### How to reproduce it?

kubectl logs prometheus-kube-prometheus-operator-784d699b98-27k6w

### Enter the changed values of values.yaml?

none

### Enter the command that you execute and failing/misfunctioning.

kubectl logs prometheus-kube-prometheus-operator-784d699b98-27k6w

**Comment by arousseau-coveo** [comment]
Got the same while upgrading from 28.0.2 to latest (39.6.0)
Seems like the chart is not modifying old serviceAccount and old role.
On the service account I still have the old label applied: 
`chart=kube-prometheus-stack-28.0.2`
