### ISSUE TITLE
[kube-prometheus-stack] Thanos sidecar metrics incompatible with default thanos sidecar dashboard

### ISSUE THREAD

**Issue by rouke-broersma** [prometheus-community/helm-charts#2275]
### Describe the bug a clear and concise description of what the bug is.

Thanos provides a default grafana dashboard for all their products. See: [dashboard json](https://github.com/thanos-io/thanos/blob/v0.25.2/examples/dashboards/sidecar.json#L1462 )

These all work fine except when used with the thanos sidecar from kube-prometheus-stack. This is because the job label filter in the thanos dashboard is different from the job label as discovered from the kube-prometheus-stack deployment.

The dashboard looks for a job label in the format of `.*thanos-sidecar.*` however the job label as discovered from the kube-prometheus-stack deployment is `prometheus-stack-kube-prom-thanos-discovery`. This doesn't match and for that reason the dashboard does not find any metrics.

This was attempted to be fixed in #2216 and #2244 however the fix was insufficient.

I believe that the correct fix is renaming the thanos sidecar service name, as I believe that is where the job label is generated from (I am not that proficient yet with prometheus so I am not 100% but that is easy to find out), however this would be a pretty major breaking change and I don't know if this is acceptable to the project.

### What's your helm version?

v3.8.1+g5cb9af4

### What's your kubectl version?

v0.23.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

37.2.0

### What happened?

Grafana dashboard for thanos sidecar shows 'no data'.

### What you expected to happen?

Grafana dashboard for thanos sidecar shows data.

### How to reproduce it?

Install and configure kube-prometheus-stack with thanos sidecar configured. Enable servicemonitor for thanos sidecar. Enable and configure grafana to use thanos as source. Import thanos sidecar grafana dashboard in grafana.

### Enter the changed values of values.yaml?

```yaml
grafana:
  sidecar:
      datasources:
        url: http://prometheus-stack-thanos-query:9090
prometheus:
    thanosService:
      enabled: true
    thanosServiceMonitor:
      enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

Chart deployment performed by argocd:
helm template prometheus-stack kube-prometheus-stack --version 37.2.0 --values values.yaml
kubectl apply -f .

### Anything else we need to know?

_Originally posted by @rouke-broersma in https://github.com/prometheus-community/helm-charts/issues/2244#issuecomment-1180236245_

**Comment by rouke-broersma** [comment]
Not stale

**Comment by aslafy-z** [comment]
Not stale

**Comment by aslafy-z** [comment]
Not sale

**Comment by aslafy-z** [comment]
Not stale

**Comment by TitanRob16** [comment]
I'm experiencing the same thing. Has no-one come up with an answer?

**Comment by aslafy-z** [comment]
@rouke-broersma Can you re-open the issue please?

**Comment by rouke-broersma** [comment]
@aslafy-z i don't think I have permission to do this
