### ISSUE TITLE
labeling centeral monitoring in kube-promethe-stack chart

### ISSUE THREAD

**Issue by mak241265** [prometheus-community/helm-charts#2287]
### Is your feature request related to a problem ?

currently i have two kubernetes cluster with kube prometheus stack installed on them, i also set the parameter externalLabels on them (cluster: cluster1,cluster:cluster2).
i have another kubernetes cluster which is going to be used as centeral monitoring.in this cluster kube prometheus stack is also installed and the parameter multicluster is activated on this cluster and with federation i scrap the metric from cluster1 and cluster2 so in grafana dashboard i have the ability to monitor those two cluster.my problem is how can i chose the third cluster(centeral monitoring itself) to monitor as this cluster does not have any cluster label because externalLabels is only work for external system.

### Describe the solution you'd like.

Any new global parameter which can set a label for internal metrics

### Describe alternatives you've considered.

NONE

**Comment by nirmaldavis** [comment]
Is there any work around for this cluster label problem? As mentioned in problem description, this main cluster does not have any cluster label because externalLabels is only work for external system.
