### ISSUE TITLE
[prometheus] Prometheus in Agent Mode

### ISSUE THREAD

**Issue by nedl86** [prometheus-community/helm-charts#2290]
### Is your feature request related to a problem ?

Same problem as #1519 but for the `prometheus` chart. There are a lot of default values in the chart which conflict with Prometheus running in agent mode.

### Describe the solution you'd like.

It would be great to have the `prometheus` chart updated to work seamlessly with agent mode, perhaps even having specific configuration to generate configuration compatible with agent mode.

### Describe alternatives you've considered.

The `prometheus.yml` for agent mode is incredibly simple, so perhaps a separate template `values-agentmode.yaml` for agent mode could be created.

**Comment by phyber** [comment]
Not stale, still relevant.

**Comment by Momotoculteur** [comment]
Why this issue is closed ?
