### ISSUE TITLE
Add DCO check

### ISSUE THREAD

**Issue by torstenwalter** [prometheus-community/helm-charts#23]
## Status

- [x] Add DCO app to `scottrigby/prometheus-helm-charts`
- [x] Authorize and re-add app after transferring repo to `prometheus-community` (#11)

## Original issue
A simple approach is to install https://github.com/apps/dco

**Comment by scottrigby** [comment]
@torstenwalter Yes, in the helm org we use https://github.com/probot/dco. I can not seem to add integrations to my personal github repo but we should definitely add this after moving to the prometheus-community org in #11 

PS I saw there was an action https://github.com/marketplace/actions/dco-check but it doesn't seem to be widely used so I just put it off until after we transfer ownership.

**Comment by scottrigby** [comment]
Changed title to make sure we track this as a to-do instead of a question. Thanks!

**Comment by scottrigby** [comment]
I added a new project to track work that needs to be done after repo transfer, and added this issue as a to-do item https://github.com/scottrigby/prometheus-helm-charts/projects/2
