### ISSUE TITLE
[prometheus-statsd-exporter] re-point liveness/readiness probe endpoint  to '/health` 

### ISSUE THREAD

**Issue by makeittotop** [prometheus-community/helm-charts#2305]
### Is your feature request related to a problem ?

Using helm chart version `v0.22.1`.

Currently, the helm chart sets up the statsd-exporter deployment with the `liveness` / `readiness` probes configured to go to `/metrics` endpoint, however the web server does expose the `/health` api endpoint too.

This can potentially become a problem as I recently discovered. The `/metrics` endpoint _can_ get relatively unresponsive depending on the number of metrics it has to serve out at each request, which in turn depends up on the cache size at any given point in time, especially if the metrics expiration `TTL` is set relatively high.

In our case, there was a single instance deployment, with the `TTL` set to `12h` initially. With this setup, and a relatively higher volume of metrics flowing in, we noticed that the pod kept getting restarted every few hours as the readiness probe started failing. Investigating further I noticed that the chart sets up the  default  `liveness/readiness` probes path to  `/metrics`, with a timeout of `1s`, which is causing the probes to fail, leading to the pod restart. 

### Describe the solution you'd like.

In my opinion, the `liveness/readiness` probe path should be set to `/health` by default as 
* it serves the intended purpose, and is extremely lightweight. 
* secondly, as the `/metrics` endpoint is production, I'd rather not overload it with probes, especially given the default timeout in the chart is only `1s`.  
* seems to be the established pattern across `k8s`

### Describe alternatives you've considered.

Increasing the replica count to more than 1 better distribute the load, but eventually, the pods do get restarted once the metrics cache size becomes big, and the `/metrics` endpoint becomes too overloaded to respond to health probes in a timely manner.

**Comment by makeittotop** [comment]
Happy to make a PR request too. Please let me know.

**Comment by monotek** [comment]
Yes, please do :)

**Comment by makeittotop** [comment]
@scDisorder @monotek PR created. Please take a look when there is a chance. 
P.S. The reason I had to create a 2nd one was that there was an email mismatch in the DCO in the first one.
