### ISSUE TITLE
[kube-prometheus-stack] Thanos ruler recording rule evaluation failures on sharded prometheus

### ISSUE THREAD

**Issue by shahmed90** [prometheus-community/helm-charts#2306]
### Describe the bug a clear and concise description of what the bug is.

I am investigating using Thanos ruler to evaluate recording rules on sharded prometheus as a suggested solution in  #809 to avoid the miscalculated recording rules of a single shard (issue indicated in the mentioned issue #809)

Still after using Thanos ruler for the evaluation, Grafana dashboard is missing metrics about some pods (prometheus-shard-1 for example" tracing back to the [k8s-resources-pod.yaml](https://github.com/prometheus-community/helm-charts/blob/0c499de4929de524a8aea2d5e4bb5035b760eed5/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-pod.yaml#L100) the metric used is a rcording rule getting evaluated by ThanosRuler by using the correct label for it

### What's your helm version?

3.5.4

### What's your kubectl version?

v1.21

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.2.0

### What happened?

But still upon checking the evaluation of  `node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate` gives a result with less Pods than the expression for the recording rule itself, which gives missing pods on the relevant Grafana dashboard 
```
sum by (cluster, namespace, pod, container) (
          irate(container_cpu_usage_seconds_total{job="kubelet", metrics_path="/metrics/cadvisor", image!=""}[5m])
        ) * on (cluster, namespace, pod) group_left(node) topk by (cluster, namespace, pod) (
          1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```
you can only see for example representation of prometheus-shard-0 cpu usage (both replicas) in the querying of the expression but not the querying of recording rule itself

### What you expected to happen?

The expectation that both the recording role and its expression deliver the same amount of Pods (all of them) so it can be represented in the dashboard as if there no sharding happened before

### How to reproduce it?

use kube-prometheus-stack chart and enable thanos ruler to evaluate the recording rules included on the official chart

### Enter the changed values of values.yaml?

shards: 2

### Enter the command that you execute and failing/misfunctioning.

![image](https://user-images.githubusercontent.com/74175219/180957059-61424376-56f0-45e4-ada1-678c28f58ba0.png)
![image](https://user-images.githubusercontent.com/74175219/180957235-ce3c4393-539d-447b-b7e3-970ff4b46f72.png)

**Comment by shahmed90** [comment]
if anybody managed to use the prometheus sharding with grafana, his support would be helpful

**Comment by muzalevs** [comment]
I also struggled with missing data in Grafana due to Prometheus sharding. I didn't, however, observe described behavior after configuring rules in Thanos Ruler. In my case results from both recording rule and its expression were the same.

But having rules in Thanos Ruler is also a drawback because periodic evaluation is very expensive from traffic and CPU usage perspective. Similar problem was reported in Thanos project: https://github.com/thanos-io/thanos/issues/943

I wonder if it wouldn't be better to have underlying expression instead of recording rule using kube-state-metrics in default Grafana dashboards.

**Comment by shahmed90** [comment]
After setting the stack properly everything works as expected and the observed behavior earlier is gone.

- Thanos Querier needs to know where is Thanos ruler by adding it as a store
- Thanos Ruler needs to have the Querier as queryEndpoints
- Thanos Ruler will be used to evaluate Prometheus rules but as @muzalevs  said, it has its own drawback

**Comment by bmgante** [comment]
Hi,
I am having this same issue, when sharding prometheus. If rules are evaluated by thanos-ruler, no metrics are generated from recording rules. If I set a rule selector matchLabel to force these recording rules to be evaluated by prometheus it works but sometimes doesn´t. Any suggestion?

Thanos querier (bitnami/thanos):
![image](https://github.com/prometheus-community/helm-charts/assets/27358817/a95fdf7e-2041-4ddc-9205-3b65c292f6b2)

Thanos ruler (kube-prometheus-stack):
```
    queryEndpoints:
      - dnssrv+_http._tcp.thanos-query-frontend.monitoring.svc.cluster.local
```

**Comment by Tarun-Narain** [comment]
+1
