### ISSUE TITLE
[prometheus] PVC says "no persistent volumes available for this claim and no storage class is set"

### ISSUE THREAD

**Issue by ultramaks** [prometheus-community/helm-charts#2313]
### Describe the bug a clear and concise description of what the bug is.

After installing the chart
`helm install prometheus1 prometheus-community/prometheus`
I see that some pods are not ready
```
NAME                                              READY   STATUS    RESTARTS   AGE
prometheus1-alertmanager-9bbb47c6b-ljfms          0/2     Pending   0          97m
prometheus1-kube-state-metrics-59846d4f4f-mxzf8   1/1     Running   0          97m
prometheus1-node-exporter-4ncmh                   1/1     Running   0          97m
prometheus1-node-exporter-mk7k8                   1/1     Running   0          97m
prometheus1-pushgateway-7df98dccf4-lqv4c          1/1     Running   0          97m
prometheus1-server-7b8955ccd6-kk5kv               0/2     Pending   0          97m
```
Looming into the isse I see that pvc were created
```
NAME                       STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus1-alertmanager   Pending                                                     97m
prometheus1-server         Pending                                                     97m
```
but there are no pv
```
k get pv
No resources found
```
And pvc is saing
```
  Type    Reason         Age                    From                         Message
  ----    ------         ----                   ----                         -------
  Normal  FailedBinding  3m47s (x382 over 99m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
```
Anything wrong with PV creation? I guess it should be created by the chart?

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

15.10.5

### What happened?

The pods are not starting

### What you expected to happen?

All pods should be in a READY status

### How to reproduce it?

just install the chart and see that there are no PV

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus1 prometheus-community/prometheus

**Comment by ultramaks** [comment]
The issue can be closed
I've found out that there is a need in Dynamic Volume Provisioning. So i have started an NFS server, used [NFS subdir external provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)
 and specifed the chart installation with the following command
`helm install prometheus prometheus-community/prometheus --set server.persistentVolume.storageClass=nfs-client --set alertmanager.persistentVolume.storageClass=nfs-client`
After this PV were successfully created and all pods started

**Comment by kushaldeb-netapp** [comment]
I'm still facing this issue. Tried the steps provided by @ultramaks but it is still failing to start the pods
root@Master:~# kubectl get pods -n monitoring
NAME                                                 READY   STATUS    RESTARTS   AGE
prometheus-alertmanager-0                            0/1     Pending   0          48s
prometheus-kube-state-metrics-64b4cd6658-zbqjt       1/1     Running   0          48s
prometheus-prometheus-node-exporter-25mmw            1/1     Running   0          48s
prometheus-prometheus-node-exporter-764g2            1/1     Running   0          48s
prometheus-prometheus-node-exporter-b8g4f            1/1     Running   0          48s
prometheus-prometheus-pushgateway-7cfd5f66f4-h4lmj   1/1     Running   0          48s
prometheus-server-594d68c5c5-dq2q5                   0/2     Pending   0          48s

**Comment by nemobis** [comment]
@kushaldeb-netapp Are you also using NFS with Trident? If so, you may be interested in https://github.com/NetApp/trident/issues/879
