### ISSUE TITLE
[Grafana] Embed Grafana dashboards in your web application

### ISSUE THREAD

**Issue by fagner-icarotech** [prometheus-community/helm-charts#2316]
### Is your feature request related to a problem ?

We need to change some parameters from default Grafana Configuration file(/etc/grafana/grafana.ini) for sharing it with our Application.

### Describe the solution you'd like.

I need to change two parameters in the default configuration file.
```
allow_embedding = true 
[auth.anonymous] 
# habilitar acesso anônimo 
habilitado = true
```
I don't know how to get the chart value from grafana, how do I?

**Comment by dotdc** [comment]
@pborn-ionos answer is correct, you can use any parameter from http://docs.grafana.org/installation/configuration/ in:
```
grafana:
  grafana.ini:
```
Grafana is a sub-chart of kube-prometheus-stack so you can also use any values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml in the `grafana:` block of your kube-prometheus-stack values.
Closing this issue.
