### ISSUE TITLE
[kube-prometheus-stack] network metrics not showing on Grafana dashboards

### ISSUE THREAD

**Issue by urbaman** [prometheus-community/helm-charts#2318]
### Describe the bug a clear and concise description of what the bug is.

I just installed the helm chart, and it worked flowlessly, also with other servicemonitors active (mysql/mariadb, traefik, redis...).
The metrics about the cluster network do not show, while other resources (CPU, memory) do show.

### What's your helm version?

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

37.3.0

### What happened?

Just installed the chart, no way to get the network metrics showing in grafana.

### What you expected to happen?

Having the Grafana dashboard showing the network metrics

### How to reproduce it?

- Install Kubernetes cluster with kubeadm and Calico
- Install kube-prometheus-stack

### Enter the changed values of values.yaml?

  namespaces:
    releaseNamespace: true
    additional:
      - calico-apiserver
      - calico-system
      - cloudflare-operator
      - default
      - kube-node-lease
      - kube-public
      - metallb-system
      - tigera-operator
      - traefik

Grafana:
    plugins:
      - grafana-piechart-panel
      - grafana-clock-panel
    defaultDashboardsTimezone: browser

### Enter the command that you execute and failing/misfunctioning.

helm install --namespace monitoring --create-namespace kube-prometheus-stack prometheus-community/kube-prometheus-stack --values prom-stack.yaml

**Comment by agtogna-nc** [comment]
The kubelet ServiceMonitor in version 37.x is configured to drop those metrics :-(

**Comment by urbaman** [comment]
Ok, thank you, I really need to learn more on how to search for related/same issues around.

I'll wait for next release, then.

**Comment by urbaman** [comment]
(or, try updating to last release)

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/pull/2297 should be the fix for https://github.com/prometheus-community/helm-charts/pull/2197
