### ISSUE TITLE
[Prometheus] Labels modified 

### ISSUE THREAD

**Issue by gjkamstra** [prometheus-community/helm-charts#2321]
### Describe the bug a clear and concise description of what the bug is.

**Description**
Similar issue as reported in #1613 
I installed the latest Prometheus chart (15.11.0) with the default config. When I use Lens, I get the message that no metrics are available. Troubleshooting revealed that this is due to label renames from kubernetes_node to node. I initially patched this on Lens (see https://github.com/gjkamstra/lens/commit/cab31b2e46dbf6e8fcf82249d226ca3f5ff3679e ). That commit also shows the queries that Lens performs. 

I looked into existing issues and found #1613. According to that one, a new setting honor_labels is introduced and set to true, which should have fixed it, e.g. no need for that fix on Lens, but unfortunately it doesn't work with the latest chart.

Is this something that needs fixing in the Promehteus Chart, or should I raise a pull request on Lens?

### What's your helm version?

Terraform Helm Provider 2.6.0

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

Prometheus

### What's the chart version?

15.11.0

### What happened?

CPU usage and CPU memory not available in Lens

### What you expected to happen?

Metrics available in Lens

### How to reproduce it?

Create an AWS EKS cluster
Install Prometheus Chart with default values (no overrides)
Open Lens
Connect to Cluster
See at the cluster tab the usage metrics are missing.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

resource "helm_release" "prometheus" {
  name             = "prometheus"
  namespace        = "prometheus"
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "prometheus"
  version          = "15.11.0"
  create_namespace = true
}

Command is not failing, only Lens doesn't show metrics

### Anything else we need to know?

Using AWS EKS, Kubernetes 1.22
Lens 5.4.4

**Comment by gjkamstra** [comment]
Sample query:
`node_cpu_seconds_total{}[5m]`

returns
`node_cpu_seconds_total{app="prometheus", app_kubernetes_io_managed_by="Helm", chart="prometheus-15.11.0", component="node-exporter", cpu="0", heritage="Helm", instance="10.0.10.225:9100", job="kubernetes-service-endpoints", mode="idle", namespace="prometheus", node="ip-10-0-10-225.eu-west-1.compute.internal", release="prometheus", service="prometheus-node-exporter"}`

Lens was expecting kubernetes_node instead of node

**Comment by gjkamstra** [comment]
For others having the same issue:
We switched to the kube-prometheus-stack chart, and now things work fine.

**Comment by Richardswe** [comment]
What version of kube-prometheus-stack are you using? I'm having the same problem but I'm selfhosting a RKE2 cluster. I use chart version 39.0. I'm thankful for advice :)

**Comment by cristianrat** [comment]
@Richardswe @gjkamstra yeah, installed it via the kube-prometheus-stack with mixed results, sometimes it works and sometimes doesn't, been messing about with config for a while , but not sure what's what
I installed the latest version, 39.11

**Comment by lanru2001** [comment]
Metrics are not available due to missing or invalid Prometheus configuration. This issue still persist when using prometheus-community/prometheus chart

**Comment by lanru2001** [comment]
Metrics are not available due to missing or invalid Prometheus configuration. This issue still persist when using prometheus-community/prometheus chart.
