### ISSUE TITLE
kube-prometheus-stack cannot parse YAML CRD

### ISSUE THREAD

**Issue by doryer** [prometheus-community/helm-charts#2334]
### Describe the bug a clear and concise description of what the bug is.

Trying to parse this CRD in my code with ruamel library ( Python 3.9 ) and getting parse error for this CRD: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml#L73

I'm getting the error on lines 73/74 which is an enum that has string values that are arithmetic operators, that are not surrounded with `'` sign, but as you can see in lines 72/75 they are surrounded with `'` signs and it not failing on those lines.

Hoping for a fix 

### What's your helm version?

v3.7.2

### What's your kubectl version?

1.23.8

### Which chart?

kube-prometheus-stack

### What's the chart version?

38.0.0

### Enter the command that you execute and failing/misfunctioning.

helm template --include-crds

**Comment by monotek** [comment]
Wron repo. The CRDs are downloaded from: https://github.com/prometheus-operator/prometheus-operator/tree/main/example/prometheus-operator-crd

**Comment by doryer** [comment]
> Wrong repo. The CRDs are downloaded from: https://github.com/prometheus-operator/prometheus-operator/tree/main/example/prometheus-operator-crd

Thanks, my bad. will open it there.
