### ISSUE TITLE
[prometheus-kube-stack] Grafana sending emails to example@email.com

### ISSUE THREAD

**Issue by mindrunner** [prometheus-community/helm-charts#2335]
### Describe the bug a clear and concise description of what the bug is.

Just recently Grafana started to send alert emails to an default address (see screenshot). Could not find a straight forward way to change this setting in `values.yaml`. Is this expected behaviour? Any advice?

![image](https://user-images.githubusercontent.com/1413542/182426886-62841b0a-fec4-4ab8-a940-be786d443eb5.png)

### What's your helm version?

version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.18.2"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"bd30c9fbc8dc9668d7ab4b0bd4fdab5c929c1ad7", GitTreeState:"clean", BuildDate:"2022-06-21T17:15:16Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

39.2.0

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install --version=39.2.0 -n ${PROJECT_NAMESPACE} --create-namespace --values=build/helm/dist/values.yaml ${PROJECT_NAME} prometheus-community/kube-prometheus-stack

**Comment by makeittotop** [comment]
I faced the same issue, and went looking. Looks like the upstream grafana binary has the `alertmanager_config` baked in, and it has not yet been exposed to the outside world via the grafana configuration settings 

https://github.com/grafana/grafana/blob/main/pkg/setting/setting_unified_alerting.go#L25

**Comment by mindrunner** [comment]
Yea, saw that as well. I guess, this needs to be moved to https://github.com/grafana/helm-charts
