### ISSUE TITLE
[kube-prometheus-stack] Support Istio  Metrics

### ISSUE THREAD

**Issue by XuejiaoZhang** [prometheus-community/helm-charts#234]
**Is your feature request related to a problem? Please describe.**
By installing prometheus, Grafana template for Istio ( for example "7639") doesn't has  data.

**Describe the solution you'd like**
Istio Metrics could be scraped out-of-box and enabled  EASILY, so that Grafana template for Istio could be imported and shows data.

**Describe alternatives you've considered**

**Additional context**
If the feature is not in the roadmap,  could you please give some clue on how to scrape Istio Metrics.
I saw the [article](https://medium.com/@emirmujic/collect-cluster-and-istio-metrics-with-prometheus-operator-42d4499d621a) related to the issue but using the old prometheus  operator, also the[ issue here](https://github.com/prometheus-operator/prometheus-operator/issues/2502)

I am wondering what the current best approach of scraping Istio Metrics.

**Comment by Keramblock** [comment]
You need that one: https://istio.io/latest/docs/ops/best-practices/observability/#federation-using-workload-level-aggregated-metrics

search for "If you are using the Prometheus Operator, use the following configuration instead:"

**Comment by XuejiaoZhang** [comment]
@Keramblock Thanks for your reply. By federation, I suppose it means to setup Prometheus with Prometheus Operator to scrape from the Istio Prometheus. What if II don't plan to use federation, just would like to setup Prometheus with Prometheus Operator and scrape directly, the way similar to the DEPRECATED helm/charts  https://github.com/helm/charts/tree/master/stable/prometheus 

Do you have any clue on this?

**Comment by fktkrt** [comment]
@XuejiaoZhang for that I'd advise to take a look at this option: https://istio.io/latest/docs/ops/integrations/prometheus/#option-1-metrics-merging

With this, you will have `prometheus.io` annotations at your pods, so you can scrape them.
