### ISSUE TITLE
http(s)_proxy and no_proxy env from chart

### ISSUE THREAD

**Issue by lagunary** [prometheus-community/helm-charts#2349]
### Is your feature request related to a problem ?

This is not a problem, just inconvenience, but it is very annoying, cause I need to patch the deployment after every update.

### Describe the solution you'd like.

In the chart it would be so nice if we have an grafana.extraenv (or smg similar) which set the environment variables inside the pod. This is more usefull compare with make some grafana.httpsproxy, httpproxy, noproxy.

### Describe alternatives you've considered.

NONE

**Comment by monotek** [comment]
Like this?
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L364-L423

**Comment by lagunary** [comment]
Yes, exactly like this. in this template: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=template
Ive tried to find it in kube-prometheus-stack chart:
![image](https://user-images.githubusercontent.com/12951104/183399966-ce4fe484-56ee-4347-8d35-dfc1587f239b.png)
But it has no result.

**Comment by lagunary** [comment]
but docs said:
Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

**Comment by monotek** [comment]
Just place it below: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L702

**Comment by lagunary** [comment]
OK. Thanks for help.
