### ISSUE TITLE
smartctl_exporter Chart

### ISSUE THREAD

**Issue by kfox1111** [prometheus-community/helm-charts#2356]
It would be great to have an official helm chart for this project.

I have a rough one started here:
https://github.com/pnnl-miscscripts/miscscripts/tree/master/charts/charts/smartctl-exporter
That could be donated.

It has a bit of tricky logic in it to support having multiple daemonsets configured differently in case you have different types of nodes in the cluster.

**Comment by monotek** [comment]
Yes, would be welcome to be contributed here.

But please recreate it with current helm version so labels and so on match current standard.

**Comment by kfox1111** [comment]
Rebased and pr submitted.
