### ISSUE TITLE
[prometheus-kube-stack] Not able to persist starred / recent viewed dashboard after adding PVC

### ISSUE THREAD

**Issue by Balamurugannagappan** [prometheus-community/helm-charts#2361]
**What happened**:
I have added the PVC to the grafana in the kube-prometheus-stack values .yaml and I could see datasources and the dashboards are persistent even after I restart my pods  Whereas my starred and the recent dashboards are not persistent , I tend to loose all starred and the recent viewed dashboard 

`  persistence:
    type: pvc
    enabled: true
    storageClassName: managed-premium
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection`
      - 
Before restart 

![image](https://user-images.githubusercontent.com/93638028/184079201-87468607-f588-418d-8ef9-e3d6432aaf92.png)

After restarting the pods
![image](https://user-images.githubusercontent.com/93638028/184079267-41e39c1b-463e-4469-a49d-73b271c91f71.png)

**What you expected to happen**:

I would expect all the starred and recently viewed dashboards to be visible 

**How to reproduce it (as minimally and precisely as possible)**:

Provision grafana along with PVC and then starred some dashboards available. After then restart the deployment. Should be able to reproduce the issue 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  ( Kube-prometheus stack ) - version = "38.0.3"
- Data source type & version:
- OS Grafana is installed on: AKS
- User OS & Browser:
- Grafana plugins:
- Others:

### What's your helm version?

I use terraform - Terraform v0.13.3

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"5a97ee6d15525f6e4a1c2646bf1dfd2ebd5220b5", GitTreeState:"clean", BuildDate:"2022-06-15T04:26:33Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

38.0.3

### What happened?

I have added the PVC to the grafana in the kube-prometheus-stack values .yaml and I could see datasources and the dashboards are persistent even after I restart my pods  Whereas my starred and the recent dashboards are not persistent , I tend to loose all starred and the recent viewed dashboard 

### What you expected to happen?

I would expect all the starred and recently viewed dashboards to be visible 

### How to reproduce it?

Provision grafana along with PVC and then starred some dashboards available. After then restart the deployment. Should be able to reproduce the issue 

### Enter the changed values of values.yaml?

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx-internal
    pathType: ImplementationSpecific
    hosts:
    - ${grafana_internal_dns_zone}
  priorityClassName: grafana

  additionalDataSources:
  - name: loki-trex
    type: loki
    access: proxy
    basicAuth: true
    basicAuthUser: loki
    url: ${loki_internal_dns_zone}
    jsonData:
      maxLines: 1000
      httpHeaderName1: X-Scope-OrgID
    secureJsonData:
      basicAuthPassword: "${loki_login_cred}"
      httpHeaderValue1: trex 
  persistence:
    type: pvc
    enabled: true
    storageClassName: managed-premium
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

### Enter the command that you execute and failing/misfunctioning.

I uses terraform apply

**Comment by Balamurugannagappan** [comment]
This issue happens only for the dashboard that are imported to grafana  from Prometheus stack

**Comment by WladyX** [comment]
This is still an issue.
