### ISSUE TITLE
[kube-prometheus-stack] prometheuses.monitoring.coreos.com CRD is too long

### ISSUE THREAD

**Issue by BCsabaEngine** [prometheus-community/helm-charts#2364]
### Describe the bug a clear and concise description of what the bug is.

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml generates too large yaml content in a CI/CD system. When I change some config values, the argocd regenerate CRD and it is too large. ArgoCD (k8s) gives an error because annotation containt previous version of yamls.

```
"prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes.
```

### What's your helm version?

3.3.4

### What's your kubectl version?

1.24.3

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.6.0

### What happened?

Error occurs in k8s. I must use ```kubectl replace .yaml``` to force update of this CRD.

### What you expected to happen?

Normal update should happen, should be remove long description fields.

### Enter the command that you execute and failing/misfunctioning.

```helm apply -f crd-prometheuses.yaml``` twice (to affects modify)

**Comment by monotek** [comment]
Check the readme. 
Use server side apply.
