### ISSUE TITLE
Node Exporter doesn't scrap metrics from other namespaces

### ISSUE THREAD

**Issue by Raji0196** [prometheus-community/helm-charts#2367]
### Describe the bug a clear and concise description of what the bug is.

When checking the node metrics (ex,) node_disk_io_now, I get prometheus namespace values only

### What's your helm version?

3.9.2

### What's your kubectl version?

v1.24.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.6.0

### What happened?

I installed chat with the below parameters. When checking the node metrics (ex,) node_disk_io_now, I get prometheus namespace values only as the snippet attached below. 

helm Install prometheus -n prometheus prometheus-community/kube-prometheus-stack -f  --set alertmanager.enabled=false --set grafana.service.type=LoadBalancer --set nameOverride=prometheustest1 --set kubelet.serviceMonitor.https=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false  

![promerror](https://user-images.githubusercontent.com/77723011/184499353-09d14839-2fd2-4f7b-8d3c-3faa4644a478.JPG)

I am getting container metrics from all the namespaces. for ex, container_cpu_usage_seconds_total.

### What you expected to happen?

Need metrics from all the namespaces.

### How to reproduce it?

Install chart with parameters as below.

helm Install prometheus -n prometheus prometheus-community/kube-prometheus-stack -f  --set alertmanager.enabled=false --set grafana.service.type=LoadBalancer --set nameOverride=prometheustest1 --set kubelet.serviceMonitor.https=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false  

### Enter the changed values of values.yaml?

alertmanager.enabled:false 
grafana.service.type:LoadBalancer 
nameOverride:prometheustest1 
kubelet.serviceMonitor.https=true 
prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false  

### Enter the command that you execute and failing/misfunctioning.

helm Install prometheus -n prometheus prometheus-community/kube-prometheus-stack -f  --set alertmanager.enabled=false --set grafana.service.type=LoadBalancer --set nameOverride=prometheustest1 --set kubelet.serviceMonitor.https=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false

**Comment by arpitjindal97** [comment]
Check https://github.com/prometheus-community/helm-charts/issues/2323#issuecomment-1214227874
