### ISSUE TITLE
[kube-prometheus-stack] container_fs_inodes_free reports as 0 when kubelet.serviceMonitor.cAdvisorMetricRelabelings is unmodified from chart default

### ISSUE THREAD

**Issue by slushysnowman** [prometheus-community/helm-charts#2373]
### Describe the bug a clear and concise description of what the bug is.

We encountered an issue when upgrading from `34.9.0` to `37.2.0`

After the upgrade, an alert based on the `container_fs_inodes_free` was triggering, and the metric value was 0 for everything.

After a lot of troubleshooting, the issue seems to be related to `kubelet.serviceMonitor.cAdvisorMetricRelabelings` - if we override this in our values.yaml:
```
kubelet:
  serviceMonitor:
    cAdvisorMetricRelabelings: {}
```
and redeploy, then suddenly we start seeing real values for `container_fs_inodes_free`
![image](https://user-images.githubusercontent.com/18573653/184899369-b34ce460-518d-42a2-bd37-363f1941e895.png)

### What's your helm version?

version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

37.2.0

### What happened?

`container_fs_inodes_free` value is 0 for all metrics

### What you expected to happen?

`container_fs_inodes_free` value should be correct

### How to reproduce it?

With default chart values, check the value of `container_fs_inodes_free` - it should be 0 for all metrics

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by soroshsabz** [comment]
ITNOA

I have same issue
