### ISSUE TITLE
Some Grafana dashboards are showing up in UI

### ISSUE THREAD

**Issue by richamishra006** [prometheus-community/helm-charts#2389]
Hi ,
I am running into a problem with grafana. The dashboards we are pushing into grafana using code are not showing up in the UI.
**Context**
We are using kube-prometheus helm chart. We are also leveraging the same chart to deploy multiple grafana dashboards. We create configmaps which contain dashboard json, and then those jsons are inherited by grafana pod and from there they show up in the UI. That is my understanding.
Problem
when i exec into grafana pod and go to the dashboards folder, i am able to see dashboards jsons but some of them are not showing up in UI. One is [MongoDB dashboard](https://grafana.com/grafana/dashboards/2583) and other is [ETCD Dashboard](https://grafana.com/grafana/dashboards/12381-etcd-cluster-health). As we are not able to deploy the dashboard of our choice, we have to settle with other dashboards.
What have we cross checked
What if grafana pod is not able to import dashboards? -> Other dashboards are visible at the same time.
What if the json provided to grafana pod is not accurate? -> Copied the content of the json from inside grafana pod and imported that json itself from the UI, it worked.
Please suggest What else can be checked? Do you have any such experience in the past? How did you fix this issue?

**Comment by WilliamCassanova** [comment]
We may have a similar problem.  As a test if you login to the UI using you admin user and password do the dashboards show up?  The symptoms we noticed specifically were:

1. Dashboard was showing up fine.
2. After applying the https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-39.6.0 release the dashboard we deployed with our service disappeared when logging in as the NON-admin user.  The dashboard do appear logging as the admin user.
3. The issue might be https://github.com/grafana/grafana/pull/46186 in that they are not setting the default permissions when they dynamically load a dashboard - only at startup.  

As a test if you HUP you Grafana pod and the dashboards re-appear that may be the problem.

Grafana issue for reference: https://github.com/grafana/grafana/issues/54086

**Comment by dotdc** [comment]
Did you checked that the dashboards doesn't have the same ID or UID than others dashboards on the Grafana instance?
If yes, could you share the dashboards that are not working well?

**Comment by richamishra006** [comment]
Hey Thanks for replying on this issue, This issue is resolved now, 
The problem was with the json file, i was providing the dashboard to the configmap yaml file which was generating dashboard.json, but when i checked the logs of grafana container in grafana pod, i found the error saying the json is not valid.
using json and yaml validator, i was able to resolve the issue.
please close this issue. Thankyou so much for coming back on this

**Comment by dotdc** [comment]
Ok great, I will close the issue then.
@WilliamCassanova: It looks like your problem is related to Grafana itself. If you find out that it's somehow related to kube-prometheus-stack, let me know and I'll check it out.
