### ISSUE TITLE
Deploy alertmanager as HA

### ISSUE THREAD

**Issue by emahdij** [prometheus-community/helm-charts#2403]
Hi
I want to know if I increase  "replicaCount", will the alert manager be deployed as HA?

**Comment by dotdc** [comment]
Hi @emahdij, 
Yes, setting replicas to 2 or more will make your alertmanager "HA". 
Test it a fill a bug if it's not the case.

https://prometheus.io/docs/alerting/latest/alertmanager/
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L534

Closing this

**Comment by emahdij** [comment]
Hi again
I changed the replica to 2. but I got an error that said can't resolve another instance of the alert manager.
```
msg=refresh result=failure addr=alertmanager-mw-0.alertmanager-mw-headless:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager.alertmanager-headless:9094: lookup alertmanager.alertmanage-headless on 10.96.0.10:53: no such host\n\n"
```
I can curl the addresses from another pod in the same namespace but I got an error in the alert manager logs.

**Comment by chanakya-svt** [comment]
@emahdij How did you resolve the issue. I am facing the same issue.
