### ISSUE TITLE
[prometheus-kube-stack] Default Thanos Ruler name too long

### ISSUE THREAD

**Issue by rverchere** [prometheus-community/helm-charts#2408]
### Describe the bug a clear and concise description of what the bug is.

When deploying the Thanos Ruler with default values, the generated name for volumes attached to pods is too long, blocking it (more than 63 chars).

It creates a volume named `thanos-ruler-<release_name>-kube-prometheus-stack-thanos-ruler-rulefiles-0`, and then I get this error:

```
$ kubectl get events
29s         Warning   FailedCreate       statefulset/thanos-ruler-prom-kube-prometheus-stack-thanos-ruler   create Pod thanos-ruler-prom-kube-prometheus-stack-thanos-ruler-0 in StatefulSet thanos-ruler-prom-kube-prometheus-stack-thanos-ruler failed error: Pod "thanos-ruler-prom-kube-prometheus-stack-thanos-ruler-0" is invalid: [spec.volumes[0].name: Invalid value: "thanos-ruler-prom-kube-prometheus-stack-thanos-ruler-rulefiles-0": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not found: "thanos-ruler-prom-kube-prometheus-stack-thanos-ruler-rulefiles-0", spec.containers[1].volumeMounts[0].name: Not found: "thanos-ruler-prom-kube-prometheus-stack-thanos-ruler-rulefiles-0"]
```

The name can be less than 63 characters if the release name is "only" 2 chars long, which is a little bit short ;)

### What's your helm version?

version.BuildInfo{Version:"v3.8.1", GitCommit:"5cb9af4b1b271d11d7a97a71df3ac337dd94ad37", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

kube-prometheus-stack-39.9.0

### What happened?

Enable the `thanosRuler` in custom values.

### What you expected to happen?

Thanos Ruler pod shoud be created

### How to reproduce it?

Just enable Thanos Ruler

### Enter the changed values of values.yaml?

```yaml
thanosRuler:
  enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

helm install prom prometheus-community/kube-prometheus-stack  -f custom-values.yaml --version 39.9.0

**Comment by rverchere** [comment]
still there

**Comment by rverchere** [comment]
Still there

**Comment by SophiaGarbenis** [comment]
experiencing the same issue: 

``FailedCreate             statefulset/thanos-ruler-kube-prometheus-kube-prome-thanos-ruler   create Pod thanos-ruler-kube-prometheus-kube-prome-thanos-ruler-0 in StatefulSet thanos-ruler-kube-prometheus-kube-prome-thanos-ruler failed error: Pod "thanos-ruler-kube-prometheus-kube-prome-thanos-ruler-0" is invalid: [spec.volumes[1].name: Invalid value: "thanos-ruler-kube-prometheus-kube-prome-thanos-ruler-rulefiles-0": must be no more than 63 characters, spec.containers[0].volumeMounts[1].name: Not found: "thanos-ruler-kube-prometheus-kube-prome-thanos-ruler-rulefiles-0", spec.containers[1].volumeMounts[0].name: Not found: "thanos-ruler-kube-prometheus-kube-prome-thanos-ruler-rulefiles-0"]``
