### ISSUE TITLE
panic: Unable to create mmap-ed active query log

### ISSUE THREAD

**Issue by thespamer** [prometheus-community/helm-charts#2420]
### Describe the bug a clear and concise description of what the bug is.

Hello.
Have issues here with my local minikube:
minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc

helm:
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}

install command:
helm upgrade --install prometheus prometheus-community/prometheus --namespace prometheus --create-namespace --set server.persistentVolume.storageClass="standard"

prometheus-server ts=2022-09-01T20:25:15.606Z caller=query_logger.go:90 level=error component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"           │
│ prometheus-server panic: Unable to create mmap-ed active query log

As I don't use local charts, only remote charts... is there any issue related to /data permissions ?

Regards

### What's your helm version?

3.7.1

### What's your kubectl version?

v1.25.0

### Which chart?

prometheus-community/prometheus

### What's the chart version?

quay.io/prometheus/prometheus:v2.36.2 

### What happened?

prometheus-server ts=2022-09-01T20:25:15.606Z caller=query_logger.go:90 level=error component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"           │
│ prometheus-server panic: Unable to create mmap-ed active query log

### What you expected to happen?

install helm successfully

### How to reproduce it?

helm upgrade --install prometheus prometheus-community/prometheus --namespace prometheus --create-namespace --set server.persistentVolume.storageClass="standard"

### Enter the changed values of values.yaml?

no values changed

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/prometheus --namespace prometheus --create-namespace --set server.persistentVolume.storageClass="standard"

### Anything else we need to know?

no

**Comment by YuikoTakada** [comment]
facing same issue.
According to https://github.com/prometheus/prometheus/issues/5976 this can be solved by changing permission of `/data` , but this did not work for me.

**Comment by YuikoTakada** [comment]
https://github.com/prometheus-community/helm-charts/issues/1162 worked me!

```
helm show values prometheus-community/helm-charts > values.yaml
```

fix values.yaml as below:
```
  ## Security context to be added to server pods
  ##
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
    runAsGroup: 0
    fsGroup: 0
```

```
helm install --generate-name -f values.yaml prometheus-community/prometheus
```

**Comment by rtrox** [comment]
Also impacted, on the `v2.39.0` image, same error.
