### ISSUE TITLE
[kube-prometheus-stack] Allow custom annotations on the CRDs

### ISSUE THREAD

**Issue by mariusandersen** [prometheus-community/helm-charts#2425]
### Is your feature request related to a problem ?

Installing kube-prometheus-stack with ArgoCD it's a well known issue with having to replace the CRDs.

Most discussed thread is probably over at [ArgoCD's github](https://github.com/argoproj/argo-cd/issues/8128)

This can be solved if CRDs have customizable annotations

### Describe the solution you'd like.

in values.yaml we can add the following
```
crds:
    additionalCrdAnnotations: {}
```

This would mean ArgoCD users can add the [documented annotation](https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#replace-resource-instead-of-applying-changes) `argocd.argoproj.io/sync-options: Replace=true` on all CRDs, neatly solving the issue described.

### Describe alternatives you've considered.

NONE

**Comment by dacamposol** [comment]
@mariusandersen would this solve your case-scenario?

https://github.com/prometheus-community/helm-charts/pull/2697

**Comment by Daniel2000815** [comment]
Reopening this issue. Installing a separate chart for this simple feature seems a bit overkill, and having this implemented in the main chart would be helpful in many use cases, like the one @MariusGrandeAndersen mentioned, enabling server side apply, etc.
