### ISSUE TITLE
Download specific chart kube-prometheus-stack-23.1.0 to my local

### ISSUE THREAD

**Issue by Manidoit** [prometheus-community/helm-charts#2426]
I want to install specific ```kube-prometheus-stack-23.1.0``` version on my eks cluster. When I ran this command ```helm repo add prometheus-community https://prometheus-community.github.io/helm-charts ``` It is adding the latest chart. 

When I am running below command I am getting this error 
```helm upgrade prometheus -n monitoring -f prom-v1.yaml prometheus-community/kube-prometheus-stack-23.1.0  --debug```
```Error: chart "kube-prometheus-stack-23.1.0" matching  not found in prometheus-community index. (try 'helm repo update'): no chart name found ```

can someone pl help me on how to download specific chart ```kube-prometheus-stack-23.1.0``` to my local

**Comment by zeritti** [comment]
You can specify the desired chart version with `helm`, e.g.
```
helm upgrade prometheus -n monitoring -f prom-v1.yaml \
prometheus-community/kube-prometheus-stack --version 23.1.0 --debug
```
If the version is not set, `helm` retrieves the latest.

**Comment by Manidoit** [comment]
Thanks Zeritti for responding. Chart is not in local. It is throwing the below error. can you pl help me. 
```helm upgrade prometheus -n monitoring -f prom-v1.yaml prometheus-community/kube-prometheus-stack-23.1.0 --version 23.1.0 --debug```
```Error: chart "kube-prometheus-stack-23.1.0" matching 23.1.0 not found in prometheus-community index. (try 'helm repo update'): no chart name found```

**Comment by iamleot** [comment]
Hello!

> Thanks Zeritti for responding. Chart is not in local. It is throwing the below error. can you pl help me.
> `helm upgrade prometheus -n monitoring -f prom-v1.yaml prometheus-community/kube-prometheus-stack-23.1.0 --version 23.1.0 --debug`
> `Error: chart "kube-prometheus-stack-23.1.0" matching 23.1.0 not found in prometheus-community index. (try 'helm repo update'): no chart name found`

There is at least an extra `-23.1.0` in the suffix of the chart name (it should be `kube-prometheus-stack` not `kube-prometheus-stack-23.1.0`). Please retry with:

```
helm upgrade prometheus -n monitoring -f prom-v1.yaml prometheus-community/kube-prometheus-stack --version 23.1.0
```
