### ISSUE TITLE
kube-prometheus-stack | default rules | runbook_url override

### ISSUE THREAD

**Issue by iocn-2-3-4** [prometheus-community/helm-charts#2434]
### Is your feature request related to a problem ?

Hello
We use default rules in our alerting system and it's very convenient but I noticed that in default rules, some part of runbook_url is hardcoded. For example:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/general.rules.yaml#L34
In this example `/general/targetdown` 
For some reasons we can't create such structure on our wiki, like <wiki_url>/<alert_group>/<alert_name>
So, we'd like to be able to rewrite whole runbook_url

### Describe the solution you'd like.

For example, replace hardcoded parts with variables that could be redefined:
runbook_url: {{ .Values.defaultRules.runbookUrl }}/$labels.alertname

### Describe alternatives you've considered.

---

### Additional context.

----

**Comment by snps-madduk** [comment]
Ran into the same issue. @iocn-2-3-4 Did you get any solutions that resolved this?
