### ISSUE TITLE
[kube-prometheus-stack] Direct upgrade from old versions

### ISSUE THREAD

**Issue by tleibovichverint** [prometheus-community/helm-charts#2467]
Hi,
According to the docs, when someone wishes to upgrade the chart, he should follow the upgrade process. For example: from 35.x to 36.x, the CRDs should be upgraded.

What about a jump from a very old version to a recent one? For example, from 19.x to 40.x, is it needed to perform *every* step, or is it enough to do the same steps as from 39.x to 40.x?

**Comment by subbuedcast** [comment]
You can do a direct upgrade it works from 19.x to 39.x
