### ISSUE TITLE
[kube-prometheus-stack] Thanos Prometheus sidecar

### ISSUE THREAD

**Issue by jholowaty** [prometheus-community/helm-charts#2474]
### Describe the bug a clear and concise description of what the bug is.

I have a doubt with the configuration of the thanos sidecar.

thanosService:
    enabled: true
    annotations: {}
    labels: {}

    ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
    ##
    externalTrafficPolicy: Cluster

    ## Service type
    ##
    type: ClusterIP

    ## gRPC port config
    portName: grpc
    port: 10901
    targetPort: "grpc"

    ## HTTP port config (for metrics)
    httpPortName: http
    httpPort: 10902
    targetHttpPort: "http"

    ## ClusterIP to assign
    # Default is to make this a headless service ("None")
    clusterIP: "None"

    ## Port to expose on each node, if service type is NodePort
    ##
    nodePort: 30901
    httpNodePort: 30902

The theory says that if thanosService is True then 1 more container is up inside the Prometheus deploy but in my case, thats not happend!!

pod/prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   0               4m21s

So when I enter the thanos query website, I don't see any metrics.

If i try the bitnami kube-prometheus, when prometheus pod starts, i see 3 containers and one of them is the thanos sidecar, so then in the thanos querier web, i saw the metrics.

What i'm doing wrong with the kube-prometheus-stack that i can't initialize the sidecar in prometheus pod?

Thanks a lot!!!!

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

40.1.0

### Enter the changed values of values.yaml?

thanosService:
    enabled: true

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f kube-prometheus-stack/values.yaml

**Comment by pgier** [comment]
The `thanosService` config only enabled the Kubernetes service.  To enable to sidecar, you have to specify a non-null `thanos` configuration inside `prometheusSpec` which will add a `thanos` section to the Prometheus CRD object.  A simple example is to just set the thanos image that you want to use for the sidecar.

```
prometheus:
  prometheusSpec:
    thanos:
      image: quay.io/thanos/thanos:v0.28.1
```
