### ISSUE TITLE
[kube-prometheus-stack] ServiceMonitors is not deployed

### ISSUE THREAD

**Issue by sergeyshaykhullin** [prometheus-community/helm-charts#248]
**Describe the bug**
ServiceMonitors is never deployed after hard namespace reinstallation and before manual release uninstall

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}                                                                                                                    Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 10.1.1

**What you expected to happen**:

ServiceMonitors always deployed and admission is not failing

**How to reproduce it** (as minimally and precisely as possible):

**Failing workflow**
1. helm install test prometheus-community/kube-prometheus-stack -n test
2. kubectl delete ns test && kubectl create ns test
3. helm install test prometheus-community/kube-prometheus-stack -n test

**Working workflow**
1. helm install test prometheus-community/kube-prometheus-stack -n test
2. helm uninstall test -n test
3. kubectl delete ns test && kubectl create ns test
4. helm install test prometheus-community/kube-prometheus-stack -n test

**Anything else we need to know**:

**Comment by sergeyshaykhullin** [comment]
No ;c

**Comment by sergeyshaykhullin** [comment]
@bismarck @gianrubio @gkarthiks @scottrigby @vsliouniaev @Xtigyro

**Comment by vsliouniaev** [comment]
The failure I see when I try to install a chart in this way is that rules are blocked from being installed due to not being able to call the admission webhook. The prometheus-operator deployment was deleted when you removed the namespace. This chart installs resources at cluster-level and into other namespaces. I would not expect deleting the namespace without uninstalling the chart to work.
