### ISSUE TITLE
[prometheus-kube-stack] send_exemplars unknown field 

### ISSUE THREAD

**Issue by darkgordon** [prometheus-community/helm-charts#2481]
### Describe the bug a clear and concise description of what the bug is.

Hello prometheus community hope you are doing great, I have a quick question, in the general values I am trying to add a remote write and using send_exemplars: true but its seems that the value doesn’t exist:

`error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "send_exemplars" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite`

any help would be appreciated, have a nice day 

### What's your helm version?

Using argoCD 2.4.7

### What's your kubectl version?

Cluster: 1.24.3 cli 1.22.3 

### Which chart?

kube-prometheus-stack

### What's the chart version?

version: 40.1.0 and  appVersion: 0.59.1

### What you expected to happen?

to create the configuration of remotewrite

### How to reproduce it?

adding the sendx_exemplars inside remotewrite in prometheusSpec

if i try to change it manually I get the following error 
![image](https://user-images.githubusercontent.com/28151796/191822842-0cddf2a1-fb72-4975-a21b-14199c97f08a.png)

### Enter the changed values of values.yaml?

    remoteWrite: 
      - url: http://myremoteaddress
        send_exemplars: true
        headers:
          x-scope-orgid: "Main Org."

### Enter the command that you execute and failing/misfunctioning.

error validating data: ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "send_exemplars" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite

**Comment by zeritti** [comment]
Hello! The operator expects the field `sendExemplars` in [RemoteWriteSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RemoteWriteSpec), hence, `send_exemplars` as an unknown field results in the error above.

**Comment by darkgordon** [comment]
thank you very much @zeritti  it works !!!
