### ISSUE TITLE
[prometheus-blackbox-exporter] Adding NET_RAW capability is not enough to run rootless container

### ISSUE THREAD

**Issue by zerkms** [prometheus-community/helm-charts#2483]
### Describe the bug a clear and concise description of what the bug is.

If just `securityContext` container added with `NET_RAW` capability it wouldn't be enough to run rootless.

Prober would fail with the following logs:

```
ts=2022-09-23T03:40:29.727021679Z caller=main.go:144 module=icmp target=xtr-srv05-idrac.wialus.co.nz level=info msg="Creating socket"
ts=2022-09-23T03:40:29.727065001Z caller=main.go:144 module=icmp target=xtr-srv05-idrac.wialus.co.nz level=debug msg="Unable to do unprivileged listen on socket, will attempt privileged" err="socket: permission denied"
ts=2022-09-23T03:40:29.727094666Z caller=main.go:144 module=icmp target=xtr-srv05-idrac.wialus.co.nz level=error msg="Error listening to socket" err="listen ip4:icmp 0.0.0.0: socket: operation not permitted"
ts=2022-09-23T03:40:29.727127158Z caller=main.go:352 module=icmp target=xtr-srv05-idrac.wialus.co.nz level=error msg="Probe failed" duration_seconds=0.049229119
```

What it's missing is setting `net.ipv4.ping_group_range` too in the pod's `securityContext`:

```yaml
      securityContext:
        sysctls:
          - name: net.ipv4.ping_group_range
            value: "0 2147483647"
```

See also: https://github.com/prometheus/blackbox_exporter/issues/147#issuecomment-901302559

### What's your helm version?

n/a

### What's your kubectl version?

n/a

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

7.1.0

### What happened?

.

### What you expected to happen?

.

### How to reproduce it?

.

### Enter the changed values of values.yaml?

.

### Enter the command that you execute and failing/misfunctioning.

.

**Comment by zerkms** [comment]
Not stale.

**Comment by zerkms** [comment]
Not stale.

**Comment by fgionghi** [comment]
We are having the same issue.

**Comment by zerkms** [comment]
Not stale.

**Comment by zerkms** [comment]
Not stale.

**Comment by gkavboy** [comment]
actual

**Comment by mossad-zika** [comment]
Not stale.

**Comment by akash123-eng** [comment]
Not stale

**Comment by akash123-eng** [comment]
We are also facing this issue.any update on this ?

**Comment by taind772** [comment]
Not stale.

**Comment by andrejshapal** [comment]
Hello, 
Issue can be fixed by adding the following in values.yaml:
`        podSecurityContext:
          sysctls:
            - name: net.ipv4.ping_group_range
              value: "0 2147483647"
`
