### ISSUE TITLE
[prometheus-redis-exporter] image tag mismatch with appVersion

### ISSUE THREAD

**Issue by lxwzy** [prometheus-community/helm-charts#2488]
### Describe the bug a clear and concise description of what the bug is.

`appVersion` changed from `1.27.0` to `1.43.0` in #2199, but the `image.tag` was not changed at same time.
`image.tag` should be set to `1.43.0` like #1297.

### What's your helm version?

n/a

### What's your kubectl version?

n/a

### Which chart?

prometheus-redis-exporter

### What's the chart version?

5.1.0

### Enter the command that you execute and failing/misfunctioning.

-

**Comment by monotek** [comment]
will be fixed with: https://github.com/prometheus-community/helm-charts/pull/2490
