### ISSUE TITLE
CRD Upgrade issue

### ISSUE THREAD

**Issue by mrad-bilel** [prometheus-community/helm-charts#2489]
### Describe the bug a clear and concise description of what the bug is.

Hello,

I've a problem when trying to upgrade prometheus-operator crd 

kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml --dry-run=server
error: Apply failed with 1 conflict: conflict with "helm" using apiextensions.k8s.io/v1: .spec.versions
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts

s
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
prometheus      monitoring      1               2022-04-29 12:06:39.295682 +0200 +0200  deployed        kube-prometheus-stack-32.2.0    0.54.0     

K8S=AKS version 1.22

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

kubectl version --short Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. Client Version: v1.25.2 Kustomize Version: v4.5.7 Server Version: v1.22.6

### Which chart?

 https://prometheus-community.github.io/helm-charts

### What's the chart version?

kube-prometheus-stack-32.2.0

### Enter the command that you execute and failing/misfunctioning.

kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.55.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml --dry-run=server
error: Apply failed with 1 conflict: conflict with "helm" using apiextensions.k8s.io/v1: .spec.versions
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts

**Comment by monotek** [comment]
Just add "--force-conflicts" to the command.

**Comment by mrad-bilel** [comment]
Hello @monotek thanks and happy to see you help me again in addition of Zammad communities

**Comment by IamTyrone** [comment]
> Just add "--force-conflicts" to the command.

Why ? What does this command really do. What is the depth of the problem? What exactly is going on. What is the problem and how des --forece-conflicts solve it.

**Comment by ametad** [comment]
I don't like the "don't worry, just do it"... But it does work indeed. The manual upgrade of the CRD's are needed, otherwise the Helm chart templates of a newer version are not correct.
