### ISSUE TITLE
[prometheus-kube-stack] helm upgrade error, Duplicate value: "http-metrics"

### ISSUE THREAD

**Issue by pOH7** [prometheus-community/helm-charts#2496]
### Describe the bug a clear and concise description of what the bug is.

```
helm upgrade --debug prom prometheus-community/kube-prometheus-stack --namespace prometheus
```
```
upgrade.go:434: [debug] warning: Upgrade "prom" failed: cannot patch "prom-kube-prometheus-stack-kube-etcd" with kind Service: Service "prom-kube-prometheus-stack-kube-etcd" is invalid: spec.ports[1].name: Duplicate value: "http-metrics"
Error: UPGRADE FAILED: cannot patch "prom-kube-prometheus-stack-kube-etcd" with kind Service: Service "prom-kube-prometheus-stack-kube-etcd" is invalid: spec.ports[1].name: Duplicate value: "http-metrics"
helm.go:84: [debug] cannot patch "prom-kube-prometheus-stack-kube-etcd" with kind Service: Service "prom-kube-prometheus-stack-kube-etcd" is invalid: spec.ports[1].name: Duplicate value: "http-metrics"
helm.sh/helm/v3/pkg/kube.(*Client).Update
	helm.sh/helm/v3/pkg/kube/client.go:274
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:376
runtime.goexit
	runtime/asm_amd64.s:1594
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.4.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1594
```

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.19"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:40:59Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack

### What's the chart version?

40.1.2

### What happened?

I want to add a exporter to prometheus, then I execute the command 
```
helm upgrade --debug prom prometheus-community/kube-prometheus-stack --namespace prometheus  --values values.yaml
```
and response
```
Error: UPGRADE FAILED: cannot patch "prom-kube-prometheus-stack-kube-etcd" with kind Service: Service "prom-kube-prometheus-stack-kube-etcd" is invalid: spec.ports[1].name: Duplicate value: "http-metrics"
```

### What you expected to happen?

upgrade success

### Enter the changed values of values.yaml?

```
    additionalScrapeConfigs:
      - job_name: router-node-exporter
        scrape_interval: 5s
        static_configs:
          - targets: ['192.168.1.2:9100']
```

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prom prometheus-community/kube-prometheus-stack --namespace prometheus --values values.yaml

**Comment by pOH7** [comment]
It's ok after uninstall

**Comment by BeyondEvil** [comment]
> It's ok after uninstall

Would you mind detailing how you solved this @pOH7 ?

What exactly did you uninstall?

**Comment by pOH7** [comment]
> 

follow the [README.md](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#uninstall-helm-chart)
```
helm uninstall prom --namespace prometheus

kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd probes.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com
```

**Comment by BeyondEvil** [comment]
> > 
> 
> follow the [README.md](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#uninstall-helm-chart)
> 
> ```
> helm uninstall prom --namespace prometheus
> 
> kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
> kubectl delete crd alertmanagers.monitoring.coreos.com
> kubectl delete crd podmonitors.monitoring.coreos.com
> kubectl delete crd probes.monitoring.coreos.com
> kubectl delete crd prometheuses.monitoring.coreos.com
> kubectl delete crd prometheusrules.monitoring.coreos.com
> kubectl delete crd servicemonitors.monitoring.coreos.com
> kubectl delete crd thanosrulers.monitoring.coreos.com
> ```

Thanks!

**Comment by Atomique** [comment]
Had the same issue. Wonder why I am forced to reinstall if I just want to upgrade to a new version.
