### ISSUE TITLE
ValidationError(Prometheus.spec.remoteWrite[0].sigv4): unknown field "role_arn" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.sigv4

### ISSUE THREAD

**Issue by Raji0196** [prometheus-community/helm-charts#2508]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to push metrics with kube-prometheus-stack chart from eks (AWS Account A) to another AWS account (AWS Account B) where the helm installation is not accepting the value file mentioned below. It's throwing errors for "role_arn" and "statefulSet" as it is not available in this chart. Is there any other key that can i use for role_arn.

ERROR:

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.remoteWrite[0].sigv4): unknown field "role_arn" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.sigv4, ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "statefulSet" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite]

ValueFile:

prometheus:
  serviceAccount:
    create: true
    name: "amp-iamproxy-ingest-service-account"
    annotations:
      eks.amazonaws.com/role-arn : "arn:aws:iam::784559426234:role/EKS-AMP-ServiceAccount-Role"
  prometheusSpec:
    remoteWrite:
      - url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/$WORKSPACE_ID/api/v1/remote_write
        sigv4:
          region: us-east-1
          role_arn: arn:aws:iam::$CENTRAL_ACCOUNT_ID:role/EKS-AMP-Central-Role
        queueConfig:
          maxSamplesPerSend: 1000
          maxShards: 200
          capacity: 2500
        statefulSet:
            enabled: "true"
prometheusOperator:
  namespaces:
    releaseNamespace: true
    additional:
      - matrixx
prometheus-node-exporter:
    prometheus:
    monitor:
      enabled: true

Here is the AWS link which i referred but it is for Prometheus chart. I need to do the same wiith kube-prometheus-stack chart.

https://aws.amazon.com/blogs/opensource/setting-up-cross-account-ingestion-into-amazon-managed-service-for-prometheus/

Find the value file under section - Deploying Prometheus server — account A only

### What's your helm version?

3.9.2

### What's your kubectl version?

v1.24.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

39.5.0

### What happened?

I'm trying to push metrics with kube-prometheus-stack chart from eks (AWS Account A) to another AWS account (AWS Account B) where the helm installation is not accepting the value file mentioned below. It's throwing errors for "role_arn" and "statefulSet" as it is not available in this chart. Is there any other key that can i use for role_arn.

ERROR:

Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Prometheus.spec.remoteWrite[0].sigv4): unknown field "role_arn" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite.sigv4, ValidationError(Prometheus.spec.remoteWrite[0]): unknown field "statefulSet" in com.coreos.monitoring.v1.Prometheus.spec.remoteWrite]

ValueFile:

prometheus:
  serviceAccount:
    create: true
    name: "amp-iamproxy-ingest-service-account"
    annotations:
      eks.amazonaws.com/role-arn : "arn:aws:iam::784559426234:role/EKS-AMP-ServiceAccount-Role"
  prometheusSpec:
    remoteWrite:
      - url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/$WORKSPACE_ID/api/v1/remote_write
        sigv4:
          region: us-east-1
          role_arn: arn:aws:iam::$CENTRAL_ACCOUNT_ID:role/EKS-AMP-Central-Role
        queueConfig:
          maxSamplesPerSend: 1000
          maxShards: 200
          capacity: 2500
        statefulSet:
            enabled: "true"
prometheusOperator:
  namespaces:
    releaseNamespace: true
    additional:
      - matrixx
prometheus-node-exporter:
    prometheus:
    monitor:
      enabled: true

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus -n prometheus prometheus-community/kube-prometheus-stack -f value.yaml --set alertmanager.enabled=false --set grafana.service.type=LoadBalancer --set nameOverride=prometheus --set kubelet.serviceMonitor.https=true --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false --version 39.5.0

**Comment by wyattkwan** [comment]
I just had the same issue. You need to change `role_arn` to `roleArn`. 

```
    remoteWrite:
    - url: ${AMP_REMOTE_WRITE}
      sigv4:
        region: us-east-1
        roleArn: ${AMP_IAM_ROLE_ARN}
```
