### ISSUE TITLE
[prometheus-kube-stack] Add custom labels to generated dashboard.

### ISSUE THREAD

**Issue by Jean-Daniel** [prometheus-community/helm-charts#2510]
### Is your feature request related to a problem ?

I'm using dashboards sidecar in grafana to import all dashboards in my cluster, and I'm using the sidecar `folderAnnotation` to group dashboards in Grafana.

My main issue with dashboards generated by prometheus-kube-stack, is that I can't specify a custom label to define the folder they should be stored in Grafana.

### Describe the solution you'd like.

Something like grafana.dashboardsLabels which could be used to add extra labels to each dashboard.

### Describe alternatives you've considered.

NONE

**Comment by from-nibly** [comment]
You'd also want to be able to change the title of the charts. otherwise you might end up with duplicate information between the title and the folder.

It'd also be cool if there was a grafana.heirarchicalDashboards or something to just switch the titles into proper folders.

**Comment by cmergenthaler** [comment]
We are also facing the same issue. Did you manage to solve it somehow?

**Comment by Jean-Daniel** [comment]
I'm post processing the files. My resource generation workflow is using `helm template` to generate the file, and has the capability to patch the generated files, but it can probably be done too using the `helm` `--post-renderer` argument.

**Comment by cmergenthaler** [comment]
Quick update: I managed to put the generated dashboards into a custom common folder using the [annotation](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L817) helm value. This adds custom annotations to the generated configmaps (e.g. [alertmanager configmap](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/alertmanager-overview.yaml#L13)). Hope this helps others too.
