### ISSUE TITLE
[kube-prometheus-stack] validation and mutation webhook failurePolicy OutOfSync

### ISSUE THREAD

**Issue by insider89** [prometheus-community/helm-charts#2516]
### Describe the bug a clear and concise description of what the bug is.

When install `prometheus-kube-stack` with ArgoCD, it become OutOfSync, cause `admissionWebhooks.failurePolicy` and `admissionWebhooks.patch.enabled` produce different values.
In the webhooks configuration we have [following condition](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml#L16-L19):
```
{{- if .Values.prometheusOperator.admissionWebhooks.patch.enabled  }}
    failurePolicy: Ignore
    {{- else }}
    failurePolicy: {{ .Values.prometheusOperator.admissionWebhooks.failurePolicy }}
    {{- end }}
```
By this one we should have failure policy `Ignore`. But, as we have `prometheusOperator.admissionWebhooks.patch.enabled : true` we are running [patch job](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml#L45), which change policy to `Fail` and leave ArgoCD OutofSync.

<img width="1617" alt="Screenshot 2022-10-03 at 12 09 06" src="https://user-images.githubusercontent.com/17744154/193541112-e523cbe9-2051-4bac-936b-9b005fc3f75b.png">

### What's your helm version?

3.8.0

### What's your kubectl version?

1.22.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

40.2.0

### What happened?

ArgoCD leave OutOfSync state after sync finish.leaves

### What you expected to happen?

ArgoCD leave in Sync state.leaves

### How to reproduce it?

Install latest chart with ArgoCD.

### Enter the command that you execute and failing/misfunctioning.

ArgoCD version: 2.4.12

**Comment by dmvk** [comment]
Running into the same issue. 😢

**Comment by marcofranssen** [comment]
Resolved it with #2528 for our deployment.

**Comment by dmvk** [comment]
@monotek @marcofranssen Can you please shed some on how https://github.com/prometheus-community/helm-charts/pull/2528 resolves this?

**Comment by lllsJllsJ** [comment]
@dmvk Any solution you found?

**Comment by HuTiuOnTheCloud** [comment]
how about change {{ .Values.prometheusOperator.admissionWebhooks.failurePolicy }}: Fail -> Ignore ??
