### ISSUE TITLE
fullnameOverride for prometheus/kube-state-metrics is not taking any effect

### ISSUE THREAD

**Issue by rohsaini** [prometheus-community/helm-charts#2517]
### Describe the bug a clear and concise description of what the bug is.

fullnameOverride for kube-state-metrics is not taking any effect and is showing default name only for kube-state-metrics pod.

I'm installing prometheus chart, which in turn is installing the child chart of kube-state-metrics chart. My intention is to override the the fullname of kube-state-metrics from prometheus main values.yaml.

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:13:07Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-15.3.0.tgz

### What's the chart version?

15.3.0

### What happened?

ubuntu@rsainiMaster0:~$ kubectl get pods -o wide -n a5g
NAME                                         READY   STATUS    RESTARTS   AGE   IP              NODE            NOMINATED NODE   READINESS GATES
anon-consul-server-0                         1/1     Running   0          42s   10.196.0.13     rsainimaster0   <none>           <none>
anon-consul-sync-catalog-6cdbdc6b7c-q2r5m    1/1     Running   0          43s   10.196.1.39     rsainiworker0   <none>           <none>
anon-elastic-master-0                        0/1     Running   0          42s   10.196.0.14     rsainimaster0   <none>           <none>
anon-grafana-77c45ddf75-7b9rq                1/1     Running   0          43s   10.196.1.36     rsainiworker0   <none>           <none>
anon-infra-ctrl-timer-0                      3/3     Running   0          42s   10.196.1.35     rsainiworker0   <none>           <none>
anon-kibana-697ff685b8-4rz2x                 0/1     Running   0          43s   10.196.1.38     rsainiworker0   <none>           <none>
anon-prometheus-node-exporter-ftzcl          1/1     Running   0          43s   172.31.51.221   rsainimaster0   <none>           <none>
anon-prometheus-node-exporter-rvpnv          1/1     Running   0          43s   172.31.48.136   rsainiworker0   <none>           <none>
anon-prometheus-server-647d49fcdd-hsz5d      2/2     Running   0          43s   10.196.0.12     rsainimaster0   <none>           <none>
anon-redis-master-0                          1/1     Running   0          43s   10.196.1.34     rsainiworker0   <none>           <none>
infra1-kube-state-metrics-78fbd89cdc-562mk   1/1     Running   0          43s   10.196.1.37     rsainiworker0   <none>           <none>  **<<<<<<< This should have been anon-prometheus-kube-state-metrics-<something>**

### Enter the changed values of values.yaml?

prometheus:
  fullnameOverride: "anon-prometheus"
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: true
    #TODO: fullnameOverride is not working
    kube-state-metrics:
      fullnameOverride: "anon-prometheus-kube-state-metrics"
  nodeExporter:
    enabled: true
    fullnameOverride: "anon-prometheus-node-exporter"
  pushgateway:
    enabled: false
  server:
    enabled: true
    fullnameOverride: "anon-prometheus-server"
    replicaCount: 1
    configPath: /etc/anon/config/prometheus.yml
    #service:
      #type: LoadBalancer
      #loadBalancerIP:
    persistentVolume:
      enabled: true
      storageClass: "anon-storage-prom"
      size: 1Gi
    extraConfigmapMounts:
      - name: anon-prom-cm
        mountPath: /etc/anon/config/prometheus.yml
        subPath: prometheus.yml
        configMap: anon-prom-cm

### Enter the command that you execute and failing/misfunctioning.

Normal helm install command.

**Comment by dotdc** [comment]
Hi @rohsaini,

Sorry I missed the notification for this issue, will have a look at it tonight or tomorrow.

**Comment by rohsaini** [comment]
Hi @dotdc ,
I tried with kube-state-metrics 4.22.1 in prometheus, I still see same issue. My chart values for prometheus are below. 
Other than kubeStateMetrics, remaining prometheus components are honouring the fullnameOverride. 
Please let me know if you need any more details.
My prometheus chart version is prometheus-15.3.0

`# --- Prometheus Sub-chart parameters --- #
prometheus:
  fullnameOverride: "anon-prometheus"
  alertmanager:
    enabled: false
  kubeStateMetrics:
    enabled: true
    kube-state-metrics:
      fullnameOverride: "anon-prometheus-kube-state-metrics"
  nodeExporter:
    enabled: true
    fullnameOverride: "anon-prometheus-node-exporter"
  pushgateway:
    enabled: false`

**Comment by finzzz** [comment]
same with node-exporter

**Comment by rohsaini** [comment]
@dotdc This was my issue. I was specifying configuration in wrong way in my values.yaml. Closing the issue. Thanks for your help.
