### ISSUE TITLE
Prometheus Kube (Helm Chart 40.x) When will 2.39 be included as this has some serious bug fixes

### ISSUE THREAD

**Issue by mkocaks** [prometheus-community/helm-charts#2527]
### Is your feature request related to a problem ?

Prometheus 2.39 fixes issues with start up (Magic Number Bug, WAL replay timing, Memory optimisations and more..)
When is it to be included in the next release for the Helm Chart

### Describe the solution you'd like.

When is it to be included in the next release for the Helm Chart

### Describe alternatives you've considered.

Workaround by clearing the chunk files on start up is not great :-(

**Comment by mkocaks** [comment]
THANK YOU!!

**Comment by davidpellcb** [comment]
came here looking for a way to enable the "TSDB: Add support for ingesting out-of-order samples." Is that supported now in kube-prometheus-stack via values??
