### ISSUE TITLE
[prometheus-smartctl-exporter] Chart references missing file rules.txt

### ISSUE THREAD

**Issue by djjudas21** [prometheus-community/helm-charts#2543]
### Describe the bug a clear and concise description of what the bug is.

When deploying the smartctl-exporter, setting

```yaml
prometheusRules:
  enabled: true
```

causes deployment to fail with this error:

```
Error: UPGRADE FAILED: failed to create resource: PrometheusRule.monitoring.coreos.com "prometheus-smartctl-exporter.rules" is invalid: spec.groups[0].rules: Required value
```

The root cause is that the Helm chart tries to import a file `rules.txt` which does not exist, and therefore renders an empty ruleset.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-smartctl-exporter/templates/prometheusrule.yaml#L17

I assume `rules.txt` existed before the chart was imported from its previous repo? Please could you add the contents of `rules.txt` to this `PrometheusRule` so it renders a valid ruleset? Thanks.

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-29T07:03:08Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-smartctl-exporter

### What's the chart version?

v0.1.1

### What happened?

Helm created an empty PrometheusRule object

### What you expected to happen?

Helm should create a PrometheusRule object which at least one rule in it

### Enter the changed values of values.yaml?

```yaml
prometheusRules:
  enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

```sh
helm upgrade -i --create-namespace \
    -n monitoring prometheus-smartctl-exporter \
    -f values.yaml \
    prometheus-community/prometheus-smartctl-exporter
```

**Comment by kfox1111** [comment]
Ah. good catch. Yeah, it was dropped when imported from my other repo. I have a 0.8.0 release just about ready to go. PR is here: https://github.com/prometheus-community/helm-charts/pull/2530

I'll just add the fix to that PR.

**Comment by djjudas21** [comment]
Nice one, thanks

**Comment by monotek** [comment]
fixed with: https://github.com/prometheus-community/helm-charts/issues/2543
