### ISSUE TITLE
[prometheus-kube-stack] values.yaml not updated to reflect new component versions

### ISSUE THREAD

**Issue by centromere** [prometheus-community/helm-charts#2545]
### Describe the bug a clear and concise description of what the bug is.

`values.yaml` [still specifies `v0.59.2`](https://github.com/prometheus-community/helm-charts/blob/8c15d58d0cda4b0cb05fb438c5cbc70ca5e0bfeb/charts/kube-prometheus-stack/values.yaml#L1862) as the image tag for `prometheus-operator` instead of `v0.60.1`. For prometheus, [it specifies](https://github.com/prometheus-community/helm-charts/blob/8c15d58d0cda4b0cb05fb438c5cbc70ca5e0bfeb/charts/kube-prometheus-stack/values.yaml#L2328) `v2.39.0` instead of `v2.39.1`.

### What's your helm version?

`version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.19.1"}`

### What's your kubectl version?

`Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-25T19:07:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}`

### Which chart?

prometheus-kube-stack

### What's the chart version?

41.0.0

### Enter the command that you execute and failing/misfunctioning.

-

**Comment by monotek** [comment]
will be fixed in: https://github.com/prometheus-community/helm-charts/pull/2546
