### ISSUE TITLE
[kube-prometheus-stack] Name overrides cause webhook calls to fail

### ISSUE THREAD

**Issue by weeco** [prometheus-community/helm-charts#257]
**Describe the bug**
Since all pod-names were prefixed with `kube-prometheus-stack` which is quite long I wanted to use `kps` as a shorter prefix. Therefore I set `fullnameOverride: kps` in the values.yaml .  The following error appears during the helm installation:

Error: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://kube-prometheus-stack-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=30s: service "kube-prometheus-stack-operator" not found

Generally it seems like that the `fullnameOverride` property is not populated into all subcharts. I checked the running pods after the helm installation failed and some pods still have the default prefix, e.g.:

- kube-prometheus-stack-kube-state-metrics-bbf56d7f5-ddkb7
- kube-prometheus-stack-prometheus-node-exporter-2pxrs

**Version of Helm and Kubernetes**:

Helm Version: v3.2.4

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

```

Kubernetes Version:

```console
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: `kube-prometheus-stack`
**Which version of the chart**: `10.1.2`

In case it matters: This is applied via the Terraform Helm provider which however utilizes helm under the hood.

**What happened**:
Helm installation failed with custome name override.

**What you expected to happen**:
Helm installation succeeds and prefixes of all kubernetes resources change to my new name override.

**How to reproduce it** (as minimally and precisely as possible):

Deploy the chart as usual and use this name override.

```yaml
fullnameOverride: kps
```

-->

**Anything else we need to know**:

**Comment by fktkrt** [comment]
Hey @weeco, please take a look at https://github.com/prometheus-community/helm-charts/issues/142
I think it can be related, and it's not an issue related to `fullnameOverride`.
