### ISSUE TITLE
go package Vulnerability observed in promethus/grafana for alertmanager

### ISSUE THREAD

**Issue by golakotigopala** [prometheus-community/helm-charts#2578]
While scanning by using twist locks , we have observed few go package vulnerabilities for the alert manger

prometheus/alertmanager version : v0.24.0

Description: In net/http in Go before 1.18.6 and 1.19.x before 1.19.1, attackers can cause a denial of service because an HTTP/2 connection can hang during closing if shutdown were preempted by a fatal error.

Alert manger is using 1.17 version to compile the binary and this have the following CVE
https://github.com/advisories/GHSA-69cg-p879-7622

Do you have any plan to release alertmanager version with the latest go package version of 1.19.1?

**Comment by longwuyuan** [comment]
Hi, 
- Alertmanager is not maintained in this project
- THere will be a release soon with go bumped to v1.19.2

**Comment by hpvd** [comment]
there is an overview what else needs a bumped version in https://github.com/prometheus-community/helm-charts/issues/2582

**Comment by monotek** [comment]
same as in: https://github.com/prometheus-community/helm-charts/issues/2582#issuecomment-1282213214

closed.
