### ISSUE TITLE
[kube-prometheus-stack] 50 fixable vulnerabilities unfixed

### ISSUE THREAD

**Issue by hpvd** [prometheus-community/helm-charts#2582]
### Is your feature request related to a problem ?

since we are planning to move to kube-prometheus-stack,

we did a quick look at the security scan of the latest helmchart (v41.5) offert by artifacthub.io
(they use the trivy engine)

The summarizing results show:
**78 vulnerabilities (50 fixable)** have been detected in this package's images.

They have different levels from Critical to Low, and are distributed across all images within this chart.
The good thing: **50 of them are fixable** with a version bump.

for details see:
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=security-report

### Describe the solution you'd like.

use latest versions where possible

![2022-10-18_11h20_17](https://user-images.githubusercontent.com/5681880/196395385-1f0d09c9-a052-4acb-9e00-be66207362da.png)

**Comment by hpvd** [comment]
for overview:
![2022-10-18_11h21_09](https://user-images.githubusercontent.com/5681880/196395590-b01735fe-8554-451c-9eb2-78d2a3e2b5de.png)

**Comment by hpvd** [comment]
more details like CVE numbers and which version fixes it are provided in detail on
https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=security-report

**Comment by z0rc** [comment]
It doesn't make any sense to provide these reports for helm chart. Please forward this to identified project.

**Comment by hpvd** [comment]
thanks for your idea. Im not sure about this if there is the only place to report.

The report shows that the versions within this helm chart contains vulnerabilities
e.g. when looking at grafana:
the helm chart includes an image of v9.17
while latest avialable grafana version, which may fix some of the found vulnerabilities is 9.20
(e.g. Security: Fix https://github.com/advisories/GHSA-69cg-p879-7622. https://github.com/grafana/grafana/pull/55361, [@yong-jie-gong](https://github.com/yong-jie-gong)
see https://github.com/grafana/grafana/releases

**Comment by monotek** [comment]
what @z0rc says....
