### ISSUE TITLE
[all] Common implementation for k8s 1.25+ PSS 

### ISSUE THREAD

**Issue by zanhsieh** [prometheus-community/helm-charts#2589]
### Is your feature request related to a problem ?

As K8S official documentation, PSP deprecation announced here:

https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

One of successors is PodSecurityStandard (PSS):

https://kubernetes.io/docs/concepts/security/pod-security-standards/

This issue is to discuss the implementation correctness of PSS with Helm chart.

### Describe the solution you'd like.

The main workflow currently is:

v1.0 -> v1.1 -> create sa, clusterrole, clusterrolebinding -> run `kubectl label ns <desired_ns>`

The concept mainly takes from the link below with helm lifecycle management:

https://craftech.io/blog/release-lifecycle-management-with-helm/

Detail implementation here:

https://github.com/helm/helm/issues/11448#issuecomment-1284722641

Note that if I did try put them into `pre-upgrade` and / or `pre-install` but the installation was hanging forever.

Please let me know if my implementation / understanding / testing has some problem. 🙇 🙇 🙇 

cc @monotek @torstenwalter @scottrigby 

### Describe alternatives you've considered.

NONE

**Comment by monotek** [comment]
If we want to introduce chart standards i would use a common libary chart, like bitnami does.

But imho thata would be a huge change to all charts so i would not do it.

Also policies might be alread y in place via kyverno or open policy agent so i would not introduce this per se for all charts.
