### ISSUE TITLE
[kube-prometheus-stack] cAdvisor missing metrics - how to query container cpu usage percentage

### ISSUE THREAD

**Issue by orong-pp** [prometheus-community/helm-charts#2603]
### Describe the bug a clear and concise description of what the bug is.

I recently upgraded my kube-prometheus-stack chart to the latest version (from version 24.0.1 to version 41.5.0)
I had working queries in my dashboards for CPU usage percent per container
and now after the upgrade some of the metrics are missing and the queries don't work anymore

the missing metrics are:
`container_spec_cpu_quota`
`container_spec_cpu_period`

they used to come from the cAdvisor (kubelet job) and now are blocked by relabeling (drop) of container_spec.*
what metrics replace these?

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.5.0

### What happened?

the full query I'm running (worked in version 24 of the chart) is the following (get cpu usage percent by pod and container)
```
avg(
   (sum by(pod, container) (rate(container_cpu_usage_seconds_total{image!="", container!="POD"}[5m]))
  / sum by(pod, container) (     container_spec_cpu_quota{image!="", container!="POD"}
                                             / container_spec_cpu_period{image!="", container!="POD"}) * 100)
  ) by (container,pod)
```

yes I am aware that I get only containers with cpu limits set, and no limit containers are dropped, that's fine by me

### What you expected to happen?

the comment in the relabeling of cAdvisor metrics says that container_spec.* metrics are available in kube-state-metrics
but I couldn't find a match for these metrics 

`container_spec_cpu_quota`
`container_spec_cpu_period`

and I'm left with a broken query I want to fix

### How to reproduce it?

try to run this query

```
avg(
   (sum by(pod, container) (rate(container_cpu_usage_seconds_total{image!="", container!="POD"}[5m]))
  / sum by(pod, container) (     container_spec_cpu_quota{image!="", container!="POD"}
                                             / container_spec_cpu_period{image!="", container!="POD"}) * 100)
  ) by (container,pod)
```

works in version 24.0.1 but not in 41.5.0

### Enter the command that you execute and failing/misfunctioning.

avg(
   (sum by(pod, container) (rate(container_cpu_usage_seconds_total{image!="", container!="POD"}[5m]))
  / sum by(pod, container) (     container_spec_cpu_quota{image!="", container!="POD"}
                                             / container_spec_cpu_period{image!="", container!="POD"}) * 100)
  ) by (container,pod)

**Comment by orong-pp** [comment]
looks like the replacement for the whole expression 
`container_spec_cpu_quota{image!="", container!="POD"} / container_spec_cpu_period{image!="", container!="POD"}`

is: `kube_pod_container_resource_limits{resource="cpu"}`

and so there is a replacement to the devision expression although there is no replacement for each of them individually

**Comment by juliorenner** [comment]
@orong-pp do you mind sharing where you found that? Are there any release notes I can take a look at on metrics that are deprecated/removed?

**Comment by orong-pp** [comment]
Hi @juliorenner I shared in my previous message that I found the metrics that replaced the missing ones
