### ISSUE TITLE
[kube-prometheus-stack] Simplified service names boolean

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#2614]
### Is your feature request related to a problem ?

For the actual services created by the kube-prometheus-stack chart, it would be helpful if I could create simplified service names.

### Describe the solution you'd like.

A chart boolean that makes the service names un-prefixed.

For the non service elements, I'd actually like to keep the `kube-prometheus-stack` prefix.  Particularly if it makes upgrades of the chart easier.

### Describe alternatives you've considered.

cleanPrometheusOperatorObjectNames = true

### Additional context.

I'm new to prometheus, helm, k8s, charts, and the whole ecosystem.    The comment in the values.yml makes me nervous about how best to get clean service names without risking breakage at upgrade time.

**Comment by XtremeOwnageDotCom** [comment]
Not sure if this helps you or not- but, I recently stumbled upon this issue....

I found its actually pretty easy to resolve-

For services from subcharts-  
* `Values.grafana.fullnameOverride=grafana`
* `Values.prometheus-node-exporter.fullnameOverride=node-exporter`
* `Values.kube-state-metrics.fullnameOverride=kube-state-metrics`
in your helm values.yaml. That easy.  This gives the services/pods/etc for those subcharts the name you specified.

For everything else which is defined in the main chart/template-

For alert manager- Looking at the [Template](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=template&template=alertmanager/service.yaml), I determined it was building the name from [This Helper](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack?modal=template&template=_helpers.tpl&line=14). As such, it will always have some form of prefix.

However, setting fullnameOverride: "monitoring" at the top level of values.yaml- produces service names which are much cleaner then the default, IMO.

![image](https://user-images.githubusercontent.com/5262735/200631192-aa6d103f-e43f-436b-92f3-24c3655b7330.png)


After doing these steps, I went from having...

![image](https://user-images.githubusercontent.com/5262735/200625823-c160616e-1b55-4746-b5a9-5a2697dc2997.png)

To having....

![image](https://user-images.githubusercontent.com/5262735/200635393-071e7bad-8d36-497e-ad30-653d5df776eb.png)

Oh- I will note- setting the fullNameOverride, did provision a new PVC, causing loss of data.. So, be aware.

**Comment by XtremeOwnageDotCom** [comment]
Yup. because, just closing it as completed, after nobody ever took the time to even comment on it, that's how to make your repo look productive. /s.
