### ISSUE TITLE
[kube-prometheus-stack] Data is lost after upgrade

### ISSUE THREAD

**Issue by stefnats** [prometheus-community/helm-charts#2620]
Hey there.

After upgrading with this command:

```
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack \  
  --namespace kube-prometheus-stack \
  --values monitoring/helm_values.yaml
```

all data is wiped. That includes:

- Custom Alerts
- Imported Dashboard
- Starred Dashboards
- Additional Datasources
etc.

What can i do to persist data so that all data is kept even after the upgrade?

**Comment by monotek** [comment]
I doubt that. I've updated today.

Seems you talking about Grafana content?
Please be aware that their default config does not have persistence enabled.
See: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L297-L299

**Comment by stefnats** [comment]
@monotek it seems like it's some kind of related thing, but your link is for the grafana chart and not for the kube-prometheus-stack
@WilliamCassanova i think it's not related, because i use only the admin-user. Or am i mistaken?!

**Comment by stefnats** [comment]
Just a quick follow-up:

@monotek 's suggestion was correct. adding the `persist: true` to the helm values yaml did the trick.
