### ISSUE TITLE
Ha doesn't work correctly

### ISSUE THREAD

**Issue by emahdij** [prometheus-community/helm-charts#2622]
### Describe the bug a clear and concise description of what the bug is.

Hi
I changed the replica to 2. but I got an error that said can't resolve another instance of the alert manager.
```
msg=refresh result=failure addr=alertmanager-mw-0.alertmanager-mw-headless:9094 err="1 error occurred:\n\t* Failed to resolve alertmanager.alertmanager-headless:9094: lookup alertmanager.alertmanage-headless on 10.96.0.10:53: no such host\n\n"
```
I can curl the addresses from another pod in the same namespace but I got an error in the alert manager logs.

### What's your helm version?

v3.8.0

### What's your kubectl version?

v1.21.0

### Which chart?

alertmanager

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

 helm upgrade alertmanager-mw -n alertmanager -f values-production.yaml ../alertmanager

**Comment by sam-mcbr** [comment]
Did this ever get resolved? I am also seeing this issue when trying to deploy HA
