### ISSUE TITLE
helm not deployed the pod

### ISSUE THREAD

**Issue by jjjan** [prometheus-community/helm-charts#263]
**Describe the bug**
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable i
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use netwo

**Version of Helm and Kubernetes**:

Helm Version:
3
```console
$ helm version
please put the output of it here
```

Kubernetes Version:

```console
$ kubectl version
please put the output of it here
```

**Which chart**:
**Which version of the chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

<~--
This could be something like:

values.yaml (only put values which differ from the defaults)

```
key: value
```

```
helm install my-release prometheus-community/name-of-chart --version version --values values.yaml
```

-->

**Anything else we need to know**:

**Comment by monotek** [comment]
Please use the issue template properly.
It's not even clear which chart you use.

**Comment by jjjan** [comment]
i used " https://prometheus-community.github.io/helm-charts"
after that i got this error on helm manifest. is it clear?

**Comment by monotek** [comment]
> i used " https://prometheus-community.github.io/helm-charts"
Thats the chart repo not the name.

Please edit you inital post and fill out all fields. 
Otherwise we have to close the issue.

**Comment by jjjan** [comment]
Describe the bug
no pod create and status just hold in deployed

Version of Helm and Kubernetes:



$ helm version
3

Kubernetes Version:

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

please put the output of it here


Which chart: prometheus-community/prometheus
Which version of the chart:11.16.5         
App version:2.21.0

What happened:
this is helm chart manifest of prometheus-community/prometheus shows this error and helm satatus show prometheus hold in deployed.
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable i
Warning: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use netwo

What you expected to happen:



How to reproduce it (as minimally and precisely as possible):

<~--
