### ISSUE TITLE
prometheus-kube-stack helm install results in unknown field "enableHttp2"

### ISSUE THREAD

**Issue by seanrclayton** [prometheus-community/helm-charts#2633]
### Describe the bug a clear and concise description of what the bug is.

Attempting Fresh install of the prometheus-kube-stack

 results in: 

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints
```

### What's your helm version?

3.6.3

### What's your kubectl version?

1.20.6

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.2

### Enter the changed values of values.yaml?

grafana.enabled:false

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.enabled=false

### Anything else we need to know?

Perhaps related to to [this commit](https://github.com/prometheus-community/helm-charts/commit/6c975ee8567869542a56e05a01e2ff1a9a63b995)

which removed the conditional, and  instead  set `alertmanager.serviceMonitor.enableHttp2` to `true`  in  `values.yaml` 

I can install the chart this way (using the previous minor version):

`helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set grafana.enabled=false --set enableHttp2=false --version 41.7.0` I do not get the error, and I have seen no issues.

**Comment by wjentner** [comment]
The last working version is `41.7.0`.
`41.7.1` and `41.7.2` both show the error.

**Comment by KosShutenko** [comment]
I have the same issue with Prometheus installed via FluxCD

**Comment by exherb** [comment]
upgrade crd manually https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-servicemonitors.yaml

**Comment by monotek** [comment]
@seanrclayton
It's also described in the upgrading docs like this. 
See: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#from-40x-to-41x

**Comment by seanrclayton** [comment]
@monotek Thank you for the information. Upgrading the CRD manually is a reasonable step to do. However  Since I was not upgrading, the section in which the CRD suggested to update, was not on my radar. It may be useful to update the helm chart's README, perhaps under prerequisites - I am more than happy to PR that change if this will be the way to install this chart from scratch going forward.

**Comment by monotek** [comment]
Sure :)

**Comment by trallnag** [comment]
Since I'm deploying the chart with Terraform I encountered another error trying to upgrade the CRDs manually:

```
error: Apply failed with 1 conflict: conflict with "terraform-provider-helm_v2.7.0_x5" using apiextensions.k8s.io/v1: .metadata.annotations.controller-gen.kubebuilder.io/version
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
```

Using `--force-conflicts` helped.

**Comment by hyorch** [comment]
Found same error upgrading from old Prometheus installation usim helm chart.
Solution: uninstall prometheus with helm, manually delete CRDs (see link) and install again from scratch.
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#uninstall-helm-chart
