### ISSUE TITLE
[prometheus-kube-stack] unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints

### ISSUE THREAD

**Issue by ketanskanade** [prometheus-community/helm-charts#2635]
### Describe the bug a clear and concise description of what the bug is.

While deploying a Kube-Prometheus-Stack helm chart in Kubernetes cluster I am facing an error :

```
# helm install prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints
```

Help me solve this. Thanks in advance.

### What's your helm version?

3.10.0

### What's your kubectl version?

1.25.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.2

### What happened?

While installing a kube-prometheus-stack helm chart its failing with an error :

`# helm install prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints`

### What you expected to happen?

Expected result is to helm chart to be installed

### How to reproduce it?

By running below command 

# helm install prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml

### Enter the changed values of values.yaml?

enableHttp2: false

### Enter the command that you execute and failing/misfunctioning.

# helm install prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml

**Comment by Froxz** [comment]
Hi @ketanskanade see here: #2633

**Comment by ketanskanade** [comment]
@Froxz  After following the suggestion I landed up into below error :

`% helm install prometheus prometheus-community/kube-prometheus-stack -f prometheus-values.yaml --version 41.7.0    
Error: INSTALLATION FAILED: Get "https://github.com/prometheus-community/helm-charts/releases/download/kube-prometheus-stack-41.7.0/kube-prometheus-stack-41.7.0.tgz": dial tcp: lookup github.com on [::1]:53: read udp [::1]:57834->[::1]:53: read: connection refused`

**Comment by ketanskanade** [comment]
It worked after some hits. Thanks a lot for your suggestion.

**Comment by ketanskanade** [comment]
It worked after some Hits. Thanks a lot for your suggestion.

**Comment by Hexxaal** [comment]
Hi there, 
So as I understood the only way to go around this bug is to update manually CRDs ?

**Comment by Hexxaal** [comment]
All right thank you for your fast answer! Yes, I installed it from a fresh install either via ansible or normal Helm install, and it says same error as this post (why it brings me there). Si I will try the only way to solve  : update manually CRDs

**Comment by hyorch** [comment]
Found some error upgrading from old Prometheus installation.
Solution: uninstall prometheus, delete CRDs and install again.
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#uninstall-helm-chart

**Comment by ketanskanade** [comment]
Still facing an error :

unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints

**Comment by Froxz** [comment]
@ketanskanade @hyorch please use Issue to report [#2633](https://github.com/prometheus-community/helm-charts/issues/2633)

**Comment by mlaube** [comment]
the last error-free chart version: 41.7.0

**Comment by Crayeth** [comment]
fresh install on k3d w.
```
k3d version v5.4.6
k3s version v1.24.4-k3s1 (default)
---
NAME                                              	                             CHART VERSION	APP VERSION
grafana/loki                                      	                                 2.16.0       	v2.6.1
prometheus-community/kube-prometheus-stack        	41.7.4       	0.60.1
```
same error, can't install KPS
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints
```

**Comment by dromadaire54** [comment]
I have the same issue with the prometheus v45.4.0 `error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints`. I have a prometheus-crd helm chart with the version 2.0.0 which is the right version. In the servicemonitor crd the parameter `enableHttp2` exist.

**Comment by drogus** [comment]
I'm facing the same issue on v46.8.0 even on a fresh cluster install. I'm using ArgoCD

**Comment by rufreakde** [comment]
So for anyone coming across this issue as well. Manually you can alway replace the servicemonitor and all looks good but it is annoying. I was thinking of maybe using this:

https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
data:
...
  resource.customizations.ignoreDifferences.monitoring.coreos.com_ServiceMonitor: |
    jqPathExpressions:
    - .spec.endpoints
```

not sure if this will work though? I will try to set this in my cluster and check if this solves the issue in the long run clusterwide.
