### ISSUE TITLE
[ALL CHARTS] Chart releasing is failing due to GitHub org settings

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#2643]
Hi @brancz and @SuperQ 

(also asked in [Slack](https://cloud-native.slack.com/archives/C01AUBA4PFE/p1667497976058749))

## Problem

Helm chart releasing to OCI (#2454) is currently blocked, due to a package setting in [github.com/prometheus-community](https://github.com/prometheus-community) org setting. Even as a repo admin, or through a properly permissioned GH Action, package visibility can not be changed to public, because:
> “Setting is disabled by organization administrators.”
<img width="458" alt="Screen Shot 2022-11-03 at 2 08 40 PM" src="https://user-images.githubusercontent.com/407675/199801267-9222b951-a25f-4df3-a54e-407f21e35966.png">

## Proposed solution

Would one of you please allow this setting in the prometheus-community org?
<img width="917" alt="Screen Shot 2022-11-02 at 5 58 32 PM" src="https://user-images.githubusercontent.com/407675/199799674-33013836-7928-4d78-835a-869181093f6f.png">

Thank you!

**Comment by SuperQ** [comment]
Ok, I think I fixed it so you can set the packages to public.

**Comment by scottrigby** [comment]
It worked! Thanks @SuperQ 💖

**Comment by monotek** [comment]
There seems still to be an issue: https://github.com/prometheus-community/helm-charts/actions/runs/3401811964/jobs/5657168212

**Comment by sereinity** [comment]
And here: https://github.com/prometheus-community/helm-charts/actions/runs/3443736059/jobs/5745583784
