### ISSUE TITLE
Add custom label in prometheus-elasticsearch-exporter

### ISSUE THREAD

**Issue by sabz90** [prometheus-community/helm-charts#2646]
I have multiple elasticsearch clusters running in different namespaces. However, the name of the cluster is the same "elasticsearch".

When I use this prometheus-elasticsearch-exporter (one instance per cluster), I can't differentiate between the different elasticsearch clusters from the metrics because the cluster name is the same.

Is there a way to include a custom label that can be added in every metric, that can help in differentiating clusters?

**Comment by zeritti** [comment]
You could use `relabeling` in your [service monitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor), if using Prometheus operator. If not, the same can be done with Prometheus' [relabel_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). That would make Prometheus attach a label to each target endpoint and to each time series coming out of that endpoint.

If you run one Elasticsearch cluster in a namespace, the namespace name would indeed identify the cluster - label `__meta_kubernetes_namespace` could then be used for creating a label of your choosing.

An example in case of a service monitor relabeling's element adding label `es_cluster`:
```
relabelings:
  - sourceLabels: [__meta_kubernetes_namespace]
    regex: ^(.*)$
    separator: ;
    targetLabel: es_cluster
    replacement: $1
```
