### ISSUE TITLE
Question - How to know which Grafana version i'm getting in each chart version

### ISSUE THREAD

**Issue by ZoharZrihen** [prometheus-community/helm-charts#2653]
Hi, sorry if this is a stupid question or if this is not the right place to ask:

I'm using prometheus-stack helm chart in version 36.0.2 and im getting Grafana in version 8.3.4.
I would like to update Grafana to newer version like 8.5.x but not to Grafana 9.x.x.
How can I know which helm chart version I need to use?
My friend is using the chart in version 36.2.0 and he is getting Grafana 9.x.x.

If this information is not mentioned anywhere, is it possible to mention it in the chart description?

Thanks in advance.

**Comment by zeritti** [comment]
I occasionally use Artifact Hub's [API](https://artifacthub.io/docs/api/), e.g.
```
ah_helm="https://artifacthub.io/api/v1/packages/helm/"
zzrepo="prometheus-community"
zzchart="kube-prometheus-stack"

# read all versions of the chart
$ curl -sL ${ah_helm}/${zzrepo}/${zzchart} \
  | jq -r '.available_versions[].version'
41.7.3
41.7.2
41.7.1
41.7.0
41.6.1
41.6.0
41.5.1
41.5.0
41.4.1
...

# reading version info and container images for the version, e.g. 36.3.0
$ curl -sL ${ah_helm}/${zzrepo}/${zzchart}/36.3.0 \
  | jq -r '.version,.app_version,.containers_images[].image'
36.3.0
0.57.0
quay.io/prometheus/node-exporter:v1.3.1
quay.io/kiwigrid/k8s-sidecar:1.19.2
grafana/grafana:9.0.1
registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
quay.io/prometheus-operator/prometheus-operator:v0.57.0
quay.io/prometheus/alertmanager:v0.24.0
quay.io/prometheus/prometheus:v2.36.1
```
with further processing as desired.

**Comment by ZoharZrihen** [comment]
very useful and exactly what I was looking for, many thanks!
