### ISSUE TITLE
[Prometheus] Standalone helm chart for Prometheus Server

### ISSUE THREAD

**Issue by ivyostosh** [prometheus-community/helm-charts#2654]
### Is your feature request related to a problem ?

Apologize if I missed this chart but I wasn't able to find one in this repo.

I want to use a helm chart that has solely the Prometheus Server image. The [Prometheus helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) is the closest to work with, but it has dependency on kube-state-metrics, and has additional component of alert-manager, node_exporter, and push gateway. 

It seems like this repo contains standalone helm chart for different exporters, so having a parallel standalone helm chart for Prometheus server will make sense as well.

### Describe the solution you'd like.

Have a standalone prometheus server helm chart.

### Describe alternatives you've considered.

Modify the [Prometheus helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus), but it's much easier to start from a cleaner state.

**Comment by zanhsieh** [comment]
@ivyostosh 
Just would like to let you know you are not the first one and the only one proposed this idea. See:

https://github.com/prometheus-community/helm-charts/pull/2627#issuecomment-1300167738
https://github.com/prometheus-community/helm-charts/pull/2627#issuecomment-1300192978

However, the following work should have:
1. Separate each chart under prometheus to each of their own repo.
2. Matching existing setting in values.yaml or at least making assembled charts work.

These two requirements are already a heavy-lifting. I would say it would take some time.

**Comment by arukiidou** [comment]
We can install standalone prometheus server, in this way

```console
helm install prometheus oci://ghcr.io/prometheus-community/charts/prometheus --set prometheus-pushgateway.enabled=false --set prometheus-node-exporter.enabled=false --set kube-state-metrics.enabled=false --set alertmanager.enabled=false
```

@zanhsieh @monotek 
This issue can closed, I thought. What do you think?
