### ISSUE TITLE
[prometheus-elasticsearch-exporter] user/pass from secret file

### ISSUE THREAD

**Issue by hedeesaa** [prometheus-community/helm-charts#2661]
### Describe the bug a clear and concise description of what the bug is.

On line [#96](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/values.yaml#L96) in `values.yaml` file, it says:  
`This will set ${ES_PASSWORD} to the 'password' key from the 'my-secret' secret`. But it is misleading. For using env values in the `es.uri` it must be with parentheses like `$(ES_PASSWORD)`.  

For example, the `es.uri` must be like this: 
`es.uri: https://$(ES_USERNAME):$(ES_PASSWORD)@<URL>:<port>`

It took me some time to fix the error, so it's worth fixing. 

### What's your helm version?

-

### What's your kubectl version?

-

### Which chart?

prometheus-elasticsearch-exporter

### What's the chart version?

-

### Enter the command that you execute and failing/misfunctioning.

-

**Comment by XiaoshiWang** [comment]
This issue saves me a lot of time debugging. Thank you for the issue and the comment in values.yaml is really misleading. Please change it
