### ISSUE TITLE
Error while serving metrics - Scrape multiple postgres datasources with postgresql exporter

### ISSUE THREAD

**Issue by kemil-sakhareliya** [prometheus-community/helm-charts#2668]
### Describe the bug a clear and concise description of what the bug is.

Hello.

I am trying to scrap metrics from multiple databases using "datasourceSecret" in values file.

**chart:**
https://github.com/prometheus-community/postgres_exporter

**values:**

config:
    datasourceSecret:
        Name: post-exporter
        key: db-connection
        logLevel: "debug"
        logFormat: "logfmt"

**secret:**

kind: Secret
metadata:
  name: post-exporter
  namespace: infra
type: Opaque
data:
  db-connection: postgresql://<user>:<password>@<ip_address>:5432/?sslmode=disable,postgresql://<user>:<password>@<ip_address>:5432/?sslmode=disable

If I just use one either of the strings then it displays metrics perfectly fine. but when I try to scrap 2 database strings then it gives ERROR:

**An error has occurred while serving metrics:**

3 error(s) occurred:
* collected metric pg_settings_enable_partition_pruning label:<name:"server" value:"ip:port" > gauge:<value:1 >  has help "Enable plan-time and run-time partition pruning." but should have "Enables plan-time and run-time partition pruning."
* collected metric pg_settings_wal_receiver_status_interval_seconds label:<name:"server" value:"ip:port" > gauge:<value:10 >  has help "Sets the maximum interval between WAL receiver status reports to the primary. [Units converted to seconds.]" but should have "Sets the maximum interval between WAL receiver status reports to the sending server. [Units converted to seconds.]"
* collected metric pg_settings_wal_receiver_timeout_seconds label:<name:"server" value:"ip:port" > gauge:<value:60 >  has help "Sets the maximum wait time to receive data from the primary. [Units converted to seconds.]" but should have "Sets the maximum wait time to receive data from the sending server. [Units converted to seconds.]"

**pog logs looks fine too:**

ts=2022-11-09T16:29:15.096Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_statio_user_tables
40
ts=2022-11-09T16:29:15.106Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_user_tables
39
ts=2022-11-09T16:29:15.116Z caller=postgres_exporter.go:731 level=error err="queryNamespaceMappings returned 1 errors"
38
ts=2022-11-09T16:29:34.739Z caller=postgres_exporter.go:634 level=debug msg="Querying PostgreSQL version" server=ip:port
37
ts=2022-11-09T16:29:34.748Z caller=pg_setting.go:28 level=debug msg="Querying pg_setting view" server=ip:port
36
ts=2022-11-09T16:29:34.768Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
35
ts=2022-11-09T16:29:34.777Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
34
ts=2022-11-09T16:29:34.787Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database
33
ts=2022-11-09T16:29:34.806Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity_idle
32
ts=2022-11-09T16:29:34.816Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_statio_user_tables
31
ts=2022-11-09T16:29:34.826Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
30
ts=2022-11-09T16:29:34.835Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication
29
ts=2022-11-09T16:29:34.844Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_statements
28
ts=2022-11-09T16:29:34.853Z caller=namespace.go:236 level=info err="Error running query on database \"ip:port\": pg_stat_statements pq: relation \"pg_stat_statements\" does not exist"
27
ts=2022-11-09T16:29:34.853Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
26
ts=2022-11-09T16:29:34.863Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_postmaster
25
ts=2022-11-09T16:29:34.872Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_user_tables
24
ts=2022-11-09T16:29:34.881Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
23
ts=2022-11-09T16:29:34.891Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
22
ts=2022-11-09T16:29:34.900Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_bgwriter
21
ts=2022-11-09T16:29:34.909Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_database
20
ts=2022-11-09T16:29:34.909Z caller=postgres_exporter.go:731 level=error err="queryNamespaceMappings returned 1 errors"
19
ts=2022-11-09T16:29:34.918Z caller=postgres_exporter.go:634 level=debug msg="Querying PostgreSQL version" server=ip:port
18
ts=2022-11-09T16:29:34.927Z caller=pg_setting.go:28 level=debug msg="Querying pg_setting view" server=ip:port
17
ts=2022-11-09T16:29:34.947Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_statio_user_tables
16
ts=2022-11-09T16:29:34.957Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_user_tables
15
ts=2022-11-09T16:29:34.967Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_locks
14
ts=2022-11-09T16:29:34.978Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication_slots
13
ts=2022-11-09T16:29:34.987Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_archiver
12
ts=2022-11-09T16:29:34.996Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity_idle
11
ts=2022-11-09T16:29:35.007Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database_conflicts
10
ts=2022-11-09T16:29:35.016Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_replication
9
ts=2022-11-09T16:29:35.026Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_bgwriter
8
ts=2022-11-09T16:29:35.035Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_database
7
ts=2022-11-09T16:29:35.035Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_postmaster
6
ts=2022-11-09T16:29:35.044Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_activity
5
ts=2022-11-09T16:29:35.054Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_database
4
ts=2022-11-09T16:29:35.074Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_replication
3
ts=2022-11-09T16:29:35.083Z caller=namespace.go:193 level=debug msg="Querying namespace" namespace=pg_stat_statements
2
ts=2022-11-09T16:29:35.092Z caller=namespace.go:236 level=info err="Error running query on database \"ip:port\": pg_stat_statements pq: relation \"pg_stat_statements\" does not exist"
1
ts=2022-11-09T16:29:35.092Z caller=postgres_exporter.go:731 level=error err="queryNamespaceMappings returned 1 errors"

### What's your helm version?

v3.9.4

### What's your kubectl version?

1.24

### Which chart?

https://github.com/prometheus-community/postgres_exporter

### What's the chart version?

0.12.0-rc.0

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by zeritti** [comment]
Looks like you hit the exporter's issue [#682](https://github.com/prometheus-community/postgres_exporter/682).

**Comment by kemil-sakhareliya** [comment]
no content at [#682](https://github.com/prometheus-community/postgres_exporter/682)
