### ISSUE TITLE
[prometheus-kube-stack] can't upgrade when installing second prometheus instance

### ISSUE THREAD

**Issue by dry4ng** [prometheus-community/helm-charts#268]
**Describe the bug**
I'm trying to run two Prometheus instances. After I deploy second instance with a different `release-name` and operator disabled, and run upgrade on first and second instance, I'm no longer able unable to upgrade the first instance. I'm getting long error.

`Error: UPGRADE FAILED: cannot patch "kube-prometheus-stack-activemq-rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prom-op-instance2-kube-pr-operator.monitor.svc:443/admission-prometheusrules/mutate?timeout=30s: service "prom-op-instance2-kube-pr-operator" not found && cannot patch "kube-prometheus-stack-black-box-probe-rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prom-op-instance2-kube-pr-operator.monitor.svc:443/admission-prometheusrules/mutate?timeout=30s: service "prom-op-instance2-kube-pr-operator" not found && cannot patch "kube-prometheus-stack-node-exporter-rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prom-op-instance2-kube-pr-operator.monitor.svc:443/admission-prometheusrules/mutate?timeout=30s: service "prom-op-instance2-kube-pr-operator" not found && cannot patch "prom-op-instance1-kub-alertmanager.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post https://prom-op-instance2-kube-pr-operator.monitor.svc:443/admission-prometheusrules/mutate?timeout=30s: service "prom-op-instance2-kube-pr-operator" not found &&...`

The secondary instance is still upgradeable.
I tried to redeploy everything from scratch after deleting and disabling validating/Mutating webhooks. Same issue.
I couldn't find any documentation on how to correctly deploy second Prometheus on the same AKS cluster.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"ea670c3ed1fab723e191551e68da613f8a9c5667", GitTreeState:"clean", BuildDate:"2020-05-30T04:43:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-kube-stack
**Which version of the chart**: 9.4.10

**How to reproduce it** (as minimally and precisely as possible):
1. Deploy `prometheus-kube-stack` chart.
2. Deploy `prometheus-kube-stack` with different `release-name` and prometheus-operator disabled.
3. Run upgrade on first instance. Get persistent error `UPGRADE FAILED: cannot patch`.

**Comment by dry4ng** [comment]
I have figured out what is happening. When I install or upgrade second instance, it creates admission webhooks for it, pointing at non existing `release-name`, even though prometheus-operator is disabled.

So a workaround is to explicitly disable admissionWebhooks in addition to disabled operator:

```yaml
prometheusOperator:
  enabled: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
```

**Comment by PhilipSchmid** [comment]
@dry4ng thanks for sharing your solution!
