### ISSUE TITLE
prometheus-postgre-exporter  : please provide container securityContext

### ISSUE THREAD

**Issue by sankalp28** [prometheus-community/helm-charts#2685]
### Is your feature request related to a problem ?

Hello,
I would like to adjust the securityContext of the containers inside the deployment.yaml template, but i find no place to do so correctly.
There is already a securityContext, but that is for Pod level not container level.
Pod Security context doesn't allow the same keys to be used as the containerSecurityContext , eg capabilities, readonlyfilesystem etc.

### Describe the solution you'd like.

One would need to rename the current securityContext to PodSecurityContext and add another securityContext which will then be included in all containers.This is common practice in other charts.

### Describe alternatives you've considered.

also trying with Pod securityContext, but this is deprecated and not allowed in current Kubernetes.

**Comment by monotek** [comment]
Pullrequests welcome ;-)

**Comment by sankalp28** [comment]
Pull request raised .Please review: https://github.com/prometheus-community/helm-charts/pull/2698
