### ISSUE TITLE
[kube-prometheus-stack] No Data

### ISSUE THREAD

**Issue by SonalJain1707** [prometheus-community/helm-charts#2690]
### Describe the bug a clear and concise description of what the bug is.

We are not able to get data from /
[Kubernetes / Compute Resources / Namespace (Pods)] Dashboard.

Below entry shows No Data

![image](https://user-images.githubusercontent.com/79579566/202125684-c55d7871-6900-4323-9ed3-80032e7962b8.png)

"expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",

### What's your helm version?

v0.10.0

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate: "2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clea n", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-promethus v0.10.0

### What's the chart version?

v0.10.0

### What happened?

No Data  in grafana dashboard

![image](https://user-images.githubusercontent.com/79579566/202127111-b2e63acc-0b9c-4ded-9b22-21fdd8dff182.png)

### What you expected to happen?

To see data. We would like to get the troubleshooting steps to check if metrics is present.
We have run the query and it returns empty data.
The rules are all ok but we see issue with kube-system namespace.
However the data from custom created namespce is coming, we want to check why data is not shown in grafana and how to check if the data is retrived from metrics.

### How to reproduce it?

Its reproducible any time

### Enter the command that you execute and failing/misfunctioning.

"expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\"})",

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/79579566/202127111-b2e63acc-0b9c-4ded-9b22-21fdd8dff182.png)

**Comment by jehutyy** [comment]
is there any update on this one ? we get the same result with the following release : 
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/6039827/205884618-3a5538a4-9824-4eac-8363-bf3e2492caa0.png">

**Comment by jeremydescamps** [comment]
I have the same behavior . I have not any `job=kubelet` label.
Installed on AWS EKS.

**Comment by rpetti** [comment]
Same problem. It was working fine on RKE 1.3.2, and stopped working after upgrading.
- RKE 1.3.17
- prometheus-operator-crds 0.62.0
- kube-prometheus-stack 0.62.0

Tried a full reinstall of kube-prometheus-stack and see the same problem. Prometheus doesn't show any scraping errors.

Example of a query not working, taken from the default dashboards provided by kube-prometheus-stack
"Kubernetes / Compute Resources / Namespaces (Pods) / CPU Usage"
```prometheus
sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster", namespace="$namespace"}) by (pod)
```

The rule for that missing metric is defined by kube-prometheus-stack as:
```
sum by (cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```

Removing the `image!=""` portion causes the query to return the information needed. It seems that the image label has disappeared from cadvisor in newer versions of k8s? Should the rules and graphs be updated accordingly?

**Comment by Ezzmo** [comment]
I'm experiencing the same issue, is this an irate vs rate problem?

**Comment by devmattrick** [comment]
I had this issue and it seems like for me it was happening due to a misconfigured firewall not allowing some of the metrics endpoints to be accessed. You can verify this in your Prometheus instance by checking Status > Targets and seeing if the metrics endpoints have connection errors. If they do, double check that your firewall isn't affecting them. I had to unblock ports `10250` and `9100`.

I'm not sure why it's using the machine's public IP instead of the internal IP for these metrics, though.

**Comment by jehutyy** [comment]
I figured that rke no longer expose cadvisor metrics which lead to this issue.

We fixed this by deploying our own cadvisor instance instead of the default one installed formerly by rke.

I hope this help

**Comment by KOCM0C** [comment]
> Same problem. It was working fine on RKE 1.3.2, and stopped working after upgrading.
> 
> * RKE 1.3.17
> * prometheus-operator-crds 0.62.0
> * kube-prometheus-stack 0.62.0
> 
> Tried a full reinstall of kube-prometheus-stack and see the same problem. Prometheus doesn't show any scraping errors.
> 
> Example of a query not working, taken from the default dashboards provided by kube-prometheus-stack "Kubernetes / Compute Resources / Namespaces (Pods) / CPU Usage"
> 
> ```
> sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster", namespace="$namespace"}) by (pod)
> ```
> 
> The rule for that missing metric is defined by kube-prometheus-stack as:
> 
> ```
> sum by (cluster, namespace, pod, container) (irate(container_cpu_usage_seconds_total{image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on (cluster, namespace, pod) group_left (node) topk by (cluster, namespace, pod) (1, max by (cluster, namespace, pod, node) (kube_pod_info{node!=""}))
> ```
> 
> Removing the `image!=""` portion causes the query to return the information needed. It seems that the image label has disappeared from cadvisor in newer versions of k8s? Should the rules and graphs be updated accordingly?

Faced the same problem. But it was enough for me to remove the symbol  "!" before the equal sign and the data appeared.
