### ISSUE TITLE
Custom alerts are auto resolved after 5 minutes, even though Prometheus keeps firing them.

### ISSUE THREAD

**Issue by asettouf** [prometheus-community/helm-charts#2695]
### Describe the bug a clear and concise description of what the bug is.

Custom alerts are auto resolved after 5 minutes, even though Prometheus keeps firing them.

### What's your helm version?

version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.18.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12-gke.2300", GitCommit:"e55564cf3a1384026a54920174977659c8c56a50", GitTreeState:"clean", BuildDate:"2022-08-16T09:24:51Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

40.5.0

### What happened?

We upgraded from `39.12.1` to `40.5.0`, after that we started seeing some alerts getting solved automatically even though the root cause was still there.

After investigation, we noticed that Prometheus has the alert in the proper state, but the alert manager seem to fire a resolved status after 5 minutes. It seems that for custom alerts, the alertmanager uses the `resolve_timeout` (defaults to 5 minutes), notwithstanding the alert is still firing.

**NOTE**: The behavior is reproduced under `41.x.y` version

Example: Custom alert `LowAvailableMemory`

- Alert configuration:
```
alert:[LowAvailableMemory]
expr:[last_over_time(node_memory_MemAvailable_bytes{instance="10.4.11.12:9100"}[30m]) / last_over_time(node_memory_MemTotal_bytes{instance="10.4.11.12:9100"}[30m]) < 0.5](http://localhost:9090/graph?g0.expr=last_over_time(node_memory_MemAvailable_bytes%7Binstance%3D%2210.4.11.12%3A9100%22%7D%5B30m%5D)%20%2F%20last_over_time(node_memory_MemTotal_bytes%7Binstance%3D%2210.4.11.12%3A9100%22%7D%5B30m%5D)%20%3C%200.5&g0.tab=1&g0.stacked=0&g0.show_exemplars=0.g0.range_input=1h.)
for: 5m
labels:
severity: warning
annotations:
summary: On host {{ $labels.instance }}, available memory is less than 50%.
```

- Alertmanager logs:
```
ts=2022-11-16T11:02:08.928Z caller=dispatch.go:517 level=debug component=dispatcher aggrGroup="{}:{alertname=\"LowAvailableMemory\", instance=\"10.4.11.12:9100\"}" msg=flushing alerts=[LowAvailableMemory[62acf54][active]]
ts=2022-11-16T11:03:08.926Z caller=dispatch.go:165 level=debug component=dispatcher msg="Received alert" alert=LowAvailableMemory[9081749][active]
ts=2022-11-16T11:04:38.926Z caller=dispatch.go:165 level=debug component=dispatcher msg="Received alert" alert=LowAvailableMemory[9081749][active]
ts=2022-11-16T11:06:08.926Z caller=dispatch.go:165 level=debug component=dispatcher msg="Received alert" alert=LowAvailableMemory[9081749][active]
ts=2022-11-16T11:07:08.929Z caller=dispatch.go:517 level=debug component=dispatcher aggrGroup="{}:{alertname=\"LowAvailableMemory\", instance=\"10.4.11.12:9100\"}" msg=flushing alerts="[LowAvailableMemory[9081749][active] LowAvailableMemory[62acf54][resolved]]"
```

- Prometheus :
![image](https://user-images.githubusercontent.com/6400458/202166873-f1de7bab-a373-447d-b5c6-8102a9103741.png)

### What you expected to happen?

The alert should not be resolved by the alert manager

### How to reproduce it?

- Create a custom alert
- Creates conditions to fire it
- Notice after 5 minutes the alert manager triggers a resolve event

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm upgrade my-release prometheus-community/kube-prometheus-stack

**Comment by ysfnsrv** [comment]
@asettouf could you fix the problem?
I have the same problem.
