### ISSUE TITLE
[kube-prometheus-stack] commonLabels are not applied to prometheus-operated service

### ISSUE THREAD

**Issue by w5346c** [prometheus-community/helm-charts#2699]
### Describe the bug a clear and concise description of what the bug is.

commonLabels are not applied to prometheus-operated service

### What's your helm version?

3.7.0

### What's your kubectl version?

1.25.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.3

### What happened?

prometheus-operated service does not have labels added to commonLabels

### What you expected to happen?

prometheus-operated service has labels added to commonLabels

### How to reproduce it?

1. Create values.yaml file
```
commonLabels:
  label1: qwerty
  label2: asdf
```

2. `helm install -f values.yaml my-prom prometheus-community/kube-prometheus-stack`

3. k describe service prometheus-operated

[Expected] :
```
Name: prometheus-operated
Labels:
  operated-prometheus=true
  label1=qwerty
  label2=asdf
...
```

[Actual] :
```
Name: prometheus-operated
Labels:
  operated-prometheus=true
...
```

### Enter the changed values of values.yaml?

```
commonLabels:
  label1: qwerty
  label2: asdf
```

### Enter the command that you execute and failing/misfunctioning.

helm install -f values.yaml my-prom prometheus-community/kube-prometheus-stack

### Anything else we need to know?

We have a web hook that requires each service to have certain labels.
Is there any way to add custom labels to prometheus-operated service?

Thank you.

**Comment by zeritti** [comment]
Unfortunately, no, not through the chart, that is. The services `prometheus-operated` and `alertmanager-operated` get created directly by the operator, e.g. [here](https://github.com/prometheus-operator/prometheus-operator/blob/1d6c2dc2e5e5d1ead94af83ee8353a50d610db4b/pkg/prometheus/statefulset.go#L258). They are resources that Helm does not know of. There is no resource in the CRDs that one might make use of in this respect.
