### ISSUE TITLE
kube-prometheus-stack - unknown field "hostNetwork"

### ISSUE THREAD

**Issue by pslattery-wyn** [prometheus-community/helm-charts#2702]
### Describe the bug a clear and concise description of what the bug is.

Beginning with version 41.8.0 of the kube-prometheus-stack chart I get the error:

From Helm:
```
STDERR:
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec
```

From `kubectl apply`
```
kubectl apply --filename=/tmp/kube-prometheus-stack_41.8.0.yaml --output=yaml --dry-run=server
  error validating "/tmp/kube-prometheus-stack_41.8.0.yaml": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

### What's your helm version?

```
version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}
```

### What's your kubectl version?

```
Client Version: v1.22.12
Server Version: v1.22.12-gke.2300
```

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.8.0 or higher

### What happened?

Beginning with version 41.8.0 of the kube-prometheus-stack chart I get the error:

From Helm:
```
STDERR:
  Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec
```

From `kubectl apply`
```
kubectl apply --filename=/tmp/kube-prometheus-stack_41.8.0.yaml --output=yaml --dry-run=server
  error validating "/tmp/kube-prometheus-stack_41.8.0.yaml": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

### What you expected to happen?

For the chart to install as it does with version 41.7.4 or below

### How to reproduce it?

Can be duplicated at will using the instructions at: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 41.9.0

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec
```

### Enter the changed values of values.yaml?

None. Will error out using just the defaults.

### Enter the command that you execute and failing/misfunctioning.

```shell
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

helm install my-kube-prometheus-stack prometheus-community/kube-prometheus-stack --version 41.9.0
```

**Comment by zeritti** [comment]
I can reproduce the same error with installed operator and CRDs 0.60.1 (`hostNetwork` was introduced in 0.60.0). The field is not present in the CRDs which is confirmed by `kubectl explain prometheus.spec.hostNetwork`. 

If I re-install CRD manifests from that same release, though, the field gets created and the following roll-out of 41.8.0 succeeds. I reckon the manifests were probably not complete at the time of the CRD upgrade to 0.60.1. or the upgrade took place at an unfortunate moment.

**Comment by jendrikjoe** [comment]
For others hitting this issue the solution is applying the crds manually, as described here: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-40x-to-41x 🙂
