### ISSUE TITLE
[kube-prometheus-stack] Grafana "Use an existing secret for the admin user" used to change password?

### ISSUE THREAD

**Issue by reefland** [prometheus-community/helm-charts#2710]
### Describe the bug a clear and concise description of what the bug is.

My values.yaml has the following to use an existingSecret for Grafana:
```
        grafana:
          admin:
            existingSecret: "kube-prometheus-stack-grafana"
            userKey: admin-user
            passwordKey: admin-password
```
I'm using SealedSecrets / AgroCD - To deploy an UPDATED SealedSecret file with new Grafana password.  The deployment works but Grafana ignores the new password within the secret.  Grafana is still accepting the original password from the previous version of the secret, from the initial install. Trying to determine if this is by design or bug.

### What's your helm version?

$ helm version version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

$ kubectl version WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

41.7.4

### Troubleshooting:
This is the only secret I have with the word grafana in it:
```
$ k get secrets -A | grep grafana
monitoring          kube-prometheus-stack-grafana          Opaque          3      2d1h
```
The admin ID & password are defined within the secret:
```
$ k describe secrets -n monitoring kube-prometheus-stack-grafana        
Name:         kube-prometheus-stack-grafana
Namespace:    monitoring
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
admin-password:  17 bytes
admin-user:      5 bytes
ldap-toml:       0 bytes
```

I can even inspect the secret and see SealedSecrets has applied the new password (I've changed it again since): 
```
$ kubectl get secret --namespace monitoring kube-prometheus-stack-grafana -o jsonpath='{.data.admin-password}' | base64 -d
ZvtZwNRGsFU5nsLOz
```

I only have a single Grafana pod, I've restart it to force it to pick up the new password:
```
$ k get pods -A | grep grafana                                                                                        
monitoring      grafana-5c84cc4c77-jtdqp                 3/3     Running   0               51s
```

When I describe the pod, it states the ENV variable will be set from the secret:
```
Environment:
    GF_SECURITY_ADMIN_USER:      <set to the key 'admin-user' in secret 'kube-prometheus-stack-grafana'>      Optional: false
    GF_SECURITY_ADMIN_PASSWORD:  <set to the key 'admin-password' in secret 'kube-prometheus-stack-grafana'>  Optional: false
```

I can view the ENV variables passed inside the Pod showing the new password is being picked up:
```
$ k exec -n monitoring grafana-5c84cc4c77-jtdqp -c grafana -- env | grep ADMIN                
GF_SECURITY_ADMIN_USER=admin
GF_SECURITY_ADMIN_PASSWORD=ZvtZwNRGsFU5nsLOz
```

However, the Grafana dashboard ignored new password; only the original password "prom-operator" is being accepted for account "admin".

Where is it getting this old password from?  I assume it stored in the database and the secrets are initial install only and then no longer used? I was unable to find this information in the documentation. 

### What you expected to happen?

I expected the admin password to be updated based on the value stored within the secret.

### How to reproduce it?

Change password stored within Grafana secret and restart the pod.   The ENV variable GF_SECURITY_ADMIN_PASSWORD reflects the new password but is ignored by Grafana.

### Enter the command that you execute and failing/misfunctioning.

Grafana Dashboard only accepts initial secret password value, not updated password.

### Anything else we need to know?

I could understand if this is by design, but I can't find a reference saying that Kubernetes secret is used for Grafana initial install only and ignored afterwards.

**Comment by daviderli614** [comment]
Hi @reefland , Is this problem solved? I also encountered.

**Comment by reefland** [comment]
No.  Based on experience, the secret seems to be the initial password only, which is persisted within the Grafana PV.  Changing the secret did not change the password.

**Comment by daviderli614** [comment]
Yes, my grafana is also mounted pv, set the `grafana.admin.existingSecret`, and will not change the password, the password is still the original prom-operator. I don't know what to do to make existingSecret password take effect.

**Comment by daviderli614** [comment]
Execute `env | grep ADMIN` in the grafana container, you can see the set user and password.

**Comment by reefland** [comment]
If you have a working initial password, then you should be able to change it from within Grafana (bottom left):

![image](https://user-images.githubusercontent.com/16230914/224703099-f43f8881-2529-467d-8888-0742436f4d59.png)

I tried `env | grep ADMIN` and got nothing.  My install (Helm based) needed `env | grep REQ` which showed values for `REQ_PASSWORD=` and `REQ_USERNAME=admin`.

**Comment by stepanbaghdasaryan** [comment]
Hi everyone. This is still an existing problem and the workarounds are not a solution for declaratively Grafana deployment. The existing password will be deployed with grafana helm charts, you can see it in grafana pod as env var GF_SECURITY_ADMIN_USER and GF_SECURITY_ADMIN_PASSWORD, but it is not adopted by grafana db. This is a bug in my opinion. Can someone take a look on this issue? Thanks.

**Comment by ChrisJBurns** [comment]
Wondering if it's secure to store credentials in environment variables? Perhaps we can make use of volume mounts?

**Comment by glerma** [comment]
I just ran into this as well!

using kube-prometheous-operator helm chart, v51.10.0, and i have set a secret called `kube-prometheus-stack-grafana-admin-permanent` with the following in values.yaml:

```    
# Use an existing secret for the admin user.
  admin:
    ## Name of the secret. Can be templated.
    existingSecret: "kube-prometheus-stack-grafana-admin-permanent"
    userKey: admin-user
    passwordKey: admin-password
```
   
   The "existing secret" is not getting picked up, no matter what I do.

**Comment by weyderfs** [comment]
> I just ran into this as well!
> 
> using kube-prometheous-operator helm chart, v51.10.0, and i have set a secret called `kube-prometheus-stack-grafana-admin-permanent` with the following in values.yaml:
> 
> ```
> # Use an existing secret for the admin user.
>   admin:
>     ## Name of the secret. Can be templated.
>     existingSecret: "kube-prometheus-stack-grafana-admin-permanent"
>     userKey: admin-user
>     passwordKey: admin-password
> ```
> 
> The "existing secret" is not getting picked up, no matter what I do.

Can you found a solution?

**Comment by weyderfs** [comment]
> > I just ran into this as well!
> > using kube-prometheous-operator helm chart, v51.10.0, and i have set a secret called `kube-prometheus-stack-grafana-admin-permanent` with the following in values.yaml:
> > ```
> > # Use an existing secret for the admin user.
> >   admin:
> >     ## Name of the secret. Can be templated.
> >     existingSecret: "kube-prometheus-stack-grafana-admin-permanent"
> >     userKey: admin-user
> >     passwordKey: admin-password
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The "existing secret" is not getting picked up, no matter what I do.
> 
> Can you found a solution?

Maybe doing a [override](https://github.com/grafana/helm-charts/blob/5fa614a41baa7e22daddd86f9e9466e5e9b56baa/charts/grafana/templates/deployment.yaml#L40C1-L42C75) works

**Comment by dcfitzpatrick00** [comment]
This is still an issue. Need developer support.

**Comment by malekerramli** [comment]
i encountered the same issue ... took me 2 days to understand whats going on ....

**Comment by Mohamed-Sharif** [comment]
I have encountered the same issue, anyone managed to find a solution to this?

**Comment by secmff** [comment]
I use this:
```yaml
grafana:
  admin:
    existingSecret: grafana-admin
  command:
    - sh
    - -c
    - cd /usr/share/grafana; bin/grafana cli admin reset-admin-password
      $GF_SECURITY_ADMIN_PASSWORD; /run.sh
  
```
But when I change the secret the password is not updated. So I also need a sidecar for this.

**Comment by Mo0rBy** [comment]
I came across this and it's a non-issue (for the Helm chart at least).

I have persistence disabled as I am deploying and setting things up first, before I enable persistence.

The Grafana Helm chart is a dependency to the kube-prometheus-stack Helm chart, so you just need to look at the values for the [Grafana Helm chart](https://artifacthub.io/packages/helm/grafana/grafana).

The correct way to set the Grafana admin credentials is documented and can be seen in their default values: https://artifacthub.io/packages/helm/grafana/grafana?modal=values&path=admin

It looks like most people in the thread have persistence enabled and this seems to be the problem. If thats the case, then I wouldn't say this is an issue at all, as that's what persistence is supposed to do.
When you set an initial password for most applications in this way, it gets set in a database somewhere (or some other dependency) and then cannot be changed by the Helm chart again, unless the persisted data is deleted.

**Comment by Time0o** [comment]
> I came across this and it's a non-issue (for the Helm chart at least).
> 
> I have persistence disabled as I am deploying and setting things up first, before I enable persistence.

That is nonsense, I do not have persistence enabled and password changes are still not applied this way.
