### ISSUE TITLE
[kube-prometheus-stack] Release 42.0.0 does not have a Changelog entry

### ISSUE THREAD

**Issue by morremeyer** [prometheus-community/helm-charts#2718]
### Describe the bug a clear and concise description of what the bug is.

Release 42.0.0 of kube-prometheus-stack does not have an upgrading entry in the README.

The [commit itself](https://github.com/prometheus-community/helm-charts/commit/f528fe820fa0f8d4eabada1b158854487e0563d8) does not have any obvious breaking changes to me, so I can't make a decision about what to add to the documentation in a PR.

@QuentinBisson @Xtigyro Would you be able to open a PR amending the [Upgrading section](https://github.com/prometheus-community/helm-charts/tree/f528fe820fa0f8d4eabada1b158854487e0563d8/charts/kube-prometheus-stack#upgrading-chart) of the readme please?

### Which chart?

kube-prometheus-stack

### What's the chart version?

42.0.0

**Comment by QuentinBisson** [comment]
@morremeyer can you add me as an assignee? I'll write something by the end of the week
