### ISSUE TITLE
[prometheus-kube-stack] Failed to publish 42.0.0 in ghcr

### ISSUE THREAD

**Issue by sereinity** [prometheus-community/helm-charts#2719]
### Describe the bug a clear and concise description of what the bug is.

Hello, the CI [still](https://github.com/prometheus-community/helm-charts/actions/runs/3524922385/jobs/5910972303) fails to publish new charts in ghcr.

From the [list of published versions](https://github.com/prometheus-community/helm-charts/pkgs/container/charts%2Fkube-prometheus-stack) we can see that the latest stable version is 41.7.4; which means that we missed: 41.8.0, 41.9.0, 41.9.1 and 42.0.0.

### What's your helm version?

NA

### What's your kubectl version?

NA

### Which chart?

kube-prometheus-stack

### What's the chart version?

42.0.0

### Enter the command that you execute and failing/misfunctioning.

NA

**Comment by monotek** [comment]
@scottrigby could you have a look please?

**Comment by sereinity** [comment]
Ping, there is a lot of unpublished releases now, I had to go back [at page 6 in releases](https://github.com/prometheus-community/helm-charts/releases?page=6) to find the latest one published in ghcr.

And [other users](https://github.com/prometheus-community/helm-charts/issues/2454#issuecomment-1340054509) have [concerns](https://github.com/prometheus-community/helm-charts/issues/2454#issuecomment-1343184954) about this

**Comment by wlritchi** [comment]
Still appears to be an issue

**Comment by sereinity** [comment]
Still here, latest published release is from November 2022.
