### ISSUE TITLE
[prometheus-cloudwatch-exporter] Service monitor not generated when using with kube-prometheus-stack

### ISSUE THREAD

**Issue by hoonahn** [prometheus-community/helm-charts#272]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-cloudwatch-exporter

**Which version of the chart**: 0.10.0

**What happened**: 

I'm trying to deploy prometheus-cloudwatch-exporter along with kube-prometheus-stack chart but the ServiceMonitor for cloudwatch exporter is not generated.

**What you expected to happen**:

ServiceMonitor manifest for prometheus-cloudwatch-exporter generated from helm cli.

**How to reproduce it** (as minimally and precisely as possible):

- Clone https://github.com/prometheus-community/helm-charts
- Edit [this line](https://github.com/prometheus-community/helm-charts/blob/137ce13d2a2a50fefa78197f841bc0436437f119/charts/prometheus-cloudwatch-exporter/values.yaml#L134) like: 
```
serviceMonitor:
  enabled: true
  interval: 30s
  telemetryPath: /metrics
  labels: {}
  timeout: 30s
  relabelings: []
  metricRelabelings: []
```
- Make package `prometheus-cloudwatch-exporter` and move to `kube-prometheus-stack/charts` directory
- Try to export manifest with `helm template`
```
helm template my-release kube-prometheus-stack
```
- But the manifest for prometheus-cloudwatch-exporter is not generated. (It works for other charts such as prometheus-elasticsearch-exporter)

**Anything else we need to know**: It doesn't works with `--set serviceMonitor.enabled=true`

**Comment by bogdansucila** [comment]
Did you ever get to the bottom of this? Currently experiencing the same problem

**Comment by borisputerka** [comment]
If you have experiencing this issue or anybody will I will write this here.
ServiceMonitor is created when both `.Values.serviceMonitor.enabled` and `.Capabilities.APIVersions.Has "monitoring.coreos.com/v1"` are true.
So what you can do is to pass `--api-versions "monitoring.coreos.com/v1" argument` in helm template.

**Comment by gciria** [comment]
I have the same problem.
If you use it with `--api-versions "monitoring.coreos.com/v1"` is working. But it's not correct.

And if you remove the `IF` from `template/servicemonitor.yaml`, leaving only: "`{{- .Values.serviceMonitor.enabled }}
`" works.

**Comment by liorco300** [comment]
Hi can .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" be removed from the chart since its not working ?
