### ISSUE TITLE
[prometheus] Error when installing latest version

### ISSUE THREAD

**Issue by walker-tom** [prometheus-community/helm-charts#2723]
### Describe the bug a clear and concise description of what the bug is.

When installing the latest version of [prometheus-community/prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) I get the following error:

```
Error: template: prometheus/templates/NOTES.txt:86:46: executing "prometheus/templates/NOTES.txt" at <index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil
```

To recreate, I ran:

```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/prometheus
```

I think it might've been caused in #2714 when pushgateway was moved to being a subchart.

If you are able to advise on a fix then I'm happy to try and implement it but I am not sure of one myself as I've not worked with references to `.SubCharts` and can't find any documentation for them either.

Thanks in advance for your help!!

### What's your helm version?

version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus

### What's the chart version?

17.0.0

### Enter the command that you execute and failing/misfunctioning.

```bash
helm install prometheus prometheus-community/prometheus
```

**Comment by zeritti** [comment]
Installing the chart with Helm 3.10.2 succeeds. However, installing the chart with e.g. Helm 3.5.3 fails with the reported error. It may be worth attempting the install with a later Helm release, probably at least 3.7.

**Comment by walker-tom** [comment]
Updated my version of Helm to 3.10.2 and installation is now succeeding, thanks for your help!

**Comment by sachinshakya507** [comment]
I am using helm version.BuildInfo{Version:"v3.10.2"
still got an issue 
Error: UPGRADE FAILED: template: prometheus/templates/NOTES.txt:85:46: executing "prometheus/templates/NOTES.txt" at <index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil

**Comment by koraykutanoglu** [comment]
i am having the same problem.

```
helm install --namespace=prometheus --timeout=10m0s --values=/home/shell/helm/values-prometheus-19.3.3.yaml --version=19.3.3 --wait=true prometheus /home/shell/helm/prometheus-19.3.3.tgz
--
Sat, Mar 4 2023 11:25:13 pm | Error: template: prometheus/templates/NOTES.txt:85:46: executing "prometheus/templates/NOTES.txt" at <index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil
```
