### ISSUE TITLE
How should 2000 nodes of Prometheus be deployed

### ISSUE THREAD

**Issue by xuchuan-666** [prometheus-community/helm-charts#273]
Hello:

We plan to deploy a 2000 node K8S cluster to monitor Prometheus. We want to ask if there are any good plans for the storage, reading and writing of Prometheus data?? Does Glusterfs' performance meet the requirements? Thank you very much

**Comment by marcus-sa** [comment]
I'd suggest checking our https://thanos.io/

**Comment by monotek** [comment]
Imho this is the wrong place to ask anyway as this is the home of the prometheus helm chart not prometheus itself.

Consider asking in the prometheus community:

* https://github.com/prometheus
* https://groups.google.com/forum/?pli=1#!forum/prometheus-users

Closing.
