### ISSUE TITLE
Prometheus postgres deployment chart uses environment variables for Secret keys DATA_SOURCE_NAME,DATA_SOURCE_PASS

### ISSUE THREAD

**Issue by deepaliguptaIBM** [prometheus-community/helm-charts#2738]
We have imported the Prometheus charts and we have an IBM guideline NOT to use environment variables for storing secrets. We should be using file/volume mounts to store them instead.

As we can see here(https://github.com/prometheus-community/helm-charts/blob/e09e9879ad75f1e787eadbeb9d73f1aafb86c226/charts/prometheus-postgres-exporter/templates/deployment.yaml#L81), `DATA_SOURCE_NAME` has got the value from the Secret, and similarly for `DATA_SOURCE_PASS` as well, which we need to change.

Can you let us know how we can avoid using those as environment variables?

**Comment by zeritti** [comment]
In combination with `extraVolumeMounts` and `extraVolumes` (assuming a corresponding secret has been created prior to launching the exporter), these values' fields may be worth checking: `config.passwordFile`, `config.pgpassfile`.

**Comment by deepaliguptaIBM** [comment]
@zeritti Thank you for the suggestion. We will check this approach once.
Also just wondering how these variables are being consumed. if we remove these variables from environment variables and store it on volume system, will it affect anything?
