### ISSUE TITLE
[kube-prometheus-stack] Gobal image registry not respected in chart dependency [prometheus-node-exporter]

### ISSUE THREAD

**Issue by guidoffm** [prometheus-community/helm-charts#2739]
### Is your feature request related to a problem ?

[kube-prometheus-stack] has a value `global.imageRegistry`. This value is not respected in the dependent chart [prometheus-node-exporter]. ``

### Describe the solution you'd like.

Find a solution to bring the global setting in effect also for the dependen charts.

### Describe alternatives you've considered.

N/A

**Comment by wisdomdevil** [comment]
Same here. Also kube-state-metrics and grafana.

**Comment by flokoenig** [comment]
Came here to post the same. One has to fix several images by hand. The problem gets worse with grafana sub-charts, which even have hard-coded images.

**Comment by phwissmann** [comment]
Same here. Prevents `helm upgrade` of the chart

**Comment by johnswarbrick-napier** [comment]
Created #3044 for review by the maintainers
