### ISSUE TITLE
PVC for grafana in custom values - save dashboards?

### ISSUE THREAD

**Issue by saul-gush** [prometheus-community/helm-charts#274]
I cant seem to set the pvc for grafana to hold the saved dashboards. If the node gets restarted, all the dashboards get wiped.

**Comment by saul-gush** [comment]
Even Grafana recommends persistent storage:
https://grafana.com/docs/grafana/latest/administration/configure-docker/

**Comment by monotek** [comment]
Please use issue the template.  It's hard to guess the used chart.

Maybe this helps: 

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L228

**Comment by muradheydarov** [comment]
> I cant seem to set the pvc for grafana to hold the saved dashboards. If the node gets restarted, all the dashboards get wiped.

I am also suffering from it. Is there any update?

**Comment by monotek** [comment]
does "--set grafana.persistence.enabled=true" not work?

**Comment by muradheydarov** [comment]
When I am enabling I see pv and pvc are creating but pod can not running. It is continuously restarting and then I am getting crashloopbackoff error. My settings for grafana is it:

`grafana: 
  additionalDataSources: []
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  enabled: true
  extraConfigmapMounts: []
  ingress: 
    annotations: {}
    enabled: false
    hosts: []
    labels: {}
    path: /
    tls: []
  namespaceOverride: ""
  persistence: 
    accessModes: 
      - ReadWriteOnce
    enabled: true
    name: grafana
    size: 1Gi
    storageClassName: shared
    type: pvc
  service: 
    portName: service
  serviceMonitor: 
    interval: ""
    metricRelabelings: []
    relabelings: []
    selfMonitor: true
  sidecar: 
    dashboards: 
      annotations: {}
      enabled: true
      label: grafana_dashboard
    datasources: 
      annotations: {}
      createPrometheusReplicasDatasources: false
      defaultDatasourceEnabled: true
      enabled: true
      label: grafana_datasource`

**Comment by piellick** [comment]
Hi everyone, i'm stuck on it too, does someone has a workaround ? @monotek  Exemple from GrafanaHelm chart does not work :

`    ## Enable persistence using Persistent Volume Claims
    ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  persistence:
    type: pvc
    enabled: true
    #  storageClassName: azurefile
    accessModes:
      - ReadWriteOnce
    size: 10Gi`

**Comment by flenoir** [comment]
Hi, i did struggle using azurefile, i finally make it work using azuredisk instead

**Comment by piellick** [comment]
Same workharound for me...Stop using azurefile ;)
