### ISSUE TITLE
prometheus-kube-stack - Startup probe failed: HTTP probe failed with statuscode: 503

### ISSUE THREAD

**Issue by vasukasarabada06** [prometheus-community/helm-charts#2749]
### Describe the bug a clear and concise description of what the bug is.

The pod associated state full set prometheus-kube-prometheus-stack-prometheus  is not running with a warning "Startup probe failed: HTTP probe failed with statuscode: 503". So we are not able to view Prometheus collected metrices grafana.

  Warning  Unhealthy  3m41s (x180 over 58m)  kubelet            Startup probe failed: HTTP probe failed with statuscode: 503

![image](https://user-images.githubusercontent.com/105363249/204481041-a494aae2-8078-4dcf-8a6d-40017ed4262f.png)

### What's your helm version?

v2.1.2

### What's your kubectl version?

4.5.4

### Which chart?

kube-prometheus-stack

### What's the chart version?

30.1.0

### What happened?

In AKS 1.21.9 we deployed kube_prometheus_stack helm version 30.1.0 with prometheus_image_version v2.32.1.
we are able to  monitor AKS with grafana dashboard. 
We deployed same in AKS 1.23.8  we can see prometheus is not collecting the metrices.

In events we can see "Startup probe failed: HTTP probe failed with statuscode: 503"

### What you expected to happen?

we should able to view metrics collected from Prometheus 

### Enter the changed values of values.yaml?

helm_kube_prometheus_stack_version : 30.1.0
prometheus_image_version:v2.32.1
hyperkube_image_version: v1.16.12
kube_prometheus_stack_image_version:v0.53.1
prometheus_config_reloader_image_version:v0.53.1

### Enter the command that you execute and failing/misfunctioning.

resource "helm_release" "kube_prometheus_stack" {
  chart      = "kube-prometheus-stack"
  name       = "kube-prometheus-stack"
  create_namespace = true
  repository = "https://prometheus-community.github.io/helm-charts"
  namespace  = kubernetes_namespace.default.metadata[0].name
  version    = var.helm_kube_prometheus_stack_version
  values = [templatefile("${path.module}/resources/values-tmpl.yaml", {

**Comment by jmc000** [comment]
Got a similar problem with chart v35.0.3, it seems that we can't change the startUp probe failureThreshold of the prometheus pods from the chart values, is it normal ?

**Comment by jmc000** [comment]
Hey, you can increase the failureThreshold of the startup probe using the `prometheusSpec.containers` value like that:

```
prometheusSpec:
    containers: 
      - name: prometheus
        startupProbe:
          failureThreshold: 300
```

**Comment by vasukasarabada06** [comment]
Thank you. it is working fine now

**Comment by maltif** [comment]
I tried increasing the `startupProbe: failureThreshold` from 60 to 300, but this didn't help. However, I noticed that the default memory allocation for `requests` and `limits` was set to 2 GB, which is quite low given the number of resources running on the k8s cluster.

By increasing the memory allocation Requests to 4 GB and Limits to 6 GB, I was able to resolve the issue.

```
prometheusSpec:
    containers: 
      - name: prometheus
         resources:
            limits:
              memory: 6Gi
            requests:
              memory: 4Gi
```            
It appears that the pods were crashing and unable to start properly due to insufficient memory allocation.

If you encounter a similar issue and increasing the `startupProbe: failureThreshold` to 300 doesn’t help, try adjusting the memory allocation Requests and Limits according to your workloads. This should resolve the problem.

**Comment by mohsen-abbas** [comment]
I had smilier issue, by increasing the values of requests and limits I was able to fix the problem. In my case memory usage of prometheus pod was higher than 8Gi.
resources:
      limits:
        memory: "12Gi"
        cpu: "2"
      requests:
        memory: "8Gi"
        cpu: "1"
