### ISSUE TITLE
[kube-prometheus-stack] Error while installing using helm

### ISSUE THREAD

**Issue by sourabhgupta385** [prometheus-community/helm-charts#2755]
### Describe the bug a clear and concise description of what the bug is.

When I install the helm chart for kube-prometheus-stack version - 42.1.0 I get below error - 

Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v6" is invalid: data: Too long: must have at most 1048576 bytes 

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"0b25cacbeba0b73f720022544dd02ffe9e67017e", GitTreeState:"clean", BuildDate:"2022-03-16T11:33:38Z", GoVersion:"go1.17.7 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

42.1.0

### What happened?

When I install the helm chart for kube-prometheus-stack version - 42.1.0 I get below error - 

Error: UPGRADE FAILED: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack.v6" is invalid: data: Too long: must have at most 1048576 bytes 

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --namespace prometheus-operator --timeout 10m --install --wait kube-prometheus-stack kube-prometheus-stack --values=kube-prometheus-stack/values.yaml

**Comment by zeritti** [comment]
That error often occurs when a chart is being installed from a directory in a file system which contains items that are not part of the chart, e.g. backups, archived charts, misplaced images, etc. A helmignore file can help in such a case if the files have to be kept.

**Comment by ArtemGontar** [comment]
Same issue, any updates here?
