### ISSUE TITLE
[prometheus-pushgateway] Service Monitor labels wrong

### ISSUE THREAD

**Issue by tarioch** [prometheus-community/helm-charts#2782]
### Describe the bug a clear and concise description of what the bug is.

With the 2.0.0 release, the labels for the service monitor are wrong. They are still app and release, but should probably be app.kubernetes.io/instance and app.kubernetes.io/name

### What's your helm version?

version.BuildInfo{Version:"v3.9.1", GitCommit:"a7c043acb5ff905c261cfdc923a35776ba5e66e4", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+k3s1", GitCommit:"0dc63334c0db3e7b99244427615e091909fc486e", GitTreeState:"clean", BuildDate:"2022-11-18T18:17:40Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-pushgateway

### What's the chart version?

2.0.1

### Enter the command that you execute and failing/misfunctioning.

helm install/helm update

**Comment by monotek** [comment]
Would you mind to create a PR please?
