### ISSUE TITLE
[ prometheus-kube-stack] latest chart Installation issue hostNetworke

### ISSUE THREAD

**Issue by Abay-gitrunner** [prometheus-community/helm-charts#2793]
### Describe the bug a clear and concise description of what the bug is.

I am using below command(s) to install the latest version :

      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus-values.yaml &&
      helm upgrade prometheus prometheus-community/kube-prometheus-stack -i -n monitoring -f prometheus-values.yaml

But, i am getting below error:

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

"clientVersion": {     "major": "1",     "minor": "24",     "gitVersion": "v1.24.3",     "gitCommit": "aef86a93758dc3cb2c658dd9657ab4ad4afc21cb",     "gitTreeState": "clean",     "buildDate": "2022-07-13T14:30:46Z",     "goVersion": "go1.18.3",     "compiler": "gc",     "platform": "linux/amd64"   },   "kustomizeVersion": "v4.5.4"

### Which chart?

kube-prometheus-stack

### What's the chart version?

43.0

### What happened?

I am using below command(s) to install the latest version :

      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus-values.yaml &&
      helm upgrade prometheus prometheus-community/kube-prometheus-stack -i -n monitoring -f prometheus-values.yaml

But, i am getting below error:

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Prometheus.spec): unknown field "hostNetwork" in com.coreos.monitoring.v1.Prometheus.spec

### What you expected to happen?

I expected latest kube-prometheus-stack to be installed in my cluster

### How to reproduce it?

run:

 helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update
      helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus-values.yaml &&
      helm upgrade prometheus prometheus-community/kube-prometheus-stack -i -n monitoring -f prometheus-values.yaml

### Enter the changed values of values.yaml?

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
  hosts:
    - host: prometheus.devk8s.kz
      paths: ["/"]
  tls:
    - secretName: 
      hosts: dev-secret
        - prometheus.devk8s.kz

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus-values.yaml

### Anything else we need to know?

thats all

**Comment by zeritti** [comment]
Please, refer to issue #2753.
