### ISSUE TITLE
Kube-prometheus-stack: Alertmanager endpoint is not getting configured in prometheus helm chart for external alertmanager

### ISSUE THREAD

**Issue by ravindraprasad85** [prometheus-community/helm-charts#2799]
### Describe the bug a clear and concise description of what the bug is.

I just want to send the alert to external endpoints by using this prometheus helm chart

I have tried below two options in values.yaml (kube-prometheus-stack) which is not working at all.
FYI: My internal "alertmanager-kube-prometheus-stack-alertmanager-0" is disabled as we need to send alerts to external alertmanager by using prometheus.
i have attached snaps where there is no Alertmanager endpoint

Method-1
  additionalAlertManagerConfigs:
      - static_configs:
        - targets: pmaas-db.xvz.mydomain.biz
        scheme: http
        server: pmaas-db.xvz.mydomain.biz:80

Method-2
`    alertingEndpoints:
       - name: "[pmaas-db.xvz.mydomain.biz](http://pmaas-db.xvz.mydomain.biz/)"
         namespace: ""
         port: http
         scheme: http
         pathPrefix: "/am0tid-cstcs-ccid-prod/api/prom/alertmanager"
         # static_configs:          #this is not supporting
         # - targets:
         #   - pmaas-db.xvz.mydomain.biz
         tlsConfig: {}
         bearerTokenFile: ""
         apiVersion: v2
         timeout: 10s`

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

version: 39.4.0

### What happened?

Alertmanager endpoint is not getting configured in prometheus

### What you expected to happen?

Prometheus Alert should received at external endpoint which is firing in prometheus

### Enter the changed values of values.yaml?

i have tried below methods but not working. I need only external alertmanager endpoint in prometheus
Method-1
  additionalAlertManagerConfigs:
      - static_configs:
        - targets: pmaas-db.xvz.mydomain.biz
        scheme: http
        server: pmaas-db.xvz.mydomain.biz:80

Method-2
`    alertingEndpoints:
       - name: "[pmaas-db.xvz.mydomain.biz](http://pmaas-db.xvz.mydomain.biz/)"
         namespace: ""
         port: http
         scheme: http
         pathPrefix: "/am0tid-cstcs-ccid-prod/api/prom/alertmanager"
         # static_configs:          #this is not supporting
         # - targets:
         #   - pmaas-db.xvz.mydomain.biz
         tlsConfig: {}
         bearerTokenFile: ""
         apiVersion: v2
         timeout: 10s`

### Enter the command that you execute and failing/misfunctioning.

helm upgrade kube-prometheus-stack ../kube-prometheus-stack -n monitoring (This command is well tested and working fine for all upgrade), There is no issue with command

**Comment by zeritti** [comment]
As to method-1, please, make sure the configs are correctly set as required by [alertmanager_config](https://prometheus.io/docs/prometheus/2.39/configuration/configuration/#alertmanager_config), e.g.
```
additionalAlertManagerConfigs:
  - scheme: http
    static_configs:
      - targets: 
          - "pmaas-db.xvz.mydomain.biz"
        labels:        
          server: pmaas-db.xvz.mydomain.biz:80
```

Method-2 can only work if the external alertmanager instance has corresponding service [endpoints](https://v1-24.docs.kubernetes.io/docs/reference/kubernetes-api/service-resources/endpoints-v1/) in some namespace accessible to Prometheus (this is why `namespace` is required and cannot be empty). Once such an endpoint exists, you can set [alertingEndpoints](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.AlertmanagerEndpoints) for  that endpoint.

**Comment by ravindraprasad85** [comment]
@zeritti - Hats off to you , Its working with Method-1

**Comment by franklinRibe** [comment]
I will commented the solution if anyone needed:
`prometheus:
   prometheusSpec:
     additionalAlertManagerConfigs:
       - scheme: http
         path_prefix: /
         static_configs:
            - targets: ['DNS_NAME_OR_IP_EXTERNAL_ALERTMANAGER']
               labels:
                 group: LABEL_THAT_YOU_WANT`

**Comment by ff-fgomez** [comment]
> I will commented the solution if anyone needed:
> 
> ```yaml
> additionalAlertManagerConfigs: 
>   - scheme: http
>      path_prefix: /
>      static_configs:
>         - targets: ['EXTERNAL_URL_TO_ALERTMANAGER']
>            labels:
>               group: LABEL_THAT_YOU_WANT
> ```

Life saver!
