### ISSUE TITLE
Deprecate stable prometheus charts

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#28]
After #11 and #34 

Note these PRs must be done properly, per https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by gkarthiks** [comment]
@scottrigby does this mean, all the existing chart maintainers need to do a PR for helm/stable ?

**Comment by Xtigyro** [comment]
@gkarthiks Yes, we do.

**Comment by gkarthiks** [comment]
I will raise a PR for deprecating the stable charts for all the 17 tomorrow for by myself if that's ok with everyone.

**Comment by Xtigyro** [comment]
It's fine for `prometheus` Helm chart.

**Comment by scottrigby** [comment]
#34 is done, so we're good to go for opening these PR. Feel free to ping me in the PRs and I'll review/merge if other chart maintainers don't get to them first 🏃

**Comment by scottrigby** [comment]
@gkarthiks I somehow missed your reply - that would be great!

**Comment by scottrigby** [comment]
@naseemkullah ended up submitting PRs tonight

**Comment by gkarthiks** [comment]
@scottrigby no worries. I see the PR https://github.com/helm/charts/pull/23693 only for `prometheus-operator`. Will do the rest then.

**Comment by gkarthiks** [comment]
@scottrigby  My bad...!!! I didn't see the merged PRs. That's awesome @naseemkullah

**Comment by torstenwalter** [comment]
Good job deprecating all charts! Adding this for documentation purpose:

| chart | PR |
| --- | --- |
prometheus-adapter | https://github.com/helm/charts/pull/23694
prometheus-blackbox-exporter | https://github.com/helm/charts/pull/23695
prometheus-cloudwatch-exporter | https://github.com/helm/charts/pull/23696
prometheus-consul-exporter | https://github.com/helm/charts/pull/23697
prometheus-couchdb-exporter | https://github.com/helm/charts/pull/23698
prometheus-mongodb-exporter | https://github.com/helm/charts/pull/23699
prometheus-mysql-exporter | https://github.com/helm/charts/pull/23700
prometheus-nats-exporter | https://github.com/helm/charts/pull/23701
prometheus-node-exporter | https://github.com/helm/charts/pull/23702
prometheus-operator 
prometheus-postgres-exporter | https://github.com/helm/charts/pull/23703
prometheus-pushgateway | https://github.com/helm/charts/pull/23704
prometheus-rabbitmq-exporter | https://github.com/helm/charts/pull/23705
prometheus-redis-exporter | https://github.com/helm/charts/pull/23706
prometheus-snmp-exporter | https://github.com/helm/charts/pull/23708
prometheus-to-sd | https://github.com/helm/charts/pull/23707
prometheus | https://github.com/helm/charts/pull/23692

**Comment by scottrigby** [comment]
https://github.com/helm/charts/issues/21103 updated

Let's leave this open until #1 is complete

**Comment by scottrigby** [comment]
Finished the last one: https://github.com/helm/charts/pull/23738

Pending prow test-infra issues from earlier. If it fails again I'll just force-merge it.

I have also updated https://github.com/helm/charts/issues/21103 ✅
