### ISSUE TITLE
prometheus-kube-stack -  Documentation incomplete

### ISSUE THREAD

**Issue by asettouf** [prometheus-community/helm-charts#2808]
### Describe the bug a clear and concise description of what the bug is.

It is indicated in extraSecret that password should be hashed. However it's unclear which hashing algorithm should be used.

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L704

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13-gke.900", GitCommit:"900b919b3b8275ecb9f70a489a318b5b08a4ab9c", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:23Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-kube-stack 

### What's the chart version?

latest

### What happened?

Missing hash function to be used in the doc

### What you expected to happen?

I'd expect the hashing algorithm expected to be mentioned

### Enter the command that you execute and failing/misfunctioning.

sha1sum mypassword

**Comment by asettouf** [comment]
> What hash? Secrets are base64 encoded. Whats in the secret and which format it is depneds only on your secret.

Ah so the documentation is just wrong mentioning hashing instead of encoding

**Comment by monotek** [comment]
What are you referring to?
