### ISSUE TITLE
[kube-prometheus-stack] allow override kube-system namespace

### ISSUE THREAD

**Issue by louis030195** [prometheus-community/helm-charts#281]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy kube-prometheus-stack but my cluster limit to only one namespace, kube-prometheus-stack deploy both to the given "namespaceOverride" value and to kube-system, so I can't deploy it.

**Describe the solution you'd like**
`kubeSystemNamespaceOverride=foo` (or any name that fit better). i.e. possibility to override this hard coded namespace.

**Describe alternatives you've considered**
Not using kube-prometheus-stack.

**Additional context**
Is it mandatory to deploy things on kube-system ?

**Comment by scottrigby** [comment]
Can you not just use helm install/update `--namespace` flag?

**Comment by louis030195** [comment]
> Can you not just use helm install/update `--namespace` flag?

Unfortunately, no, I can only tweak the values (UI deployment, not CLI ...)
