### ISSUE TITLE
[prometheus-pushgateway] Doesn't respect serviceMonitor.additionalLabels

### ISSUE THREAD

**Issue by gozer** [prometheus-community/helm-charts#2826]
### Describe the bug a clear and concise description of what the bug is.

It's in the default [values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/values.yaml#L224) file

It was apparently removed in 1349fc508af7fb131fe77c617b4abae13948dc1a inadvertently

### What's your helm version?

version.BuildInfo{Version:"v3.10.0", GitCommit:"ce66412a723e4d89555dc67217607c6579ffcb21", GitTreeState:"clean", GoVersion:"go1.18.6"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-pushgateway

### What's the chart version?

2.0.2

### How to reproduce it?

values.yaml:

```yaml
serviceMonitor:
  enabled: true
  additionalLabels:
    foo: bar
```

### Enter the changed values of values.yaml?

serviceMonitor:
  enabled: true
  additionalLabels:
    foo: bar

### Enter the command that you execute and failing/misfunctioning.

helm template prometheus-community/prometheus-pushgateway --values values.yaml

**Comment by zeritti** [comment]
Ref. #2820
