### ISSUE TITLE
[kube-prometheus-stack]I need to use HTTPS to access the web pages of prometheus and alertmanagement

### ISSUE THREAD

**Issue by michelalive** [prometheus-community/helm-charts#2828]
### Is your feature request related to a problem ?

As the title says, I need to use https to access, and I need to modify the parameter web.config The secret specified by file is managed by the crd resource of the profileus and cannot be modified. How can I modify it?

### Describe the solution you'd like.

I need to use HTTPS to access the web pages of prometheus and alertmanagement

### Describe alternatives you've considered.

NONE

**Comment by zeritti** [comment]
The desired TLS configuration can be set through the chart's `prometheus.prometheusSpec.web` and `alertmanager.alertmanagerSpec.web`, respectively, corresponding to [AlertmanagerWebSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.AlertmanagerWebSpec) and [PrometheusWebSpec](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PrometheusWebSpec).

The secrets you are mentioning get created by the operator out of the configuration and eventually mounted as `CONFDIR/web-config/web-config.yaml` in the container, e.g. `/etc/prometheus/web_config/web-config.yaml`. The path is then used as the value of the `--web.config.file` start-up flag.

Enabling TLS will have effect on probes like ReadinessProbe, LivenessProbe and StartupProbe as these use by default a `httpGet` with the HTTP scheme.

**Comment by michelalive** [comment]
> 
Thank you very much.About the "prometheus.prometheusSpec.web",Can you give me some examples of how to write it?I have tried to write here, but they are all wrong

**Comment by zeritti** [comment]
As a brief example, this snippet of a values file enables HTTPS at prometheus provided secret `prometheus-tls` exists in the namespace. This secret holds the private key (PEM base64-encoded) in key `tls.key` and certificate (PEM base64-encoded) in key `tls.crt`.
```
prometheus:
  prometheusSpec:
    web:
      tlsConfig
        keySecret:
          key: tls.key
          name: prometheus-tls
        cert:
          secret:
            key: tls.crt
            name: prometheus-tls
```
Once rolled out, both TLS keys get stored by the operator in `/etc/prometheus/web_config` as `secret_prometheus-tls_tls.crt` and `secret_prometheus-tls_tls.key`. The web-config configuration file `web-config.yaml` gets updated accordingly:
```
tls_server_config:
  cert_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.crt
  key_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.key
```

BTW The probes' scheme, e.g. that of livenessProbe, gets changed by the operator from HTTP to HTTPS.

**Comment by michelalive** [comment]
> As a brief example, this snippet of a values file enables HTTPS at prometheus provided secret `prometheus-tls` exists in the namespace. This secret holds the private key (PEM base64-encoded) in key `tls.key` and certificate (PEM base64-encoded) in key `tls.crt`.
> 
> ```
> prometheus:
>   prometheusSpec:
>     web:
>       tlsConfig
>         keySecret:
>           key: tls.key
>           name: prometheus-tls
>         cert:
>           secret:
>             key: tls.crt
>             name: prometheus-tls
> ```
> 
> Once rolled out, both TLS keys get stored by the operator in `/etc/prometheus/web_config` as `secret_prometheus-tls_tls.crt` and `secret_prometheus-tls_tls.key`. The web-config configuration file `web-config.yaml` gets updated accordingly:
> 
> ```
> tls_server_config:
>   cert_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.crt
>   key_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.key
> ```
> 
> BTW The probes' scheme, e.g. that of livenessProbe, gets changed by the operator from HTTP to HTTPS.

This has solved a big problem for me. Thank you very much

**Comment by michelalive** [comment]
> As a brief example, this snippet of a values file enables HTTPS at prometheus provided secret `prometheus-tls` exists in the namespace. This secret holds the private key (PEM base64-encoded) in key `tls.key` and certificate (PEM base64-encoded) in key `tls.crt`.
> 
> ```
> prometheus:
>   prometheusSpec:
>     web:
>       tlsConfig
>         keySecret:
>           key: tls.key
>           name: prometheus-tls
>         cert:
>           secret:
>             key: tls.crt
>             name: prometheus-tls
> ```
> 
> Once rolled out, both TLS keys get stored by the operator in `/etc/prometheus/web_config` as `secret_prometheus-tls_tls.crt` and `secret_prometheus-tls_tls.key`. The web-config configuration file `web-config.yaml` gets updated accordingly:
> 
> ```
> tls_server_config:
>   cert_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.crt
>   key_file: /etc/prometheus/web_config/secret_prometheus-tls_tls.key
> ```
> 
> BTW The probes' scheme, e.g. that of livenessProbe, gets changed by the operator from HTTP to HTTPS.

Sorry, I want to bother again. If I need to add basic_auth to "web-config.yaml". What should I do?

**Comment by zeritti** [comment]
I am afraid basic authentication at Prometheus is not supported by the operator as yet. There's PR [#4652](https://github.com/prometheus-operator/prometheus-operator/pull/4652) on this topic but still a draft. At the moment, you can work around that by using a proxy, e.g. Nginx running as a sidecar container, or handle  it at the ingress level.

**Comment by guoard** [comment]
@zeritti please reopen this issue.
