### ISSUE TITLE
Unable to Upgrade or even rollback to previous revision

### ISSUE THREAD

**Issue by yathishgowdaanandaraj-pge** [prometheus-community/helm-charts#284]
I installed the kube-prometheus-stack on EKS, it all worked fine initially but then when I upgraded the grafana svc to service type loadbalancer with --set flag the upgrade was succesful. But then the loadbalancer was in the pending state for a long time so I tried to rollback to the previous version and helm threw an error 

"Error: UPGRADE FAILED: cannot patch "prometheus-nonprod-grafana" with kind Service: Service "prometheus-nonprod-grafana" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP"

So I decided to upgrade the version by passing a yaml file with service type as ClusterIP for grafana service and it still throws the same error. Not sure how to go about this. Attaching the screenshots.

<img width="1504" alt="Screen Shot 2020-10-29 at 2 04 51 PM" src="https://user-images.githubusercontent.com/64862207/97621170-91915b80-19f0-11eb-8e6e-a852c0c6f7bd.png">

**Comment by byangtri** [comment]
@yathishgowdaanandaraj-pge  were you ever able to resolve this

**Comment by yathishgowdaanandaraj-pge** [comment]
Yes I did, I just had to delete the service manually and deploy the stack again which created new service again.
