### ISSUE TITLE
[prometheus-kube-stack] Some Grafana dashboards are getting empty values although in Prometheus they are available

### ISSUE THREAD

**Issue by borgdrone7** [prometheus-community/helm-charts#2847]
### Describe the bug a clear and concise description of what the bug is.

Some default Dashboards in Grafana like Kubernetes / Compute Resources work like others like for example Kubernetes / Proxy are empty. 
When I check Prometheus the values are there but Grafana query always returns empty set although the call is ok and returns HTTP code 200. Please check the images below.

![prometheus cpu](https://user-images.githubusercontent.com/4692377/209336094-4e0669e3-6967-41b9-9f94-ecca657df81a.png)
![grafana cpu](https://user-images.githubusercontent.com/4692377/209336024-ae4d51d3-e3fe-4942-892d-a1c668f4c675.png)

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9+k3s1", GitCommit:"f45cf3267307b153ed8b418ae5b8ea6c6b9ebaca", GitTreeState:"clean", BuildDate:"2022-07-19T00:42:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-kube-stack (I am not sure exactly which chart from the stack is affecting this)

### What's the chart version?

"kube-prometheus-stack-43.1.1"

### What happened?

Kube Proxy and some other dashboards are empty while some like Compute resources are ok although Prometheus exposes values for both

### What you expected to happen?

All dashboards work and update values

### How to reproduce it?

Deploy the stack with above heml, kubernetes and chart versions.

##
    externalUrl: http://{{ template "kube-prometheus-stack.fullname" . }}-prometheus.{{ template "kube-prometheus-stack.namespace" . }}:{{ .Values.prometheus.service.port }}/prom

grafana:
  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/grafana"
      serve_from_sub_path: true

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prom-mon  helm/platform/kube-prometheus-stack --install --atomic --cleanup-on-fail --wait --devel --create-namespace --namespace monitoring --set "fullnameOverride=kubeprom"

**Comment by zeritti** [comment]
I'd guess that although some of the time series are available, the panel's query returns an empty set due to a label that is being specified in the query leading to a no match result. 

The query specifies `job=kube-proxy` but there do not seem to be any time series with this label as seen in Prometheus UI. You can check in the UI under Status/Targets if kube-proxy is amongst successfully scraped targets. Also, if you take the query and execute it in the UI replacing variables with appropriate literals, you can gradually determine where the problem lies.

**Comment by borgdrone7** [comment]
> I'd guess that although some of the time series are available, the panel's query returns an empty set due to a label that is being specified in the query leading to a no match result.
> 
> The query specifies `job=kube-proxy` but there do not seem to be any time series with this label as seen in Prometheus UI. You can check in the UI under Status/Targets if kube-proxy is amongst successfully scraped targets. Also, if you take the query and execute it in the UI replacing variables with appropriate literals, you can gradually determine where the problem lies.

Hi, thanks for the quick response. I tried changing the label however unless I also hard-code an instance url I don't get any results. Also I saw that Grafana queries have a query for variables coming from kube-proxy however they aren't in Prometheus. Seems like kube-proxy is not exposed at all.
So basically the stack is not working as expected out of the box. Can it maybe be because I am using K3S cluster? Are there any known issues/workarounds with the stack working on K3S?

**Comment by zeritti** [comment]
There are always two sides in this: Prometheus/Prometheus operator have to be told of your potential monitoring targets and your monitoring targets have to be told to expose their metrics endpoints.

As to the former, you set the appropriate values in your values file reflecting your environment, thus configuring the stack for your cluster.

For the latter, one has to make sure that the services' metrics ports are exposed. For kube-proxy in particular, it opens its metrics port (10249/tcp) at the localhost only, hence, it is not accessible to Prometheus. To make these scrapable by Prometheus, they need to be started with the appropriate flags, e.g. for kube-proxy `--metrics-bind-address=0.0.0.0:10249`. This concerns the cluster deployment itself.

You will probably need to set `endpoints` for control plane services in the given section of the values file, and appropriate service ports and scheme.

**Comment by borgdrone7** [comment]
> 

Thanks @zeritti , I actually used this config for K3s:

`apiVersion: k3d.io/v1alpha4
kind: Simple
options:
  k3s:
    kube-controller-manager-arg:
      - "address=0.0.0.0"
      - "bind-address=0.0.0.0"
    kube-proxy-arg:
      - "metrics-bind-address=0.0.0.0"
    kube-scheduler-arg:
      - "address=0.0.0.0"
      - "bind-address=0.0.0.0"
    etcd-expose-metrics: true`

However I still don't get the values in the Dashboard. When you say "You will probably need to set endpoints for control plane services in the given section of the values file" what do you mean by that? I in values yml I have for example:

`kubeProxy:
  enabled: true

  ## If your kube proxy is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
`
So how do I know which IP address to use, and why is not this handled by the prom stack like for the dashboards which work?

Thanks

**Comment by borgdrone7** [comment]
I solved the issue by setting endpoints to node IPs and using Prometheus filtering to remove K3s duplicates.
