### ISSUE TITLE
Cannot Deploy AlertManager with PVC

### ISSUE THREAD

**Issue by TechBrain64** [prometheus-community/helm-charts#2859]
### Describe the bug a clear and concise description of what the bug is.

I have made numerous attempts to deploy PV using custom-values.yaml file only to uninstall and start again. In the confusion of these attemps I had removed the CRDs before running the uninstall. This lead me to manually remove remainder of the code. At some point I broke my ability to successfully redeploy prometheus stack. I now get the following error everytime:

[command executed]
helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitor-system --values custom-values.yaml 

These are the changes I made in the custom.values.yaml:

[under AlertManager]
storage: 
    volumeClaimTemplate:
      spec:
        storageClass: longhorn
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

[under Prometheus]
 storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

The Prometheus config works and Longhorn provisions the 50 Gi volume. Nothing happens with AlertManger and I see nothing in logs.

### What's your helm version?

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+wcp.3", GitCommit:"fb53e772aa2828c695b1f6b9fe83c63f87c27cf6", GitTreeState:"clean", BuildDate:"2021-02-05T05:07:45Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14+k3s1", GitCommit:"c62b03fb70fbabb198b7f9fb5eb0e11010246360", GitTreeState:"clean", BuildDate:"2022-11-18T18:42:08Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

43.1.1 - 43.1.3 (unsure)

### What happened?

[the error]
Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-kube-prometheus-operator.monitor-system.svc:443/admission-prometheusrules/mutate?timeout=10s": service "prometheus-kube-prometheus-operator" not found

### What you expected to happen?

I would like to know how I can resolve this issue. I've already tried deleting the namespace, recreating it and redeploying; no good.

And have to project succesfully installed with AlertManager using 10Gi PV and Prometheus 50Gi.

### How to reproduce it?

I guess first remove the CRDs and then manually delete all other references of deployment from cluster, 

### Enter the changed values of values.yaml?

[under AlertManager]
storage: 
    volumeClaimTemplate:
      spec:
        storageClass: longhorn
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

[under Prometheus]
 storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: 
          - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitor-system --values custom-values.yaml

**Comment by AkshayAwate** [comment]
[This](https://github.com/prometheus-community/helm-charts/issues/108) might help! @TechBrain64
