### ISSUE TITLE
[complete stack] Stack is not working by default on K3S clusters, enable it to work out of the box on K3S

### ISSUE THREAD

**Issue by borgdrone7** [prometheus-community/helm-charts#2865]
### Is your feature request related to a problem ?

Hi, I am trying to setup kube prometheus stack on K3s and I am having a lot of issues. By default kube controller, proxy and etcd services are not mapped to any endpoint (with the latest version of the stack) and I have empty dashboards for those services in Grafana. Also I read that K3s is exposing metrics from all these in each of them so for the ones which work I will get duplicated data in the Prometheus. So is there custom version of kube prometheus stack which works with K3s and if not, are there any workarounds to get it to work with the latest prom stack version?

### Describe the solution you'd like.

I don't have a solution. I noticed that if I add node IP for the services which do not work (proxy, controller, etcd) to endpoints key in values yaml I get Grafana dashboard showing values. I only tested it with version 41 of the stack. But this solution is not longterm and doesn't seem like something I could count on. Didn't test with multi node setup and not sure how would that work. Also I don't understand why it even works (I guess because k3s exposes all variables on all services but not sure)

### Describe alternatives you've considered.

I don't know of any alternatives.

**Comment by Camphul** [comment]
This helm chart pulls metrics from services not related to prometheus. To configure k3s with this chart you will have to add certain arguments to the k3s service (see k3s docs, expose etcd metrics to 0.0.0.0 as an example). Then configure this chart's applicable endpoints to your node ip's.

Issue can be closed?

**Comment by borgdrone7** [comment]
> This helm chart pulls metrics from services not related to prometheus. To configure k3s with this chart you will have to add certain arguments to the k3s service (see k3s docs, expose etcd metrics to 0.0.0.0 as an example). Then configure this chart's applicable endpoints to your node ip's.
> 
> Issue can be closed?

Hi, I exposed all the k3s metrics by configuring it, however duplicated data is still there, so if anyone is using this chart by just simply configuring k3s and the endpoints then he will get a lot of wasted resources. I partially solved it by adding some drop filters in chart's Prometheus scraper configuration. The point is that the stack is not working out of the box with k3s and it is not easy to make it work correctly (not that I say it should, but it would be nice if it did). I see on the net that people mostly ignore this duplication which is sub optimal as they will get 4x the data in their system, or they do things like disabling all metrics in k3s except one in which case they loose ability to easily upgrade the stack as they need to manually configure Prometheus scraping and Grafana dashboards, basically completely changing the stack. I asked k3s developers and they told me that I should enable only one metrics endpoint to avoid duplicates, which in turn beats the purpose of this stack as too much of the stuff needs to be changed.
Regarding endpoints I did add all nodes IPs to the chart's endpoints configuration, however this requires that metrics are exposed on 0.0.0.0 which might be a security issue (not 100% sure but it looks like it as Prometheus by default has no authentication of any kind). Do you have any idea how to enable stack to scrape the data without exposing the metrics on 0.0.0.0? Or is there some easy way to expose them and still secure these endpoints? 
Thanks

**Comment by onedr0p** [comment]
@borgdrone7 are you willing to share your helm values for dropping the duplicate metrics? It would help out greatly. Thanks!

**Comment by maradanasai** [comment]
Thanks @onedr0p for this. Anything latest on this? also, can you please share more details on why kubeProxy is disabled due to eBPF ?

**Comment by denniseffing** [comment]
This issue should be re-opened. To this day, kube-prometheus-stack collects all metrics 5 times and is therefore not really suited for a deployment on k3s clusters.

**Comment by onedr0p** [comment]
This isn't an issue with kube prometheus stack, it's an issue work how k3s exposes these metrics.

**Comment by denniseffing** [comment]
It depends on how you look at it. What I understand is that to fix this issue, k3s must expose the metrics like all other k8s distributions. However, due to constraints in the Prometheus Go libraries, this is technically not possible without k3s moving away from its monolithic architecture (as explained in [k3s#3619 comment 1483521268](https://github.com/k3s-io/k3s/issues/3619#issuecomment-1483521268)).

But shouldn't it also be possible to rework kube-prometheus-stack's monitoring configuration so that it is aware of k3s monolithic architecture and metrics are only scraped once? I guess this would also require reworking the Grafana dashboards as well. Guess that'd be a lot of work. Or am I missing something?

**Comment by onedr0p** [comment]
It would be a lot of work to do what you purpose, yes because there needs to be relabelings to drop the duplicated metrics on each component and require people willing to keep these metric relabelings up-to-date. This issue was one major reason why I have since moved to Talos since it doesn't inherit this problem.
