### ISSUE TITLE
[all] Automatically create a new release of a chart when a new release of one of its subcharts is created

### ISSUE THREAD

**Issue by jsolbrig** [prometheus-community/helm-charts#2869]
### Is your feature request related to a problem ?

When a PR is accepted for a specific chart a new release is created for that chart. However, if that chart is used as a subchart by any other charts, the parent charts won't begin making use of the new release until a new release is created for the parent chart.

### Describe the solution you'd like.

When a new release is created for a chart, use CI (an action) to determine whether any other charts depend on the updated chart, then automatically create a new release for each of the parent charts as well.

### Describe alternatives you've considered.

Add a review step to determine if any parent charts need to be updated before accepting a PR.

Also, in the mean time, I have created PRs to update the two charts that depend on `prometheus-node-exporter` (#2867 and #2868).

### Additional context.

I ran into this issue after fixing a bug in `prometheus-node-exporter` (see #2825). This is partly a misunderstanding on my part, but I think that the workflow could be improved.

There was a bug in `prometheus-node-exporter` that was introduced in v4.5.1 that I fixed in v4.8.1. Since only the major and minor versions for chart dependencies are pinned in this repo, I assumed that pulling a new copy of the same version of `kube-prometheus-stack` would collect the updated version of `prometheus-node-exporter. 

I made this assumption because I didn't appreciate the role of `Chart.lock` in a released chart. Since it freezes the versions of the dependencies, a new release of `kube-prometheus-stack` is also required before it can be distributed with the updated dependency by default.

While this behavior should be expected due to what `Chart.lock` does, it would be nice if a new release of the parent chart had automatically been created when a new release was made for one of its subcharts.

The reason that this is important to me is because I'm using argocd to deploy my applications. Without modification, argocd doesn't allow me to run `helm dependency update` to retrieve newer versions of the subcharts.

**Comment by monotek** [comment]
The reason for the chart.lock is to guarantee fixed versions. 

I don't see this as a solution.

Dependency updatesbreaking changes. Stuff like this should only be added manually, together with update instructions. An automated process can't do this.
