### ISSUE TITLE
kube-prometheus-stack alongside istio setup

### ISSUE THREAD

**Issue by entrymon** [prometheus-community/helm-charts#2870]
### Is your feature request related to a problem ?

The chart does great job in setting up prometheus stack, would be good to get some help in understanding how this works alongside of istio.

Here is the situation

- Have local minikube installed with 6 nodes
- Have istio installed
- Have created new namespace for prometheus - called monitoring.

### Describe the solution you'd like.

Documentation around how this char should work along side istio?

- Should we inject istio of monitoring namespace?
- How to configure values to work along side istio?
- Any best practices and recommendations.

### Describe alternatives you've considered.

Documentation within istio is confusing https://istio.io/latest/docs/ops/integrations/prometheus/

**Comment by alterEgo123** [comment]
Hello, were you able to do it?
