### ISSUE TITLE
[prometheus-kube-stack] A lockfile from a previous execution already existed. It was replaced

### ISSUE THREAD

**Issue by guobei2028** [prometheus-community/helm-charts#2872]
### Describe the bug a clear and concise description of what the bug is.

my prometheus often restarts because of lockfile. The log when restarting is as follows。

__CONTENT__:ts=2022-12-30T05:00:23.828Z caller=head.go:551 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
_CONTENT__:ts=2022-12-30T05:00:23.746Z caller=tls_config.go:231 level=info component=web msg="TLS is disabled." __CONTENT__:ts=2022-12-30T05:00:23.735Z caller=dir_locker.go:77 level=warn component=tsdb msg="A lockfile from a previous execution already existed. It was replaced" file=/prometheus/lock
__CONTENT__:ts=2022-12-30T05:00:23.735Z caller=db.go:851 level=info component=tsdb msg="Found and deleted tmp block dir" dir=/prometheus/01GNGPDTWFQJFZ25N1R2H1P9BY.tmp-for-creation

### What's your helm version?

3.3.0

### What's your kubectl version?

1.20.6 , eks cluster

### Which chart?

prometheus-kube-stack

### What's the chart version?

41.7.3

### What happened?

Prometheus often restarts because of lockfile. "A lockfile from a previous execution already existed. It was replaced"

I just deployed 1 replicas.

### What you expected to happen?

I hope the prometheus-kube-stack chart value file supports configuring the startup parameters of prometheus.
--storage.tsdb.no-lockfile

So as to solve the problem of prometheus restarting because of lockfile

### Enter the command that you execute and failing/misfunctioning.

 helm insall prometheus prometheus-community/prometheus-kube-stack --version 41.7.3 --values values.yaml

**Comment by guobei2028** [comment]
https://github.com/prometheus-community/helm-charts/issues/2169
The same problem as this issue，It also has no solution in it

having the same issue with prometheus v2.39.1

**Comment by chimera-rep** [comment]
The same problem as this issue，It also has no solution in it

**Comment by PickledChris** [comment]
[Ensure rpc-statd is running on your node](https://github.com/prometheus-community/helm-charts/issues/2169#issuecomment-1648243012)

**Comment by debuggedme** [comment]
oom-kill
