### ISSUE TITLE
[Prometheus] No private IP found, explicit advertise addr not provided

### ISSUE THREAD

**Issue by StellaV** [prometheus-community/helm-charts#2880]
### Describe the bug a clear and concise description of what the bug is.

`ts=2023-01-03T11:35:41.977Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
ts=2023-01-03T11:35:41.978Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe866dd5717, date=20221222-14:51:36)"
ts=2023-01-03T11:35:41.982Z caller=cluster.go:178 level=warn component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
ts=2023-01-03T11:35:41.985Z caller=main.go:272 level=error msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"`

### What's your helm version?

version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus

### What's the chart version?

19.2.2

### What happened?

I deployed Prometheus with Alertmanager using the prometheus helm chart (not the operator) as a sub-chart of another deployment. The Prometheus part works perfectly fine and alertmanager's ingress is correctly created, but the pod dies due to an error message. 

Any idea what can be done to solve this? :)

### What you expected to happen?

Pod works

### Enter the changed values of values.yaml?

`
  alertmanager:

    enabled: true

    config:
      global: {}
        # slack_api_url: 
      templates:
        - /etc/alertmanager/*.tmpl
      receivers:
        - name: default-receiver
      route:
        group_wait: 10s
        group_interval: 5m
        receiver: default-receiver
        repeat_interval: 3h

    ingress:
      enabled: true
      className: alb
      ## Alertmanager Ingress annotations
      ##
      annotations:
          <...>
      ## Prometheus server Ingress hostnames with optional path
      ## Must be provided if Ingress is enabled
      ##
      hosts:
        - host: <this works>
          paths:
            - path: /
              pathType: Prefix
`

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus . --namespace prometheus --values ./values.yaml

### Anything else we need to know?

We're running an IPv6 k8s cluster and only want a single replica of AM.

**Comment by zeritti** [comment]
AM still needs to bind to a cluster advertise address. It looks for a private IP as defined in RFC 6890 that it can use (see also [README](https://github.com/prometheus/alertmanager#high-availability) on HA). Finding none, it won't start. In such a case, setting the address explicitely is needed, e.g.
```
alertmanager:
  extraArgs:
    cluster.advertise-address: "[$(POD_IP)]"
```
That would use the pod's IP address available in env variable POD_IP. The chart itself sets this flag to $POD_IP only if `alertmanager.replicaCount` > 1 or `alertmanager.additionalPeers` are present.

**Comment by StellaV** [comment]
@zeritti Thanks a lot for this one. I wonder why it's not default, if it AM cannot run without it? 

I did have to go a bit further than your suggestion due to the following error: 
`ts=2023-01-04T09:15:47.965Z caller=main.go:272 level=error msg="unable to initialize gossip mesh" err="invalid advertise address: address [ipv6 addr here]: missing port in address"`


So, I added the port to it:
`alertmanager:
  extraArgs:
    cluster.advertise-address: "[$(POD_IP)]:9093"`
