### ISSUE TITLE
[kube-prometheus-stack] No $cluster variable is being taken from any ServiceMonitor

### ISSUE THREAD

**Issue by jpicara** [prometheus-community/helm-charts#2887]
Hi,
It was detected that we are **missing metrics** from some of the built-in dashboards in Grafana because of the lack of cluster variable value. Some examples:
In Dashboard: Kubernetes / Compute Resources / Cluster CPU usage is trying to retrieve the value from:
`sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster"}) by (namespace)`
Where **$cluster is defined as a variable**: `label_values(up{job="kubelet", metrics_path="/metrics/cadvisor"}, cluster)`. **However it does not retrieve any value**, as this key value pair is not inside the metric up:
`up{endpoint="https-metrics", instance="192.168.49.2:10250", **job="kubelet"**, metrics_path="/metrics/cadvisor", namespace="kube-system", node="minikube", service="monitoring-platform-kube-p-kubelet"}`

However it is not only on the kubelet job coming from the service monitoring-platform-kube-p-kubelet but also:
In Kubernetes / Compute Resources / Workload Dashboard, the graph CPU usage is querying:
`sum(
    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster="$cluster", namespace="$namespace"}
  * on(namespace,pod)
    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster="$cluster", namespace="$namespace", workload="$workload", workload_type="$type"}
) by (pod)
`
Being $cluster the output of the variable: ` label_values(up{**job="kube-state-metrics"**}, cluster)`
As it happens with kubelet, there is not key value par called cluster:
`up{container="kube-state-metrics", endpoint="http", instance="172.17.0.6:8080", job="kube-state-metrics", namespace="platform", pod="monitoring-platform-kube-state-metrics-c888d57fc-h4xbb", service="monitoring-platform-kube-state-metrics"}`

I tried to apply some workaround found on tickets like: https://github.com/prometheus-operator/kube-prometheus/issues/1056 or https://github.com/prometheus-community/helm-charts/issues/1664 but unable at this point.

Could someone help me to make this variable working and so that all the dashboard filled?
BTW, I am trying this solution over a minikube, but checked in a real environment and that variable is not either present.
Thanks in advance,

### What's your helm version?

version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

43.2.1

### What happened?

No output of $cluster variable as it is not present in any of the prometheus jobs (ServiceMonitors)

### What you expected to happen?

All the grafana dashboards should show data as they are released on the latest versions.

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n kube-prometheus

**Comment by zeritti** [comment]
The included dashboards support multi-cluster environment where the label naturally exists, e.g. central multi-cluster metrics aggregation through federation or remote writes. If it does not, you'd have to add the label `cluster`. There are quite a few ways of doing this. Generally with service monitors, you may wish to attach a new label to the discovered scrape target endpoints via `servicemonitor.endpoints.relabelings`. 

For instance, for the kubelet service monitor in the values file:
```
kubelet:
  enabled: true
  serviceMonitor:
    cAdvisor: true
    cAdvisorRelabelings:
    - sourceLabels: [__address__]
      targetLabel: cluster
      replacement: staging
...
```
resulting in a new label `cluster="staging"` attached to each time series coming out of that endpoint. You'd need to add that relabelings item to each endpoint and there are a few for kubelet if enabled (relabelings, resourceRelabelings, probesRelabelings). Similarly for other service monitors. 

For more info, please, see description of relabelings, metricRelabelings and targetLabels in the servicemonitor [CRD](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor).

Adding this particular label may be easier once PR 2877 gets merged.

**Comment by jpicara** [comment]
Hi,
Thanks for your reply. I have deployed the whole kube-prometheus-stack in one of our existing environments and that $cluster even though it was not taken as the variable was not defined, grafana dashboard prints successfully data.
Apart from that, I also enabled that variable for testing purposes and everything works well.

**Comment by jpicara** [comment]
Proceed to close the issue
