### ISSUE TITLE
[Prometheus-server ] Replicacount=3 results in pod CrashLoopBackOff error

### ISSUE THREAD

**Issue by kurekbharath** [prometheus-community/helm-charts#2894]
We are using the latest helm chart 19.3.0 to deploy prometheus-server component ONLY. We are overriding the server.replicaCount to 3. We are seeing the below error.
`ts=2023-01-07T05:44:04.892Z caller=main.go:1132 level=error err="opening storage failed: lock DB directory: resource temporarily unavailable"`
Based on several Prometheus sources (GitHub Issue), I used server.strategy.type=RollingUpdate instead of recreate. Still, I see the same error. 
This error is seen only when we increase the pod count to more than 1. 

Please let us know how to proceed further here

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.17.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.14-dispatcher-dirty", GitCommit:"009f3ac5f1d09b1ec5d4dc811b6032271fe61f75", GitTreeState:"dirty", BuildDate:"2022-09-19T01:27:12Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-community/prometheus

### What's the chart version?

19.3.0

### How to reproduce it?

Just increase the replica count to 3 or more and only deploy Prometheus-server component and disable all the rest of other component deployment

### Enter the changed values of values.yaml?

"alertmanager.enabled"false"
"kube-state-metrics.enabled":"false",
"prometheus-node-exporter.enabled":"false"
"prometheus-pushgateway.enabled":"false"
"server.replicaCount":"3"

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-server-install prometheus-community/prometheus --namespace grafana --set alertmanager.enabled=false --set kube-state-metrics.enabled=false --set prometheus-node-exporter.enabled=false --set prometheus-pushgateway.enabled=false --set server.replicaCount=3

**Comment by zeritti** [comment]
Please, use statefulset:
```
server:
  statefulSet:
    enabled: true
```
if setting `server.replicaCount` > 1.

**Comment by kurekbharath** [comment]
@zeritti  Yeah it worked post enabling stateful set 

Thanks for the help.
