### ISSUE TITLE
kube-prometheus-stack Persistant Storage issue 

### ISSUE THREAD

**Issue by vijaybiradar** [prometheus-community/helm-charts#2906]
### Describe the bug a clear and concise description of what the bug is.

Hi Team,

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration  

grafana:
    persistence:
      enabled: True
      type: pvc
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
      size: 20Gi
prometheus:
  prometheusSpec:
    remoteWrite:
    - url:  http://mimir-prod-nginx.mimir.svc:80/api/v1/push
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi

helm command
~~~
helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack --values=prometheus.yaml -n kube-prom --version 41.7.0 --debug 

~~~

### What's your helm version?

Version:v3.7.2

### What's your kubectl version?

Major:"1", Minor:"23", GitVersion:"v1.23.5"

### Which chart?

*

### What's the chart version?

41.7.0

### What happened?

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration  

### What you expected to happen?

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration  

### How to reproduce it?

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration  

### Enter the changed values of values.yaml?

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration  

### Enter the command that you execute and failing/misfunctioning.

Unable to persist  the Prometheus and grafana data when we re-deploy/upgrade we are losing the data(need to re-add data source ,alerts ,etc) . anything missing in below configuration

**Comment by AkshayAwate** [comment]
Did you get any chance to have look at [this](https://github.com/prometheus-community/helm-charts/issues/186) ?
