### ISSUE TITLE
[kube-prometheus-stack] Missing ValidatingWebhookConfiguration for AlertManagerConfig

### ISSUE THREAD

**Issue by plaes** [prometheus-community/helm-charts#2916]
### Is your feature request related to a problem ?

Prometheus operator supports webhook validator for AlertManagerConfig:
https://prometheus-operator.dev/docs/user-guides/webhook/#alertmanagerconfig

Unfortunately this feature is not enabled in the kube-prometheus-stack (there's one for `PrometheusRule`).

### Describe the solution you'd like.

Include also ValidatingWebhookConfiguration for AlertManagerConfig if possible.

### Describe alternatives you've considered.

-

**Comment by jimethn** [comment]
Looks like we need [these example resources](https://github.com/prometheus-operator/prometheus-operator/tree/v0.62.0/example/admission-webhook) brought into the helm chart
