### ISSUE TITLE
[kube-prometheus-stack], [prometheus-blackbox-exporter] How to configure Blackbox Exporter 

### ISSUE THREAD

**Issue by JonasJW** [prometheus-community/helm-charts#292]
This is more like a help request/question but I think it would also be great to have this documented.

**Is your feature request related to a problem? Please describe.**

I'm using the kube-prometheus-stack and I have installed the Blockbox Exporter with the prometheus-blackbox-exporter. I'm having trouble with configuring the Blackbox exporter with the kube-prometheus-stack.

**Describe the solution you'd like**

I have tried overriding the values.yaml to add the exporter as a prometheus scrape target as shown below. This is the only solution that came to my mind but I think it would be even better if it was possible to add the exporter with `ServiceMonitors`, so I do not have to upgrade the chart with the values every time I want to add additional probe targets.

**Describe alternatives you've considered**

I have tried to configure the exporter with overriding the values.yaml like this:

    prometheusSpec:
      additionalScrapeConfigs: 
        - job_name: 'blackbox'
          metrics_path: /probe
          params:
            module: [http_2xx]  # Look for a HTTP 200 response.
          static_configs:
            - targets:
              - http://nodejs-client-service.default.svc.cluster.local
              - http://prometheus.io
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 'http://blackbox-exporter-prometheus-blackbox-exporter.default.svc.cluster.local' 

This does not seem to work, the Blackbox exporter does not show up in my prometheus targets and it also has no configured probe targets.

**Additional context**

**Comment by JonasJW** [comment]
I have found a solution by overwriting the values from the blackbox exporter like this:
    serviceMonitor:
      enabled: true

      defaults:
        labels:
          release: prometheus
        interval: 30s
        scrapeTimeout: 30s
        module: http_2xx

      targets:
        - name: prometheus
          url: http://prometheus.io
          labels:
            release: prometheus


    config:
      modules:
        http_2xx:
          prober: http
          http:
            preferred_ip_protocol: "ip4"

I'm still wondering if there is a way to have the targets configured in configMap that I can apply to just add probe targets without having to upgrade the chart with the override values.
Or even better if there is a way to just probe all services in my cluster.

**Comment by shibumi** [comment]
@JonasJW I had the same problem, but for me even your fix didn't help. I enabled the servicemonitor and I see the servicemonitors if I do `kubectl get servicemonitors`, but they are not showing up in the prometheus web UI as target.

**Comment by JonasJW** [comment]
@shibumi I'm not an export on this but are you sure you have set the right release label?

**Comment by shibumi** [comment]
@JonasJW yes, even with release label it's not working.

**Comment by shibumi** [comment]
@JonasJW I need this label only on the service Monitor defaults, right? Can you share your values file?

**Comment by shibumi** [comment]
@JonasJW  I see this error in my prometheus:

```
level=error ts=2020-11-04T08:51:43.635Z caller=main.go:290 msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: scrape timeout greater than scrape interval for scrape config with job name \"monitoring/blackbox-exporter-prometheus-blackbox-exporter-picturepeople/0\""
```

any idea? When I had a look into the blackbox exporter I see it's not scraping. My blackbox exporter diff is the following:

```diff
diff --git a/default.yaml b/values.yaml
index f443833..f684539 100644
--- a/default.yaml
+++ b/values.yaml
@@ -173,12 +173,13 @@ serviceMonitor:
   ## If true, a ServiceMonitor CRD is created for a prometheus operator
   ## https://github.com/coreos/prometheus-operator
   ##
-  enabled: false
+  enabled: true

   # Default values that will be used for all ServiceMonitors created by `targets`
   defaults:
     additionalMetricsRelabels: {}
-    labels: {}
+    labels:
+      release: prometheus-stack
     interval: 30s
     scrapeTimeout: 30s
     module: http_2xx
@@ -190,13 +191,32 @@ serviceMonitor:
   bearerTokenFile:

   targets:
-#    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
-#      url: http://example.com/healthz  # The URL that blackbox will scrape
-#      labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
-#      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
-#      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
-#      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
:...skipping...
diff --git a/default.yaml b/values.yaml
index f443833..f684539 100644
--- a/default.yaml
+++ b/values.yaml
@@ -173,12 +173,13 @@ serviceMonitor:
   ## If true, a ServiceMonitor CRD is created for a prometheus operator
   ## https://github.com/coreos/prometheus-operator
   ##
-  enabled: false
+  enabled: true

   # Default values that will be used for all ServiceMonitors created by `targets`
   defaults:
     additionalMetricsRelabels: {}
-    labels: {}
+    labels:
+      release: prometheus-stack
     interval: 30s
     scrapeTimeout: 30s
     module: http_2xx
@@ -190,13 +191,32 @@ serviceMonitor:
   bearerTokenFile:

   targets:
-#    - name: example                    # Human readable URL that will appear in Prometheus / AlertManager
-#      url: http://example.com/healthz  # The URL that blackbox will scrape
-#      labels: {}                       # Map of labels for ServiceMonitor. Overrides value set in `defaults`
-#      interval: 60s                    # Scraping interval. Overrides value set in `defaults`
-#      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
-#      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
-#      additionalMetricsRelabels: {}    # Map of metric labels and values to add
+    - name: picturepeople                    # Human readable URL that will appear in Prometheus / AlertManager
+      url: https://gutschein.picturepeople.de  # The URL that blackbox will scrape
+      labels:
+        release: prometheus-stack
+      interval: 5s                    # Scraping interval. Overrides value set in `defaults`
+      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
+      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
+      additionalMetricsRelabels: {}    # Map of metric labels and values to add
+    - name: picturepeople-at                   # Human readable URL that will appear in Prometheus / AlertManager
+      url: https://gutschein.picturepeople.at  # The URL that blackbox will scrape
+      labels:
+        release: prometheus-stack
+      interval: 5s                    # Scraping interval. Overrides value set in `defaults`
+      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
+      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
+      additionalMetricsRelabels: {}    # Map of metric labels and values to add
+    - name: picturepeople-nl                   # Human readable URL that will appear in Prometheus / AlertManager
+      url: https://giftcard.picturepeople.nl  # The URL that blackbox will scrape
+      labels:
+        release: prometheus-stack
+      interval: 5s                    # Scraping interval. Overrides value set in `defaults`
+      scrapeTimeout: 60s               # Scrape timeout. Overrides value set in `defaults`
+      module: http_2xx                 # Module used for scraping. Overrides value set in `defaults`
+      additionalMetricsRelabels: {}    # Map of metric labels and values to add
+
+

 ## Custom PrometheusRules to be defined
 ## ref: https://github.com/coreos/prometheus-operator#customresourcedefinitions
~
```

When I look into the blackbox-exporter via kubectl exec I see no targets defined in the blackbox.yaml. Is this normal? I don't think so

**Comment by JonasJW** [comment]
What values.yaml would you like to see? All I did after installing the kube-prometheus-stack was really just `helm install [RELEASE_NAME] prometheus-community/prometheus-blackbox-exporter -f values.yaml` (or upgrade if already installed) with the values I added in my reply.

As to your error it says `Error loading config` and I think it points to your prometheus config? Not sure what you have inside `prometheus.env.yaml ` but to configure the blackbox export you only need to override the values of the blackbox exporter.

Hope that helps

**Comment by shibumi** [comment]
@JonasJW Ok, I found the issue while uninstalling and installing the whole kube-prometheus-stack.. the prometheus pod did not come up, because of a wrong scraping interval in my configuration. The scrapeInterval can't be shorter than the ScrapeTimeout. That's why. It works now.

**Comment by shibumi** [comment]
@JonasJW  btw.. @bismarck  told me in another issue, that Prometheus supports a `Probe` Resource now: https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/prober/05_probers.yaml

**Comment by JonasJW** [comment]
@shibumi Thats good to know, thank you! Do you plan un using the Probe Resource?

**Comment by shibumi** [comment]
@JonasJW  no. I think the ServiceMonitor + Target definition in the helm chart is fine for me.. Probe would be only interesting if I want to declare Probes in another Helm projects.
