### ISSUE TITLE
[kube-prometheus-stack/grafana] Enable Grafana dashboards to be discovered in all namespaces by default

### ISSUE THREAD

**Issue by migueleliasweb** [prometheus-community/helm-charts#2928]
### Is your feature request related to a problem ?

Not a problem per se but there is a caveat when using `kube-prometheus-stack`.

The Grafana helm chart exposes a feature to configure the `k8s-sidecar` in a way that is searches for dashboards in **all namespaces** but this feature is not enabled by default whici conflicts a bit wiith the rest of the features already exposed by Prometheus Operator.

All the Prometheus Operator kinds e.g `PrometheusRule` are already distributed and automatically discovered in all namespaces. This is vital feature for any platform. The Grafana dashboards, by default will only the discovered in the namespace Grafana is running by default.

IMHO we should make it so Grafana is able to discover dashboards in all namespaces. Note that I only mentioned `dashboards` and not `datasources`.

### Describe the solution you'd like.

The required change is minimal and can be achieved with a single line in the `values.yaml` of  `kube-prometheus-stack`.

Here's the PR: https://github.com/prometheus-community/helm-charts/pull/2927

### Describe alternatives you've considered.

For now, I'm overriding the same Grafana value in my own `values.yaml`.

**Comment by QuentinBisson** [comment]
Closed by https://github.com/prometheus-community/helm-charts/pull/2927
