### ISSUE TITLE
[kube-prometheus-stack] Alertmanager inconsistent in notifying on Slack

### ISSUE THREAD

**Issue by rylerin** [prometheus-community/helm-charts#2929]
### Describe the bug a clear and concise description of what the bug is.

I want to configure Alertmanager to send notifications to Slack. I am able to receive some Slack notifications intermittently, however the container logs show:
```
ts=2023-01-18T03:52:05.960Z caller=dispatch.go:354 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="slack-notifications/slack[0]: notify retry canceled after 13 attempts: Post \"<redacted>\": EOF"
ts=2023-01-18T03:52:05.987Z caller=notify.go:732 level=warn component=dispatcher receiver=slack-notifications integration=slack[0] msg="Notify attempt failed, will retry later" attempts=1 err="Post \"<redacted>\": EOF"
```
Which indicates that Alertmanager is not successful in sending all notifications to Slack.

### What's your helm version?

`version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}`

### What's your kubectl version?

`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}`

### Which chart?

`kube-prometheus-stack`

### What's the chart version?

`44.0.0`

### What happened?

After deploying `kube-prometheus-stack` helm chart in my EKS cluster and passing values to the helm chart to configure Alertmanager to send notifications to slack, the above error messages show up in the Alertmanager pod logs.

### What you expected to happen?

I expected there to not be any errors in the Alertmanager container logs, and to receive notifications on my slack channel consistently.

### How to reproduce it?

Deploy `kube-prometheus-stack` helm chart in an EKS environment and configure Alertmanager using the values.yaml overwrites below.

### Enter the changed values of values.yaml?

Use the terraform `templatefile(filename, {})` command on a file containing the following configuration:
```
${
  yamlencode({
    alertmanager: {

      "config": {
        "global": {
          "slack_api_url": "XXXXXXXXXX"
        }
        "route": {
          "receiver": "slack-notifications"
          "group_by": [
            "alertname",
            "severity"
          ]
          "group_wait": "30s" # default 30s
          "group_interval": "5m" # default 5m
          "repeat_interval": "10m" # default 12h
        }
        "receivers": [
          {
            "name": "slack-notifications"
            "slack_configs": [
              {
                "channel": "#app-monitoring"
                "text": "{{ template \"slack.default.text\" . }}"
              }
            ]
          },
          {
            "name": "null" # adds back 'null' receiver in the values.yaml defaults
          }
        ]
      }

      "templateFiles": {
        "default.tmpl": <<EOT
{{/* Default text format for Slack alerts */}}
{{ define "slack.default.text" -}}{{ range .Alerts }}
*Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
*Description:* {{ .Annotations.description }}
*Details:*
 • *alertname:* `{{ .Labels.alertname }}`
 • *environment:* `{{ .Labels.env }}`

{{- end }}{{- end }}

EOT
      }

      "alertmanagerSpec": {
        "image": {
          "tag": "v0.25.0"
        }
        "logLevel": "debug"
      }
    }
  })
}

```

### Enter the command that you execute and failing/misfunctioning.

`kubectl logs alertmanager-<release>-kube-prometheus-stack-alertmanager-0 -n <namespace>`

### Anything else we need to know?

I can receive some notifications from Alertmanager but on a very unpredictable basis. This is despite configuring the following:
```
          "group_wait": "30s" # default 30s
          "group_interval": "5m" # default 5m
          "repeat_interval": "10m" # default 12h
```
<img width="520" alt="Screenshot 2023-01-18 at 3 02 25 PM" src="https://user-images.githubusercontent.com/12382928/213105691-0b3f6172-da4d-4223-b063-d319291ab9ed.png">

**Comment by hashilbasheer** [comment]
I Have the similar issue with latest Prometheus and alert manager slack integration. with latest chart
