### ISSUE TITLE
[prometheus-operator-crds] default empty object annotations field causes differences between crd in chart and deployed crd

### ISSUE THREAD

**Issue by rouke-broersma** [prometheus-community/helm-charts#2932]
### Describe the bug a clear and concise description of what the bug is.

The annotations field is default set to an empty object, instead of being omitted. K8s ignores the field because it's an empty object (does not create the field, instead of setting to empty object), diff tools such such as argocd then see a difference between the desired state and the actual state, causing a sync-loop. It would be better if the value was nonexistent by default.

### What's your helm version?

v3.10.3+g835b733

### What's your kubectl version?

v0.24.2

### Which chart?

prometheus-operator-crds

### What's the chart version?

0.1.1

### Enter the command that you execute and failing/misfunctioning.

argocd calculates difference, sees a difference and decides a kubectl apply --server-side is neccesary. Couple seconds later it sees a difference once again and applies the same change.

**Comment by zeritti** [comment]
@rouke-broersma Please, see release 1.1.0, the issue should not occur any longer.
