### ISSUE TITLE
[kube-prometheus-stack] Can't use existing PVC

### ISSUE THREAD

**Issue by klubi** [prometheus-community/helm-charts#2933]
### Is your feature request related to a problem ?

I'm migrating "manual" prometheus + operator deployment to kube-prometheus-stack, and would like to re-use already existing PCV, where current deployment stores data.

### Describe the solution you'd like.

I'd like to have the ability to define existing PVC name to mount as volume to prometheus, instead of defining `volumeClaimTemplate`.

### Describe alternatives you've considered.

NONE

**Comment by UntouchedWagons** [comment]
I would like this too.

**Comment by jvergara-runbuggy** [comment]
can this be opened?

**Comment by nezlobnaya** [comment]
It should be reopened

**Comment by barthofu** [comment]
Yep, should be reopened

**Comment by joeypiccola** [comment]
fwiw:

1. I let the chart make the PVC.
2. I took note of the name and labels.
3. I then commented out `storageSpec` and redeployed the chart, removing the PVC (I manually deleted it though).
4. I then outside of the chart created the PVC using the previous name and labels.
5. I then uncommented `storageSpec` leaving it as shown below.
6. I then redeployed the chart.
7. the deployment attached to the PVC just fine. 

I suppose you could do this under `extraManifests: []` but I am unsure of the timing, the PVC needs to exist before helm tries to create it. In my case, my deployment process supports pre-creating PVCs from backups so it is not difficult to pre-create the PVC before workloads are deployed. 


```yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
```
