### ISSUE TITLE
Unable to install prometheus

### ISSUE THREAD

**Issue by benthomas40G** [prometheus-community/helm-charts#2934]
### Describe the bug a clear and concise description of what the bug is.

When i tried to install the prometheus with below command i got error

helm install prometheus prometheus-community/prometheus --namespace prometheus --set alertmanager.persistentVolume.storageClass="gp3-enc" --set server.persistentVolume.storageClass="gp3-enc"
Error: This command needs 1 argument: chart name

I tried below command, 
helm install prometheus-community/prometheus --namespace prometheus --set alertmanager.persistentVolume.storageClass="gp3-enc" --set server.persistentVolume.storageClass="gp3-enc"

i am trying to do the config using below
https://www.eksworkshop.com/intermediate/240_monitoring/deploy-prometheus/

this time i got different error
Error: parse error in "prometheus/charts/kube-state-metrics/templates/deployment.yaml": template: prometheus/charts/kube-state-metrics/templates/deployment.yaml:87: function "mustUniq" not defined

Please correct me if i am doing anything wrong 

### What's your helm version?

Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"} Server: &version.Version{SemVer:"v2.16.12", GitCommit:"47f0b88409e71fd9ca272abc7cd762a56a1c613e", GitTreeState:"clean"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-a05fdea", GitCommit:"a05fdea9a04815782f9c4b08eed73bb2d78b07e3", GitTreeState:"clean", BuildDate:"2022-06-09T21:50:47Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.23) and server (1.19) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus/charts/kube-state-metrics/templates/deployment.yaml

### What's the chart version?

1.3

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus --namespace prometheus --set alertmanager.persistentVolume.storageClass="gp3-enc" --set server.persistentVolume.storageClass="gp3-enc"

helm install prometheus-community/prometheus --namespace prometheus --set alertmanager.persistentVolume.storageClass="gp3-enc" --set server.persistentVolume.storageClass="gp3-enc"

**Comment by zeritti** [comment]
Shown above is Helm release 2.13.1. You must use Helm 3 as stated in [README](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#prerequisites).
