### ISSUE TITLE
[prometheus-kube-stack] Couldn't find way to set email notification properly

### ISSUE THREAD

**Issue by flenoir** [prometheus-community/helm-charts#294]
**Describe the bug**
Hi, 

It may be a dumb question but i try to set smtp and email settings in alertmanager config but couldn't find a simple way to do it. 

I'm using this helm chart through Terraform so i did all installation and everything is running. 

I have a alertmanager pod and i found a alertmanager.yaml file in /etc/alertmanager/config folder. Cannot edit it as it's read only. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
~> 1.0.0
```

Kubernetes Version:

```console
$ kubectl version
1.18.8
```

**Which chart**: prometheus-kube-stack
**Which version of the chart**: latest

**What happened**:

I couldn't find the way to edit alertmanager config file to add email notification. Should it be edited through alertmanager pod or through prometheus pod ?

**Comment by bismarck** [comment]
@flenoir Please see: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md

**Comment by mrueg** [comment]
If helm version returns 1.0.0, you should also upgrade your helm client.
