### ISSUE TITLE
[kube-prometheus-stack] Mutating webhook config denies rules using partial_response_strategy

### ISSUE THREAD

**Issue by aiyengar2** [prometheus-community/helm-charts#297]
**Describe the bug**
Can't add `partial_response_strategy` to a PrometheusRule when validation is enabled

**Version of Helm and Kubernetes**:

Helm Version: 3.3.3

```console
$ helm version
version.BuildInfo{Version:"v3.3.3-rancher3", GitCommit:"657df59bbba1d9e175cf5080d4885bd57d037906", GitTreeState:"clean", GoVersion:"go1.13.15"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack
**Which version of the chart**: 11.0.0

**What happened**:
When trying to add `partial_response_strategy` to any existing PrometheusRule CR, it is rejected with the following error from Prometheus Operator:

```
level=info ts=2020-11-03T01:35:38.709271395Z caller=admission.go:206 component=admissionwebhook msg="Invalid rule" err="yaml: unmarshal errors:\n line 1: field partial_response_strategy not found in type rulefmt.RuleGroup"
```

**What you expected to happen**:
Should have been accepted.

**How to reproduce it** (as minimally and precisely as possible):

Use default `values.yaml` and deploy the chart. Try to modify any PrometheusRule deployed with `spec.groups[i].partial_response_strategy` and it will fail

**Anything else we need to know**:

Could be related to https://github.com/thanos-io/thanos/issues/1096

**Comment by bismarck** [comment]
@aiyengar2 The admission webhook runs promtool under the cover.  `partial_response_strategy` is a Thanos specific extension, so you would need to write your own admission webhook.
