### ISSUE TITLE
[kube-prometheus-stack] Securing exposed endpoint with basic auth

### ISSUE THREAD

**Issue by nikolic-milan** [prometheus-community/helm-charts#2972]
Greetings,

I have kube-prometheus-stack deployed in a Kubernetes cluster, with Grafana disabled. I then have an external self-hosted Grafana, where I have all dashboards from all project including this one.  To add Prometheus as a data source, I've exposed it through an endpoint. This works fine, but now I have an unsecured endpoint. How do I enable basic authentication, or any other form of supported auth? 

I've tried doing it like this - https://github.com/prometheus-community/helm-charts/issues/1255#issuecomment-983635542 .
But does not work for kube-prometheus-stack. Also, I can't find “server”, "serverFiles", "probeHeaders" in the values.yaml for kube-prometheus-stack. 

How can I enable basic auth while using kube-prometheus-stack?

Also, what's the difference between the kube-prometheus-stack and prometheus charts? What additional fetures come with kube-prometheus-stack that are not present in prometheus?

Thanks,
Kind Regards

**Comment by zeritti** [comment]
> How can I enable basic auth while using kube-prometheus-stack?

Currently not supported by Prometheus operator. Basic authentication was briefly discussed in #2828 together with general web-config configuration ([Ref.](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.PrometheusWebSpec)) and elsewhere. What you might consider is TLS client authentication which the operator supports through the chart's value `prometheus.prometheusSpec.web.tlsConfig` ([Ref.](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.WebTLSConfig)). 

Other than that, deploying an auth proxy sidecar through `prometheus.prometheusSpec.containers` for basic authentication like nginx may be the way forward.
