### ISSUE TITLE
[prometheus] unable to use env variables in the helm chart

### ISSUE THREAD

**Issue by ivomarino** [prometheus-community/helm-charts#2996]
### Describe the bug a clear and concise description of what the bug is.

hi all, as described in https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L135-L150 I'm trying to use `env` variables in the prometheus pod, actually it doesn't seem to be set when the container runs, here are my settings:

```
  helm:
    values: |

      server:
        enabled: true

        env:
          - name: BA_USERNAME
            value: "foo"
```

verification:

```
kubectl exec -it prometheus-server-864cd86456-2q9h6 -nmonitoring sh

/ $ export 
export HOME='/home'
export HOSTNAME='prometheus-server-864cd86456-2q9h6'
export KUBERNETES_PORT='tcp://10.43.0.1:443'
...
export PROMETHEUS_SERVER_SERVICE_PORT_HTTP='80'
export PWD='/'
export SHLVL='1'
export TERM='xterm'
```

`BA_USERNAME` is not set at all. Any suggestions or am I doing something wrong? The helm chart actually should support this as mentioned here https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/templates/deploy.yaml#L100-L103 -- Thanks

### What's your helm version?

version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2+k3s1", GitCommit:"53c268d8eb90ceea5e1c7865f89db5c7fb8763bc", GitTreeState:"clean", BuildDate:"2022-09-28T16:30:25Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.22) and server (1.25) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus

### What's the chart version?

19.3.3

### Enter the command that you execute and failing/misfunctioning.

using ArgoCD

**Comment by ivomarino** [comment]
if I take a look at the deployment I can find the exported var:

```
kubectl describe deployments.apps -nmonitoring prometheus-server
Name:               prometheus-server
Namespace:          monitoring
CreationTimestamp:  Tue, 07 Feb 2023 11:59:16 +0100
Labels:             app=prometheus
                    argocd.argoproj.io/instance=prometheus
                    chart=prometheus-19.3.3
                    component=server
                    heritage=Helm
                    release=prometheus
Annotations:        deployment.kubernetes.io/revision: 1
Selector:           app=prometheus,component=server,release=prometheus
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           app=prometheus
                    chart=prometheus-19.3.3
                    component=server
                    heritage=Helm
                    release=prometheus
  Service Account:  prometheus-server
  Containers:
   prometheus-server-configmap-reload:
    Image:      jimmidyson/configmap-reload:v0.8.0
    Port:       <none>
    Host Port:  <none>
    Args:
      --volume-dir=/etc/config
      --webhook-url=http://127.0.0.1:9090/-/reload
    Environment:  <none>
    Mounts:
      /etc/config from config-volume (ro)
   prometheus-server:
    Image:      quay.io/prometheus/prometheus:v2.41.0
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --enable-feature=agent
      --storage.agent.retention.max-time=30m
      --config.file=/etc/config/prometheus.yml
    Liveness:   http-get http://:9090/-/healthy delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:  http-get http://:9090/-/ready delay=30s timeout=4s period=5s #success=1 #failure=3
    Environment:
      BA_USERNAME:  foo
```

`BA_USERNAME:  foo` is anyway not available inside the pod seems.

**Comment by ivomarino** [comment]
I can also see it when I describe the pod:

```
kubectl describe pod prometheus-server-864cd86456-2q9h6 -nmonitoring
Name:         prometheus-server-864cd86456-2q9h6
Namespace:    monitoring
Priority:     0
...
    Liveness:       http-get http://:9090/-/healthy delay=30s timeout=10s period=15s #success=1 #failure=3
    Readiness:      http-get http://:9090/-/ready delay=30s timeout=4s period=5s #success=1 #failure=3
    Environment:
      BA_USERNAME:  foo
```

can't see it in any case using `export` inside the pod.

**Comment by zeritti** [comment]
> kubectl exec -it prometheus-server-864cd86456-2q9h6 -nmonitoring sh

This looks like entering the first pod's container which is `prometheus-server-configmap-reload`. More reliable is using `-c` to select the desired container:
```
kubectl exec -it prometheus-server-864cd86456-2q9h6 \
  -c prometheus-server -nmonitoring -- sh
```

**Comment by reyerdam** [comment]
it depends what you try to do with the export.
if you for example want to use that also in an template you have to deal with envsubst .
