### ISSUE TITLE
Dependent charts of prometheus-operator?

### ISSUE THREAD

**Issue by sachinmsft** [prometheus-community/helm-charts#30]
I see that we are moving prometheus charts from stable to this repo. what about other charts that prometheus-operatror deploy like grafana, kube-state-metrics. ?

**Comment by sachinmsft** [comment]
@scottrigby

**Comment by scottrigby** [comment]
@sachinmsft This was asked in a long thread of collapsed comments on #14. Here was my reply: https://github.com/scottrigby/prometheus-helm-charts/pull/1#discussion_r474766376

Do you have any other thoughts about this?

**Comment by monotek** [comment]
I guess grafana will be moved to an official grafana helm repo anyway. Loki for example is already managed by the grafana guys. See: https://hub.helm.sh/charts/loki/loki

**Comment by scottrigby** [comment]
Re grafana I thought I replied to them last week but can't find the issue. So just made this comment: https://github.com/grafana/grafana/issues/18665#issuecomment-683425843

**Comment by scottrigby** [comment]
Also see https://github.com/helm/charts/pull/23662

**Comment by scottrigby** [comment]
Update: stable/grafana has officially deprecated and moved to a new repo 🙌 So we should update that dependency definition.

**Comment by gkarthiks** [comment]
@scottrigby should we change the dependency after the rename of prom-operator?

**Comment by scottrigby** [comment]
@gkarthiks yes as a fast follow of #1 if we can get that tested and reviewed one more time and merged soon. Otherwise I can update as part of that PR

**Comment by gkarthiks** [comment]
@scottrigby  No worries, I can update this soon after the #1 is done.

**Comment by scottrigby** [comment]
If you want you could make it sooner against the #1 PR branch instead of main

**Comment by gkarthiks** [comment]
@scottrigby is there anything else we have to do against this issue here?

**Comment by scottrigby** [comment]
I don't think so. We can follow up with kube-state-metrics here https://github.com/kubernetes/kube-state-metrics/issues/1153 but until then, nothing is needed. Thanks!
