### ISSUE TITLE
[kube-prometheus-stack] Make possible to set Grafana Helm chart K8s resources (i.e. requests/limits)

### ISSUE THREAD

**Issue by paoloyx** [prometheus-community/helm-charts#3005]
### Is your feature request related to a problem ?

I'd like to set Grafana Helm charts K8s resources (i.e. requests and limits). At the moment it seems not possible to do so, am I right?

### Describe the solution you'd like.

Use the relevant `grafana.resources` (etc. etc.) keys in `kube-prometheus-stack` chart values.file, under the `grafana` section

### Describe alternatives you've considered.

Imho there are no alternatives than the one of using already existent Grafana chart (that provides the "levers" to set resources)

### Additional context.

I can set-up a PR if already there is not one, the only thing that I'm missing is how must I backport the code to previous tags (i.e. we're using the `34.1.1` version of `kube-prometheus-stack` in some of our environments and, while we could upgrade, I'd like to know if there is a "proper" way to manage this situations)

**Comment by zeritti** [comment]
> I'd like to set Grafana Helm charts K8s resources (i.e. requests and limits). At the moment it seems not possible to do so, am I right?

No, that is not correct. As the Grafana chart is being used as a subchart, you can use any of the Grafana chart's supported values underneath the key `grafana`, including resources for the main container, init containers and sidecar containers. 

You can retrieve the values of the corresponding chart release (6.24.1 is set in  34.1.1), e.g.
```
helm show values grafana/grafana --version 6.24.1
```
assuming the Helm repository is configured, or view the values in the Grafana chart [repository](https://github.com/grafana/helm-charts/tree/main/charts/grafana) at the appropriate tag. [Artifacthub.io](https://artifacthub.io/) can also help with determining charts' values.

**Comment by paoloyx** [comment]
Ok @zeritti, thanks, it makes perfect sense
