### ISSUE TITLE
[prometheus] ServiceMonitor not used?

### ISSUE THREAD

**Issue by rufreakde** [prometheus-community/helm-charts#3010]
### Describe the bug a clear and concise description of what the bug is.

So I used the general Prometheus helm chart since I need a minimalistic installation.

Everything works fine so far it is also connected with my grafana instance but when I try to use Service Monitors it is not picking up any. So I looked into the configuration and also did not see any obvious values.yaml properties to configure it.

So then I saw in the readme:
https://github.com/prometheus-community/helm-charts/blob/22fb660debb1bb302c50957ce41fcf634924b7dc/charts/prometheus/README.md?plain=1#L207

That the scraping of prometheus is done via annotation. Is this the best practice or is this just the new (or maybe old) way of doing it?

```yaml
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.13.0
```
Best regards,
rufreakde

### What's your helm version?

ArgoCD Helm

### What's your kubectl version?

kubectl version --short Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. Client Version: v1.24.1 Kustomize Version: v4.5.4 Server Version: v1.24.1

### Which chart?

prometheus

### What's the chart version?

15.13.0

### What happened?

Service Monitor Ignored / annotation is used also in prometheus-node-exporter

### What you expected to happen?

Maybe I am just not informed but I thought all prometheus helm charts use the ServiceMonitor?

### How to reproduce it?

Install chart / deploy any servicemonitor with a service

### Enter the changed values of values.yaml?

serverFiles:
...
alertmanager:
...
alertmanagerFiles:
...

### Enter the command that you execute and failing/misfunctioning.

Helm installation works without issues

**Comment by monotek** [comment]
Servicemonitor is a custom resource definition of the prometheus operator, not prometheus.
So you're using the wrong chart.
Use https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack instead.

**Comment by rufreakde** [comment]
@monotek thanks for the clear answer! Is there some source somewhere what is proposed to be used to be on the "latest and gratest"? I could not find the "suggested" chart in the documentation but I would expect it to be kube-prometheus-stack?

**Comment by monotek** [comment]
yes, the one i linked.
