### ISSUE TITLE
[prometheus-kube-stack] alertmanger tplConfig does not allow complex templating 

### ISSUE THREAD

**Issue by TheKangaroo** [prometheus-community/helm-charts#302]
**Describe the bug**
We try to dynamically create alertmanager routes and receivers at prometheus-kube-stack deploy based on namespaces with a specific label on the namespaces and api key secret them.
The templating does not allow for complex config templating like range or if-else blocks.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-kube-stack

**Which version of the chart**:
11.0.0

**What happened**:
The chart allows to use helm templating in `Values.alertmanager.config` if you set `Values.alertmanager.tplConfig: true`.
We try to loop over namespaces and create a route and reciever for every namspace with a specific label (example for routes):
```
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ["namespace", "alertname"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: "teams"
        routes:
          {{- range $index, $ns := (lookup "v1" "Namespace" "" "").items }}
            {{- if and $ns.metadata.labels }}
            {{- if and $ns.metadata.labels.opsgenie_team }}
            {{- $secret := (lookup "v1" "Secret" $ns.metadata.name "opsgenie" ) }}
            {{- if and $secret $secret.data }}
            {{- if (hasKey $secret.data "api_key") }}
            - receiver: {{$ns.metadata.labels.opsgenie_team}}-{{$ns.metadata.name}}
              match:
                namespace: {{$ns.metadata.name}}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
```
This fails however, because it is not valid yaml and helm cannot load it properly. We defined the config as a multiline string as a workaround:
```
    config: |
      global:
        resolve_timeout: 5m
[...]
```
This works for helm deployment but leaves us with an invalid alertmanager configuration like:
```
|
  global:
    resolve_timeout: 5m
[...]
```
We made it work with the following change in the alertmanager secret template:
```
 {{- if .Values.alertmanager.tplConfig }}
-  alertmanager.yaml: {{ tpl (toYaml .Values.alertmanager.config) . | b64enc | quote }}
+  alertmanager.yaml: {{ tpl .Values.alertmanager.config . | b64enc | quote }}
 {{- else }}
```

Is there any way to make it work without the template change?
And if not, is it possible to change the template upstream? I am a bit concerned, that just removing the `toYaml` could possibly break different deployments.
 
**What you expected to happen**:
Being able to render complex templates for alertmanager config.

**How to reproduce it** (as minimally and precisely as possible):
See example "What happend" or:
```
alertmanager:
  config: |
    {{- range $index, $ns := (lookup "v1" "Namespace" "" "").items }}
    namespace: {{$ns.metadata.name}}
    {{- end }}
  tplConfig: true
```
```
helm install my-release prometheus-community/prometheus-kube-stack --values values.yaml
```

**Comment by mmack** [comment]
Same here. /reopen pls

**Comment by monotek** [comment]
To get this solved you might want to create a pr? :)

**Comment by TheKangaroo** [comment]
@monotek, I didn't provide a PR since I wasn't sure if just removing the `toYaml` function call would break other intended use cases.
This issue was meant to be more of a question if someone more familiar with the codebase can say something about the implications this change would have.

Anyways, I learned about  AlertmanagerConfig CRD in the meantime which will solve our use case and this issue in a much more elegant way.
Thank you for your hint anyways @monotek :)
