### ISSUE TITLE
kube-prometheus-stack Support for relabeling in additionalServiceMonitors

### ISSUE THREAD

**Issue by causalbody** [prometheus-community/helm-charts#3041]
### Is your feature request related to a problem ?

I think there is no means to add a new labels to metrics scraped through custom service monitors. The custom service monitors could be scrapping a microservice endpoint (/actuator/prometheus) and the chart doesn't have an option to supply relabelling like in https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/servicemonitor.yaml#L41

The custom monitors added through _additionalServiceMonitors_ end up using https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml which doesn't have relabelling

### Describe the solution you'd like.

Support relabelings for _additionalServiceMonitors_ config

### Describe alternatives you've considered.

One possible workaround is to have those labels come through application itself.

**Comment by zeritti** [comment]
> The custom monitors added through additionalServiceMonitors end up using https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/servicemonitors.yaml which doesn't have relabelling

The thing is that through `additionServiceMonitors[]` one can set most of the top level service monitor fields including `endpoints` "as is" contents of which are then entirely under the user's control. As relabelings are defined as `endpoints[].relabelings`, custom relabelings can thus be set for each additional service monitor in the values file (ref. [Endpoint](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.Endpoint)).

**Comment by causalbody** [comment]
Thank you for this detail. Please feel free to mark this issue closed or I
shall try to do it myself a bit later.
