### ISSUE TITLE
[kube-state-metrics] Deployment orphaned after move to `autosharding`

### ISSUE THREAD

**Issue by mbrancato** [prometheus-community/helm-charts#3042]
### Describe the bug a clear and concise description of what the bug is.

After moving from `autosharding.enabled: false` to `true` with replicas > 1, the old deployment  for KSM is not deleted.

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.15-gke.2500", GitCommit:"fbf2f97a417bed01195ce67ab3c222d68f06f8b7", GitTreeState:"clean", BuildDate:"2022-10-26T09:24:45Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-state-metrics

### What's the chart version?

45.1.1

### What happened?

The old `Deployment` resource is not removed.

### Enter the command that you execute and failing/misfunctioning.

helm upgrade

**Comment by pedrohro1992** [comment]
try to pass the --atomic parameter when running the helm upgrade command may help
