### ISSUE TITLE
[kube-prometheus-stack] Scraping of kube-state-metrics broken after update v45.2.0 

### ISSUE THREAD

**Issue by ldunkum** [prometheus-community/helm-charts#3050]
### Describe the bug a clear and concise description of what the bug is.

We updated to the Chart version v45.2.0 earlier today and since the kube-state-metrics Endpoint is in state `down`  with the following error kube-state-metrics: `proto: wrong wireType = 0 for field Metric`.  

As v45.2.0 introduces kube-state-metrics v2.8.0 (app version), on the first glance it seems like the bug might be related to the feature introduced in https://github.com/kubernetes/kube-state-metrics/pull/1974.  

After reverting the update, kube-state-metrics metrics are accessible again. 

### What's your helm version?

v3.11.0

### What's your kubectl version?

v1.26.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

v45.2.0

### Enter the command that you execute and failing/misfunctioning.

-

**Comment by ben5556** [comment]
@ldunkum I think I hit this issue too. I don't see `kube_pod*` and other related metrics in Prometheus UI. What version did you revert to, to fix the issue ? Thanks

**Comment by ldunkum** [comment]
@ben5556 We reverted to v45.1.1, if you need any more confirmation, you can check Status → Targets and filter by unhealthy in the Prometheus UI.
