### ISSUE TITLE
[prometheus-kube-stack] storage for prometheus and alertmanager is not respected

### ISSUE THREAD

**Issue by omerfsen** [prometheus-community/helm-charts#3056]
### Describe the bug a clear and concise description of what the bug is.

I am using an expandable PVC on AWS (aws-ebs-cni )

```hcl
resource "kubernetes_storage_class" "ebs_sc" {
  metadata {
    name = "ebs-sc"
  }
  storage_provisioner = "ebs.csi.aws.com"
  parameters = {
    "csi.storage.k8s.io/fstype" = "xfs"
    encrypted                   = "true"
    type                        = "gp3"
  }
  allow_volume_expansion = true
}
``` 

and using this on kube-prometheus-stack. Volume resize (expansion) is respected on grafana but not on  prometheus nor alertmanager 

```yaml
-  alertmanagerSpec:
-  ⦙ storage:
-  ⦙ ⦙ volumeClaimTemplate:
-  ⦙ ⦙ ⦙ spec:
5  ⦙ ⦙ ⦙ ⦙ storageClassName: ebs-sc
5  ⦙ ⦙ ⦙ ⦙ accessModes: ["ReadWriteOnce"]
-  ⦙ ⦙ ⦙ ⦙ resources:
-  ⦙ ⦙ ⦙ ⦙ ⦙ requests:
7  ⦙ ⦙ ⦙ ⦙ ⦙ ⦙ storage: 11Gi
```

```yaml
-  prometheusSpec:
2  ⦙ enableRemoteWriteReceiver: true
-  ⦙ enableFeatures:
3  ⦙ ⦙ - remote-write-receiver
-  ⦙ nodeSelector:
3  ⦙ ⦙ kubernetes.io/os: linux
-  ⦙ storageSpec:
-  ⦙ ⦙ volumeClaimTemplate:
-  ⦙ ⦙ ⦙ spec:
5  ⦙ ⦙ ⦙ ⦙ storageClassName: ebs-sc
5  ⦙ ⦙ ⦙ ⦙ accessModes: ["ReadWriteOnce"]
-  ⦙ ⦙ ⦙ ⦙ resources:
-  ⦙ ⦙ ⦙ ⦙ ⦙ requests:
7  ⦙ ⦙ ⦙ ⦙ ⦙ ⦙ storage: 110Gi
```

both not working (resizing) but following works (was 100Gi before and after applying changes it is resized to 120Gi)

```yaml
-grafana:
-  persistence:
2  ⦙ enabled: true
2  ⦙ size: 120Gi
2  ⦙ storageClassName: ebs-sc
```

```bash
NAME                                                                                                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
alertmanager-prometheus-kube-prometheus-alertmanager-db-alertmanager-prometheus-kube-prometheus-alertmanager-0   Bound    pvc-6ba6c6dd-bde7-4dda-ac23-9b7e36ca5d8c   10Gi       RWO            ebs-sc         6d10h
prometheus-grafana                                                                                               Bound    pvc-4c17837c-368b-4c4b-a5f5-c0d2933e64af   120Gi      RWO            ebs-sc         6d10h
prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0           Bound    pvc-f7a926fa-fd10-4f0c-8cf2-38185aa2b960   100Gi      RWO            ebs-sc         6d10h
```

### What's your helm version?

version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.2.0

### What happened?

Only grafana PVC is expanded.

### What you expected to happen?

I want grafana,prometheus and alertmanager persistent pvc to be expanded not only grafana

### How to reproduce it?

Install helm chart, resize disk and apply see pvc sizes are expanding for all 3

### Enter the changed values of values.yaml?

size: 120Gi

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -i stack  prometheus-community/kube-prometheus-stack -f values.yaml

**Comment by eimarfandino** [comment]
are there any solutions for this? We are losing time after time the silences in alertmanager due to the lack of persistence

**Comment by eimarfandino** [comment]
update: i updated to the latest version of the chart and is all working fine, this can be closed
