### ISSUE TITLE
add the compatibility matrix for Kubernetes versions to README

### ISSUE THREAD

**Issue by hari-vamsikrishna** [prometheus-community/helm-charts#3057]
### Is your feature request related to a problem ?

We are planning EKS upgrade from 1.22 to 1.23. We have right now installed the 43.1.2 version of kube-prometheus-stack helm chart. It would be great if the compatibility matrix is added like the one from (https://github.com/prometheus-operator/kube-prometheus/tree/v0.11.0#compatibility)

### Describe the solution you'd like.

compatibility matrix with Kubernetes version is added like the one from (https://github.com/prometheus-operator/kube-prometheus/tree/v0.11.0#compatibility)

### Describe alternatives you've considered.

Alternative to above would be to add the relationship of the kube-prometheus-stack versions/releases with the kube-prometheus releases,
https://github.com/prometheus-operator/kube-prometheus/releases?page=1

**Comment by aolmosj** [comment]
There's plenty of issues caused by app / k8s versions. So I think this matrix could be of great help...

**Comment by Dingoldine** [comment]
commenting in support of this, and also to point out that [ingress-nginx](https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table) is a great example

**Comment by peterreji** [comment]
is this released? unable to find the compatibility matrix. i was planning to upgrade my EKS cluster from 1.26 to 1.27, currently using kube-prometheus-stack helm chart version 46.4.2. wanted to know if there will be any breaking changes
