### ISSUE TITLE
[kube-prometheus-stack] "failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory"

### ISSUE THREAD

**Issue by SrinivReddy** [prometheus-community/helm-charts#3062]
### Describe the bug a clear and concise description of what the bug is.

I am trying to configure a promethues stack with Thanos but I am getting below error, any one have idea on this error.

```
level=info ts=2023-02-23T13:10:05.015644651Z caller=options.go:27 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-02-23T13:10:05.016367002Z caller=factory.go:50 msg="loading bucket configuration"
level=info ts=2023-02-23T13:10:05.016702782Z caller=sidecar.go:360 msg="starting sidecar"
level=info ts=2023-02-23T13:10:05.016874781Z caller=reloader.go:200 component=reloader msg="nothing to be watched"
level=info ts=2023-02-23T13:10:05.017041144Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-02-23T13:10:05.017101976Z caller=http.go:73 service=http/server component=sidecar msg="listening for requests and metrics" address=:10902
level=info ts=2023-02-23T13:10:05.018281393Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-02-23T13:10:05.018501014Z caller=tls_config.go:195 service=http/server component=sidecar msg="TLS is disabled." http2=false
level=info ts=2023-02-23T13:10:05.018680618Z caller=grpc.go:131 service=gRPC/server component=sidecar msg="listening for serving gRPC" address=:10901
level=info ts=2023-02-23T13:10:05.02230405Z caller=sidecar.go:179 msg="successfully loaded prometheus version"
level=info ts=2023-02-23T13:10:05.051227161Z caller=sidecar.go:201 msg="successfully loaded prometheus external labels" external_labels="{prometheus=\"monitoring/prom-kube-stack-kube-prome-prometheus\", prometheus_replica=\"prometheus-prom-kube-stack-kube-prome-prometheus-0\"}"
level=warn ts=2023-02-23T13:10:07.019060267Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory"
```

### What's your helm version?

v3.8.2

### What's your kubectl version?

Major:"1", Minor:"21", GitVersion:"v1.21.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-45.2.0

### Enter the changed values of values.yaml?

values.yaml file is

```
prometheus:
  prometheusSpec:
    replicas: 2      
    retention: 12h  
    thanos:         
      objectStorageConfig: 
        key: thanos.yaml
        name: thanos-objstore-config
```

### Enter the command that you execute and failing/misfunctioning.

helm install --namespace monitoring prom-kube-stack kube-prometheus-stack -f prom_values.yaml --repo https://prometheus-community.github.io/helm-charts/

**Comment by ebini** [comment]
Hi, 
i had also this issue (repeating error).
I had a wrong object store configuration. (in my case thanos was not authorized / wrong credentials)
After fixing this, the message only appears once.
the file is then created by thanos (perhaps)? 
not sure if this helps.

**Comment by leepereira** [comment]
I am running into this same issue with the config and the thanos side car is showing up the following errors
`level=info ts=2023-03-07T05:58:48.003965285Z caller=options.go:26 protocol=gRPC msg="disabled TLS, key and cert must be set to enable"
level=info ts=2023-03-07T05:58:48.004666893Z caller=factory.go:52 msg="loading bucket configuration"
level=info ts=2023-03-07T05:58:48.064437504Z caller=sidecar.go:363 msg="starting sidecar"
level=info ts=2023-03-07T05:58:48.064537305Z caller=intrumentation.go:75 msg="changing probe status" status=healthy
level=info ts=2023-03-07T05:58:48.064588005Z caller=http.go:73 service=http/server component=sidecar msg="listening for requests and metrics" address=:10902
level=info ts=2023-03-07T05:58:48.064811808Z caller=tls_config.go:232 service=http/server component=sidecar msg="Listening on" address=[::]:10902
level=info ts=2023-03-07T05:58:48.064836008Z caller=tls_config.go:235 service=http/server component=sidecar msg="TLS is disabled." http2=false address=[::]:10902
level=info ts=2023-03-07T05:58:48.064927209Z caller=reloader.go:199 component=reloader msg="nothing to be watched"
level=info ts=2023-03-07T05:58:48.06496391Z caller=intrumentation.go:56 msg="changing probe status" status=ready
level=info ts=2023-03-07T05:58:48.06499211Z caller=grpc.go:131 service=gRPC/server component=sidecar msg="listening for serving gRPC" address=:10901
level=info ts=2023-03-07T05:58:48.08773018Z caller=sidecar.go:179 msg="successfully loaded prometheus version"
level=info ts=2023-03-07T05:58:48.101936249Z caller=sidecar.go:201 msg="successfully loaded prometheus external labels" external_labels="{prometheus=\"prom/prometheus-kube-prometheus-prometheus\", prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\"}"
level=warn ts=2023-03-07T05:58:50.066407089Z caller=shipper.go:239 msg="reading meta file failed, will override it" err="failed to read /prometheus/thanos.shipper.json: open /prometheus/thanos.shipper.json: no such file or directory"`

I am using azure blob storage for thanos configuration

**Comment by rajat-tomar** [comment]
@SrinivReddy were you able to resolve the issue? If yes, how?

**Comment by bacek** [comment]
I have same error. Is there actual solution for it?

**Comment by Mihail-blip** [comment]
I think this is a warning message that appears only when thanos shiper runs the first time. It will be created once it uploads file to object storage. 
On the next restart the warning message dissapears
