### ISSUE TITLE
[prometheus-kube-stack] Helm-upgrade fails due to :  Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com

### ISSUE THREAD

**Issue by avivlev98** [prometheus-community/helm-charts#3074]
### Describe the bug a clear and concise description of what the bug is.

When I try to helm-upgrade the prometheus-kube-stack chart after it installed once in the cluster, it failes due to error : Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com" . 

### What's your helm version?

version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}

### What's your kubectl version?

v1.22.10

### Which chart?

prometheus-kube-stack

### What's the chart version?

36.6.1

### What happened?

When I try to helm-upgrade the prometheus-kube-stack chart after it installed once in the cluster, it failes due to error : Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com" . 

Error: UPGRADE FAILED: cannot patch "kube-prometheus-stack-company.blackbox.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/mutate?timeout=10s)": dial tcp prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/mutate?timeout=10s)": context deadline exceeded && cannot patch "kube-prometheus-stack-prometheus.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/mutate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/mutate?timeout=10s)": context deadline exceeded && cannot patch "prometheus-kube-prometheus-alertmanager.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded && cannot patch "prometheus-kube-prometheus-config-reloaders" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded && cannot patch "prometheus-kube-prometheus-etcd" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded && cannot patch "prometheus-kube-prometheus-general.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "[https://prometheus-kube-prometheus-operator.monitoring.svc:443/admission-prometheusrules/validate?timeout=10s](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/validate?timeout=10s)": context deadline exceeded && cannot patch "prometheus-kube-prometheus-k8s.rules" with kind PrometheusRule: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": Post "[https://prometheus-kube-prometheus-](https://prometheus-kube-prometheus-operator.monitoring.svc/admission-prometheusrules/validate?timeout=10s)

### What you expected to happen?

Upgrade successfully the chart

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-stack/ -f manual-values.yaml 

### Anything else we need to know?

I know there is a solution to delete manually the two files before upgrade the chart : 

kubectl get validatingwebhookconfiguration -A
kubectl delete validatingwebhookconfiguration/kube-prometheus-stack-admission -A
kubectl get mutatingwebhookconfiguration -A
kubectl delete mutatingwebhookconfiguration/kube-prometheus-stack-admission -A

We deploy this chart as part of automatic cluster creation and I wanted to know if there is another solution that is not the deletion of these components manually .

**Comment by halradaideh** [comment]
this drove me crazy

it seems that the webhook admission is not waiting for the pods to be available causing the helm deployment to fail
and even with a second retry, it will pass but will start facing x509 certificates issues

**Comment by halradaideh** [comment]
this is the error I am getting, btw it is a **fresh installation on a fresh GKE cluster**
```
helm upgrade -i --create-namespace prometheus-operator -n prometheus-operator prometheus-community/kube-prometheus-stack -f values-prom.yaml
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://prometheus-operator-kube-m-operator.prometheus-operator.svc:443/admission-prometheusrules/mutate?timeout=30s": no endpoints available for service "prometheus-operator-kube-m-operator"```

**Comment by zeritti** [comment]
The internal server error on context deadline exceeded or no endpoints available  point to the API server not being able to communicate with the webhook. I noticed them at install time only as a fresh operator had just been started and a service endpoint was being created.

What you can do is set webhooks' `failurePolicy` to *Ignore* or keep it empty at install time whilst keeping the patch job enabled. The installation then succeeds. It must succeed so that the patch-job (post-install hook) can run and populate `CAbundle` field in the webhook configurations (assuming cert-manager is not being used). It is the missing field's value that is then responsible for x509-related errors coming from the API server at upgrade time - the issuer CA is untrusted. 

If the initial install fails, a corrective upgrade with `failurePolicy` as above should complete the installation. Once successful, `failurePolicy` can be set to *Fail*. A PR on introducing failure policy *IgnoreOnInstallOnly* is currently open.

**Comment by avivlev98** [comment]
> The internal server error on context deadline exceeded or no endpoints available point to the API server not being able to communicate with the webhook. I noticed them at install time only as a fresh operator had just been started and a service endpoint was being created.
> 
> What you can do is set webhooks' `failurePolicy` to _Ignore_ or keep it empty at install time whilst keeping the patch job enabled. The installation then succeeds. It must succeed so that the patch-job (post-install hook) can run and populate `CAbundle` field in the webhook configurations (assuming cert-manager is not being used). It is the missing field's value that is then responsible for x509-related errors coming from the API server at upgrade time - the issuer CA is untrusted.
> 
> If the initial install fails, a corrective upgrade with `failurePolicy` as above should complete the installation. Once successful, `failurePolicy` can be set to _Fail_. A PR on introducing failure policy _IgnoreOnInstallOnly_ is currently open.



> Adding to @zeritti 's answer, the way you set the webhooks failurepolicy in the helm chart values file is the following:
> 
> ```
> prometheusOperator:
>   admissionWebhooks:
>     failurePolicy: Ignore
> ```
> 
> or from the command line:
> 
> ```
> --set prometheusOperator.admissionWebhooks.failurePolicy=Ignore
> ```

Thank you very much i added that value failurePolicy: Ignore , and now it seems to upgrade the chart without failing .
