### ISSUE TITLE
helm template generates, wrong image when global.imageregistry is set

### ISSUE THREAD

**Issue by btwseeu78** [prometheus-community/helm-charts#3084]
https://github.com/prometheus-community/helm-charts/blob/4c2cca2750499044801d82ce65bbe487d3c3f464/charts/kube-state-metrics/templates/deployment.yaml#L125

**Comment by michbeck100** [comment]
same here

**Comment by michbeck100** [comment]
duplicate of https://github.com/prometheus-community/helm-charts/issues/3075
