### ISSUE TITLE
[prometheus-blackbox-exporter] PodSecurityPolicy removed in 1.25

### ISSUE THREAD

**Issue by nbjohnson** [prometheus-community/helm-charts#3092]
### Describe the bug a clear and concise description of what the bug is.

In kubernetes 1.25 PodSecurityPolicy will be removed. blackbox-exporter still has a PSP defined if the API has the beta version still available. The main prometheus chart has disabled all PSPs by default. Will blackbox-exporter continue to work fine without the PSP in 1.25? Or is there some change that is needed for blackbox-exporter to function properly on 1.25 with no PSP? Other exporters also seem to configured in the same way.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/templates/podsecuritypolicy.yaml#L1

### What's your helm version?

3.11.1

### What's your kubectl version?

1.25.5

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

PodSecurityPolicy removed from kubernetes 1.25

**Comment by tico24** [comment]
Seeming as this was raised speculatively, I installed the chart onto a k3d local environment and it worked fine. While I agree that the PSP should be removed from the chart, it shouldn't be a blocker to upgrading:

![image](https://user-images.githubusercontent.com/45351296/223692300-7d197ec0-33d2-4cb8-95d1-0a474d3982a1.png)

![image](https://user-images.githubusercontent.com/45351296/223692486-95ed726a-d98d-4a09-957a-5b21cb2dc387.png)

**Comment by tico24** [comment]
I disagree that this is completed. The thing should be removed.

**Comment by ShaneGCareCru** [comment]
Installing with argocd is blocked by this. Request this be reopened.

**Comment by sastorsl** [comment]
Upgrading to `8.3.x` (from 7.2.x`) with flux (fluxcd.io) fails at least.

```
prometheus-blackbox-exporter   632d   False   Helm upgrade failed: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "prometheus-blackbox-exporter-psp" namespace: "devops" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"...
```

**Comment by druskus20** [comment]
There is an option `pspEnabled` in the prometheus-blackbox-exporter chart. For me, setting that option to `false`, then re-deploying removed the PSP from the cluster.
