### ISSUE TITLE
[kube-prometheus-stack] AlertManagerConfig CRD Doesn't Have Definition for WebEx

### ISSUE THREAD

**Issue by StuxxNet** [prometheus-community/helm-charts#3106]
### Is your feature request related to a problem ?

In the alertmanagerconfig crd there's no option to configure webex as an alerting channel. This is available since alertmanager version 0.25.0.

### Describe the solution you'd like.

Add WebEx as a channel option as we have WeChat, for example

### Describe alternatives you've considered.

Try to add the configuration manually to see if the container get's the configuration anyway.

**Comment by spender0** [comment]
+

**Comment by jswager-cisco** [comment]
I can confirm; Alert Manager 0.25.0 has this feature, but the CRD does not allow for the definition.
