### ISSUE TITLE
[kube-prometheus-stack ] Add explicit version variable for prometheus entity generation

### ISSUE THREAD

**Issue by aarozhkov** [prometheus-community/helm-charts#3108]
### Is your feature request related to a problem ?

I try to use kube-prometheus-stack with "Google managed prometheus" service. GMP  use custom prometheus implementation with "custom" image tag([self-managed collections](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged))

Ex: `gke.gcr.io/prometheus-engine/prometheus:v2.35.0-gmp.2-gke.0`

This tag fails semver checks in prometheus-operator.
`caller=promcfg.go:166 component=prometheusoperator msg="ignoring \"enable_http2\" not supported by Prometheus" version=v2.35.0-gmp.4-gke.0 minimum_version=2.35.0"`

As workaround i can use .spec.version in CRD prometheuses.monitoring.coreos.com to set exact version.

But kube-prometheus-stack does not give opportunity to set custom version value.

### Describe the solution you'd like.

Add ability to customize version. Save default behavior with image tag usage as version.

Something like that:
```diff
diff --git a/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml b/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
index 310a473e..f4a9db22 100644
--- a/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
+++ b/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
@@ -42,7 +42,7 @@ spec:
   {{- else }}
   image: "{{ $registry }}/{{ .Values.prometheus.prometheusSpec.image.repository }}"
   {{- end }}
-  version: {{ .Values.prometheus.prometheusSpec.image.tag }}
+  version: {{ .Values.prometheus.prometheusSpec.version | default .Values.prometheus.prometheusSpec.image.tag }}
   {{- if .Values.prometheus.prometheusSpec.image.sha }}
   sha: {{ .Values.prometheus.prometheusSpec.image.sha }}
   {{- end }}
diff --git a/charts/kube-prometheus-stack/values.yaml b/charts/kube-prometheus-stack/values.yaml
index 0dbe5902..d1765437 100644
--- a/charts/kube-prometheus-stack/values.yaml
+++ b/charts/kube-prometheus-stack/values.yaml
@@ -2673,6 +2673,9 @@ prometheus:
       tag: v2.42.0
       sha: ""
 
+    # Explicitly set version for prometheus spec
+    # version: v2.42.0
+
     ## Tolerations for use with node taints
     ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
     ##

```

### Describe alternatives you've considered.

NONE

**Comment by aniekgul** [comment]
Facing the same issue trying to integrate with managed Prometheus on GKE, using the proposed fix in https://github.com/prometheus-community/helm-charts/pull/3112 seems to work
