### ISSUE TITLE
index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil

### ISSUE THREAD

**Issue by agvsap1** [prometheus-community/helm-charts#3111]
### Describe the bug a clear and concise description of what the bug is.

Hi 

I am installing prometheus with this command:

pushgateway.enabled=false -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
  --namespace prometheus --create-namespace \
  --set pushgateway.enabled=false \
  --set alertmanager.enabled=false

but the system reports this message error

Error: template: prometheus/templates/NOTES.txt:85:46: executing "prometheus/templates/NOTES.txt" at <index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil

I have seen that this chart was modified 3 months ago.

Regards.

### What's your helm version?

version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.9-dispatcher-dirty", GitCommit:"2c922a0aeb84a19590ed91f00449636b87bb507a", GitTreeState:"dirty", BuildDate:"2023-01-11T06:26:10Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8-gke.2000", GitCommit:"63bd400145c58fe450325af1d249c3072fed68ef", GitTreeState:"clean", BuildDate:"2022-12-07T09:33:04Z", GoVersion:"go1.18.8b7", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

https://prometheus-community.github.io/helm-charts

### What's the chart version?

https://prometheus-community.github.io/helm-charts

### What happened?

Hi 

I am installing prometheus with this command:

pushgateway.enabled=false -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
  --namespace prometheus --create-namespace \
  --set pushgateway.enabled=false \
  --set alertmanager.enabled=false

but the system reports this message error

Error: template: prometheus/templates/NOTES.txt:85:46: executing "prometheus/templates/NOTES.txt" at <index .Subcharts "prometheus-pushgateway">: error calling index: index of untyped nil

I have seen that this chart was modified 3 months ago.

Regards.

### What you expected to happen?

prometheus installation

### How to reproduce it?

prometheus installation

### Enter the command that you execute and failing/misfunctioning.

helm install my-prometheus --repo https://prometheus-community.github.io/helm-charts prometheus --namespace prometheus --create-namespace --set pushgateway.enabled=false -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
  --namespace prometheus --create-namespace \
  --set pushgateway.enabled=false \
  --set alertmanager.enabled=false \
  -f https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml

**Comment by zeritti** [comment]
I reckon upgrading helm to 3.7+ will fix that.
