### ISSUE TITLE
[kube-prometheus-stack] Missing `tsdb.outOfOrderTimeWindow` on Prometheus Spec

### ISSUE THREAD

**Issue by carlosrmendes** [prometheus-community/helm-charts#3124]
### Is your feature request related to a problem ?

Yes, I want to set the `.storage.tsdb.out_of_order_time_window` config on the Prometheus Server. 

### Describe the solution you'd like.

Prometheus Operator already supports that TSDB config on the PromtheusSpec: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.TSDBSpec

### Describe alternatives you've considered.

There's no alternative to achive this using this chart.

**Comment by zeritti** [comment]
#2960 merged in 45.8.0
