### ISSUE TITLE
[prometheus] unknown long flag '--volume-dir'

### ISSUE THREAD

**Issue by jmpalomar** [prometheus-community/helm-charts#3140]
### Describe the bug a clear and concise description of what the bug is.

When starting prometheus-config-reloader it fails due unknown flag `--volume-dir`

### What's your helm version?

3.11.2

### What's your kubectl version?

1.24.4

### Which chart?

prometheus

### What's the chart version?

20.0.0

### What happened?

After upgrading chart to version 2.0.0 prometheus-server fails due prometheus-config-reloader fails because unknown flag `--volume-dir`

### What you expected to happen?

prometheus-server started properly

### How to reproduce it?

Simply deploy new chart with config-reload enabled

### Enter the command that you execute and failing/misfunctioning.

helm upgrade prometheus prometheus-community/prometheus --install

### Anything else we need to know?

Seems args from template for config-reload are not compatible with prometheus-config-reloader

**Comment by zeritti** [comment]
Got fixed in 20.0.1 through #3141.
