### ISSUE TITLE
[kube-prometheus-stack] Metrics of Persistent volume does not exist

### ISSUE THREAD

**Issue by jdalia001** [prometheus-community/helm-charts#3144]
### Describe the bug a clear and concise description of what the bug is.

Hello,

I setup the prometheus kube-stack, everything is working except for persistent volume.
In my grafana dashboard, all metrics related to persistent volume does not exist in my prometheus (For exemple : kubelet_volume_stats_used_bytes).

Do you know if we have to add something in particular to get it ?

Regards,

### What's your helm version?

3.11.1

### What's your kubectl version?

1.26.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.7.1

### Enter the command that you execute and failing/misfunctioning.

No command is failing

**Comment by zeritti** [comment]
Availability of the `kubelet_volume_stats_*` metrics depends on the persistent volume plugin's/type's support for node capability GET_VOLUME_STATS implemented with the `NodeGetVolumeStats` RPC call. Some support it, others do not.
