### ISSUE TITLE
Alertmanager and Prometheus statefulsets in terminating mode on AKS 1.24.9 version

### ISSUE THREAD

**Issue by fromario007** [prometheus-community/helm-charts#3148]
### Describe the bug a clear and concise description of what the bug is.

Hello
I attempted to deploy a kube-prometheus-stack on an AKS cluster version 1.24.9. However, I encountered an issue where the pods for Alertmanager and Prometheus, which are part of a statefulset, were not successfully deployed. Upon creation, these pods immediately transitioned into a terminating state
NAME READY STATUS RESTARTS AGE
alertmanager-release-monitoring-kube-pro-alertmanager-0 0/2 Pending 0 0s
release-monitoring-grafana-5fb4c98d88-r2j99 3/3 Running 0 19m
release-monitoring-kube-pro-operator-7647b95df6-2dndd 1/1 Running 0 19m
release-monitoring-kube-state-metrics-7c484759cd-qwmwg 1/1 Running 0 19m
release-monitoring-prometheus-node-exporter-6gvs9 1/1 Running 0 19m
release-monitoring-prometheus-node-exporter-p87h4 1/1 Running 0 19m
release-monitoring-prometheus-node-exporter-rgjnv 1/1 Running 0 19m
release-monitoring-prometheus-node-exporter-sq69v 1/1 Running 0 19m
prometheus-release-monitoring-kube-pro-prometheus-0 0/2 Terminating 0 3s

The logs I am able to get:
kubectl logs alertmanager-release-monitoring-kube-pro-alertmanager-0 -f
ts=2023-03-22T16:14:39.902Z caller=main.go:240 level=info msg="Starting Alertmanager" version="(version=0.25.0, branch=HEAD, revision=258fab7cdd551f2cf251ed0348f0ad7289aee789)"
ts=2023-03-22T16:14:39.902Z caller=main.go:241 level=info build_context="(go=go1.19.4, user=root@abe8654564717, date=20221222-14:51:36)"
ts=2023-03-22T16:14:39.966Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-03-22T16:14:39.966Z caller=coordinator.go:118 level=error component=configuration msg="Loading configuration file failed" file=/etc/alertmanager/config_out/alertmanager.env.yaml err="open /etc/alertmanager/config_out/alertmanager.env.yaml: no such file or directory"
 I tried to deploy an older version of the chart 40.0.0 but same result with statefulset.
On an AKS that has version 1.23.8 I did not had any issue deploying the Helm chart.
Is there anything I need to take in consideration when I deploying this helm chart on this new AKS version?

### What's your helm version?

v3.8.2

### What's your kubectl version?

v1.26.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.7.1

### What happened?

I attempted to deploy a kube-prometheus-stack on an AKS cluster version 1.24.9. However, I encountered an issue where the pods for Alertmanager and Prometheus, which are part of a statefulset, were not successfully deployed. Upon creation, these pods immediately transitioned into a terminating state

### What you expected to happen?

Prometheus and Alertmanager statefulset to produce 2 running pods

### How to reproduce it?

install chart on a AKS that has versio 1.24.9
helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack

### Enter the changed values of values.yaml?

I tried without any values

### Enter the command that you execute and failing/misfunctioning.

kubectl get pods

### Anything else we need to know?

On an AKS that has version 1.23.8 I did not had any issue deploying the Helm chart.

**Comment by leam18** [comment]
Having the same issue. The Prometheus statefulset gets restarted.

**Comment by dominch** [comment]
I've just found this on my k3s 1.26 
Same thing - those two pods are restarting over and over again :(

**Comment by Sincerite** [comment]
Having the same issue.

**Comment by BJWRD** [comment]
Has anyone identified a fix for this? I'm experiencing the same issue.

**Comment by joshsten** [comment]
same here

**Comment by stand-sure** [comment]
two things that have helped reduce the frequency for me, to wit: setting resources requests (which changes the QoS) and running HA

```yaml
prometheus:
  prometheusSpec:
    replicas: 2
    resources:
      requests:
        memory: 400Mi
```

FWIW, I'm also running thanos, which changes the memory footprint slightly
