### ISSUE TITLE
[kube-prometheus-stack] prometheus-operator ClusterRole permissions

### ISSUE THREAD

**Issue by AmiraAbdo** [prometheus-community/helm-charts#3158]
So, looking at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/clusterrole.yaml, there are three wildcards (*) (lines 27, 33, 40) used to define the rules for the prometheus-operator ClusterRole. 
This is reported as bad practice/vulnerability by some cloud security scanners.

My question is- are all these permissions absolutely necessary? i.e. does it really need all verbs for given resources, including, for example, secrets?

**Comment by AmiraAbdo** [comment]
Additionally, does prometheus absolutely need permissions to get/list/watch secrets in the Cluster?

**Comment by pfrydids** [comment]
Also interested in this.
