### ISSUE TITLE
[kube-prometheus-stack] Deprecation of legacy k8s.gcr.io container image registry

### ISSUE THREAD

**Issue by AlexPerkbox** [prometheus-community/helm-charts#3161]
### Is your feature request related to a problem ?

Starting April 3, 2023, the Kubernetes project will stop publishing community-owned images (known as community images) to the old image registry [k8s.gcr.io](http://k8s.gcr.io/) and use a new community owned registry: [registry.k8s.io](http://registry.k8s.io/)

### Describe the solution you'd like.

Can we have the helm charts updated with the new image repository?

### Describe alternatives you've considered.

A way to explicitly specify image URI

**Comment by Whisper40** [comment]
Hello, this problem does not exist in the chart you specified, they already use the new registry. (check on main branch)
