### ISSUE TITLE
kube-prometheus-stack: node-exporter scrapeInterval should be quoted

### ISSUE THREAD

**Issue by wedobetter** [prometheus-community/helm-charts#3170]
### Describe the bug a clear and concise description of what the bug is.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/servicemonitor.yaml#L44

`Error: UPGRADE FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "monitoring-prometheus-node-exporter" is invalid: spec.endpoints[0].interval: Invalid value: "integer": spec.endpoints[0].interval in body must be of type string: "integer"`

Maybe it needs quoting in the template?

### What's your helm version?

v3.11.2

### What's your kubectl version?

v1.26.2

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

45.8.0

### What happened?

Bug

### How to reproduce it?

set node-exporter scrape interval: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1783

### Enter the changed values of values.yaml?

interval: "10"

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by zeritti** [comment]
`servicemonitor.spec.endpoints[].interval` is of *Duration* type which is a string alias and requires a unit. For instance, both would be correct:
```
interval: "30s"
interval: 30s
```

> Duration is a valid time duration that can be parsed by Prometheus model.ParseDuration() function. Supported units: y, w, d, h, m, s, ms Examples: 30s, 1m, 1h20m15s, 15d
