### ISSUE TITLE
[prometheus] Specify and Use tsdb.out_of_order_time_window in values file

### ISSUE THREAD

**Issue by pchang388** [prometheus-community/helm-charts#3171]
Hi, I am using the helm chart for prometheus (not kube-stack)  - https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus .

I was wondering how we could use the flag for: 
`tsdb.out_of_order_time_window`

Ref: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb (enabled if specified in versions >= `v2.39`)

I tried various combinations in the `extraFlags` section but was not able to make it work and see errors like: 
```
Error parsing commandline arguments: unknown long flag '--storage.tsdb.out_of_order_time_window'
prometheus: error: unknown long flag '--storage.tsdb.out_of_order_time_window'

Error parsing commandline arguments: unknown long flag '--storage.tsdb.out-of-order-time-window'
prometheus: error: unknown long flag '--storage.tsdb.out-of-order-time-window'

etc...
```

Has anyone been able to get this feature flag enabled using the helm chart?

Chart Version: `20.0.2`
App/Image Version: `v2.43.0`

Thanks!

**Comment by zeritti** [comment]
`tsdb.out_of_order_time_window` is a runtime-reloadable parameter that has to be present in the Prometheus' config file. As I see it, the chart does not support `storage.tsdb` at the moment.
