### ISSUE TITLE
Basic auth issue

### ISSUE THREAD

**Issue by Vsevosemnog** [prometheus-community/helm-charts#3172]
### Describe the bug a clear and concise description of what the bug is.

What is a password of admin user for prometheus web ui when i set basic auth?

It creates basic-auth-secret with admin user and apache md5 password. But what is this password? where to find it or set? There`s no variable in values template

### What's your helm version?

v3.11.2

### What's your kubectl version?

1.26

### Which chart?

kube-prometheus-stack

### What's the chart version?

v0.63.0

### Enter the command that you execute and failing/misfunctioning.

helm install chart

**Comment by luizzitol** [comment]
I am also trying to set basic auth to prometheus UI, more specifically I want to set basic auth when accepting remote-writes from other prometheuses.

How did you enable basic auth in prometheus?
