### ISSUE TITLE
Add Renovate to repo to auto update dependencies

### ISSUE THREAD

**Issue by DrFaust92** [prometheus-community/helm-charts#3184]
### Is your feature request related to a problem ?

I see manual work around bumping dependencies as this requires explicit action and time such as https://github.com/prometheus-community/helm-charts/pull/3120

### Describe the solution you'd like.

Use https://docs.renovatebot.com/ with its https://docs.renovatebot.com/modules/manager/helmv3/ capability to auto update dependencies

### Describe alternatives you've considered.

None

**Comment by mikejoh** [comment]
@DrFaust92 Out of curiosity (haven't worked with Renovate yet), how would this be done? In the context of this repo, would it be an easy thing to add?

**Comment by DrFaust92** [comment]
@mikejoh its a github app and it only requires adding a renovte.json config file to root.
for example in one of my projects:
https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/blob/master/renovate.json

and this is an example PR it opens:
https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/pull/104

the renovate.json can be tuned to do stuff like bump chart version as well and it auto rebase PRs

**Comment by mikejoh** [comment]
> @mikejoh its a github app and it only requires adding a renovte.json config file to root.
> 
> for example in one of my projects:
> 
> https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/blob/master/renovate.json
> 
> 
> 
> and this is an example PR it opens:
> 
> https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/pull/104
> 
> 
> 
> the renovate.json can be tuned to do stuff like bump chart version as well and it auto rebase PRs

Awesome! Thanks for the info, seems very straight forward! 👍🏻
