### ISSUE TITLE
Unable to set logLevel to debug via kube-prometheus stack values.yaml file

### ISSUE THREAD

**Issue by wittymindstech** [prometheus-community/helm-charts#3188]
I am trying to change the logLevel to debug in order to check debug messages in the Prometheus pod.

kube-prometheus-stack:
  enabled: true
  prometheus:
    service:
      type: LoadBalancer
    logLevel: debug

 operator:
    logLevel: debug
 alertmanager:
    logLevel: debug

But, i am not seeing debug logs even after restarting prometheus. Please help.
kube-prometheus-stack version : Promethues v2.36.1 
name: kube-prometheus-stack
version: 36.6.2

**Comment by zeritti** [comment]
Log level for Prometheus can be set to debug through
```
prometheus:
  prometheusSpec:
    logLevel: debug
```

**Comment by wittymindstech** [comment]
@zeritti  Thanks a lot, it works !! :)

**Comment by QuentinBisson** [comment]
@wittymindstech Can we close this issue?
