### ISSUE TITLE
[prometheus-blackbox-exporter] cannot disable podSecurityPolicy

### ISSUE THREAD

**Issue by headyj** [prometheus-community/helm-charts#3192]
### Describe the bug a clear and concise description of what the bug is.

Helm seems not very consistent about how api capabilities are detected. Even if I have kubernetes v1.25+, the podSecurityPolicy is being applied. setting `pspEnabled: false` doesn't solve the issue

### What's your helm version?

v3.11.0

### What's your kubectl version?

v1.26 (Client) v1.25.6 (Server)

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

v7.7.0

### What happened?

Helm seems not very consistent about how api capabilities are detected. Even if I have kubernetes v1.25+, the podSecurityPolicy is being applied:
 ```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "prometheus-blackbox-exporter-psp" namespace: "prometheus" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```
So I tried to disable it manually, by setting pspEnabled to false. But still having the same issue:
```
helm upgrade -n prometheus prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter --version 7.7.0 --set pspEnabled=false
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "prometheus-blackbox-exporter-psp" namespace: "prometheus" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

### What you expected to happen?

setting pspEnabled to false should not create the PodSecurityPolicy

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -n prometheus prometheus-blackbox-exporter prometheus-community/prometheus-blackbox-exporter --version 7.7.0 --set pspEnabled=false

**Comment by zeritti** [comment]
The chart does not *install* PSP resources in a cluster without the PSP API, no matter what I set `pspEnabled` to. 

IMHO this specific *upgrade* problem arises from the fact that the chart, as it appears, was installed with `pspEnabled=true` (is default), the cluster then upgraded and with the upgrade the PSP API removed. Now, at upgrade, Helm gets only an error from the API when, I reckon, it is going to remove those PSP resources since `pspEnabled=false`. This Helm [issue](https://github.com/helm/helm/issues/11287) may help.

**Comment by eva-mueller-coremedia** [comment]
We also ran into this problem. We updated to K8s 1.25 but the `prometheus-blackbox-exporter` (Terraform) deployment failed afterwards with the error message

```
Error: unable to build kubernetes objects from current release manifest: 
  resource mapping not found for name:  "prometheus-blackbox-exporter-psp" 
     namespace:  "default"  from "": 
        no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

Unfortunately, both links did not help
* https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/
* https://docs.aws.amazon.com/eks/latest/userguide/pod-security-policy-removal-faq.html

We tried to solve the problem by (temporarily) deleting the `prometheus-blackbox-exporter` helm chart (deployed via Terraform resource) but this did not work. It stucks in state: `uninstalling`

```
helm uninstall --debug prometheus-blackbox-exporter
uninstall.go:95: [debug] uninstall: Deleting prometheus-blackbox-exporter
uninstall.go:117: [debug] uninstall: Failed to delete release: [unable to build kubernetes objects for delete: resource mapping not found for name: "prometheus-blackbox-exporter-psp" namespace: "default" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```

We could solve both (uninstalling and the initial one) problems by using [helm-mapkubeapis](https://github.com/helm/helm-mapkubeapis) as suggested in [Helm release stuck in uninstalling #11513](https://github.com/helm/helm/issues/11513#issuecomment-1404101041)

<details>
<summary>
helm mapkubeapis prometheus-blackbox-exporter
</summary>

```
helm plugin install https://github.com/helm/helm-mapkubeapis
helm mapkubeapis prometheus-blackbox-exporter
2023/05/30 16:00:50 Release 'prometheus-blackbox-exporter' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2023/05/30 16:00:50 Get release 'prometheus-blackbox-exporter' latest version.
2023/05/30 16:00:55 Check release 'prometheus-blackbox-exporter' for deprecated or removed APIs...
2023/05/30 16:00:55 Found 1 instances of deprecated or removed Kubernetes API:
"apiVersion: policy/v1beta1
kind: PodSecurityPolicy
"
No supported API equivalent
2023/05/30 16:00:55 Finished checking release 'prometheus-blackbox-exporter' for deprecated or removed APIs.
2023/05/30 16:00:55 Deprecated or removed APIs exist, updating release: prometheus-blackbox-exporter.
2023/05/30 16:00:55 Set status of release version 'prometheus-blackbox-exporter.v6' to 'superseded'.
2023/05/30 16:00:55 Release version 'prometheus-blackbox-exporter.v6' updated successfully.
2023/05/30 16:00:55 Add release version 'prometheus-blackbox-exporter.v7' with updated supported APIs.
2023/05/30 16:00:55 Release version 'prometheus-blackbox-exporter.v7' added successfully.
2023/05/30 16:00:55 Release 'prometheus-blackbox-exporter' with deprecated or removed APIs updated successfully to new version.
2023/05/30 16:00:55 Map of release 'prometheus-blackbox-exporter' deprecated or removed APIs to supported versions, completed successfully.
```

</details>

**Comment by jkroepke** [comment]
This is not an issue on the blackbox-exporter helm chart. It's an limitation of helm. helm tries to get all the resources which lives in the Helm Release. The issue also exists, if CRD resources are getting deleted.

Such things should be resolved before upgrading Kubernetes. In future, consider to run https://github.com/FairwindsOps/pluto before upgrade your Kubernetes cluster.

https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest Describe, how you can manually patch the helm release or use the [helm-mapkubeapis](https://github.com/helm/helm-mapkubeapis) plugin as mention above.
