### ISSUE TITLE
[prometheus-*-exporter] Changelog for exporter

### ISSUE THREAD

**Issue by tpoindessous** [prometheus-community/helm-charts#3193]
### Is your feature request related to a problem ?

When I want to upgrade version of an exporter (example mysql), I'm not sure what has changed.

### Describe the solution you'd like.

I would like a changelog for version of each exporter.

### Describe alternatives you've considered.

for the moment, I try to view changes between two releases but it's difficult because of the nature of monorepo.

### Additional context.

Thanks for your work !

**Comment by nlamirault** [comment]
I try this feature (https://github.com/argoproj/argo-helm/issues/1721#issuecomment-1382733023), and it works fine.
Chart releases has a changelog using Artifact Hub annotations

**Comment by nlamirault** [comment]
Fixed by : https://github.com/prometheus-community/helm-charts/pull/3567
