### ISSUE TITLE
[kube-state-metrics] Add configmap template

### ISSUE THREAD

**Issue by isuyyy** [prometheus-community/helm-charts#3195]
### Is your feature request related to a problem ?

Since kube-state-metrics support CRD metrics configured in-line or in a **file**,
it would be great to add kube-state-metrics configmap template.
https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md

### Describe the solution you'd like.

I want to add kube-state-metrics configmap template, that can be used to configure CRD metrics.

### Describe alternatives you've considered.

NONE

**Comment by dotdc** [comment]
Hi @isuyyy,

This should be possible using [extraArgs](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml#L43).

Did you tried?
