### ISSUE TITLE
[prometheus-kube-stack]  field bearerTokenFile not found in type config.ScrapeConfig 

### ISSUE THREAD

**Issue by wittymindstech** [prometheus-community/helm-charts#3196]
### Describe the bug a clear and concise description of what the bug is.

I wanted to update the token for authentication using cronjob in a file every 60 minutes  ( expiry time for our token) and consumed by Prometheus because Oauth2 is not supported in our environment.
This token is used to federate metrics from remote endpoint using TLS https.
I am using the bearerTokenFile param as below in the values.yaml file

tls_config:
          insecure_skip_verify: true
bearerTokenFile: /path/to/bearer/token/file/txt

But I got the below error while deploying the Prometheus.

 Message:   ts=2023-04- caller=main.go:450 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 1388: field bearerTokenFile not found in type config.ScrapeConfig"

### What's your helm version?

version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9+k3s2", GitCommit:"0d4e64f7bdb0759f835fb3414278756fc4aa4b03", GitTreeState:"clean", BuildDate:"2023-01-11T21:08:18Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

36.6.2

### What happened?

I wanted to update the token using cronjob in a file every 60 minutes  ( expiry time for our token) and consumed by Prometheus because Oauth2 is not supported in our environment.

I am using the bearerTokenFile param as below in the values.yaml file

tls_config:
          insecure_skip_verify: true
bearerTokenFile: /path/to/bearer/token/file/txt

But I got the below error while deploying the Prometheus.

 Message:   ts=2023-04- caller=main.go:450 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 1388: field bearerTokenFile not found in type config.ScrapeConfig"

### What you expected to happen?

Prometheus metrics  federation should work with the token TLS https.

### How to reproduce it?

In values.yaml file put below:

 - job_name: 'remote-federation'
        scrape_interval: 20s
        scrape_timeout: 20s
        scheme: https
        metrics_path: /federate
        honor_labels: true
        tls_config:
          insecure_skip_verify: true
        bearerTokenFile: /path/to/bearertoken.txt
   
        metric_relabel_configs:
          - source_labels: [id]
            regex: '^static-agent$'
            action: drop
        params:
          match[]:
            - '{job="xyt"}'
        static_configs:
          - targets: ['192.168.1.46:9090']
          
and deploy using helm chart.

### Enter the changed values of values.yaml?

bearerTokenFile

### Enter the command that you execute and failing/misfunctioning.

helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack -f your_values.yaml

**Comment by zeritti** [comment]
It looks like you are setting native Prometheus' configuration but Prometheus does not know `bearerTokenFile`, hence the error. This field is a service monitor's field  `servicemonitor.spec.endpoints[].bearerTokenFile`. 

If you wish to use native Prometheus' configuration in that given context, you are probably looking for `scrape_configs[].authorization.type` and `scrape_configs[].authorization.credentials_file` ([Prometheus ref.](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)). A bearer token is a means of authorization, has no relation to a TLS configuration.
