### ISSUE TITLE
[kube-prometheus-stack] update to 0.64

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#3214]
### Is your feature request related to a problem ?

The prometheus operator is now on version 0.64, it would be nice if this chart followed.

### Describe the solution you'd like.

update CRDs to 0.64

### Describe alternatives you've considered.

Using another chart

### Additional context.

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.64.0

**Comment by sathieu** [comment]
A new CRD needs to be added: https://github.com/prometheus-operator/prometheus-operator/blob/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml

**Comment by jcpunk** [comment]
I believe this is still ongoing on the PR.
