### ISSUE TITLE
[kube-state-metrics] Installation failed

### ISSUE THREAD

**Issue by rneto12** [prometheus-community/helm-charts#3228]
### Describe the bug a clear and concise description of what the bug is.

Kube-state-metrics installation failed in this new chart version

### What's your helm version?

3.11.2

### What's your kubectl version?

1.25.4

### Which chart?

kube-state-metrics

### What's the chart version?

5.4.0

### What happened?

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext]

### What you expected to happen?

kube-state-metrics installed

### How to reproduce it?

helm install kube-state-metrics prometheus-community/kube-state-metrics -n kube-system

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install kube-state-metrics prometheus-community/kube-state-metrics -n kube-system

### Anything else we need to know?

On deployments, maybe the securityContext should be under container spec, like Deployment.spec.template.spec.containers.securityContext.

https://v1-25.docs.kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by pemaxim** [comment]
I have the exact same error.

helm: 3.7.1
kubectl 1.24.9
chart: kube-state-metrics
version: 5.4.0

**Comment by robertlindner** [comment]
The fields allowPrivilegeEscalation and capabilities are only defined in [containerSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core) but the chart tries to set them in [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podsecuritycontext-v1-core)

**Comment by ramdaspotale** [comment]
i wonder if maintainers do care to test before merging changes into main and releasing it.  it does not work on k8s version 1.24 and 1.26 as well @mrueg @jcpunk @dotdc

**Comment by dotdc** [comment]
We do care and are generally doing tests, but everyone can make mistakes, being rude doesn't help anyone.

Please use 5.3.0 or wait for 5.4.1 once https://github.com/prometheus-community/helm-charts/pull/3233 is merged.

**Comment by dotdc** [comment]
Should be good in [kube-state-metrics-5.5.0](https://github.com/prometheus-community/helm-charts/releases/tag/kube-state-metrics-5.5.0)
