### ISSUE TITLE
Add GMartinez-Sisti as chart maintainer

### ISSUE THREAD

**Issue by GMartinez-Sisti** [prometheus-community/helm-charts#3231]
Following https://github.com/prometheus-community/helm-charts/issues/1656, this issue tracks adding @GMartinez-Sisti to the [@prometheus-community/helm-charts-maintainers](https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers) group.

Thank you

**Comment by SuperQ** [comment]
Added in https://github.com/prometheus-community/helm-charts/pull/1778

**Comment by SuperQ** [comment]
Invite sent.

**Comment by GMartinez-Sisti** [comment]
Accepted! Thank you 🙌
