### ISSUE TITLE
Add QuentinBisson as a kube-prometheus-stack maintainer

### ISSUE THREAD

**Issue by QuentinBisson** [prometheus-community/helm-charts#3232]
Following https://github.com/prometheus-community/helm-charts/issues/1656, this issue tracks adding @QuentinBisson to the [@prometheus-community/helm-charts-maintainers](https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers) group.

For context: 

I am an old user of the kube-prometheus-stack helm chart and I have a fair bit of contributions to it and I would like to help maintain the chart

I am already in the list of unnofficial maintainers https://github.com/prometheus-community/helm-charts/blob/0468a4b7aa0350f2d523b0e517ac49a638be5976/charts/kube-prometheus-stack/Chart.yaml#L18 and I would like to have this status official

cc @SuperQ

**Comment by SuperQ** [comment]
Added with https://github.com/prometheus-community/helm-charts/pull/2728

Sent invite.

**Comment by QuentinBisson** [comment]
Thank you it's donw
