### ISSUE TITLE
Add jkroepke as a kube-prometheus-stack maintainer

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/helm-charts#3242]
Following https://github.com/prometheus-community/helm-charts/issues/1656, this issue tracks adding @jkroepke to the [@prometheus-community/helm-charts-maintainers](https://github.com/orgs/prometheus-community/teams/helm-charts-maintainers) group.

I'm mainly responsable for 
- https://github.com/prometheus-community/helm-charts/blob/8b445e4e6be511cf4927ed58cc4bdb8caf36d2e7/charts/prom-label-proxy/Chart.yaml#L13
- https://github.com/prometheus-community/helm-charts/blob/8b445e4e6be511cf4927ed58cc4bdb8caf36d2e7/charts/jiralert/Chart.yaml#L14

and did [contributions](https://github.com/prometheus-community/helm-charts/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajkroepke+) to kube-prometheus-stack as well as other charts like blackbox exporter.

cc @SuperQ

**Comment by SuperQ** [comment]
Verified, invite sent.

**Comment by jkroepke** [comment]
Invite accepted and joined the @prometheus-community/helm-charts-maintainers group
