### ISSUE TITLE
[kube-prometheus-stack] remote error: tls: unrecognized name

### ISSUE THREAD

**Issue by Regis-Loyaute** [prometheus-community/helm-charts#3243]
### Describe the bug a clear and concise description of what the bug is.

Hello since a few days ago i am having this issue while using a discord webhook for alertmanager:

caller=notify.go:732 level=warn component=dispatcher receiver=discord integration=slack[0] msg="Notify attempt failed, will retry later" attempts=1 err="Post \"<redacted>\": remote error: tls: unrecognized name"

I haven't change anything and it was working fine before.

I double check and my webhook works fine ... tried to change a few things but i haven't been able to solve it.

### What's your helm version?

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.11+k3s1", GitCommit:"c14436a9ecfffb3be553a06bb0a4fac6122579ce", GitTreeState:"clean", BuildDate:"2023-03-10T22:03:01Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

 prometheus-community/kube-prometheus-stack

### What's the chart version?

latest

### What you expected to happen?

caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="discord/slack[0]: notify retry canceled after 17 attempts: Post \"<redacted>\": remote error: tls: unrecognized name"

### Enter the changed values of values.yaml?

alertmanager:
  fullnameOverride: alertmanager
  enabled: true
  ingress:
    enabled: false
  config:
    global:
      slack_api_url: "https://discord.com/api/webhooks/1097097876431192114/k7Q8oZDoszvH_89pM3mDk6wA2Jds4ZleKi5oFP_H8BoqgAaTARgsmycBdnvV2RdReCN7/slack"
      resolve_timeout: 5m
    receivers:
    - name: "null"
    - name: "discord"
      slack_configs:
      - channel: "prometheus"
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        username: "Alerts"
        send_resolved: true
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ if ne .CommonAnnotations.summary ""}}{{ .CommonAnnotations.summary }}{{ else }}{{ .CommonLabels.alertname }}{{ end }}
        text: >-
          {{ range .Alerts -}}
          Alert: {{ .Annotations.title }}{{ if .Labels.severity }} - {{ .Labels.severity }}{{ end }}
          Description: {{ if ne .Annotations.description ""}}{{ .Annotations.description }}{{else}}N/A{{ end }}
          Details:
          {{ range .Labels.SortedPairs }} • {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 6h
      receiver: "discord"
      routes:
      - receiver: "null"
        match:
          alertname: Watchdog
      - receiver: "discord"
        match_re:
          severity: critical
        continue: true
    inhibit_rules:
    - source_match:
        severity: "critical"
      target_match:
        severity: "warning"
      equal: ["alertname", "namespace"]

### Enter the command that you execute and failing/misfunctioning.

helm install -n monitoring prometheus prometheus-community/kube-prometheus-stack -f values.yaml

**Comment by tracyhoward** [comment]
I get the error when applying ingress.tls[0] data from the install as follows
`--set grafana.ingress.tls[0].secretName=grafana-tls`
but I was able to successfully set the values in the root values file for the grafana.ingress.tls data
also on latest chart
