### ISSUE TITLE
[prometheus-community/prometheus] Prometheus helm chart not deleting storage-prometheus-alertmanager-0 volume when helm chart is deleted

### ISSUE THREAD

**Issue by mohammed-infstones** [prometheus-community/helm-charts#3257]
### Describe the bug a clear and concise description of what the bug is.

When we delete the prometheus-community/prometheus helm chart, it does not delete the `storage-prometheus-alertmanager-0` volume. This is running on EKS with k8s version 1.25.

### What's your helm version?

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.6-eks-48e63af", GitCommit:"9f22d4ae876173884749c0701f01340879ab3f95", GitTreeState:"clean", BuildDate:"2023-01-24T19:19:02Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

alertmanager

### What's the chart version?

prometheus-20.2.0

### What happened?

When we delete the prometheus-community/prometheus helm chart, it does not delete the `storage-prometheus-alertmanager-0` volume. This is running on EKS with k8s version 1.25.

### What you expected to happen?

The `storage-prometheus-alertmanager-0` volume should be deleted

### How to reproduce it?

# Install
helm upgrade -i prometheus prometheus-community/prometheus --namespace prometheus \
       --set alertmanager.persistence.storageClass="gp3",server.persistentVolume.storageClass="gp3" \
       -f prometheus_values.yaml -f alertmanager_values.yml

# Delete
helm delete prometheus -n prometheus

### Enter the changed values of values.yaml?

Annotations for load balancers

### Enter the command that you execute and failing/misfunctioning.

helm delete prometheus -n prometheus

**Comment by CygnusHyoga** [comment]
I have the same problem with nfs-client or with host-pathprivioner with k3s v1.26. When we delete the prometheus-community/prometheus helm chart, it does not delete the storage-prometheus-alertmanager-0 volume, but other volumes are deleting ok.

It will be a good idea a naming convention for pvc, alert manager have  storage-prometheus-alertmanager-0. I think it will be great to naming the pvc "prometheus-alertmanager". Similar naming the pvc of prometheus server (pvc name: prometheus-server).

Thanks!

**Comment by mohammed-infstones** [comment]
@zeritti thanks for that background. Can we add this as a new feature as I do not see it in the current statefulset spec of alertmanager? And I would like to avoid customizing the chart if possible.
