### ISSUE TITLE
Alertmanager auto override label with matchers is current kubernetes namespace

### ISSUE THREAD

**Issue by duongneo** [prometheus-community/helm-charts#3260]
### Describe the bug a clear and concise description of what the bug is.

Every time I add a new contact point for AlertManager, I always receive an overridder matchers with the namespace of the Kubernetes that I have Helm installed as the value and the namespace of the label.

### What's your helm version?

v3.10.3

### What's your kubectl version?

1.26

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

45.10.1

### What happened?

Every time I add a new contact point for AlertManager, I always receive an overridder matchers with the namespace of the Kubernetes that I have Helm installed as the value and the namespace of the label.

![1](https://user-images.githubusercontent.com/63243846/233045410-7da1171d-b7ab-4740-834d-a92b31f74ac5.PNG)

Command: 'helm install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring -f kube-prometheus-stack-values.yaml'
Content of kube-prometheus-stack-values.yaml:
grafana:
  enabled: false # Not install Grafana
prometheus:
  enabled: false # Not install Prometheus
alertmanager:
  enabled: true
  service: 
    type: LoadBalancer # Create a public IP for Alertmanager
  alertmanagerSpec:
    alertmanagerConfigSelector:
      matchLabels:
        alertmanagerconfig: delivery-infras  
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 30m
      receiver: 'default' # receiver name for default (root) route configuration
      routes:
    receivers:
    - name: 'default' # default receiver name
    templates:
    - '/etc/alertmanager/config/*.tmpl'
 
Content of contact point:
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: rules
  namespace: prometheus
  labels: 
    alertmanagerconfig: XXXXXX
spec:
  route:
      receiver: 'grafana-default-alert'
  receivers:
  - name: 'grafana-default-alert'
    snsConfigs:
    - topicARN: 'arn:aws:sns:XXXX:XXXX:XXXXX'
      sigv4:
        region: XXXX
        accessKey: 
          key: accessKey
          name: sns-config
        secretKey: 
          key: secretKey
          name: sns-config

### What you expected to happen?

I do not want the matchers value in my contact point configuration file to be changed.

### Enter the command that you execute and failing/misfunctioning.

helm install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring -f kube-prometheus-stack-values.yaml

**Comment by hugree** [comment]
@duongneo did you ever solve it? I have the same issue
