### ISSUE TITLE
[prometheus-adapter] Support extra-arguments for the container

### ISSUE THREAD

**Issue by Ladicle** [prometheus-community/helm-charts#327]
**Is your feature request related to a problem? Please describe.**
prometheus-adapter Deployment already supports `extraVolumes` and `extraVolumeMounts`, so we can mount the certifications like this:

```
# Any extra volumes
extraVolumes: []
  # - name: example-name
  #   hostPath:
  #     path: /path/on/host
  #     type: DirectoryOrCreate
  # - name: ssl-certs
  #   hostPath:
  #     path: /etc/ssl/certs/ca-bundle.crt
  #     type: File

# Any extra volume mounts
extraVolumeMounts: []
  #   - name: example-name
  #     mountPath: /path/in/container
  #   - name: ssl-certs
  #     mountPath: /etc/ssl/certs/ca-certificates.crt
  #     readOnly: true
```

However, the Deployment does not allow to specify the extra-arguments of the container, so we cannot specify the certification flag.

**Describe the solution you'd like**

I'd like to specify the extra-arguments to the prometheus-adapter container.

```
extraArguments: []
# - --cert-dir=/etc/ssl/certs
# - --tls-private-key-file=/etc/tls/tls.key
# - --tls-cert-file=/etc/tls/tls.crt
```

**Comment by monotek** [comment]
Would you mind to provide an pr?

**Comment by Ladicle** [comment]
Sure, I'll send pr later.
