### ISSUE TITLE
chart/prometheus older tag 14.12.0 lost?

### ISSUE THREAD

**Issue by mcallaghan-geotab** [prometheus-community/helm-charts#3274]
### Describe the bug a clear and concise description of what the bug is.

hi team quick Q?

https://github.com/prometheus-community/helm-charts/pkgs/container/charts%2Fprometheus/versions

why doesn't  that link show older tags anymore?
the "oldest" one we see is:
```
[15.18.0](https://github.com/orgs/prometheus-community/packages/container/charts%2Fprometheus/48830533?tag=15.18.0)
Published 6 months ago · Digest …
```

using `prometheus-community	https://prometheus-community.github.io/helm-charts`
(helm repo)

i.e. this one:
```
$ helm show chart prometheus-community/prometheus --version 14.12.0
apiVersion: v2
appVersion: 2.31.1
dependencies:
- condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 3.5.*
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
- email: monotek23@gmail.com
  name: monotek
- email: naseem@transit.app
  name: naseemkullah
name: prometheus
sources:
- https://github.com/prometheus/alertmanager
- https://github.com/prometheus/prometheus
- https://github.com/prometheus/pushgateway
- https://github.com/prometheus/node_exporter
- https://github.com/kubernetes/kube-state-metrics
type: application
version: 14.12.0
```

### What's your helm version?

v3.11.2

### What's your kubectl version?

v4.5.7

### Which chart?

charts/prometheus

### What's the chart version?

14.12.0

### What happened?

just wondering about the "packages" list here on github, vs. what is available in the helm repository

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by dotdc** [comment]
Not sure, maybe a change on GitHub.

You can get the tags from the command line : 
```
git clone https://github.com/prometheus-community/helm-charts
cd helm-charts/
git tag -l 'prometheus-[0-9]*'
```

The version you're looking for is from Nov 24, 2021, I think you should upgrade.
