### ISSUE TITLE
Add zeritti as chart maintainer

### ISSUE THREAD

**Issue by zeritti** [prometheus-community/helm-charts#3292]
Please, add @zeritti to the @prometheus-community/helm-charts-maintainers group.

I am currently set as a maintainer in charts _prometheus-operator-admission-webhook_ and _prometheus-smartctl-exporter_
(PR #3208, PR #3277). Some more will follow as per #1656.

Thank you.

cc @SuperQ

**Comment by zanhsieh** [comment]
ping @SuperQ @brancz

**Comment by SuperQ** [comment]
Verified, sent invite.

**Comment by zeritti** [comment]
Thank you, @SuperQ, closing the issue.
