### ISSUE TITLE
[prometheus] configmap-reload fails to connect to prometheus-server

### ISSUE THREAD

**Issue by zeritti** [prometheus-community/helm-charts#3307]
### Describe the bug a clear and concise description of what the bug is.

configmap-reload fails to connect to the Prometheus container `prometheus-server` as set in its `reload-url` flag.

### What's your helm version?

version.BuildInfo{Version:"v3.11", GitCommit:"'66a969e7cc08af2377d055f4e6283c33ee84be33'", GitTreeState:"'clean'", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: v1.27.1 Kustomize Version: v5.0.1 Server Version: v1.26.4+k3s1

### Which chart?

prometheus

### What's the chart version?

21.1.1

### What happened?

`configmap-reload` fails to connect to `prometheus-server` printing the following error repeatedly:

```
level=error ts=2023-04-29T12:58:34.615001641Z caller=runutil.go:100 msg="function failed.
Retrying in next tick" err="trigger reload: received non-200 response:
405 Method Not Allowed; have you set `--web.enable-lifecycle` Prometheus flag?"
```

The flag `web.enable-lifecycle` is enabled by default.

When investigating the flag's value in the configmap-reload container, it shows the URL as `http://127.0.0.1:9090//-/reload`. The double slash is not expected. Removing a slash indeed fixes the problem. If `configmapReload.reloadUrl` gets set to the correct value, the container works as well.

The additional slash character has been introduced through empty `server.prefixURL` (default)  and the deployment template constructing the URL in this manner:
```
{{- $default_url := printf "http://127.0.0.1:9090/%s/-/reload" .Values.server.prefixURL }}
  - --reload-url={{ default $default_url .Values.configmapReload.reloadUrl }}
```

It looks like a regression from #3298.

### What you expected to happen?

configmap-reload can connect to Prometheus successfully.

### How to reproduce it?

Deploy the chart with default values.

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

```
helm install prometheus prometheus-community/prometheus --set persistentVolume.enabled=false
```

**Comment by zanhsieh** [comment]
@zeritti please review #3308
