### ISSUE TITLE
prometheus-kube-stack addtional-scrape-configs adds relabel _configs

### ISSUE THREAD

**Issue by linuxmanju** [prometheus-community/helm-charts#3310]
### Describe the bug a clear and concise description of what the bug is.

kube-promethues stack adding un-necessary rel abel configs in additional scrape configs, making targets non scrapable

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}

### What's your kubectl version?

NA

### Which chart?

prometheus-community/kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-45.23.0

### What happened?

Created below addtional scrape config

`# cat prometheus-additional.yaml
- job_name: "consul"
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
    - targets: ["localhost:9090"]
      labels:
        env: 'production'
        app: 'consul'
 `

Adding it as a secret produces below /etc/prometheus/config_out/prometheus.env.yaml file

`
- job_name: consul
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
    labels:
      env: production
      app: consul
  relabel_configs:
  - source_labels:
    - __meta_ec2_instance_id
    target_label: abcd
  - source_labels:
    - __address__
    target_label: __tmp_hash
    modulus: 3
    action: hashmod
  - source_labels:
    - __tmp_hash
    regex: 0
    action: keep
`

The issue I am facing is additional un-necessary relabel-config is making all my target labels getting dropped and makes the scrape config in active .

<img width="1707" alt="Screenshot 2023-04-30 at 1 15 19 PM" src="https://user-images.githubusercontent.com/15226526/235341846-56619a61-88b0-4bbb-917f-b3b3b7d82355.png">

If I manually run it be removing those relabel configs, everything works fine. 

Any help would be appreciated.

### What you expected to happen?

Additional scrape-config should not have any additional re-label configs which is not added by the end users

### Enter the command that you execute and failing/misfunctioning.

helm install release-ops prometheus-community/kube-prometheus-stack -f values.yaml -n monitoring

**Comment by zeritti** [comment]
That specific `relabel_configs` gets created by Prometheus operator if sharding has been enabled, i.e. value `prometheus.prometheusSpec.shards` is greater than 1. In your case, the value seems to be 3. This `relabel_configs` does not result from your `prometheus.prometheusSpec.additionalScrapeConfigs`.

**Comment by linuxmanju** [comment]
> That specific `relabel_configs` gets created by Prometheus operator if sharding has been enabled, i.e. value `prometheus.prometheusSpec.shards` is greater than 1. In your case, the value seems to be 3. This `relabel_configs` does not result from your `prometheus.prometheusSpec.additionalScrapeConfigs`.

Thanks @zeritti  for the  lead. I got it working, the issue is __address__ needs an IP address I believe,  as opposed to a hostname/FQDN, with ip address in place it seems to works fine.

Thanks to your comment, I could search and find out a similar issue posted in Prometheus operator, their recommendation was to use a service monitor for FQDNs. But for now, this seems sorted. Thanks again.
