### ISSUE TITLE
[prometheus] Enable native histograms 

### ISSUE THREAD

**Issue by danielnaumau** [prometheus-community/helm-charts#3330]
### Describe the bug a clear and concise description of what the bug is.

I cannot enable native-histograms. 

Tried to override default flags but metrics still cannot be uploaded.

 defaultFlagsOverride:
    - --enable-feature=native-histograms

### What's your helm version?

3.8.0

### What's your kubectl version?

1.27.0

### Which chart?

prometheus 

### What's the chart version?

21.1.2

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus --namespace prometheus -f values.yaml

**Comment by zeritti** [comment]
`defaultFlagsOverride` replaces all the default flags. `extraArgs` will do:
```
server:
  extraArgs:
    enable-feature: native-histograms
```

**Comment by danielnaumau** [comment]
tried to use it but unfortunately this config crashes prometheus server. Should I set up smth else too?

**Comment by zeritti** [comment]
Here a note on trying them out: [2.42.0 / 2023-01-31](https://github.com/prometheus/prometheus/releases/tag/v2.42.0)

**Comment by ksemele** [comment]
please reopen that issue because we don't have a way for enable that feature now...
