### ISSUE TITLE
[kube-state-metrics] Image repository override is not working for kube-state-metrics from prometheus chart 

### ISSUE THREAD

**Issue by upasmoh** [prometheus-community/helm-charts#3332]
### Describe the bug a clear and concise description of what the bug is.

Below is defined in values.yaml
image:
  registry: registry.k8s.io
  repository: kube-state-metrics/kube-state-metrics

And in deployment.yaml, it is defined as image: {{ include "kube-state-metrics.image" . }}.
Please update it deployment yaml file to correctly pick the image.

### What's your helm version?

3.10

### What's your kubectl version?

1.25

### Which chart?

kube-state-metrics

### What's the chart version?

v2.8.0

### What happened?

Images is not defined correctly in deployment yaml file.

### What you expected to happen?

Deployment yaml should make use of this
image:
  registry: registry.k8s.io
  repository: kube-state-metrics/kube-state-metrics

### How to reproduce it?

Try to use some custom location for kube-state-metrics image

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus --version 21.0.0 --values values.yaml
Version can be different,

**Comment by zeritti** [comment]
The current Prometheus chart comes with kube-state-metrics release 4.30 which does not yet support split registry and repository. This feature made it to the chart in 5.0. 

For the moment, please, use the `repository` field combining the registry host with repository, e.g.
```
kube-state-metrics:
  enabled: true
  image:
    repository: registry.local/kube-state-metrics
```

**Comment by QuentinBisson** [comment]
This has been solved a few weeks ago https://github.com/prometheus-community/helm-charts/blob/6be7a82ea5c0f966ce4d0c13e91a7edae98a857c/charts/kube-prometheus-stack/Chart.yaml#L43
