### ISSUE TITLE
[prometheus-operator-crds] update to 0.65.0

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#3334]
### Is your feature request related to a problem ?

The upstream CRDs are newly updated

### Describe the solution you'd like.

CRDs updated to the current version

### Describe alternatives you've considered.

nothing specific

### Additional context.

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.65.0

**Comment by aubm** [comment]
Anyone working on this? Otherwise I could take care of it needed
