### ISSUE TITLE
[prometheus-node-exporter] node-exporter should listen on 127.0.0.1 when kube-rbac-proxy is enabled

### ISSUE THREAD

**Issue by rnyrnyrny** [prometheus-community/helm-charts#3339]
### Is your feature request related to a problem ?

With kubeRBACProxy enabled, node-exporter still listens on 0.0.0.0:8100 or $nodeIP:8100,  which makes it easy for anyone to get the metrics data. Maybe it's better to listen on 127.0.0.1:8100, as the point of using kube-rbac-proxy is to protect the metrics api.

### Describe the solution you'd like.

Make node-exporter listen on 127.0.0.1:8100 when kubeRBACProxy is enabled. Also need to add host to readinessProbe and livenessProbe.

### Describe alternatives you've considered.

NA

**Comment by zeritti** [comment]
Is currently being addressed with PR [#3336](https://github.com/prometheus-community/helm-charts/pull/3336).
