### ISSUE TITLE
[kube-prometheus-stack] Use Basic Auth with kube-prometheus-stack

### ISSUE THREAD

**Issue by manidharanupoju24** [prometheus-community/helm-charts#3364]
### Is your feature request related to a problem ?

I'm trying to get basic-auth setup for all the components with the kube-prometheus-stack. I understand that we can use this with 'extraSecret' in helm values.yaml file, but it doesn't reallly work without ingress.

I would like to use basic-auth 

### Describe the solution you'd like.

I would like to use basic-auth without depending on ingress or its annotations. 

### Describe alternatives you've considered.

Looked for this solution everywhere. Although, it works fine with standalone prometheus installation, I'm not able to achieve this using helm chart. 

### Additional context.

I understand that security is a concern, but it would be great if we could use out of the box basic-auth without any dependency on ingress. 

I referred to this : set up basic auth for Alermanager and Prometheus UI via kube-prometheus-stack #1754

**Comment by manidharanupoju24** [comment]
https://github.com/prometheus-community/helm-charts/pull/1193

**Comment by QuentinBisson** [comment]
This is currently not possible with prometheus-operator as the basic-auth-users is not implemented in prometheus-operator https://github.com/prometheus-operator/prometheus-operator/blob/f103831b389be5cf504bdf28002cfa2915b821ed/pkg/apis/monitoring/v1/types.go#L516

@manidharanupoju24 [here](https://github.com/prometheus-operator/prometheus-operator/issues/4200) is the upstream issue, maybe you can contribute there.

I'm closing this for now but reopen if the feature is implemented :)
