### ISSUE TITLE
[kube-prometheus-stack] Use Kustomize for Managing CRDs

### ISSUE THREAD

**Issue by KazW** [prometheus-community/helm-charts#3379]
Managing CRDs can be made easier with a `Kustomization` resource in the chart's `crds` folder. If Kustomize was used, the CRDs can be updated to the latest or a specific version more easily.

Latest:
```bash
kubectl apply --server-side -k https://github.com/prometheus-community/helm-charts/charts/kube-prometheus-stack/crds/
```

Versioned:
```bash
kubectl apply --server-side -k https://github.com/prometheus-community/helm-charts/charts/kube-prometheus-stack/crds/?ref=kube-prometheus-stack-x.y.z
```

### Describe the solution you'd like.

Add a `kustomization.yaml` file to the `crds` directory that references the CRD files.

### Describe alternatives you've considered.

NONE

### Additional context.

This is the approach Traefik uses: https://github.com/traefik/traefik-helm-chart

**Comment by rgarcia6520** [comment]
Placing a kustomization.yaml there will break Fluxv2 installations (an error will be thrown the kustomization can't be created properly), this would be better placed in https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds/templates/ chart

**Comment by GMartinez-Sisti** [comment]
Hi @KazW, https://github.com/prometheus-community/helm-charts/pull/3547 provides a way to manage the CRDs in an easier way.

Closing this. Thank you!
