### ISSUE TITLE
[prometheus] cannot modified retention time by helm chart upgrade command 

### ISSUE THREAD

**Issue by renzibin** [prometheus-community/helm-charts#3381]
### Describe the bug a clear and concise description of what the bug is.

I install prometheus by command:   
helm upgrade --install prometheus prometheus-community/prometheus -f prometheus.values.yaml --namespace istio-system --version 15.11.0

I want set retention time equal 30 day, so  the content of  file prometheus.values.yaml is:
server:
  retention: 30d
it does not work, please help me 

### What's your helm version?

version.BuildInfo{Version:"v3.9.2", GitCommit:"1addefbfe665c350f4daf868a9adc5600cc064fd", GitTreeState:"clean", GoVersion:"go1.17.12"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform :"windows/amd64"} Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platfor m:"linux/amd64"}

### Which chart?
prometheus 

### What's the chart version?

15.11.0

### What happened?
cannot modified retention time

### What you expected to happen?
retention= 30d

### Enter the changed values of values.yaml?
prometheus.values.yaml 
server:
  retention: 30d

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus prometheus-community/prometheus -f prometheus.values.yaml --namespace istio-system --version 15.11.0

**Comment by QuentinBisson** [comment]
@renzibin have you used the correct syntax:

```yaml
server:
  retention: 30d # this needs 2 spaces 
```

**Comment by renzibin** [comment]
@QuentinBisson 
YES，I used the correct syntax:
server:
  retention: 30d # this needs 2 spaces 
but it not cannot modified retention time

**Comment by QuentinBisson** [comment]
Can you send an extract of the generated template so I can try to run it? Because I've tested this property and it works on my end
