### ISSUE TITLE
[kube-prometheus-stack] Missing operator thanosrulers/status cluster role

### ISSUE THREAD

**Issue by Delorien84** [prometheus-community/helm-charts#3382]
### Describe the bug a clear and concise description of what the bug is.

Prometheus operator is complaining that it cannot update resource thanosrulers/status. The coresponding cluster role is missing for operator. See https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheusOperator-clusterRole.yaml#LL26C5-L26C24 

failed: failed to update status subresource: thanosrulers.monitoring.coreos.com \"prometheus-operator-thanos-ruler\" is forbidden: User \"system:serviceaccount:monitoring:prometheus-operator\" cannot update resource \"thanosrulers/status\" in API group \"monitoring.coreos.com\" in the namespace \"monitoring\"

### What's your helm version?

version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"dirty", GoVersion:"go1.20.2"}

### What's your kubectl version?

Client Version: v1.27.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.27.2

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -n monitoring . -f values.yaml

**Comment by zeritti** [comment]
The operator's cluster role has been amended for CRDs and operator release 0.65.1 in chart release 46.0.0.

**Comment by QuentinBisson** [comment]
Thanks zeritti, i'm closing
