### ISSUE TITLE
Add to Artifact Hub and Helm Hub

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#34]
- [x] Artifact Hub
- [x] Helm Hub

**Comment by scottrigby** [comment]
Artifact Hub org is made, and repo is added. It should appear within 30 mins.

If no one gets to it first @Xtigyro has offered to make a Helm Hub PR tomorrow. Once that's done and reviewed I will merge it.

**Comment by scottrigby** [comment]
Artifact Hub is now updated: https://artifacthub.io/packages/search?page=1&org=prometheus&kind=0

**Comment by gkarthiks** [comment]
@scottrigby I will make a Helm Hub PR.

**Comment by gkarthiks** [comment]
I have created the PR in the helm hub. Please take a look at the above PR.

**Comment by gkarthiks** [comment]
@scottrigby just checked. Its already there https://hub.helm.sh/charts/prometheus-community :rocket:
