### ISSUE TITLE
[kube-prometheus-stack] prometheus pod CrashLoopBack

### ISSUE THREAD

**Issue by mohammadasim** [prometheus-community/helm-charts#3409]
### Describe the bug a clear and concise description of what the bug is.

I wanted to install the chart, however after install the Prometheus pod was in CrashLoopBackOff state. The pod logs showed an error in the config files. 
`ts=2023-05-20T06:35:18.408Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: empty duration string"`
I checked my `values.yaml` file and couldn't find any issue. To test that it wasn't an issue with my custom config file, I upgraded the chart installation with vanilla `values.yaml` file provided in this repository. However the pod still had the same state with the same log.

### What's your helm version?

v3.11.3

### What's your kubectl version?

Client Version: v1.27.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

45.28.1

### What happened?

I wanted to install the chart, however after install the Prometheus pod was in CrashLoopBackOff state. The pod logs showed an error in the config files. 
`ts=2023-05-20T06:35:18.408Z caller=main.go:468 level=error msg="Error loading config (--config.file=/etc/prometheus/config_out/prometheus.env.yaml)" file=/etc/prometheus/config_out/prometheus.env.yaml err="parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: empty duration string"`

### What you expected to happen?

I expected the chart to install without any errors, with all pods running.

### How to reproduce it?

Install the chart using the `values.yaml` file

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

`helm install <release-name> prometheus-community/kube-prometheus-stack -f prod_values_new.yaml -n monitoring`

**Comment by zeritti** [comment]
I would suggest to check whether Prometheus operator CRDs are already installed before installing the chart. If they are they are probably out of date and should be upgraded separately (or removed if conditions allow so that helm can install them with the chart).

**Comment by mohammadasim** [comment]
> I would suggest to check whether Prometheus operator CRDs are already installed before installing the chart. If they are they are probably out of date and should be upgraded separately (or removed if conditions allow so that helm can install them with the chart).
