### ISSUE TITLE
Prometheus-kube-stack Add documentation to Readme for third-party applications in a different namespace

### ISSUE THREAD

**Issue by cccsss01** [prometheus-community/helm-charts#3410]
### Is your feature request related to a problem ?

I'm finding it difficult configuring scrapeMonitors to scrape third-part applications in a different namespace.  Hoping we can add some documentation to address this.  Most specifically interested in serviceMonitorNamespaceSelector and not serviceMonitorSelectorNilUsesHelmValues: false
with mTLS would be huge!

### Describe the solution you'd like.

I would be greatly appreciative of adding this documentation to the readme for prometheus-kube-stack

### Describe alternatives you've considered.

Trying to tie in prometheus-operator prometheus and kube-stack prometheus all in one

**Comment by cccsss01** [comment]
I'll submit a PR

**Comment by antinova** [comment]
@cccsss01 any update?
