### ISSUE TITLE
[kube-prometheus-stack] unknown field "attachMetadata"

### ISSUE THREAD

**Issue by tranphuoctien** [prometheus-community/helm-charts#3411]
### Describe the bug a clear and concise description of what the bug is.

I can not install to k8s autopilot (GCP)
This is error: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "attachMetadata" in com.coreos.monitoring.v1.ServiceMonitor.spec`

### What's your helm version?

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17-gke.5400", GitCommit:"6862a2a3696fe4a22d5e429d689d5874ef4200d4", GitTreeState:"clean", BuildDate:"2023-02-22T09:27:53Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.27) and server (1.22) exceeds the supported minor version skew of +/-1

### Which chart?

https://prometheus-community.github.io/helm-charts

### What's the chart version?

45.29.0

### What happened?

I can not install to k8s autopilot (GCP)
This is the error: 
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "attachMetadata" in com.coreos.monitoring.v1.ServiceMonitor.spec`

### What you expected to happen?

I can install 

### Enter the command that you execute and failing/misfunctioning.

helm install prome-stack prometheus-community/kube-prometheus-stack

**Comment by cizara** [comment]
I was having the same issue. Apply the new CRDS (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-44x-to-45x) and try again

**Comment by tranphuoctien** [comment]
> I was having the same issue. Apply the new CRDS (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-44x-to-45x) and try again

Yeah! correct but first we must cleanup
CRDs created by this chart are not removed by default and should be manually cleaned up
```bash
kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd probes.monitoring.coreos.com
kubectl delete crd prometheusagents.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd scrapeconfigs.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com
```
I'll close this issue thanks all

**Comment by gjmzj** [comment]
kube-state-metrics 可以提供哪些监控

**Comment by jgryffindor** [comment]
Looks like this issue has re-emerged. Experiencing it with a clean installation. Initially was causing issues in ArgoCD but now manually reinstalling with helm I get 

`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec): unknown field "attachMetadata" in com.coreos.monitoring.v1.ServiceMonitor.spec`

I've manually deleted the CRDs and applied the latest versions. 

App Version: 0.69.1 
Chart Version:  54.0.1

Any help would be appreciated!

**Comment by jgryffindor** [comment]
It appears that with the helm chart, even when disabling CRDs in the values, it's overwriting the existing servicemonitor definition which is missing the attachMetadata.

**Comment by LSparkzwz** [comment]
> It appears that with the helm chart, even when disabling CRDs in the values, it's overwriting the existing servicemonitor definition which is missing the attachMetadata.

Hi, did you manage to find a workaround for this?

**Comment by rbjorklin** [comment]
@LSparkzwz you might want to try `--server-side=true`
