### ISSUE TITLE
Add xiu to @prometheus-community/helm-charts-maintainers

### ISSUE THREAD

**Issue by xiu** [prometheus-community/helm-charts#3431]
Hi!

Can you add me to the @prometheus-community/helm-charts-maintainers group?

I am currently set as a maintainer for the following charts:
* prometheus-snmp-exporter - https://github.com/prometheus-community/helm-charts/pull/3405
* prometheus-json-exporter - https://github.com/prometheus-community/helm-charts/pull/3406

Thanks!

Related issue: https://github.com/prometheus-community/helm-charts/issues/1656#issuecomment-1554647111

cc @SuperQ

**Comment by SuperQ** [comment]
Verified and sent invite.
