### ISSUE TITLE
[prometheus-kube-stack] Issue while installing it using Helm

### ISSUE THREAD

**Issue by mahmoud-anwer** [prometheus-community/helm-charts#3451]
### Describe the bug a clear and concise description of what the bug is.

While installing prometheus using Helm I got the following issue
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "scrapeConfigNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "scrapeConfigSelector" in com.coreos.monitoring.v1.Prometheus.spec]
```

### What's your helm version?

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Client Version: v1.24.13-eks-0a21954 Kustomize Version: v4.5.4 Server Version: v1.24.13-eks-0a21954

### Which chart?

prometheus-kube-stack

### What's the chart version?

46.5.0

### What you expected to happen?

Successful deployment

### How to reproduce it?

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
kubectl create ns monitoring
helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
```

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

```
helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring
```

**Comment by zedtux** [comment]
Thank you @mahmoud-anwer, I had the exact same issue, and I solved it by deleting the `*.monitoring.coreos.com` CRDs and now it works ! 🎉
