### ISSUE TITLE
[kube-prometheus-stack] Grafana Path values.yaml

### ISSUE THREAD

**Issue by sonic-sw** [prometheus-community/helm-charts#3460]
### Describe the bug a clear and concise description of what the bug is.

Dear community,
below is my config section for grafana. After configuring, the endpoint becomes availble, but a 302 redirects me to /login without the path /grafana/. What am I missing to make the sub-path stick?

### What's your helm version?

1

### What's your kubectl version?

v1.25.9-dispatcher

### Which chart?

kube-prometheus-stack

### What's the chart version?

46.6.0

### Enter the changed values of values.yaml?

`ingress:
    ## If true, Grafana Ingress will be created
    enabled: true

    ## Annotations for Grafana Ingress
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        proxy_set_header Forwarded "for=$http_cf_connecting_ip";
        proxy_set_header X-Forwarded-For "$http_cf_connecting_ip";

    ## Labels to be added to the Ingress
    labels: {}

    ## Hostnames.
    hosts: 
      - apollo.example.com

    ## Path for grafana ingress
    path: /grafana/

    ## TLS configuration for grafana Ingress
    tls: 
      - secretName: ingress-ssl
        hosts:
          - apollo.example.com
`

### Enter the command that you execute and failing/misfunctioning.

    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: 46.6.0
      helm:
        valueFiles:
          - $values/kubernetes/apollo/prometheus/values.yaml

**Comment by zeritti** [comment]
> What am I missing to make the sub-path stick?

Grafana needs to know it is to serve its contents from a subpath. The following should suffice beside the path change in ingress (see also [Run Grafana behind a reverse proxy](https://grafana.com/tutorials/run-grafana-behind-a-proxy/)):

```
grafana:
  grafana.ini:
    server:
      domain: apollo.example.com
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true
```
