### ISSUE TITLE
[prometheus-blackbox-exporter] change values.yaml to take image-version from chart.yaml

### ISSUE THREAD

**Issue by sstoffregen** [prometheus-community/helm-charts#3471]
Could you change it so that the image version is taken from Chart.yaml app labbel like in: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-conntrack-stats-exporter/templates/daemonset.yaml#L35

_Originally posted by @monotek in https://github.com/prometheus-community/helm-charts/pull/3468#pullrequestreview-1467195903_

**Comment by monotek** [comment]
Please just do it in the pr. It's a small change. We don't need another issue for this..
