### ISSUE TITLE
[kube-state-metrics] Support for adding sidecar container from values file

### ISSUE THREAD

**Issue by iamshinto** [prometheus-community/helm-charts#3479]
### Is your feature request related to a problem ?

We are using KSM to monitor CRDs in our cluster and the metrics definition is defined as separate configmaps for each CRD. We would like to make use of a [sidecar container](https://github.com/kiwigrid/k8s-sidecar) which will be used to create a combined configmap of the metrics configuration and then supply this as the KSM configuration.

### Describe the solution you'd like.

Update the deployment template to add fields for additional containers and volumes to be passed as an input from the helm values file

### Describe alternatives you've considered.

We tried using the [chart](https://github.com/bitnami/charts/blob/main/bitnami/kube-state-metrics/values.yaml#L149) provided by bitnami which supports this feature but it does not support monitoring custom resources.

We tried patching the deployment from argocd in a local setup but in our existing setup this is deployed as part of a crossplane composition and can't patch the deployment there. Currently we are using kyverno to combine the configmaps and would like to replace it with this sidecar solution and make the configuration auto generated from a list of resource definitions.

**Comment by dotdc** [comment]
Hi @iamshinto,
This should be fixed by https://github.com/prometheus-community/helm-charts/pull/3861
