### ISSUE TITLE
[prometheus-kube-stack] prometheus datasource test HTTP bad gateway error and dashboards broken

### ISSUE THREAD

**Issue by zmmdv** [prometheus-community/helm-charts#349]
Hello everyone. I have problem with prometheus datasource in grafana. 

Im using 
Kubernetes HA 1.17.13 version
Centos 8 latest update
Docker version 19.03.13 
Helm version 3.4.0 and 
Cilium as network cni. 

As you mentioned in README. Im installing with this command helm install monitoring --namespace monitoring prometheus-community/kube-prometheus-stack. But after all installation done. In grafana dashboard none of dashboards is working. And in datasource im trying to test datasource and HTTP error bad gateway error is coming. Sorry for my bad english. Hope you can help me. I've try versions from master to 10.0.0. Not making any changes in values file

**Comment by franusierra** [comment]
The same problem appears on my local k3s cluster.
I have read that this can be solved by changing the datasource access mode from `proxy` to `direct`, that can be done by modifying [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml) template to accept a access mode value.
I will try today and open a pr if successfull.

**Comment by muammercakir** [comment]
Same issue here.

**Comment by zmmdv** [comment]
> 
> 
> Same issue here.



> 
> 
> The same problem appears on my local k3s cluster.
> I have read that this can be solved by changing the datasource access mode from `proxy` to `direct`, that can be done by modifying [this](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml) template to accept a access mode value.
> I will try today and open a pr if successfull.

Hello everyone. My problem solved with changing network cni on kubernetes cluster. I could not find the correct solution for the plugin problem for weave net on Centos 8. I've changed to cilium cni version 1.9 and everything went ok. Don't forget about firewall ports for cilium on your virtual machines if you using masquerade and firewall ports. You can find the needed ports for cilium here  https://docs.cilium.io/en/v1.9/operations/system_requirements/  Hope my experinece will help you.
