### ISSUE TITLE
[prometheus-redis-exporter] linting fails due to deprecated rbac api version

### ISSUE THREAD

**Issue by gmelillo** [prometheus-community/helm-charts#352]
**Describe the bug**

Running `helm lint fails` with the following error:

```console
[ERROR] templates/role.yaml: the kind "rbac.authorization.k8s.io/v1beta1 Role" is deprecated in favor of "rbac.authorization.k8s.io/v1 Role"
[ERROR] templates/rolebinding.yaml: the kind "rbac.authorization.k8s.io/v1beta1 RoleBinding" is deprecated in favor of "rbac.authorization.k8s.io/v1 RoleBinding"

Error: 1 chart(s) linted, 1 chart(s) failed
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: `prometheus-community/prometheus-redis-exporter`

**Which version of the chart**: `3.6.0`

**What happened**: Linting fails

**What you expected to happen**: Linting to succeed

**How to reproduce it** (as minimally and precisely as possible):

- Have Kubernetes `1.18+`
- Clone the repository
- Navigate to directory `charts/prometheus-redis-exporter`
- Run Helm (3+) linting with helm lint

**Anything else we need to know**: Nope

**Comment by gmelillo** [comment]
If can be helpful I can propose myself to open a PR to upgrade the `apiVersion`

**Comment by monotek** [comment]
Yes, this would be nice :)
