### ISSUE TITLE
[prometheus-kube-stack] Alert manager config secret is not used by alert manager

### ISSUE THREAD

**Issue by CarsonBull** [prometheus-community/helm-charts#355]
**Describe the bug**
When a user sets their alert manager config via helm values(alertmanager.config) it creates a secret named `alertmanager-prometheus-kube-prometheus-alertmanager` but alert manager gets the config from the secret `alertmanager-prometheus-kube-prometheus-alertmanager-generated`. Since this is not set it will roll back to using the default config. 

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version

version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"dirty", GoVersion:"go1.15.3"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.2502", GitCommit:"974eff7a63e05b7eb05c9aded92fae8a3ce14521", GitTreeState:"clean", BuildDate:"2020-10-19T17:01:32Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-kube-stack

**Which version of the chart**:
kube-prometheus-stack-11.1.1

**What happened**:
When configuring alert manager the prometheus kube stack configs from the values file were not being populated and it was using the default alert manager config

**What you expected to happen**:
In the helm values, if a user sets alertmanager.config then it should be used by alert manager overwriting the defaults.

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

Add an alert manager config to you values for the chart
Run a helm install of the chart
Port forward to alert manager
Go to status
The config will be the default config and not the set config

**Anything else we need to know**:

You can work around this by running:
```
kubectl get secrets -n monitoring alertmanager-prometheus-kube-prometheus-alertmanager -o yaml`
copy the yaml into a file and rename it alertmanager-prometheus-kube-prometheus-alertmanager-generated
run `kubectl apply -f alertmanager-config.yaml
Port forward to alert manager then post to /-/reload to load the config
```

This might be as simple as adding `-generated` [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/alertmanager/secret.yaml#L5). I might also be missing something.

Happy to help fix this if it's an issue

**Comment by CarsonBull** [comment]
It looks like I probably created this issue some other way. When deploying to a different environment it worked as expected. Closing for now. I'll reopen if I figure out the issue

**Comment by jjacob27** [comment]
I am facing this same issue...

**Comment by iTaybb** [comment]
This also happens here. I'm baffled to what creates this `-generated` secret.

**Comment by iTaybb** [comment]
In my case, the issue was a bad alertmanager config secret (valid yaml but incorrect keys).
After i fixed it, it all worked fine.

**Comment by celestialorb** [comment]
Having the same issue, I can't see why @iTaybb's solution would help here as the configuration never seems to make its way into the container at all. From what I can tell the chart creates a Secret with the configuration, but never links the StatefulSet to it.

**Comment by unalterable** [comment]
> Having the same issue, I can't see why @iTaybb's solution would help here as the configuration never seems to make its way into the container at all. From what I can tell the chart creates a Secret with the configuration, but never links the StatefulSet to it.

@celestialorb I'm having the same issue too - but i'll tell you why @iTaybb is correct. There is a container deployed alongside alertmanager in alertmanager pod. It's called `config-reloader`. If i tail the logs i can see that it reacts when the non-mounted secret is changed (but only when it's changed correctly). The mounted secret is then updated by this container. However when my new config is invalid - i do not see a reaction.

To be sure i had correct config - i copied the mounted secret (i.e. XXX-generated) and made a tiny change to one of the values and put it into my alertManager config (in my helm chart values.yaml). It worked - the change comes through.

Terrible experience. But, after hours, i did get it to work.

**Comment by nvthuong1996** [comment]
check log of prometheus-operator for get issue
