### ISSUE TITLE
[kube-prometheus-stack] Add support for multicluster configuration with thanos

### ISSUE THREAD

**Issue by batas** [prometheus-community/helm-charts#356]
I have multi cluster prometheus configuration with Thanos, it is working well and I have data from both sources. 
I have a problem with grafana dashboard only, because the variable `cluster` is hidden by default and it will be nice to add option in values to configure this dashboard to hide or show this variable.

**Comment by chromafunk** [comment]
@batas I am facing a similar problem now. My problem is that I have implemented thanos with 3 prom replicas but I need grafana and its dashboards from this repo. How did you manage to get both together ? Do you know of a guide or article I can follow ? Thanks
