### ISSUE TITLE
[prometheus-snmp-exporter] Dell IDRAC timeout

### ISSUE THREAD

**Issue by urbaman** [prometheus-community/helm-charts#3572]
### Describe the bug a clear and concise description of what the bug is.

Hi,

After enabling the snmp-exporter with snmp v3 and a custom snmp.yml to scrape three different IDRAC snmp (different targets in the servicemonitor), I am getting a lot of timeouts even if I set interval and timeout both at 300s.

Is this just the IDRAC(s) being slow to respond?

### What's your helm version?

3.10.1

### What's your kubectl version?

1.27.2

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

0.21.0

### What happened?

Deployed the snmp-exporter with a custom snmp.yml to read three IDRACs in v3, it works but I get a lot of timeouts, even with interval and timeout both at 300s.

### What you expected to happen?

The snmp read being faster.

### How to reproduce it?

Create a custom snmp.yml with an idrac module reading all of the IDRAC's MIB tree.
Deply an snmp-exporter with three different targets.

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-snmp-exporter-idrac prometheus-community/prometheus-snmp-exporter -f snmp-exporter-idrac.yaml -n monitoring

**Comment by tuctboh** [comment]
If you used a custom snmp.yml, it must have created a configmap for you, correct? Are you checking the logs for issues? I feel like the reload mechanism of the snmp.yml isn't working properly, I tried the default config and it didn't work. Didn't understand auths, didn't understand modules.

**Comment by urbaman** [comment]
Hi,

The problem was in a the module asking for everything the idrac snmp exposes. That made the requests too big, and they took more than 2, 3 minutes, sometimes 5. That's too much and more than the timeouts around.
Streamlining the module asking only for what I really needed solved the issue.
