### ISSUE TITLE
[kube-prometheus-stack] Configuration for Base URL

### ISSUE THREAD

**Issue by SujithJulakanti2002** [prometheus-community/helm-charts#3585]
### Is your feature request related to a problem ?

I need to install the Kube-Prometheus-Stack helm chart with base URL and I found that there is no base URL configuration for this chart, like it exists for the Prometheus chart

### Describe the solution you'd like.

It will be better if there exists a configuration available in values.yaml of Kube-prometheus-stack for server-related configurations like base URL and ingress

### Describe alternatives you've considered.

I considered using Prometheus Helm chart, but it doesn't have dependencies like prometheus UI, grafana

**Comment by zeritti** [comment]
> It will be better if there exists a configuration available in values.yaml of Kube-prometheus-stack for server-related configurations like base URL and ingress

The _prometheus_ chart's `server.baseURL` corresponds to the _kube-prometheus-stack_ (KPS) chart's `prometheus.prometheusSpec.externalUrl` ([Ref.](https://github.com/prometheus-community/helm-charts/blob/262ecde2e2c8b8fbee0be724555e2f026b0aa40f/charts/kube-prometheus-stack/values.yaml#L2945)). Both eventually set the Prometheus' flag `web.external-url`.

An ingress to Prometheus can be defined in KPS by means of `prometheus.ingress` ([Ref.](https://github.com/prometheus-community/helm-charts/blob/262ecde2e2c8b8fbee0be724555e2f026b0aa40f/charts/kube-prometheus-stack/values.yaml#L2673)).

**Comment by SujithJulakanti2002** [comment]
So if I want the prometheus to run on sample.westeurope.cloudapp.azure.com/prometheus, I have to give external URL as
externalUrl: " sample.westeurope.cloudapp.azure.com/prometheus" right? @***@***.***>


-
SUJITH JULAKANTI
MLops Engineer
Mobile: 9100810471

**Comment by zeritti** [comment]
> So if I want the prometheus to run on sample.westeurope.cloudapp.azure.com/prometheus, I have to give external URL as
externalUrl: " sample.westeurope.cloudapp.azure.com/prometheus" right?

Including scheme, e.g.:
```
externalUrl: "https://sample.westeurope.cloudapp.azure.com/prometheus"
```

**Comment by SujithJulakanti2002** [comment]
What if I don't have any host configured as of now and I want to test it in localhost and later configure an Application Gateway to have ingress, will it work?

**Comment by SujithJulakanti2002** [comment]
@zeritti , could you please help me

**Comment by SujithJulakanti2002** [comment]
@monotek @zanhsieh @bismarck @mrueg @gkarthiks @QuentinBisson @scottrigby

**Comment by SujithJulakanti2002** [comment]
I think the issue can be closed
