### ISSUE TITLE
[prometheus-cloudwatch-exporter] Ignores IAM Role from ServiceAccount

### ISSUE THREAD

**Issue by setevoy2** [prometheus-community/helm-charts#3596]
### Describe the bug a clear and concise description of what the bug is.

After deploying the chart, a Pod with CloudWatch has ServiceAccount created, and environment variables `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE` set, but instead of using this IAM Role, it uses a WorkerNode Role.

### What's your helm version?

version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.4"}

### What's your kubectl version?

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"archive", BuildDate:"2023-06-15T08:14:06Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.6-eks-a5565ad", GitCommit:"895ed80e0cdcca657e88e56c6ad64d4998118590", GitTreeState:"clean", BuildDate:"2023-06-16T17:34:03Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Which chart?

prometheus-cloudwatch-exporter

### What's the chart version?

0.25.1

### What happened?

After deploying the chart, a Pod with CloudWatch has a ServiceAccount created, and environment variables set:

```
    Environment:
      POD_IP:                        (v1:status.podIP)
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           us-east-1
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 arn:aws:iam::***:role/atlas-monitoring-dev-CloudwatchExporterRole0613A27-EU5LW9XRWVRL
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

But instead of the `AWS_ROLE_ARN`, it uses a NodeRole and thus, can not access CloudWatch:

```
WARNING: CloudWatch scrape failed
software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: User: arn:aws:sts::***:assumed-role/eks-dev-1-26-EKSClusterNodegroupNodegroupNodeGroup-1A4PNH1LKOJZT/i-0e71a18f8f67796c8 is not authorized to perform: cloudwatch:ListMetrics because no identity-based policy allows the cloudwatch:ListMetrics action (Service: CloudWatch, Status Code: 403, Request ID: d33881ee-ca25-4400-9f3c-a62ce7da5f2a)
```

Also, the NodeRole is displayed in the Pod's IMDS:

```
$ kk -n dev-monitoring-ns exec -ti  atlas-victoriametrics-prometheus-cloudwatch-exporter-cd656hdxlt -- curl -s 169.254.169.254/latest/meta-data/iam/security-credentials/
eks-dev-1-26-EKSClusterNodegroupNodegroupNodeGroup-1A4PNH1LKOJZT
```

### What you expected to happen?

The Pod must use a Role from the `AWS_ROLE_ARN` variable

### How to reproduce it?

Deploy the chart with the `serviceAccount.annotations.eks.amazonaws.com/role-arn: <role_arn>` set

### Enter the changed values of values.yaml?

```
  serviceAccount: 
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::***:role/atlas-monitoring-dev-CloudwatchExporterRole0613A27-EU5LW9XRWVRL
  aws:
    role: arn:aws:iam::***:role/atlas-monitoring-dev-CloudwatchExporterRole0613A27-EU5LW9XRWVRL
    stsRegional:
      enabled: true
```

### Enter the command that you execute and failing/misfunctioning.

```
$ helm -n dev-monitoring-ns upgrade --install atlas-victoriametrics . -f values/dev/atlas-monitoring-dev-values.yaml
```

**Comment by arseny-zinchenko** [comment]
I had an error in the Trus relation policy, so CloudWatch Pod couldn't assume it and used Node Role instead.

**Comment by setevoy2** [comment]
I had an error in the Trust relationship of the Role, so CloudWatch Pod couldn't assume it and used Node's Role instead.

**Comment by durga-dwibedy** [comment]
Hi @setevoy2 ,

I am facing exactly same issue. What was your fix ? This is my trust relationship of the role.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

**Comment by setevoy2** [comment]
@durga-dwibedy 
Are you running CW Exporter on an EC2? As my issue was in Kubernetes.

If you are on a plain EC2, try to check if it can assume that Role by running `[aws sts assume-role](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html)` from the EC2.

Also, check events in the CloudTrail - there must be errors related to the IAM `sts:AssumeRole` operations.

**Comment by durga-dwibedy** [comment]
Hi @setevoy2 ,

I have deployed it on an EKS Cluster. I think I got you , but if you can provide a snippet of your Trust Policy , it would be great.

**Comment by durga-dwibedy** [comment]
Hi @setevoy2 ,

My Trust Policy looks exactly same , but I still get error...I have only attached [CloudWatchReadOnlyAccess] policy  though...

Do  I  need to attach some other policies ?
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::ACCOUNT_ID:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/XXXXXX"
            },
            "Action":  "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/XXXXX:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-2.amazonaws.com/id/XXXXX:sub": "system:serviceaccount:default:prometheous-cloudwatch-exporter"
                }
            }
        }
    ]
}

```
**Error** 

Jul 20, 2023 6:38:54 PM io.prometheus.cloudwatch.CloudWatchCollector collect
WARNING: CloudWatch scrape failed
software.amazon.awssdk.services.sts.model.StsException: User: arn:aws:sts::**ACCOUNT_ID**:assumed-role/prometheous-cloudwatch-exporter-role/aws-sdk-java-1689878154487 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::**ACCOUNT_ID**:role/prometheous-cloudwatch-exporter-role (Service: Sts, Status Code: 403, Request ID: a48ec4c1-8a5d-4473-9618-d1e6ba382e8d)

**Comment by setevoy2** [comment]
That's weird...

Compare my error:
> User: arn:aws:sts::***:assumed-role/eks-dev-1-26-EKSClusterNodegroupNodegroupNodeGroup-1A4PNH1LKOJZT/i-0e71a18f8f67796c8 **is not authorized to perform: cloudwatch:ListMetrics**

And your:
> User: arn:aws:sts::ACCOUNT_ID:assumed-role/prometheous-cloudwatch-exporter-role/aws-sdk-java-1689878154487 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::ACCOUNT_ID:role/prometheous-cloudwatch-exporter-role

Looks like circle loop, but with the `sts:AssumeRole` on the next iteration.
And your Pod already assumed the correct Role, as it says "_User: arn:aws:sts::ACCOUNT_ID:assumed-role/prometheous-cloudwatch-exporter-role ... is not authorized_" (the first iteration was successful, with the `sts:AssumeRoleWithWebIdentity`.

Maybe it's something with the values? But anyway - why `sts:AssumeRole`?... IDK :-/

Could you show your IAM Policy attached to the Role, and related `values.yaml` part?

**Comment by durga-dwibedy** [comment]
Hi @setevoy2 ,

I figured it last night , It was a typo in the values.yaml file vs the actual role name . Thanks for your guidance...

[AWS: EKS, OpenID Connect, and ServiceAccounts](https://rtfm.co.ua/en/aws-eks-openid-connect-and-serviceaccounts/) Link is very good.

**Comment by Vaibhav-1995** [comment]
Hi @durga-dwibedy 

Thank you for raising this issue - it helped to recheck my IAM role configuration.

I also faced the same issue and noticed that SA name generated through helm deployment and the SA name I provided in Trust Relationships of IAM role was not matching. So, it was redirecting to eks-node IAM role.

**Comment by TreeKat71** [comment]
Does it support IRSAv2 now? I mean the pod identity association.

**Comment by Rohlik** [comment]
@TreeKat71 We use cloudwatch-exporter with EKS Pod Identity without issues.
