### ISSUE TITLE
[prometheus-postgres-exporter] support log.level flags or any extra flag variable

### ISSUE THREAD

**Issue by azhurbilo** [prometheus-community/helm-charts#360]
**Is your feature request related to a problem? Please describe.**
Default log level not enough to understand a custom query problem

**Describe the solution you'd like**
Add support "log.level" flag or any extra flags variable

https://github.com/wrouesnel/postgres_exporter#flags

**Comment by gkarthiks** [comment]
Feel free to open a PR as well.
