### ISSUE TITLE
[prometheus] Install Error at <.Subcharts.alertmanager>

### ISSUE THREAD

**Issue by Sediket** [prometheus-community/helm-charts#3610]
### Describe the bug a clear and concise description of what the bug is.

Hello new to all of this, trying to install the prometheus helm chart per instructions and I receive the error below:
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/prometheus
```
results in error:
```
Error: template: prometheus/templates/_helpers.tpl:112:47: executing "prometheus.alertmanager.fullname" at <.Subcharts.alertmanager>: nil pointer evaluating interface {}.alertmanager
```

Not sure if I needed to set a value or something it wasn't clear.

### What's your helm version?

v3.6.3

### What's your kubectl version?

1.27.1

### Which chart?

prometheus

### What's the chart version?

23.1.0

### What happened?

install error:
```
Error: template: prometheus/templates/_helpers.tpl:112:47: executing "prometheus.alertmanager.fullname" at <.Subcharts.alertmanager>: nil pointer evaluating interface {}.alertmanager
```

### What you expected to happen?

chart installation

### How to reproduce it?

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/prometheus
```

### Enter the command that you execute and failing/misfunctioning.

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/prometheus
```

**Comment by zeritti** [comment]
Please, upgrade `helm`. Installing the chart requires `helm` release 3.7+ ([README](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#prerequisites)).
