### ISSUE TITLE
kube-prometheus-stack ,Issue : unknown field "scrapeConfigNamespaceSelector" "scrapeConfigSelector"

### ISSUE THREAD

**Issue by jones-traice** [prometheus-community/helm-charts#3624]
### Describe the bug a clear and concise description of what the bug is.

Getting the below error when installing the kube prometheus stack.

---------------------------------------------------------------
:~$  helm repo add prometheus-community https://prometheus-community.github.io/helm-charts  
"prometheus-community" already exists with the same configuration, skipping

:~$ helm repo add stable https://charts.helm.sh/stable  
"stable" already exists with the same configuration, skipping

:~$ helm install prom  prometheus-community/kube-prometheus-stack
W0721 08:19:51.030972    2953 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "scrapeConfigNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "scrapeConfigSelector" in com.coreos.monitoring.v1.Prometheus.spec]

-------------------------------------------------------------

### What's your helm version?

version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.18.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10-gke.2300", GitCommit:"1d7ae0799b40b0cd95502e3a5e698db62572e341", GitTreeState:"clean", BuildDate:"2023-02-22T09:28:49Z", GoVersion:"go1.19.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

version: 48.1.2

### What happened?

Issue while installing kube prometheus stack

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

helm install prom  prometheus-community/kube-prometheus-stack

**Comment by jones-traice** [comment]
Issue got solved by deleting the old CRD resources.

kubectl delete crd alertmanagerconfigs.monitoring.coreos.com
kubectl delete crd alertmanagers.monitoring.coreos.com
kubectl delete crd podmonitors.monitoring.coreos.com
kubectl delete crd probes.monitoring.coreos.com
kubectl delete crd prometheusagents.monitoring.coreos.com
kubectl delete crd prometheuses.monitoring.coreos.com
kubectl delete crd prometheusrules.monitoring.coreos.com
kubectl delete crd scrapeconfigs.monitoring.coreos.com
kubectl delete crd servicemonitors.monitoring.coreos.com
kubectl delete crd thanosrulers.monitoring.coreos.com

**Comment by Markieta** [comment]
A less destructive approach:

```bash
# Retrieve CRD manifests
git clone git@github.com:prometheus-community/helm-charts.git
cd helm-charts/charts/kube-prometheus-stack/charts/crds/crds/
git checkout <version_tag> # e.g., kube-prometheus-stack-48.1.2

# Create new CRDs
kubectl create -f crd-prometheusagents.yaml
kubectl create -f crd-scrapeconfigs.yaml

# Patch existing CRDs
kubectl patch crd alertmanagerconfigs.monitoring.coreos.com --patch-file crd-alertmanagerconfigs.yaml
kubectl patch crd alertmanagers.monitoring.coreos.com       --patch-file crd-alertmanagers.yaml
kubectl patch crd podmonitors.monitoring.coreos.com         --patch-file crd-podmonitors.yaml
kubectl patch crd probes.monitoring.coreos.com              --patch-file crd-probes.yaml
kubectl patch crd prometheuses.monitoring.coreos.com        --patch-file crd-prometheuses.yaml
kubectl patch crd prometheusrules.monitoring.coreos.com     --patch-file crd-prometheusrules.yaml
kubectl patch crd servicemonitors.monitoring.coreos.com     --patch-file crd-servicemonitors.yaml
kubectl patch crd thanosrulers.monitoring.coreos.com        --patch-file crd-thanosrulers.yaml
```

If you're using Argo, **REFRESH** Argo CD `app` should clear the error. Then **SYNC**.
