### ISSUE TITLE
[kube-prometheus-stack] Enabling windowsMonitoring does not produces metrics for windows nodes

### ISSUE THREAD

**Issue by buckleyGI** [prometheus-community/helm-charts#3625]
### Describe the bug a clear and concise description of what the bug is.

After setting up the stack and succefully received the linux nodes metrics in grafana,
I enabled windows montoring for the helm chart

```
windowsMonitoring:
  enabled: true
```

Reading up on the documentation this should be sufficient. 

The dashboards in Grafana are created but I recieve not data for the dashboards, for example

Kubernetes / USE Method / Node(Windows)

Reading further I see hat HostProcess Containers is a prerequisites.
I run the cluster on amazon EKS version 1.26
This feature is GA as of 1.26 so this prereq should be fullfilled.

Trying to troublesshot this further I queried the service of the windows export 

` curl kube-prometheus-stack-prometheus-windows-exporter:9182`

And go back the following

 ```
   <main>
      <h2>Prometheus Exporter for Windows servers</h2>
      <div>
        <ul>

          <li><a href="/metrics">Metrics</a></li>

          <li><a href="/health">Health Check</a></li>

          <li><a href="/version">Version Info</a></li>

        </ul>
      </div>
    </main>
  </body>
</html>
```

I believe this is already wrong as the Metrics/Healt Check/Version info should already return something at this point

Checking the logs of the 2 containers of the exporter give the following

The configure-firewall container

```
¦ Description                   :                                                                                                                          ¦
¦ DisplayGroup                  :                                                                                                                          ¦
¦ Group                         :                                                                                                                          ¦
¦ Enabled                       : True                                                                                                                     ¦
¦ Profile                       : Any                                                                                                                      ¦
¦ Platform                      : {}                                                                                                                       ¦
¦ Direction                     : Inbound                                                                                                                  ¦
¦ Action                        : Allow                                                                                                                    ¦
¦ EdgeTraversalPolicy           : Block                                                                                                                    ¦
¦ LooseSourceMapping            : False                                                                                                                    ¦
¦ LocalOnlyMapping              : False                                                                                                                    ¦
¦ Owner                         :                                                                                                                          ¦
¦ PrimaryStatus                 : OK                                                                                                                       ¦
¦ Status                        : The rule was parsed successfully from the store. (65536)                                                                 ¦
¦ EnforcementStatus             : NotApplicable                                                                                                            ¦
¦ PolicyStoreSource             : PersistentStore                                                                                                          ¦
¦ PolicyStoreSourceType         : Local                                                                                                                    ¦
¦ RemoteDynamicKeywordAddresses : {}                                                                                                                       ¦
¦ PolicyAppId                   : 
```

windows-exporter
```
time="2023-07-21T14:21:32Z" level=info msg="Starting windows_exporter (version=0.22.0, branch=heads/tags/v0.22.0, revision=b29434c7c057e8616880cacf99d59 │
│ time="2023-07-21T14:21:32Z" level=info msg="Build context (go=go1.20.2, platform=windows/amd64, user=runneradmin@fv-az365-662, date=20230326-19:59:45, t │
│ time="2023-07-21T14:21:32Z" level=info msg="Listening on" source="gokit_adapter.go:38"                                                                   │
│ time="2023-07-21T14:21:32Z" level=info msg="TLS is disabled." source="gokit_adapter.go:38"                                                               │
│ time="2023-07-21T15:20:54Z" level=info msg="No Network Stats for container: 1f649cd5066df421e888a629b52274e553cee3380c07750d218f47e355ed8c7f" source="co │
│ time="2023-07-21T15:20:54Z" level=info msg="No Network Stats for container: 209cee2d2bf0c37a534cd9f48864ba1577d0d626fa206bb9744afaf366eadbe7" source="co │
│ time="2023-07-21T15:20:54Z" level=info msg="No Network Stats for container: 20b63fb1cecd870504a391d4bdcdac958e26a3186c8576998130925317a049a6" source="co │
```

I read on the other issues that the "No Network Stats for container" is still and issue but should not for example prevent CPU metrics to come through.

Any help is greatly appreciated as I am a bit out of my depth setting up Prometheus for the first time

Should I not only helm install the Prometheus stack but also create a ServiceMonitor mannualy for the windows export?
I could not find this in the documentation but find it strange that there is a node-exporter (linux) in prometheus->status->targets but not a windows-export.

Any tips or help on how to further troubleshoot this are very welcome as all the logs that I consult don't bring a problem to light other then the "No Network Stats" from above.
As I am a Prometheus beginner I could also have wrong exceptions at this point (it should be separate Prometheus target) or make wrong assumptions.

@lippertmarkus I would be very grateful if you can point me in the right direction to get this working.
Thank you for the fresh PR and thinking of windows BTW :)

Thank you!

### What's your helm version?

v3.12.2

### What's your kubectl version?

1.26

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.1.1

### Enter the changed values of values.yaml?

windowsMonitoring:
  enabled: true

### Enter the command that you execute and failing/misfunctioning.

 helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --values prom-values.yaml

**Comment by lippertmarkus** [comment]
Hi @buckleyGI, like you already discussed in the other issue: 
- you need to explicitely activate the ServiceMonitor or PodMonitor in the prometheus-windows-exporter subchart, that might is a bit unintuitive
- The memory collector is not enabled per default for the prometheus-windows-exporter subchart so that some data is missing
- There's a bug that the job name in the Windows dashboards in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14 are currently not parameterized (should be set to `windowsMonitoring.job`) and is currently `kubernetes-windows-exporter`. As a workaround, you can set the jobLabel on the serviceMonitor.

As a workaround for all of this you can use the following values:
```yaml
kube-prometheus-stack:
  prometheus-windows-exporter:
    podLabels: 
      jobLabel: kubernetes-windows-exporter
    prometheus:
      monitor:
        enabled: true
        jobLabel: jobLabel
    config: |-
      collectors:
        enabled: '[defaults],memory,container'
  windowsMonitoring:
    enabled: true
    job: kubernetes-windows-exporter
```
