### ISSUE TITLE
[prometheus-snmp-exporter] GitOps keeps getting OutOfSync due to missing param in ServiceMonitor endpoint

### ISSUE THREAD

**Issue by outductor** [prometheus-community/helm-charts#3626]
### Describe the bug a clear and concise description of what the bug is.

It looks like the action parameter is missing here.
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-snmp-exporter/templates/servicemonitor.yaml#L29

<img width="1229" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/20236173/76579117-c112-4798-93c8-f4a50a3d1657">

### What's your helm version?

ArgoCD 2.7.8

### What's your kubectl version?

ArgoCD 2.7.8

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

1.6.0

### Enter the command that you execute and failing/misfunctioning.

https://github.com/GiganticMinecraft/seichi_infra/blob/main/seichi-onp-k8s/manifests/seichi-kubernetes/apps/cluster-wide-apps/app-of-other-apps/prometheus-snmp-exporter.yaml

**Comment by lenglet-k** [comment]
Hi, I have this problem with prometheus-blackbox-exporter

**Comment by thinkmassive** [comment]
I also have this issue with the blackbox-exporter (see [`metricsRelabeling`](https://github.com/prometheus-community/helm-charts/blob/prometheus-blackbox-exporter-8.4.0/charts/prometheus-blackbox-exporter/templates/servicemonitor.yaml#L36-L46) in the template). The default `action: replace` is added by k8s, so the only fix seems to be adding those fields into the chart.
