### ISSUE TITLE
[kube-prometheus-stack] Enabling query log for prometheus

### ISSUE THREAD

**Issue by yaron-idan** [prometheus-community/helm-charts#365]
**Is your feature request related to a problem? Please describe.**
Our prometheus servers have started OOMing in one of our clusters, and we want to explore the queries made against them to assess if this is the root cause. However - I can't figure out how to enable query log using the chart.

**Describe the solution you'd like**
I would like the chart to allow extending a configmap which can include the [required configuration for enabling query log.](https://prometheus.io/docs/guides/query-log/#enable-the-query-log)

**Describe alternatives you've considered**
I've noticed the pod is loading an empty dir volume called config-out, which is empty. I can override this directive manually but I'm not sure what the consequences would be.

**Comment by skoenig** [comment]
I think this is still a valid feature request as it would help to debug slow / expensive queries.
