### ISSUE TITLE
[kube-prometheus-stack] PDB uses wrong api version

### ISSUE THREAD

**Issue by titirigaiulian** [prometheus-community/helm-charts#3655]
### Is your feature request related to a problem ?

After k8s upgrade from 1.24 to 1.25 there are some api deprecations. One such [deprecation](policy/v1beta1: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125) is PodDisruptionBudget apiVersion

All across the project, we use Capabilities [build it object](https://helm.sh/docs/chart_template_guide/builtin_objects/) from helm.
The problem arrises when trying to install the chart with tools that don't use helm instal, but helm template and kubectl apply. On helm template the Capabilities feature uses k8s client version which might be different from the remote one.

### Describe the solution you'd like.

Allow apiVersion overriding from values.yaml

### Describe alternatives you've considered.

None I can think of

**Comment by Allex1** [comment]
Hi, I'm reasonable sure `helm template --validate` would help here  https://helm.sh/docs/helm/helm_template/#helm-template

**Comment by GMartinez-Sisti** [comment]
Hi, @titirigaiulian, 

As posted on https://github.com/prometheus-community/helm-charts/pull/3656#discussion_r1304056673.

This can be easily overcome using the parameter [`--kube-version`](https://helm.sh/docs/helm/helm_template/) on `helm template`. If you're using `kubectl apply`, it means you can get the server version with `kubectl version`.

Would this work for you?
