### ISSUE TITLE
Add @rpahli as member to prometheus-community/helm-charts-maintainers

### ISSUE THREAD

**Issue by torstenwalter** [prometheus-community/helm-charts#366]
@rpahli was added as maintainer of the prometheus-stackdriver-exporter chart in https://github.com/prometheus-community/helm-charts/pull/183#issuecomment-709910061

He needs to be added to the `prometheus-community/helm-charts-maintainers` team so that he can review and approve PRs.

@brancz or @superq could you do that?

**Comment by SuperQ** [comment]
Done, invite sent.

**Comment by torstenwalter** [comment]
Thanks!
