### ISSUE TITLE
[prometheus-kube-stack] podMonitorNamespaceSelector and serviceMonitorNamespaceSelector are wrongly pointing to namespaceselector type

### ISSUE THREAD

**Issue by amuraru** [prometheus-community/helm-charts#367]
**Describe the bug**

The `podMonitorNamespaceSelector` and `serviceMonitorNamespaceSelector` parameters: 
https://github.com/prometheus-community/helm-charts/blob/72a59c7bd3ff092cfd1bd2e654feaa62618a2b6f/charts/kube-prometheus-stack/values.yaml#L1809-L1812

are pointing to https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#namespaceselector type but looking into the CRD definition these seem to be `LabelSelector`s:
https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml#L4397-L4401
and https://github.com/prometheus-operator/prometheus-operator/blob/05c02d1ddb9bc0dcf83cf0cc7f24c3b36beb5d1c/pkg/apis/monitoring/v1/types.go#L94

Can you clarify this? thanks

**Comment by amuraru** [comment]
reopening this as this is still valid

**Comment by monotek** [comment]
Would you mind to create an pr please?
