### ISSUE TITLE
[kube-prometheus-stack]  A Small Error in values.yaml

### ISSUE THREAD

**Issue by ismail-temiz** [prometheus-community/helm-charts#3687]
### Describe the bug a clear and concise description of what the bug is.

Hi,

Not sure if I opened this in the right place, apologies if not.

This is not a major issue but while I was deploying the helm chart noticed a mistake in one of the examples in values.yaml

```
    scrapeConfigSelector: {}
    ## Example which selects scrapeConfigs with label "prometheus" set to "somelabel"
    # scrapeConfig:
    #   matchLabels:
    #     prometheus: somelabel
```

In the example `scrapeConfig` should also be `scrapeConfigSelector` otherwise it won't work.

Thank you.

### What's your helm version?

"v3.12.2"

### What's your kubectl version?

1

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.2.2

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by dongjiang1989** [comment]
Seems like an example error
