### ISSUE TITLE
[prometheus] defaultFlagsOverride example causes "Error loading config (--config.file=prometheus.yml)" 

### ISSUE THREAD

**Issue by CVanF5** [prometheus-community/helm-charts#3694]
### Describe the bug a clear and concise description of what the bug is.

Just a values example issue

If you enable the agent feature as the helm values example suggests, the Prometheus pod will CrashLoop
```
server:
  defaultFlagsOverride:
    - --enable-feature=agent
```
```
ts=2023-08-15T13:04:52.673Z caller=main.go:190 level=info msg="Experimental agent mode enabled."
ts=2023-08-15T13:04:52.673Z caller=main.go:489 level=error msg="Error loading config (--config.file=prometheus.yml)" file=/prometheus/prometheus.yml err="open prometheus.yml: no such file or directory"
```

A simple workaround is to re-add the --config.file flag as it gets removed when defaultFlagsOverride is used 
```
server:
  defaultFlagsOverride:
    - --config.file=/etc/config/prometheus.yml
    - --enable-feature=agent
```

### What's your helm version?

3.12.3

### What's your kubectl version?

1.27.4

### Which chart?

prometheus

### What's the chart version?

23.3.0

### Enter the command that you execute and failing/misfunctioning.

```
helm -n prometheus upgrade --install --create-namespace <namespace> prometheus-community/prometheus -f values.yaml
```

**Comment by ferncabrera** [comment]
Any reason this has been closed? I've been battling this issue for hours now first thinking it was a skaffold templating issue as using the below configuration + override throws the same error as OP describes:

`
          - name: prometheus
            remoteChart: prometheus
            version: 25.26.0
            namespace: monitoring
            createNamespace: true
              # valuesFiles:
              #   - ./common/prom/kustomize/base/values.yaml
            setValues:
              server.defaultFlagsOverride: 
                - --web.external-url=http://localhost/prometheus
            # wait: true
            # upgradeOnChange: true
            repo: https://prometheus-community.github.io/helm-charts
`
I tried manually copying the values and schema files to use them instead and override the inputs manually but get the exact same error, below is the part of the values.yml I am referring to specifically, the commented out lines at the bottom were my attempt at getting overriding the external url:
`
  # List of flags to override default parameters, e.g:
  # - --enable-feature=agent
  # - --storage.agent.retention.max-time=30m
  # - --config.file=/etc/config/prometheus.yml
  defaultFlagsOverride: [] 
  # defaultFlagsOverride: 
    # - --web.external-url="http://localhost/prometheus"  
`

Cannot use this chart at all as it stands 😢

**Comment by jibzmat** [comment]
I tried doing 
```
defaultFlagsOverride:
      - --enable-feature=otlp-write-receiver
```
and face the same issue

**Comment by julian-sanz-code-seat** [comment]
Hi @ferncabrera and @jibzmat , it seems that defaultFlagsOverride override all args used by prometheus command so maybe it override some mandatory flag.

I tried to use extraArgs attribute to add enable-feature ar. It adds new arg to command line and i have not got any error.
```
server:
  extraArgs:
    enable-feature: otlp-write-receiver
```
Maybe it is useful for you.

**Comment by zeritti** [comment]
> I tried doing
> 
> ```
> defaultFlagsOverride:
>       - --enable-feature=otlp-write-receiver
> ```
> 
> and face the same issue version 25.26.0

Please, do not use field `defaultFlagsOverride` as this field overwrites all the default flags including the path to the configuration file. 

If you wish to add a flag, use `server.extraArgs`(alternatively, `server.extraFlags` but this list is by default not empty, its default elements have to be repeated). Please, see the comments at the fields in the values file.
