### ISSUE TITLE
[kube-prometheus-stack] ARM Support

### ISSUE THREAD

**Issue by eddiezane** [prometheus-community/helm-charts#373]
After digging in deep I'm opening this as tracking for anyone that comes here looking to deploy kube-prometheus-stack on an ARM or ARM64 device like a Raspberry Pi.

With https://github.com/prometheus-community/helm-charts/pull/280 merged the last thing remaining is for [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics/) to merge https://github.com/kubernetes/kube-state-metrics/pull/1237 - that's being tracked here at https://github.com/prometheus-community/helm-charts/issues/111.

The default image in the [old kube-state-metrics chart](https://github.com/helm/charts/tree/master/stable/kube-state-metrics) was from quay.io and did not have multi-arch support. The new chart mentioned above will use the new multi-arch gcr image and it will switch to v2 of kube-state-metrics which has some breaking changes.

For now you can override the kube-state-metrics image in your `values.yml` with:

```
kube-state-metrics:
  image:
    repository: k8s.gcr.io/kube-state-metrics-arm64
    tag: v1.9.5
```

If you need v1.9.7 you can use the image that I built [here](https://hub.docker.com/r/eddiezane/kube-state-metrics/tags). See https://github.com/kubernetes/kube-state-metrics/issues/1037#issuecomment-723139173.

**Comment by ruckc** [comment]
still waiting for kube-state-metrics 2.0 to be GA, which will require an update for something as `--collectors` is an unknown flag when trying to run with 2.0.0-beta on arm64.

**Comment by eddiezane** [comment]
Some work in progress here https://github.com/kubernetes/kube-state-metrics/pull/1358

**Comment by cablespaghetti** [comment]
Kube-state-metrics 1.9.8 has been releases which now has multi-arch builds. I'll raise a PR. :) https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.8

**Comment by cablespaghetti** [comment]
Opened this PR on kube-state-metrics helm chart first: https://github.com/kubernetes/kube-state-metrics/pull/1391

**Comment by eddiezane** [comment]
@cablespaghetti it looks like the `grafana-sc-dashboard` sidecar image (quay.io/kiwigrid/k8s-sidecar:1.10.6) isn't multi arch?

```
pikube/kube-prometheus-stack[main ☂ ] kubectl -n monitoring logs kube-prometheus-stack-grafana-984c8bb67-jkhtz grafana-sc-datasources
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by disconn3ct** [comment]
Simple workaround for anyone that is stuck: the docker hub images are still multiarch.
```
sidecar.image.repository: kiwigrid/k8s-sidecar
```

**Comment by cablespaghetti** [comment]
You're correct. Sorry, this must have been changed on the grafana side, probably to avoid Docker hub rate limiting. I'll raise some more PRs...

**Comment by cablespaghetti** [comment]
Raised a PR to fix this in the kiwigrid/k8s-sidecar side: https://github.com/kiwigrid/k8s-sidecar/pull/112

**Comment by jekkel** [comment]
Hi there, thanks for making us aware, we fixed to quay.io mirror to be multi-arch as well and updated the existing tags accordingly. This means `quay.io/kiwigrid/k8s-sidecar:1.10.6` should just work now.
