### ISSUE TITLE
[kube-state-metrics] Support elastic agent sidecar

### ISSUE THREAD

**Issue by dominic-paul-92** [prometheus-community/helm-charts#3759]
### Is your feature request related to a problem ?

Currently the standalone elastic agent needs to be separately deployed to collect kube state metrics.
If auto sharding enabled for KSM, it is an overhead to deploy a scaled elastic agent to connect to multiple sharded KSM instance. A one to one mapping is required between the pods.

### Describe the solution you'd like.

If the standalone elastic agent can be deployed as a sidecar container, it will be easier to manage the deployment.

Something similar is suggested by [elastic](https://github.com/elastic/elastic-agent/tree/main/docs/manifests/kustomize-autosharding). But this introduce the overhead of using k8s [Kustomization](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#overview-of-kustomize) on top of helm chart.

Instead, it will be good to have an optional container in the helm chart of KSM, where a user can deploy elastic agent as a sidecar container.

### Describe alternatives you've considered.

NONE

**Comment by dotdc** [comment]
Should be fixed by https://github.com/prometheus-community/helm-charts/pull/3861
