### ISSUE TITLE
[kube-state-metrics] Allow setting verbosity during installation

### ISSUE THREAD

**Issue by kranurag7** [prometheus-community/helm-charts#3761]
### Is your feature request related to a problem ?

When working with kube-state-metrics and trying to fetch custom resources, there are a lot of things that can go wrong and not having the correct configuration for custom resources in one of them, which occurs very frequently. 

I would like to have the ability to set verbosity during the installation when dealing with custom resources. 

### Describe the solution you'd like.

Changes in `deployment.yaml` manifest
```diff
+ {{- if .Values.verbosity }}
+ - --v={{ default 0 .Values.verbosity }}
+ {{- end}}
```

changes in `values.yaml`
```diff
+ verbosity: 0
```

### Describe alternatives you've considered.

As of now, I've to start the pod and edit the deployment manifest using `kubectl edit` 

### Additional context.

If accepted, I'm happy to create a small patch for it. 
// kind ping cc @mrueg

**Comment by mrueg** [comment]
I don't think it will add a lot of value to template each config option, have you tried `.Values.extraArgs` ?

**Comment by kranurag7** [comment]
Thanks, Manuel, sticking to `extraArgs` sounds good to me. 
```yaml
extraArgs: ["--v=4"]
```
I'm going to close this issue as this is resolved now.
