### ISSUE TITLE
[kube-prometheus-stack] ServiceMonitor needs separate scheme parameters

### ISSUE THREAD

**Issue by tynsh** [prometheus-community/helm-charts#3802]
Hi,

currently the prometheus config reloader does not support https at the metrics endpoint. As both the config reloader and prometheus/alertmanager share the same scheme value, when activating https on the serviceMonitor scraping of will fail on the reloader container. This issue exists for the prometheus service monitor as well as the one for alertmanager. Here are the relevant lines for alertmanager:

https://github.com/prometheus-community/helm-charts/blob/723cfad365d5c55b84162d4a5f11294ea736ca54/charts/kube-
prometheus-stack/templates/alertmanager/servicemonitor.yaml#L57-L59

**Comment by n1kofr** [comment]
Facing the same issue for prometheus config reloader. Scrapping config-reloader is failing with wrong scheme issue as config-reloader ServiceMonitor is using the same scheme as prometheus.

[https://github.com/prometheus-community/helm-charts/blob/723cfad365d5c55b84162d4a5f11294ea736ca54/charts/kube-prometheus-stack/templates/prometheus/servicemonitor.yaml#L50-L52](https://github.com/prometheus-community/helm-charts/blob/723cfad365d5c55b84162d4a5f11294ea736ca54/charts/kube-prometheus-stack/templates/prometheus/servicemonitor.yaml#L50-L52)
