### ISSUE TITLE
[prometheus-snmp-exporter] migrate to quay.io/prometheus-operator/prometheus-config-reloader

### ISSUE THREAD

**Issue by freedge** [prometheus-community/helm-charts#3819]
### Is your feature request related to a problem ?

as in https://github.com/prometheus-community/helm-charts/issues/415, 

unlike the other charts that moved to quay.io/prometheus-operator/prometheus-config-reloader, snmp-exporter is still using jimmidyson/configmap-reload

### Describe the solution you'd like.

move to quay.io/prometheus-operator/prometheus-config-reloader

### Describe alternatives you've considered.

staying with the non official jimmidyson from docker.io

**Comment by walker-tom** [comment]
Thanks for the suggestion, looking at when this was done for the `prometheus` chart in https://github.com/prometheus-community/helm-charts/pull/3133, it shouldn't be too difficult to change. I'll look to get this changed or feel free to submit a PR for me to review.

**Comment by MohammadrezaTavakoli** [comment]
Hi @walker-tom,
I created a PR for this issue, please review.
This is my first issue 😄 please tell me if there is something that needs to change.

**Comment by walker-tom** [comment]
Fixed in #4304, thanks @MohammadrezaTavakoli!
