### ISSUE TITLE
[kube-prometheus-stack] Changing the node port of node-exporter

### ISSUE THREAD

**Issue by jaepetto** [prometheus-community/helm-charts#3827]
### Describe the bug a clear and concise description of what the bug is.

In order to apply "seggregation of concerns", we would like to deploy the kube-prometheus-stack twice in different namespaces.

Obviously, it does not work OoB because it causes a conflict while allocating node port 9100 to node-exporter.
Looking at the values of the chart, I did not find any option to change this port.

Is it possible?

### What's your helm version?

version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:16:45Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.2.0

### Enter the command that you execute and failing/misfunctioning.

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack \
    -n monitoring --create-namespace --set grafana.enabled=false
```

**Comment by QuiTran86** [comment]
You can edit service's port to the desired number in value.yml https://github.com/prometheus-community/helm-charts/blob/main/charts/promethe
![Screenshot from 2023-09-29 13-16-20](https://github.com/prometheus-community/helm-charts/assets/47933780/e130601a-bc95-41e6-9bb0-357cf8527ae0)
us-node-exporter/values.yaml

**Comment by jaepetto** [comment]
Thanks @QuiTran86
