### ISSUE TITLE
[prometheus-blackbox-exporter] Issue with extraInitContainers

### ISSUE THREAD

**Issue by maximebrun** [prometheus-community/helm-charts#3856]
### Describe the bug a clear and concise description of what the bug is.

Error running helm template with extra init container.

### What's your helm version?

v3.13.0

### What's your kubectl version?

v1.26.7

### Which chart?

prometheus-blackbox-exporter

### What's the chart version?

8.4.0

### What happened?

There is a an error running helm template with additional extraInitContainers :

``` bash
$ helm template .
Error: YAML parse error on prometheus-blackbox-exporter/templates/deployment.yaml: error converting YAML to JSON: yaml: line 37: block sequence entries are not allowed in this context
```

With debug flag, we see this result :

``` yaml
...
      initContainers:  - args:
          - echo "Fake..."
...
```

### What you expected to happen?

Template output whithout error.

### How to reproduce it?

run `helm template .`

### Enter the changed values of values.yaml?

extraInitContainers:
  - name: test
    image: prom/blackbox-exporter:v0.24.0
    command: ["/bin/sh", "-c"]
    args:
      - echo "Fake..."

### Enter the command that you execute and failing/misfunctioning.

helm template .

### Anything else we need to know?

Problem exist with extraInitContainers and extraContainers.

**Comment by zeritti** [comment]
#3850
