### ISSUE TITLE
[kube-prometheus-stack] thanos-ruler alertmanagerConfigSpec does not work

### ISSUE THREAD

**Issue by thameezb** [prometheus-community/helm-charts#3869]
### Describe the bug a clear and concise description of what the bug is.

As per https://github.com/prometheus-community/helm-charts/pull/2358#issuecomment-1750484024

The CRD expects a secret, the chart rather provides an entire config block

### What's your helm version?

version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}

### What's your kubectl version?

Client Version: v1.28.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.22.17-eks-2d98532 WARNING: version difference between client (1.28) and server (1.22) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

48.3.1

### What happened?

Helm throws error as it tries to use an array in place of a map when `thanosRuler.thanosRulerSpec.alertmanagersConfig` is set

### What you expected to happen?

Thanos Ruler CRD deployed with appropriate alertmanager config

### How to reproduce it?

Use the example config as per values https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3928

### Enter the command that you execute and failing/misfunctioning.

standard helm install command

**Comment by dragoangel** [comment]
@QuentinBisson this fix breaks existing setups for a people, please read my comment: https://github.com/prometheus-community/helm-charts/pull/3913#issuecomment-1769130571

**Comment by GMartinez-Sisti** [comment]
Replied on https://github.com/prometheus-community/helm-charts/pull/3913#issuecomment-1769134294. I’m on it.

**Comment by GMartinez-Sisti** [comment]
I was under the impression that this was not working so it wasn’t being used. Let’s keep the chat on this issue to make it easier to follow.

**Comment by dragoangel** [comment]
In short, it was working and used as:
```yaml
    alertmanagersConfig:
      name: thanos-monitoring-config
      key: alertmanagers.yml

    objectStorageConfig:
      name: thanos-monitoring-config
      key: objstore.yml

    queryConfig:
      name: thanos-monitoring-config
      key: query.yml
```

**Comment by thameezb** [comment]
> Yeah, in short, it was working and used as:
> 
> ```yaml
>     alertmanagersConfig:
>       name: thanos-monitoring-config
>       key: alertmanagers.yml
> 
>     objectStorageConfig:
>       name: thanos-monitoring-config
>       key: objstore.yml
> 
>     queryConfig:
>       name: thanos-monitoring-config
>       key: query.yml
> ```
> 
> allowing to get data from existing secret

Didn't mean to break existing capability with these changes. However the values file examples does not work with the previous methodology (therefore I had assumed the mapping was incorrect, not the example and proposed the changes).

Fully keen to have a flag that allows for usage of existing secrets, provided the option to create a secret (via values) is not removed

**Comment by dragoangel** [comment]
> > Yeah, in short, it was working and used as:
> > 
> > ```yaml
> >     alertmanagersConfig:
> >       name: thanos-monitoring-config
> >       key: alertmanagers.yml
> > 
> >     objectStorageConfig:
> >       name: thanos-monitoring-config
> >       key: objstore.yml
> > 
> >     queryConfig:
> >       name: thanos-monitoring-config
> >       key: query.yml
> > ```
> > 
> > allowing to get data from existing secret
> 
> Didn't mean to break existing capability with these changes. However the values file examples does not work with the previous methodology (therefore I had assumed the mapping was incorrect, not the example and proposed the changes).
> 
> Fully keen to have a flag that allows for usage of existing secrets, provided the option to create the appropriate secret (via values) is not removed 

I setup Thanos about to my kube-prometheus-stack half year ago and was checked how these values applied, and I did not have any issues with them.

**Comment by GMartinez-Sisti** [comment]
It happens @thameezb 😄 

If I get this right, something like this would work for both use cases:

```yaml
thanosRuler:
  thanosRulerSpec:
    objectStorageConfig:
      name: ""
      key: ""
    objectStorageSecret:
      create: false
      config: {}
```

when `thanosRuler.thanosRulerSpec.objectStorageSecret.create: false` (previous logic):
- on `charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml`
  - set `objectStorageConfig.key: thanosRuler.thanosRulerSpec.objectStorageConfig.key`
  - set `objectStorageConfig.name: thanosRuler.thanosRulerSpec.objectStorageConfig.name`

when `thanosRuler.thanosRulerSpec.objectStorageSecret.create: true`:
- on `charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml`
  - set `objectStorageConfig.key: object-storage-configs.yaml`
  - set `objectStorageConfig.name: {{ template "kube-prometheus-stack.thanosRuler.name" . }}`
- on `charts/kube-prometheus-stack/templates/thanos-ruler/secret.yaml`
  - add `object-storage-configs.yaml: {{ toYaml .Values.thanosRuler.thanosRulerSpec.objectStorageSecret.config | b64enc | quote }}`

Although `objectStorageSecret.config` is on the values file, it doesn't mean it will be configured as clear text, there are some tools that will integrate with this like `Sops` or `Values`, so we should allow it to be used.

WDYT @dragoangel @thameezb ?

**Comment by dragoangel** [comment]
Looks good to me @GMartinez-Sisti

**Comment by dragoangel** [comment]
If go with new values then better:
```yaml
thanosRuler:
  thanosRulerSpec:
    objectStorage:
      existingSecret:
        name: ""
        key: ""
      secret: {}
```

And if existingSecret is set then the secret is ignored. It will remove unnecessary enabled switch

**Comment by thameezb** [comment]
Will create a PR shortly

**Comment by dragoangel** [comment]
> Will create a PR shortly

Thank you 😊🙏, and need place nice comments in default values.yaml to remove in future any misunderstanding. I updated my previous comment with raw examples

**Comment by rouke-broersma** [comment]
The config is currently the same for all the thanos components available in the chart (also sidecar). I think this should remain so.

Would it not be more appropriate to revert the previous change and introduce a new `objectStorageConfigSecret` instead of introducing a hasty breaking change for new functionality that was implemented in the wrong way?

**Comment by GMartinez-Sisti** [comment]
> The config is currently the same for all the thanos components available in the chart (also sidecar). I think this should remain so.
> 
> Would it not be more appropriate to revert the previous change and introduce a new `objectStorageConfigSecret` instead of introducing a hasty breaking change for new functionality that was implemented in the wrong way?

That is what I suggest [here](https://github.com/prometheus-community/helm-charts/issues/3869#issuecomment-1769271171) (first yaml snippet) and I'm expecting the PR to be the revert and the new functionality all in one, instead of having two PRs for the same result.

**Comment by rouke-broersma** [comment]
> > The config is currently the same for all the thanos components available in the chart (also sidecar). I think this should remain so.
> > Would it not be more appropriate to revert the previous change and introduce a new `objectStorageConfigSecret` instead of introducing a hasty breaking change for new functionality that was implemented in the wrong way?
> 
> That is what I suggest [here](https://github.com/prometheus-community/helm-charts/issues/3869#issuecomment-1769271171) (first yaml snippet) and I'm expecting the PR to be the revert and the new functionality all in one, instead of having two PRs for the same result.

Yes but @dragoangel suggested a breaking change instead I think

**Comment by GMartinez-Sisti** [comment]
> Yes but @dragoangel suggested a breaking change instead I think, maybe I misunderstood.

You're right @rouke-broersma, there are two available solutions and one is a breaking change. While I prefer to avoid them too, as long as we document all the required steps in detail it shouldn't be an issue.

Giving it some more thought, I think it would be better to do the breaking change and fix it for good, using properly named variables and the simplest logic instead of trying to adapt an existing logic just to prevent the breaking change. The last suggestion from @dragoangel is clean and a common flow across other helm charts.

**Comment by dragoangel** [comment]
For me personally it doesn't matter if it will be revert and additional PR, or breaking change if things will work. It's up to you guys :)
