### ISSUE TITLE
[kube-prometheus-stack] node-exporter priorityClass not being applied

### ISSUE THREAD

**Issue by jaepetto** [prometheus-community/helm-charts#3875]
### Describe the bug a clear and concise description of what the bug is.

I'm trying to set a `priorityClass` to node-exporter through the use of the following values:
```
    --set alermanager.alertmanagerSpec.priorityClassName="system-cluster-critical"
    --set prometheus.prometheusSpec.priorityClassName="system-cluster-critical"
    --set prometheusOperator.admissionWebhooks.patch.priorityClassName="system-cluster-critical"
    --set prometheusOperator.priorityClassName="system-cluster-critical"
```

Unfortunately, the `priorityClass` does not get applied to the resulting pods.

### What's your helm version?

version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"darwin/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.4.0

### What happened?

When deploying the kube-prometheus-stack with Helm:
```
  helm install prometheus-community prometheus-community/kube-prometheus-stack \
    --namespace=monitoring \
    --create-namespace \
    --set alermanager.alertmanagerSpec.priorityClassName="system-cluster-critical" \
    --set grafana.enabled=true \
    --set prometheus.prometheusSpec.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.admissionWebhooks.patch.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.priorityClassName="system-cluster-critical"
```

no `priorityClass` gets applied to the node-exporter pods.

### What you expected to happen?

I expected the "system-cluster-critical" `priorityClass` to be applied to the node-exporter pods.

### How to reproduce it?

```
  helm install prometheus-community prometheus-community/kube-prometheus-stack \
    --namespace=monitoring \
    --create-namespace \
    --set alermanager.alertmanagerSpec.priorityClassName="system-cluster-critical" \
    --set grafana.enabled=true \
    --set prometheus.prometheusSpec.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.admissionWebhooks.patch.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.priorityClassName="system-cluster-critical"
```

### Enter the changed values of values.yaml?

alermanager.alertmanagerSpec.priorityClassName: "system-cluster-critical"
grafana.enabled: true
prometheus.prometheusSpec.priorityClassName: "system-cluster-critical"
prometheusOperator.admissionWebhooks.patch.priorityClassName: "system-cluster-critical"
set prometheusOperator.priorityClassName: "system-cluster-critical"

### Enter the command that you execute and failing/misfunctioning.

  helm install prometheus-community prometheus-community/kube-prometheus-stack \
    --namespace=monitoring \
    --create-namespace \
    --set alermanager.alertmanagerSpec.priorityClassName="system-cluster-critical" \
    --set grafana.enabled=true \
    --set prometheus.prometheusSpec.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.admissionWebhooks.patch.priorityClassName="system-cluster-critical" \
    --set prometheusOperator.priorityClassName="system-cluster-critical"

### Anything else we need to know?

AFAIK nothing

**Comment by zeritti** [comment]
The prometheus-node-exporter chart does not set a default priorityClassName - it has to be set as you do for other workloads above. As far as I can see, the chart sets the field in the daemonset manifest correctly if `prometheus-node-exporter.priorityClassName` is set to an existing class name. Setting the property is not seen in your command above, though.

**Comment by jaepetto** [comment]
@zeritti You are absolutely right. Adding `--set prometheus-node-exporter.priorityClassName="system-cluster-critical"` did the trick.
Thank you
