### ISSUE TITLE
[kube-stack-prometheus] CertManager integration

### ISSUE THREAD

**Issue by mrueg** [prometheus-community/helm-charts#388]
**Is your feature request related to a problem? Please describe.**
Currently setting up kube-stack-prometheus securely and enabling TLS everywhere requires a lot of manual intervention and set up for those.
**Describe the solution you'd like**
https://github.com/jetstack/cert-manager offers a CA Kubernetes pods can use and it gains wider adoption in other charts (e.g. https://github.com/sighupio/opa-helm-charts/blob/main/charts/opa/templates/webhookconfiguration.yaml#L40 ).
It uses CRDs to define the Certificates that need to be created and could be utilized e.g. for the prometheus-operator webhook (instead of the kube-webhook-certgen that is currently used) as well as to secure prometheus, alertmanager, etc. itself.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by kfox1111** [comment]
Big +1. I use it for both securing web services themselves and for k8s webhooks. Its nice when all of the webhooks use it so you get consistent debugging rather then each app doing their own thing.

**Comment by monotek** [comment]
Imho this should kept out of the monitoring charts and be configured separately.
