### ISSUE TITLE
[kube-prometheus-stack] Grafana dashboard for etcd broken

### ISSUE THREAD

**Issue by felixscheinost** [prometheus-community/helm-charts#3889]
### Describe the bug a clear and concise description of what the bug is.

Recent commit bdfef97dd9b62afc3a59bd412b80cdb9f3e2a791 broke the etcd Grafana dashboard.

The problem is that a variable that was previously named "cluster" was renamed to a name of "job" but there are still ocurrences of $cluster in the panels.

### What's your helm version?

irrelevant

### What's your kubectl version?

irrelevant

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.6.0

### What happened?

The Grafana dashboard for etcd has no data at all, as the not defined variable $cluster is used.

### What you expected to happen?

The Grafana dashboard should work.

### How to reproduce it?

Install the Grafana dashboards for etcd.

### Enter the changed values of values.yaml?

grafana:
   forceDeployDashboards: true

### Enter the command that you execute and failing/misfunctioning.

not applicable

**Comment by QuentinBisson** [comment]
Fix waiting for approval https://github.com/prometheus-community/helm-charts/pull/3917
