### ISSUE TITLE
[prometheus] Allow turning off automountServiceAccountToken

### ISSUE THREAD

**Issue by OmarHawk** [prometheus-community/helm-charts#3909]
### Is your feature request related to a problem ?

For security reasons, we are currently turning off automounting serviceAccountTokens by default in our deployments and if the Deployment really requires that, we put the corresponding mount manually into the requiring containers again. Unfortunately, this is not possible, as there is no option to provide this as part of the config values.

### Describe the solution you'd like.

Allow providing automountServiceAccountToken as config value for the ServiceAccount / Pod, while allowing to provide the necessary mounts / volumes manually (that 2nd part would be possible already)

### Describe alternatives you've considered.

NONE

### Additional context.

This is part of fixing a MS Defender for Cloud recommendation. "Kubernetes clusters should disable automounting API credentials"

**Comment by DrFaust92** [comment]
ill take a look
