### ISSUE TITLE
[kube-prometheus-stack] Grafana additional data source basicAuthPassword not picked up

### ISSUE THREAD

**Issue by malek-delphai** [prometheus-community/helm-charts#3921]
### Describe the bug a clear and concise description of what the bug is.

When adding Grafana [additionalDataSources](https://github.com/prometheus-community/helm-charts/blob/7d1bd03d93b2af5bfcb5dcea6b81ac3e37770f65/charts/kube-prometheus-stack/values.yaml#L1031), the sources are added and configured as expected once checked from the UI except for the `basicAuthPassword` which is not picked up at all (shown as empty/not configured in the data sources tab) which of course makes the connection to the data source (e.g., Prometheus) fail. Adding the password manually naturally solves it. Is there an explanation to this? 

### What's your helm version?

version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.21.3"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"7ffcdf755d47c73903854cc5955afcdcd8c95225", GitTreeState:"clean", BuildDate:"2023-10-09T14:43:34Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.9.4

### What happened?

[basicAuthPassword](https://github.com/prometheus-community/helm-charts/blob/7d1bd03d93b2af5bfcb5dcea6b81ac3e37770f65/charts/kube-prometheus-stack/values.yaml#L1031) is shown as empty/not configured in the data sources Grafana tab, but it shows up in the configuration inside the grafana datasources container

<img width="938" alt="Screenshot 2023-10-19 at 10 37 16" src="https://github.com/prometheus-community/helm-charts/assets/98817985/88c8ca3b-09f0-420b-acc1-7c166944f3f1">

### What you expected to happen?

Have the password picked up from `values.yaml`

### Enter the command that you execute and failing/misfunctioning.

`helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack -n monitoring --reuse-values -f monitoring/prom_values.yaml`

**Comment by zeritti** [comment]
> When adding Grafana [additionalDataSources](https://github.com/prometheus-community/helm-charts/blob/7d1bd03d93b2af5bfcb5dcea6b81ac3e37770f65/charts/kube-prometheus-stack/values.yaml#L1031), the sources are added and configured as expected once checked from the UI except for the basicAuthPassword which is not picked up at all (shown as empty/not configured in the data sources tab) which of course makes the connection to the data source (e.g., Prometheus) fail. Adding the password manually naturally solves it. Is there an explanation to this?

`basicAuthPassword` is expected in the `secureJsonData` field. Please, see [datasource config file](https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file) and [secureJsonData](https://grafana.com/docs/grafana/latest/administration/provisioning/#secure-json-data).

**Comment by riosje** [comment]
Thanks @zeritti it makes sense to use `secureJsonData` as you mentions and it works.
Any person could lead to this issue due to some wrong documentation in the `values.yaml` of the helm chart.
they propose to use the `basicAuthPassword` on top of the datasource object not within `secureJsonData` [see here the example](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-56.3.0/charts/kube-prometheus-stack/values.yaml#L1088)

Instead of that example it should be implemented like this
```yaml
  - name: prometheus-sample
     access: proxy
     basicAuth: true
     basicAuthUser: daco
     editable: false
     jsonData:
       tlsSkipVerify: true
     secureJsonData:
       basicAuthPassword: pass
     orgId: 1
     type: prometheus
     url: https://{{ printf "%s-prometheus.svc" .Release.Name }}:9090
     version: 1
```
