### ISSUE TITLE
[prometheus] Invalid type for pdb.maxUnavailable in schema

### ISSUE THREAD

**Issue by zerkms** [prometheus-community/helm-charts#3923]
### Describe the bug a clear and concise description of what the bug is.

Currently it's typed as `integer`:

https://github.com/prometheus-community/helm-charts/blob/8effa619e74aed1af123c25e11caeb7277782f3f/charts/prometheus/values.schema.json#L403

While kubernetes defines it as a string:

```
$ kubectl explain pdb.spec.maxUnavailable
KIND:     PodDisruptionBudget
VERSION:  policy/v1

FIELD:    maxUnavailable <string>

DESCRIPTION:
     An eviction is allowed if at most "maxUnavailable" pods selected by
     "selector" are unavailable after the eviction, i.e. even in absence of the
     evicted pod. For example, one can prevent all voluntary evictions by
     specifying 0. This is a mutually exclusive setting with "minAvailable".

     IntOrString is a type that can hold an int32 or a string. When used in JSON
     or YAML marshalling and unmarshalling, it produces or consumes the inner
     type. This allows you to have, for example, a JSON field that can accept a
     name or number.
```

It should be string because otherwise it's not possible  to specify the `100%` value.

### What's your helm version?

n/a

### What's your kubectl version?

n/a

### Which chart?

n/a

### What's the chart version?

n/a

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by DrFaust92** [comment]
ill take a look
