### ISSUE TITLE
[kube-prometheus-stack] CRD sync handling

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/helm-charts#3941]
Actually, I totally forgot that there are more moving parts regarding this:

- we use CRDs from [prometheus-operator-crds](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds) helm chart
- we run [charts/kube-prometheus-stack/hack/update_crds.sh](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/hack/update_crds.sh) to update it on this chart

This is going to be lost next time we run a sync if we don't do the right process now. Asking for help regarding this process to @jkroepke 🙏

_Originally posted by @GMartinez-Sisti in https://github.com/prometheus-community/helm-charts/issues/3938#issuecomment-1781914803_

**Comment by jkroepke** [comment]
@GMartinez-Sisti I would propose to add an additional CI check for kube-prometheus-stack here to ensure CRDs are fine. Do you think that this is sufficent?

**Comment by GMartinez-Sisti** [comment]
> @GMartinez-Sisti I would propose to add an additional CI check for kube-prometheus-stack here to ensure CRDs are fine. Do you think that this is sufficent?

That works, it's better to flag it right on the PR and block it from being merged.

**Comment by jcpunk** [comment]
With 0.69.0 just released this ticket popped up on my reports.
