### ISSUE TITLE
[kube-prometheus-stack] I can't install the kube-prometheus-stack

### ISSUE THREAD

**Issue by kay07** [prometheus-community/helm-charts#395]
**My Env:**
  Kubernetes:v1.18.0
  helm: v3.3.0
**According to the official method:**
  ` helm repo add prometheus-community https://prometheus-community.github.io/helm-charts`
  `helm repo add stable https://charts.helm.sh/stable`
  `helm repo update`
  `helm install kps prometheus-community/kube-prometheus-stack`
  
**I can't install it ,and I get an error:**
  Error: failed to download "prometheus-community/kube-prometheus-stack" (hint: running `helm repo update` may help)
**I think:**
  Maybe the method provided have not been updated for a long time,could anyone help me to solve it.Thanks in advance.

**Comment by kay07** [comment]
I see.This repo has no "kube-prometheus-stack" chart.

**Comment by scottrigby** [comment]
@kay07 it does.

Fresh test:

```console
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.18.2) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊

took 29s

$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
"prometheus-community" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "prometheus-community" chart repository
Update Complete. ⎈Happy Helming!⎈

took 2s

$ helm install kps prometheus-community/kube-prometheus-stack
NAME: kps
LAST DEPLOYED: Mon Nov 30 21:29:15 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
kube-prometheus-stack has been installed. Check its status by running:
  kubectl --namespace default get pods -l "release=kps"

Visit https://github.com/prometheus-operator/kube-prometheus for instructions on how to create & configure Alertmanager and Prometheus instances using the Operator.

took 47s

$ helm ls
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
kps 	default  	1       	2020-11-30 21:29:15.195738 -0500 EST	deployed	kube-prometheus-stack-12.3.0	0.43.2     
```

Are you able to install charts from other repositories?

**Comment by kay07** [comment]
@scottrigby 
It looks so strange.I use the same cmd but got the different result.
<img width="849" alt="1606810551(1)" src="https://user-images.githubusercontent.com/40294040/100714303-8ca93880-33f0-11eb-9ba7-bd9db7b053e6.png">

**Comment by kay07** [comment]
<img width="849" alt="1606810551(1)" src="https://user-images.githubusercontent.com/40294040/100714559-e447a400-33f0-11eb-8183-e14852d6adf4.png">

**Comment by kay07** [comment]
So strange.I can't install it.
![image](https://user-images.githubusercontent.com/40294040/100715773-a9467000-33f2-11eb-8b8e-72c34b5000fa.png)
There is another repo "https://charts.helm.sh/stable",but it was deprecated

**Comment by totoroot** [comment]
Check if you can pull the latest version from the repo. Don't use the deprecated one from stable and stick with the community chart.
```bash
helm pull prometheus-community/kube-prometheus-stack --version 12.2.3
```

If that works, try installing it from this local repo.
```bash
helm install test kube-prometheus-stack-12.2.3.tgz
```

**Comment by kay07** [comment]
@totoroot 
It seems impossible to achieve.My helm version is v3.3.3.
![image](https://user-images.githubusercontent.com/40294040/100813784-1271c600-347b-11eb-80ae-e585788183a7.png)

**Comment by kay07** [comment]
@scottrigby @totoroot 
I solved it.
First,removed the repo.
Second, add it  .
And then,I can use the repo.
Thanks all of you.
