### ISSUE TITLE
Prometheus Community: CI maintainers

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/helm-charts#3999]
Hi @prometheus-community/helm-charts-admins, @SuperQ 

I would like to discuss if there would be possible to have some CI maintainers/CODE owners.

Atm, each CI change need to be approved by helm-charts-admin which feels a limited factor. OpenSource is sometimes private time and I'm fine that not everyone of us have always the time for review or investigate PR/code review in this repository. 

I would like to discuss if it would be possible to make separate maintainer team for maintain the CI actions here. By default, the current admin team should be included some trusted community members are included as well, too.

This proposal should be reduce the load of the current helm-chart-admin team here.

**Comment by SuperQ** [comment]
Yea, I think it makes sense to add a CODEOWNERS entry for `/.github/workflows`.
