### ISSUE TITLE
[kube-prometheus-stack] Support `additionalArgs` on `thanosRulerSpec`

### ISSUE THREAD

**Issue by clux** [prometheus-community/helm-charts#4007]
### Is your feature request related to a problem ?

This is to primarily to allow enabling [stateless rulers via remote write](https://thanos.io/tip/components/rule.md/#stateless-ruler-via-remote-write) which currently uses `additionalArgs` to provide a remote write config.

Examples from issues show this can be done inline: https://github.com/prometheus-operator/prometheus-operator/issues/4451#issuecomment-1682373352

### Describe the solution you'd like.

Expose `additionalArgs` on `thanosRulerSpec` with the example from the linked issue.

Happy to try to send a PR.

### Describe alternatives you've considered.

none available yet afaikt. also good to be able to support this for any potential future features.

### Additional context.

Expected implementation location: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
ThanosRuler docs for the new field: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#thanosruler

**Comment by mattiasnensen** [comment]
I want this to be prioritized.

Best regards,
Mattias N.

**Comment by clux** [comment]
PR for this is on #4092. Reviews are appreciated 🙏
