### ISSUE TITLE
[kube-prometheus-stack] default rules for k8sContainerMemoryWorkingSetBytes are not enabled

### ISSUE THREAD

**Issue by FlorisFeddema** [prometheus-community/helm-charts#4056]
### Describe the bug a clear and concise description of what the bug is.

In version 54.2.0 the default k8s where split into multiple rules. 
However there is no default value for k8sContainerMemoryWorkingSetBytes added in the values.yaml so we lost this recording rule in the upgrade. This means the node_namespace_pod_container:container_memory_working_set_bytes metric does not exist anymore and our dashboards stopped working. 

To keep the same functionality it would be best to add a default for this in the helm chart. 

### What's your helm version?

v3.10.3

### What's your kubectl version?

v1.28.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

54.2.0

### What happened?

We updated from 54.1.x to 54.2.0 without changing the values and we noticed in one of our dashboard that the Memory usage was missing. After looking into it the node_namespace_pod_container:container_memory_working_set_bytes metric was not showing up anymore. 

### What you expected to happen?

No change in the default rules that are deployed. 

### How to reproduce it?

Upgrade to 54.2.0 without change the default rules. 

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

We use ArgoCD for our deployments, however any helm install with the default rules should work.

**Comment by cmitri-harris** [comment]
@GMartinez-Sisti this was introduced in https://github.com/prometheus-community/helm-charts/pull/3883.
k8sContainerMemoryWorkingSetBytes rule is missing [here](https://github.com/jkroepke/prometheus-community-helm-charts/blob/16219b723e20e41cdfdba3944434acea3c7033d2/charts/kube-prometheus-stack/values.yaml#L45C1-L50C22) & [here](https://github.com/jkroepke/prometheus-community-helm-charts/blob/16219b723e20e41cdfdba3944434acea3c7033d2/charts/kube-prometheus-stack/values.yaml#L98C1-L103C20) & [here](https://github.com/jkroepke/prometheus-community-helm-charts/blob/16219b723e20e41cdfdba3944434acea3c7033d2/charts/kube-prometheus-stack/values.yaml#L133C1-L138C20)

**Comment by cmitri-harris** [comment]
This was solved in https://github.com/prometheus-community/helm-charts/pull/4044
