### ISSUE TITLE
[kube-prometheus-stack] unable to update the grafana.ini via values.yaml

### ISSUE THREAD

**Issue by zrankinOCEUS** [prometheus-community/helm-charts#4061]
### Describe the bug a clear and concise description of what the bug is.

This is an issue reopening the following issue:

https://github.com/prometheus-community/helm-charts/issues/1337

I have followed a similar structure where within the "grafana:" label I added a grafana.ini section and auth.generic_oauth within the ini. 

`grafana:
    grafana.ini:
        auth.generic_oath:
            <oauth config>`

### What's your helm version?

3

### What's your kubectl version?

latest

### Which chart?

kube-prometheus-stack

### What's the chart version?

latest

### What happened?

Pulled the charts, added the grafana.ini tag and everything beneath it. 
Deployed charts within rancher, ssh'd into the worker that hosted the grafana instance, and saw that the grafana.ini file was still the default one. 

### What you expected to happen?

able to see grafana.ini updated

### How to reproduce it?

add a grafana.ini tag within grafana and you will not see any custom configuration added. 

### Enter the changed values of values.yaml?

see description

### Enter the command that you execute and failing/misfunctioning.

cat <path>/grafana.ini and saw the default configuration

**Comment by zeritti** [comment]
Checked and found the config map `RELEASE-grafana` getting rendered, created and mounted correctly with the defined contents. The resulting file `/etc/grafana/grafana.ini` in the `grafana` container is correct including custom modifications. So far, I cannot confirm the described behaviour.

Used a trivial customization (grafana chart 7.0.11 as in KPS 55.0.0): 

```yaml
grafana:
  grafana.ini:
    auth.generic_oauth:
      enabled: false
      name: OAuth
    analytics:
      check_for_updates: false
```

**Comment by zrankinOCEUS** [comment]
> Checked and found the config map `RELEASE-grafana` getting rendered, created and mounted correctly with the defined contents. The resulting file `/etc/grafana/grafana.ini` in the `grafana` container is correct including custom modifications. So far, I cannot confirm the described behaviour.
> 
> Used a trivial customization (grafana chart 7.0.11 as in KPS 55.0.0):
> 
> ```yaml
> grafana:
>   grafana.ini:
>     auth.generic_oauth:
>       enabled: false
>       name: OAuth
>     analytics:
>       check_for_updates: false
> ```

Ah, you are correct for this issue. My mistake was nesting grafana.ini within data as such:
`grafana:
    data:
        grafana.ini: |
            auth.generic_oauth:`
            
I am encountering a separate issue though, I'd like to update the [server] tag, but am unable to overwrite the existing config map configuration:
`2023-12-07T22:42:38.118555956Z Error: INSTALLATION FAILED: template: kube-prometheus-stack/charts/grafana/templates/deployment.yaml:36:28: executing "kube-prometheus-stack/charts/grafana/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: kube-prometheus-stack/charts/grafana/templates/configmap.yaml:20:45: executing "kube-prometheus-stack/charts/grafana/templates/configmap.yaml" at <"grafana.ini">: range can't iterate over server: `

**Comment by zeritti** [comment]
Closing as completed.
