### ISSUE TITLE
[prometheus-pushgateway] Support for hostAliases in PodSpec

### ISSUE THREAD

**Issue by Roymprog** [prometheus-community/helm-charts#4093]
### Is your feature request related to a problem ?

I'm looking for a way to add additional host entries to enable the sidecar container I'm running next to the `prometheus-pushgateway` to resolve some domains. I noticed various other charts provide support for it already e.g. [alertmanager](https://github.com/prometheus-community/helm-charts/blob/ef3fe76dbb88ce712eaae22e8e14a868d41df061/charts/alertmanager/values.schema.json#L398) and [prometheus](https://github.com/prometheus-community/helm-charts/blob/ef3fe76dbb88ce712eaae22e8e14a868d41df061/charts/prometheus/values.schema.json#L285).

### Describe the solution you'd like.

Support `hostAliases` in the [prometheus-pushgateway PodSpec](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/templates/_helpers.tpl#L117C48-L117C48).

### Describe alternatives you've considered.

None

**Comment by DrFaust92** [comment]
I can add this
