### ISSUE TITLE
[kube-prometheus-stack] Automatically assign a ClusterIP to alertmanager-operated service?

### ISSUE THREAD

**Issue by fmunteanu** [prometheus-community/helm-charts#4119]
### Describe the bug a clear and concise description of what the bug is.

Looking at the chart, [clusterIP](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L469) is an empty value for `alertmanager`. What is the correct way to automatically assign a `clusterIP` to that service, not hardcode it as value into chart? My goal is to expose the `alertmanager-operated` web interface through a LoadBalancer. I'm using k3s.

### What's your helm version?

v3.13.3

### What's your kubectl version?

v1.28.4+k3s2

### Which chart?

kube-prometheus-stack

### What's the chart version?

v55.5.1

### What happened?

N/A

### What you expected to happen?

N/A

### How to reproduce it?

N/A

### Enter the changed values of values.yaml?

        values:
          alertmanager:
            alertmanagerSpec:
              replicas: 2
              storage:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 5Gi
          grafana:
            admin:
              existingSecret: grafana-credentials
              passwordKey: password
              userKey: username
          kubeControllerManager:
            endpoints: '{{ k3s_server_ips }}'
          kubeEtcd:
            endpoints: '{{ k3s_server_ips }}'
          kubeProxy:
            endpoints: '{{ k3s_server_ips }}'
          kubeScheduler:
            endpoints: '{{ k3s_server_ips }}'
          prometheus:
            prometheusSpec:
              enableAdminAPI: true
              replicaExternalLabelName: replica
              serviceMonitorSelectorNilUsesHelmValues: false
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    storageClassName: longhorn
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 50Gi
          prometheus-node-exporter:
            resources:
              limits:
                cpu: 400m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 64Mi

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

N/A

**Comment by pescador691** [comment]
Having the same issue. +1 to follow the thread

**Comment by shafeequem** [comment]
Yes, I'm also facing the issue.
I have to modify the prometheus and change ‘type: ClusterIP’ to 'LoadBalancer' manually.

**Comment by shafeequem** [comment]
Hi @dpetersen @Bregor @redondos @jkroepke

**Comment by jkroepke** [comment]
If clusterIP is empty, Kubernetes auto-assign one.
