### ISSUE TITLE
[prometheus] Azure SD: targets not discovered

### ISSUE THREAD

**Issue by kulsinghdeep** [prometheus-community/helm-charts#4128]
### Describe the bug a clear and concise description of what the bug is.

Hi team 

while configuring prometheus via helm chart i am facing issue in service dsicovery on nodes on azure cloud outside the kubernets cluster.  

helm chart infomation - prometheus  prometheus-community/prometheus --version 25.4.0 

i am using below sd config under scrape config and when am applying it - 
in service discovery no new target found via name of vm-db-nodes, no logs in Prometheus pods, its look like azure cloud feature is not working, i had given proper role for monitoring to service principle but its not showing any result.

 - job_name: 'vm-db-nodes'
        azure_sd_configs:
          - environment: AzurePublicCloud
            tenant_id: "xxxx"
            client_id: "xxxxxx"
            client_secret: "xxxxx"
            resource_group: xxxx
            port: 9100
            subscription_id: xxxxxxxxxxxxxxx
        relabel_configs:    
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: private_ip
          - source_labels: [__meta_azure_machine_name]
            target_label: instance
          - source_labels: [__meta_azure_machine_tag_app]
            target_label: vm_tag_name
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: vm_ip

can you pls suggest solution for it or i am missing something

### What's your helm version?

v1.28.3

### What's your kubectl version?

v1.28.3

### Which chart?

prometheus-community/prometheus

### What's the chart version?

25.4.0 

### What happened?

while configuring prometheus via helm chart i am facing issue in service dsicovery on nodes on azure cloud outside the kubernets cluster.  

### What you expected to happen?

in service discovery a new target should appear

### How to reproduce it?

we can reproduce it using config 

 - job_name: 'vm-db-nodes'
        azure_sd_configs:
          - environment: AzurePublicCloud
            tenant_id: "xxxx"
            client_id: "xxxxxx"
            client_secret: "xxxxx"
            resource_group: xxxx
            port: 9100
            subscription_id: xxxxxxxxxxxxxxx
        relabel_configs:    
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: private_ip
          - source_labels: [__meta_azure_machine_name]
            target_label: instance
          - source_labels: [__meta_azure_machine_tag_app]
            target_label: vm_tag_name
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: vm_ip

### Enter the changed values of values.yaml?

 - job_name: 'vm-db-nodes'
        azure_sd_configs:
          - environment: AzurePublicCloud
            tenant_id: "xxxx"
            client_id: "xxxxxx"
            client_secret: "xxxxx"
            resource_group: xxxx
            port: 9100
            subscription_id: xxxxxxxxxxxxxxx
        relabel_configs:    
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: private_ip
          - source_labels: [__meta_azure_machine_name]
            target_label: instance
          - source_labels: [__meta_azure_machine_tag_app]
            target_label: vm_tag_name
          - source_labels: [__meta_azure_machine_private_ip]
            target_label: vm_ip

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install prometheus  prometheus-community/prometheus --version 25.4.0 -n  monitoring

**Comment by McHammar** [comment]
We also get this when we update over 53.x.x

What did you do to solve it? Something seems to happen to just azure_sd_config jobs.
