### ISSUE TITLE
Possible to keep a container for the configmap-reload in the prometheus-operator org on quay.io?

### ISSUE THREAD

**Issue by 4n3w** [prometheus-community/helm-charts#415]
Hey folks; I have a customer that isn't loving the idea of having the configmap-reload existing on dockerhub and not alongside the rest of the prometheus-operator containers on quay.io.

I totally get that jimmidyson's configmap-reload code is ubiquitous and used in countless deployments, and I'm curious if there's any chance of getting the container pushed out to the prometheus-operator org in quay.io -- it will reduce the questions from their security folks as it will at least appear to be all a common set of containers in a single org.

https://github.com/prometheus-community/helm-charts/blob/9abd1cfc61b9a3828c9d6909bf1fc7f755f0536d/charts/kube-prometheus-stack/values.yaml#L1423

**Comment by perezjasonr** [comment]
is this image still being used? I no longer see it accounted for in helm values file.
