### ISSUE TITLE
[prometheus-snmp-exporter] Extra maintainers

### ISSUE THREAD

**Issue by walker-tom** [prometheus-community/helm-charts#4158]
### Describe the bug a clear and concise description of what the bug is.

Hello,

The `prometheus-snmp-exporter` chart is a few versions behind [prometheus/snmp_exporter](https://github.com/prometheus/snmp_exporter) and there are multiple open PRs to update it that haven't been reviewed:

- #4086
- #4043
- #4020
- #3791 

The maintainers are down as @miouge1 and @xiu according to [CODEOWNERS](https://github.com/prometheus-community/helm-charts/blob/main/.github/CODEOWNERS) but there are errors for @miouge1 (suggesting they may not have write access), so it is just @xiu that gets added to PRs.

Are the maintainers open in having any additional maintainers help out? I would be happy to volunteer if so. Thanks!

### What's your helm version?

N/A

### What's your kubectl version?

N/A

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

N/A

### Enter the command that you execute and failing/misfunctioning.

N/A

**Comment by walker-tom** [comment]
@prometheus-community/helm-charts-admins apologies for the direct mention but are you able to help with this at all as mentioned in https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#review-process? Thanks in advance.

**Comment by xiu** [comment]
@walker-tom Absolutely! I have little time for it at the moment so having more people to help would be great!

**Comment by SuperQ** [comment]
I've invited @walker-tom to the @prometheus-community/helm-charts-maintainers team.

**Comment by caarlos0** [comment]
(Lock/unlock was a missclick, sorry)

**Comment by onedr0p** [comment]
Nice to see a maintainer on this, welcome @walker-tom 

_hint hint nudge nudge #4086_ 😆
