### ISSUE TITLE
[kube-prometheus-stack] Can't extract container images supplied through flags

### ISSUE THREAD

**Issue by blazs3fs** [prometheus-community/helm-charts#4161]
### Describe the bug a clear and concise description of what the bug is.

When trying to extract all container images used by `kube-prometheus-stack` when running `helm template` and grepping for `image:` images for

- `quay.io/prometheus-operator/prometheus-config-reloader`
- `quay.io/thanos/thanos`

get skipped since they're provided using flags and dynamically build with code.

I've also inspected the source of `articathub.io` and they're using a [similar method](https://github.com/artifacthub/hub/blob/e26403613dc1074661ef1c2f16bfceb18dc25c3e/internal/tracker/source/helm/helm.go#L72) to extract container images which means those two mentioned images are also missing from the **container images** dialog on the [site](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack).

Could you suggest a method for extracting the missing container images?

### What's your helm version?

version.BuildInfo{Version:"v3.13.3", GitCommit:"c8b948945e52abba22ff885446a1486cb5fd3474", GitTreeState:"clean", GoVersion:"go1.21.5"}

### What's your kubectl version?

Client Version: v1.29.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.27.4 WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1

### Which chart?

kube-prometheus-stack

### What's the chart version?

51.10.0

### How to reproduce it?

Create a demo file with partial k8s manifest.
```sh
$ cat <<'EOF' >> demo
spec:
  containers:
    - name: kube-prometheus-stack
      image: "quay.io/prometheus-operator/prometheus-operator:v0.68.0"
      imagePullPolicy: "IfNotPresent"
      args:
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.68.0
        - --thanos-default-base-image=quay.io/thanos/thanos:v0.32.4
EOF
```

Current approach of extracting container images
```sh
$ yq demo | grep 'image:'
        image: "quay.io/prometheus-operator/prometheus-operator:v0.68.0"
```

We geet only `prometheus-operator` but we also want `prometheus-config-reloader` and `thanos`.

A similar approach is used by [artifacthub.io](https://github.com/artifacthub/hub/blob/e26403613dc1074661ef1c2f16bfceb18dc25c3e/internal/tracker/source/helm/helm.go#L72) and has the same problem.

### Enter the command that you execute and failing/misfunctioning.

See **How to reproduce it?** section.

**Comment by jkroepke** [comment]
Thats a common issue with operators.

You could use the command `helm template | grep quay.io` to extract additional images.

**Comment by jkroepke** [comment]
No, because this would result into errors at the Deployment. Kubernetes would try to start the containers and fails then.

I create an upstream issue for this: https://github.com/artifacthub/hub/issues/3619

**Comment by jkroepke** [comment]
@blazs3fs https://github.com/artifacthub/hub/issues/3619

At the moment, there is no standardized way to define images, maybe https://github.com/nikhilsbhat/helm-images helps you.

**Comment by blazs3fs** [comment]
Thanks for your help. I'll try `helm-images` and report back if it solved my problem.

**Comment by blazs3fs** [comment]
I've tried `helm-images` but it did not solve my problem. The images supplied through `args` are still missing.

```sh
$ helm images get prometheus-community /tmp/kube-prometheus-stack -f /tmp/kube-prometheus-stack/values.yaml
quay.io/prometheus/node-exporter:v1.6.1
quay.io/kiwigrid/k8s-sidecar:1.25.1
quay.io/kiwigrid/k8s-sidecar:1.25.1
docker.io/grafana/grafana:10.1.5
registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.0
quay.io/prometheus-operator/prometheus-operator:v0.68.0
quay.io/prometheus/alertmanager:v0.26.0
quay.io/prometheus/prometheus:v2.47.1
docker.io/bats/bats:v1.4.1
registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
```
