### ISSUE TITLE
[kube-prometheus-stack] Prom Operator SA Missing Permissions

### ISSUE THREAD

**Issue by Daniel-Vaz** [prometheus-community/helm-charts#4173]
### Describe the bug a clear and concise description of what the bug is.

With Operator `v0.71.0` we get the following logs:

```
[pod/kps-operator-7cd5c97769-pplpm/kps] 2024-01-22T15:18:08.958826732+01:00 level=warn ts=2024-01-22T14:18:08.95863544Z caller=main.go:259 msg="missing permission to emit events" reason="missing \"create\" permission on resource \"events\" (group: \"\") for all namespaces"
[pod/kps-operator-7cd5c97769-pplpm/kps] 2024-01-22T15:18:08.958837184+01:00 level=warn ts=2024-01-22T14:18:08.958671375Z caller=main.go:259 msg="missing permission to emit events" reason="missing \"patch\" permission on resource \"events\" (group: \"\") for all namespaces"
```

### What's your helm version?

v3.13.1

### What's your kubectl version?

v1.29.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.0.3

### Enter the command that you execute and failing/misfunctioning.

Not applicable. 
Since the Operator SA permissions are hardcoded in the templates, no values would change this behaviour.

**Comment by DrFaust92** [comment]
Ill open a PR for this, i see its indeed add upstream in the operator https://github.com/prometheus-operator/prometheus-operator/blob/main/example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
