### ISSUE TITLE
[kube-prometheus-stack] prometheusOperator.admissionWebhooks.enabled=false fails

### ISSUE THREAD

**Issue by ansd** [prometheus-community/helm-charts#418]
**Describe the bug**
```console
helm install prom prometheus-community/kube-prometheus-stack \
  --set prometheusOperator.admissionWebhooks.enabled=false
```
results in 
```
pod/prom-kube-prometheus-stack-operator-869f7cfd69-2nfzr   0/1     ContainerCreating   0          2m14
```
and 
```
Warning  FailedMount  26s (x9 over 2m34s)  kubelet            MountVolume.SetUp failed for volume "tls-secret" : secret "prom-kube-prometheus-stack-admission" not found
```

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.10-gke.2101", GitCommit:"abb34dc6bb651ef0eb9d25d868a5a8b9001201ff", GitTreeState:"clean", BuildDate:"2020-11-06T18:24:35Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
kube-prometheus-stack

**Which version of the chart**:
12.2.3

**What happened**:
```console
> kubectl describe pod/prom-kube-prometheus-stack-operator-869f7cfd69-2nfzr
...
Volumes:
  tls-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prom-kube-prometheus-stack-admission
    Optional:    false
...
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m34s                default-scheduler  Successfully assigned default/prom-kube-prometheus-stack-operator-869f7cfd69-2nfzr to gke-lre-default-pool-8af3bc28-6mj6
  Warning  FailedMount  31s                  kubelet            Unable to attach or mount volumes: unmounted volumes=[tls-secret], unattached volumes=[prom-kube-prometheus-stack-operator-token-c52dz tls-secret]: timed out waiting for the condition
  Warning  FailedMount  26s (x9 over 2m34s)  kubelet            MountVolume.SetUp failed for volume "tls-secret" : secret "prom-kube-prometheus-stack-admission" not found
```

**What you expected to happen**:
Prometheus operator pod doesn't hang in status `ContainerCreating`.

**How to reproduce it** (as minimally and precisely as possible):
```console
helm install prom prometheus-community/kube-prometheus-stack \
  --set prometheusOperator.admissionWebhooks.enabled=false
```

**The helm command that you execute and failing/misfunctioning**:
same as previous command

**Helm values set after installation/upgrade:**

```console
> helm get values prom
USER-SUPPLIED VALUES:
prometheusOperator:
  admissionWebhooks:
    enabled: false
```

**Additional context:**
Might be related to https://github.com/prometheus-community/helm-charts/blob/021fa0ebae5b523493be99b951b5fd4738e2bb74/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L116-L122
However, the secret doesn't get created if `prometheusOperator.admissionWebhooks.enabled=false` is set.

**Comment by sentros** [comment]
I'm experiencing this exact same problem.

**Comment by jetersen** [comment]
according the lines below you need to add `prometheusOperator.tls.enabled`
https://github.com/prometheus-community/helm-charts/blob/63e0c0ef24c41a0849daf937c9db3995c16b52a5/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L118-L124

So this is required:
```yaml
prometheusOperator:
  tls:
    enabled: false
  admissionWebhooks:
    enabled: false
```

**Comment by alexppg** [comment]
Why this change? Why you suddenly need a tls secret?

**Comment by MythicManiac** [comment]
I'm having a hard time finding documentation on how are you supposed to configure the TLS in this chart, and as I'm not using helm for the installation, the steps described in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#how-the-chart-configures-the-hooks are not very useful.

As I understand it, I need a self signed certificate and CA. I however do not know where exactly are these supposed to be placed and in what format. The values.yaml file being 2.3k lines long and lack of documentation doesn't exactly help

**Comment by aariacarterweir** [comment]
> according the lines below you need to add `prometheusOperator.tls.enabled`
> https://github.com/prometheus-community/helm-charts/blob/63e0c0ef24c41a0849daf937c9db3995c16b52a5/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L118-L124
> 
> So this is required:
> 
> ```yaml
> prometheusOperator:
>   tls:
>     enabled: false
>   admissionWebhooks:
>     enabled: false
> ```

You're a legend. Saved me a headache. Docs should probably be updated for this?

**Comment by teochenglim** [comment]
it doesn't work for me on EKS. Any help is appreciate.

raise an issue at
https://github.com/prometheus-community/helm-charts/issues/661

**Comment by goshlanguage** [comment]
Just came across this as well, not sure what's supposed to be responsible for creating the secret. There isn't a template for it, but it's referenced here: 

https://github.com/prometheus-community/helm-charts/blob/29df8b9de95c258d35d4136d02b25158dc9b3d96/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L109-L119

Seems odd, the defaults should cause this to be immediately reproducible to anyone using the default chart I'd think?
https://github.com/prometheus-community/helm-charts/blob/29df8b9de95c258d35d4136d02b25158dc9b3d96/charts/kube-prometheus-stack/values.yaml#L1238-L1244

**Comment by goshlanguage** [comment]
On further inspection, I do have a secret in the namespace that ends in `-admission`.

```sh
k get secret -n monitoring | grep admission
prometheus-kube-prometheus-admission-sjbfk             Opaque                                1      150m
```

However it is being templated incorrectly, the secret is appended with whatever auto-populated text, where as the template scaffolds it out without referencing it directly. Here's the resulting operator spec scoped to the secret in question:
```
  volumes:
  - name: tls-secret
    secret:
      defaultMode: 420
      secretName: prometheus-kube-prometheus-admission
```

**Comment by teochenglim** [comment]
Guys.. most of this error come from upgrade I believe. Fresh install would just work. 

to solve them look at a few things like
1. Readme.md from the upgrade guide carefully.
2. delete all your CRD and recreate
3. admission webhook
4. all other resource created

it toke me sometime to migrate the helm chart from live instance because I can't delete it while the monitor are all running. manually modify one by one is a pain, but it is possible to do live migration.

**Comment by goshlanguage** [comment]
My error is from a fresh install, so I don't think that's the case.

**Comment by teochenglim** [comment]
opps. sorry I am using another chart called kube-prometheus-stack

**Comment by goshlanguage** [comment]
@teochenglim, you were right. I reinstalled without a values file and it worked as you suggested.

**Comment by RaceFPV** [comment]
This is still occuring for me on a fresh install with tls enabled set to false

`MountVolume.SetUp failed for volume "tls-secret" : secret "kube-prometheus-stack-admission" not found`

The admission secret is not being created either

**Comment by robertchen** [comment]
please reopen this issue, This is still occuring for me on a fresh install with tls enabled set to false

MountVolume.SetUp failed for volume "tls-secret" : secret "kube-prometheus-stack-admission" not found

The admission secret is not being created either

**Comment by vadimlungu** [comment]
```sh
helm --debug install -n monitoring -f custom-values.yaml  prometheus  --timeout 3m prometheus-community/kube-prometheus-stack  --set prometheusOperator.admissionWebhooks.enabled=true
```

```sh
k -n monitoring get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prometheus-kube-prometheus-alertmanager-0   2/2     Running   0          28m
prometheus-grafana-755d987f69-6w26x                      2/2     Running   0          28m
prometheus-kube-prometheus-operator-c6fd486cc-2g247      1/1     Running   0          28m
prometheus-kube-state-metrics-85c6d84f85-ml27n           1/1     Running   0          28m
prometheus-prometheus-kube-prometheus-prometheus-0       2/2     Running   0          28m
prometheus-prometheus-node-exporter-6b4mc                1/1     Running   0          28m
prometheus-prometheus-node-exporter-92t8t                0/1     Pending   0          28m
prometheus-prometheus-node-exporter-fkqzv                1/1     Running   0          28m
```

**Comment by Maelstromeous** [comment]
Just hit this on a fresh install, please reopen. Fix for me was the `tls.enabled: false` portion as described here: https://github.com/prometheus-community/helm-charts/issues/418#issuecomment-740578727

**Comment by Vsevosemnog** [comment]
Issue still occurs, is there any fix coming?

**Comment by valkiriaaquatica** [comment]
> Issue still occurs, is there any fix coming?

Same here with latest version 62.7.0 , trying with argcd and values file returns error, but trying without it as: `helm install monitoring prometheus-community/kube-prometheus-stack --namespace monitoring`  there is no error

**Comment by julian-perge** [comment]
For anyone else who came to this issue and running into a similar error in AWS EKS, if you're using a fips compliant AMI for your cluster, the default `VersionTLS13` may not be supported.

We're currently using EKS 1.31 version, ami ID `ami-08c59b428bf5f7648`, and I had to set `prometheusOperator.tls.tlsMinVersion` to `VersionTLS12` in order for the operator pod to come up healthy.

Version `69.2.4` of the kube-prometheus-stack helm chart.
