### ISSUE TITLE
[prometheus-node-exporter] upgrade failed: unclosed action

### ISSUE THREAD

**Issue by dongxiaosong** [prometheus-community/helm-charts#4206]
### Describe the bug a clear and concise description of what the bug is.

Error: UPGRADE FAILED: parse error at (kube-prometheus-stack/charts/prometheus-node-exporter/templates/daemonset.yaml:164): unclosed action

### What's your helm version?

3.2.2

### What's your kubectl version?

1.27.7

### Which chart?

prometheus-node-exporter

### What's the chart version?

4.26.1

### Enter the command that you execute and failing/misfunctioning.

helm -n monitoring \
    upgrade monitoring \
    prometheus-community/kube-prometheus-stack \
    --cleanup-on-fail \
    -f base.yml \
    -f prometheus.yml \
    -f alertmanager.yml \
    -f rules.yml \
    -f thanos-sidecar.yml

**Comment by zeritti** [comment]
The error can be reproduced with helm 3.2.2 (GoVersion:"go1.13.12"). Please, upgrade your helm binary to a more recent release.

**Comment by ktestbee44** [comment]
Hello, I have helm version 3.5.2 and getting the same error. 
`Error: parse error at (kube-prometheus-stack/charts/prometheus-node-exporter/templates/daemonset.yaml:179): unclosed action

version.BuildInfo{Version:"v3.5.2"
`
