### ISSUE TITLE
[kube-prometheus-stack] Unable to install in different namespace other than default in openshift

### ISSUE THREAD

**Issue by samyak335** [prometheus-community/helm-charts#4207]
### Describe the bug a clear and concise description of what the bug is.

While trying helm install command
 helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug 
 ,the command is being struck and eventually  timed out. Deploying kube-prometheus stack in different namespace other than default causing this issue in openshift. Even changed security context in values.yaml as shown below according to namespace uid, gid.
 
securityContext:
      runAsGroup: 1000700000
      runAsNonRoot: true
      runAsUser: 1000700000
      fsGroup: 1000700000
      seccompProfile:
        type: RuntimeDefault
 
 Got the below timeout installation failed .

C:\Users\t\.crc\bin\oc>helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: C:\Users\~1.KAL\AppData\Local\Temp\helm\repository\kube-prometheus-stack-55.7.1.tgz

client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagerconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD probes.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusagents.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD scrapeconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ServiceAccount
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRole
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" Role
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" RoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission-create" Job
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job prometheus-kube-prometheus-admission-create with timeout of 5m0s
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: ADDED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: MODIFIED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Release prometheus has been cancelled.
Error: INSTALLATION FAILED: context canceled
helm.go:84: [debug] context canceled
INSTALLATION FAILED

### What's your helm version?

v3.14.0-rc.1

### What's your kubectl version?

openshift version  : 4.14.7

### Which chart?

kube-prometheus-stack

### What's the chart version?

55.7.1

### What happened?

When trying to install kube-prometheus-stack in different namespace other than default on openshift , observing installation failed and struck .

C:\Users\t\.crc\bin\oc>helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: C:\Users\~1.KAL\AppData\Local\Temp\helm\repository\kube-prometheus-stack-55.7.1.tgz

client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagerconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD alertmanagers.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD podmonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD probes.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusagents.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheuses.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD prometheusrules.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD scrapeconfigs.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD servicemonitors.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
install.go:168: [debug] CRD thanosrulers.monitoring.coreos.com is already present. Skipping.
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ServiceAccount
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRole
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" ClusterRoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" Role
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission" RoleBinding
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:486: [debug] Starting delete for "prometheus-kube-prometheus-admission-create" Job
wait.go:66: [debug] beginning wait for 1 resources to be deleted with timeout of 5m0s
client.go:142: [debug] creating 1 resource(s)
client.go:712: [debug] Watching for changes to Job prometheus-kube-prometheus-admission-create with timeout of 5m0s
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: ADDED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for prometheus-kube-prometheus-admission-create: MODIFIED
client.go:779: [debug] prometheus-kube-prometheus-admission-create: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
Release prometheus has been cancelled.
Error: INSTALLATION FAILED: context canceled
helm.go:84: [debug] context canceled
INSTALLATION FAILED

### What you expected to happen?

I expect using below command , kube-prometheus-stack should be in installed in any namespace.

bin\oc>helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug

### How to reproduce it?

create a different namespace in openshift cluster , and try to run/install kube-prometheus-stack in that namespace .

bin\oc>helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug

### Enter the changed values of values.yaml?

securityContext:
      runAsGroup: 1000700000
      runAsNonRoot: true
      runAsUser: 1000700000
      fsGroup: 1000700000
      seccompProfile:
        type: RuntimeDefault

### Enter the command that you execute and failing/misfunctioning.

helm install -f values.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace --wait --debug

### Anything else we need to know?

Even after changing the security context in values.yaml according to the uid,gid of the namespace , which i got from describe namespace as shown below, still failing to install kube-prometheus-stack.

Name:         monitoring
Labels:       kubernetes.io/metadata.name=monitoring
              name=monitoring
              pod-security.kubernetes.io/audit=restricted
              pod-security.kubernetes.io/audit-version=v1.24
              pod-security.kubernetes.io/warn=restricted
              pod-security.kubernetes.io/warn-version=v1.24
Annotations:  openshift.io/sa.scc.mcs: s0:c26,c25
              openshift.io/sa.scc.supplemental-groups: 1000700000/10000
              openshift.io/sa.scc.uid-range: 1000700000/10000
Status:       Active

**Comment by zeritti** [comment]
> When trying to install kube-prometheus-stack in different namespace other than default on openshift , observing installation failed and struck .

This is because [SCC](https://docs.openshift.com/container-platform/4.14/authentication/managing-security-context-constraints.html)s do not apply in the _default_ namespace. In user-created namespaces, you have to consider the impact of the applicable SCC on the settings permitted in `securityContext`. Without specifying a SCC, SCC _restricted_/_restricted-v2_ apply. Note that the restricted SCC will not be enough for running Node Exporter.

Please, refer to the [documentation](https://docs.openshift.com/container-platform/4.14/authentication/managing-security-context-constraints.html) and adjust your security context settings. You can get started by unsetting containers' and pods' `securityContext` entirely whilst relying on the _restricted_ SCC wherever this is sufficient. Furthermore, review events in your namespace - you'll likey get more info.

**Comment by samyak335** [comment]
With correct uid/gid of namespace in the values.yaml i was able to deploy the chart, but i do observe warning for node-exporter and its not deployed as shown below, and i was not able to find any specific security context defined for node-exporter in values.yaml. I have referred https://docs.openshift.com/container-platform/4.14/authentication/managing-security-context-constraints.html , i see specifically for prometheus we have an node-exporter SCC , but  noted as cautious.



bin\oc>helm install -f prometheusvalues.yaml prometheus prometheus-community/kube-prometheus-stack --namespace monitoring

W0210 21:41:47.453295   23620 warnings.go:70] would violate PodSecurity "restricted:v1.24": host namespaces (hostNetwork=true, hostPID=true), hostPort (container "node-exporter" uses hostPort 9100), allowPrivilegeEscalation != false (container "node-exporter" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "node-exporter" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volumes "proc", "sys", "root" use restricted volume type "hostPath"), seccompProfile (pod or container "node-exporter" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")


NAME: prometheus
LAST DEPLOYED: Sat Feb 10 21:41:36 2024
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None

bin\oc>oc get pods -n monitoring
NAME                                                   READY   STATUS    RESTARTS   AGE
prometheus-kube-prometheus-operator-68969b9c99-qd8pp   1/1     Running   0          17s
prometheus-prometheus-kube-prometheus-prometheus-0     1/2     Running   0          13s

**Comment by zeritti** [comment]
> but i do observe warning for node-exporter and its not deployed as shown below, and i was not able to find any specific security context defined for node-exporter in values.yaml

You can specify only those security context parameters that are allowed by the applying SCC. For Node exporter, you will need to set SCC _node-exporter_ if you wish to use full exporter's functionality to provide host's metrics (something that typically cluster owners/operators want) - it requires certain privileges to achieve that such as access to _hostPID_, _hostNetwork_, _rootfs_, _proc_ and _sys_ volumes (all this is set by default in the _prometheus-node-exporter_ chart, access to _proc_ and _sys_ volumes is not optional).

**Comment by samyak335** [comment]
I have added custom scc with high priority as shown below , but i still get the warning , what i observed in events is that it is still some how using default value user/group value 65534 while creating node exporter/kube-state-metric pods, but in my  values.yaml, i have changed everything to user/group 1000700000 range according to the namespace as shown in below events.

**events:**
0s          Warning   FailedCreate             daemonset/prometheus-prometheus-node-exporter                  Error creating: pods "prometheus-prometheus-node-exporter-" is forbidden: unable to validate against any security context constraint: [provider "custom-scc": Forbidden: not usable by user or serviceaccount, provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{65534}: 65534 is not an allowed group, provider restricted-v2: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used, spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65534: must be in the ranges: [1000700000, 1000709999], provider restricted-v2: .containers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[0].containers[0].hostPort: Invalid value: 9100: Host ports are not allowed to be used, provider restricted-v2: .containers[0].hostPID: Invalid value: true: Host PID is not allowed to be used, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "hostpath-provisioner": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]


**warn:**

W0211 18:07:26.891963   10484 warnings.go:70] would violate PodSecurity "restricted:v1.24": host namespaces (hostNetwork=true, hostPID=true), hostPort (container "node-exporter" uses hostPort 9100), allowPrivilegeEscalation != false (container "node-exporter" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "node-exporter" must set securityContext.capabilities.drop=["ALL"]), restricted volume types (volumes "proc", "sys", "root" use restricted volume type "hostPath"), seccompProfile (pod or container "node-exporter" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

**custom security context constraint:**

`kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: custom-scc
allowHostNetwork: true
allowHostPID: true
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowedHostPaths:
  - pathPrefix: "/proc"
    readOnly: true
  - pathPrefix: "/sys"
    readOnly: true
  - pathPrefix: "/root"
    readOnly: true
allowHostPorts: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
priority: 11`

**Comment by samyak335** [comment]
I have created a custom SCC and assigned it to the required service accounts. when installing, in the events i do see the warnings , as shown below.
 It is only working/installing with out any issue when i add "privileged" SCC to the required  Service accounts .

**commands**
oc adm  policy add-scc-to-user  privileged -z prometheus-prometheus-node-exporter   -n monitoring
oc adm  policy add-scc-to-user  privileged -z prometheus-kube-state-metrics   -n monitoring


**SCC:**

kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: custom-scc
allowHostNetwork: true
allowHostPID: true
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
allowedHostPaths:
  - pathPrefix: "/proc"
    readOnly: true
  - pathPrefix: "/sys"
    readOnly: true
  - pathPrefix: "/root"
    readOnly: true
allowHostPorts: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:openshift-monitoring:default
  - system:serviceaccount:openshift-monitoring:prometheus-prometheus-node-exporter
  - system:serviceaccount:openshift-monitoring:prometheus-kube-state-metrics
priority: 11

**Warnings:**

2m50s       Warning   FailedCreate        daemonset/prometheus-prometheus-node-exporter                  Error creating: pods "prometheus-prometheus-node-exporter-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used, provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{65534}: 65534 is not an allowed group, provider restricted-v2: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used, provider restricted-v2: .containers[0].runAsUser: Invalid value: 65534: must be in the ranges: [1000660000, 1000669999], provider restricted-v2: .containers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted-v2: .containers[0].containers[0].hostPort: Invalid value: 9100: Host ports are not allowed to be used, provider restricted-v2: .containers[0].hostPID: Invalid value: true: Host PID is not allowed to be used, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{65534}: 65534 is not an allowed group, provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used, provider restricted: .containers[0].runAsUser: Invalid value: 65534: must be in the ranges: [1000660000, 1000669999], provider restricted: .containers[0].hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted: .containers[0].containers[0].hostPort: Invalid value: 9100: Host ports are not allowed to be used, provider restricted: .containers[0].hostPID: Invalid value: true: Host PID is not allowed to be used, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "hostpath-provisioner": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

**Comment by zeritti** [comment]
Your custom SCC does not look right. It should be similar to the node-exporter SCC in your cluster, i.e. [node-exporter](https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/security-context-constraints.yaml) at cluster-monitoring-operator. The [SCC API](https://docs.openshift.com/container-platform/4.14/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html) does not support `allowedHostPaths`.

**Comment by samyak335** [comment]
Thankyou , reference links helped a lot to resolve this issue.
