### ISSUE TITLE
[prometheus-community/prometheus] strategy: type: leads to unhealthy deployment.

### ISSUE THREAD

**Issue by abedunkevich** [prometheus-community/helm-charts#421]
We use prometheus-community/prometheus chart to deploy Prometheus server, and it works with persistent volume for the purpose of historical data to survive pod replacement.

After every small config change applied (e.g. retention time 1d->5d), Prometheus deployment renders unhealthy: There are 2 pods and latter restarts continuously. This is because the  update strategy is first launch new, then terminate old, while with persistent volume having 2 pods accessing same volume is impossible.

The solution desired:
 to be able to set in manifest
```
strategy:
  type: Recreate
```

I think that it applies as well to other components which use persistent volume.

**Comment by monotek** [comment]
Could you mind to create a pr please?

**Comment by zhujik** [comment]
@abedunkevich you can already set this value:
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L144
I think that this value should be the default though.

**Comment by abedunkevich** [comment]
Let me comment. I see that helm chart can be downloaded, customized locally, and used then.
Just i use it in it's simplest form so far. Something like that:
```
    helm upgrade --install prometheus prometheus-community/prometheus \
        --namespace prometheus \
        --set server.retention="3d" \
        --set server.persistentVolume.size="8Gi"
```
This is probably supported way of use.
So i wanted arguments there to solve those problems i suppose not only i might encounter.
One is setting correct strategy with persistent storage. Another is setting retention by data amount not only by time passed.

I am rather new to coding, so not very fast to me to prepare such merge (or pull?) request.

**Comment by fert-f** [comment]
@abedunkevich, you are not alone. You can use that code to override helm values:
```
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm upgrade --install prometheus prometheus-community/prometheus \
        --namespace prometheus \
        --set server.retention="3d" \
        --set server.persistentVolume.size="8Gi" \
        --set server.strategy.type="Recreate" \
        --set alertmanager.strategy.type="Recreate"
```

**Comment by mcallaghan-geotab** [comment]
(can we re-open) - I agree with the sentiment of this issue;
Given that the default for `prometheus-server` and `prometheus-alertmanager` will be leveraging PVC (persistent volume mounts), the _default_ strategy here of "rolling update" is broken - because new pods CANNOT claim the volume while it is already mounted by the previous deployment.

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

`alertmanager`

```
  persistentVolume:
    ## If true, alertmanager will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

  ## Alertmanager Deployment Strategy type
  # strategy:
  #   type: Recreate
```

`server`

```
  persistentVolume:
    ## If true, Prometheus server will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

  ## Server Deployment Strategy type
  # strategy:
  #   type: Recreate
```
