### ISSUE TITLE
[prometheus] Bad reference to configmapReload.prometheus.extraConfigmapMounts on sts.yaml

### ISSUE THREAD

**Issue by tomasrojas26** [prometheus-community/helm-charts#4215]
Hi there,

I'm running Prometheus on StatefulSet mode and I need to include some **extraVolumeMounts** on configmap-reload container, but sts.yaml makes reference to **extraConfigmapMounts**, so this feature is not available.

I managed to solve my requirement with a sidecar container, but it would be better if this can be managed by an existing container.

[This is the line](https://github.com/prometheus-community/helm-charts/blob/b4364470f84653145323c18796278c585609bf74/charts/prometheus/templates/sts.yaml#L322) that have to be changed:

**From:**
```yaml
      {{- range .Values.configmapReload.prometheus.extraConfigmapMounts }}
```

**To:**
```yaml
      {{- range .Values.configmapReload.prometheus.extraVolumeMounts }}
```

Thanks in advance.

**Comment by zeritti** [comment]
In fact, `configmapReload.prometheus.extraConfigmapMounts` is handled twice in `spec.template.spec.volumes` in both deploy.yaml and sts.yaml (L322, L340).

A the same time, as reported above, `configmapReload.prometheus.extraVolumeMounts` is not implemented in `spec.template.spec.containers[0].volumeMounts` in sts.yaml and needs to be added. The suggested fix will not be sufficient.

**Comment by Sheikh-Abubaker** [comment]
> A the same time, as reported above, `configmapReload.prometheus.extraVolumeMounts` is not implemented in `spec.template.spec.containers[0].volumeMounts` in sts.yaml and needs to be added. The suggested fix will not be sufficient.

please checkout the latest changes.
