### ISSUE TITLE
[prometheus-community/prometheus] storage.tsdb.retention.size= option is not implemented

### ISSUE THREAD

**Issue by abedunkevich** [prometheus-community/helm-charts#422]
In order to control of how much space Prometheus data may take (to prevent persistent volume to get full and server gets stopped), Prometheus have 2 options: retention time and retention size:
[https://prometheus.io/docs/prometheus/latest/storage/](https://prometheus.io/docs/prometheus/latest/storage/)
```
--storage.tsdb.retention.time=
--storage.tsdb.retention.size=
```
Both options are important, as soon as volume of data stored daily may vary wildly per grid size and workload.

In Helm chart, the first option is supported (`--set server.retention=`)
While the second option is not implemented at all.

Desired solution:
To have Helm chart option equivalent to `--storage.tsdb.retention.size=`

**Comment by monotek** [comment]
You can add any additional argument you want via: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L621

Retention time can be set via: 

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L967
