### ISSUE TITLE
[kube-prometheus-stack] Prometheus / Overview dashboard no data

### ISSUE THREAD

**Issue by zhoutong12589** [prometheus-community/helm-charts#4221]
### Describe the bug a clear and concise description of what the bug is.

Prometheus / Overview Dashboard is empty.
Data was found in prometheus, but dashboard is empty.

### What's your helm version?

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.14", GitCommit:"0018fa8af8ffaff22f36d3bd86289753ca61da81", GitTreeState:"clean", BuildDate:"2023-05-17T16:21:16Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.6.0

### What happened?

new installed via helm -> no data in Prometheus / Overview Dashboard.

### What you expected to happen?

Prometheus / Overview Dashboard shows data.

### How to reproduce it?

1. new install via helm
2. start Grafana
3. open Dashboard Grafana Overview

### Enter the changed values of values.yaml?

alertmanager:
  enabled: false
grafana:
    persistence:
    enabled: true
    type: sts
    storageClassName: "nfs-client"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
 
  service:
    portName: http-web
    type: LoadBalancer

prometheus:
    storageSpec:
    ## Using PersistentVolumeClaim
    ##
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

### Enter the command that you execute and failing/misfunctioning.

helm install --namespace monitoring kube-prometheus-stack  prometheus-community/kube-prometheus-stack -f kube-prometheus-stack.yaml

### Anything else we need to know?

I find metric "prometheus_target_sync_length_seconds_sum" include label "cluster", but that label was not exist in prometheus, and for Variables of "Prometheus / Overview" dashboard, "cluster" variable was not able to get values,
because filter "job" was fixed as "promethesu-k8s".
![Snip20240203_1](https://github.com/prometheus-community/helm-charts/assets/5142946/be9d1564-7760-4554-8104-d86edf89215d)
![Snip20240203_2](https://github.com/prometheus-community/helm-charts/assets/5142946/2a1ed1cc-15e5-4213-9939-27d466e8a560)
![Snip20240203_4](https://github.com/prometheus-community/helm-charts/assets/5142946/bf0d8488-163a-4b0c-a29c-d8df829e2bf6)
![Snip20240203_3](https://github.com/prometheus-community/helm-charts/assets/5142946/b3121d5f-e193-438e-a550-4e96ba3db65c)
![Snip20240203_6](https://github.com/prometheus-community/helm-charts/assets/5142946/b072b91c-a287-4dd1-a02c-a639e71cf17e)
![Snip20240203_5](https://github.com/prometheus-community/helm-charts/assets/5142946/63d58a8e-ac95-45de-bf4d-83d59257802e)

**Comment by y1100101s** [comment]
I have the same issue
56.1.0 version

**Comment by svparamzin** [comment]
I have the same issue
56.6.2 version

**Comment by freedrikp** [comment]
I'm seeing the same thing on 56.6.2 as well.

In this case it looks like the metrics are there in Prometheus and looks more like an issue with the dashboard.

In the dashboard there is a `cluster` dashboard variable that looks odd:

`label_values(prometheus_build_info{job="prometheus-k8s",namespace="monitoring"}, cluster)`

1. The job and namespace labels are hard-coded to values that may not match the actual setup. For example I have: ` job="prometheus-kube-prometheus-prometheus", namespace="prometheus"`.
2. I don't see any cluster label at all in My Prometheus instance when querying for `prometheus_build_info`.

If I manually tweak the dashboard and remove the `cluster` variable from the dashboard and all graphs I can get it working.

**Comment by omenv** [comment]
I have the same issue
56.13.0 version

**Comment by svparamzin** [comment]
Enter the changed values of values.yaml

prometheus:
  serviceMonitor:
    relabelings:
      - targetLabel: cluster
        replacement: 'cluster_name'

It's worked for me

**Comment by mrclrchtr** [comment]
@svparamzin thank you! It's working.

**Comment by ba-work** [comment]
looks like this broke in this commit: https://github.com/prometheus-community/helm-charts/commit/20f22df45471ad92d782a0ec4b6a725c8223fa0c. thats the first time this `cluster` label was added to the default query. 

It took a while to track down where it comes from but the issue is the `cluster` label added by this PR: https://github.com/prometheus/prometheus/pull/13180
