### ISSUE TITLE
[kube-prometheus-stack] Update steps for older versions

### ISSUE THREAD

**Issue by C4tWithShell** [prometheus-community/helm-charts#4235]
Hey, I a planning to update my deployed kube-prometgeus-stack. It's a quite outdated. But it's not clear from the Readme - should I update it one by one version, applying crd breaking changes. Or can I update it from 40 to 53 directly with latest crd changes?

**Comment by GMartinez-Sisti** [comment]
Hi @C4tWithShell, it's always best to update one version at a time, we can not ensure compatibility between two major versions that are not sequential. Also sometimes there are some components that change and need to be updated manually, these changes are reflected on the upgrade steps so increasing one by one is safer.
