### ISSUE TITLE
[kube-prometheus-stack] kube_state_metrics_list_total metrics are not exported

### ISSUE THREAD

**Issue by dbluxo** [prometheus-community/helm-charts#424]
**Describe the bug**

The `kube_state_metrics_list_total` and `kube_state_metrics_watch_total` metrics are missing. The are needed for the predefined Prometheus alerts `KubeStateMetricsListErrors` and `KubeStateMetricsWatchErrors`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

Kubernetes Version:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 12.2.3

**What happened**: Missing `kube_state_metrics_list_total` and `kube_state_metrics_watch_total` metrics.

**What you expected to happen**: Present `kube_state_metrics_list_total` and `kube_state_metrics_watch_total` metrics.

**How to reproduce it** (as minimally and precisely as possible):

Install kube-prometheus-stack Helm Chart with default values.

**Comment by TheKangaroo** [comment]
This is still an issue with kube-prometheus-stack 16.0.0 (kube-state-metrics v2.0.x)
kube-state-metrics does not include such a metric:
```
curl master-kube-state-metrics:8080/metrics|grep kube_state_metrics_watch_total
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2600k    0 2600k    0     0  18.2M      0 --:--:-- --:--:-- --:--:-- 18.2M
bash-5.1#
```
