### ISSUE TITLE
[kube-prometheus-stack] Enable cluster variable from start - k8s-prom-stack 46.4.2 - v.065.1

### ISSUE THREAD

**Issue by sojjan1337** [prometheus-community/helm-charts#4242]
### Is your feature request related to a problem ?
NO

Is there a global way for me to enable the "cluster-variable" by default? So it shows in the drop down menu. I don't want to enable it one by one. Can i enable this by code in the grafana helm-chart file? By default it is set to "Nothing"
So when i deploy it, all of the dashboard will have this set to = "Label and value".

<img width="286" alt="default" src="https://github.com/prometheus-community/helm-charts/assets/44612734/dc9f3700-b13c-4634-a214-7b5bafc0d2d6">

Using the kube-prom-stack.

### Describe the solution you'd like.

I would like to showing the cluster variable by start for all dashboards.

### Describe alternatives you've considered.

Do i need to do the change in grafana for all dashboards and then export the dashboards?
Then i guess i can send them in again through the API. OR with the grafana-helm-chart.

**Comment by dsiperek-vendavo** [comment]
This is something that would be very useful for us also.

**Comment by jkroepke** [comment]
Enable multicluster values to enable the cluster variable:

https://github.com/prometheus-community/helm-charts/blob/742559fb1e54d9da08e23fde2b51e126b92c656d/charts/kube-prometheus-stack/values.yaml#L1043-L1047
