### ISSUE TITLE
[prometheus] Allow User to Configure ConfigMap Metadata Annotation

### ISSUE THREAD

**Issue by clavinjune** [prometheus-community/helm-charts#4243]
### Is your feature request related to a problem ?

I want to be able to customize prometheus ConfigMap Metadata Annotation

https://github.com/prometheus-community/helm-charts/blob/e4588e35952ebccedd028bcdcdc7dacf4720ba91/charts/prometheus/templates/cm.yaml#L4-L11

### Describe the solution you'd like.

similar to https://github.com/prometheus-community/helm-charts/blob/e4588e35952ebccedd028bcdcdc7dacf4720ba91/charts/prometheus/templates/deploy.yaml#L5-L7

### Describe alternatives you've considered.

or we can just use the `.Values.server.deploymentAnnotations` for the ConfigMap also

### Additional context.

For additional Context, I want to be able to put this

```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
```

reference: https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#server-side-apply

i'll be more than happy to contribute on this issue

mentioning codeowner:
@gianrubio @naseemkullah @Xtigyro @zanhsieh @zeritti

**Comment by zanhsieh** [comment]
@clavinjune 
Please do. Thank you.

**Comment by clavinjune** [comment]
could you please assign this issue to me @zanhsieh? thank you
