### ISSUE TITLE
[kube-prometheus-stack] kubernetes-mixin dashboards links do not work anymore

### ISSUE THREAD

**Issue by FlorisFeddema** [prometheus-community/helm-charts#4255]
### Describe the bug a clear and concise description of what the bug is.

When using the kubernetes-mixin dashboads the links to more in-depth dashboard do not work.
For example if I open the _Kubernetes / Compute Resources / Workload_ dashboard and click on one of the rows in the _CPU Quota_ table it links to another dashboard. However the url of this dashboard does not seem to be working.

These are the parameters I end up with:
![image](https://github.com/prometheus-community/helm-charts/assets/19294266/0e38678f-2f6a-4d7c-b8d4-368616de0d00)

### What's your helm version?

v3.10.3

### What's your kubectl version?

v1.28.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.6.2

### What happened?

Went to the _Kubernetes / Compute Resources / Workload_ dashboard and clicked on one of the rows in the _CPU Quota_ table. The newly opened page does not have the correct paramters.

### What you expected to happen?

The newly opened page to use the parameters of the tablerow to fill in the next dashboard parameters.

### How to reproduce it?

Deploy kube prometheus stack with grafana and the dashboards.
Navigate to the Kubernetes / Compute Resources / Workload dashboard and click on one of the rows in the CPU Quota table.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

The install worked.

**Comment by fctb** [comment]
Click on pod name (drill down) forward not the pod name. The url is: `&var-pod=${__value.text}`

**Comment by FlorisFeddema** [comment]
I tried some things and I could not get the links working with the new vars indeed. 

The links result in the following data fields:
![image](https://github.com/prometheus-community/helm-charts/assets/19294266/30cec229-53d3-4b7b-8ca6-008e741bb09f)

**Comment by jkroepke** [comment]
Thats strange. I implement this, because the old table panel wont work with the old variables.

However I have multiple grafana instances, where is issues does not appear. Currently, I'm at 10.3.3, but it worked with 10.2.x.

For any reasons. Grafana always to an automatic migration of the table panel. Seems like this is not the case on your site.

Could you please generate an json export?

<img width="814" alt="image" src="https://github.com/prometheus-community/helm-charts/assets/1560587/a40cdd80-5e01-471b-b01d-4b6b173e7f63">

**Comment by FlorisFeddema** [comment]
Here is the export of our dashboard. We have about 30 environments where we run Grafana and they all have the same problem.
I have also deleted the pvc and recreated the grafana instance.
[Kubernetes _ Compute Resources _ Workload-1708936097167.json](https://github.com/prometheus-community/helm-charts/files/14401708/Kubernetes._.Compute.Resources._.Workload-1708936097167.json)

**Comment by jkroepke** [comment]
If you are try to edit the table panal, does Grafana offer the migration?

**Comment by FlorisFeddema** [comment]
I have deployed it on one of our test instances and after disabling the angular support flag in the grafana config it automatically migrated the tables to the new one!

**Comment by pierreozoux** [comment]
@jkroepke we think we have the same issue on the node dashboard.

we attached a PR to this bug report:
https://github.com/prometheus-community/helm-charts/issues/4828

Did you modify upstream https://github.com/kubernetes-monitoring/kubernetes-mixin repo, or just here?
We'd like to submit a proper PR, but are a bit lost to be honest :) If you could this would be nice!

Thanks for your help!
