### ISSUE TITLE
[prometheus-pushgateway] pod prometheus-pushgateway label not match NOTES display post install

### ISSUE THREAD

**Issue by zhoutong12589** [prometheus-community/helm-charts#4265]
### Describe the bug a clear and concise description of what the bug is.

After install prometheus-pushgateway without change any of configure file, I follow the note trying to get POD_NAME variable, but not resource.

--- Display content:
NAME: prometheus-pushgateway
LAST DEPLOYED: Sun Feb 18 05:23:20 2024
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace monitoring -l "app=prometheus-pushgateway,release=prometheus-pushgateway" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:9091 to use your application"
  kubectl port-forward $POD_NAME 9091

--- run kubectl get 
root@net65-host1:~/prometheus-pushgateway# kubectl get pods --namespace monitoring -l "app=prometheus-pushgateway,release=prometheus-pushgateway"
No resources found in monitoring namespace.

### What's your helm version?

version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.18.9"}

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:21:34Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v5.0.1 Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.6", GitCommit:"741c8db18a52787d734cbe4795f0b4ad860906d6", GitTreeState:"clean", BuildDate:"2023-09-13T09:14:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

prometheus-pushgateway

### What's the chart version?

2.6.0

### What happened?

run POD_NAME=$(kubectl get pods --namespace monitoring -l "app=prometheus-pushgateway,release=prometheus-pushgateway" -o jsonpath="{.items[0].metadata.name}")

but no pods was found.

### What you expected to happen?

Found the pushgateway pod.

### How to reproduce it?

Fresh install.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-pushgateway --namespace monitoring prometheus-community/prometheus-pushgateway -f prometheus-pushgateway.yaml

### Anything else we need to know?

I describe pushgateway pod, I believe pushgateway pod has it's own label not "app=prometheus-pushgateway,release=prometheus-pushgateway"

`root@net65-host1:~/prometheus-pushgateway# kubectl get pods --namespace monitoring 
NAME                                                        READY   STATUS    RESTARTS   AGE
kube-prometheus-stack-grafana-0                             3/3     Running   0          41h
kube-prometheus-stack-kube-state-metrics-6c6954ccd8-rmnqm   1/1     Running   0          46h
kube-prometheus-stack-operator-58f8fbcbd4-p5l4c             1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-5wrtf        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-7pwpn        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-dcd9x        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-fpsm5        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-mt2l2        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-nr9gm        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-svlqr        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-wqw9x        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-wsvns        1/1     Running   0          46h
kube-prometheus-stack-prometheus-node-exporter-ww2gk        1/1     Running   0          46h
prometheus-kube-prometheus-stack-prometheus-0               2/2     Running   0          161m
prometheus-pushgateway-7bc894b878-sf7nb                     1/1     Running   0          60s

root@net65-host1:~/prometheus-pushgateway# kubectl describe -n monitoring pod prometheus-pushgateway-7bc894b878-sf7nb 
Name:             prometheus-pushgateway-7bc894b878-sf7nb
Namespace:        monitoring
Priority:         0
Service Account:  prometheus-pushgateway
Node:             net65-host12.cdc.veritas.com/10.188.65.12
Start Time:       Sun, 18 Feb 2024 04:52:02 +0000
Labels:           app.kubernetes.io/instance=prometheus-pushgateway
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=prometheus-pushgateway
                  app.kubernetes.io/version=v1.7.0
                  helm.sh/chart=prometheus-pushgateway-2.6.0
                  pod-template-hash=7bc894b878
Annotations:      <none>
Status:           Running
IP:               10.244.9.19
IPs:
  IP:           10.244.9.19
Controlled By:  ReplicaSet/prometheus-pushgateway-7bc894b878`

**Comment by zeritti** [comment]
NOTES.txt has not obviously been updated after labels were changed in release [2.0](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway#to-200):
`app` became `app.kubernetes.io/name` and `release` became `app.kubernetes.io/instance`. The POD_NAME variable should be written

```shell
POD_NAME=$(kubectl get pods --namespace {{ .Release.Namespace }} \
-l "app.kubernetes.io/name={{ template "prometheus-pushgateway.name" . }},\
app.kubernetes.io/instance={{ .Release.Name }}" \
-o jsonpath="{.items[0].metadata.name}")
```

Furthermore, lines 17 and 18 should really be swapped and namespace set via helper template _prometheus-pushgateway.namespace_.
