### ISSUE TITLE
[kube-prometheus-stack] Grafana chart version 7.3.2 breaks k8s-sidecar

### ISSUE THREAD

**Issue by siretart** [prometheus-community/helm-charts#4288]
### Describe the bug a clear and concise description of what the bug is.

Grafana fails to start up

### What's your helm version?

version.BuildInfo{Version:"v3.11.3", GitCommit:"323249351482b3bbfc9f5004f65d400aa70f9ae7", GitTreeState:"clean", GoVersion:"go1.20.3"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.6+k3s2", GitCommit:"c9f49a3b06cd7ebe793f8cc1dcd0293168e743d9", GitTreeState:"clean", BuildDate:"2024-02-06T01:58:54Z", GoVersion:"go1.20.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

grafana

### What's the chart version?

7.3.2

### What happened?

see https://github.com/grafana/helm-charts/issues/2986

### What you expected to happen?

grafana to start

### How to reproduce it?

deploy with default config

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

see https://github.com/grafana/helm-charts/issues/2986

### Workaround

Pinning grafana to 7.3.1 allows the pods to come up

**Comment by Sheikh-Abubaker** [comment]
Already opened a PR (https://github.com/grafana/helm-charts/pull/2987) for the above issue.
