### ISSUE TITLE
[prometheus-kube-stack] Upgrading from helm chart prometheus-operator@9.3.2

### ISSUE THREAD

**Issue by elsbrock** [prometheus-community/helm-charts#429]
**Describe the bug**

Hi!

I am trying to follow up on the helm chart prometheus-operator deprecation. We have been using prometheus-operator@9.3.2 so far.

I noticed the deprecation while I was trying to upgrade our existing release; looks like 9.3.2 has been removed in the meantime:

```
helm3 dep up
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "prometheus-community" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading prometheus-operator from repo https://kubernetes-charts.storage.googleapis.com
Save error occurred:  could not download https://charts.helm.sh/stable/prometheus-operator-9.3.2.tgz: failed to fetch https://charts.helm.sh/stable/prometheus-operator-9.3.2.tgz : 404 Not Found
Deleting newly downloaded charts, restoring pre-update state
Error: could not download https://charts.helm.sh/stable/prometheus-operator-9.3.2.tgz: failed to fetch https://charts.helm.sh/stable/prometheus-operator-9.3.2.tgz : 404 Not Found
```

I am aware this is not your decision, but IMO it is kind of unfortunate that I am now unable to update my chart.

Anyhow, I see the benefits of moving to the updated version and was trying to figure out how to do it. I found out the closest version maintained in this repo is kube-prometheus-stack@9.3.4. Upgrading our existing deployment to anything newer seems too risky to me.

What I noticed is that there are no volumes created anymore; as far as I got the Github issues it seems like an intentional change. But I am lacking the big picture here:

* What does it mean in general - where does Prometheus/Alertmanager then store its data? Are you just writing to the underlying host? Can this be documented?
* While there are a few comments regarding upgrading, I did not really manage to understand what I am now supposed to do with my existing volumes. How do I get them reattached into the new installation?
* What other things changed? Can I still import dashboards? Any notable configuration parameter renames? Anything I need to look out for?

Any way/intention to make this more smooth for people coming from the deprecated helm chart, or is this not really on the roadmap, and we should just reinstall instead? That would mean we will loose all of our metrics data I guess?

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm3 version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.13-gke.1400", GitCommit:"00c919adfe4adf308bcd7c02838f2a1b60482f02", GitTreeState:"clean", BuildDate:"2020-10-28T09:22:18Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: `kube-prometheus-stack`

**Which version of the chart**: 9.3.4

**What happened**: Trying to upgrade from deprecated prometheus-operator chart, noticed volumes are missing.

**What you expected to happen**: I can upgrade to 9.3.4 without losing my data (🙏 )

**Anything else we need to know**:

Hope you don't misunderstand me - I am aware people are maintaining this in their spare time and I am thankful for this; but I just hoped there was a way to upgrade to this chart while retaining my data.

**Comment by scottrigby** [comment]
Hi @elsbrock 👋 

1. You can still run the old prometheus-operator version 9.3.2 from this repo - all prometheus chart package history from stable has been imported here: https://github.com/prometheus-community/helm-charts/pull/146
2. When you are ready to upgrade, several community members have written a migration guide from stable/prometheus-operator to kube-prometheus-stack, here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#migrating-from-stableprometheus-operator-chart

Does that help?

**Comment by elsbrock** [comment]
Thank you! I was not aware existing charts have been imported, and probably did not find them because I was looking for a tag starting with `kube-prometheus` 🙂 – that helps a lot.

Regarding your second link, does that apply to e.g. 9.3.4 too, or only to newer versions? What confused me is that when I ran `helm3 upgrade --dry-run --debug` I did not find PVs or PVCs for the alertmanager and prometheus itself. When I started investigating, I had the impression that these are not being used anymore. The link you provided though says that everything is compatible. Is that the case for that version too?

Thanks again for your help!

**Comment by scottrigby** [comment]
@elsbrock How are your PVCs configured now? You should be able to see your settings with `helm get values RELEASE_NAME [flags]`. I don't personally have much experience using `prometheus.prometheusSpec.storageSpec` which is why others needed to write the migration guide (and yet others tested and verified it before we merged it to the readme). I would recommend trying to follow the guide in non-production, and see where that lands you. If you do find a use case that isn't covered by the guide, please do file an issue, or even consider making a pull request to update it. And please let us know here how it turned out for you either way. Thanks!

**Comment by JohnMops** [comment]
> Hi @elsbrock 👋
> 
> 1. You can still run the old prometheus-operator version 9.3.2 from this repo - all prometheus chart package history from stable has been imported here: #146
> 2. When you are ready to upgrade, several community members have written a migration guide from stable/prometheus-operator to kube-prometheus-stack, here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#migrating-from-stableprometheus-operator-chart
> 
> Does that help?

From the guide with no downtime I get the error of: 

`Error: UPGRADE FAILED: template: kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml:12:16: executing "kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml" at <.Values.prometheusOperator.tls.enabled>: nil pointer evaluating interface {}.enabled
helm.go:81: [debug] template: kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml:12:16: executing "kube-prometheus-stack/templates/prometheus-operator/servicemonitor.yaml" at <.Values.prometheusOperator.tls.enabled>: nil pointer evaluating interface {}.enabled
UPGRADE FAILED`

**Comment by elsbrock** [comment]
Looks like you will need to set `prometheusOperator.tls`.

On my side, I have yet to try it out.

**Comment by ianks** [comment]
Ran into the same issue here. Is the `--reuse-values` flag neccesary?
