### ISSUE TITLE
[kube-prometheus-stack] Grafana Dashboards Contain Soon-to-Be-Deprecated Panels

### ISSUE THREAD

**Issue by tadeha** [prometheus-community/helm-charts#4308]
### Is your feature request related to a problem ?

Grafana dashboards located in the "charts/kube-prometheus-stack/templates/grafana/dashboards-1.14" directory contain panels utilizing the `Graph (old)` type, which rely on a plugin set to be deprecated in upcoming Grafana releases. Further details can be found here: [Link](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/)

![SCR-20240227-nxto](https://github.com/prometheus-community/helm-charts/assets/22890731/e7f4df5c-7f7b-4142-84a4-d70cc5bbf8b9)

### Describe the solution you'd like.

According to the documentation provided [here](https://grafana.com/docs/grafana/latest/developers/angular_deprecation/angular-plugins/#automatic-migration-of-plugins), it's recommended to migrate the panel types to `Time Series`.

### Describe alternatives you've considered.

NONE

### Additional context.

The panels can be located in the code by searching for `"type":"graph"`.

**Comment by ArtemGontar** [comment]
Is anyone working on update it in kube-promethues stack helm chart?

**Comment by jkroepke** [comment]
duplicate of https://github.com/prometheus-community/helm-charts/issues/4380 - follow the conversation there.
