### ISSUE TITLE
[prometheus-snmp-exporter] Add optional auth section PR broke the chart

### ISSUE THREAD

**Issue by kevinastone** [prometheus-community/helm-charts#4315]
### Describe the bug a clear and concise description of what the bug is.

As commented on PR #4020, the reference to the default value of `$.Values.serviceMonitor.auth` pulls in an array, but the assignment is expecting a single array element.  This breaks the chart without an explicit auth for each `param` since by default it applies an auth array as a single element.

### What's your helm version?

version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

### What's your kubectl version?

Client Version: v1.29.2 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.1

### Which chart?

prometheus-snmp-exporter

### What's the chart version?

3.1.0

### What happened?

This change seems to be broken in the default case where you don't specify an auth in the `params[*]`.  It's attempting to apply the default `$.Values.serviceMonitor.auth` (which is an array, defaulting to `[public_v2]`) to a single item in the array:

```
      auth:
      - {{ .auth | default $.Values.serviceMonitor.auth }}
```

 So it's ending up being:
 ```
    auth:
    - [public_v2]
```

Here's the error from my HelmRelease install:

```
ServiceMonitor.monitoring.coreos.com "snmp-exporter-prometheus-snmp-exporter-<target1>" is invalid: spec.endpoints[0].params.auth[0]: Invalid value: "array": spec.endpoints[0].params.auth[0] in body must be of type string: "array" && cannot patch "snmp-exporter-prometheus-snmp-exporter-<target2>" with kind ServiceMonitor: ServiceMonitor.monitoring.coreos.com "snmp-exporter-prometheus-snmp-exporter-<target2>" is invalid: spec.endpoints[0].params.auth[0]: Invalid value: "array": spec.endpoints[0].params.auth[0] in body must be of type string: "array"
````

### Enter the changed values of values.yaml?

serviceMonitor:
  enabled: true
  namespace: prometheus
  params:
    - name: target
      target: target.localdomain
      module: [synology]
  selfMonitor:
    enabled: true

### Enter the command that you execute and failing/misfunctioning.

(Helm is run by fluxcd's controller in my setup, so this is simulated)

```
helm upgrade --install prometheus-snmp-exporter prometheus-community/prometheus-snmp-exporter
```

**Comment by walker-tom** [comment]
Thanks for highlighting this @kevinastone, do you want to PR the fix of removing the `-` from inside the `ServiceMonitor` so instead it is:

```
auth: {{ .auth | default $.Values.serviceMonitor.auth }}
```
This should resolve it because then you don't have the double array? I can get that reviewed and merged today then.

**Comment by kevinastone** [comment]
Sure, posted #4316 for your review.
