### ISSUE TITLE
[prometheus-kube-stack]How to modify the following parameters of tsdb ?

### ISSUE THREAD

**Issue by owedocker** [prometheus-community/helm-charts#434]
--storage.tsdb.min-block-duration=2h
--storage.tsdb.max-block-duration=2h

**Comment by monotek** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L1672

**Comment by rmendal** [comment]
Also had this issue. This was the fix, https://github.com/prometheus-operator/prometheus-operator/issues/3725#issuecomment-741820940
