### ISSUE TITLE
[kube-prometheus-stack] Can't install via HELM due to validation errors with Alertmanager

### ISSUE THREAD

**Issue by shodanwashere** [prometheus-community/helm-charts#4348]
### Describe the bug a clear and concise description of what the bug is.

Can't do a basic install (without custom values) of the prometheus stack via HELM. I want a simple install that I can port forward Grafana from just to check that everything is working properly, but I get this error message when trying to install:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "automountServiceAccountToken" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec.securityContext): unknown field "seccompProfile" in com.coreos.monitoring.v1.Alertmanager.spec.securityContext]
```

This is some sort of probelm with Alertmanager, but i've tried using a values file with just
```
alertmanager:
  enabled: false
```
and it doesn't work either.

### What's your helm version?

version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}

### What's your kubectl version?

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"} Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-5e0fdde", GitCommit:"462fb841c09eeed8cb38ba5ee9adf967ef6b56ab", GitTreeState:"clean", BuildDate:"2024-01-02T20:38:19Z", GoVersion:"go1.19.13", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

kube-prometheus-stack

### What's the chart version?

56.21.3

### What happened?

Helm install fails with the following error message:

```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigNamespaceSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "alertmanagerConfigSelector" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec): unknown field "automountServiceAccountToken" in com.coreos.monitoring.v1.Alertmanager.spec, ValidationError(Alertmanager.spec.securityContext): unknown field "seccompProfile" in com.coreos.monitoring.v1.Alertmanager.spec.securityContext]
```

### What you expected to happen?

The install to go through with no problems.

### How to reproduce it?

Try to install the kube-prometheus-stack chart on a new namespace called `monitoring`.

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring --create-namespace

**Comment by shodanwashere** [comment]
Thanks for the tip, @zeritti. Indeed, it seems there are Prometheus operator CRDs, but I don't see any past prometheus installs...
Are all those CRDs following the naming `*.monitoring.coreos.com`? Are they used by the k8s-metrics-server? If not, I can try removing them and see if the Helm chart will install that way.

**Comment by zeritti** [comment]
> Are all those CRDs following the naming *.monitoring.coreos.com?

Yes, that is correct.

> Are they used by the k8s-metrics-server?

No, they are not.

You can check whether any corresponding CRs are present for each CRD before removing them, e.g.

```bash
kubectl get alertmanagerconfigs,alertmanagers,podmonitors,probes,prometheuses,servicemonitors \
  --all-namespaces
```

or per specific namespace, e.g.
```bash
kubectl get alertmanagerconfigs,alertmanagers,podmonitors,probes,prometheuses,servicemonitors \
  -n monitoring
```

If there are none, it should be safe to remove them.

**Comment by shodanwashere** [comment]
Ok, I can confirm that the old CRDs were causing issues. After removing them, I could install Prometheus with no problems.

Thanks for all your help!

**Solution**:
```
$ for i in `kubectl get crd | grep monitoring.coreos.com`; do kubectl delete crd $i; done
$ helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
```
