### ISSUE TITLE
[kube-prometheus-stack] node:node_cpu_utilization:ratio_rate5m recording rule doesn't seem to work

### ISSUE THREAD

**Issue by mhamzahkhan** [prometheus-community/helm-charts#4360]
Apologise if I'm missing something, but the recording rule for node:node_cpu_utilization:ratio_rate5m doesn't seem to work.

It expects the "node" label on the node_cpu_seconds_total metric, but that label doesn't seem to be present (at least not on the stock installation of kube-prometheus-stack).

https://github.com/prometheus-community/helm-charts/blob/7453a0ae1010297f4c556d9becf1705ca56e14b5/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/node.rules.yaml#L80

Should this use the instance label instead?

**Comment by jkroepke** [comment]
Source: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/a1c276d7a46c4b06fa5d8b4a64441939d398efe5/rules/node.libsonnet#L57-L64

We are just embed https://github.com/kubernetes-monitoring/kubernetes-mixin Any issues around the rules should be reported upstream. 

Sorry.
