### ISSUE TITLE
[kube-state-metrics] missing chart for v2.11.0 supporting k8s 1.28

### ISSUE THREAD

**Issue by grigoni** [prometheus-community/helm-charts#4378]
### Describe the bug a clear and concise description of what the bug is.

missing chart for latest ksm app release v2.11.0 supporting k8s 1.28

### What's your helm version?

3.13.2

### What's your kubectl version?

1.29.1

### Which chart?

kube-state-metrics

### What's the chart version?

Latest

### What happened?

Latest released chart supporting old app version

### What you expected to happen?

New chart version supporting v2.11.0 will be released in order to support K8s 1.28.x

### Enter the command that you execute and failing/misfunctioning.

Na

**Comment by DrFaust92** [comment]
Closed via https://github.com/prometheus-community/helm-charts/pull/4371
