### ISSUE TITLE
[kube-prometheus-stack] upgrade grafana dashboards from AngularJS to the new panels

### ISSUE THREAD

**Issue by dmpe** [prometheus-community/helm-charts#4380]
### Is your feature request related to a problem ?

Grafana dashboards need to be updated/refreshed in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14. 

Reason being is that AngularJS panels are being deprecated https://grafana.com/docs/grafana/latest/developers/angular_deprecation/

### Describe the solution you'd like.

Please use new panels which are not dependant on angularJS. 

E.g. `graph` panel becomes `time-series` ? table is still called `table` in the new grafana

### Describe alternatives you've considered.

N/A - sure `[angular_support_enabled](https://github.com/grafana/grafana/blob/d61bcdf4ca5e69489e0067c56fbe7f0bfdf84ee4/conf/defaults.ini#L362)` would be possible to use, but question is for how long...

**Comment by wykhuh** [comment]
I was testing out `kube-prometheus-stack` this week and  noticed the AngularJS  depreciation warning too.

**Comment by dmpe** [comment]
Actually, this issue has already been reported to the upstream project -> https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/898. I.e it is still relevant insofar as, after the upstream change, grafana dashboards need to be updated here as well.. 

cc @jkroepke

**Comment by jkroepke** [comment]
You can set `angular_support_enabled=false`, then Grafana will auto convert deprecated panels.

However, upstream must be upgrade everything, since we only depend on them.

**Comment by vfarcic** [comment]
Was this completed? The Angular warning is still there.

**Comment by ArtemGontar** [comment]
So, is that planned or not planned, or fixed?

I am confused

**Comment by jkroepke** [comment]
> So, is that planned or not planned, or fixed?
> 
> I am confused

In general, it's not planned. There reason for this is that is not development at kube-prometheus-stack in terms of Grafana Dashboards & Prometheus Rules.

The majority comes from https://github.com/kubernetes-monitoring/kubernetes-mixin and there is an going issue to track this: https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/898

For example: https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/904

The dashboards needs to be upgrade there. Once it's done, we are able to update them at kube-prometheus-stack.

**Comment by jkroepke** [comment]
There is an PR in testing which implements the new dashboards from upstream: https://github.com/prometheus-community/helm-charts/pull/4531
