### ISSUE TITLE
[kube-prometheus-stack] Getting Angular deprecated warnings for the dashboards 

### ISSUE THREAD

**Issue by cp319391** [prometheus-community/helm-charts#4398]
### Describe the bug a clear and concise description of what the bug is.

we updated `kube-prometheus-stack` to `v57.1.1`

Getting Angular deprecated warnings for the dashboards. 

![image](https://github.com/prometheus-community/helm-charts/assets/67651406/60071afc-b3e9-4181-96ac-9d7a1bdc5ad8)

When is it expected to be fixed. Or is there something which we can do, so we don't get the warning and we migrate to the newer alternative. 

### What's your helm version?

3.14.3

### What's your kubectl version?

1.26.11

### Which chart?

kube-prometheus-stack

### What's the chart version?

57.1.1

### Enter the command that you execute and failing/misfunctioning.

helm

**Comment by jennydaman** [comment]
Duplicate of https://github.com/prometheus-community/helm-charts/issues/4393 https://github.com/prometheus-community/helm-charts/issues/4380

**Comment by cp319391** [comment]
works after setting `security.angular_support_enabled = false`
