### ISSUE TITLE
[kube-prometheus-stack] 57.2.0 include broken kube-state-metrics

### ISSUE THREAD

**Issue by mcantinqc** [prometheus-community/helm-charts#4410]
### Describe the bug a clear and concise description of what the bug is.

The latest version of kube-prometheus-stack update the dependency kube-state-metrics to version 5.18.0 that include the version 2.11.0 of kube-state-metrics. 

The version 2.11.0 is invalid with prometheus : https://github.com/kubernetes/kube-state-metrics/pull/2270.

### What's your helm version?

57.2.0

### What's your kubectl version?

v1.29.1

### Which chart?

kube-prometheus-stack

### What's the chart version?

57.2.0

### What happened?

Prometheus scrape fail with with invalid metric type "info".

See https://github.com/kubernetes/kube-state-metrics/issues/1973

### What you expected to happen?

Add a warning to https://github.com/prometheus-community/helm-charts/releases/tag/kube-prometheus-stack-57.2.0 or rollback kube-state-metrics.

### Enter the command that you execute and failing/misfunctioning.

n/a

**Comment by cdenneen** [comment]
With the release of 5.18.1 of kube-state-metrics can this helm-chart be bumped so its distributed package has the latest kube-state-metrics instead of 5.18.0

**Comment by cdenneen** [comment]
@dotdc anyway we can get a release to close out this issue?

**Comment by dotdc** [comment]
Hi @cdenneen,

Made PR https://github.com/prometheus-community/helm-charts/pull/4419 to force a release.
Should fix the issue once merged.

In the meantime, you can configure your kube-prometheus-stack values to use the latest ksm image:

```
kube-state-metrics:
  image:
    tag: "2.12.0"
```
