### ISSUE TITLE
[kube-prometheus-stack] support dual stack clusters

### ISSUE THREAD

**Issue by M0NsTeRRR** [prometheus-community/helm-charts#4429]
### Is your feature request related to a problem ?

There is no way for me to set the ipFamilyPolicy and ipFamilies to "preferDualStack" in the current helm chart for services

### Describe the solution you'd like.

Add the possibility to set in the ipFamilyPolicy and ipFamilies

### Describe alternatives you've considered.

Patch the current helm chart with kustomize

**Comment by M0NsTeRRR** [comment]
I will create the MR for this issue but I need to know if you want each services to be configurable with dual-stack or a global configuration for all services to enable dual-stack is sufficient.
I will of course reuse codes `ipDualStack` from other chart.

**Comment by jkroepke** [comment]
Each service should be preferred.
