### ISSUE TITLE
[prometheus-kube-stack]  how to rename datasource

### ISSUE THREAD

**Issue by shay-berman** [prometheus-community/helm-charts#443]
**Describe the bug**
When I rename the name of the datasource in the helm chart and then update the helm chart, it create additional datasource in grafana instead of just rename the existing one.

Is it possible to rename datasource in grafana that was configured with prometheus operator helm chart with setting  additionalDataSources ?  when i tried to rename and apply the helm it just created a new datasource in grafana with the new name.
```
  additionalDataSources:
   - name: Prometheus1
     access: proxy
     editable: false
     type: prometheus
     url: http://thanos-query:9090

```
**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.404", GitCommit:"81e2afbf51b876d15f0af546998c670207fdd592", GitTreeState:"clean", BuildDate:"2020-10-30T23:52:44Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}


```

**Which chart**:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

**Which version of the chart**:
11.1.1

**What happened**:
I installed the chart with this additional datasource for grafana:
```
  additionalDataSources:
   - name: Prometheus1
     access: proxy
     editable: false
     type: prometheus
     url: http://thanos-query:9090

```

and then i wanted just to rename this datasource which was already define by this setting (it has `prom-kube-prometheus-stack-grafana-datasource` configmap already)  
so i changed to name prometheus2 and appy the helm chart, but instead of just renaming (u cannot rename manually the datasource because if its comes from configmap its locked from UI changes so u want do it from the helm chart)
```
  additionalDataSources:
   - name: Prometheus2
     access: proxy
     editable: false
     type: prometheus
     url: http://thanos-query:9090

```
and then when u login to grafana you see 2 datasources prometheus1 and prometheus2. 

**What you expected to happen**:
would expect that it will rename prometheus1 to prometheus2 like u do in the UI.

**Comment by danielrosa-zh** [comment]
I'm facing this same problem in chart 16.11.0!
