### ISSUE TITLE
How to install custom plugins for grafana

### ISSUE THREAD

**Issue by knkarthik** [prometheus-community/helm-charts#444]
I really want to add `grafana-polystat-panel` and `yesoreyeram-boomtable-panel` plugins to grafana but I don't see an option to specify `GF_INSTALL_PLUGINS`  in `values.yml` of kube-prometheus-stack.

**Comment by monotek** [comment]
Asking in the grafana helm chart repo might be a better idea ;-)

https://github.com/grafana/helm-charts/tree/main/charts/grafana

Besides... Please use the issue template.

**Comment by ddides** [comment]
List them under:
```yaml
grafana:
  plugins:
    - your-plugin-here
 ```
