### ISSUE TITLE
[kube-prometheus-stack] How to change Timezone of Alert Manager UI?

### ISSUE THREAD

**Issue by rwlove** [prometheus-community/helm-charts#4451]
### Describe the bug a clear and concise description of what the bug is.

How do you change the timezone of the Alert Manager Web UI via values.yaml for kube-prometheus-stack.

I didn't see another place to ask questions. Apologies if this is the wrong place.

### What's your helm version?

version.BuildInfo{Version:"v3.11", GitCommit:"", GitTreeState:"", GoVersion:"go1.20.1"}

### What's your kubectl version?

1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

57.2.1

### What happened?

TZ is UTC

### What you expected to happen?

TZ is my actual timezone

### How to reproduce it?

look at the web ui

### Enter the command that you execute and failing/misfunctioning.

View the Web UI. Alerts are in UTC.

### Anything else we need to know?

no

**Comment by jkroepke** [comment]
Try to set TZ environment variable on that container, like TZ=Europe/Berlin

**Comment by flaviusavgust** [comment]
@rwlove 
It worked?

**Comment by jkroepke** [comment]
https://github.com/prometheus/alertmanager/issues/3810#issuecomment-2144065455
