### ISSUE TITLE
CPUThrottling High value configurable

### ISSUE THREAD

**Issue by sambitr** [prometheus-community/helm-charts#4465]
### Is your feature request related to a problem ?

Hi There, currently the CPUThrottling high value is fixed at 25% in the helm chart. That's too low and to be honest that should be left to the application teams to decide what should be the ideal value for them. With 25% limit set, we are getting too many alerts for now.

      expr: |-
        sum(increase(container_cpu_cfs_throttled_periods_total{container!="", }[5m])) by ({{ range $.Values.defaultRules.additionalAggregationLabels }}{{ . }},{{ end }}cluster, container, pod, namespace)
          /
        sum(increase(container_cpu_cfs_periods_total{}[5m])) by ({{ range $.Values.defaultRules.additionalAggregationLabels }}{{ . }},{{ end }}cluster, container, pod, namespace)
          > **( 25 / 100 )**

### Describe the solution you'd like.

I would like to make this field configurable through values.yml file, so that different project teams can use different threshold values according to them.

Or if there is a way to override it

### Describe alternatives you've considered.

NONE

**Comment by sambitr** [comment]
Please ignore this. I can update the value in prometheusrules: cluster-monitoring-kube-pr-kubernetes-resources

**Comment by Tim-herbie** [comment]
@sambitr Can you explain where exactly I can set the value to configure the percentage of this alert in the helm values?
