### ISSUE TITLE
[prometheus] Installation error: unknown field "minReadySeconds" in io.k8s.api.apps.v1.StatefulSetSpec

### ISSUE THREAD

**Issue by yunnniverse** [prometheus-community/helm-charts#4470]
### Describe the bug a clear and concise description of what the bug is.

I tried to use scaphandre and prometheus for kubernetes cluster. 

I entered commands below.
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
$ helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
$ helm repo update

and after that, I entered like:
$ helm install prometheus prometheus-community/prometheus \
--set alertmanager.persistentVolume.enabled=false \
--set server.persistentVolume.enabled=false

But there is always an error. about unknown field "minReadySeconds" in statefulsetspec.

### What's your helm version?

version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

### What's your kubectl version?

Client Version: v1.30.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.21.1

### Which chart?

prometheus-community/prometheus

### What's the chart version?

unspecified

### What happened?

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): unknown field "minReadySeconds" in io.k8s.api.apps.v1.StatefulSetSpec

### What you expected to happen?

complete installation

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus prometheus-community/prometheus \
--set alertmanager.persistentVolume.enabled=false \
--set server.persistentVolume.enabled=false

**Comment by zeritti** [comment]
Duplicate #4333. At the moment, release 25.12.0 should work with your cluster.

**Comment by ninjacoderz** [comment]
@zeritti , how to fix it ? I still got this error

**Comment by case0sh** [comment]
@ninjacoderz 
I had this problem too, when I set the `alertmanager` to `false` the problem went away.

```
alertmanager:
  enabled: false
```
