### ISSUE TITLE
[kube-prometheus-stack] Thanos Sidecar Uploading Duplicate data to S3

### ISSUE THREAD

**Issue by mohitmaheshwari31** [prometheus-community/helm-charts#4484]
### Describe the bug a clear and concise description of what the bug is.

Hi Team, 

I have two Prometheus running in the stack and each has sidecar associated with it .  I am using thanos sidecar to upload the data to S3 . 
Issue : Both the thanos sidecar are uploading the data , due to which duplicate data is being stored in Long Term storage. 
I need only one thanos sidecar to upload the data to s3 . 
Can someone please suggest how i can fix this?

### What's your helm version?

3.10.3

### What's your kubectl version?

1.29

### Which chart?

kube-prometheus-stack

### What's the chart version?

Latest

### What happened?

NA

### What you expected to happen?

NA

### How to reproduce it?

NA

### Enter the command that you execute and failing/misfunctioning.

NA

**Comment by jkroepke** [comment]
The bug you mention is the expected design of Thanos. If you want only want to avoid duplicate data, you have to run Prometheus with replica one.

Thanos is able to deduplicate data using the compactor.

For more thanos related question, reach-out the maintainers directly: https://github.com/thanos-io/thanos
