### ISSUE TITLE
[prometheus] Targets not shown in UI with file SD

### ISSUE THREAD

**Issue by brancomrt** [prometheus-community/helm-charts#4487]
### Describe the bug a clear and concise description of what the bug is.

Scrape_config "file_sd_configs" not working.

### What's your helm version?

version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

### What's your kubectl version?

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.12+rke2r1", GitCommit:"12031002905c0410706974560cbdf2dad9278919", GitTreeState:"clean", BuildDate:"2024-03-15T20:45:44Z", GoVersion:"go1.21.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Which chart?

https://artifacthub.io/packages/helm/prometheus-community/prometheus

### What's the chart version?

25.20.0

### What happened?

When I create a "job_name" in scrape_configs on serverFiles and set the target as "file_sd_configs" to read the "job" from a .json file, the target is not displayed in "targets" through the Prometheus GUI.

values.yaml

`    scrape_configs:
     - job_name: teste
        file_sd_configs:
          - files:
            - /prometheus-targets.json
            refresh_interval: 10s`
            
 prometheus-targets.json
 
 `[
  {
    "labels": {
      "job": "teste"
    },
    "targets": [
      "10.199.4.252:7777"
    ]
  }
]`

### What you expected to happen?

The target was supposed to be displayed under "Targets" > "All scrape pools" through the Prometheus Server GUI, but it's not being shown.

### How to reproduce it?

I replicated the installation of the chart via local Helm, which involved fetching from the official repository on an RKE2 cluster.

### Enter the changed values of values.yaml?

`    scrape_configs:
     - job_name: teste
        file_sd_configs:
          - files:
            - /prometheus-targets.json
            refresh_interval: 10s`

### Enter the command that you execute and failing/misfunctioning.

"helm install prometheus . -n prometheus-system" on the local chart helm.

**Comment by zeritti** [comment]
You are not saying whether and how the file gets mounted in the container, i.e. how it becomes available to prometheus for reading.

**Comment by brancomrt** [comment]
I am using a storage class that stores data on NFS on values.yaml.

prometheus:
   prometheusSpec:
       storageSpec:
           volumeClaimTemplate:
                spec:
                     storageClassName: "nfs-client"
                     accessModes: ["ReadWriteOnce"]
                     resources:
                         requests:
                              storage: 200Gi
                              

# kubectl get storageclasses.storage.k8s.io 
NAME            PROVISIONER                                     RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
nfs-client      cluster.local/nfs-subdir-external-provisioner   Delete          Immediate              true                   131d

**Comment by brancomrt** [comment]
Was solved!
