### ISSUE TITLE
[kube-prometheus-stack] extract prometheus into another seperated chart

### ISSUE THREAD

**Issue by LeoQuote** [prometheus-community/helm-charts#4494]
### Is your feature request related to a problem ?

In some cases, I would like to install multiple prometheus instance inside a cluster:
* jaeger
* cluster monitor
* other app metrics

or even one prometheus instance for a team.

I would be good if there's a helm chart that can create a prometheus including:
* Prometheus
* Service
* Ingress

all by one command
```
helm install my-prometheus 
```

I'd prefer to continue using prometheus-operator provided CRD `Prometheus` as it can intergrate with other CRs, like `ServiceMonitor` or `PrometheusRule`

### Describe the solution you'd like.

Create a new helm chart installing the prometheus instance using `Prometheus` CRD

### Describe alternatives you've considered.

n/a

**Comment by jkroepke** [comment]
We have it already: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

**Comment by LeoQuote** [comment]
@jkroepke Thanks for your reply, but this is not what I wanted, the helm chart you provided can only ingest config map, but I want a prometheus that can discover scrape config and service monitor using `ServiceMonitor` and `ScrapeConfig`, while this is only available when using prometheus operator

**Comment by jkroepke** [comment]
You can install kube-prometheus-stack twice.

On first install, you install everything except prometheus (`prometheus.enabled=false`) and for the second install, you disable to prometheusOperator components.

**Comment by GMartinez-Sisti** [comment]
Hi @LeoQuote, what you are proposing is just a copy of the kube-prometheus-stack helm chart with files removed, which is the exact same thing as configuring it to install only the components you want and this is why configuration values exist.

Are we missing something here? 🤔 Please let us know.

**Comment by LeoQuote** [comment]
Exactly, but during the implementation I found it tiring and boring to do this, maybe following @jkroepke is a good idea.

What do you suggest, a new helm chart or just the original one with multiple components disabled in values file? I’m on the half way implementing the new chart, I wonder how many people would need that.

**Comment by GMartinez-Sisti** [comment]
IMHO it won't probably be accepted since we don't want to maintain two charts for the same thing.

Using values file is the correct way to go. If you need to do it multiple times, just re-use the values file with your desired config.

**Comment by LeoQuote** [comment]
Understand your concern, I dont like two chart for the same reason either, and I also dont want kube-prometheus-stack to depend on another helm chart, thanks for your explaination.
