### ISSUE TITLE
[kube-prometheus-stack] How to add the additional args using "extraArgs" for kube-state-metrics

### ISSUE THREAD

**Issue by sivap083** [prometheus-community/helm-charts#4504]
### Describe the bug a clear and concise description of what the bug is.

We attempted to add additional arguments using the 'extraArgs' field in the values.yaml file; however, kube-state-metrics did not accept the changes.

I want to add the '--metric-labels-allowlist' argument under the container's 'args' section.

Below is the content of my values.yaml file:

kubeStateMetrics:
  enabled: true
  extraArgs: 
    - '--metric-labels-allowlist=nodes=[*]'

### What's your helm version?

v3.14.2

### What's your kubectl version?

v1.30.0

### Which chart?

kube-state-metrics

### What's the chart version?

5.19.0

### What happened?

We attempted to add additional arguments using the 'extraArgs' field in the values.yaml file; however, kube-state-metrics did not accept the changes.

### What you expected to happen?

I want to add the '--metric-labels-allowlist' argument under the container's 'args' section in kube-state-metrics deployment.

### Enter the changed values of values.yaml?

kubeStateMetrics:
  enabled: true
  extraArgs:
    - "--metric-labels-allowlist=nodes=[*]"

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml

**Comment by zeritti** [comment]
> We attempted to add additional arguments using the 'extraArgs' field in the values.yaml file; however, kube-state-metrics did not accept the changes.

The subchart supports a specific field for that argument (ref. KSM [values](https://github.com/prometheus-community/helm-charts/blob/21021a2799659dbb892c29ab661ad8cbb7bb2a1b/charts/kube-state-metrics/values.yaml#L310)):

```yaml
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  metricLabelsAllowlist:
  - nodes=[*]
```

**Comment by sivap083** [comment]
Thank you!!! It worked.
