### ISSUE TITLE
[kube-prometheus-stack] Breaking change in 58.3.1 for ArgoCD deployed kube-prometheus-stack

### ISSUE THREAD

**Issue by dexter136** [prometheus-community/helm-charts#4509]
### Describe the bug a clear and concise description of what the bug is.

#4503 Made a change that set a default value for prometheusOperator.admissionWebhooks.patch.ttlSecondsAfterFinished of 0.

For deployments through ArgoCD this breaks synchronization, as those admission jobs are now removed by kubernetes before ArgoCD sees that they have completed. Due to this the synchronization process get's stuck on waiting for that job.

To have the chart properly deploy the value has to manually be set high enough for ArgoCD to be able to remove the job before kubernetes.

### What's your helm version?

version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

### What's your kubectl version?

Client Version: v1.30.0 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.30.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

58.3.1

### What happened?

ArgoCD was unable to synchronize the helm chart after moving to version 58.3.1.

### What you expected to happen?

ArgoCD successfully can deploy the new version.

### How to reproduce it?

Attempt to deploy the chart with version 58.3.1 without explicitly setting the value prometheusOperator.admissionWebhooks.patch.ttlSecondsAfterFinished

### Enter the changed values of values.yaml?

NONE

### Enter the command that you execute and failing/misfunctioning.

Helm install

**Comment by jemag** [comment]
Same problem here, for now I simply configured
```yaml
        ttlSecondsAfterFinished: 60
```
which seems to work fine at the moment.

However I feel that the default value should definitely allow for ArgoCD deployment, instead of users needing to manually change it.

**Comment by jkroepke** [comment]
If 60 seconds is a working default, please create a PR for that.

**Comment by DrFaust92** [comment]
@jkroepke opened a quick PR as I broke this 😊
