### ISSUE TITLE
[prometheus] Secure Prometheus with enabling Ldap authentication

### ISSUE THREAD

**Issue by kksaha** [prometheus-community/helm-charts#4522]
### Is your feature request related to a problem ?

At present, there is no option in Prometheus Helm Chart to allow LDAp authentication. How are we going to do that?

### Describe the solution you'd like.

To secure Prometheus need to enable ldap authentication 

### Describe alternatives you've considered.

NA

**Comment by walker-tom** [comment]
Thank you for submitting this issue, you will need to raise this issue on https://github.com/prometheus/prometheus as this repository only maintains the Helm Chart rather than the Prometheus application itself so we can't implement new features such as LDAP.
