### ISSUE TITLE
[kube-prometheus-stack] Shards PVC has too long name so that it cannot be provisioned

### ISSUE THREAD

**Issue by kworkbee** [prometheus-community/helm-charts#4523]
### Describe the bug a clear and concise description of what the bug is.

I'm deploying Prometheus via `kube-prometheus-stack` helm chart on AWS EKS environment, but operator is giving too long PVC name even though `fullnameOverride` value is short. Therefore, there's an issue that PVC cannot be provisioned.

<img width="1450" alt="image" src="https://github.com/prometheus-operator/prometheus-operator/assets/18034626/d3454d73-ba28-40e8-8802-f313c501f3b8">

### What's your helm version?

3.14.3

### What's your kubectl version?

1.28.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

55.8.1

### Enter the command that you execute and failing/misfunctioning.

Sync through ArgoCD

**Comment by zeritti** [comment]
Setting `volumeClaimTemplate.metadata.name` may help: https://github.com/prometheus-community/helm-charts/issues/3392#issuecomment-1564705588

**Comment by kworkbee** [comment]
@zeritti It works! Thanks for your help 😄

**Comment by kworkbee** [comment]
Some of them still have long names...

**Comment by kworkbee** [comment]
Aside from such issues, it certainly seems problematic that Prometheus is repeated in the currently generated PVC naming.

**Comment by jkroepke** [comment]
This to set the value

https://github.com/prometheus-community/helm-charts/blob/e0c3624150e9554a7dcca40d4a7f0f8ba8ed3848/charts/kube-prometheus-stack/values.yaml#L4695

to values.


Other note: Please mention that it expected and the TSDB (prometheus database) may get corrupt on NFS based volumes, since it not an supported file storage.

**Comment by kworkbee** [comment]
@jkroepke It solved clearly. Thank you for your help.
