### ISSUE TITLE
[kube-prometheus-stack] deploy only dashboards

### ISSUE THREAD

**Issue by not7cd** [prometheus-community/helm-charts#4604]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

I want to integrate dashboards in **kube-prometheus-stack** chart to my existing stack. I'm using **grafana-operator** that could handle _GrafanaDashboard_ CRDs, and quite complex Prometheus deployment. 

I'm looking for a configuration example or guideance. 
Maybe an option to generate GrafanaDashboard CRDs.

### Describe alternatives you've considered.

Copying [dashboards-1.14 folder](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14) and creating custom templating with GrafanaDashboard CRD.

**Comment by LeoQuote** [comment]
You can use this chart but disable all the other components you dont want.

**Comment by not7cd** [comment]
I found out that you can generate those dashboards yourself with https://monitoring.mixins.dev/
They will be in newer versions and allow you to wrap them into Kubernetes resources however you want, I went with grafana-operator CRs.
