### ISSUE TITLE
[prometheus] Chart Issue - getting error while installing

### ISSUE THREAD

**Issue by susheelpatil1** [prometheus-community/helm-charts#4620]
### Describe the bug a clear and concise description of what the bug is.

Getting below error whicle installing the chart
`helm install prometheus-community prometheus-community/prometheus -f prometheues-values.yml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): unknown field "minReadySeconds" in io.k8s.api.apps.v1.StatefulSetSpec`

### What's your helm version?

version.BuildInfo{Version:"v3.15.2", GitCommit:"1a500d5625419a524fdae4b33de351cc4f58ec35", GitTreeState:"clean", GoVersion:"go1.22.4"} √bpatil:prometheus  % 

### What's your kubectl version?

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:14:10Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"} Kustomize Version: v4.5.4 Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"} WARNING: version difference between client (1.24) and server (1.20) exceeds the supported minor version skew of +/-1

### Which chart?

prometheus-community/prometheus 

### What's the chart version?

25.22.0

### What happened?

When i try to install the chart i am getting below error
`helm install prometheus-community prometheus-community/prometheus -f prometheues-values.yml
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(StatefulSet.spec): unknown field "minReadySeconds" in io.k8s.api.apps.v1.StatefulSetSpec`

### What you expected to happen?

should install the chart

### How to reproduce it?

run
`helm install prometheus-community prometheus-community/prometheus`

### Enter the changed values of values.yaml?

none

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-community prometheus-community/prometheus

### Anything else we need to know?

no

**Comment by ninjacoderz** [comment]
I still getting this error 
how to fix it please @zeritti
