### ISSUE TITLE
[kube-prometheus-stack] Add Gateway API templates

### ISSUE THREAD

**Issue by e3b0c442** [prometheus-community/helm-charts#4622]
### Is your feature request related to a problem ?

I need to manually add HTTPRoutes when trying to use Gateway API for ingress

### Describe the solution you'd like.

Now that Gateway API has reached v1 and implementations are beginning to land, add Gateway API templates (HTTPRoute) that can be chosen in lieu of Ingress resources.

### Describe alternatives you've considered.

* Disabling ingress and adding Gateway API resources manually (current option)
* Continue using Ingress

### Additional context.

Using kube-prometheus-stack as a filler here, I understand the ingress is a part of the subordinate charts.

**Comment by jkroepke** [comment]
@monotek @GMartinez-Sisti @QuentinBisson I think, adding Gateway API feels natural, since ingress API reached the feature complete state and may not receive new features.

Do you already have a good template for HTTPRoutes? Should we support Gateway as well? Do you have Gateway API already in use on your company and already develop a good base?

With some coordination, we can deliver the same experience for all end-users across all prometheus community helm charts.

**Comment by GMartinez-Sisti** [comment]
> @monotek @GMartinez-Sisti @QuentinBisson I think, adding Gateway API feels natural, since ingress API reached the feature complete state and may not receive new features.
> 
> Do you already have a good template for HTTPRoutes? Should we support Gateway or BackendTLSPolicy as well? Do you have Gateway API already in use on your company and already develop a good base?
> 
> With some coordination, we can deliver the same experience for all end-users across all prometheus community helm charts.

I think we should support both for now, clusters that were created some time ago and are still being used (even if they are on the latest k8s version) are very likely to still use ingress controllers that might not support this.

**Comment by jkroepke** [comment]
Definitive! I was not talking about removing ingress.

**Comment by jkroepke** [comment]
An initial draft can be found here: https://github.com/prometheus-community/helm-charts/pull/4646

Some Feedback would be appreciated. @e3b0c442 I would like to know, if that would meets your expectation.

**Comment by QuentinBisson** [comment]
I Can take a look but i'm not familiar with the gateway api yet. Also, is it enabled for the grafana depencency? If you did not we might want to make the gateway api enable flag global as well?

**Comment by jkroepke** [comment]
No, but you can setup an PR which I can review/approve at grafana 😅

**Comment by jkroepke** [comment]
> I Can take a look but i'm not familiar with the gateway api yet. Also, is it enabled for the grafana depencency? If you did not we might want to make the gateway api enable flag global as well?

https://github.com/grafana/helm-charts/pull/3400
