### ISSUE TITLE
[prometheus] Liveness and Readiness probes missing

### ISSUE THREAD

**Issue by luigi-bitonti** [prometheus-community/helm-charts#4623]
### Is your feature request related to a problem ?

I've a Kyverno rule that checks if all containers have Readiness and Liveness probes defined. It would be nice if "reload" container in Prometheus deployment had these probes enabled as others container.

### Describe the solution you'd like.

Possibility to insert Readiness and Liveness probes.

### Describe alternatives you've considered.

NONE

**Comment by zeritti** [comment]
A PR will be appreciated!
