### ISSUE TITLE
Watchdog alerts in Prometheus Federation

### ISSUE THREAD

**Issue by KR411-prog** [prometheus-community/helm-charts#466]
How does watchdog alert work in Prometheus federation?

I have Prometheus federation setup with 4 Prometheus instances.How to get notified by alerts in Prometheus Federation when one prometheus goes down?

**Comment by monotek** [comment]
Please use the issue template.
Besides your question seems not be chart related.
Maybe visiting the prometheus project website / documentation makes more sense:
https://prometheus.io/docs/prometheus/latest/federation/
