### ISSUE TITLE
How to specify resources to prometheusOperator and prometheus-node-exporter

### ISSUE THREAD

**Issue by Naveen671** [prometheus-community/helm-charts#4712]

**Comment by DrFaust92** [comment]
Hi [Naveen671](https://github.com/Naveen671),

1. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2388
2. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2114C1-L2114C26 - need to add explicitly `resources` block - as its supported in the nested chart - https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L75C3-L75C12

Good luck!
