### ISSUE TITLE
[prometheus-kube-stack] issue PrometheusRule and Permission issue with queries.active

### ISSUE THREAD

**Issue by mohanagandlla** [prometheus-community/helm-charts#472]
Hi team I have upgraded my operator from 0.42.0 to 0.44.0 this is the current version and I am using kubernetes version as 1.19. What I have observed here is at 0.42 i saw Prometheus contain 3 containers and now at 0.44 Prometheus contain 2 containers there is no rule-config-reload container 
I done the deployment by helm chart some rules are trigger I have manually added rules those are not triggering and i have deleted the existed rule that rule is not erased at!
May i know to do add the PrometheusRule at operator v0.44.0

Most of the time the pod is automatically getting crashloopbackoff due to permission denined issue of query.active file 
uid=65534
gid=65534  these are the security context 
level=error ts=2020-12-09T12:05:39.096Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"

**Comment by bstavenuiter** [comment]
Hi,

is this still an active issue? I've rolled out prometheus-stack on a GCP kubernetes cluste. Using the values.yaml file to tweak some configuration. 
However I can't seem to get rid of this permissions error. 

I get a prometheus-persisted statefulset in the default namespace. But this this exact error.
Setting securityContext doesn't seem to have an effect.

**Comment by lodotek** [comment]
Bump. Any resolution found here?
