### ISSUE TITLE
[ kube-prometheus-stack ] PrometheusMissingRuleEvaluations continuously firing

### ISSUE THREAD

**Issue by irizzant** [prometheus-community/helm-charts#473]
**Describe the bug**
In my cluster PrometheusMissingRuleEvaluations alert is firing and resolving continuously.
I read the runbook and it looks like the cause is a slow evaluation of a rules group.

The problem here is that the rule group is not one I defined myself, but 
`/etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/monitoring-kube-prometheus-stack-kube-apiserver.rules.yaml;kube-apiserver.rules`

The cluster itself is working fine I cannot find any apparent issue. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s3", GitCommit:"0e4fbfefe1dd8734756dfa4f9ab4fc89665cece4", GitTreeState:"clean", BuildDate:"2020-11-13T07:19:02Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

```

**Which chart**:
 kube-prometheus-stack 
**Which version of the chart**:
12.5.0
**What happened**:
I see the PrometheusMissingRuleEvaluations alert firing and resolving continously 

**What you expected to happen**:
The alert should not be firing

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
The kube-apiserver section of my values.yaml is the same as the official one, meaning no change was made there.

**Comment by irizzant** [comment]
Turns out that this [line](https://github.com/prometheus-community/helm-charts/blob/0595e7fcec6d58fd67b492bc2f4965d90520e696/charts/kube-prometheus-stack/values.yaml#L37) was overloading Prometheus with a too large query and causing the issue.
Since I changed it to `false` I didn't have this issue anymore

**Comment by jdomag** [comment]
@irizzant 
Can you share some details on how you troubleshooted this issue? How can I check what causing this alert?

**Comment by irizzant** [comment]
@jdomag  I'd give a look at the current prometheus configuration you have in your cluster, in my case the problem was the line I reported in my [previous reply](https://github.com/prometheus-community/helm-charts/issues/473#issuecomment-757695282).
I turned it off and the problem went away.
