### ISSUE TITLE
[prometheus-kafka-exporter] test folder pods gets created

### ISSUE THREAD

**Issue by Minutis** [prometheus-community/helm-charts#475]
**Describe the bug**
It is impossible to disable `kafka` and `zookeeper` test pods, since there are no conditionals or helm hooks configured in https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-kafka-exporter/templates/tests

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-kafka-exporter

**Which version of the chart**: all

**What happened**: `kubectl get pods` shows not only `prometheus-kafka-exporter`, but also test pods `kafka` and `zookeeper`.

**What you expected to happen**: only `prometheus-kafka-exporter` pod should be provisioned.

**How to reproduce it** (as minimally and precisely as possible):
I use helmfile, but i guess it could be reproduced with bare helm: `helmfile -e <env> apply`

**Changed values of values.yaml** (only put values which differ from the defaults):

```console
fullnameOverride: "prometheus-kafka-exporter"

kafkaServer:
 - one
 - two

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9308"

liveness:
  enabled: true

readiness:
  enabled: true
```

**Comment by gna582** [comment]
Would like to second this. Got really scared for a sec.

**Comment by monotek** [comment]
Would you mind to create a pr please?

**Comment by monotek** [comment]
closing in favour of: https://github.com/prometheus-community/helm-charts/pull/498
