### ISSUE TITLE
[kube-prometheus-stack] Error when apply CRD.

### ISSUE THREAD

**Issue by weyderfs** [prometheus-community/helm-charts#4756]
### Describe the bug a clear and concise description of what the bug is.

```sh
The CustomResourceDefinition "alertmanagers.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### What's your helm version?

version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

### What's your kubectl version?

v1.29.2

### Which chart?

Kube Prometheus Stack

### What's the chart version?

kube-prometheus-stack-61.3.1

### What happened?

When you try apply manually the CRD `monitoring.coreos.com_alertmanagers.yaml ` return the error.

### What you expected to happen?

Apply the CRD

### How to reproduce it?

Just run `kubectl apply`

### Enter the command that you execute and failing/misfunctioning.

k apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.75.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml

**Comment by zeritti** [comment]
> Just run kubectl apply

Please, use server-side-apply when applying the CRDs as indicated in [README](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-60x-to-61x):

```bash
kubectl apply --server-side \
  -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.75.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
...
```

**Comment by weyderfs** [comment]
> > Just run kubectl apply
> 
> Please, use server-side-apply when applying the CRDs as indicated in [README](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-60x-to-61x):
> 
> ```shell
> kubectl apply --server-side \
>   -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.75.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
> ...
> ```

Not works I've tried before. I just delete everything and _deploy_ again, works. Maybe was some update bug in the past.

**Comment by kevinburkesegment** [comment]
We also saw this error message but were unsure why it happened.
