### ISSUE TITLE
[kube-prometheus-stack] override image repository from helm command line (--set) not working

### ISSUE THREAD

**Issue by bbetuk** [prometheus-community/helm-charts#4780]
### Describe the bug a clear and concise description of what the bug is.

When using helm and --set to specify values for image repository, registry, and tag the default values are being used instead of the provided values. I used the alertmanager image as an example.

### What's your helm version?

v3.15.3

### What's your kubectl version?

Client/Server: v1.29.7, Kustomize Version: v5.0.4-0

### Which chart?

prometheus-kube-stack

### What's the chart version?

61.6.0

### What happened?

Executed the following command attempting to use my own repo to pull the alertmanager image:
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set alertmanagerSpec.image.registry=ghcr.io,alertmanagerSpec.image.repository=bbetuk/alertmanager,alertmanagerSpec.image.tag=v0.27.0 -n default

The alertmanager image was pulled from quay.io.

### What you expected to happen?

After entering the above command I checked the image location from the pod and the image came from quay.io not ghcr.io. I would expect the image source to be ghcr.io.

kubectl get pods
kubectl get pods alertmanager-kube-prometheus-stack-alertmanager-0 -o yaml | grep image
Image was pulled from registry: quay.io/prometheus/alertmanager:v0.27.0

### How to reproduce it?

In order to test this I pulled the alertmanager image from quay.io and put it in ghcr (public). The public
image is ghcr.io/bbetuk/alertmanager:v0.27.0. You can use this to test.

1. helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set alertmanagerSpec.image.registry=ghcr.io,alertmanagerSpec.image.repository=bbetuk/alertmanager,alertmanagerSpec.image.tag=v0.27.0 -n default
2. Check where the image was pulled from:
kubectl get pods
kubectl get pods alertmanager-kube-prometheus-stack-alertmanager-0 -o yaml | grep image
Image was pulled from registry: quay.io/prometheus/alertmanager:v0.27.0

### Enter the changed values of values.yaml?

None.

### Enter the command that you execute and failing/misfunctioning.

helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --set alertmanagerSpec.image.registry=ghcr.io,alertmanagerSpec.image.repository=bbetuk/alertmanager,alertmanagerSpec.image.tag=v0.27.0 -n default

### Anything else we need to know?

Setting the image location for alertmanger in the values.yaml file works as expected:

Override image using values.yaml file. Changed the following:
    image:
      registry: ghcr.io
      repository: bbetuk/alertmanager
      tag: v0.27.0
      sha: ""

kubectl get pods
kubectl get pods alertmanager-kube-prometheus-stack-alertmanager-0 -o yaml | grep image
Image was pulled from ghcr.io as expected.

**Comment by zeritti** [comment]
The correct path to the image map is 

```yaml
alertmanager:
  alertmanagerSpec:
    image:
```

Your install command would then be

```
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
--set alertmanager.alertmanagerSpec.image.registry=ghcr.io,\
alertmanager.alertmanagerSpec.image.repository=bbetuk/alertmanager,\
alertmanager.alertmanagerSpec.image.tag=v0.27.0 \
-n default
```

Similarly for prometheus, i.e. `prometheus.prometheusSpec.image`. The top-level keys can be determined with e.g. 
`yq 'keys' values.yaml`.

**Comment by bbetuk** [comment]
Thank you! I see the top level I was missing. Tested it and it works perfect.
