### ISSUE TITLE
[prometheus-elasticsearch-exporter] image.pullSecret not taken into account

### ISSUE THREAD

**Issue by Hathoute** [prometheus-community/helm-charts#4786]
### Describe the bug a clear and concise description of what the bug is.

`image.pullSecret` is not taken into account by the image. PR #4589 seems to break this, which results in ImagePullBackOff.

Using `global.imagePullSecrets` does the job for now.

### What's your helm version?

version.BuildInfo{Version:"v3.15.1", GitCommit:"e211f2aa62992bd72586b395de50979e31231829", GitTreeState:"clean", GoVersion:"go1.22.3"}

### What's your kubectl version?

Client Version: v1.29.2

### Which chart?

prometheus-elasticsearch-exporter

### What's the chart version?

6.0.0

**Comment by zeritti** [comment]
Thank you, @Hathoute, for the issue. Indeed, `image.pullSecret` seems to have been omitted. A PR will be appreciated!

**Comment by Hathoute** [comment]
Done. You can check the PR if you've got some free time @zeritti, tried to keep it as simple as possible.
