### ISSUE TITLE
[prometheus] How to set podLabels for the remaining pods (alertmanager, node-exporter, pushgateway, etc.)

### ISSUE THREAD

**Issue by RoFz** [prometheus-community/helm-charts#4795]
I'm currently deploying prometheus using:

```
helm install prometheus prometheus-community/prometheus \
  --set-string 'server.podLabels.sidecar\.istio\.io/inject=false'
```

How can I do the same thing with the other deployed pods such as alertmanager, node-exporter, kube-state-metrics, etc.)?

Running:

```
helm install prometheus prometheus-community/prometheus \
  --set-string 'server.podLabels.sidecar\.istio\.io/inject=false' \
  --set-string 'alertmanager.podLabels.sidecar\.istio\.io/inject=false'
```

leads to:

> Error: INSTALLATION FAILED: cannot re-use a name that is still in use

I'm assuming I'll need to set these other pods in prometheus' chart to `enabled = false` and then use their own individual charts for the installation to be able to apply individual podLabels. Is that correct?

**Comment by zeritti** [comment]
The error does not refer to `podLabels`. You are installing a chart release that already exists, i.e. a chart release of the same name has already been installed in the given namespace. You can check with `helm list -n NAMESPACE` and upgrade that release if desired.
