### ISSUE TITLE
[kube-prometheus-stack] retentionSize is not taken into effect

### ISSUE THREAD

**Issue by radhupr** [prometheus-community/helm-charts#4799]
### Describe the bug a clear and concise description of what the bug is.

From issue comment [here](https://github.com/prometheus-operator/prometheus-operator/issues/6854#issuecomment-2298638407), I understand the retentionSize is not supported for prometheus operator. 
Why is the option still available in helm chart as a configurable option?

### What's your helm version?

v3.11.1

### What's your kubectl version?

v1.28.3

### Which chart?

prometheus-operator

### What's the chart version?

60.0.0

### How to reproduce it?

More details under [issue](https://github.com/prometheus-operator/prometheus-operator/issues/6854) 

### Enter the command that you execute and failing/misfunctioning.

kustomize build --enable-helm ./prometheus-operator | kubectl apply -f -

**Comment by zeritti** [comment]
> From issue comment https://github.com/prometheus-operator/prometheus-operator/issues/6854#issuecomment-2298638407, I understand the retentionSize is not supported for prometheus operator.

Your statement is not correct. Prometheus Operator does support the Prometheus' flag `--storage.tsdb.retention.size` in `prometheus` CRD with `prometheus.spec.retentionSize` (ref. [prometheus](https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Prometheus)) which corresponds to the chart's `prometheus.prometheusSpec.retentionSize` ([values.yaml](https://github.com/prometheus-community/helm-charts/blob/7cdb29adfdb68d4b337afcc4c5a98a46b918ca38/charts/kube-prometheus-stack/values.yaml#L3707)).

The flag is to be used only when running Prometheus in _server_ mode:
> --storage.tsdb.retention.size=STORAGE.TSDB.RETENTION.SIZE  
                                 Maximum number of bytes that can be stored for blocks. A unit is required, supported
                                 units: B, KB, MB, GB, TB, PB, EB. Ex: "512MB". Based on powers-of-2, so 1KB is 1024B.
                                 Use with server mode only.

> retentionSize is not taken into effect

If `prometheus.prometheusSpec.retentionSize` is set when installing/upgrading the chart, e.g.

```bash
$ helm install kps prometheus-community/kube-prometheus-stack \
--version=62.1.0 \
--set "prometheus.prometheusSpec.retentionSize=2GB"
```

the flag is correctly set in the prometheus container:

```bash
$ kubectl exec prometheus-kps-kube-prometheus-stack-prometheus-0 \
-c prometheus -- \
pgrep -fa prometheus

1 /bin/prometheus --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries \
--config.file=/etc/prometheus/config_out/prometheus.env.yaml --web.enable-lifecycle --web.external-url=http://kps-kube-prometheus-stack-prometheus.default:9090 \
--web.route-prefix=/ --storage.tsdb.retention.time=10d --storage.tsdb.retention.size=2GB --storage.tsdb.path=/prometheus --storage.tsdb.wal-compression \
--web.config.file=/etc/prometheus/web_config/web-config.yaml
```
