### ISSUE TITLE
[kube-prometheus-stack] Issue with the Prometheus upgrade from 61.8.0 to 62.2.1

### ISSUE THREAD

**Issue by numa1985** [prometheus-community/helm-charts#4808]
### Describe the bug a clear and concise description of what the bug is.

Prometheus works fine in 61.8.0 with the attached values.yaml .

While upgrading Prometheus to 62.2.1 the pods related to the stateful set "prometheus-prometheus-kube-prometheus-prometheus" are getting terminated , for some reason stateful set is picking prometheus-config-reloader:v0.75.2 though we updated crds to 0.76.0.

Not sure if some thing has been changed related to the statefulset that needs to be taken care of.
Any suggestions are much appreciated.

### What's your helm version?

v3.15.4

### What's your kubectl version?

v1.29.2

### Which chart?

kube-prometheus-stack

### What's the chart version?

62.2.1

### What happened?

Prometheus works fine in 61.8.0 with the attached values.yaml .

While upgrading Prometheus to 62.2.1 the pods related to the statefulset "prometheus-prometheus-kube-prometheus-prometheus" are getting terminated , for some reason statefulset is picking prometheus-config-reloader:v0.75.2 though we updated crds to 0.76.0.

Not sure if some thing has been changed related to the statefulset that needs to be taken care of.
Any suggestions are much appreciated.

### Enter the changed values of values.yaml?

[values.txt](https://github.com/user-attachments/files/16712191/values.txt)

### Enter the command that you execute and failing/misfunctioning.

helm upgrade  --install prometheus prometheus-community/kube-prometheus-stack  -f values.yaml -n prometheus --force --set prometheusOperator.admissionWebhooks.patch.nodeSelector."kubernetes\.io/os"=linux --set prometheusOperator.nodeSelector."kubernetes\.io/os"=linux --set kube-state-metrics.nodeSelector."kubernetes\.io/os"=linux --set prometheus-node-exporter.nodeSelector."kubernetes\.io/os"=linux --set prometheus.prometheusSpec.nodeSelector."kubernetes\.io/os"=linux --set alertmanager.enabled=false --set grafana.enabled=false --set prometheus.service.type="LoadBalancer"

**Comment by numa1985** [comment]
Seems the CRDS of the 62.*.* version is conflicting with old CRD (0.75.2) ,since **prometheus-config-reloader** under **Prometheus** values.yaml is using 0.75.2 which result in STS termination . Kindly do the needful.

![image](https://github.com/user-attachments/assets/fa26aa7e-2132-4aef-82e9-7aa5c46d3dc3)



![image](https://github.com/user-attachments/assets/a9e3e3d6-e1cc-4b22-be78-f2cda124590a)


From kubectl events

![image](https://github.com/user-attachments/assets/ac7112f0-7e18-4ff4-abbf-4e3c8399d3ae)

**Comment by zeritti** [comment]
> Seems the CRDS of the 62.2.1 version is conflicting with old CRD (0.75.2), since prometheus-config-reloader under Prometheus values.yaml is using 0.75.2 which result in STS termination . 

config-reloader's image tag has no dependency on CRDs. The tag gets set to the chart's `appVersion`, i.e. the `tag` field is by default empty ([values.yaml](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml)):

```yaml
prometheusOperator:
  prometheusConfigReloader:
    image:
      registry: quay.io
      repository: prometheus-operator/prometheus-config-reloader
      # if not set appVersion field from Chart.yaml is used
      tag: ""
      sha: ""
```

Using image tag 0.75.2 does not cause the Prometheus pod to get terminated.

**Comment by numa1985** [comment]
@zeritti : Thanks for your response.

In 61.8.0 Prometheus works fine ,but in 62.2.1 or 62.3.0  am running into config  reloader issue ,not sure why this is happening in the newer version. kindly find the pod logs in the below snapshot for reference.

![image](https://github.com/user-attachments/assets/e77dee1c-de83-4367-b720-a57adf893119)

![image](https://github.com/user-attachments/assets/0460043c-8fa0-4fe7-bba2-cb716ffa165b)


![image](https://github.com/user-attachments/assets/847603ca-4350-44a5-940c-89e0688a29e6)

**Comment by numa1985** [comment]
After adding below snippet in the values.yaml manually it started working .

![image](https://github.com/user-attachments/assets/7edf050b-5968-4942-82f7-ea029d8e2c3b)

![image](https://github.com/user-attachments/assets/408c395c-34dc-4230-934c-d39cc0213ec0)
