### ISSUE TITLE
[kube-prometheus-stack] Can't set root_url

### ISSUE THREAD

**Issue by vhartmannselfee** [prometheus-community/helm-charts#4823]
### Describe the bug a clear and concise description of what the bug is.

Hello,

M

Best regards,

### What's your helm version?

3.15.4-1

### What's your kubectl version?

1.29.0

### Which chart?

kube-prometheus-stack

### What's the chart version?

61.9.0

### What happened?

I would like to have custom value in grafana.ini for root_url:

I put in my values.yaml:
grafana.ini:
  server:
    domain: grafana.prod.toto.info
    port: 80
    root_url: http://grafana.prod.toto.info

But it does'nt add these values to my grafana.ini stored in  prometheus-grafana configmap

Thanks for your help,

### What you expected to happen?

I expected changes in prometheus-grafana configmap

### How to reproduce it?

Install helm charts kube-prometheus-stack

### Enter the changed values of values.yaml?

grafana.ini:
  server:
    domain: grafana.prod.toto.info
    port: 80
    root_url: http://grafana.prod.toto.info

### Enter the command that you execute and failing/misfunctioning.

helm upgrade

**Comment by zeritti** [comment]
Unless you enable ingress, `domain`gets set to `''`as per the default [values](https://github.com/grafana/helm-charts/blob/44e86c586add0801084ce2c29e9afeb7da9e4126/charts/grafana/values.yaml#L800). Otherwise, `domain` gets set to an ingress host.

This should work (with a literal for domain in `root_url`):

```yaml
grafana:
  grafana.ini:
    server:
      http_port: 80
      root_url: http://grafana.prod.toto.info:%(http_port)s/
```

**Comment by vhartmannselfee** [comment]
Hi @zeritti , 
with http_port i have this error
`api.HTTPServer run error: failed to open listener on address 0.0.0.0:80: listen tcp 0.0.0.0:80: bind: permission denied`

When i only have 
`grafana:
  grafana.ini:
    server:
      root_url: http://grafana.prod.toto.info:%(http_port)s/`

It works !

Thanks for your help !
