### ISSUE TITLE
add traefik ingress to prometheus-kube-stack

### ISSUE THREAD

**Issue by dummys** [prometheus-community/helm-charts#483]
Hi,

Is it possible to add traefik ingress to the ingress options ? As there is nginx already implemented and nowadays there is lot of people that use traefik as ingress controller.
thanks.
I can help to test if needed.

**Comment by monotek** [comment]
Is the question to add traefiks ingress route or do you want to change the ingress class?
Adding other ingress implementations like traefiks ingress route is likely out of scope of the chart.

**Comment by dummys** [comment]
hum, so why do you implement nginx then ? If its out of scope. I didn't understand why using one and not the other than is more used right now

**Comment by monotek** [comment]
There is no "nginx implementation".

You can choose the ingressclass. 
Occurrence of "nginx" is an example. 
Just replace it with "traefik", if you want to use traefik as ingress controller.

P.S.: Please use Githubs issue template if you create issues.
