### ISSUE TITLE
[kube-prometheus-stack] Can't set assertNoLeakedSecrets in kube-prometheus-stack?

### ISSUE THREAD

**Issue by HyunSu1768** [prometheus-community/helm-charts#4852]
Hello there 👋,

I am using the kube-prometheus-stack helm chart, but the assertNoLeakedSecrets option in grafana is not visible in values.yaml. Could it be that I can't set it up?

**Comment by QuinnBast** [comment]
```
grafana:
  assertNoLeakedSecrets: false
```
