### ISSUE TITLE
 kube-prometheus-stack support for cgroup v2

### ISSUE THREAD

**Issue by alonapester** [prometheus-community/helm-charts#4859]
### Is your feature request related to a problem ?

Hello,
As of GKE version 1.32, the kuberenetes will start using cgroup v2, I wanted to make sure that the Prometheus stack will support that.
If it does, what versions support the cgroup v2? Do I need to do any updates for it to work?

### Describe the solution you'd like.

Making sure that kube-prometheus-stack will be ready for the upgrade for the cgroup v2 that will occur in a few months.
Also, please document what versions of cgroups can work with it.

### Describe alternatives you've considered.

Currently, if the kube-prometheus-stack won't be able to use cgroup v2 the current solution is to stay at an older kubernetes version, but this is a temporary solution.

### Additional context.

https://kubernetes.io/docs/concepts/architecture/cgroups/#migrating-cgroupv2

**Comment by jkroepke** [comment]
AKS (Azure) is using cgroup v2 by default since some months and there are no known issues.
