### ISSUE TITLE
[prometheus-operator-crds] update to current (0.77.1)

### ISSUE THREAD

**Issue by jcpunk** [prometheus-community/helm-charts#4892]
### Is your feature request related to a problem ?

The CRDs in the dedicated CRD chart do not match upstream's latest release.

### Describe the solution you'd like.

Update CRDs to current

### Describe alternatives you've considered.

NONE

### Additional context.

https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.77.1

**Comment by gaetanars** [comment]
Why do you close this issue after releasing cube-prometheus-stack and not prometheus-operator-crds?

**Comment by jkroepke** [comment]
Because I mis-read the title/issue.
