### ISSUE TITLE
[prometheus-kube-stack] Metrics missing after upgrading to 62.7.0.

### ISSUE THREAD

**Issue by ethicalmohit** [prometheus-community/helm-charts#4904]
### Describe the bug a clear and concise description of what the bug is.

We have upgraded from 51.10.0 to 62.7.0. We have deleted the CRD and apply new crd. Since, then we are not able to see a couple of metrics including container_cpu_cfs_throttled_periods_total and some container_fs metrics. Also, for some pods these widgets are working fine. 

### What's your helm version?

version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}

### What's your kubectl version?

Client Version: v1.31.1 Kustomize Version: v5.4.2 Server Version: v1.29.7-eks-a18cd3a

### Which chart?

kube-prometheus-stack

### What's the chart version?

62.7.0

### What happened?

After upgrade, Metrics missing and widgets are empty for some of the pods.

### What you expected to happen?

Ideally, We should be able to soon grafana widgets.

### Enter the command that you execute and failing/misfunctioning.

We are using ArgoCD to install this chart as it is without modification. 

### Screenshot
![Kubernetes-Compute-Resources-Pod-Dashboards-Grafana-10-08-2024_11_05_AM](https://github.com/user-attachments/assets/5087cbf8-d0be-4095-8668-4bed79cb4969)

**Comment by jkroepke** [comment]
The metrics are dropped since v37

https://github.com/prometheus-community/helm-charts/pull/2197/files

**Comment by ethicalmohit** [comment]
> The metrics are dropped since v37
> 
> #2197

So we have to explicitly remove them from drop list if we want to see? Because, For some of the pods its fine. 
Also, If we want them to staty dropped how can we also disable them from the dashboard too?

**Comment by ethicalmohit** [comment]
> The metrics are dropped since v37
> 
> #2197

Thanks, I have enabled them.

**Comment by jkroepke** [comment]
I re-check this on my AKS cluster, and i do not have that kind of issue, using AKS 1.29 / 1.30. Seems like the issue is related to EKS.
