### ISSUE TITLE
[alertmanager] templateFiles doesn't seem to be mounted inside pod

### ISSUE THREAD

**Issue by craig5** [prometheus-community/helm-charts#492]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-06-26T03:47:41Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
alertmanager

**Which version of the chart**:
0.2.0

**What happened**:
"templateFiles" is not mounted in the pod.

**What you expected to happen**:
Each key should be a file inside a directory on the pod/

**How to reproduce it** (as minimally and precisely as possible):

Added the following to the instance of the helm chart:
```
    helm:
      values: |
        <lots of other config>
        templateFiles: 
          default.tmpl: |-
           <template data>
```

**Comment by kmaris** [comment]
Hi @craig5 

I was dealing with something similar a bit ago and figured it out so I'm wondering if you're having the same issue as me. If you run `kubectl exec <alertmanager-pod-name> -c alertmanager -- cat /etc/alertmanager/config/` do you see `default.tmpl` in there?

If so, try adding the `templates` key to your global config. ie (watch the indentation too):

```yaml
values: |
  config:
    global:
      ... global stuff ...
    receivers:
      .... etc ...
    templates: '/etc/alertmanager/config/*.tmpl'
  templateFiles:
    default.tmpl: |-
      ...
```

**Comment by uvw** [comment]
@kmaris thanks, that is exactly what I noticed today. Your fix works 👍 

Might be worth extending the chart to list the `templateFiles` keys in `config.templates` automatically.

**Comment by uvw** [comment]
I realized that I am using the `kube-prometheus-stack` chart, not the `alertmanager`.
So, this issue definitely affects `kube-prometheus-stack`; not sure about the `alertmanager` though.

**Comment by craig5** [comment]
I hacked around the issue by creating a local "fork" of the chart. (So, I can't test this right now.)

I could create a PR with my diff so you can see what I did...

I should have some time next week/year to test the above. :)

**Comment by monotek** [comment]
PR would be welcome :)
