### ISSUE TITLE
[kube-prometheus-stack] Kubernetes has deprecated port 10251-10252 for controller manager and scheduler

### ISSUE THREAD

**Issue by vipinjn24** [prometheus-community/helm-charts#494]
**Is your feature request related to a problem? Please describe.**
Kubernetes has deprecated port 10251-10252 for controller manager and scheduler.
Now we have port 10257 for controller manager and 10259 for scheduler, they both are secure ports and requires authentication to fetch the metrics.

**Describe the solution you'd like**
Add the parameters that takes care of this in helm values.

**Describe alternatives you've considered**
No alternatives as of now.

**Comment by monotek** [comment]
There is already a pr for it:

https://github.com/prometheus-community/helm-charts/pull/490

**Comment by vipinjn24** [comment]
@monotek thanks got it figured out from the comments of PR on how to make it working.
And there is a pr for it so we can close this request.
