### ISSUE TITLE
[prometheus-node-exporter] kube-rbac-proxy volume mounts

### ISSUE THREAD

**Issue by alkur-gh** [prometheus-community/helm-charts#4953]
Hi, is there a proper way to mount TLS certificates into the kube-rbac-proxy container?
Currently, i just modified chart locally to mount .Values.secrets. https://github.com/prometheus-community/helm-charts/blob/5f64862e5d434ad33d358d4dae3b3256d7281e5c/charts/prometheus-node-exporter/templates/daemonset.yaml#L196

**Comment by zeritti** [comment]
> Hi, is there a proper way to mount TLS certificates into the kube-rbac-proxy container?

No, support for custom volume mounts in the proxy container is currently missing. Mounts from `secrets` apply to the Node Exporter container only.

**Comment by alkur-gh** [comment]
@zeritti Thanks!
