### ISSUE TITLE
[kube-prometheus-stack] Enable receiving grafana alerts with prometheus alert manager

### ISSUE THREAD

**Issue by EHJ-52n** [prometheus-community/helm-charts#4994]
### Describe the bug a clear and concise description of what the bug is.

I am new to grafana and prometheus and only an enduser, not a grafana or prometheus developer.

I cannot find any usable documentation on how to enable the prometheus alertmanager to receive grafana alerts using the values.yaml.

In the WebUI, it is just a button to click.
![image](https://github.com/user-attachments/assets/45d29397-5624-4a58-9707-3134446c313e)

How is this done using the values.yaml?

### What's your helm version?

version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}

### What's your kubectl version?

Client Version: v1.28.13 Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 Server Version: v1.29.2-r0-29.0.11.8

### Which chart?

kube-prometheus-stack

### What's the chart version?

kube-prometheus-stack-56.5.0	v0.71.2

### Enter the command that you execute and failing/misfunctioning.

there is none.

### Anything else we need to know?

Where is the best place to state questions like this?

Sorry for any caused inconvenience and thank you very much for your time!

**Comment by zeritti** [comment]
> In the WebUI, it is just a button to click.

That corresponds to the field `grafana.sidecar.datasources.alertmanager.handleGrafanaManagedAlerts`. 

If deploying data sources without the sidecar, the configuration parameter is `datasources.jsonData.handleGrafanaManagedAlerts` ([datasources](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources)). 

If enabled, the datasource will become a _candidate_ for receiving Grafana managed alerts - it will  receive the alerts once selected. 
This selection can probably be done in UI but certainly through the [ngalert](https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json) API (configuration). To my knowledge, Grafana currently does not support provisioning this feature.

**Comment by EHJ-52n** [comment]
>> In the WebUI, it is just a button to click.
>
> That corresponds to the field `grafana.sidecar.datasources.alertmanager.handleGrafanaManagedAlerts`.

Thank you very much. This did the trick and I am now receiving the alerts from my grafana alerting rules with the prometheus alert manager.

I added the following in my `values.yaml`:

```yaml
grafana:
  sidecar:
    datasources:
      alertmanager:
        handleGrafanaManagedAlerts: true
```
