### ISSUE TITLE
[prometheus] How to add new options for alert manager subchart?

### ISSUE THREAD

**Issue by alobandarifan** [prometheus-community/helm-charts#5013]
### Describe the bug a clear and concise description of what the bug is.

I want to change the alert manager service type to loadbalcner , but there's no such option.
From the comments, it has a service type option in  the chart https://github.com/prometheus-community/helm-charts/blob/main/charts/alertmanager/values.yaml, but the option is not available in the main chart

### What's your helm version?

version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"} 

### What's your kubectl version?

Client Version: v1.29.0                                                                                                                          Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3                                                                                          Server Version: v1.28.5

### Which chart?

prometheus-community chart

### What's the chart version?

latest

### Enter the command that you execute and failing/misfunctioning.

helm install prometheus-test prometheus-community/prometheus \                                                                                   -n monitor --create-namespace \                                                                                                                  -f prometheus-chart.yaml

**Comment by zeritti** [comment]
> I want to change the alert manager service type to loadbalcner , but there's no such option.

One can use any value that the subchart supports - a subchart is a standalone chart, afterall:

```yaml
alertmanager:
  service:
    type: LoadBalancer
```
