### ISSUE TITLE
[kube-prometheus-stack] broken Availability (30d) metrics

### ISSUE THREAD

**Issue by wlm277** [prometheus-community/helm-charts#5043]
### Describe the bug a clear and concise description of what the bug is.

After an upgrade of prometheus-kubec-stack (65.0.0 -> 66.2.2) some metrics display broken values in prometheus-kube-stack version 66.2.2

Previously this metric apiserver_request:availability30d showed right value ~"99%" after an update it shows "-71802.236%"

### What's your helm version?

Version:"v3.15.0-rc.2

### What's your kubectl version?

Server Version: v1.29.7

### Which chart?

prometheus-kube-stack

### What's the chart version?

66.2.2

### What you expected to happen?

Metric value should not change between updates

### Enter the command that you execute and failing/misfunctioning.

helm upgrade --install kube-stack-prometheus kube-prometheus-stack
--repo https://prometheus-community.github.io/helm-charts
--namespace monitoring

**Comment by ironashram** [comment]
indeed i see the same, last good version is 66.1.1, the issue is caused by this [commit](https://github.com/prometheus-community/helm-charts/commit/d6ab6a32094ce9876b3ff262637edfd6800546ce)

**Comment by M-A-X-I-M** [comment]
Same for us
![grafik](https://github.com/user-attachments/assets/11d3dec1-5f43-4bd9-a86d-6d83958117e5)

**Comment by StevenVdBGit** [comment]
> indeed i see the same, last good version is 66.1.1, the issue is caused by this [commit](https://github.com/prometheus-community/helm-charts/commit/d6ab6a32094ce9876b3ff262637edfd6800546ce)

Indeed I added a comment https://github.com/prometheus-community/helm-charts/commit/d6ab6a32094ce9876b3ff262637edfd6800546ce#r150204606

**Comment by Daniel-Vaz** [comment]
Related with https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/990
