### ISSUE TITLE
[prometheus] Support for ingressClassName in > Kubernetes 1.18

### ISSUE THREAD

**Issue by dhaas-genscape** [prometheus-community/helm-charts#507]
Is your feature request related to a problem? Please describe.
The annotation kubernetes.io/ingress.class will be deprecated. See https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation

Describe the solution you'd like
Support for the ingressClassName field for prometheus server and alertmanager ingress.

Similar to #265

**Comment by monotek** [comment]
would you mind to create a pr please?

**Comment by fede-r1c0** [comment]
Hi! im deploying pushgateway with ingress enabled and i was not rendering the value "ingressClassName". I see that the lines were not added in the PR # 507 
`spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
  {{- if .Values.pushgateway.ingress.ingressClassName }}
  ingressClassName: {{ .Values.pushgateway.ingress.ingressClassName }}
  {{- end }}
  {{- end }}`
  Adding this would be complete the support for ingressClassName, what do they say?
