### ISSUE TITLE
[prometheus-kube-stack] ScrapeConfig CRDs scrapeFallbackProtocol configuration not appear in the Prometheus configuration

### ISSUE THREAD

**Issue by kallaics** [prometheus-community/helm-charts#5074]
### Describe the bug a clear and concise description of what the bug is.

The Scrape CRDs are mapping the `scrapeFallbackProtocol` to `fallback_scrape_protocol` configuration item in Prometheus config. After the clusters upgraded from 67.2.0 to 67.3.0 this mapping not works anymore and the targets failing again, because the fallback_scrape_protocol is missing (maybe not mapped well into the config from the CRDs?).

The Scrape CRD contains the `scrapeFallbackProtocol` definition in case of 67.3.0 as well.

The solution currently to downgrade to 67.2.0.

### What's your helm version?

version.BuildInfo{Version:"v3.16.3", GitCommit:"cfd07493f46efc9debd9cc1b02a0961186df7fdf", GitTreeState:"dirty", GoVersion:"go1.23.3"}

### What's your kubectl version?

Client Version: v1.31.2 Kustomize Version: v5.4.2 Server Version: v1.30.6

### Which chart?

kube-prometheus-stack

### What's the chart version?

67.3.0

### What happened?

The Scrape CRDs are mapping the `scrapeFallbackProtocol` to `fallback_scrape_protocol` configuration item in Prometheus config. After the clusters upgraded from 67.2.0 to 67.3.0 this mapping not works anymore and the targets failing again, because the fallback_scrape_protocol is missing (maybe not mapped well into the config from the CRDs?).

The Scrape CRD contains the `scrapeFallbackProtocol` definition in case of 67.3.0 as well.

The solution currently to downgrade to 67.2.0.

### What you expected to happen?

Do not remove the fallback protocol configuration after the upgrade.

### How to reproduce it?

1. Deploy a kube-promethus-stack version 67.3.0 with CRDS.
2. Deploy a Scrape CRD,that include scrapeFallbackProtocol definition
3. Check the generated configuration and the `fallback_scrape_protocol` will missing.
If you try it with 67.2.0 will work well.

### Enter the changed values of values.yaml?

None

### Enter the command that you execute and failing/misfunctioning.

Add repo:

```bash
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
```

Install Promethus:

```bash
helm install prometheus prometheus-community/kube-prometheus-stack --version 67.3.0 -n monitoring --create-namespace
```

Prepare Scrape CRD:

```bash
cat << EOF > example-scrape-crd.yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: test
  namespace: monitoring
spec:
  jobName: test
  scrapeInterval: 30s
  scrapeTimeout: 3s
  metricsPath: '/metrics'
  scheme: HTTPS
  scrapeFallbackProtocol: PrometheusText1.0.0
  staticConfigs:
    - targets:
        - example.com
EOF
```

Deploy CRD:

```bash
kubectl apply -f example-scrape-crd.yaml
```

### Anything else we need to know?
Nothing

**Comment by kallaics** [comment]
ServiceMonitor also affected with same issue!

**Comment by Overglazed** [comment]
I have run into this issue this morning after upgrading to kube-prometheus-stack-67.3.0.  My servicemonitor resources no longer work with scrapeFallbackProtocol defined

**Comment by Luuk-Horsman-ISNL** [comment]
The field has been renamed from `scrapeFallbackProtocol` to `fallbackScrapeProtocol` in the CRDs. See https://github.com/prometheus-community/helm-charts/commit/513b4622bd5b87d50c0ee6d756ba133124446c70

**Comment by kallaics** [comment]
The issue looks like the CRDs are not upgraded in 67.3.0 well. Now works fine with version 67.4.0.
Thank you for your help and reply.
