### ISSUE TITLE
[CI] Python 3.7 not available in ubuntu-latest

### ISSUE THREAD

**Issue by zeritti** [prometheus-community/helm-charts#5082]
### Describe the bug a clear and concise description of what the bug is.

Step `actions/setup-python@5` in workflow job `lint-test` set with `python-version=3.7` fails as this version is not available in the current image `ubuntu-latest`. It appears that the image has already been updated to 24.04 which does not include python 3.7 any longer:

```console
  Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
  The list of all available versions can be found here:
  https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

Steps with that action fail, e.g. https://github.com/prometheus-community/helm-charts/actions/runs/12444946805/job/34745736173?pr=5053

On image update to Ubuntu 24.04: [Ubuntu-latest workflows will use Ubuntu-24.04 image](https://github.com/actions/runner-images/issues/10636)

The affected workflow jobs may need an adjustment.

**Comment by dotdc** [comment]
PR to fix: https://github.com/prometheus-community/helm-charts/pull/5085
