### ISSUE TITLE
[kube-prometheus-stack] Decomposition

### ISSUE THREAD

**Issue by xxxbobrxxx** [prometheus-community/helm-charts#510]
Hi!

Current implementation of kube-prometheus-stack is a monolith solution which makes possible to install prometheus components only once. If you need to have multiple Prometheus installations in cluster you can:

1. Install this chart one more time **but** you have to manually disable all components before which makes configuration more complex.
2. Install required components manually but it is less useful because kube-prometheus-stack already has all required resources for components work (services, ingresses, servicemonitors).

I can see some possible solutions:

1. Move prometheus, alertmanager and potentially thanos rule templates in separate helm charts and install them as dependencies.
2. Add an option to disable by default installation of all components.

What do you think about it?
Thanks!

**Comment by scottrigby** [comment]
In general this was part of the plan when we moved and renamed the chart, to simplify the charts where possible: phase 2 after moving them as-is. See https://github.com/prometheus-community/community/issues/28#issuecomment-670230344

**Comment by xxxbobrxxx** [comment]
Do you plan to finish this activity and if yes - do you have any estimations?
