### ISSUE TITLE
Install grafana only

### ISSUE THREAD

**Issue by chromafunk** [prometheus-community/helm-charts#529]
Is it possible to install grafana and its dashboards separately ? The thing is, I have a HA Thanos setup and I would like to get all the dashboards from this chart ! Thanks

**Comment by stylianosrigas** [comment]
Hey @chromafunk can you explain what you are trying to achieve? When you say separately what do you mean?

**Comment by monotek** [comment]
```
helm install grafana grafana/grafana
```

**Comment by stylianosrigas** [comment]
Yeap you can definitely install separately. Just set
```
grafana
    enabled: false
```
and install Grafana with a separate Helm deployment. You can configure the datasource to be the Prometheus or Thanos Query or anything.

**Comment by ergunozyurt** [comment]
```
grafana
    enabled: false
```

This field only prevents the predefined dashboards to be created and there seem to be no other configuration just for that.

This also mentioned in #127 which seems to be closed by the author minutes later. 
Not sure if they found out how to do it or closed the issue by mistake.

**Comment by stylianosrigas** [comment]
The grafana helm chart has its own configuration for dashboard creation. Why not to deploy the dashboards via the grafana helm chart?

**Comment by ergunozyurt** [comment]
That's certainly a way to do it. 
I guess, getting the dashboards at [/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14) without the grafana deployment would be less complicated and more specific for this chart.

**Comment by chromafunk** [comment]
thanks for your comments. I have finally gotten to the point where I am installing the grafana helm chart separately, but the dashboards are not there. As @ergunozyurt said, it would be nice if I can pull that repo directory and install them with the grafana chart separately, but can you point me to a doc showing how to achieve this ? Thank you
