### ISSUE TITLE
[prometheus] prometheus.io/scheme annotation ignored for pods (and services)

### ISSUE THREAD

**Issue by inistor** [prometheus-community/helm-charts#533]
**Is your feature request related to a problem? Please describe.**
The `prometheus.io/scrape`, `/port`, `/path` and `/scheme` are used for endpoints (kubernetes-service-endpoints, kubernetes-service-endpoints-slow) but, for pods and services, `prometheus.io/scheme` is ignored (not used).
Due to this, if a pod exposes the prometheus metrics on a TLS (https) port, it cannot be scraped. 

**Describe the solution you'd like**
`prometheus.io/scheme` is clearly excluded from the configuration (example, for pods, in  f4d1f5fb63cbf08e1a9f95e66e69539e05f89a55, charts/prometheus/values.yaml:1553 and charts/prometheus/values.yaml:1554) so it looks to me like a deliberate decision - maybe I am missing something.
Scrape jobs for pods, at least (I think services, too), should take into account `prometheus.io/scheme` and update the `__scheme__` label, just as for endpoints.

**Describe alternatives you've considered**
Again, maybe I am missing something, but I don't see how this could be addressed otherwise.

**Additional context**
N/A

**Comment by monotek** [comment]
Would you mind tio create a pr?
Should be pretty straight forward to add it around: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1514

**Comment by monotek** [comment]
Thanks :)

**Comment by inistor** [comment]
> Would you mind tio create a pr?
> Should be pretty straight forward to add it around: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L1514

Someone else did it  - thanks
I was hesitant, as I assumed this was omitted on purpose.

**Comment by inistor** [comment]
Just an addition - for services it's still not done - is this intended?
