### ISSUE TITLE
All containers used by this kube-prometheus should be tied to a well known entity

### ISSUE THREAD

**Issue by MrD2** [prometheus-community/helm-charts#538]
Notice on https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml:

repository: docker.io/jimmidyson/configmap-reload

**Comment by monotek** [comment]
Would you mind to provide a pr please?

**Comment by MrD2** [comment]
I don't have access to the project official repos

**Comment by mrueg** [comment]
This one is deprecated with https://github.com/prometheus-operator/prometheus-operator/pull/3457 so with prometheus-operator-0.43.0 or later you should be able to run without it. It will be removed in prometheus-operator 0.45.0
