### ISSUE TITLE
[kube-prometheus-stack]  Exclude or alter default prometheus alert rules

### ISSUE THREAD

**Issue by va3093** [prometheus-community/helm-charts#542]
### Problem
The [prometheus templates](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus) define many rules that get automatically applied in my cluster when I deploy the `kube-prometheus-stack`. Most of these rules are amazing (thank you 🙏) but there are a few that I would like to exclude or change.

### Desired solution
1. It would be amazing if I could specify a field in the `values.yml` like `alertRulesToExclude` where I could simply provide a list of alert rule ids that would be excluded.
2. It would be amazing if I could provide an a field in the `values.yml` like `alertRulesToOverride` where I coul specify a list of objects that would make it possible to do things like change the `promql` expression of a given alert.

**Comment by monotek** [comment]
Please us the issue template. It's not clear which chart you're talking about.

**Comment by va3093** [comment]
@monotek I have updated the issue slightly. Hope that is better.

**Comment by va3093** [comment]
@monotek Friendly ping 🙂

**Comment by mortaelth** [comment]
agree. If one rule causes an issue, it would be ideal to either turn it off or alter it. Currently it would require to disable creation of the whole group of rules and somehow managed them on your own. => hard to keep up with future changes to the default rules.

**Comment by monotek** [comment]
You can disable single rules now. See: 
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L76
