### ISSUE TITLE
[kube-prometheus-stack] Premature end block in Prometheus resource

### ISSUE THREAD

**Issue by aiyengar2** [prometheus-community/helm-charts#550]
**Describe the bug**
A [premature end block](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L264-L265) causes the rendered manifest to be invalid if prometheus.enabled=false and a following field is set.

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 11.0.3

**What happened**:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [apiVersion not set, kind not set]
```

**What you expected to happen**:

No failure

**How to reproduce it** (as minimally and precisely as possible):

After building the deps:
```
$ helm install --dry-run kube-prometheus-stack charts/kube-prometheus-stack/ --set prometheus.enabled=false --set prometheus.prometheusSpec.enforcedNamespaceLabel="hello" > output.yaml 
```

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
prometheus:
  enabled: false
  prometheusSpec:
    enforcedNamespaceLabel: "hello"
```

**The helm command that you execute and failing/misfunctioning**:

```
$ helm install --dry-run kube-prometheus-stack charts/kube-prometheus-stack/ --set prometheus.enabled=false --set prometheus.prometheusSpec.enforcedNamespaceLabel="hello" > output.yaml 
```

**Anything else we need to know**: 

The fix should be pretty straightforward, as executed in https://github.com/rancher/charts/pull/923/files

**Comment by monotek** [comment]
Would you mint to add an pr with the fix please?
