### ISSUE TITLE
[kube-prometheus-stack] Support customized certificate duration when using cert-manager as tls certificate provisioner

### ISSUE THREAD

**Issue by ethernoy** [prometheus-community/helm-charts#551]
**Is your feature request related to a problem? Please describe.**
cert-manager support in prometheus operator admission webhook does not support customized duration. It is hardcoded to be 1 year. Moreover, its hardcoded value "8760h" is parsed as 8760h0m0s when applied in k8s, which may cause trouble in automatically managed k8s environment like ArgoCD (it will assume 8760h is different from 8760h0m0s and keep synchronizing, which is unnecessary)

**Describe the solution you'd like**
Support customized certificate duration (e.g. add a field in value file `.Values.prometheusOperator.admissionWebhooks.certManager.duration`). I can create a pull request if I am allowed to do so.

**Describe alternatives you've considered**
Replace 8760h with 8760h0m0s.

**Additional context**
N/A

**Comment by aslafy-z** [comment]
This PR should be reopened! I've seen this was already implemented for prometheus-adapter, it's a trivial change. @ethernoy I'm sure you can open a PR to tackle this or I will have to do so anyway.

**Comment by ethernoy** [comment]
> This PR should be reopened! I've seen this was already implemented for prometheus-adapter, it's a trivial change. @ethernoy I'm sure you can open a PR to tackle this or I will have to do so anyway.

sure, happy to do it 

;)

**Comment by aslafy-z** [comment]
> > This PR should be reopened! I've seen this was already implemented for prometheus-adapter, it's a trivial change. @ethernoy I'm sure you can open a PR to tackle this or I will have to do so anyway.
> 
> @aslafy-z
> sure, happy to do it 
> 
> Update:
> The duration set in Certificate CR is already updated to comply with cert-manager format. However it is still valuable to support customization on the duration. Should I do it?

I'd say yes
