### ISSUE TITLE
[prometheus-pingdom-exporter] Pingdom exporter chart not published in repo

### ISSUE THREAD

**Issue by mcanevet** [prometheus-community/helm-charts#558]
**Describe the bug**
The `prometheus-pingdom-exporter` chart is not published in helm repo.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

**Which chart**: prometheus-pingdom-exporter

**Which version of the chart**: 2.3.1

**What happened**: not available in helm repo

**What you expected to happen**: helm chart available in repo

**How to reproduce it** (as minimally and precisely as possible):

```shell
$ helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
$ helm search repo prometheus-community | grep -i pingdom
<nothing>
```

**Comment by mcanevet** [comment]
Action of last push workflow on code change in this chart : https://github.com/prometheus-community/helm-charts/runs/1364220774?check_suite_focus=true

**Comment by mcanevet** [comment]
I don't understand how the release process works.
If I look at some actions on push on commits related to kube-prometheus-stack (https://github.com/prometheus-community/helm-charts/runs/1677864916?check_suite_focus=true), it compares with the latest release : `Discovering changed charts since 'kube-prometheus-stack-12.11.2'`, but with other charts, statsd-exporter for example (https://github.com/prometheus-community/helm-charts/runs/1674499512?check_suite_focus=true), it compares with the `prometheus` chart, not `prometheus-statsd-exporter` : `Discovering changed charts since 'prometheus-13.0.3'`.
For the pingdom-exporter chart, it also discover changes since an old version of the `prometheus` chart, not the `prometheus-pingdom-exporter` chart... But this time, it does not find any differences, and thus it does not release the chart on the repo (at least that's my comprehension of the problem)

**Comment by monotek** [comment]
@torstenwalter @scottrigby 

Seems there is something broken.

There is at least a release for version 2.3.0 of the chart: https://github.com/prometheus-community/helm-charts/releases/tag/prometheus-pingdom-exporter-2.3.0 

But that release can't be found in the index.yaml: https://prometheus-community.github.io/helm-charts/index.yaml

The release for version 2.3.1 was not created: https://github.com/prometheus-community/helm-charts/runs/1364220774?check_suite_focus=true

I've created a new pr with version 2.3.2: https://github.com/prometheus-community/helm-charts/pull/561
