### ISSUE TITLE
Relabelings in pushgateway service monitor

### ISSUE THREAD

**Issue by MightGainer** [prometheus-community/helm-charts#566]
Hello everybody! I am new to the community and I would like to add relabelings in [ServiceMonitor](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-pushgateway/templates/servicemonitor.yaml) for pushgateway.

**Is your feature request related to a problem? Please describe.**
We have got some big cardinality metrics collected from different machines to pushgateway. There is no possible way to reduce cardinality, so we want to use relabelings and remove/replace some labels.

For possible future issues it is good to add metricsRelabelings support also.

**Describe the solution you'd like**
Here is a simple way to implement this:

```yaml
    <...>
    {{- with .serviceMonitor.relabelings }}
    relabelings:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    <...>
```

**Describe alternatives you've considered**
As an alternative we have to create a serviceMonitor with relabelings and disable it in the pushgateway chart.

**Comment by monotek** [comment]
Will be closed by: https://github.com/prometheus-community/helm-charts/pull/567
