### ISSUE TITLE
[prometheus] Upgrade from 13.1.0 to 13.2.0 fails - label selector field is immutable for kube-state-metrics

### ISSUE THREAD

**Issue by petarGitNik** [prometheus-community/helm-charts#568]
**Describe the bug**

Cannot upgrade prometheus chat from version 13.1.0 to 13.2.0 - kube state metrics fails with `Upgrade "prometheus" failed: cannot patch "prometheus-kube-state-metrics" with kind Deployment: Deployment.apps "prometheus-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"prometheus", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable`.

**Version of Helm and Kubernetes**:

Helm Version:

```console
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

Kubernetes Version:

```console
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-gke.1600", GitCommit:"7c407f5cc8632f9af5a2657f220963aa7f1c46e7", GitTreeState:"clean", BuildDate:"2020-12-07T09:22:27Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:

prometheus-community/prometheus

**Which version of the chart**:

13.1.0 / 13.2.0

**What happened**:

Upgrade rolled back to working version.

**What you expected to happen**:

New release.

**How to reproduce it** (as minimally and precisely as possible):

1. Deploy version 13.1.0
2. Upgrade to 13.2.0

**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
alertmanager:
  strategy:
    type: Recreate

server:
  statefulSet:
    enabled: true

pushgateway:
  strategy:
    type: Recreate
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm upgrade prometheus prometheus-community/prometheus --install --atomic --cleanup-on-fail --namespace prometheus --version 13.2.0 --values values.yaml
```

**Helm values set after installation/upgrade:**

```console
alertmanager:
  strategy:
    type: Recreate
server:
  statefulSet:
    enabled: true
pushgateway:
  strategy:
    type: Recreate
```

**Anything else we need to know**:

N/A

**Comment by Skaronator** [comment]
This is a issue with switching from the helm/stable to the bitnami repository for the kube-state-metrics helm chart. I think best workaround is to disable kube-state-metrics and delete everything and then just re-enable it again.

Disable kubeStateMetrics in your values.yaml
```
kubeStateMetrics:
  enabled: false
```

Apply helm chart..

re-enable it again (or delete it from your values.yaml since its enabled by default)

```
kubeStateMetrics:
  enabled: true
```

**Comment by petarGitNik** [comment]
Thank you.

**Comment by piec** [comment]
I had the issue and @Skaronator's solution worked for me :+1:

**Comment by vhosakot** [comment]
saw same error when helm upgrading prometheus `14.6.0` to `15.6.0`:
```
Error: UPGRADE FAILED: cannot patch "monitor-kube-state-metrics" with kind Deployment: Deployment.apps "monitor-kube-state-metrics" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitor", "app.kubernetes.io/name":"kube-state-metrics"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
per https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150, deleting `kube-state-metrics` deployment and then re-trying helm upgrade worked and prometheus was successfully upgraded to `15.6.0`.

**Comment by eins** [comment]
> This is a issue with switching from the helm/stable to the bitnami repository for the kube-state-metrics helm chart. I think best workaround is to disable kube-state-metrics and delete everything and then just re-enable it again.
> 
> Disable kubeStateMetrics in your values.yaml
> 
> ```
> kubeStateMetrics:
>   enabled: false
> ```
> 
> Apply helm chart..
> 
> re-enable it again (or delete it from your values.yaml since its enabled by default)
> 
> ```
> kubeStateMetrics:
>   enabled: true
> ```

@Skaronator this worked for me. thanks a lot
from prometheus-15.0.3 to  prometheus-15.8.5
