### ISSUE TITLE
[kube-prometheus-stack] How to copy pod labels to metrics

### ISSUE THREAD

**Issue by bentatham** [prometheus-community/helm-charts#569]
I cannot figure out where to put the relabel config to copy pod labels to metrics.

Specifically, I am looking to get my custom pod labels onto `container_cpu_usage_seconds_total` and other similar metrics.

I have tried adding both specific relabel config, as well as general:

```yaml
- action: labelmap
  regex: __meta_kubernetes_pod_label_(.+)
```
in almost every place I can think of in the Helm values for kube-prometheus-stack (basically any/all components with `relabelings` or `metricRelabelings`), but it does not seem to work.

You could see this issue as a cry for help, but I see it as bug report about documentation of something that I imagine many people need to do, and thus should be documented well.  Thanks for your help!

**Version of Helm and Kubernetes**:

Helm Version: 
```console
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

Kubernetes Version: (EKS)
```console
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 9.4.8

**Comment by StepanKuksenko** [comment]
@bentatham did you managed to figure out how to do this ? 
i also need to add pods labels to kubelet metrics like container_cpu_usage_seconds_total

**Comment by adammwood** [comment]
This is an upstream issue with cAdvisor not exporting pod labels, i.e. there's no way for Prometheus to get them as they don't exist on these metrics.

See this 6 year old issue regarding it: https://github.com/kubernetes/kubernetes/issues/32326

**Comment by lutz108** [comment]
I "solved" that be joining the metrics with kube-state-metrics/kubelet, which does scrape the labels
```
(some promQL query/expression for {job="kubernetes-nodes-cadvisor"} metric calculation)
*
on(pod) # use the pod name (unique per job) as base for the join
group_left(
    # add all the KSM labels you want to have in the resource metric
  cluster,
  gitlab_runner_job_id,
  gitlab_runner_job_name,
  ...
)
(
  max(kube_pod_annotations) # the kube-state-metrics/kubelet metric that contains the job labels we need
  by(
    # this will ensures uniqueness. Otherwise there may be more than one KSM related to the KNCA metric
    pod,
    container,
    cluster,
    gitlab_runner_job_id,
    ...,
  )
)```
