### ISSUE TITLE
Chart release process not updating 'generated' field

### ISSUE THREAD

**Issue by Niksko** [prometheus-community/helm-charts#577]
**Describe the bug**
The `generated` field of the Helm repository is not being updated when releasing new charts. I _think_ this is what's causing my installation of Flux to fail to find the latest Helm chart version.

**What happened**:

```
$ curl -s https://prometheus-community.github.io/helm-charts/index.yaml | grep generated
generated: "2020-09-27T05:31:40.762116-04:00"
```

**What you expected to happen**:

The `generated` date in the `index.yaml` should match the last time the index was regenerated.

**Comment by Niksko** [comment]
Seems like this is caused by this issue: https://github.com/helm/chart-releaser/issues/90

**Comment by onedr0p** [comment]
This has been fixed in the chart releaser action no version released yet.
