### ISSUE TITLE
prometheus fails on ssl validation when communication to external alertmanager instance

### ISSUE THREAD

**Issue by chitha20** [prometheus-community/helm-charts#597]
We are setting up external alertmanager and prometheus using the charts provided here.

Now we have alertmanager running on https://alertmanager.xyz which is in cluster-a

We have prometheus up and running on https://prometheus-test.xyz in cluster-b

We are trying to configure alertmanger with prometheus to send alarms with below config in operator helm chart.

    additionalAlertManagerConfigs:
    - tls_config:
        insecureSkipVerify: true
    - static_configs:
      - targets: ['alertmanager-xyz']

however the ssl validation always fails and it cannot send alarm . i dont see a good info around this on how to disable ssl validation for external alerts?

Also alert from the prom pod which looks like "insecureSkipVerify" is not supported ?

2.969Z"}
{"caller":"main.go:672","err":"couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: yaml: unmarshal errors:\n  line 623: field insecureSkipVerify not found in type config.plain","level":"error","msg":"Error reloading config","ts":"2021-01-20T13:00:52.973Z"}

Any leads or help here would be awesome

**Comment by chitha20** [comment]
Also i have tried 

```
      tls_config:
        insecure_skip_verify: true
```

**Comment by gbavoz1** [comment]
Did you solve the issue? I'm in the same boat
