### ISSUE TITLE
[prometheus-kafka-exporter] Use secret/configmap for kafka-server

### ISSUE THREAD

**Issue by arvidviderberg** [prometheus-community/helm-charts#599]
**Is your feature request related to a problem? Please describe.**
It's not possible to use a secret/configmap value to set the [Kafka server url](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-kafka-exporter/templates/deployment.yaml#L28) in the starting container. 

**Describe the solution you'd like**
If it was possible to set environment variables for the container, it would possible to use a secret/configmap to set the kafka server. This would be possible by inserting the environment variable name as a part of the `kafka-server` string list.

**Describe alternatives you've considered**
I've tried using `valueFrom` in the `kafka-server` list but that doesn't work since `valueFrom` is a map.

**Additional context**
[Here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-kafka-exporter/values.yaml#L19) is were the `kafka-server` is set.

I'd be happy to implement this feature.

**Comment by golgoth31** [comment]
Hi, thank you for your work.
Using env variables will not work with the current default kafka-exporter image because it doesn't support them (see here: danielqsj/kafka_exporter#64).

regards

**Comment by arvidviderberg** [comment]
@golgoth31 I think you misunderstood how the env vars would be used. I explained it with an example in the PR #601.
