### ISSUE TITLE
Error: apiVersion 'v2' is not valid. The value must be "v1"

### ISSUE THREAD

**Issue by mattronix** [prometheus-community/helm-charts#607]
**Describe the bug**
Unable to use Terraform Helm 3 to install Prometheus chart on our K8S Cluster. 

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
prometheus-community/prometheus 

**Which version of the chart**:
"13.2.1"

**What happened**:
Error occurs whenever helm tries to deploy the chart.

**What you expected to happen**:
Helm would deploy the chart and stack would come up.

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

Install Chart using the Terraform Helm Provider (version of helm 3)

**Comment by Skaronator** [comment]
You're using a client with 1.19 on a server with 1.15. Kubectl only support one patch above or below so only 1.14 - 1.16 clients work with your server. Non the less, you should upgrade your server ;)

**Comment by monotek** [comment]
which version of helm.is installed? Is this still helm 2.x.x?

**Comment by lyz-code** [comment]
I have the same error, but with helm 2.16.1, was the support for helm 2 dropped?

**Comment by Skaronator** [comment]
Helm 2 is EOL for like 5 month now so yes Helm 2 support was dropped in #387

**Comment by mattronix** [comment]
Ah good to know we are moving to helm 3 anyway but did not know it was EOL already

**Comment by SarasaGunawardhana** [comment]
If you are using helm **v2** and if you want to install **Prometheus chart on our K8S Cluster**, use the version tag to pass supported version.  **--version v11.0.0**

helm install prometheus-community/kube-prometheus-stack --name kube-prometheus-stack --values values.yaml --version v11.0.0

If you are not running other helm charts using v2, It is better to upgrade helm v2 to v3 and install the charts.
