### ISSUE TITLE
[kube-prometheus-stack] Duplicate services matched by kubelet rule causing PrometheusRuleFailures

### ISSUE THREAD

**Issue by Foltik** [prometheus-community/helm-charts#614]
**Describe the bug**
When deploying a fresh install of kube-prometheus-stack with no config changes, Prometheus immediately starts failing to evaluate rules related to the kubelet.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

I bootstrapped my cluster with kubeadm on Debian 10 with no other config changes.

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 13.0.2

**What happened**:

Just prefacing this with the fact that I'm new to prometheus-operator and kubernetes in general, so I may be misunderstanding some aspects of this.

After deploying with no config changes, Prometheus fails to evaluate rules related to the kubelet:

```console
$ helm install prom prometheus-community/kube-prometheus-stack --version 13.0.2 -n monitoring --create-namespace
$ kubectl logs prometheus-prom-kube-prometheus-stack-prometheus-0 -n monitoring -c prometheus
level=warn ts=2021-01-24T18:41:00.447Z caller=manager.go:598 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.99\"\n" err="found duplicate series for the match group {instance=\"10.16.3.1:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.16.3.1:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"pylon\", service=\"prom-kube-prometheus-stack-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.16.3.1:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"pylon\", service=\"kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
```

Similarly to #192, this appears to be because of multiple services in `kube-system` being picked up as endpoints by the rule, in this case `kubelet` and `kube-prometheus-stack-kubelet`:

![2021-01-22-130646_1420x411_escrotum](https://user-images.githubusercontent.com/5026551/105642106-b6f9fe00-5e55-11eb-8371-dbc81114f0b7.png)

![2021-01-24-150746_1003x282_escrotum](https://user-images.githubusercontent.com/5026551/105642157-fde7f380-5e55-11eb-928e-ce241fb6c273.png)

Looking at the ServiceMonitor, I see it matches services based on the selector `k8s-app=kubelet`
```console
$ kubectl describe servicemonitor prom-kube-prometheus-stack-kubelet -n monitoring
# ...
  Selector:
    Match Labels:
      k8s-app:  kubelet
# ....
```

Which matches the two services I see in Prometheus:

```console
$ kubectl get svc -n kube-system -l k8s-app=kubelet
NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                        AGE
kubelet                              ClusterIP   None         <none>        10250/TCP,10255/TCP,4194/TCP   5d13h
prom-kube-prometheus-stack-kubelet   ClusterIP   None         <none>        10250/TCP,10255/TCP,4194/TCP   90m
```

I tried deleting the `prom-kube-prometheus-stack-kubelet` service, which temporarily fixes the issue. When the service is not present the rules no longer fail, however after some amount of time the service is re-created by the operator or something, so the rule failures start happening again.

**What you expected to happen**:

It seems to me that the `kube-prometheus-stack-kubelet` created in the `kube-system` service isn't needed and is causing failures.

**How to reproduce it**:

Deploy the chart with no config changes, and failures will start showing up in the logs.

**Helm values set after installation/upgrade:** None

**Comment by mprzygrodzki** [comment]
Same thing on my side, fresh install on clean EKS cluster, Prom is failing to evaluate following rules:

```
rule_group=/etc/prometheus/rules/prometheus-k8s-prometheus-kube-promet-prometheus-rulefiles-0/monitoring-k8s-prometheus-kube-promet-kubernetes-system-kubelet.yaml;kubernetes-system-kubelet``` 

Example log from Prom pod:

```
level=warn ts=2021-01-24T21:56:58.418Z caller=manager.go:598 component="rule manager" group=kubernetes-system-kubelet msg="Evaluating rule failed" rule="alert: KubeletPodStartUpLatencyHigh\nexpr: histogram_quantile(0.99, sum by(instance, le) (rate(kubelet_pod_worker_duration_seconds_bucket{job=\"kubelet\",metrics_path=\"/metrics\"}[5m])))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}\n  > 60\nfor: 15m\nlabels:\n  severity: warning\nannotations:\n  description: Kubelet Pod startup 99th percentile latency is {{ $value }} seconds\n    on node {{ $labels.node }}.\n  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeletpodstartuplatencyhigh\n  summary: Kubelet Pod startup latency is too high.\n" err="found duplicate series for the match group {instance=\"10.10.65.247:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.10.65.247:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-10-65-247.eu-central-1.compute.internal\", service=\"k8s-prometheus-staging-kubelet\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.10.65.247:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"ip-10-10-65-247.eu-central-1.compute.internal\", service=\"k8s-prometheus-kube-promet-kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"```

**Comment by Foltik** [comment]
This is still an issue

**Comment by DefunctExodus** [comment]
Seeing the same thing on a fresh install. I can't find a way around it since I am using argo to deploy and the service always gets re-applied.

**Comment by casey-robertson** [comment]
Same issue here...... we hadn't touched Prometheus in a while and I'm working through installation of the kube-prometheus chart to get things up to date and running into this.

**Comment by muffl0n** [comment]
My workaround was to patch the ServiceMonitor "kube-prometheus-stack-kubelet".
was:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
  ...
  selector:
    matchLabels:
      k8s-app: kubelet
```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
spec:
  ...
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: prometheus-operator
      k8s-app: kubelet
```

**Comment by monotek** [comment]
Would you mind to create an or with your change?

**Comment by muffl0n** [comment]
I actually just patched the resource in Kubernetes by hand. But I'll see if I can craft an appropriate PR.

**Comment by muffl0n** [comment]
Please check the PR #860. Weird thing is: I have this additional service "kubelet" only on one of several clusters (GKE) and I'm not quite sure where it came from.
```
kube-prometheus-stack-kubelet                   ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   39d
kubelet                                         ClusterIP   None          <none>        10250/TCP,10255/TCP,4194/TCP   31d
```

**Comment by igrowheart** [comment]
> My workaround was to patch the ServiceMonitor "kube-prometheus-stack-kubelet" by adding an additional matchLabel:
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> ...
> spec:
>   ...
>   selector:
>     matchLabels:
>       k8s-app: kubelet
> ```
> 
> -->
> 
> ```
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> ...
> spec:
>   ...
>   selector:
>     matchLabels:
>       app.kubernetes.io/managed-by: prometheus-operator
>       k8s-app: kubelet
> ```

I have exactly the same issue as Foltik mentioned. Cannot solve the issue with this workaround.

**Comment by dewnull** [comment]
I added an additional label to the **service** for kublet and the matchLabels for the **servicemonitor** 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: core-kube-prometheus-stack-kubelet
  namespace: kube-system

  labels:
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: kubelet
    k8s-app: kubelet
  + release: core
...
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-kube-prometheus-stack-kubelet
  namespace: monitoring
 ...
spec:
...
  selector:
    matchLabels:
      app.kubernetes.io/name: kubelet
      k8s-app: kubelet
    + release: core
```

**Comment by jsalatiel** [comment]
> When you delete helm instance it doesn't delete `{{.Release.Name}}-kube-prometheus-stack-kubelet` service. When you create a new instance with a new name – you've got 2 services match the ServiceMonitor label and duplicated entry. I assume there's an error in the Chart delete sequence. Just remove the old kubelet service and you good to go

Where exactly should be that service ? When I helm uninstall I can see nothing remaining on the monitoring namespace. ( Namespace where I deploy the stack )

**Comment by a-thomas-22** [comment]
> > When you delete helm instance it doesn't delete `{{.Release.Name}}-kube-prometheus-stack-kubelet` service. When you create a new instance with a new name – you've got 2 services match the ServiceMonitor label and duplicated entry. I assume there's an error in the Chart delete sequence. Just remove the old kubelet service and you good to go
> 
> Where exactly should be that service ? When I helm uninstall I can see nothing remaining on the monitoring namespace. ( Namespace where I deploy the stack )

Should be in the kube-system namespace

**Comment by northonheld** [comment]
The problem still exists I'm using Chart version 58.6.0 . I did a test installation on a newly created cluster "v1.28.9-eks". Then I re-installed Prometheus Operator and started getting the errors described in this issue. I had to delete my first service test, which was created in the kube-system namespace. Helm isn't deleting this service, leaving behind dirt from old installations.

**Comment by PT-GD** [comment]
For EKS clusters is it possible that this feature added in k8s v1.28 and above is the issue:

https://docs.aws.amazon.com/eks/latest/userguide/view-raw-metrics.html#fetch-metrics-prometheus 

This is supposedly metrics for only the EKS control plane, which should not be the same instances as the worker nodes, though.

**Comment by PT-GD** [comment]
I take it back:

```
$ kubectl get -n kube-system  svc kube-prometheus-stack-kubelet prometheus-kube-prometheus-kubelet  --show-labels 
NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                        AGE     LABELS
kube-prometheus-stack-kubelet        ClusterIP   None         <none>        10250/TCP,10255/TCP,4194/TCP   25d     app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=kubelet,k8s-app=kubelet
prometheus-kube-prometheus-kubelet   ClusterIP   None         <none>        10250/TCP,10255/TCP,4194/TCP   2d19h   app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=kubelet,k8s-app=kubelet

```

So for some reason I have a 25d duplicate (old name) service. Was a bug filed for the failure to delete the (renamed?) service?

**Comment by TsengSR** [comment]
> When you delete helm instance it doesn't delete `{{.Release.Name}}-kube-prometheus-stack-kubelet` service. When you create a new instance with a new name – you've got 2 services match the ServiceMonitor label and duplicated entry. I assume there's an error in the Chart delete sequence. Just remove the old kubelet service and you good to go

Thanks man! That was the vital pointer. It seems that installing and uninstalling it a few times while fiddling around with the name and meta data (the default pvc name is hillariously long, blowing my k9s into pieces with its half-screen sized name) has created a few services there with different names that were not deleted when uninstalling. 

Uninstalling it, deleting all services and installing again and now it works. I had 4 times (!!!) inflated memory usage. 750 MB would show as 3 GB memory usage in there. 

Can't imagine this bug is still there 4 years later. I'd look into it, but I still have nightmares trying to patch our companies helm charts. 

But where exactly is the bug here? Is the service really supposed to run in kube-system namespace? Sounds odd to mee and someone contruary to the all-in-one-namespace where you can just delete the name space to delete all traces of it. 

@monotek Was that service really intended to be in the kube-system namespace? Do you know that?
