### ISSUE TITLE
prometheus-kube-stack CRD yaml has .status - which causes validation issues

### ISSUE THREAD

**Issue by simon-anz** [prometheus-community/helm-charts#632]
**Describe the bug**
Failed to validate CRD yaml before applying, because of invalid .status element

**Version of Helm and Kubernetes**:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-prometheuses.yaml#L4420

Causes issue with (in this case) "nomos vet" from Anthos

```
[1] KNV1045: Configs with "status" specified are not allowed. To fix, either remove the config or remove the "status" field in the config:

metadata.name: alertmanagerconfigs.monitoring.coreos.com
group: apiextensions.k8s.io
version: v1
kind: CustomResourceDefinition

For more information, see https://cloud.google.com/anthos-config-management/docs/reference/errors#knv1045


[2] KNV1045: Configs with "status" specified are not allowed. To fix, either remove the config or remove the "status" field in the config:
```

**Comment by monotek** [comment]
This shoud be a bug in the prometheus operator repo as the crds are copied from there.
See: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-alertmanagerconfigs.yaml#L1
