### ISSUE TITLE
[kube-prometheus-stack] how to use mixins with the chart?

### ISSUE THREAD

**Issue by mtb-xt** [prometheus-community/helm-charts#653]
Hi everyone,

could anyone point out to me, if Im using kube-prometheus-stack, how can I add and deploy additional monitoring mixins?

**Comment by shilpa-0** [comment]
Hi,
I have the same question. I couldn't find any option in kube-prometheus-stack helm chart to deploy additional mixins.

**Comment by CaptAintHere** [comment]
Hi,
Were you able to find a solution @mtb-xt? I would also like to deploy additional mixins directly within the Helm chart.
Thanks

**Comment by mtb-xt** [comment]
Sorry, no, still trying to figure it out
