### ISSUE TITLE
Upgraded prometheus-server POD stuck in ContainerCreating

### ISSUE THREAD

**Issue by jorotg** [prometheus-community/helm-charts#655]
Hi guys,
 
 Almost every time I need to change some values in the helm chart and execute:

`helm upgrade -f values_mine.yaml prometheus ./ -n monitoring`

my new/upgraded prometheus-server POD gets stuck in:

`prometheus-server-bf867fc59-bzhhl                 0/2       ContainerCreating     0            10m`

  When checking with **kubectl describe pods prometheus-server-bf867fc59-bzhhl -n monitoring** I get:

`Warning  FailedAttachVolume  3m28s  attachdetach-controller  Multi-Attach error for volume "pvc-15980b33-e57f-4f68-bed6-f72f9318415e" Volume is already used by pod(s) prometheus-server-5b9dd7db67-rgbq2`

  `Warning  FailedMount         85s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[config-volume prometheus-server-token-6mtkb storage-volume]: timed out waiting for the condition`
  
 
  I don't know why does this happen but reinstalling the release is not acceptable option for me.

**Comment by monotek** [comment]
Please use the issue template and also add the values you've used.

**Comment by jorotg** [comment]
**Describe the bug**
Almost every time I need to change some values in the helm chart my new/upgraded prometheus-server POD gets stuck in:

prometheus-server-bf867fc59-bzhhl 0/2 ContainerCreating 0 10m

When checking with kubectl describe pods prometheus-server-bf867fc59-bzhhl -n monitoring I get:

Warning FailedAttachVolume 3m28s attachdetach-controller Multi-Attach error for volume "pvc-15980b33-e57f-4f68-bed6-f72f9318415e" Volume is already used by pod(s) prometheus-server-5b9dd7db67-rgbq2

Warning FailedMount 85s kubelet Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[config-volume prometheus-server-token-6mtkb storage-volume]: timed out waiting for the condition

**Version of Helm and Kubernetes:**

Helm Version:

```
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"dirty", GoVersion:"go1.15.6"}Kubernetes Version:
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.12", GitCommit:"7cd5e9086de8ae25d6a1514d0c87bac67ca4a481", GitTreeState:"clean", BuildDate:"2020-11-12T09:11:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart:**
prometheus-community/charts/prometheus

Which version of the chart:
13.2.1

What happened:
When I upgraded the prometheus-server chart using the following command:

`helm upgrade -f values_mine.yaml prometheus ./ -n monitoring`

my new/upgraded prometheus-server POD gets stuck in:

prometheus-server-bf867fc59-bzhhl 0/2 ContainerCreating 0 10m

**What you expected to happen:**
I expected the new POD to be created and ready and not stuck.

How to reproduce it (as minimally and precisely as possible):

# add helm repo
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm install prometheus prometheus-community/kube-prometheus-stack
Used values from attached values_mine.yaml file

**The helm command that you execute and failing/misfunctioning:**

helm upgrade -f values_mine.yaml prometheus ./ -n monitoring

[values_mine.zip](https://github.com/prometheus-community/helm-charts/files/5951499/values_mine.zip)

**Anything else we need to know:**

**Comment by monotek** [comment]
Please only post the values you've changed.

**Comment by jorotg** [comment]
1. Commented out admin-api:
 
  extraFlags:
     - web.enable-admin-api

2. Changed from 1m to 5m:

 alerting_rules.yml:
    groups:
      - name: AllInstances
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 5m.              <--- here
            annotations:
              title: 'Instance {{ $labels.instance }} down'
              description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minute.'  <--- and here

**Comment by jorotg** [comment]
Guys, have you had the chance to look into this issue?

**Comment by satwell** [comment]
I'm running into this as well, using a Longhorn volume, which is ReadWriteOnce.  I think the issue is that the `prometheus-server` deployment is configured to use RollingUpdate strategy with maxUnavailable set to the default 25%.  With one replica, max unavailable is rounded down to 0, so kubernetes won't terminate the old pod first.  But the new pod can't start until the old pod releases the persistent volume.

I've worked around it by using the Recreate strategy instead of RollingUpdate by setting `server.strategy.type=Recreate`.

**Comment by jorotg** [comment]
Do you think changing the strategy to RollingUpdate would preserve already collected metrics by Prometheus or they'll be lost?

**Comment by satwell** [comment]
Metrics will be preserved unless you've disabled persistent storage.  The strategy only affects how pods are recreated when the deployment is updated.  It doesn't affect the persistent volume or claim.

**Comment by jorotg** [comment]
So have this issue been fixed? Perhaps the percentage logic should take into consideration the number of prometheus-server PODs.

**Comment by luvpreetsingh** [comment]
@satwell Thanks for the updateStrategy tip. It seemed obvious once I knew about it.

It will result in downtime though. But if one is having high availability configured using Thanos then I think one can go for it.
