### ISSUE TITLE
[prometheus-kube-stack] duplicated servicemonitor

### ISSUE THREAD

**Issue by KeepMasterBranch** [prometheus-community/helm-charts#675]
**Which chart**: `kube-prometheus-stack`

**Which version of the chart**: `13.7.2`

**What happened**: Duplicate service monitors for the same service

`kube-prometheus-stack` [depends on the chart `prometheus-node-exporter`](https://github.com/prometheus-community/helm-charts/blob/54f0c4af9550dcadbd8e57b986f5bc8e8ffe3770/charts/kube-prometheus-stack/Chart.yaml#L42)

`prometheus-node-exporter` define a service monitor [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/monitor.yaml).

But `kube-prometheus`  define an other one for the same service [here](https://github.com/prometheus-community/helm-charts/blob/54f0c4af9550dcadbd8e57b986f5bc8e8ffe3770/charts/kube-prometheus-stack/templates/exporters/node-exporter/servicemonitor.yaml).

I ends with duplicate metrics, plus the cost to scrap twice the same thing.

**Comment by chitha20** [comment]
I am hitting the same bug !

**Comment by KeepMasterBranch** [comment]
Created a PR to fix this, it's too annoying

**Comment by KeepMasterBranch** [comment]
Just need to set `prometheus-node-exporter.prometheus.monitor.enabled` to `false`
