### ISSUE TITLE
Installation Guideline - kube-prometheus-stack

### ISSUE THREAD

**Issue by wrahmann** [prometheus-community/helm-charts#681]
Hello,

I need some advice regarding the installation of the charts. I have been installing and testing  Prometheus with  a cluster that has access to the internet  using the following commands:

$ helm repo add Prometheus-community https://prometheus-community.github.io/helm-charts
$ helm repo update
$ helm install [RELEASE_NAME] Prometheus-community/kube-prometheus-stack

Now I need to do the installation in a production environment with a private registry. 

1. Do I download all the charts and then install  Prometheus stack to spin Prometheus /Grafana and Alert manager?
 or just copying the prometheus-stack chart is enough?

2. Should I update the values.yaml file in prometheus-stack  chart only? I see there is a separate chart named alertmanager but in online config I only did the changes in values.yaml that came with prometheus-stack.

3. I might need to enable some exporters, will they go separately?

Regards,

Wajih

**Comment by thodquach** [comment]
Hello,
I have an additional question too:

4. I noticed that there is no place to update config prometheus configuration in this chart (kube-prometheus-stack chart). After using `helm install`, I see that config is mounted as a Secret into `Prometheus` statefulset, but I can not see the place to customize prometheus.yaml anywhere in this chart.
