### ISSUE TITLE
[prometheus (pushgateway)] Add support for basic auth in liveness probe ( basic auth shipped in prom/pushgateway 1.4.0)

### ISSUE THREAD

**Issue by SpectralHiss** [prometheus-community/helm-charts#683]
Hello,

Before the very recent pushgateway release (1.4.0) basic auth was supposed to be handled by adding some kind of reverse proxy like nginx. \
It's now possible to configure TLS and basic auth with a web.yml file: https://github.com/prometheus/pushgateway/releases/tag/v1.4.0 \
I was able to use existing latest chart `13.3.2` to almost work with it by:
- override the image tag
- using initContainer to write a web.yml with a basic_auth entry.
- use `extraArgs: web.config.file` to point to the web.yml file.

This seems to work but there is one element i don't see a workaround for which is healthcheck, as i now have 401 on `/-/healthy` and `/-/ready` (the package seems to add auth to all endpoints).
```  Warning  Unhealthy  7m4s (x88 over 91m)   kubelet  Readiness probe failed: HTTP probe failed with statuscode: 401```

The minimal solution is to allow for extra keys on liveness probe to be injected like the authorisation header. 

I am not sure what plans you have for supporting extending pushgateway in this manner, but this saves a headache of having to manage an extra nginx deployment etc.. I will make a PR of exposing this small tweak on httpGet header to unblock myself, provided that you don't have a more elegant way of supporting the new basic auth feature of pushgateway. 
I saw there was an other PR dealing with this but had a completely different approach with oauth2 proxy extra container ,[that PR](https://github.com/prometheus-community/helm-charts/pull/493) seems stale potentially.

Thanks in advance!

**Comment by SpectralHiss** [comment]
Before this is considered stale or anything, perhaps a more general question is how does the community chart intend to support prom/pushgateway 's new experimental built-in basic auth when it hits GA.. ( I suppose soon)

**Comment by monotek** [comment]
I can only guess that the maintainers will wait for community contribution.
So a pr would be welcome :)

**Comment by SpectralHiss** [comment]
Ah yeah i believe i can make the community avoid quite a lot of gotchas with this one, i got it working in the end but had to compromise a bit on security.. the only problem is of having password injected as values. i could make the initcontainer read all this from secret, but then i'd need to change other things that are at the api object level, which i could only do with a patch call:
these are things like updated scrape configs to include basic auth on pushgateway, this extra httpProbesHeaders i expose to pass healthcheck and an updated scrape config (on the main prometheus container, which i guess i could template otherwise),

there's even a bcrypt function to make htpassd in helm but they say themselves it's insecure to keep such values in helm https://helm.sh/docs/chart_template_guide/function_list/#htpasswd
