### ISSUE TITLE
[kube-prometheus-stack] Helm chart does not support extraPaths

### ISSUE THREAD

**Issue by clausa20** [prometheus-community/helm-charts#690]
This chart shall support the extraPaths field for ingress in the values.yaml for the use case when it is wanted to specify for example the following setting in the ingress:
  - path: /*
      backend:
         serviceName: ssl-redirect
         servicePort: use-annotation

This example is necessary to support http to https redirect using AWS Load Balancer controller with alb.

You can see an example in the prometheus chart where it is supported: 
https://github.com/prometheus-community/helm-charts/blob/eb1fedc514fd757a1f26c0bbf5b20b419c000d7b/charts/prometheus/values.yaml#L128

**Comment by monotek** [comment]
Would you mind to create a PR for that please?
