### ISSUE TITLE
[kube-prometheus-stack] Please bump Grafana to 6.4.4 to fix sidecar issues

### ISSUE THREAD

**Issue by languitar** [prometheus-community/helm-charts#696]
**Describe the bug**

As already described upstream in https://github.com/grafana/helm-charts/issues/233 and https://github.com/kiwigrid/k8s-sidecar/issues/110 the Grafana version currently included in the stack chart contains a bug that prevents the sidecar from properly functioning with secrets (instead of configmaps).

Please upgrade the pinned Grafana chart dependency to 6.4.4 to include a fix for this issue.

**Which chart**:

kube-prometheus-stack

**Which version of the chart**:

13.10.0

**What happened**:

Grafana sidecar crashes when secrets are used. See upstream bugs.

**What you expected to happen**:

Things work like before without errors

**Comment by monotek** [comment]
Is this realy needed? The chart uses a dependency to "6.4.*".
In fact, using 13.12.0 you get 6.4.4 installed.

```
k -n monitoring get deployments.apps kube-prometheus-stack-grafana --show-labels
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE     LABELS
kube-prometheus-stack-grafana   1/1     1            1           7h10m   app.kubernetes.io/instance=kube-prometheus-stack,app.kubernetes.io/managed-by=Helm,app.kubernetes.io/name=grafana,app.kubernetes.io/version=7.4.2,helm.sh/chart=grafana-6.4.4
```

**Comment by languitar** [comment]
Isn't the lock file what is used for installing? At least when I looked at the lock file it was pointing to a version before 6.4.4. Seems to be updated now: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.lock#L10
