### ISSUE TITLE
[name of the chart e.g. prometheus-kube-stack] issue title: Alertmanager is trying to mount the self generated secret on the pod

### ISSUE THREAD

**Issue by rshiva777** [prometheus-community/helm-charts#697]
**Describe the bug**

**Version of Helm and Kubernetes**:

Helm Version: 3
k8s version: 1.20

```console
$ helm version
please put the output of it here
```
3

Kubernetes Version:

```console
1.20
$ kubectl version
please put the output of it here
```
1.20

**Which chart**:
prometheus-kube-stack
**Which version of the chart**:
13.10.0
**What happened**:
Alertmanager is trying to mount the self generated secret on the alermanager pod

```
[root@k8s-master01 ~]# kubectl get secrets -monitoring
NAME                                                              TYPE                                  DATA   AGE
alertmanager-prometheus-kube-prometheus-alertmanager              Opaque                                1      8m37s
**alertmanager-prometheus-kube-prometheus-alertmanager-generated    Opaque                                1      4m2s**
alertmanager-prometheus-kube-prometheus-alertmanager-tls-assets   Opaque                                0      161m
```

Highlighted one is the self generated secret of alertmanger config file, and when i try to delete this self generated secret it is automatically creating back
I am unable to update my configuration to the alertmanager yaml file using new secret
I am unable to update the secret in alermanager statefulset to a different one, when i try to change secret, it is not saving with the new secret name that i gave and it is again pointing back to default secret

**What you expected to happen**:
I want to mount secret that i created in alertmanager pod.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jr200** [comment]
I am seeing the same issue in prometheus-kube-stack 13.12.0.

**Comment by antoineozenne** [comment]
Same issue in kube-prometheus-stack 13.13.0.

**Comment by jr200** [comment]
I retract my previous report of the issue (on 13.12.0), but it was slightly confusing!

I had an existing install of kube-prometheus-stack, so I was using the helm upgrade command.

I had been making changes to my alertmanager configuration in a custom values.yaml. My alertmanager configuration was mis-formed (which I found by inspecting the alertmanager pod), and my upgraded chart was only partially applied. After tracking down the bug and correcting the alertmanager configuration the problem went away.

**Comment by vsimon** [comment]
Confirming I see the same thing going on in kube-prometheus-stack 13.13.0.

**Comment by pvlltvk** [comment]
@jr200 
Yes, I can confirm that. A secret with `-generated` postfix is used when there is some misconfiguration in the new alertmanager config.  You can check logs from prometheus-operator pod to find the problem.

**Comment by rajat-bb** [comment]
I am also facing the same issue. What's the short term fix?

**Comment by chernihiv** [comment]
I see the same issue in 16.8.0

**Comment by chernihiv** [comment]
I had the same issue, the problem was
