### ISSUE TITLE
[kube-prometheus-stack] Job to update CRD on upgrade

### ISSUE THREAD

**Issue by QuentinBisson** [prometheus-community/helm-charts#704]
**Is your feature request related to a problem? Please describe.**
Helm currently does not support upgrading CRD and prefer CI or script to actually update the CRD.
Internally, we added a pre-upgrade helm hook to update the CRD by trigerring a job that applies the latest CRD defined https://github.com/giantswarm/prometheus-operator-app/tree/master/helm/prometheus-operator-app/templates/crd-install

As the prometheus CRD are not templated, adding this job here could help uses of the kube-prometheus-stack upgrade.

Would it make sense to add it here so this can be provided for everyone? If you think this is worth it, we can create the PR.

cc @glitchcrab

**Comment by glitchcrab** [comment]
Just commenting in order to remove the stale label.

**Comment by QuentinBisson** [comment]
@bismarck @scottrigby do you think this makes sense in the chart?

**Comment by bismarck** [comment]
@QuentinBisson I believe we had something like this in the chart before. Don't remember why we ripped it out.

@vsliouniaev any thoughts?

**Comment by mkilchhofer** [comment]
Another way would be to maintain a dedicated chart only containing these CRDs (in the `template` dir instead of the `crds` dir). The users then could ensure, that they install the CRD chart first (eg. when using terraform or flux, we can bubble the dependency handling to the infra structure tool).

**Comment by monotek** [comment]
Maybe an option to disable crd install by helm at all would be nice too, so i could just mange the crd outside of the chart.

This would also help with problems like: https://github.com/prometheus-community/helm-charts/issues/805

**Comment by mkilchhofer** [comment]
> Maybe an option to disable crd install by helm at all would be nice too, so i could just mange the crd outside of the chart.
> 
> This would also help with problems like: #805

This already exists in helm ;-). The chart is a `v2` chart and therefore only helm3 is supported. You can use the `--skip-crds` option:
```console
helm install foo prometheus-community/kube-prometheus-stack --skip-crds
```

**Comment by mkilchhofer** [comment]
Does someone knows why the cleanup-CRD job was removed here? https://github.com/prometheus-community/helm-charts/pull/280

I think something similar for upgrading CRDs would be a huge improvement.

**Comment by invidian** [comment]
Not stale.

**Comment by vsliouniaev** [comment]
This would introduce a possible failure scenario in the case where a field added to the CRD is then used elsewhere in the chart. Introducing inconsistencies like this can break deployments in unpredictable ways and I strongly recommend avoiding doing this. The best option for managing CRDs using helm is to deploy them as a separate chart before deploying the chart that uses them.

**Comment by pschichtel** [comment]
Did anything come out of this?

**Comment by QuentinBisson** [comment]
There is a séparate helm chart for the crds but that's it

**Comment by pschichtel** [comment]
Do you mean the subchart to be enabled using `crds.enabled` or the separate prometheus-operator-crds chart?

**Comment by QuentinBisson** [comment]
Thé prometheus operator CRD chart is what we use but we have other lifecycle requirements. I would advise you to use both :)
