### ISSUE TITLE
[prometheus-kube-stack] runbookUrl parameter does not pass to prometheus rules

### ISSUE THREAD

**Issue by eugenberend** [prometheus-community/helm-charts#707]
**Describe the bug**
`runbookUrl` parameter does not pass to prometheus rules. If I specify it in `values.yaml`, it does not appear in annotations.

That is because the chart [template](https://github.com/prometheus-community/helm-charts/blob/86947d2decaee9f4678144b8716015c9fa1b6f7f/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/prometheus.yaml) does not contain runbook_url field.

I've read an explanation [here](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/hack). I'm sorry but I'm still not sure that I've completely understand this instruction. Should I _really_ make 3 pull requests in order to simply add a field in a helm template?

**Comment by GMartinez-Sisti** [comment]
I'm having the same issue. They were removed in this [PR](https://github.com/prometheus-community/helm-charts/pull/665), but it looks like it might've been unintencional, as most entries still have the key.

@invidian can you help ? 👼

**Comment by invidian** [comment]
Those changes are pulled from upstream, perhaps there was a reason why they has been removed from there?
