### ISSUE TITLE
[kube-prometheus-stack] grafana pod won't start due to psp

### ISSUE THREAD

**Issue by jsalatiel** [prometheus-community/helm-charts#711]
**Describe the bug**
grafana pod won't start due psp.
Message:        Cannot enforce AppArmor: AppArmor is not enabled on the host

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

```

Kubernetes Version:
1.19.7

**Which chart**:
prometheus/kube-prometheus-stack

**Which version of the chart**:
 0.45.0 

**What happened**:
grafana pod won't start due to podsecuritypolicy

**What you expected to happen**:
grafana pod should start because the prometheus-grafana psp was created and should have the expected permissions needed.
But since it is annotated with 
```
    apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
    apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
```
and the host has no apparmor installed, it fails. ( as far as i understand )

If I edit the psp and remove those two annotations, the pod will start just fine.

**How to reproduce it** (as minimally and precisely as possible):
Install the helm on a host without app armor ( redhat 7.9 in this case )

**Comment by SmithJosh** [comment]
@jsalatiel Just ran into this today as well. The values under the [grafana section](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L600) get passed to the grafana chart, so you can customize any of the values that the grafana chart uses (see https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart). I was able to remove those apparmor annotations by adding this to the values file:

```
...
grafana:
  rbac:
    pspUseAppArmor: false
...
```

**Comment by jsalatiel** [comment]
Thanks, it worked.
