### ISSUE TITLE
Installation in GKE Autopilot fails - cannot create resource "services" in API group "" in the namespace "kube-system": GKEAutopilot authz: the namespace "kube-system" is managed and the request's verb "create" is denied

### ISSUE THREAD

**Issue by FalkW** [prometheus-community/helm-charts#713]
When trying to deploy on a GKE autopilot cluster installation is failing with:  
upgrade.go:369: [debug] warning: Upgrade "prometheus" failed: failed to create resource: services is forbidden: User "***********" cannot create resource "services" in API group "" in the namespace "kube-system": **GKEAutopilot authz: the namespace "kube-system" is managed and the request's verb "create" is denied**

Looks like nothing can be deployed to the kube-system space. Same values-files worked when it has been deployed to a non-autopilot cluster.

Has anyone else tried it?

**Comment by monotek** [comment]
I've read on twitter that a lot of stuff is not working on autopilot. You probably have to use a standard cluster.

**Comment by ronisec** [comment]
See workaround at https://github.com/SumoLogic/sumologic-kubernetes-collection/issues/1468#issuecomment-1005800179

**Comment by Chucheen** [comment]
On my end it was because of autopilot. Created a new regular cluster and worked

**Comment by GuillaumeCisco** [comment]
Is there a way to make it work with autopilot?
