### ISSUE TITLE
[prometheus-kube-stack] CRDs manual installation

### ISSUE THREAD

**Issue by lexfrei** [prometheus-community/helm-charts#717]
**Is your feature request related to a problem? Please describe.**
I was extremely frustrated about I should install CRDs manually.

**Describe the solution you'd like**
- A documentation
- Automatic install
- Note in the readme

**Describe alternatives you've considered**
fetch the full chart
kubectl apply -f ./path/to/crds

**Additional context**
Without installed CRDs:
```
Failed to render chart: exit status 1: Error: unable to build kubernetese manifest: [
unable to recognize "": no matches for kind "Alertmanager" in versos.com/v1",
unable to recognize "": no matches for kind "Prometheus" in version om/v1",
unable to recognize "": no matches for kind "PrometheusRule" in version om/v1",
unable to recognize "": no matches for kind "ServiceMonitor" in version om/v1"
]
```

**Comment by kfox1111** [comment]
Helm has had a very hard time wrangling CRDs. There's an issue here with a lot of the gory details: https://github.com/helm/community/pull/138/files

I would strongly recommend against automatic installs.

Documentation would be a better solution IMO.
