### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[storage-volume prometheus-alertmanager-token-ht648 config-volume]: failed to get Plugin from volumeSpec

### ISSUE THREAD

**Issue by vmalhotra22** [prometheus-community/helm-charts#72]
Hi,

First of all thanks to the team for making such a wonderful helm charts for prometheus.

This issue occurs when I try to do PVC for my existing PV.

Though I see the PV is getting Bound to the Pod but my Pod throws error "ContainerCreating"  and I see the below error.

Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[storage-volume prometheus-alertmanager-token-ht648 config-volume]: failed to get Plugin from volumeSpec for volume "storek8s" err=no volume plugin matched

I see lot of online suggestions for adding FlexVolume or plugin but not sure how we can implement that in the existing helm charts values.yml

Please help me with the same.

Below is the part of the PersistentVolume for alertmanager in values.yml

  persistentVolume:
    ## If true, alertmanager will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

    ## alertmanager data Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessModes:
      - ReadWriteMany

    ## alertmanager data Persistent Volume Claim annotations
    ##
    annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"storek8s","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"2Gi"}}}}

    ## alertmanager data Persistent Volume existing claim name
    ## Requires alertmanager.persistentVolume.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: ""

    ## alertmanager data Persistent Volume mount root path
    ##
    mountPath: /data

    volumes:
    - flexVolume:
        driver: fstab/cifs
        fsType: cifs
        options:
          mountOptions: dir_mode=0755,file_mode=0644,noperm
          networkPath: //store/ThinkBigLogs/k8s
        secretRef:
          name: cifs-secret-test
    name: storek8s2

    ## alertmanager data Persistent Volume size
    ##
    size: 2Gi

    ## alertmanager data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClassName: ""

    ## alertmanager data Persistent Volume Binding Mode
    ## If defined, volumeBindingMode: <volumeBindingMode>
    ## If undefined (the default) or set to null, no volumeBindingMode spec is
    ##   set, choosing the default mode.
    ##
    volumeBindingMode: ""

**Comment by vmalhotra22** [comment]
anyone to pick this up please.

**Comment by monotek** [comment]
might help you mention the chart you're using.
the issue template is here for a reason ;-)

**Comment by vmalhotra22** [comment]
prometheus-community/helm-charts/charts/prometheus is the one am using  to install prometheus.

**Comment by monotek** [comment]
Please prrovide all Infos requested by the issue template. 

K8s version vnd so on. 

What storage plugin do you use?
Does Our standard storage class exist?

**Comment by vmalhotra22** [comment]
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

am leaving that as Blank for storageclass.

am trying to use the existing PVC now but got same issue.

-------------------
  persistentVolume:
    ## If true, alertmanager will create/use a Persistent Volume Claim
    ## If false, use emptyDir
    ##
    enabled: true

    ## alertmanager data Persistent Volume access modes
    ## Must match those of existing PV or dynamic provisioner
    ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    ##
    accessModes:
      - ReadWriteMany

    ## alertmanager data Persistent Volume Claim annotations
    ##
    annotations: {}
    #kubectl.kubernetes.io/last-applied-configuration: |
    #  {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"storek8s"}}

    ## alertmanager data Persistent Volume existing claim name
    ## Requires alertmanager.persistentVolume.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: "prom-alertmgr"

    ## alertmanager data Persistent Volume mount root path
    ##
    mountPath: /data
    ## alertmanager data Persistent Volume size
    ##
    size: 10Gi

    ## alertmanager data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClassName: ""

    ## alertmanager data Persistent Volume Binding Mode
    ## If defined, volumeBindingMode: <volumeBindingMode>
    ## If undefined (the default) or set to null, no volumeBindingMode spec is
    ##   set, choosing the default mode.
    ##
    volumeBindingMode: ""

    ## Subdirectory of alertmanager data Persistent Volume to mount
    ## Useful if the volume's root directory is not empty
    ##
    subPath: ""
------------------


but I still get same error.

When I try to use the same PV and PVC for a busybox container, it works.

Do we need specific pluging of Flex to be installed via helm?

**Comment by monotek** [comment]
Alermanager Persistence is enabled by default, tested with our CI on every PR and therefore works.

I guess you have some problems with your storage implementation. 
We can't support you with that.

**Comment by honhaoyuan0** [comment]
For my case, I used a Storageclass to create the PV PVCs for me but I still get the pvc bound error especially the alertmanager that was having problem binding with the storage class. As I'm using one storage class across my whole cluster, I fixed it by simply setting the storage class as the default storage class in storage class.yaml file. You can do it by adding this line
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
   under the metadata session.
