### ISSUE TITLE
[prometheus-blackbox-exporter] Wrong configuration default for config.modules.http_2xx.http.valid_http_versions

### ISSUE THREAD

**Issue by leahneukirchen** [prometheus-community/helm-charts#74]
(Repost of https://github.com/helm/charts/issues/23535)

Describe the bug

Wrong configuration default for config.modules.http_2xx.http.valid_http_versions.

Version of Helm and Kubernetes:

version.BuildInfo{Version:"v3.2", GitCommit:"", GitTreeState:"", GoVersion:"go1.14.3"}
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"archive", BuildDate:"2020-07-20T23:19:14Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Which chart:

stable/prometheus-blackbox-exporter

What happened:

Probing HTTP/2.0 sites results in failures.

What you expected to happen:

Probing HTTP/2.0 sites should work.

How to reproduce it (as minimally and precisely as possible):

Run the default setup against any HTTP/2.0 site.

Anything else we need to know:

This can be fixed by replacing `valid_http_versions: ["HTTP/1.1", "HTTP/2"]` with `valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]`.
See prometheus/blackbox_exporter#658

**Comment by monotek** [comment]
fixed in: https://github.com/prometheus-community/helm-charts/commit/d3184e900b4120c85c782a1bfac2b62efe23fc0e#diff-711ccd42b755d858f62f44246a271e46
