### ISSUE TITLE
[prometheus-postgres-exporter] Add podTargetLabels to chart for better flexibility

### ISSUE THREAD

**Issue by AlexDHoffer** [prometheus-community/helm-charts#749]
**Is your feature request related to a problem? Please describe.**

Need to add podTargetLabels to allow pod labels to propagate into Prometheus.

**Describe the solution you'd like**

Copy prometheus-mysql-exporter targetLabel values https://github.com/helm/charts/pull/15349

**Comment by Aaron-ML** [comment]
Looks like this could be fixed by something like: helm/charts#18257
