### ISSUE TITLE
[kube-prometheus-stack] How to get my pod /metrics get scraped??

### ISSUE THREAD

**Issue by haalcala** [prometheus-community/helm-charts#758]
My pod is listening on :9100, how to configure the values such that it will be automatically registered as a target (via ServiceMonitor perhaps)?  And what if I have more than one listeners in different ports?

**Comment by langecode** [comment]
If your pod is not exposed by a service inside of Kubernetes you probably want the `PodMonitor` instead of `ServiceMonitor`- have you looked at some of the various getting started information on Prometheus Operator?

https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
https://github.com/prometheus-operator/prometheus-operator/tree/master/example/user-guides/getting-started

**Comment by haalcala** [comment]
> If your pod is not exposed by a service inside of Kubernetes you probably want the `PodMonitor` instead of `ServiceMonitor`- have you looked at some of the various getting started information on Prometheus Operator?
> 
> https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
> https://github.com/prometheus-operator/prometheus-operator/tree/master/example/user-guides/getting-started

Hi thank you for your reply.  I will check those links.  I'm using kube-prometheus-stack but I only have basic understanding of k8s, and I'm actually using EKS which ads some level of complexity. I'm trying to find something like ready to use solution that I only need to put extra labels on my pod/service.

**Comment by haalcala** [comment]
> If your pod is not exposed by a service inside of Kubernetes you probably want the `PodMonitor` instead of `ServiceMonitor`- have you looked at some of the various getting started information on Prometheus Operator?
> 
> https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
> https://github.com/prometheus-operator/prometheus-operator/tree/master/example/user-guides/getting-started

Sorry for all the dumb questions, I'm also a beginner in Helm. Is it just a matter of installing prometheus-operator?  I just reading about the prometheus-operator, the README says it doesn't provide the monitoring stack.  This is the part I don't understand, monitoring is monitoring, why can't just both co-exists in one chart and just enable or disable through config.  I thought this is what Helm is all about.
