### ISSUE TITLE
Discussion - [kube-prometheus-stack] Prometheus Operator in separate chart?

### ISSUE THREAD

**Issue by langecode** [prometheus-community/helm-charts#760]
I have previously worked with the original `prometheus-operator` from the Helm stable repository. When the deprecation of the stable repository was announced we created our own version based on the stable repo - before the Prometheus community charts came along.

While creating the new version we chose to split it up into more smaller charts, e.g., a Prometheus Operator chart, a kube-statemetrics chart, etc. I think this chart is taking responsibility for a lot of different things at the same time. But instead of maintaining our own chart we would rather contribute to the Prometheus community.

Have you considered splitting up this chart? And would you be interested in us contributing at least a Prometheus Operator chart - which in turn then could be used as dependency for the {{kube-prometheus-stack}}?

**Comment by monotek** [comment]
I think a pr for single prometheus operator chart would be appreciated.
