### ISSUE TITLE
[multiple charts]: Move to apiVersion v2

### ISSUE THREAD

**Issue by oliverbaehler** [prometheus-community/helm-charts#764]
**Is your feature request related to a problem? Please describe.**

Hi there

I was wondering if it would be possible to upgrade all charts in the repository to the Helm apiVersion v2. Since v1 is already considered deprecated a while. The following Charts are currently still apiVersion 1:

  * [prometheus-adapter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-adapter/Chart.yaml#L1)
  * [prometheus-blackbox-exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-blackbox-exporter/Chart.yaml#L1)
  * [prometheus-cloudwatch-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-cloudwatch-exporter/Chart.yaml#L1)
  * [prometheus-consul-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-consul-exporter/Chart.yaml#L1)
  * [prometheus-couchdb-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-couchdb-exporter/Chart.yaml#L1)
  * [prometheus-druid-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-druid-exporter/Chart.yaml#L2)
  * [prometheus-elasticsearch-exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-elasticsearch-exporter/Chart.yaml#L1)
  * [prometheus-mongodb-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-mongodb-exporter/Chart.yaml#L1)
  * [prometheus-mysql-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-mysql-exporter/Chart.yaml#L1)
  * [prometheus-nats-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-nats-exporter/Chart.yaml#L1)
  * [prometheus-node-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-node-exporter/Chart.yaml#L1)
  * [prometheus-pingdom-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-pingdom-exporter/Chart.yaml#L1)
  * [prometheus-pushgateway](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-pushgateway/Chart.yaml#L1)
  * [prometheus-rabbitmq-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-rabbitmq-exporter/Chart.yaml#L1)
  * [prometheus-snmp-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-snmp-exporter/Chart.yaml#L1)
  * [prometheus-stackdriver-exporter](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-stackdriver-exporter/Chart.yaml#L1)
  * [prometheus-to-sd](https://github.com/prometheus-community/helm-charts/blob/8318ce1d92e8c3dd487d89066d0f7b2405c65653/charts/prometheus-to-sd/Chart.yaml#L1)
 
As you can see, a lot of charts will be affected by this changed. I noticed that only the "popular" charts are kinda v2 so I would propose the change all of them.

**Describe the solution you'd like**

For mentioned charts above:
  1. Change apiVersion to `v2`
  2. Bump to a new major
  3. Add documentation, that new major needs at least helm v3.0.0

**Describe alternatives you've considered**
-

**Additional context**
I would be happy to do that contribution for the community, but first wanted to check with you guys, what your opinion on this matter is. Thanks in advance :)

**Comment by monotek** [comment]
If there are still charts with v1 available feel free to add a pr for erver chart :)
