### ISSUE TITLE
[kube-prometheus-stack] Enable setting environment variables for Alertmanager

### ISSUE THREAD

**Issue by carolili** [prometheus-community/helm-charts#766]
I would like to set environment variables for Alertmanager in the kube-prometheus-stack Helm chart in a similar way that it is possible to set them in the [Prometheus Helm chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L77).

**Is your feature request related to a problem? Please describe.**
I would like to set an environment variable for Alertmanager pods.

**Describe the solution you'd like**
I would like a field, e.g., `env` or `extraEnv` for [Alertmanage](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L114)r that would allow me to set environment variables.

**Describe alternatives you've considered**
A similar solution as the one in the [Prometheus Helm chart](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml#L77) would be practical. However I am not an expert on Helm charts, so I don't know if there are any technical blockers for this feature.

**Additional context**
None.

Please let me know if there is already a way to set environment variables that I'm not aware of. If you have any pointers or think it can be done easily I'm happy to try to add this feature and make a PR. Thank you.

**Comment by zethis** [comment]
+1

**Comment by CristaLCorp** [comment]
+1

**Comment by monotek** [comment]
Pull request would be appreciated. 
We will likely not implement it by yourself.
