### ISSUE TITLE
[Adding support for dcgm-exporter]

### ISSUE THREAD

**Issue by aii-shanker-jj** [prometheus-community/helm-charts#801]
Already we have a dcgm-exporter to export **GPU** stats **https://github.com/NVIDIA/gpu-monitoring-tools** as an optional exporter support in **kube-prometheus-stack**.

Currently considering deploying https://github.com/NVIDIA/gpu-monitoring-tools separately in the k8s cluster.

**Comment by louis030195** [comment]
I'm interested too in GPU monitoring using **kube-prometheus-stack**, is there any way to use https://github.com/NVIDIA/dcgm-exporter with it? Thanks!
