### ISSUE TITLE
Adding support for Grafana LOKI

### ISSUE THREAD

**Issue by shan100github** [prometheus-community/helm-charts#802]
Grafana LOKI helm chart is in  https://github.com/grafana/helm-charts & we can provide support in **kube-prometheus-stack**

**Describe the solution you'd like**
Currently we can deploy Grafana LOKI separately from https://github.com/grafana/helm-charts & add it as a LOKI datasource in Grafana.

**Comment by FeizNouri** [comment]
any idea how or where to add Loki datasource in the kube-prometheus-stack ? how to do it

**Comment by monotek** [comment]
you can add datasources via configmaps.
see: https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L636

**Comment by qzio** [comment]
This would be AWESOME.

**Comment by maxekman** [comment]
Would it be possible to provide an option to install the dashboards from this chart, but not the actual Grafana deployment?

**Comment by monotek** [comment]
It's already possible. See my comment above.

**Comment by qzio** [comment]
> It's already possible. See my comment above.

Hmm, I'm  I missing something here?

The configmaps for grafana dashboards in the kube-prometheus-stack are gated by `grafana.enabled` being true, which is also the `condition` to install grafana as part of the chart.

i.e.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml#L1

**Comment by shan100github** [comment]
@qzio, true that only `grafana.enabled` is set, for the same reason thought of requesting to integrate it in kube-prometheus stack.

**Comment by nick-lehmann** [comment]
I'm with @qzio. The gate makes it impossible to use the configmap from this chart with the grafana deployment from `loki` charts.

However, you could use the grafana deployment from this chart instead and get the configmap for the loki datasource from the loki chart, as this is not gated by `grafana.enabled`. See [here](https://github.com/grafana/helm-charts/blob/76ef792c3d2910f2a4c4996a66c77cc65daa0074/charts/loki-stack/templates/datasources.yaml).

Still, it would be nice if the condition could be dropped.
