### ISSUE TITLE
[prometheus-postgres-exporter] PostgreSQL 13 does not have "total_time" field 

### ISSUE THREAD

**Issue by solyard** [prometheus-community/helm-charts#804]
**Describe the bug**
Default queryes bundle contain incorrect field name which was renamed in PG 13 from **_total_time_** to  **_total_exec_time_**

**Version of Helm and Kubernetes**:

Helm Version:
```console
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

Kubernetes Version:
```console
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**:
Repo: https://prometheus-community.github.io/helm-charts
Name: prometheus-postgres-exporter

**Which version of the chart**:
Version: 2.2.0

**What happened**:
Exporter did not expose some part of metrics with error:
```console
Error running query on database pg_stat_statements pq: column \"total_time\" does not exist" source="postgres_exporter.go:1503"
```
**What you expected to happen**:
Exporter started and expose metrics

**How to reproduce it** (as minimally and precisely as possible):
Just install chart without editing default queryes

**Helm values set after installation/upgrade:**

```console
USER-SUPPLIED VALUES:
config:
  datasourceSecret:
    key: pg-connection-strings
    name: pg-exporter-connection-strings
nameOverride: prometheus-pg-exporter
serviceMonitor:
  enabled: true
  labels:
    release: prometheus-stack
```

**Anything else we need to know**:
Maybe need add some if condition block that will be support each version of PG

Fix is simple:

Replace **_total_time_** via **_total_exec_time_** in query above:
https://github.com/prometheus-community/helm-charts/blob/585c8fcad793f0256cefa6926d6f1de0d5555fee/charts/prometheus-postgres-exporter/values.yaml#L284 

Official PG13 pg_statements page:
https://www.postgresql.org/docs/13/pgstatstatements.html

**Comment by solyard** [comment]
Discovered that more inconsistent tables for pg13 were used for creating query:

In PG 13 *_plan_time metric and *_exec_time metric have been splited:

So correct query for PostgreSQL < v13 is:

```yaml
pg_stat_statements:
  query: "SELECT t2.rolname, t3.datname, queryid, calls, total_time / 1000 as total_time_seconds, min_time / 1000 as min_time_seconds, max_time / 1000 as max_time_seconds, mean_time / 1000 as mean_time_seconds, stddev_time / 1000 as stddev_time_seconds, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time / 1000 as blk_read_time_seconds, blk_write_time / 1000 as blk_write_time_seconds FROM pg_stat_statements t1 JOIN pg_roles t2 ON (t1.userid=t2.oid) JOIN pg_database t3 ON (t1.dbid=t3.oid) WHERE t2.rolname != 'rdsadmin'"

``` 

And corret query for PostgreSQL >= v13 is:

```yaml
pg_stat_statements:
          query: "SELECT t2.rolname, t3.datname, queryid, calls, total_exec_time / 1000 as total_time_seconds, min_exec_time / 1000 as min_time_seconds, max_exec_time / 1000 as max_time_seconds, mean_exec_time / 1000 as mean_time_seconds, stddev_exec_time / 1000 as stddev_time_seconds, rows, shared_blks_hit, shared_blks_read, shared_blks_dirtied, shared_blks_written, local_blks_hit, local_blks_read, local_blks_dirtied, local_blks_written, temp_blks_read, temp_blks_written, blk_read_time / 1000 as blk_read_time_seconds, blk_write_time / 1000 as blk_write_time_seconds FROM pg_stat_statements t1 JOIN pg_roles t2 ON (t1.userid=t2.oid) JOIN pg_database t3 ON (t1.dbid=t3.oid) WHERE t2.rolname != 'rdsadmin'"
```

**Comment by zanhsieh** [comment]
@solyard 
How do you make above query compatible for both pg12 and pg13?

**Comment by solyard** [comment]
> @solyard
> How do you make above query compatible for both pg12 and pg13?

We are split exporters between versions for now. For =< 12 we are using one query for >= 13 another

**Comment by monotek** [comment]
maybe on of you guys could create an pr, introducing a postgres version variable so you have a config option to decide which query is used.
