### ISSUE TITLE
[kube-prometheus-stack] Recording rule evaluation failures on sharded prometheus due to target sharding

### ISSUE THREAD

**Issue by paranoidsp** [prometheus-community/helm-charts#809]
**Describe the bug**
On setting the shard value to 2 in the values.yaml, two prometheus shards are created. Only one of them seems to be  successfully evaluating the [(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) recording rule](https://github.com/prometheus-community/helm-charts/blob/585c8fcad793f0256cefa6926d6f1de0d5555fee/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L33) from the default set of rules. 
Eg. Shard 0 performs the recording rules, shard 1 does not

This is because the rule requires a `kube_pod_info` gauge that is scraped from `kube-state-metrics`, which only one of the shards scrapes.

Grafana uses this in the [default set of dashboards ](https://github.com/prometheus-community/helm-charts/blob/585c8fcad793f0256cefa6926d6f1de0d5555fee/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/k8s-resources-workload.yaml#L80), and we only see live CPU data from pods on nodes that have been scraped by shard 0, and not shard 1.

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

Kubernetes Version:

```console
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-18T11:44:09Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**:  14.0.1

**What happened**:
On setting shards to >1, only one of the Prometheus shards seems to be evaluating the [(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) recording rule](https://github.com/prometheus-community/helm-charts/blob/585c8fcad793f0256cefa6926d6f1de0d5555fee/charts/kube-prometheus-stack/templates/prometheus/rules-1.14/k8s.rules.yaml#L33) from the default set of rules.

**What you expected to happen**:
All prometheus shards should evaluate recording rules successfully.

**How to reproduce it** (as minimally and precisely as possible): Deploy default helm chart with shards > 1
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
prometheus:
  prometheusSpec:
    shards: 2
```

**Comment by paranoidsp** [comment]
This was not correctly located, I'll debug further and recreate, it seems to be an issue with the recording rule evaluation itself failing on one of the shards.

**Comment by paranoidsp** [comment]
The bug seems to be around sharding still:

The following recording rule fails to evaluate on one of the shards due to the absence of any kube_pod_info metrics on one of the shards

```
    sum by(cluster, namespace, pod, container) (rate(container_cpu_usage_seconds_total{container!="POD",image!="",job="kubelet",metrics_path="/metrics/cadvisor"}[5m])) * on(cluster, namespace, pod) group_left(node) topk by(cluster, namespace, pod) (1, max by(cluster, namespace, pod, node) (kube_pod_info{node!=""}))
```

`kube_pod_info` is only present on the prometheus that scrapes `kube-state-metrics`, which in my example case was shard 0. Shard 1 does not have this, and therefore fails to evaluate the recording rule.

**Comment by paranoidsp** [comment]
I assume the solution here is to evaluate these recording rules via thanos, or some sort of component that spans all prometheus shards?

**Comment by Frizlab** [comment]
I’d say so yeah. Will try and do this.
Like I said in #913 it would be great if the chart allowed creating the rules for Thanos Ruler automatically.

**Comment by Frizlab** [comment]
**Update**: Yup, using a Thanos Ruler works.

**Comment by paranoidsp** [comment]
Yes, we went the thanks ruler route too.

**Comment by danksim** [comment]
@paranoidsp @Frizlab

i have a 4-shard kube-prometheus-stack prometheus cluster:
```
prometheus-0                     3/3     Running   1          3d5h
prometheus-shard-1-0             3/3     Running   1          3d5h
prometheus-shard-2-0             3/3     Running   1          3d5h
prometheus-shard-3-0             3/3     Running   1          3d5h
```

and i have 2 pods (of a statefulset named a-consumer) each exposing a `/federate` endpoint to be scraped:
```
a-consumer-0                1/1     Running   0          27h
a-consumer-1                1/1     Running   0          27h
```

and each has its `/federate` endpoint scraped by 1 of the 4 shards (under `additionalScrapeConfigs`):
```
# Setting the hashmod number to calculate from (total number of instances)
- source_labels: [__meta_kubernetes_pod_name]
  modulus:       4
  target_label:  __tmp_hash
  action:        hashmod
# Setting this instance replica ID - only matched source calculated hashmod will be kept
- source_labels: [__tmp_hash]
  regex:         $(SHARD)
  action:        keep
```

now, the targets land on shard-0 and shard-1-0 and they are scraping each of the 2 pods' `/federate` endpoint and shard-2-0 and shard-3-0 are not scraping a-consumer (`/targets` does not show a-consumer being scraped).

i have a prometheusrule with expression:
```
absent(up{service="a-consumer-service"} == 1)
```

and since shard-2-0 and shard-3-0 are not scraping a-consumer, the above expression returns 1 for both of these shards and triggers alerts.

i think i am running into the same issue but i would like to not introduce thanos ruler since i have it disabled at the moment. do i need to use thanos ruler for all rules that are evaluated by only some shards?

**Comment by armas-mk** [comment]
I had a similar problem with the default 1 shard setup using 2 replicas. Whenever i used Thanos datasource it failed to get the data due to the replica label.

The solution was to set query.replica-label="prometheus_replica" in the Thanos helm chart and now i can load the panels via Thanos DS

**Comment by danksim** [comment]
@paranoidsp @Frizlab

**Comment by apollie** [comment]
> @paranoidsp @Frizlab
> 
> i have a 4-shard kube-prometheus-stack prometheus cluster:
> 
> ```
> prometheus-0                     3/3     Running   1          3d5h
> prometheus-shard-1-0             3/3     Running   1          3d5h
> prometheus-shard-2-0             3/3     Running   1          3d5h
> prometheus-shard-3-0             3/3     Running   1          3d5h
> ```
> 
> and i have 2 pods (of a statefulset named a-consumer) each exposing a `/federate` endpoint to be scraped:
> 
> ```
> a-consumer-0                1/1     Running   0          27h
> a-consumer-1                1/1     Running   0          27h
> ```
> 
> and each has its `/federate` endpoint scraped by 1 of the 4 shards (under `additionalScrapeConfigs`):
> 
> ```
> # Setting the hashmod number to calculate from (total number of instances)
> - source_labels: [__meta_kubernetes_pod_name]
>   modulus:       4
>   target_label:  __tmp_hash
>   action:        hashmod
> # Setting this instance replica ID - only matched source calculated hashmod will be kept
> - source_labels: [__tmp_hash]
>   regex:         $(SHARD)
>   action:        keep
> ```
> 
> now, the targets land on shard-0 and shard-1-0 and they are scraping each of the 2 pods' `/federate` endpoint and shard-2-0 and shard-3-0 are not scraping a-consumer (`/targets` does not show a-consumer being scraped).
> 
> i have a prometheusrule with expression:
> 
> ```
> absent(up{service="a-consumer-service"} == 1)
> ```
> 
> and since shard-2-0 and shard-3-0 are not scraping a-consumer, the above expression returns 1 for both of these shards and triggers alerts.
> 
> i think i am running into the same issue but i would like to not introduce thanos ruler since i have it disabled at the moment. do i need to use thanos ruler for all rules that are evaluated by only some shards?

after enabling sharding, we've started experiencing same issues...
In our case KubeAPI and KubeScheduler alerts are triggered.
Don't really want to disable them completely, but non-functional state is also not very nice.

**Comment by yccharles** [comment]
@Frizlab  How to distinguish which recording/alert should be included in Thanos Ruler Component？ 

It's must work if I put all prometheus-rule into Thanos Rule. But, It is recommended to keep deploying rules inside the relevant Prometheus servers locally. Use Thanos Ruler only on specific cases, such as sharding promethues.

In my opinion, most of the rules should be evaluating in promethues, and only a few have to be evaluating in Thanos Rule.
Does helm-chart classify prometheusrule and thanosrule?

**Comment by Frizlab** [comment]
I don’t think so.
Anyway, personally I’ve mostly given up with Thanos and I’m currently trying VictoriaMetrics which seems _much_ more promising.

**Comment by CharlieC3** [comment]
Can this issue please be re-opened? We're currently unable to make use of sharding because based on this thread, it seems to require Thanos Ruler for recorded rules to function properly, which many people do not want to use (including myself).
