### ISSUE TITLE
[prometheus-blackbox-exporter] Add support to chart to work with 'helm template'

### ISSUE THREAD

**Issue by pstackle** [prometheus-community/helm-charts#810]
**Is your feature request related to a problem? Please describe.**

It would be very helpful to be able to use the chart in a GitOps pipeline (e.g. [Flux](https://github.com/fluxcd/flux)) or via Spinnaker's [Bake Manifest stage](https://spinnaker.io/guides/user/kubernetes-v2/deploy-helm/). For the Flux use case, this involves using `helm template` to render the chart's contents into fully populated manifests and then committing the manifests to a git repository that is monitored by a GitOps operator running in the cluster. For Spinnaker, it involves using `helm template` to render the chart's contents that are then applied directly to the Kubernetes cluster.

The current chart does not work as-is for this use case because the namespace-scoped objects are missing a `namespace` field, which results in the objects ending up being applied to the `default` namespace.

**Describe the solution you'd like**
I would like to see the various namespace-scoped objects be defined with `namespace: {{ .Release.Namespace }}` so that they will work well with `helm template`.

**Describe alternatives you've considered**
An alternative approach is to fork this chart in order to add the namespace fields.

**Additional context**
The requested change is the same as other charts have done:
- https://github.com/fluxcd/flux/pull/3076
- https://github.com/helm/charts/pull/13924
- https://github.com/bitnami/charts/pull/3417
- https://github.com/bitnami/charts/pull/3418
- https://github.com/bitnami/charts/pull/3419
- https://github.com/falcosecurity/charts/pull/144

**Comment by kfox1111** [comment]
why not just add -n to your apply?

**Comment by pstackle** [comment]
@kfox1111 when using a gitops operator or spinnaker, there isn't a human that is typing the apply command. Those tools are applying manifests that could belong to a variety of namespaces, so the expectation is that the manifests themselves have the namespace field defined.

**Comment by monotek** [comment]
If your ci supports kustomize, like fluxcd, you could easily patch your resources while applying them.
