### ISSUE TITLE
Artifact Hub repo improvements

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#82]
- [x] verified (#75, #76, #78)
- [x] official (https://github.com/artifacthub/hub/issues/642)

**Comment by scottrigby** [comment]
This repo's package now have ` verified` and `official` badges in the hub 🙂

![image](https://user-images.githubusercontent.com/407675/92722558-c872bb80-f335-11ea-9c88-5e1c33e25e74.png)

**Comment by gkarthiks** [comment]
should we also add ourself to https://chartcenter.io/ ?

**Comment by scottrigby** [comment]
From the last Helm dev call, I believe Chart Center will pull from Artifact Hub. If that turns out not to be the case, then sure 😄
