### ISSUE TITLE
Issue number 159, I'm facing same issue. any solution?

### ISSUE THREAD

**Issue by docgurureddy** [prometheus-community/helm-charts#822]
https://github.com/prometheus-community/helm-charts/issues/159

This bug appears to have already been reported but not in exactly the way I'm seeing it.

Describe the bug
It appears that the chart has dependencies that were not implemented as sub-charts. When I run the following

helm install metrics ./kube-prometheus-stack/ -n metrics
I get the following error:

Error: found in Chart.yaml, but missing in charts/ directory: kube-state-metrics, prometheus-node-exporter, grafana
Helm Version:

$ helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

What happened: I received the error message: Error: found in Chart.yaml, but missing in charts/ directory: kube-state-metrics, prometheus-node-exporter, grafana

What you expected to happen: I expected the chart to deploy.

How to reproduce it (as minimally and precisely as possible):

git clone https://github.com/prometheus-community/helm-charts.git
cd helm-charts/charts
kubectl create namespace monitoring
helm install metrics ./kube-prometheus-stack -n metrics

**Comment by borisputerka** [comment]
Hi @docgurureddy, 
run `helm dependency update` before installing.
