### ISSUE TITLE
kube-prometheus-stack is not a 1:1 to prometheus-operator

### ISSUE THREAD

**Issue by kevin-shelaga** [prometheus-community/helm-charts#83]
It might be nice to bundle alertmanager with kube-prometheus-stack so that it matches what prometheus-operator provided out of the box.

**Comment by torstenwalter** [comment]
It includes alertmanager see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/alertmanager or am I missing something?

**Comment by kevin-shelaga** [comment]
@torstenwalter hmm seems youre correct. I guess i couldnt find any clear mention until i started reading further into what CRDs are deployed or looking at the templates. closing
