### ISSUE TITLE
[prometheus-kube-stack] Setup persistent prometheus with multiple replicas

### ISSUE THREAD

**Issue by PeteMac88** [prometheus-community/helm-charts#837]
Hey there,
we are running a prometheus in an AWS EKS Cluster and want to run multiple prometheus replicas for our prod cluster. I realized that when enabling multiple replicas a `persistentVolumeClaim` is created for each replica. Is there a way of not duplicating the metrics or is it just the way how prometheus replicas in a high availability setup work?

Will this setup affect how the metrics are shown in grafana or are the duplicates filtered? Sorry for my questions here but I didnt found something regarding this topic in the docs here.

**Comment by borisputerka** [comment]
Hi @PeteMac88,
this behaviour is how prometheus-operator works. Info about HA can be found here https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/high-availability.md
