### ISSUE TITLE
[kube-prometheus-stack & Prometheus] document differences between the two charts

### ISSUE THREAD

**Issue by caleb15** [prometheus-community/helm-charts#838]
**Is your feature request related to a problem? Please describe.**
I'm not confident in which chart I should use

**Describe the solution you'd like**
More documentation on the differences

**Describe alternatives you've considered**
I googled and looked at both readme's in detail.
Somewhat relevant reddit discussion:
https://www.reddit.com/r/kubernetes/comments/lgws6b/do_you_install_prometheus_as_an_operator_or_a/

**Additional context**

Here are the differences as I understand them currently:

**kube-prometheus-stack Chart:**
\+ Has custom operators (what's benefit of this exactly?)
\+ sets up grafana
\+ Has great [tutorial video series](https://www.youtube.com/playlist?list=PLy7NrYWoggjxCF3av5JKwyG7FFF9eLeL4)
\~ specify servicemonitor to scrape metrics
\- https://github.com/prometheus-operator/kube-prometheus, which the chart is based on, is still experimental
\- a bit more complicated compared to Prometheus chart

**Prometheus Chart:**
\+ a bit simpler
\+ seems stabler
\~ specify annotations to scrape metrics
\- doesn't setup grafana (although not a minus if you already have grafana)
\- no custom operator

**Comment by monotek** [comment]
I dont think we should add information about prometheus to kube-prometheus-stack or vice versa.
