### ISSUE TITLE
[kube-state-metrics] Migration to this repository

### ISSUE THREAD

**Issue by mrueg** [prometheus-community/helm-charts#839]
**Is your feature request related to a problem? Please describe.**
The maintainers (@tariq1890, @mrueg) of the kubernetes/kube-state-metrics chart would like to be host it in this repository.
Currently the chart is part of the repository which causes issues to non-helm users as the chart creates a lot of releases (cf. https://github.com/kubernetes/kube-state-metrics/issues/1392).

**Describe the solution you'd like**
Starting with kube-state-metrics release 2.0, we would like to create a PR to host the chart in this repository including its history and maintain it here (if additional maintainers are interested, hit Tariq or myself up on kubernetes' slack instance). The old chart is considered deprecated and eventually will be removed from the kube-state-metrics repository.

**Describe alternatives you've considered**
We have considered maintaing the chart in lockstep with the application, due to the nature of kube-state-metrics this is not an ideal solution.

**Comment by monotek** [comment]
Not sure if it fits 100% here, as it has not a real Prometheus background but i tend to support that wish as the chart is used in Prometheus and kube-prometheus-stack charts as dependency. 


Imho the question would also be what that means for other charts like Thanos or Cortex?
Should they get a home here too if somebody wants to add them? 
So i guess this would need to be a general decission, if also charts from the wider prometheus ecosystem should be accepted here?

**Comment by mrueg** [comment]
> Not sure if it fits 100% here, as it has not a real Prometheus background but i tend to support that wish as the chart is used in Prometheus and kube-prometheus-stack charts as dependency.

Yes, this is the reason why we considered this repository as a lot of users use it in combination with those.

> 
> Imho the question would also be what that means for other charts like Thanos or Cortex?
> Should they get a home here too if somebody wants to add them?
> So i guess this would need to be a general decission, if also charts from the wider prometheus ecosystem should be accepted here?

I would prefer if we can keep this issue limited to kube-state-metrics and have that discussion separately.
