### ISSUE TITLE
[kube-prometheus-stack] Can't find upgrade procedure from stable/prometheus-operator

### ISSUE THREAD

**Issue by TrustNoOne** [prometheus-community/helm-charts#84]
Hi, I've been looking everywhere but I can't find how to upgrade stable/prometheus-operator to the renamed chart. I looked in open issues but found nothing.

I've never upgraded a renamed chart, I tried to look it up with no luck. Can anyone point me to that if it's anywhere?

I guess it's worth mentioning it in https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md ?

**Comment by den-is** [comment]
The easiest way is that you will have to do a clean reinstall from scratch :(

Virtually I can imagine that there is a way to migrate Prometheus data manually if it is stored in PVs to new PVs with new names - you can fake and create statefulset volumes by yourself - just match the name of these volumes with what the chart would do by itself.

**Comment by tbomberg** [comment]
It looks like upgrading the chart is possible by setting

`nameOverride: prometheus-operator`

in your values.yaml (or add it to the --set's in your helm upgrade commandline)
This way the generated object names stay the same as with the old chart.

**Comment by monotek** [comment]
@tbomberg
Would you mind to add this info to readme via a pr?

**Comment by scottrigby** [comment]
Thanks yes was thinking the same as @monotek here. Testing this is one of the things we asked people to help with in #1, but I don't believe anyone did, and in the end I didn't have enough personal experience with persistence in this chart and it's subcharts to know what to test.

There is already this [`Migrating from coreos/prometheus-operator chart` > `Persistent Volumes`](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#persistent-volumes) section in the README. Do these steps help meet your need?

Either way, I would like to see a similar `Upgrading from stable/prometheus-operator` section as well. Including:
- in-place release upgrade
- recreate release with new chart, and (optionally) attach existing volume claims

The community could then add to that section as new use cases upgrading from `stable/prometheus-operator` are defined.

**Comment by fktkrt** [comment]
I was not able to properly migrate using the solution described above.

Re-using existing PVs might be the most crucial step during this process mostly.
I've created a PR tackling this issue, and with those steps I was able to migrate my existing storage successfully to the new chart.
