### ISSUE TITLE
[kube-prometheus-stack] Mount configmap for thanos sidecar

### ISSUE THREAD

**Issue by PeteMac88** [prometheus-community/helm-charts#844]
Hey there,
i am having a hard time to configure the thanos sidecar with the `objectStorageConfigFile` option. Here you need to add the path to the config file used by the sidecar but how do I mount the file? To use `objectStorageConfig` with a secret is working but actually the secret does not include any credentials when you use IAM roles for serviceAccounts. 

Is there a possibility to pass the config as a configMap or even plain yaml?

**Comment by Dhru1Tanna** [comment]
This is a problem for sure, I think we should have **volumes** and **volumeMounts** option in the thanosSpec as well just like we have in the prometheusSpec.
Ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2200

I think the thanosSidecar should be implemented in the chart with certainty. Currently, there is a comment stating, the thanosSpec is experimental and can change significantly without any prior notice. 
Ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L2300
