### ISSUE TITLE
[kube-prometheus-stack] pull functionality in hack scripts out of main into separate functions

### ISSUE THREAD

**Issue by m1o1** [prometheus-community/helm-charts#85]
We would like to add our own dashboards, rules, and alerts, but they are private, and we do not want them pushed upstream. We also want to be able to modify those made by kube-prometheus via jsonnet. To do these things, we are vendoring these helm charts as-is, then generating the json for these things via jsonnet with [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus), then finally piping them into a modified version of the hack scripts to create the templates for the helm charts.

If some of the heavy lifting (particularly the loops) were pulled into their own functions, then it would be easier to write slightly modified versions of the hack script, and I won't need to merge with updates pulled from upstream as often (that hasn't really been an issue, but if all the main functionality is available in specific functions, then I have more confidence that it won't be). It would be nice to just copy these hack scripts into my own python module for me to use the functions provided. I assume there would still be some churning as there's no API guarantees in these hack scripts, but it seems more manageable at a function-level.

This is the "easy" feature request, though I guess this leads to what I'm ultimately trying to achieve: the ability to add rules, dashboards, and alerts (as well as **modify** the ones from kube-prometheus), then easily be able to deploy them as part of the helm charts (with all the helm templating, etc.) without having to first push these somewhere public.

**Is your feature request related to a problem? Please describe.**
Having a "static" set of dashboards, rules, and alerts won't work for us. We need to be able to modify things in the jsonnet as well as add our own stuff. However, using helm is still a huge benefit, in terms of switching them on/off with the values.yaml and using helm templating for variables not known until deployment time (i.e. not known when the charts are generated with these hack scripts).

**Describe the solution you'd like**
For the easy solution, I would just like any loops or non-trivial functionality to be pulled into functions, so the `main` function is simplified and I don't need to worry about having to merge things when pulling upstream changes as often.

Ultimately, I'm picturing these hack scripts basically being a helm chart "generator" (since helm natively doesn't support jsonnet or workflows like this), and I'd like to use functions from these `hack.py` scripts to help with that.

**Describe alternatives you've considered**
We've considered using just kube-prometheus without helm, but given that `kubectl apply --prune` is still alpha, helm seems to be best for packaging things. Plus the helm templating is a huge plus as well.

HTH make a PR for this.

**Comment by monotek** [comment]
We just upload such dashboards, rules & alerts as configmaps which have a special label.
For Grafana, Prometheus & Alermanager there are controllers, which can be run as sidecar, which import the configmaps as config files.

For Grafana we're using: https://github.com/kiwigrid/k8s-sidecar
For Prometheus we're using: https://github.com/kiwigrid/k8s-configmap-watcher

**Comment by m1o1** [comment]
Thanks, yeah we were previously doing that for the dashboards. My only concern with that approach is it doesn't (AFAIK) get all the benefits of being part of the helm charts.

Some Prometheus rules need to relabel metrics based on the job name set in the values.yaml file, so if I want to deploy the kube-prometheus rules myself, I seem to lose the ability to use the config set in the helm values. The hack scripts make these changes for us.

Also, unless I label them appropriately (which isnt possible at jsonnet build time), the dashboards would not be adopted by the helm release, so when I remove a chart or alert or something, it would still exist in the cluster and I think I'd need to manually remove it.

I could maybe add helm templating in the jsonnet and just put the {{ }} in strings, but then we lose the ability to use helm templates for non-string values, since jsonnet would require that to be a string.
