### ISSUE TITLE
prometheus-node-exporter ignores taints 

### ISSUE THREAD

**Issue by kevin-shelaga** [prometheus-community/helm-charts#86]
https://github.com/helm/charts/issues/23542 recreated here

Describe the bug
prometheus-node-exporter ignores taints

Version of Helm and Kubernetes:
helm 3, k8s 1.16.3

Which chart:
kube-prometheus-stack

What happened:

Taints: node.kubernetes.io/os=windows:NoSchedule
Taints: search=true:NoSchedule

the above taints are being ignored and the node-exporter is scheduled regardless on nodes, get stuck at container creating for windows nodes

monitoring     kube-prometheus-stack-prometheus-node-exporter-2l5wz       1/1     Running             0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-4vmt4       1/1     Running             0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-5lkwh       0/1     ContainerCreating   0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-6l7bc       1/1     Running             0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-89926       1/1     Running             0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-bbpcg       0/1     ContainerCreating   0          5m28s
monitoring     kube-prometheus-stack-prometheus-node-exporter-l9p4r       1/1     Running             0          5m27s

What you expected to happen:
node-exporter should not be scheduled on windows nodes

How to reproduce it (as minimally and precisely as possible):

    setup a cluster with taints
    helm install [RELEASE_NAME] prometheus-community/kube-prometheus-stack

workaround: 

```
--set prometheus-node-exporter.nodeSelector."beta\.kubernetes\.io/os"=linux

```

**Comment by kevin-shelaga** [comment]
any updates on this?

**Comment by kevin-shelaga** [comment]
still valid

**Comment by kevin-shelaga** [comment]
still valid

**Comment by pbariamisxm** [comment]
@kevin-shelaga did you find any workaround ?

**Comment by kevin-shelaga** [comment]
@pbariamisxm Yes, I just set the node selector

```sh
helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --set prometheus-node-exporter.nodeSelector."beta\.kubernetes\.io/os"=linux
```

**Comment by agray-ctm** [comment]
#45ae69f referencing this issue does not seem to have been a fix. I am still experiencing the exporter scheduling on my tainted nodes.
