### ISSUE TITLE
[kube-prometheus-stack] prometheus.thanosService.clusterIP should not be required

### ISSUE THREAD

**Issue by yurrriq** [prometheus-community/helm-charts#863]
**Describe the bug**

`prometheus.thanosService.clusterIP` ought not be a required value

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version --short
v3.5.3+g041ce5a
```

Kubernetes Version:

```console
$ kubectl version --short
Client Version: v1.19.9
Server Version: v1.19.9
```

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 14.9.0

**What happened**:

```
UPGRADE FAILED: cannot patch "prometheus-operator-thanos-discovery" with kind Service: Service "prometheus-operator-thanos-discovery" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

**What you expected to happen**: successful no-op upgrade

**How to reproduce it** (as minimally and precisely as possible):
**Changed values of values.yaml** (only put values which differ from the defaults):

values.yaml

```console
prometheus:
  thanosService:
    enabled: true
    clusterIP: null # or ""
    type: LoadBalancer
```

**The helm command that you execute and failing/misfunctioning**:

For example:

```console
helm install prometheus-operator prometheus-community/kube-prometheus-stack -upgrade --version version --values values.yaml
```

**Anything else we need to know**:

This is essentially the same problem as https://github.com/helm/charts/issues/9227 (fixed in https://github.com/helm/charts/pull/13646)

**Comment by yurrriq** [comment]
As [requested](https://github.com/prometheus-community/helm-charts/pull/864#discussion_r619812882) by @monotek re: #864, I have confirmed the bug exists with `prometheus.thanosService.clusterIP=""` as well.

**Comment by doug-ba** [comment]
I've opened #916 with an alternative solution which creates a service specifically for external access to the thanos-sidecar.  The service being modified in the earlier PR is intended as a headless service for service discovery, which is why it has "discover" in the name and originally had ClusterIP set to None with no way to modify it.
