### ISSUE TITLE
[prometheus-kube-stack] Update grafana helm chart dependency

### ISSUE THREAD

**Issue by wasfree** [prometheus-community/helm-charts#876]
**Describe the bug**
Currently kube-prometheus-stack has a dependency to grafana helm chart version 6.7.4. This Version has and issue when generating the ConfigMap for grafana.ini, lines longer than 120 chars will be wrapped causing an invalid yaml file.

`YAML parse error on kube-prometheus-stack/charts/grafana/templates/configmap.yaml: error converting YAML to JSON: yaml: line 45: could not find expected ':'`

Fortunately this issue was aleady fixed in Version 6.7.5 https://github.com/grafana/helm-charts/pull/386. However latest version is 6.8.0 so it would make sense to update dependency to grafana to this version.

**Comment by ArchiFleKs** [comment]
I also cannot use ingress on grafana on the latest version : `15.1.3` maybe because of [this](https://github.com/grafana/helm-charts/commit/5c0c3f340855f197a8a5f5e55054f204edb9a0da)
