### ISSUE TITLE
[kube-state-metrics] Add maintainers to org

### ISSUE THREAD

**Issue by scottrigby** [prometheus-community/helm-charts#905]
@brancz or @SuperQ 👋 would one of you please add @mrueg and @tariq1890 to @prometheus-community/helm-charts-maintainers GitHub team per https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#adding-chart-maintainers? Thanks 😸 

https://github.com/prometheus-community/helm-charts/blob/fc70a3e0194085c61eb7c0d4fad0baa563f6f640/.github/CODEOWNERS#L11

Related to #903

**Comment by SuperQ** [comment]
Invites sent.
