### ISSUE TITLE
 [prometheus-pushgateway] added ClusterIP flag in values.yaml to support headless service

### ISSUE THREAD

**Issue by tomfankhaenel** [prometheus-community/helm-charts#907]
**Describe the bug**
After the merge of https://github.com/prometheus-community/helm-charts/pull/324 an upgrade of the helm chart is broken because of the clusterIP value in the template. It is failing with
`Error: UPGRADE FAILED: an error occurred while rolling back the release. original upgrade error: cannot patch "prometheus-pushgateway" with kind Service: Service "prometheus-pushgateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable: cannot patch "prometheus-pushgateway" with kind Service: Service "prometheus-pushgateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable`

**Version of Helm and Kubernetes**:

Helm Version:

```
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

Kubernetes Version:

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-eks-7737de", GitCommit:"7737de131e58a68dda49cdd0ad821b4cb3665ae8", GitTreeState:"clean", BuildDate:"2021-03-10T21:33:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart**: prometheus-pushgateway

**Which version of the chart**: prometheus-pushgateway-1.9.0

**What happened**: version update

**What you expected to happen**: working pushgateway like in version prometheus-pushgateway-1.8.0

**How to reproduce it** (as minimally and precisely as possible):
- deploy prometheus-pushgateway-1.8.0
- upgrade to prometheus-pushgateway-1.9.0

**The helm command that you execute and failing/misfunctioning**:

```
helm upgrade
```

**Anything else we need to know**:
This change causing issues while upgrading the prometheus-pushgateway.
Setting the ClusterIP to None also does not change the behavior.
I think it would be good to add an additional if condition for the clusterIP value in the template like here: https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/templates/controller-service.yaml

**Comment by rxbn** [comment]
i'm also facing the same issue

**Comment by dmitriishaburov** [comment]
Experiencing the same issue too, and can't even rollback helm release:
```helm rollback prometheus-pushgateway
Error: cannot patch "prometheus-pushgateway" with kind Service: Service "prometheus-pushgateway" is invalid: spec.clusterIP: Invalid value: "": field is immutable```

**Comment by mmslkr** [comment]
Still relevant

**Comment by mmslkr** [comment]
Still relevant

**Comment by 0x0badc0de** [comment]
Was able to upgrade chart 1.8.0 to 1.10.1

**Comment by tomfankhaenel** [comment]
It looks like it is fixed in the latest release: prometheus-pushgateway-1.10.1
I will verify and update the ticket.

**Comment by tomfankhaenel** [comment]
prometheus-pushgateway-1.10.1 solved this issue
