### ISSUE TITLE
[kube-prometheus-stack] Deploy grafana dashboards but not grafana itself

### ISSUE THREAD

**Issue by awoimbee** [prometheus-community/helm-charts#921]
**Is your feature request related to a problem? Please describe.**

- I have multiple datasources and it doesn't make sense for Grafana to be bundled with one of them (Prometheus).
- This chart is way too big and slow to deploy, it's horrible when any issue occurs.
- Also, separation of concerns, my Grafana chart handles Grafana and my Prometheus chart handles Prometheus.

But the preconfigured dashboards of this chart are too nice to live without !

**Describe the solution you'd like**
Make it possible to _not_ deploy grafana but still deploy the dashboards and datasources (and notifiers).
Currently not possible because of: https://github.com/prometheus-community/helm-charts/blob/88b387b3ced28cbe4c422c3c440c8ff62d8e3fdb/charts/kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml#L1

To make it not breaking, maybe add something like that to `values.yaml`:
```yaml
grafana:
    forceDeployDatasources: false
    forceDeployDashboards: false
```

**Describe alternatives you've considered**
Ripping out the dashboard from this repo to deploy them myself, but there is too much to rip out and that's not sustainable.

**Additional context**
Grafana isn't a Prometheus only project, there are lots of datasources. So I should not be forced to bundle Grafana  with Prometheus.

What do you think of this ?

**Comment by monotek** [comment]
Would you mind to create an pr for that?

**Comment by awoimbee** [comment]
bumb
I currently don't have much time, but it's in my plans to do a PR (if someone can do it faster that me, don't hesitate !).

**Comment by timbrd** [comment]
> bumb
> I currently don't have much time, but it's in my plans to do a PR (if someone can do it faster that me, don't hesitate !).

I have already worked on that based on your recommendations and just have opened a PR: #1040
