### ISSUE TITLE
[prometheus-kube-stack]  wrong selector on prometheus service

### ISSUE THREAD

**Issue by Leen15** [prometheus-community/helm-charts#938]
Hello,
On a standard install of this helm chart service selectors don't match statefulset deployed, due to an hardcoded label in service definition:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/service.yaml#L54

It doesn't match with the statefulset definition:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L8

so the result is:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: kube-prometheus-stack
    project.cattle.io/namespaces: '["default","kube-prometheus","kube-prometheus-stack"]'
    prometheus-operator-input-hash: "10289447891296225279"
  creationTimestamp: "2021-05-04T16:20:28Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 15.4.2
    chart: kube-prometheus-stack-15.4.2
    heritage: Helm
    io.cattle.field/appId: kube-prometheus-stack
    monitoring.coreos.com: "true"
    release: kube-prometheus-stack
```

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prometheus-stack
    meta.helm.sh/release-namespace: kube-prometheus-stack
  creationTimestamp: "2021-05-04T16:20:27Z"
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 15.4.2
    chart: kube-prometheus-stack-15.4.2
    heritage: Helm
    io.cattle.field/appId: kube-prometheus-stack
    release: kube-prometheus-stack
    self-monitor: "true"
  name: kube-prometheus-stack-prometheus
  namespace: kube-prometheus-stack
  resourceVersion: "2264566"
  uid: 97bfb747-9bab-432a-a60a-6699fd64ef66
spec:
  clusterIP: 10.43.192.143
  clusterIPs:
  - 10.43.192.143
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    io.cattle.field/appId: kube-prometheus-stack
    prometheus: kube-prometheus-stack-prometheus
  sessionAffinity: None
  type: ClusterIP
```  

Service selector will never match and grafana will not be able to connect to prometheus instance.

**Comment by jaanhio** [comment]
hi @Leen15 , 

You should be looking at the Pod labels under the StatefulSet, not the StatefulSet labels itself. 

Also, the file you referenced https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L8 is the CRD for `kind: Prometheus`, it is not the StatefulSet definition.

This is the StatefulSet file which you should be looking at https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/prometheus/templates/server/sts.yaml#L31

That value is actually defined here https://github.com/prometheus-community/helm-charts/blob/1b406181133b5843652ac4685d693edd82600eb6/charts/prometheus/templates/_helpers.tpl#L20

Hope this helps.

**Comment by Leen15** [comment]
Sorry I was wrong.
The main issue is due to Rancher Orchestrator that inject a `io.cattle.field/appId` in the selector of the service, with the result that it doesn't match with pods labels (only with StatefulSet labels).
I will check with them.
