### ISSUE TITLE
[kube-prometheus-stack] prometheus-operator deployment uses deprecated flags

### ISSUE THREAD

**Issue by yurrriq** [prometheus-community/helm-charts#941]
**Describe the bug**
15.4.4 [installs prometheus-operator v0.47.0](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-15.4.4/charts/kube-prometheus-stack/values.yaml#L1543), but [uses the deprecated config-reloader flags](https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-15.4.4/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L73-L74).

**Version of Helm and Kubernetes**: irrelevant

**Which chart**: kube-prometheus-stack

**Which version of the chart**: 15.4.4

**What happened**: deprecated flags

**What you expected to happen**: new flags

**Anything else we need to know**:

> The `--config-reloader-cpu` and `--config-reloader-memory` flags are deprecated and will be removed in v0.49.0. They are replaced respectively by the `--config-reloader-cpu-request`/`--config-reloader-cpu-limit` and `config-reloader-memory-request`/`config-reloader-memory-limit` flags.

Ref: https://github.com/prometheus-operator/prometheus-operator/blob/v0.47.0/CHANGELOG.md

**Comment by monotek** [comment]
Would you mind to create a pr please?
