### ISSUE TITLE
[n/a] Add prometheus-nginx-exporter chart

### ISSUE THREAD

**Issue by caleb15** [prometheus-community/helm-charts#959]
**Is your feature request related to a problem? Please describe.**
We don't use the ingress-nginx chart for ...reasons, so we have our own nginx but that doesn't have provide prometheus metrics out-of-the-box.

**Describe the solution you'd like**
A nginx exporter chart that uses https://github.com/nginxinc/nginx-prometheus-exporter to export nginx metrics in prometheus format.

**Describe alternatives you've considered**
Switching to ingress-nginx

**Additional context**
I'm writing a nginx-prometheus-exporter helm chart, I can open a PR to add it if you want.

**Comment by monotek** [comment]
PR's are always welcome :)
