### ISSUE TITLE
[prometheus-mysql-exporter] serviceMonitor.enabled not work

### ISSUE THREAD

**Issue by Jamlee** [prometheus-community/helm-charts#96]
the prometheus service monitor selector is changed.  mysql-exporter configuration serviceMonitor.enabled is not work

![image](https://user-images.githubusercontent.com/5196641/93176853-78945a00-f764-11ea-97f9-1960174744e8.png)

![image](https://user-images.githubusercontent.com/5196641/93176978-a6799e80-f764-11ea-91e0-de6e0bc6a0c2.png)

**Comment by Jamlee** [comment]
```
helm install mysql-exporter  prometheus-community/prometheus-mysql-exporter -n default  --set mysql.host=200.200.200.160,mysql.port=30036,mysql.pass=123456,serviceMonitor.enabled=true,serviceMonitor.additionalLabels.release=prometheus-stack
```

**Comment by monotek** [comment]
Sorry, i'm not using servicemonitors so i cant help here.
But if i compare it to other charts using servicemonitor it looks good to me.

**Comment by skiley22** [comment]
Try changing it to `serviceMonitorSelector: {}`
