### ISSUE TITLE
[kube-prometheus-stack] etcd Grafana dashboard breaks without "multicluster" enabled with other etcd metrics

### ISSUE THREAD

**Issue by invidian** [prometheus-community/helm-charts#965]
**Describe the bug**
When `kube-prometheus-stack` is deployed e.g. together with `grafana/loki-stack` chart, with the following values:
```yaml
# For grafana/loki-stack
loki:
  serviceMonitor:
    enabled: true
promtail:
  serviceMonitor:
    enabled: true
```

`etcd` Grafana dashboard shows the wrong data, because etcd metrics coming from loki are use instead of ones from `kube-etcd` job.

Setting `.Values.grafana.sidecar.dashboards.multicluster` works, but it adds also fields for all other Kubernetes dashboards, which may not be desired.

There could be a separate option to enable multi-cluster only for etcd or just always enable it, to avoid this confusing scenario.

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}```
```
Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}```
```

**Which chart**: prometheus-community/kube-prometheus-stack

**Which version of the chart**: 15.4.5

**Comment by invidian** [comment]
Not stale :cry:

**Comment by monotek** [comment]
Would you mind to create a pr for that?

**Comment by invidian** [comment]
@monotek do you think it's fine to just always enable multi-cluster for etcd dashboard?

**Comment by monotek** [comment]
As chart default?
Don't think so but i'm not a maintainer of this chart.

**Comment by invidian** [comment]
Created #1132 to address this issue.

**Comment by invidian** [comment]
Not stale.
