### ISSUE TITLE
[prometheus-kube-stack] impossible to install chart

### ISSUE THREAD

**Issue by youbihi** [prometheus-community/helm-charts#99]
**Describe the bug**
I don't manage to install prometheus-kube-stack , and I don't understand why. 
I am on an AWS EC2 instance with Koops and Kubectl.

<img width="759" alt="Capture d’écran 2020-09-15 à 15 49 23" src="https://user-images.githubusercontent.com/5676321/93219142-52be8380-f76b-11ea-82d0-239efa2a1215.png">

**Version of Helm and Kubernetes**:

version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}
Helm Version:

**Which chart**:
prometheus-kube-stack

**Which version of the chart**:
last version

**What happened**:
impossible to install prometheus-kube-stack

**What you expected to happen**:
to install smootly prometheus-kube-stack

**How to reproduce it** (as minimally and precisely as possible):
tape this:
**helm install monitoring prometheus-community/kube-prometheus-stack**

**Comment by EYassir** [comment]
If you're using kops with t2.micro they will not work not enough capacity to handle all object, upgrade the type of instances.
